### ISSUE TITLE
Handling multiple content type parser 

### ISSUE THREAD

**Issue by amitguptagwl** [fastify/help#1]
I'm trying to write a plugin which can handle multiple content types. Hence I'm adding it as
```js
fastify.addContentTypeParser("*", contentParser)
```
Inside the parser I'm handling supported content type only, and calling next so that other parsers should work fine.

```js
if(!isSupportingContentType(req.headers["content-type"])){
   next()
}
```

When I test my parser with supported content-type then it works fine. 
```js
fastify
    .register(plugin, pluginOptions)
    .post(uri, (req, res) => {
      res.send(Object.assign({}, req.body))
    })
```
but I found that fastify with other content type ;

* is not sending any response when content type is "application/json", 
* sends `"{}"` when content type is  "text/plain".

#### Expected
As given in above snippet, it should return the request body back

#### Context

* *node version*: 9
* *fastify version*: 1.0.0-rc.1
* *os*: Ubuntu 17

**Comment by delvedor** [comment]
Hi!
The *catch-all* content type parser should be used only in  particular cases, if you need to add a limited number of content type parsers, just declare them with the `addContentTypeParser` API.
In this way your code will be way faster, because we take care of the "is a supported content type" part.

```js
fastify.addContentTypeParser('text/html', htmlParser)
fastify.addContentTypeParser('multipart/form-data', multipartParser)
fastify.addContentTypeParser('image/jpeg', jpgParser)
```

Currently the json parser is integrated in the framework and there is no way to overwrite that, this because we wrote an extremely optimized parser. But we are working on that.

Regarding the `text/plain` can you paste the code of your parsers?

**Comment by amitguptagwl** [comment]
Thanks for your quick response. Considering your suggestion, here is the [test](https://github.com/NaturalIntelligence/fastify-xml-body-parser/blob/master/test/integration.test.js) file which is failing for `application\json` and `text\plain`. I'm adding parser only to handle XML payload, hence expecting that rest parser must work fine.

```js
it("should not parse if non-xml payload: text/plain", function (done) {
    runFastify(
        null,
        "string",
        "text/plain",
        function(err, response, body){
            expect(body.toString()).toBe("string");
            done()
          }
        )
});

it("should not parse if non-xml payload: application/json", function (done) {
    runFastify(
        null,
        {"valid":"JSON"},
        "application/json",
        function(err, response, body){
            expect(response.statusCode).toBe(200);
            expect(JSON.parse(body)).toEqual({"valid":"JSON"});
            done()
          }
        )
});

:

function runFastify(pluginOptions,reqBody,contentType, verificationCall){
  const fastify = Fastify()
  const uri = "/testuri"
  fastify
    .register(plugin, pluginOptions)
    .post(uri, (req, res) => {
      //console.log("body:",req.body)
      res.send(Object.assign({}, req.body))
    })
  
  fastify.listen(0, (err) => {
    const reqOpts = {
      method: 'POST',
      baseUrl: 'http://localhost:' + fastify.server.address().port,
      headers: {'content-type':  contentType }
    }
    if (err) console.error(err)
    fastify.server.unref()
    const req = request.defaults(reqOpts)
    req({uri: uri, body: reqBody}, verificationCall)
  });
}
```

**Comment by delvedor** [comment]
Why are you using `res.send(Object.assign({}, req.body))`?
I recommend you to read the docs about the [`reply.send`](https://github.com/fastify/fastify/blob/master/docs/Reply.md#send) interface.

ps: as far as I know if you are using the `request` module and you are sending a JSON you can do it in two ways:
1. `body: JSON.stringify(obj)` and `headers: { 'Content-Type': 'application:json' }`
2. `body: obj` and `json: true` option.

**Comment by amitguptagwl** [comment]
Sorry I'm confused. In my understanding `reply` or `res` are nothing but the name of the object calling the same `send` method. I've taken this example from [fastify-formbody](https://github.com/fastify/fastify-formbody/blob/master/test/integration.test.js). So I'm expecting that it should be correct.

**Comment by delvedor** [comment]
> Sorry I'm confused. In my understanding reply or res are nothing but the name of the object calling the same send method. I've taken this example from fastify-formbody. So I'm expecting that it should be correct.

Yes, but I think in that example we are handling just objects, and `Object.assign` create a new object with the body and another object.
In your example you are using `Object.assign` with req.body that can be an object or a string. That's not correct.

> I'm already setting headers: { 'Content-Type': 'application\json' }

Yes, but the body in an object and not a string, you should send the json body as `JSON.stringify`.
See [here](https://github.com/request/request#requestoptions-callback).

**Comment by amitguptagwl** [comment]
Thanks for your kind reply. It fixed the issue for JSON. But in case of `text\plain' 

```js
fastify
    .register(plugin, pluginOptions)
    .post(uri, (req, res) => {
      res.send(req.body)
    })
```

It gives `{"statusCode":415,"error":"Unsupported Media Type","message":"Unsupported Media Type: text/plain"}`

It gives the same response even if I don't register the plugin.

**Comment by delvedor** [comment]
Have you added a `text/plain` content type parser?

**Comment by amitguptagwl** [comment]
No! I was considering that fastify restrict to add parser for `application/json` but handles `text\plain` already.

**Comment by amitguptagwl** [comment]
Considering it doesn't handle `text\plain`, can you please tell me fastify  maintain the list of 3rd party plugins where I can submit mine?

**Comment by delvedor** [comment]
Just submit a pr in our main repo that updates the ecosystem list :)

**Comment by amitguptagwl** [comment]
Great thanks. Do you mean [Ecosystem.md](https://github.com/fastify/fastify/blob/master/docs/Ecosystem.md)?

**Comment by delvedor** [comment]
Yeah.
