### ISSUE TITLE
How to pass a token to the request

### ISSUE THREAD

**Issue by cyberwombat** [fastify/help#10]
#### You have already researched for similiar issues?
yes

#### What are you trying to achieve or the steps to reproduce?

I am trying to decorate the request with the bearer token auth info

```
async function verifyToken (request, reply, done) {
  try {
    const payload = await decodeBearerToken(request.req.headers['authorization'])

    // The identity seems to get set for all requests and I cannot overwrite. How to achieve this?
    if (!request.identity) {
      log.debug('Bearer token decoded', payload)
      this.decorateRequest('identity', payload.id)
    }
    done()
  } catch (e) {
    done(e)
  }
}


  fastify.decorate('verifyToken', verifyToken)

```

#### What was the result you received?

The decorated request is shared among every user/requests. I am not able to overwrite it as it throws. So each user gets logged in as the same user essentially.

#### What did you expect?

That I could attach the token info to the current request.

#### Context

* *node version*: 9
* *fastify version*: 1.1.1
* *os*: Mac

**Comment by Ethan-Arrowood** [comment]
I may be able to give more details later, but for now you may want to look at the fastify-auth and fastify-jwt libraries as I believe they use request decorators.

**Comment by delvedor** [comment]
Hi!
`decorateRequest` enhances the request constructor, not the request itself :)
The correct usage should be:
```js
fastify.decorateRequest('identity', '') // usa the same type you will use later

// if you are using an async hook, there is no need to use `done`
fastify.addHook('preHandler', async (req, reply) => {
  const payload = await decodeBearerToken(request.raw.headers['authorization'])
  // assign the value
  req.identity = payload.id
})

fastify.get('/', (req, reply) => {
  console.log(req.identity)
  reply.send('hello')
})
```

The use of `decorateRequest` is not mandatory, but it will make your code way faster :)

**Comment by cyberwombat** [comment]
Ok that works great. Would love to see that sample/note added to the docs as it was not completely evident for me how to use it correctly. Thank you for the quick response!

**Comment by cyberwombat** [comment]
Yes. I will put something together.

**Comment by cyberwombat** [comment]
fastify/fastify#890
