### ISSUE TITLE
TypeScript questions

### ISSUE THREAD

**Issue by alizahid** [fastify/help#100]
Hey,

A few TypeScript questions.

This is my `index.ts`

```typescript
import fastify from 'fastify'

import { home } from './routes'

const server = fastify()

server.register(home)

server.listen(3000, error => {
  if (error) {
    throw error
  }

  console.log('Listening on 3000')
})
```

And this is my `routes/home.ts`

```typescript
import { FastifyInstance, RouteOptions } from 'fastify'

const home: RouteOptions = {
  method: 'GET',
  url: '/',
  async handler() {
    return {
      hello: 'world'
    }
  }
}

export default (fastify: FastifyInstance, options: any, next: any) => {
  fastify.route(home)

  next()
}
```

*Questions*

1. What are the correct types for `options` and `next`?
2. Where do I define my `body` schema for `POST` requests so I can just `request.body.foo`?

**Comment by alizahid** [comment]
Bump?

**Comment by Eomm** [comment]
Maybe @Ethan-Arrowood know it 💪

**Comment by Ethan-Arrowood** [comment]
Ahh this is tough as I’m currently traveling. I know for a fact V3 fixes this (available under the next branch, alpha release coming by EOY). If you want to do this using v2 tho I believe a generic exists for the body property. You’ll define the type for body via `type BodyT = {}` (you could also use an interface I believe). And then pass that to the generic expression which I think would be for the RouteOptions parameter. 

I’m sorry this response isn’t great, I’m currently away and only have my cell phone to reply! Looking through can be quite difficult.

**Comment by evanshortiss** [comment]
@alizahid you can define them like so using the generics in the [types here](https://github.com/fastify/fastify/blob/master/fastify.d.ts#L271-L283)

The options can be anything you like, it's a generic that extends `RegisterOptions` seen [here](https://github.com/fastify/fastify/blob/master/fastify.d.ts#L540)

Here's an updated version of your code 😄 

```
import { FastifyInstance, DefaultQuery, DefaultParams, DefaultHeaders, RegisterOptions } from 'fastify'
import { Server, IncomingMessage, OutgoingMessage } from 'http';

interface Opts extends RegisterOptions<Server, IncomingMessage, OutgoingMessage> {
  stuff: string[]
}

export default (fastify: FastifyInstance, options: Opts, next: () => void) => {
  type MyBody = {
    name: string 
  }

  fastify.route<DefaultQuery, DefaultParams, DefaultHeaders, MyBody>({
    method: 'GET',
    url: '/',
    handler: async (req) => {
      return {
        hello: req.body.name
      }
    }
  })

  next()
}
```

```ts
import fastify from 'fastify'

import home from './routes'

const server = fastify()

server.register(home, {
    stuff: ['1']
})

server.listen(3000, error => {
  if (error) {
    throw error
  }

  console.log('Listening on 3000')
})
```

As @Ethan-Arrowood says, this gets better in v3 thanks to his hard work and the contributions of others

**Comment by alizahid** [comment]
Thank you. I'll give this a shot and get back soon.
