### ISSUE TITLE
create repository `fastify/fastify-elasticsearch`

### ISSUE THREAD

**Issue by RodrigoDornelles** [fastify/help#1000]
Opensearch support would be interesting, I think the community would help create and implement this.

 * <https://www.npmjs.com/package/@opensearch-project/opensearch>
 * <https://www.npmjs.com/package/@elastic/elasticsearch>
 * <https://github.com/fastify/fastify-elasticsearch>
 * <https://opensearch.org/>

opensearch is a community-driven project with some extra features like improved authentication, ssl, anomaly detection, easier for clusters and many other things in addition to being less obfuscated.

**Comment by Uzlopak** [comment]
It is unclear what you propose

**Comment by RodrigoDornelles** [comment]
> It is unclear what you propose

just create a github repository for elasticsearch, so that it is published in the npm registry.

to be maintained as an official package, I could send a pull request myself, it would be a few things other than [@fastify/elasticsearch](https://github.com/fastify/fastify-elasticsearch).

@Uzlopak  @mcollina

**Comment by metcoder95** [comment]
You can also create your repository and library and submit it as part of the community plugins

**Comment by RodrigoDornelles** [comment]
fastify has a rich ecosystem, it looks interesting as an official project.

**Comment by mcollina** [comment]
So... somebody wants to contribute a `@fastify/opensearch` plugin? I can create a repo if there is a volunteer

**Comment by RodrigoDornelles** [comment]
> So... somebody wants to contribute a `@fastify/opensearch` plugin? I can create a repo if there is a volunteer

Me! :raising_hand:

@mcollina

**Comment by jsumners** [comment]
What is it about the current plugin that prevents it from being used or extended?

**Comment by RodrigoDornelles** [comment]
> What is it about the current plugin that prevents it from being used or extended?

the current plugin would leave you with extra dependencies. _(adding elasticsearch when you use opensearch)_ I also suggested perhaps extending it by leaving it up to the user to choose which database it should work with. https://github.com/fastify/fastify-elasticsearch/issues/108

@jsumners

**Comment by mcollina** [comment]
Here: https://github.com/fastify/fastify-opensearch

**Comment by RodrigoDornelles** [comment]
@mcollina 
I believe it is private (error 404), at the weekend I believe it will be finished!

**Comment by mcollina** [comment]
Then @RodrigoDornelles why don't you start adding it to fastify-elasticsearch to begin with?

**Comment by RodrigoDornelles** [comment]
@mcollina I don't see a problem. That's why I raised the question, I think it would also be good as an improvement to { `@fastify/opensearch` itself.

**Comment by mcollina** [comment]
I've invited you to the org, you should be able to transfer the repo!

**Comment by RodrigoDornelles** [comment]
> I've invited you to the org, you should be able to transfer the repo!

@mcollina There is already a private repository, which I don't have access to, called `fastify-opensearch` and I can't transfer it because of this!


![image](https://github.com/fastify/help/assets/29123479/ea415353-1157-4427-936e-9ced4026fd26)

**Comment by mcollina** [comment]
removed

**Comment by RodrigoDornelles** [comment]
@mcollina transferred!

you can now publish it,

What do you think about making a pull request that automates publishing via github actions, I can add [provenance](https://docs.npmjs.com/generating-provenance-statements) that give greater traceability to the packages, this can be a CI plugin in the repository [fastify/workflows](https://github.com/fastify/workflows) in the future, when I better understand the fastify flow.

**Comment by mcollina** [comment]
Published
