### ISSUE TITLE
How to terminate a session using an administrator user in @fastify/secure-session

### ISSUE THREAD

**Issue by mateusvieites** [fastify/help#1002]
Is there a way to terminate a session? Or maybe list all? Let's say I have a property called 'user':
`request.session.set("me", {"user": user});`
I need to search for the session with the 'user' value of 'mateus' and delete it. The reason is to be able to deactivate someone's session if necessary.

Example of my issue: I have 3 users, Mateus, Nirin, and an administrator user. I need the administrator to be able to deactivate the session for one of them

**Comment by mcollina** [comment]
That's currently not possible with `@fastify/secure-session`. The sessions are stored completely client side. A "quick" solution is to rotate out the secrets, so that the users would need to re-authenticate.

**Comment by mateusvieites** [comment]
I have the problem that:
1 - The login can only be used on one machine; if there are two, then terminate the first login.
2 - The administrator must be able to log out a user.
I need this control to be server-side but saving an authentication cookie on the client.
I was using Redis pointing the cookie secrets as lookup keys for Redis, but it seemed wrong to me. If it's not inconvenient, could you tell me if any of your frameworks would solve this?

**Comment by jsumners** [comment]
Determining what solves your requirements is your responsibility.

**Comment by mateusvieites** [comment]
> Determining what solves your requirements is your responsibility.

Dont be rude. I am asking this, literally for study purposes, in case there is a solution I haven't seen. Anyway, have a good day. 
And thank you, Matteo, for your suggestion. It worked this way :D
