### ISSUE TITLE
fast-json-stringify slow on STR_ESCAPE regex

### ISSUE THREAD

**Issue by cesco69** [fastify/help#1005]
I have a JSON with a lot of strings that take time during the STR_ESCAPE regex evaluation. Some of these strings I know are safe (no need to escape), is there a way to skip regex evaluation in some way?

**Comment by mcollina** [comment]
Not at this time. However a way to do so could be a great addition to the library.
Maybe using a custom keyword in the schema?

**Comment by cesco69** [comment]
mhh yep, I think is a big booster... 

Maybe the "format"?
```json
"name": {
    "type": "string",
    "format": "unescape"
 },
```

**Comment by Uzlopak** [comment]
unescape has already a specific meaning. Lol, it is even a function in javascript 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/unescape

So unescape is not considerable.
I would prefer something like format "as-is" or "raw" or "pass-through"

**Comment by cesco69** [comment]
Side note, why `asStringSmall` is just for string of length 42? and why 42?

**Comment by Uzlopak** [comment]
Up to 42. Why 42? Idk

**Comment by climba03003** [comment]
I though it is just a random picked number for small string.
`42 is the answer to the Ultimate Question of Life, the Universe, and Everything`

**Comment by kibertoad** [comment]
+1 for `passthrough`

**Comment by cesco69** [comment]
I have made a PR https://github.com/fastify/fast-json-stringify/pull/685
