### ISSUE TITLE
Prevent IP Address Spoofing With trustProxy

### ISSUE THREAD

**Issue by Orel-A** [fastify/help#1009]
I'm using Fastify on a Windows Server with iisnode. In web.config I must set `<iisnode enableXFF="true" />` along with trustProxy: true on Fastify init, otherwise request.ip would be null/undefined.

The problem is, while this works fine most of the time, sometimes I can see invalid ips, such as lan ip 10.10.157.14 or ipv6 that should not be possible as the server doesn't have an ipv6 exposed, that ipv6 is 2001:db8:519:7c6d:1bc8:2db0:2481:d4b6 (should also be a lan ip)

Any help is appreciated.

Node version: 18
Fastify version: 4.26.1
OS: Windows Server 2008

**Comment by climba03003** [comment]
It is actually not Invalid IPs.
When using `true` for `trustProxy`, it provides the IP that is the most left-hand side inside `X-Forwarded-*` header.
Which means when some people accessing using proxy or others tools, it may add the Internal IP as one of the hop.

Most of the time, you should set the IP range of the proxy, or how many hop you expected for truxt proxy.

**Comment by Orel-A** [comment]
Thanks for the reply. How can I tell Fastify to give me their public IP instead of their internal IP?

**Comment by climba03003** [comment]
There is no reliable way to get the Public IP.
You should either use trusted IP range or hop number to determine what is the acceptable one.

**Comment by Orel-A** [comment]
> When using true for trustProxy, it provides the IP that is the most left-hand side inside X-Forwarded-* header.
> There is no reliable way to get the Public IP.

I've looked into iisnode, it's always appending the Public IP to the most right-side inside X-Forwarded-For header. This means that I need to change the behaviour of Fastify. So I've looked into the custom trust proxy function, but the arguments passed are address and the number of the hop. This isn't what I need though.

@climba03003 Any ideas?

**Comment by Orel-A** [comment]
Okay, I've found a fix. Just set "trustProxy: 1".
This works because the "proxy-addr" library uses the "forwarded" library which reverses the order.
Still, I don't know if the original "trustProxy: true" is a valid implementation. For all we know, this could be a vulnerability within Fastify.

**Comment by climba03003** [comment]
> Okay, I've found a fix. Just set "trustProxy: 1".

That's is what I means next hop number. You should knows how your infrastructure look like.
Beware the number may differ when you deploy to different environment.
 
 > Still, I don't know if the original "trustProxy: true" is a valid implementation. For all we know, this could be a vulnerability within Fastify.
 
 It is not vulnerable, `true` already said how it behave.
 `true` means it trust all the proxy services. 
 So, even the client internal one is trusted by you and provide you the internal IP.
