### ISSUE TITLE
How to deploy Fastify REST app on windows IIS server? 

### ISSUE THREAD

**Issue by Jitendragit2019** [fastify/help#1016]
## 💬  Request help on deploying fastify rest app on  windows IIS server

We have developed a REST API with using Node JS Fastify framework. All works great when we run through local server. But it get several errors when we deploye on IIS server on windows.

```js
[RangeError: "port" argument must be >= 0 and < 65536]
````

## Your Environment

- *node version*: 21.7.1
- *fastify version*: >=4.20.4
- *os*: Windows
- *any other relevant information*

**Comment by melroy89** [comment]
I assume you didn't set a port..? Maybe share your code regarding Fastify listen.. I suspect you didn't set a fallback value for your port. Are you maybe using some PORT environment variable?

**Comment by Orel-A** [comment]
```
const portNumber = Number(process.env.PORT || 3000);
fastify.listen({ ...(isNaN(portNumber) ? { path: process.env.PORT } : { port: portNumber }), host: '127.0.0.1' });
```
Try this.

**Comment by Fdawgs** [comment]
@Jitendragit2019 I assume you're using [iisnode](https://github.com/Azure/iisnode?tab=readme-ov-file) and have set the [port as the author described](https://tomasz.janczuk.org/2011/08/hosting-nodejs-applications-in-iis-on.html)?

Closing as no example provided.
