### ISSUE TITLE
Testing fastify/multipart file upload without form-data library

### ISSUE THREAD

**Issue by shania-g** [fastify/help#1017]
Hello there.

I would like to add testing to my endpoint which uses `fastify/multipart` to accept a file upload and then writes it to the filesystem.

In the testing directory of this repository I saw that popular `form-data` library is used, however, I think this can also be achieved without it?

What I have come up with, but for some reason does not work:
```ts
const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const filePath = join(__dirname, '../example.jpg')

describe('POST /asset', () => {
        it('should return 201 when the payload is valid', async () => {
            const rawData = readFileSync(filePath, 'binary')

            const body = new FormData()
            const blob = new Blob([rawData])

            body.set('file', blob, 'example.jpg')

            const res = await app.inject({
                method: 'POST',
                url: '/asset',
                payload: {
                    file: body.get('file')
                }
            })

            assert.deepStrictEqual(res.statusCode, 201)
        })
    })
 ```
    
However, this gives me the following error:
```
{"statusCode":400,"code":"FST_ERR_VALIDATION","error":"Bad Request","message":"body/file should be a file"}
```

This is my route definition (I do not think this is relevant, but maybe it could be):
```ts
fastify.post(
        '/',
        {
            schema: {
                consumes: ['multipart/form-data'],
                body: {
                    type: 'object',
                    required: ['file'],
                    properties: {
                        file: { isFile: true }
                    }
                }
            }
        },
        createAsset
    )
```
    
Is there any way to make this testing work?

Thank you very much in advance.

**Comment by climba03003** [comment]
It doesn't work because you didn't provide the proper header.

**Comment by shania-g** [comment]
> It doesn't work because you didn't provide the proper header.

You mean for the inject I should include multipart/form-data as a header?

**Comment by climba03003** [comment]
see https://github.com/fastify/light-my-request/pull/286

If you don't want to use `form-data`, you need to wait until the above PR landed and published.
Otherwise `form-data` package should be the only choice.
