### ISSUE TITLE
How to specify onClose hooks execution order among plugins

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [fastify/help#1018]
## 💬  Question here 

Is there any way to specify which `onClose` (or `preClose`) hooks from each plugin should be executed before the others? I have some plugins that rely on other main plugins in order to execute correctly their `onClose` hooks. 

E.G.: Some plugins need the database plugin in order to perform some cleaning operations on the database before closing the server. If the database plugin gets torn down before the plugin, the database client results disconnected.

## Your Environment

- *node version*: 20
- *fastify version*: >=4.23.2
- *os*: Mac

**Comment by climba03003** [comment]
Currently, no.
But I see the needs of this feature.

**Comment by giovanni-bertoncelli** [comment]
Thank you @climba03003 

If when wrapping the plugin with `fastify-plugin` I specify some `dependencies`, these are respected only on server bootstrap or also on teardown? Or it does not change anything in the latter case?

**Comment by metcoder95** [comment]
It works on startup, not on teardown; the feature seems quite interesting, but it will require to creation of a graph of plugins for its dependency mapping.
I believe this can be implemented within `fastify` but its something that `avvio` might get some benefit from

**Comment by giovanni-bertoncelli** [comment]
Thank you @metcoder95. If this feature can be interesting, what would be the next steps?

**Comment by metcoder95** [comment]
A PR drafting the idea will be very welcomed

**Comment by giovanni-bertoncelli** [comment]
> A PR drafting the idea will be very welcomed

Fastify or avvio?

**Comment by metcoder95** [comment]
I'd suggest `fastify` first but we can re-take it from there and evaluate where it might have more sense

**Comment by giovanni-bertoncelli** [comment]
Ok, maybe first I can file an issue in fastify? I have no idea where to start with the PR

**Comment by metcoder95** [comment]
Oh, good call; I thought we were in `fastify`, now I see we are on `help`, sorry. Let me transfer refer an issue there

**Comment by metcoder95** [comment]
Closing in favor of https://github.com/fastify/fastify/issues/5375
