### ISSUE TITLE
fastify-websocket schema validation

### ISSUE THREAD

**Issue by Extarys** [fastify/help#102]
You have been so helpful in the past, so here I am.

I have a route that serve HTTP and websocket connections. It works great. I would like to use the build-in validator to validate the object received no matter if it's through http or websocket.
```
fastify.route({
        method: 'GET',
        url: '/v1/testhybrid',
        handler: (request, reply) => {
          myfunction("http", request, reply)
        },
        wsHandler: (conn, request) => {
          conn.setEncoding('utf8')
          // **message need validation**
          conn.socket.on('message', async message => {
            myfunction("ws", conn, request, message)
          })
 }})
```

I never really had to use ws before and I just started using schema validation in fastify. Tips are welcome.

**Comment by mcollina** [comment]
That would be an handy feature for fastify-websocket, would you like to send a PR?

**Comment by Extarys** [comment]
I would love to but my lack of knowledge would make it so it'll be available in a year :P
Can I access the AJV instance from fastify and plug my `message` object in the schema?

**Comment by mcollina** [comment]
You should be able to access the schema definition (what is passed to the route) in https://github.com/fastify/fastify-websocket/blob/462d5510b8e7aa22e6e9bd62a718fa2791534e51/index.js#L29. I'm not sure who a the actual validator for the route could become available to a websocket.
