### ISSUE TITLE
route with params and open/close paren 

### ISSUE THREAD

**Issue by xpr0gamers** [fastify/help#1020]
Hello,

what is the correct path pattern for the url:

![request](https://github.com/fastify/help/assets/25172624/64320baa-6f8e-4687-88b2-92cbc9136bc1)

http://localhost:3000/odata/reifen-srv/Reifen(sId=04bebdad-b27c-463e-9cad-ff9b91edb532,IsActiveEntity=true)

The url is an odata v4 url, which is described [here](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_URLsforRelatedEntitieswithReferentia).
I tried this path pattern and it's not working (404). I think the open/close paren are interpreted as regex.
Do i need do mask the open/closen paren?
![requestRoute](https://github.com/fastify/help/assets/25172624/c176a84a-3f4b-4cef-9ec5-11df0be9c5b2)

**Comment by climba03003** [comment]
You added one more slash in between.

![image](https://github.com/fastify/help/assets/23028015/c3e4fe78-7460-4ab3-aa3d-c25496cdc727)

**Comment by xpr0gamers** [comment]
Hello @climba03003,

thank you very much for your quick reply and your effort. 
So dumb ....

**Comment by climba03003** [comment]
Also note the `(.*)` behind `:sId` and `:isactiveEntity`. It is required to determine the start and end of param.
