### ISSUE TITLE
Help: Reason for the major version bump on fastify-swagger-ui

### ISSUE THREAD

**Issue by hardillb** [fastify/help#1021]
## 💬  Question here 

Can you explain the major version bump (2.1.0 to 3.0.0) in the last fastify-swagger-ui release?

I can't see any breaking changes in the included commits

https://github.com/fastify/fastify-swagger-ui/releases/tag/v3.0.0

And there is nothing in the release notes about a breaking change.

Thanks

**Comment by climba03003** [comment]
In the PR https://github.com/fastify/fastify-swagger-ui/pull/115, it is using the `v4` workflow which means it drops support on certain version of `Node.js`.

**Comment by climba03003** [comment]
I have updated the release notes for the reason.
