### ISSUE TITLE
trying understand how fastify handles db connections

### ISSUE THREAD

**Issue by punkish** [fastify/help#1023]
I have a fastify+SQLite3 application using [better-sqlite3](https://github.com/WiseLibs/better-sqlite3/issues) and my own [fastifyBetterSqlite3](https://github.com/punkish/fastify-better-sqlite3) plugin. In my `app.js` I have the following code

```js
import fastifyBetterSqlite3 from '@punkish/fastify-better-sqlite3';
import { initDb } from './lib/dbconn.js';
const db = initDb();
const fastifyBetterSqlite3Opts = {
        "class": db.class,
        "connection": db.conn
};
```

As I understand the order of how things happen -- 

1. fastify starts
2. `initDb()` is imported from my external db connection file which is used to create a new `db` instance
3. fastifyBetterSqlite3Opts is initialized with this external db connection and is registered with fastify
4. As long as the fastify app or node is not restarted, this single fastifyBetterSqlite3Opts remain active for the entire life of the fastify application

My question is -- is my understanding above correct? And, if yes, are the following assumptions true?

The same db connection is used for all incoming web requests even if they are coming from different clients.

If I create a TEMP table in SQLite, that TEMP table remains visible to all the subsequent requests until the table is dropped.

If a SQLite query takes a long time, all subsequent queries are backed up as well.

Is there a better (canonical) way of doing this? Obviously, I would rather not recreate a new db connection for every single request. On the other hand, I'd rather not suffer from the possible drawbacks noted in my above assumptions, if true.

Many thanks in advance for any guidance.

**Comment by mcollina** [comment]
> My question is -- is my understanding above correct? And, if yes, are the following assumptions true?

Mostly

> The same db connection is used for all incoming web requests even if they are coming from different clients.

Yes

> If I create a TEMP table in SQLite, that TEMP table remains visible to all the subsequent requests until the table is dropped.

Yes

> If a SQLite query takes a long time, all subsequent queries are backed up as well.

No. Better-sqlite3 operates synchronously. So it's the main thread that is blocked.
The only caveat are transactions, which are slightly harder to manage if you need to perform an asynchronous operation inside it. I've created https://github.com/mcollina/sqlite-pool to deal with it.

> Is there a better (canonical) way of doing this? Obviously, I would rather not recreate a new db connection for every single request. On the other hand, I'd rather not suffer from the possible drawbacks noted in my above assumptions, if true.

That's how better-sqlite3 operates. You'll need more node.js processes to counterbalance the drawbacks.

**Comment by punkish** [comment]
Thanks for your super-helpful response. Naturally, this leads me to the following --

> No. Better-sqlite3 operates synchronously. So it's the main thread that is blocked.

That implies that there are other threads besides the *main* thread (I must confess, I know very little about "threads").

> You'll need more node.js processes to counterbalance the drawbacks.

Does this mean I should consider starting multiple instances of my node.js + fastify application? For one, each would be on a different port, and I would need some kind of port balancer so that external users continue to visit `http://myapplication/` without worrying about port numbers. Second, that would require as many times more CPU and memory as my current single node.js + fastify process takes. And finally, each process would have its own db connection which would be oblivious of the other connections.

Ideally, what I would want is a single db connection that shares db and memory, but responds to each request independently of other requests so one slow request doesn't block others. I guess I am asking too much from SQLite…

**Comment by mcollina** [comment]
> Ideally, what I would want is a single db connection that shares db and memory, but responds to each request independently of other requests so one slow request doesn't block others. I guess I am asking too much from SQLite…

Yes, you are.
