### ISSUE TITLE
400 Bad Request when content-length is set 0 and body is getting sent in post request

### ISSUE THREAD

**Issue by abhinavgautam07** [fastify/help#1025]
#### You have already researched for similar issues?
Yes already researched.

#### What are you trying to achieve, or the steps to reproduce?

I am migrating my server from express to fastify, in the express server, when i set the headers content-type: application/json, content-length:0, and send some body. It used to parse the body as {} and rest of the code works fine. But in fastify I am getting 400 bad request error.
Describe your issue here, include as many details as necessary to reproduce the issue, 
or implement a missing functionality. If you are reporting a bug, you will get a faster response 
if you submit a pull request with a failing test.

you can try this curl on any fastify server

curl --verbose --location 'http://localhost:8000/getUsers
--header 'Accept: application/json' \
--header 'content-length: 0' \
--header 'Content-Type: application/json' \
-X POST \
--data '{
    "username": "abhinav"
}'

#### What was the result you received?

Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying [::1]:2756...
* Connected to localhost (::1) port 8000
> POST /getUsers HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/8.4.0
> Accept: application/json
> content-length: 0
> Content-Type: application/json
> 
< HTTP/1.1 400 Bad Request
< Connection: close
< 
* Closing connection

#### What did you expect?

200 OK response

#### Context

how fastify handles content-length. Once I remove the content-length header, everything seems to be working fine. Issue is in content-length header only. But If i go on correcting this for all the clients, migration will become very tedious. 

* *node version*: 14.18.0
* *fastify version*: >=0.37.0
* *os*: Mac

**Comment by metcoder95** [comment]
Hey! Can you provide an 
[Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) that we can use?

**Comment by mcollina** [comment]
This behavior is expected. The content-length must match the length of the body.
