### ISSUE TITLE
Cannot read properties of undefined (reading 'getAccessTokenFromAuthorizationCodeFlow')

### ISSUE THREAD

**Issue by clubside** [fastify/help#1035]
#### You have already researched for similar issues?
I have done a bunch of searching but nothing in particluar comes up for this basic error.

#### What are you trying to achieve, or the steps to reproduce?

I'm trying to implement login with Google using the oauth2 plugin and the code in the [Google example](https://github.com/fastify/fastify-oauth2/blob/master/examples/google.js). The login page displays fine but after choosing a Google account it throws an error in the callback handler.

```js
app.register(oauthPlugin, {
	name: 'googleOAuth2',
	scope: ['profile', 'email'],
	credentials: {
	  client: {
			id: '** my client id **',
			secret: '** my secret **'
	  },
	  auth: oauthPlugin.GOOGLE_CONFIGURATION
	},
	startRedirectPath: '/login/google',
	callbackUri: 'http://localhost:3950/api/auth/google/callback'
})
app.get('/api/auth/google/callback', async (request, reply) => {
	this.googleOAuth2.getAccessTokenFromAuthorizationCodeFlow(request, async (err, result) => {
		if (err) {
			reply.send(err)
			return
		}
		const response = await fetch('https://www.googleapis.com/oauth2/v2/userinfo', {
			method: 'GET',
			headers: { Authorization: `Bearer ${result.token.access_token}` }
		})
		if (response.ok) {
			const data = await response.json()
			reply.send(data)
		} else {
			reply.send(response.status)
		}
		return response.json()
	})
})
```

#### What was the result you received?
 `{"statusCode":500,"error":"Internal Server Error","message":"Cannot read properties of undefined (reading 'getAccessTokenFromAuthorizationCodeFlow')"}`

#### What did you expect?
At this point I don't know, but `result.token.access_token` at the very least.

#### Context

* *node version*: 22.3.0
* *fastify version*: 4.28.1
* *oauth2 version*: 7.8.1
* *os*:  Windows

**Comment by Eomm** [comment]
1) first error: you can't use `this` with arrow functions in this case.

```diff
-app.get('/api/auth/google/callback', async (request, reply) => {
+app.get('/api/auth/google/callback', async function (request, reply) {
	this.googleOAuth2.getAccessTokenFromAuthorizationCodeFlow(request, async (err, result) => {
```


2) it seems a duplicate of https://github.com/fastify/fastify-oauth2/issues/236

**Comment by clubside** [comment]
Thanks so much, that makes sense. I switched to Fastify Passport which worked fine using their example but I prefer this library’s design so I will use your fix for my next project.
