### ISSUE TITLE
JavaScript file executed twice when using `pino/file` transport with `--import` option

### ISSUE THREAD

**Issue by richterich** [fastify/help#1049]
## 💬  Question

When using the `pino/file` transport with the `--import` option to include a JavaScript file, the file is executed twice instead of just once. This behavior looks as unexpected and can lead to issues such as duplicated log entries or other side effects from the script running twice. Should I report an issue or is there a solution for this problem?

To reproduce this issue, please, create fastify instance with following options:
```js
// index.js
const app = fastify({
  logger: {
    level: 'debug',
    transport: {
      target: 'pino/file',
      options: { destination: './tmp/app.log', mkdir: true },
    },
  },
});

app.listen({ port: 8080, host: '127.0.0.1' }, (err, address) => {
  if (err) {
    instance.log.error({ err, address }, 'Server Start Error');
    process.exit(1);
  }
});

console.log("once");
````
Create another module with the following code:
```js
// twice.js
console.log("twice");
```
Run application with command:
```bash
node --import=./twice.js index.js
```
Actual output:
```bash
twice
once
twice
```
Expected output:
```bash
twice
once
```

Please, see the [repo](https://github.com/richterich/pino-twice) to reproduce the problem.

## Environment

- *node version*: 20.16.0
- *fastify version*: 4.28.1
- *os*: Linux 6.5.0-45-generic Ubuntu 22.04.1

## Additional

As workaround it possible use `true` in logger options or don't use the `transport` option in logger options.
```js
// use boolean value
const app = fastify({
  logger: true
});

// without transport option
const app = fastify({
  logger: {
    level: 'debug',
  },
});
```

**Comment by climba03003** [comment]
It is more like an issue from `pino` or `node.js` itself.

**Comment by jsumners** [comment]
Pino does not modify `console.log`. Nothing in the report is due to Fastify nor Pino. `--import` loads the designated script in a separate thread. There must be something omitted from `index.js` that shows where it is _also_ importing `twice.js`.

**Comment by climba03003** [comment]
I think the issue is related to the usage of `Worker`. but I cannot find a way to reproduce with just `Worker` right now.

```js
import pino from 'pino';
pino({
  level: 'debug',
  transport: {
    target: 'pino/file',
    options: { destination: './tmp/app.log', mkdir: true },
  },
});
```

**Comment by climba03003** [comment]
Here is the minimal repro with file creation.
The `--import` script will be run in every `Worker` creation. If that is not the desire behavior, you should file an issue to `node` repository.

```js
import { spawn } from 'node:child_process';
import { rm, writeFile } from 'node:fs/promises';

await writeFile('main.mjs', `
import { rm, writeFile } from 'node:fs/promises';
import { Worker } from 'node:worker_threads';

await writeFile('worker.mjs', \`console.log('worker')\`)

const stream = new Worker('./worker.mjs')

process.once('beforeExit', () => {
  rm('worker.mjs')
})`)

await writeFile('import.mjs', `console.log('import')`)

spawn('node', ['--import', './import.mjs', 'main.mjs'], {
  stdio: 'inherit'
})

process.once('beforeExit', () => {
  rm('main.mjs')
  rm('import.mjs')
})
```

**Comment by richterich** [comment]
Thank you!
