### ISSUE TITLE
Migrating a ready project from another framework

### ISSUE THREAD

**Issue by frodoe7** [fastify/help#105]
## 💬 Questions and Help

My project already built on a framework called [Actionhero](https://www.actionherojs.com) , for some reasons I found this framework is not suitable and has many issues.

Now , I'm planning to migrate my ready project to Fastify.

As there's no a magical button to do this step , I have to make this step manually , this require studying the structure of both frameworks.

some modules will need some light extra work like (routes , mongoose models and so on ..) - different syntax

The following 2 modules maybe a challenge for me ( **I need help in these modules** )

-   Tasks : my project core depends on scheduled tasks which I implemented it very well using the other framework ( [Action Hero Tasks](https://docs.actionherojs.com/tutorial-tasks.html) )

I did not find any helper or plugin in Fastify to help with the tasks / scheduler
I may have to use a separated node package to handle something like this , like Bull , Agenda and so on .. any comment ?

-   Middlewares : in ( [Actionhero Middlewares](https://docs.actionherojs.com/tutorial-middleware.html) ) , I assign multiple middlewares to a certain route and each one passes through 2 steps preProcessor before handling the request and postProcessor after handling the request - in the other side I looked into ( [Fastify Middlewares](https://www.fastify.io/docs/latest/Middlewares/) ) and ( [Fastify Lifecycle](https://www.fastify.io/docs/latest/Lifecycle/) ) , I could not reach to the same architecture or to know how to migrate this part ? - looks these Lifecycle events are global not for each route.

for example , I have this ENDPOINT GET /api/getUserId
and 2 middlewares ["authMiddleware","anotherMiddleware"]

`assign(["authMiddleware","anotherMiddleware"] , "GET /api/getUserId"); // how to make something like this in Fastify , and each middleware should have 2 functions to run before and after handling the request`

The purpose of this study to finish this migration process fast , as the project is delayed too much.

**Comment by Eomm** [comment]
> I may have to use a separated node package to handle something like this , like Bull , Agenda and so on .. any comment ?

I think there aren't plugins of this use case, you could build it or open an issue as "plugin request".

I think a scheduled task is a batch, and I don't like to put this kind of processing in an HTTP server: you are stealing resources and throughput on your server.
I used Bull and it is a solid and a simple to use, I think a dedicated node process that does these king of tasks is the best choice (and the HTTP server ask only for task, doesn't execute them -the plugin-)

> I could not reach to the same architecture or to know how to migrate this part ? 

Absolutely you can do it.
You are looking for this:
https://github.com/fastify/fastify/blob/master/docs/Routes.md#full-declaration
`preHandler` and `preSerialization`

Consider that if the `authMiddleware` is always the same for all the routes, you can use a [hook](https://github.com/fastify/fastify/blob/master/docs/Hooks.md#preHandler) in your context

**Comment by frodoe7** [comment]
Thanks @Eomm for replying , that's help
