### ISSUE TITLE
Request for Inclusion of a Template Engine in the Fastify/View List

### ISSUE THREAD

**Issue by shari-ar** [fastify/help#1052]
Dear @fastify/view contributors,

I am writing to request the inclusion of a template engine I have developed in the Fastify/View list.

For your reference, I have provided the website address for the template engine below. Should you require further information, please do not hesitate to contact me.

Thank you for considering my request.

Sincerely,
Shahriyar G.

Template Engine Website Address: [frontobjectsjs](https://frontobjectsjs.com)

**Comment by mcollina** [comment]
That website is not loading

**Comment by shari-ar** [comment]
The site opens, but it might take a little longer than usual — around 5 or 6 seconds. I apologize for this inconvenience and will work on resolving it as soon as possible. Thanks for your patience!

Other links: [GitHub](https://github.com/shari-ar/frontobjectsjs) and [npm](https://www.npmjs.com/package/frontobjectsjs)

**Comment by mcollina** [comment]
Thanks, but this is really not popular enough to be included.
