### ISSUE TITLE
Understand how to use Fastify plugin

### ISSUE THREAD

**Issue by SkyTik** [fastify/help#1056]
#### What are you trying to achieve, or the steps to reproduce?

I'm studying Fastify and register plugin with @fastify/redis like this

```
app.register(redisPlugin, {
  client: initRedis(app.config.REDIS_INTERNAL__HOST, app.config.REDIS_INTERNAL__PASS),
  closeClient: true,
});

```

And register route:

```
import { FastifyInstance, FastifyPluginAsync } from "fastify";

import v1Routes from "./v1/index.js";

const routes: FastifyPluginAsync = async (fastify: FastifyInstance): Promise<void> => {
  fastify.register(v1Routes, { prefix: "/v1" });
};

export default routes;
```

and inside v1 route

```
const v1Routes: FastifyPluginAsync = async (fastify: FastifyInstance): Promise<void> => {
  fastify.register(seedlogsRoutes, { prefix: "/seedlogs" });
};

```
route with controller
    
 ```
const orderRoutes: FastifyPluginAsync = async (fastify: FastifyInstance) => {
  fastify.get("/", getOrders);
};

export default orderRoutes;
```

with **getOrders** function, I can access Redis like this:

```
const getOrders = async (request: FastifyRequest, reply: FastifyReply) => {
  const redis = request.server.redis;
  await redis.set("orders", "abc");
  const orders = await redis.get("orders");
  return { message: "Orders", orders };
};

```
But what if I want to access Redis from an inner service, how can I access Redis from the 
**FastifyInstance**, like

```
const cacheOrder = async (order) => {
  await redis.set("order",order)
}
```

Should I init a client before passing it to the plugin and reuse it wherever does not have access to the FastifyInstance?

`import redis from "./cache/redis.js"`

I searched on Google but still can not find any satisfactory answer.
Many thanks

#### Context

* *node version*: 20.14.0
* *fastify version*: 4.28.1
* *os*: Mac

**Comment by metcoder95** [comment]
What do you mean exactly with an inner service?

When decorating a `FastifyInstance`, you can access the different decorations through the `this` context of the decoration.

Then, you can do things like:
```js
fastifyInstance.decorate('service', function (..args) {
  await this.otherDecorator();
  // do your thing
})
```

So the reference to the main `fastifyInstance` is preserved and you can use it across decorators.

**Comment by SkyTik** [comment]
my flow is Route -> Controller -> Service, the Controller look like this

```
const getOrders = async (request: FastifyRequest, reply: FastifyReply) => {
  const redis = request.server.redis;
  await redis.set("orders", "abc");
  const orders = await redis.get("orders");
  return { message: "Orders", orders };
};
```

I can easily access the **Redis** via **server**, now I want to modify the Controller into this

```
const getOrders = async (request: FastifyRequest, reply: FastifyReply) => {
  const order = request.body;
  const newOrder = await createOrder(order);
  await cacheOrderDetail(order)
  return { message: "Orders", orders };
};

const cacheOrderDetail = (order) => {
 // how can I access Redis in this function
}
```

In Express, I only need to import the Redis client.

**Comment by metcoder95** [comment]
I'd say that it is mostly up to you; you can also import and reference it there directly, or follow a Dependency Injection pattern.

```js
fastify.decorate('cacheOrderDetail', cacheOrderDetail(fastify.redis));

// later in code

fastify.cacheOrderDetail(order);
```

It will depend on what methodology, or principles are you following within your application folder structure

**Comment by SkyTik** [comment]
Still I do not understand why I need plugin if I can import the client directly in code

**Comment by climba03003** [comment]
We are not restricting developer to use the plugin, you can use the controller just like normal import.

The benefit of plugin is that,
1. Database / Resource is managed inside a single place and binded to the application lifecycle.
2. Ensure the singleton of instance

I knows that you can achieve it with many different way.
The plugin only offer you one of the solution.

**Comment by SkyTik** [comment]
Thank you, I'm looking into DI to achieve my purpose.
