### ISSUE TITLE
'FST_ERR_CTP_INVALID_MEDIA_TYPE'

### ISSUE THREAD

**Issue by vinnycosta1998** [fastify/help#1059]
I need to send images to the backend and I still have the same problem 'FST_ERR_CTP_INVALID_MEDIA_TYPE', I have already installed @fastify/muiltipart and configured it in the application, below is how I did it

<img width="1021" alt="Screenshot 2024-09-21 at 15 05 11" src="https://github.com/user-attachments/assets/ebce252d-ae81-44d5-ad1b-aa29350fe72c">

<img width="879" alt="Screenshot 2024-09-21 at 15 06 01" src="https://github.com/user-attachments/assets/f131d990-b9a7-4485-82dc-7270b68fe1ce">

<img width="1177" alt="Screenshot 2024-09-21 at 15 07 18" src="https://github.com/user-attachments/assets/84b9e766-26a6-49d6-bd17-f34272837cec">

**Comment by climba03003** [comment]
Since there's no runnable code provided, I guess you can try to place the `appRoutes` to the bottom.
It depends, but sometimes order of registration is important.

**Comment by vinnycosta1998** [comment]
Seriously, I did what you wrote and solved this problem, thanks bro.
