### ISSUE TITLE
Fastify sendFile async support?

### ISSUE THREAD

**Issue by markrzen** [fastify/help#106]
#### You have already researched for similar issues?

Yep. I may have missed something though. Hopefully not.
Closest I could come to is:
https://www.fastify.io/docs/latest/Routes/#promise-resolution

#### What are you trying to achieve or the steps to reproduce?

When trying to use async style routes and `sendFile` from `fastify-static`, the results properly goto the client, but a `Promise may not be fulfilled with 'undefined'...` is logged.

```js
  fastify.get('/', async (request, reply) => {
    reply.sendFile('/html/index.html');
  });
```

#### What was the result you received?

```
err: {
      "type": "FastifyError",
      "message": "FST_ERR_PROMISE_NOT_FULLFILLED: Promise may not be fulfilled with 'undefined' when statusCode is not 204",
...
}
```

#### What did you expect?

No logged error.

#### Context

* *node version*: `12.7.0`
* *fastify version*: 2.8.0
* *os*: OSX

**Comment by RafaelGSS** [comment]
I tried to reproduce your error, but everything worked. Can you provide a full code example?

**Comment by markrzen** [comment]
Sure, standby. Will type it up. Thanks for the help.

**Comment by markrzen** [comment]
@RafaelGSS 
```js
const path = require('path');
const fastify = require('fastify');
const static = require('fastify-static');

const {
  LOG_LEVEL: level = 'info',
  NODE_ENV: env,
  NODE_PORT: port = 8080,
  NODE_HOST: host = '0.0.0.0'
} = process.env;

const isDevelopment = (env !== 'production');

const server = fastify({ logger: true });

server.register(static, {
  root: path.join(__dirname, '..', 'common', 'static'),
  prefix: '/assets/'
});

server.get('/', async (request, reply) => {
  reply.sendFile('/html/index.html');
});

const start = async () => {
  try {
    await server.listen(port, host);
  } catch (err) {
    server.log.error(err);
    process.exit(1);
  }
}

start();
```

**Comment by StarpTech** [comment]
Hi @markrzen this is intentional and described here https://github.com/fastify/fastify/blob/master/docs/Routes.md#promise-resolution

**Comment by markrzen** [comment]
@StarpTech I did read that, but it doesn't quite make sense.

It says we can use reply.send (I assume sendFile included), as long as we don't return. Then it states you can't return undefined.

Are you saying if we want to use `async/await` we will have to tolerate these false-positive Errors?

**Comment by StarpTech** [comment]
You're right. It took some time to understand the example. You example is fine and it looks like a bug @mcollina

**Comment by markrzen** [comment]
Ah drat. I was hoping it wasn't a bug and I was doing something dumb.

I will have a peek and see if I can find the source.

**Comment by StarpTech** [comment]
@markrzen in case of callback-style it's stable ?

**Comment by markrzen** [comment]
@StarpTech Not sure, I may have to switch to that, it's just not my preferred style.

**Comment by StarpTech** [comment]
I can reproduce it with the `example` in fastify-static

```js
'use strict';

const path = require('path');
const fastify = require('fastify')({ logger: { level: 'trace' } });

fastify
  .register(require('../'), { root: path.join(__dirname, '/public') })
  .get('/', async (request, reply) => {
    reply.sendFile('index.css');
  });

fastify.listen(3000, err => {
  if (err) throw err;
});

```

**Comment by StarpTech** [comment]
It's a race condition. I could fix it by wrapping the entire [code](https://github.com/fastify/fastify-static/blob/master/index.js#L37-L98) in a promsie and resolve and reject in the appropriate cases. Then you can use

```js
fastify
  .register(require('../'), { root: path.join(__dirname, '/public') })
  .get('/', async (request, reply) => {
    await reply.sendFile('index.css');
  });
```

**Comment by markrzen** [comment]
@StarpTech To answer your previous question, pure callback style does work. The downside is I like the `setErrorHandler` behavior with `async`, instead of the `callback` behavior of process.exit.

**Comment by RafaelGSS** [comment]
> It's a race condition.

Why is the race condition? the fastify static does not send stream?

**Comment by StarpTech** [comment]
It does but the async handler is proceed before the stream was sent. The reason is that `sendFile` wasn't implemented to support async control flow.

**Comment by markrzen** [comment]
@StarpTech Should I move this over to the fastify-static project as a bug report? At the moment, I have switched to just streaming the file contents per request.

**Comment by StarpTech** [comment]
@markrzen yes

**Comment by markrzen** [comment]
Moved to https://github.com/fastify/fastify-static/issues/110
