### ISSUE TITLE
Instantiating synchronous pino-pretty logger with fastify 5

### ISSUE THREAD

**Issue by kibertoad** [fastify/help#1060]
## 💬  Question here 

Previously this was the way to instantiate a synchronous pino-pretty logger (which is very convenient for tests):

```ts
import pretty from 'pino-pretty'

    const logger = pino(
      pretty({
        sync: true,
        minimumLevel: appConfig.logLevel as Level,
        colorize: true,
        translateTime: 'SYS:standard',
        ignore: 'hostname,pid',
      }),
    )

  const app = fastify({
    logger
  })
```

Unfortunately, this no longer works, because fastify 5 only supports logger configuration but not preinstantiated logger. How does one use pino-pretty while still respecting the `sync` attribute now?

## Your Environment

- *node version*: 20
- *fastify version*: >=5.0.0

**Comment by mcollina** [comment]
Use `fastify({ loggerInstance: logger })` This is mentioned in the migration guide.

**Comment by kibertoad** [comment]
thank you!
