### ISSUE TITLE
Studying Fastify Core

### ISSUE THREAD

**Issue by jean-michelet** [fastify/help#1063]
I contribute to core plugins and some components around the Fastify ecosystem for a couple of months. I also work on the official demo.

I now want to go further and study Fastify's Core to help you but also to be a better plugin's and demo contributor. What's your advice? Take one issue and find out as you go along? Are there any useful resources in addition to the official documentation?

My initial idea was to install the project, read the code and try to create a mini-fastify repo to understand how the main components work together. One of the TypeScript maintainers created [this repo](https://github.com/sandersn/mini-typescript) to help to understand the compiler and it did help me to contribute back then, so I think it might be a good idea to have one too if doable.

**Comment by mcollina** [comment]
I would recommend just start solving issues ;).

**Comment by simoneb** [comment]
I would suggest to close this issue as there is no further follow up required.
