### ISSUE TITLE
Add support for overriding request/response access logging `message`

### ISSUE THREAD

**Issue by markrzen** [fastify/help#107]
## 🚀 Feature Proposal

Allow for the overriding of request/response logging `message` via function (`(req) => {}`) or string.

## Motivation

In stackdriver `message` is a preview of the log event. Providing a more meaningful message would be very helpful.

E.g. `Request Incoming GET /blah 200`

### Application
```js
fastify({
  reqLogMsg: (req) => { return `incoming request: ${req.url}`}
  resLogMsg: (res) => { return `outgoing response: ${res.statusCode}`}
});
```

### fastify
```js
childLogger.info({ req }, reqLogMsg(req))
```

**Comment by Eomm** [comment]
I think you can do it.
You need to customize the serializer of the logger: https://github.com/fastify/fastify/blob/master/docs/Logging.md

**Comment by jsumners** [comment]
In particular, see https://github.com/fastify/fastify/blob/80ddb4ea2dddef828b5c366516b522f19b48e4f0/docs/Server.md#disablerequestlogging

**Comment by markrzen** [comment]
Oh brilliant! Thanks y'all!
