### ISSUE TITLE
Why does the Web Frameworks Benchmark report HTTP Errors for Fastify?

### ISSUE THREAD

**Issue by tomekt-bolt** [fastify/help#1073]
#### You have already researched for similar issues?
It's not uncommon that somebody already opened an issue or in best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/fastify/fastify/issues) at first before submitting a new one.

#### What are you trying to achieve, or the steps to reproduce?

I'm considering migrating a project to Fastify. I've noticed that on the [Web Frameworks Benchmark](https://web-frameworks-benchmark.netlify.app/result?l=javascript) page, Fastify is indicated to return HTTP Errors during the benchmark.

Is there a known reason for this? Is this related to some _actual_ limitations of Fastify under high load, or is the benchmark somehow irrelevant? 

#### What was the result you received?
Benchmark indicated HTTP Errors for Fastify

#### What did you expect?
I expected no HTTP Errors for Fastify

#### Context

* *node version*: v23.3.0
* *fastify version*: 5.1.0
* *os*: Linux

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by jsumners** [comment]
Have you asked whoever created and maintains that suite?

**Comment by tomekt-bolt** [comment]
I haven't. Since the benchmark seems quite popular, I hoped that maybe it's a known topic for the Fastify community.

**Comment by jsumners** [comment]
I can say that I haven't ever seen it before.

**Comment by mcollina** [comment]
I'm not sure what they are doing, but they seem to be benchmarking the error path and not the actual request flow.

**Comment by tomekt-bolt** [comment]
Thanks @mcollina! Just for reference - I've also opened an issue on the benchmark project, following @jsumners suggestion: https://github.com/the-benchmarker/web-frameworks/issues/8038.

**Comment by waghanza** [comment]
Thanks @tomekt-bolt for this report. The results will be updated on monday with the fix made by @mcollina

**Comment by climba03003** [comment]
Closing as the issue resolved.
