### ISSUE TITLE
express.js compatibility 

### ISSUE THREAD

**Issue by aung-san-i** [fastify/help#113]
Can I use express.js module with this FW? 

Such as: 

https://www.npmjs.com/package/express-uws
https://github.com/jaredhanson/passport

Many Thanks

**Comment by Ethan-Arrowood** [comment]
Hello, 

Fastify v2 supports most express modules. However, I would recommend using a Fastify equivalent. You can find our collection of modules at https://www.fastify.io/ecosystem/

**Comment by aung-san-i** [comment]
For sure I am going to use fastify modules. Just in case if there is none. 
Thanks for info.
