### ISSUE TITLE
Fastify freezing

### ISSUE THREAD

**Issue by hashtriton** [fastify/help#114]
Hello everyone, I apologize immediately for my English.

There was a problem with the intermittent freezing of the API on fastify.
3-5 clients use the APIs, but fastify may freeze without giving an error. Sometimes it comes to life on its own, but most often you have to restart it.

We tried pm2 and forever - it did not help.

Now we rented a VPS with two processors, launched via pm2 in a cluster and the situation improved.
However, there is a clear understanding that this should not be.
Let me explain: we think that fastify responds to one client, and puts others in the queue and only multicore saves them, but it should not be like for 2020.
The processor and RAM are loaded no more than 5%

please help us, we are probably missing something, because before that we used yii and there have never been such problems
    
fastify.register(require('./routes/tasks/all'), {
  prefix: '/task/get',
})
const handler = require('../../handlers/tasks/all')

module.exports = function(fastify, opts, next) {
  fastify.get('/all', handler.getRoot)
  next()
}

module.exports = {
  //fastify.get('/all', handler.getRoot)
  getRoot: async function(request, reply) {
  
    const client = await this.mysql.getConnection(onConnect)

    function onConnect (err, client) {
      if (err) {
        //console.log(err);
        return reply.send(err);
      }
      
      client.query(
        'SELECT \
          task.uid, request.name, request.client, request.address, request.date, request.time, request.state, \
          request.name as request, inspector.name  as inspector\
         FROM \
          task \
         JOIN request ON task.requestUid = request.uid \
         JOIN inspector ON task.inspectorUid = inspector.uid', 
        [
        ],
        function onResult (err, result) {
          client.release()
          // check errors
          if(err != null) {
            return reply.send(err)
          }
          else {
            return reply
            .header('Content-Type', 'application/json; charset=utf-8')
            .send(result)
          }          
        }
      )
    }
  }
}

* *node version*: 12.2.0
* *fastify version*: 1.14.2
* *os*: Debian 9

**Comment by Eomm** [comment]
Why you are awaiting a promise and giving a callback?

`const client = await this.mysql.getConnection(onConnect)`

I think this could impact.
Moreover, you should release the connection as [mysql document explains](https://github.com/mysqljs/mysql#closing-all-the-connections-in-a-pool). So I think you end the connections at your disposal.

Try this out 👍
