### ISSUE TITLE
Error Customization - Include AJV Errors Lib as Default with Schema 

### ISSUE THREAD

**Issue by thesrs02** [fastify/help#116]
#### You have already researched for similiar issues?
Yes, I've spent 2 hours searching for solution and after that I've found out that AJV errors are not included in Fastify by default that means, I cannot add custom error messages for properties in schema.

#### What are you trying to achieve or the steps to reproduce?
Want to customize the "Message" field directly from the schema - I should not have to create a separate logic under the route handler to modify the language of the error messages. Just want to make it more human-readable.

```js
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "body.first_name should be boolean"
}
```

#### What was the result you received?
Can't seem to change it without including another library.

#### What did you expect?
I expected this feature to be in Fastify since it is supporting the Schema option.

**Comment by Eomm** [comment]
Is this your case?
https://github.com/fastify/example/tree/master/validation-messages

**Comment by thesrs02** [comment]
Yes, but I'd need to install AJV-Errors library to customize the validation messages, correct?

**Comment by Eomm** [comment]
Yes

**Comment by mcollina** [comment]
I think we should improve the docs on this!
Il 11 nov 2019, 11:03 +0000, Manuel Spigolon <notifications@github.com>, ha scritto:

**Comment by thesrs02** [comment]
Okay guys, I've spent like two more hours and still not able to get it to work. Just to customize the errors messages seems to take heck a lot of work and time.

- AJV Errors is installed
- Tried to follow the docs

Basic Route & Scheme File:
![image](https://user-images.githubusercontent.com/37621213/68647612-27ae4680-0540-11ea-9145-770aeed16251.png)

No effect in the response 
![image](https://user-images.githubusercontent.com/37621213/68647714-59271200-0540-11ea-844e-3987a44dc47e.png)

Any help would be appreciated!

**Comment by mcollina** [comment]
You need to configure your custom Ajv instance as in https://www.fastify.io/docs/latest/Validation-and-Serialization/#schema-compiler.

**Comment by thesrs02** [comment]
Got it working - thanks a lot!

Quick question: Why it is showing "body" in the custom error message?

Here's a image of the Schema (custom error message) & the response on a 400 request:
![image](https://user-images.githubusercontent.com/37621213/68940401-d662b900-07c4-11ea-8872-097e44128d41.png)

Route Config:
![image](https://user-images.githubusercontent.com/37621213/68940452-fbefc280-07c4-11ea-862e-e2876cb74d7a.png)


Many thanks!

**Comment by mcollina** [comment]
Big question, I don't know. The schema is applied to the body property, so that's likely the issue... but I have no clue on how to change this.
Il 15 nov 2019, 11:28 +0000, Rehan Haider <notifications@github.com>, ha scritto:
