### ISSUE TITLE
fastify-multipart - JSON string Validation

### ISSUE THREAD

**Issue by dkrutsko** [fastify/help#117]
## 💬 Questions and Help

I'm trying to implement an API that looks like the following:

```bash
curl http://127.0.0.1/upload -X POST \
	--form data='{ "a": 1, "b": 2 }' \
	--form image=@path/to/image/file.jpg
```

I'm using [`fastify-multipart`](https://github.com/fastify/fastify-multipart) and it's working well but how can I perform validation in this scenario. Specifically, how am I able to validate `data`, which I'm currently getting via `mp.on ('field', ...)`.

It seems that the key is `data` and `value` is the string `'{ "a": 1, "b": 2 }'`, but I'd like to leverage Fastify's validation and serialization to parse this data.

**Comment by mcollina** [comment]
@dkrutsko If you use the `attachToBody: true` config option, you can just validate your keys as part of the body validation of fastify.

**Comment by dkrutsko** [comment]
Hey, thanks for your response. I actually tried that but the problem is that `value` is being presented as a string '{ "a": 1, "b": 2 }', instead of the object `{ "a": 1, "b": 2 }`.

**Comment by mcollina** [comment]
You can add a preValidation hook to parse it to JSON: https://www.fastify.io/docs/latest/Lifecycle/. We cannot automatically parse it because we do not know it is a JSON.

**Comment by dkrutsko** [comment]
Thanks, I'll give this a try when I get home. I'll post a follow up if I get it to work.
