### ISSUE TITLE
No Request ID header

### ISSUE THREAD

**Issue by digitalmio** [fastify/help#118]
## 💬 Questions and Help

I do want to include Reuest Id in the headers, so when users will have a problem with API call, we can easily track it back.
ATM we have super simple code:

```js
import 'reflect-metadata';
import { config as dotEnvConfig } from 'dotenv';
import fastify from 'fastify';
import { Server, IncomingMessage, ServerResponse } from 'http';

import { genReqId } from './helpers/generateReqId';

// define server and its config
const server: fastify.FastifyInstance<Server, IncomingMessage, ServerResponse> = fastify({
  logger: true,
  genReqId
});

// load env variables and do the configuration
dotEnvConfig();
const serverPort: number = process.env.PORT ? parseInt(process.env.PORT) : 3000;
server.decorate('config', process.env);

// set plugins
server.register(require('fastify-cors'));
server.register(require('fastify-favicon'));

server.get('/ping', async (request, reply) => {
  request.user = {
    id: 1,
    name: 'mac'
  };
  reply.send(request.user);
});

server.listen(serverPort, function(err, address) {
  if (err) {
    server.log.error(err);
    process.exit(1);
  }
});
```

genrateRequestId.ts
```js
import hyperId from 'hyperid';

const hId = hyperId({
  urlSafe: true
});

export const genReqId = () => hId();
```

Code works fine. Logging to console works fine (I am using HyperID). 
However I do not see any RequestID header. I tried to change the header name, but it did not help...

```
{"level":30,"time":1573505563036,"pid":38117,"hostname":"Macs-MacBook-Pro-2.local","reqId":"kJ-gvC7vRzaqv_npgZzoSg-7","req":{"method":"GET","url":"/ping","hostname":"127.0.0.1:4000","remoteAddress":"127.0.0.1","remotePort":61811},"msg":"incoming request","v":1}
{"level":30,"time":1573505563036,"pid":38117,"hostname":"Macs-MacBook-Pro-2.local","reqId":"kJ-gvC7vRzaqv_npgZzoSg-7","res":{"statusCode":200},"responseTime":0.1978759989142418,"msg":"request completed","v":1}
```

```
➜  http GET http://127.0.0.1:4000/ping
HTTP/1.1 200 OK
Connection: keep-alive
Date: Tue, 12 Nov 2019 11:09:22 GMT
access-control-allow-origin: *
content-length: 21
content-type: application/json; charset=utf-8

{
    "id": 1,
    "name": "mac"
}
```

Any idea what I am doing wrong? Reading the manual I understood that it should work out of the box...

- Node v10.16.3 via NVM
- Mac OS 10.14.4 (18E226)
- Fastify v2.10.0

**Comment by RafaelGSS** [comment]
Here a example:
```js
const fastify = require('fastify')({ logger: 'info' })

fastify.addHook('onSend', async (req, reply, payload) => {
  reply.header('request-id-dbg', req.id)
  return payload
})

fastify.get('/example', (req, reply) => {
  reply.send({})
})

fastify.listen(3000, err => {
  if (err) throw err
})
```

**Test**:
```
> curl -s -I -X GET localhost:3000/example
HTTP/1.1 200 OK
content-type: application/json; charset=utf-8
request-id-dbg: 4
content-length: 2
Date: Tue, 12 Nov 2019 12:22:49 GMT
Connection: keep-alive
```

**Comment by digitalmio** [comment]
Thanks for your comment. I do know I can append it myself via hook, but after reading the documentation, I understood (maybe incorrectly) that it should be added auto-magically, like it's done to log.

Here: https://www.fastify.io/docs/latest/Server/#requestidheader
and here: https://www.fastify.io/docs/latest/Server/#genreqid

If this is the correct way (add by hook) - will amend my code.

**Comment by RafaelGSS** [comment]
If you want to send to a group of routes (or globally) I don't see problems in send from hook.
You can create a `decorateReply` to make it for you too.

btw, I think that can be explained better these parts on the doc. Would you like to send a PR to adjust it? :smiley:

**Comment by jsumners** [comment]
@digitalmio the `genReqId` function is used in request _logging_. It does not add any headers to any subsequent requests or responses. You can see the request id in the logs you provided. If you want to put that `req.id` into a header, you'll need to use a hook like @RafaelGSS suggests.

**Comment by digitalmio** [comment]
OK, that's all fair. Will amend my code to include the ID by hand.
Just to clarify - what is that https://www.fastify.io/docs/latest/Server/#requestidheader header setting then? 
When you click the 'request id' link, para states:
`By default, Fastify adds an id to every request for easier tracking. If the "request-id" header is present its value is used, otherwise a new incremental id is generated. See Fastify Factory requestIdHeader and Fastify Factory genReqId for customisation options.`
This is confusing part for me. My understanding is that the header (not just in log, but actual response header) should be added by Fastify automatically, but looks like I am wrong.

**Comment by jsumners** [comment]
That is talking about the incoming request. If the request has a recognized id header then its value will be used instead of generating a new one via the function.

**Comment by digitalmio** [comment]
Makes sense! Thanks a lot!
