### ISSUE TITLE
Pass new data from PreValidation Hook to the Handler (No Mutation)?

### ISSUE THREAD

**Issue by thesrs02** [fastify/help#119]
#### Problem:
How do you handle processing the request data in a preValidation hook, then sending it to the actual route handler without mutating the request object?

Here's where I'm stuck :
![image](https://user-images.githubusercontent.com/37621213/68749557-3c620b80-0620-11ea-812a-1e8d39c0e815.png)

Is there another method to attach a different payload to the request before it is sent to the route handler or is validated?

#### Tried: 
Fastify Docs.

Thanks!

**Comment by jsumners** [comment]
```js
fastify.decorateRequest('userBody', {});
```

Then in your `preValidateRequestBody` simply `req.userBody = userBody`.

**Comment by thesrs02** [comment]
Thanks a lot @jsumners!
