### ISSUE TITLE
can't assign a prefix to routes, not using fp with routes.

### ISSUE THREAD

**Issue by helixion** [fastify/help#12]
#### What are you trying to achieve or the steps to reproduce?

Trying to namespace / assign a prefix to a group of routes, but I'm getting a 404 error.
```
app.register(require("../users/v1/routes", { prefix: "/v1/users" }))

'use strict'
const UserController = require('./UserController');

module.exports = function(app, opts, next) {
 const userController = new UserController(app);

 app.get('/', userController.index);
 app.get('/test', userController.test);

next();
}

```

Both of these routes work, but outside of the /v1 prefix, and when I attempt to go to /v1 or /v1/users/test I get an 404 error.

Basically I want to namespace them so I have different routes with different prefixes, for example /v1/users, /v1/posts, etc without having too much boilerplate within the routes themselves.

I thought that the prefixes work like namespaces.

#### Context

* *node version*: 9.3.0
* *fastify version*: >=1.3.0
* *os*: Linux, Ubuntu

**Comment by mcollina** [comment]
```
app.register(require("../users/v1/routes", { prefix: "/v1/users" }))
```

Should be

```
app.register(require("../users/v1/routes"), { prefix: "/v1/users" })
```

you were missing a parenthesis, and you were passing the options to `require`, not `register`.
