### ISSUE TITLE
Typescript - add property to request

### ISSUE THREAD

**Issue by ReTWi** [fastify/help#122]
How to add some property to request so that typescript compiler will not complain?
```
fastify.register(
  async api => {
    api.addHook('preHandler', async (req, res) => {
      req.user = 'some loaded from db data'
      if (res.sent) return
    })

    api.get('/', function(req, res) {
      res.send({ hello: 'world' })
    })
  },
  {
    prefix: '/api'
  }
)
```
 Then you get error:

`Property 'user' does not exist on type 'FastifyRequest<Http2ServerRequest, DefaultQuery, DefaultParams, DefaultHeaders, any>`

---

If you will try to customize request following docs:
```
interface CustomHttp2ServerRequest extends Http2ServerRequest {
  user: string
}

const https: fastify.FastifyInstance<Http2SecureServer, CustomHttp2ServerRequest, Http2ServerResponse> = fastify({
  logger: log,
  ignoreTrailingSlash: true,
  http2: true,
  https: { allowHTTP1: true }
})

```
Then you get error:
`Type 'FastifyInstance<Http2SecureServer, Http2ServerRequest, Http2ServerResponse>' is not assignable to type 'FastifyInstance<Http2SecureServer, CustomHttp2ServerRequest, Http2ServerResponse>'`

---

Or maybe there is a way to add additional prop to methods, so it's will be like:
```
fastify.get('/', function(req, res, myData) {
      res.send({ hello: 'world' })
})
```

**Comment by ReTWi** [comment]
I found a way to decorate fastify request, but how to "typescript it"?
```
import fp from 'fastify-plugin'
import fastify, { FastifyRequest } from 'fastify'
import { IncomingMessage } from 'http'
import { Http2ServerRequest } from 'http2'

/*
type HttpRequest = IncomingMessage | Http2ServerRequest

interface FastifyRequest<
  HttpRequest,
  Query = fastify.DefaultQuery,
  Params = fastify.DefaultParams,
  Headers = fastify.DefaultHeaders,
  Body = any
> {
  user: string
}*/

function plugin(fastify, options, next) {
  fastify.decorateRequest('user', 'userData')
  next()
}

export const reqDecorator = fp(plugin)
```

**Comment by turbobuilt** [comment]
For me, it turned out to be very simple:

```
import fastify from "fastify";
declare module 'fastify' {
    export interface FastifyRequest {
        user: { id: string }
    }
}
```

**Comment by spiffytech** [comment]
Is there a way to add a property to the request type, but not globally for all requests? I have  authenticated routes that have a `request.user` property, but unauthenticated routes shouldn't see that property in the types, nor should authenticated routes have to do a non-null assertion on every access.

I've got my code structured so that it'd be easy to pass an extended `FastifyInstance` to the routes that need the extra property, but I can't figure out the right way to extend the Fastify types to handle this.

**Comment by spiffytech** [comment]
I added a nullable `user` property onto the global Fastify types and then do non-null assertions (`!`) everywhere :frowning_face:

**Comment by jonathan-roy** [comment]
> I added a nullable `user` property onto the global Fastify types and then do non-null assertions (`!`) everywhere ☹️

Thank you, this is likely what I ended up doing too but it's not ideal :-/

**Comment by dawid-bytys** [comment]
> Is there a way to add a property to the request type, but not globally for all requests? I have authenticated routes that have a `request.user` property, but unauthenticated routes shouldn't see that property in the types, nor should authenticated routes have to do a non-null assertion on every access.
> 
> I've got my code structured so that it'd be easy to pass an extended `FastifyInstance` type to the route factories that need the extra property, but I can't figure out the right way to extend the Fastify types to handle this.

Any update on this? I'm struggling with the same problem. We need more encapsulation...

**Comment by Sufiane** [comment]
Currently struggling with the same issue as @spiffytech  and @jonathan-roy , gonna use the same work around even though its not ideal. It still is the best solution so far

**Comment by pawelgrzybek** [comment]
What @turbobuilt suggested is a good solution with a tiny little change. Make the user on request optional. Like so.

```ts
import fastify from "fastify";

declare module 'fastify' {
    export interface FastifyRequest {
        user?: User
    }
}
```

**Comment by dawid-bytys** [comment]
> What @turbobuilt suggested is a good solution with a tiny little change. Make the user on request optional. Like so.
> 
> ```ts
> import fastify from "fastify";
> 
> declare module 'fastify' {
>     export interface FastifyRequest {
>         user?: User
>     }
> }
> ```

It is still a workaround, not a solution to the problem. Ideally, this field should not be visible in every controller and so as not to check every time whether the user field is undefined.

**Comment by pawelgrzybek** [comment]
Alternatively, you can extend an interface for request in a particular route tree. This one requires a bit more work, but it will achieve what you need, @dawid-bytys. Like so.

```ts
interface FastifyRequestWithUser extends FastifyRequest {
  user?: User
}
```

**Comment by Sufiane** [comment]
> Alternatively, you can extend an interface for request in a particular route tree. This one requires a bit more work, but it will achieve what you need, @dawid-bytys. Like so.
> 
> ```ts
> interface FastifyRequestWithUser extends FastifyRequest {
>   user?: User
> }
> ```

not ideal when using type provider, where you don't have the needs to specify your types (while using `fastify.route` for instance), then i'm not sure how you could extends it.
You kinda loose the "out-of-the-box" management of such things.

Still a solution for sure

**Comment by frederikheld** [comment]
> > What [@turbobuilt](https://github.com/turbobuilt) suggested is a good solution with a tiny little change. Make the user on request optional. Like so.
> > import fastify from "fastify";
> > 
> > declare module 'fastify' {
> >     export interface FastifyRequest {
> >         user?: User
> >     }
> > }

Thanks a lot! I was missing the import statement which resulted in a lot of "module 'fastify' has no exported member x" errors.

You actually only need `import "fastify"`, otherwise you get an "'fastify' is defined but never used" error.
