### ISSUE TITLE
Typescript response type validation

### ISSUE THREAD

**Issue by ReTWi** [fastify/help#125]
Yuo can validate req.body like this, nice:
`api.route<unknown, unknown, unknown, ApiReqLogin>`

I have shared typescript type ApiResLogin, that i check on frontend reciving side and want to check on backend send side. But how to do it? 

My only idea is this:

```
import { API } from '@backend'
import { ApiReqLogin, ApiResLogin } from '@shared'

export const auth: API = (api, opts, done) => {
  api.route<unknown, unknown, unknown, ApiReqLogin>({
    method: 'POST',
    url: '/login',
    schema: {
      body: {
        type: 'object',
        properties: {
          code: 'str#'
        },
        required: ['code']
      },
      response: {
        200: {
          type: 'object',
          properties: {
            registered: 'bool#'
          }
        }
      }
    },
    handler: async (req, res) => {
      console.log(req.body) // it's of type ApiReqLogin, ok.

      let data = {} as ApiResLogin

      data = { registered: false, test: 1 } // test: 1 gives error

      return data
    }
  })

  done()
}
```

**Comment by Ethan-Arrowood** [comment]
What is the error?

**Comment by ReTWi** [comment]
@Ethan-Arrowood oh, it's just example of my idea way to check response, error is expected and ok.

```
type ApiResLogin = {
   registered: boolean;
}
```

I was just hoping that there is another (build-in) way to check response, something like:
```
handler: async (req, res: ApiResLogin) => {
       res.send( { registered: false, test: 1 }) // error test 1 should be not in response
       res.send( { registered: false }) // everything is ok!
    }
```

**Comment by Ethan-Arrowood** [comment]
I'm sorry for missing this notification.

Currently `.send` is specified as an `any` payload type. A generic could be used here -- in fact I like this addition a lot. I'll make a note of it to add to the v3 type system in the future. 

For now you can try to implement this behaviour using declaration merging. I cannot guarantee this would work nor how easy it would be to implement in the v2 type system.
```typescript
declare module 'fastify' {
  interface FastifyReply {
    send<T>(payload?: T): FastifyReply
  }
}
```

**Comment by Qocotzxin** [comment]
Hi, I'm trying to use the generic type mentioned in the PR, but this doesn't seem to be working in v4.0.0, is there a new way to accomplish this? I couldn't find anything in the migration guide or in the Reply docs.

Right now TS complains about adding a generic type:

```
      return rep.status(500).send<Response>({
        ok: false,
        data: { token: null },
        message: "Access Token creation failed.",
      });
```

`Expected 0 type arguments, but got 1.`
