### ISSUE TITLE
The framework instantiate

### ISSUE THREAD

**Issue by Denusdv** [fastify/help#126]
I try to create the fastify with logger enabled and https here is my code

```
fastify = require('fastify')({
        logger: debug === 'true',
        https: {
            key: fs.readFileSync(path.join(__dirname, 'ssl/server.key')),
            cert: fs.readFileSync(path.join(__dirname, 'ssl/server.cert'))
        }
    })
```

although my instance is inited with logger disable. I assume it's related to the way I provide init params. Unfortunately I didn't find and sample of init multiple init options sample.

Pls help me to figure it out

**Comment by Denusdv** [comment]
Sorry it should be, just pasted the code with param
```
fastify = require('fastify')({
        logger: true,
        https: {
            key: fs.readFileSync(path.join(__dirname, 'ssl/server.key')),
            cert: fs.readFileSync(path.join(__dirname, 'ssl/server.cert'))
        }
    })
```

**Comment by jsumners** [comment]
Please see https://www.fastify.io/docs/latest/Logging/. Your example will enable _info_ level logging. If you are not issuing any `info` logs then you will not see any log lines.

**Comment by Denusdv** [comment]
The problem is that if I remove 
  https: {
            key: fs.readFileSync(path.join(__dirname, 'ssl/server.key')),
            cert: fs.readFileSync(path.join(__dirname, 'ssl/server.cert'))
        }

I do see extra logs, the same result when I init fastify like

`fastify = require('fastify')({logger: true})`

**Comment by Eomm** [comment]
```
const fs = require('fs')
const Fastify = require('fastify')
const fastify = Fastify({
  logger: true
   https: {
     key: fs.readFileSync('./node_modules/fastify/test/https/fastify.key'),
     cert: fs.readFileSync('./node_modules/fastify/test/https/fastify.cert')
   }
})
fastify.listen(3000)
// will print
{"level":30,"time":1576517608304,"pid":21048,"hostname":"EOMM","msg":"Server listening at https://127.0.0.1:3000","v":1}
```

```
const fs = require('fs')
const Fastify = require('fastify')
const fastify = Fastify({
  logger: true
})
fastify.listen(3000)
// print:
{"level":30,"time":1576517631688,"pid":19840,"hostname":"EOMM","msg":"Server listening at http://127.0.0.1:3000","v":1}
```

What do you expect?
Do you have the same behaviour?
