### ISSUE TITLE
How to run multiple apps on the same port and redirect to each of those based on the domain name

### ISSUE THREAD

**Issue by platoputhur** [fastify/help#127]
Hello all,
I am trying to run multiple fastify apps on the same port and route to each of those based on the domain name. For example, let's say I have 2 domains appone.com apptwo.com. Here is the set up I am trying with.

host: directory has a fastify app which is supposed to do the routing
appone: directory with a fastify app
apptwo: directory with a fastify app

So I have to configure the app inside the host directory such that, all the requests coming for appone.com opens the app from appone directory and all the requests coming for apptwo.com opens the app from apptwo directory

I was able to achieve this in express using vhost module and in koa without using any module. I am interested in using fastify for this purpose. So how do I do this?

I checked the vhost module of fastify, but it needs multiple ports for each domains or each app which is not something I want. So I can't use that. Here is what I tried:

**_The contents of index.js from host directory_**

```
// Require the framework and instantiate it
const fastify = require('fastify')({
    logger: true
})
const appone = require('./appone/server/index.js')
const apptwo = require('./apptwo/server/index.js')

fastify.addHook('onRequest', (request, reply, done) => {
     // Get the domain name
     const host = request.hostname
     if (host == 'appone.com:3000') {
         fastify.register(appone)
         fastify.use(appone)
     } else if (host == 'apptwo.com:3000') {
         fastify.register(apptwo)
         fastify.use(apptwo)
     }
     done()
 })

// Run the server!
fastify.listen(3000, (err) => {
    if (err) {
        fastify.log.error(err)
        process.exit(1)
    }
    fastify.log.info(`server listening on ${fastify.server.address().port}`)
})
```

But this fails with an error "plugin must be a function or a promise"

**Comment by RafaelGSS** [comment]
I think that Nginx can be better work for this use case.
To usage like gateway (based on example above) do you need start all the application, and redirect to him in your gateway.

Or, register you application based on prefix, and redirect to same application but with prefix.

**Comment by jsumners** [comment]
This sort of role is filled by a proper HTTP proxy like HAProxy, Nginx, or even Apache HTTPd.

**Comment by platoputhur** [comment]
I understand that, but I am not talking about that way of doing things. I want only one fastify app to run and listen on a port. The other two fastify apps shouldn't be listening on anything. I was able to achieve this by using a few lines in express. See the code below:

```
const appone = require('./appone/server/index.js')
const apptwo = require('./apptwo/server/index.js')

app
    .use(
        function (req, res, next) {
            if (req.hostname == 'appone.com') {
                appone(req, res, next)
            } else if (req.hostname == 'apptwo.com') {
                apptwo(req, res, next)
            }
        }
    )
    .listen(3000);
```

And in the index.js file of app one I exported the app variable and removed the listening part.

So here only one expressjs app was listening on the port. This is what I want to do with fastify. This can't be done using apache or nginx or any proxy softwares afaik.

I was able to do the same with koajs as well. So I just want to duplicate this in fastify if I can.

**Comment by mcollina** [comment]
A single fastify app serve one domain. It should be possible to do what you want by using an external http server with https://www.fastify.io/docs/latest/Server/#serverfactory.

**Comment by jsumners** [comment]
Yes, this is a very easy thing to accomplish in HAProxy. It is specifically designed for just this sort of scenario. An `acl` rule with a `hdr(host)` condition is exactly what one would use.

https://blog.entrostat.com/routing-multiple-domains-using-haproxy-http-and-https-ssl/

**Comment by platoputhur** [comment]
> Regardless of the Node.js framework you use, you should be using a proxy in front of it to handle the ingress connection.

So where would the proxy redirect to? Shouldn't it be different servers which listen on its own ports?

-----

I still don't understand how this can be done with what you guys are saying. The whole setup should only listen to one port. And there can be only one server process.

                                                        appone
                                                       /
fastify_multitenant_app:3000 ----
                                                       \
                                                        apptwo

Here appone and apptwo can't listen on any ports. It shouldn't even have any servers running. All requests come to fastify_multitenant_app and it redirects to the right fastify app

Or am I missing something?

**Comment by jsumners** [comment]
See https://github.com/fastify/fastify/blob/master/docs/Recommendations.md#use-a-reverse-proxy
