### ISSUE TITLE
Disable coerce types only on body

### ISSUE THREAD

**Issue by ncsft** [fastify/help#128]
How can i disable fastify coerce types ONLY on body?
/sessions/123 -> it's coerce to int, thats ok
{
session: '123' -> it's coerce to int, thats no ok, i want error message if session is not integer
}

**Comment by Ethan-Arrowood** [comment]
I believe this would have something to do with ajv - what we use under the hood to do validation.

I found this: https://ajv.js.org/coercion.html

And you can set types for ajv through the fastify options argument: https://www.fastify.io/docs/latest/Server/#factory-ajv

Let me know if you need more help!

**Comment by ncsft** [comment]
Yes, but i can't enable it for parameters, and disable it for body at the same time...

**Comment by ncsft** [comment]
I solve a problem like that, thanks for help!
```javascript
const Ajv = require('ajv');
const fastify = require('fastify');
const app = fastify();
app.route({
  method: 'POST',
  url: '/api/:id',
  schema: {
    params: {
      $comment: 'coerce',
      type: 'object',
      required: ['id'],
      additionalProperties: false,
      properties: {
        id: { type: 'integer' }
      }
    },
    body: {
      type: 'object',
      required: ['uid'],
      additionalProperties: false,
      properties: {
        uid: { type: 'integer' }
      }
    },
    querystring: {
      $comment: 'coerce',
      type: 'object',
      properties: {
        querystring: { type: 'string' }
      }
    },
    headers: {
      $comment: 'coerce',
      type: 'object',
      properties: {
        headers: { type: 'string' }
      }
    },
    response: {}
  },
  handler: async (request, reply) => {
    console.log(request.params, request.body);
  }
});

function compiler(coerceTypes = false) {
  return new Ajv({
    removeAdditional: true,
    useDefaults: true,
    coerceTypes: coerceTypes,
    allErrors: true,
    nullable: true,
  });
}

app.setSchemaCompiler( schema => {
  return compiler(schema['$comment'] === 'coerce').compile(schema);
});

(async () => {
  try {
    const response = await app.inject({
      method: 'POST',
      url: '/api/1',
      payload: {
        uid: '222'
      }
    });
    console.log(response.payload);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
})();
```

**Comment by jsumners** [comment]
You should also set a resolver https://www.fastify.io/docs/latest/Validation-and-Serialization/#schema-resolver

**Comment by KrakerXyz** [comment]
To anyone that finds this from a google search, here's my solution as of v3.19.1

```typescript
const schemaCompilers: Record<string, Ajv.Ajv> = {
    'body': new Ajv({
        removeAdditional: false,
        coerceTypes: false,
        allErrors: true
    }),
    'params': new Ajv({
        removeAdditional: false,
        coerceTypes: true,
        allErrors: true
    }),
    'querystring': new Ajv({
        removeAdditional: false,
        coerceTypes: true,
        allErrors: true,
    })
};

server.setValidatorCompiler(req => {
    if (!req.httpPart) { throw new Error('Missing httpPart'); }
    const compiler = schemaCompilers[req.httpPart];
    if (!compiler) { throw new Error(`Missing compiler for ${req.httpPart}`); }

    return compiler.compile(req.schema);
});
```

**Comment by Eomm** [comment]
I love to see how you find great solutions with the validator compiler feature!
Thanks for sharing!

**Comment by ashwinchandran13** [comment]
> To anyone that finds this from a google search, here's my solution as of v3.19.1
> 
> ```ts
> const schemaCompilers: Record<string, Ajv.Ajv> = {
>     'body': new Ajv({
>         removeAdditional: false,
>         coerceTypes: false,
>         allErrors: true
>     }),
>     'params': new Ajv({
>         removeAdditional: false,
>         coerceTypes: true,
>         allErrors: true
>     }),
>     'querystring': new Ajv({
>         removeAdditional: false,
>         coerceTypes: true,
>         allErrors: true,
>     })
> };
> 
> server.setValidatorCompiler(req => {
>     if (!req.httpPart) { throw new Error('Missing httpPart'); }
>     const compiler = schemaCompilers[req.httpPart];
>     if (!compiler) { throw new Error(`Missing compiler for ${req.httpPart}`); }
> 
>     return compiler.compile(req.schema);
> });
> ```

Can you describe the usage?

**Comment by KrakerXyz** [comment]
> > To anyone that finds this from a google search, here's my solution as of v3.19.1
> > ```ts
> > const schemaCompilers: Record<string, Ajv.Ajv> = {
> >     'body': new Ajv({
> >         removeAdditional: false,
> >         coerceTypes: false,
> >         allErrors: true
> >     }),
> >     'params': new Ajv({
> >         removeAdditional: false,
> >         coerceTypes: true,
> >         allErrors: true
> >     }),
> >     'querystring': new Ajv({
> >         removeAdditional: false,
> >         coerceTypes: true,
> >         allErrors: true,
> >     })
> > };
> > 
> > server.setValidatorCompiler(req => {
> >     if (!req.httpPart) { throw new Error('Missing httpPart'); }
> >     const compiler = schemaCompilers[req.httpPart];
> >     if (!compiler) { throw new Error(`Missing compiler for ${req.httpPart}`); }
> > 
> >     return compiler.compile(req.schema);
> > });
> > ```
> 
> Can you describe the usage?

I'm assuming you're asking for my use case, if that is not correct, let me know and I'll clarify.

I prefer my body schema to be strict and not assume the user sending "0" really intended for it to be 0 which is what the schema requires. 

This is in contrast to query parameters, where the user only has the option of sending a parameter as a string. Here, having "0" automatically converted to 0 before the handler is called eliminates repetitive code to do the coercion ourselves within the handler.
