### ISSUE TITLE
Custom 404 fallback response

### ISSUE THREAD

**Issue by robinvdvleuten** [fastify/help#13]
#### You have already researched for similiar issues?

✅

#### What are you trying to achieve or the steps to reproduce?

I would like to have a default 404 message when no custom 404 message is passed.

```js
fastify.setNotFoundHandler(function (req, reply) {
    reply.code(404).send({ error: 'Not Found', message: 'Four Oh Four 🤷‍♂️', statusCode: 404 })
})

fastify.get((req, reply) => {
    // Using the helper method from `fastify-sensible` here
    reply.notFound('My Custom 404 message')
})
```

#### What was the result you received?

I always receive my custom 404 message.

#### What did you expect?

I expect that the any custom thrown 404 message is respected with my custom message as a fallback when a route is not found.

#### Context

* *node version*: 10
* *fastify version*: ^1.4.0
* *os*: Mac

**Comment by delvedor** [comment]
Hi! Currently you can't do it, but we are discussing about it in https://github.com/fastify/fastify/issues/848.

**Comment by Eomm** [comment]
Now, with Fastify v2 you can use [.setNotFoundHandler](https://github.com/fastify/fastify/blob/master/docs/Server.md#setnotfoundhandler)

**Comment by IR367776** [comment]
Your Test Is still Failed sometimes!!!!
