### ISSUE TITLE
In what scenarios is onResponse not called (other than process terminated/hung)

### ISSUE THREAD

**Issue by markrzen** [fastify/help#131]
I have looked at the Lifecycle documentation. The way I interpreted it it looks like the onResponse handler wouldn't be called in 404 or 5xx situations, but that does not appear true to my manual testing.

Are there any scenarios (other than process termination or hanging) that the onResponse would not be called for a request?

**Comment by mcollina** [comment]
I think the only case it's not called is when the response is closed by using the node core objects, but I might be wrong. Feel free to send an update to the docs!

**Comment by markrzen** [comment]
@mcollina Will do. I will run it a bit in prod and confirm before sending a PR your way.
Thanks again.
