### ISSUE TITLE
how to set keepAliveTimeout and headersTimeout in fastify?

### ISSUE THREAD

**Issue by msantagata** [fastify/help#132]
Hello there,
I'm migrating an app from Express to Fastify, but I couldn't find where to set those two timeouts in fastify. I would need those to prevent random 502 errors on AWS ELB (see https://shuheikagawa.com/blog/2019/04/25/keep-alive-timeout/ for a detailed description).
Is it possible?
Thanks for your help!

**Comment by mcollina** [comment]
You can set them with `app.server.headersTimeout` and `app.server.keepAliveTimeout`.

**Comment by msantagata** [comment]
Excellent, thanks!

**Comment by brianmorin-ef** [comment]
This is what worked for me when dealing with setting these options to deal with ALBs:

```
const server = fastify({
        serverFactory(handler) {
            const httpServer = http.createServer(handler);
            httpServer.keepAliveTimeout = 65000;
            httpServer.headersTimeout = 70000;
            return httpServer;
        }
    });
```
