### ISSUE TITLE
sendFile in the onRequest hook cause error "Request Already Sent"

### ISSUE THREAD

**Issue by Forux** [fastify/help#135]
#### You have already researched for similiar issues?
I did not find information about this

#### What are you trying to achieve or the steps to reproduce?

I want to sendFile using fastify-static, in some specific case I need to change file and send different one, instead of file mentioned in url. Example:

```js
app.addHook('onRequest', async function (request, reply) {
        if (request.query.compress === "br") {
            reply.sendFile(filePath + "br");
        }
});
```

#### What was the result you received?

All work, but server produce errors "Reply already sent"

It looks like standard fastify-static logic trying to send original file too, how to prevent that? How to stop propagation in onRequest and why sendFile did not stop propagation?

```js
{"level":40,"time":1580400398650,"pid":25524,"hostname":"DESKTOP-NACQR8C","reqId":24,"err":{"type":"FastifyError","message":"FST_ERR_REP_ALREADY_SENT: Reply was already sent.","stack":"FastifyError [FST_ERR_REP_ALREADY_SENT]: FST_ERR_REP_ALREADY_SENT: Reply was already sent.\n    at _Reply.Reply.send (C:\\VRNET\\VRnet\\web\\site\\v2\\node_modules\\fastify\\lib\\reply.js:104:26)\n    at PassThrough.<anonymous> (C:\\VRNET\\VRnet\\web\\site\\v2\\node_modules\\fastify-static\\index.js:73:13)\n    at PassThrough.emit (events.js:209:13)\n    at ReadStream.Readable.pipe (_stream_readable.js:779:8)\n    at SendStream.stream (C:\\VRNET\\VRnet\\web\\site\\v2\\node_modules\\send\\index.js:799:10)\n    at SendStream.send (C:\\VRNET\\VRnet\\web\\site\\v2\\node_modules\\send\\index.js:708:8)\n    at onstat (C:\\VRNET\\VRnet\\web\\site\\v2\\node_modules\\send\\index.js:730:10)\n    at FSReqCallback.oncomplete (fs.js:167:5)","name":"FastifyError [FST_ERR_REP_ALREADY_SENT]","code":"FST_ERR_REP_ALREADY_SENT","statusCode":500},"msg":"Reply already sent","v":1}
```
#### What did you expect?

No errors

#### Context

* *node version*: v12.9.1
* *fastify version*: ^2.11.0
* *os*: Windows
* *any other relevant information*: "fastify-static": "^2.5.1"
And i DO NOT use next, at all, only async functions, just leting you knew that this is not a case

**Comment by mcollina** [comment]
I think you should remove the `async` part or add `return reply` at the end.

**Comment by Forux** [comment]
> I think you should remove the `async` part or add `return reply` at the end.

Why do you think so?

I tried, both, nothing changed.

**Comment by jsumners** [comment]
Why are you sending the response from the `onRequest` hook? I believe what is happening is you are sending the response in this hook and then also from your handler. You should only send the response from one location.

**Comment by Forux** [comment]
I send file only in the hook itself and I expect that after sendFile command propagation will be stoped, and onRequest is the first place so it looks like the best one to stop the process.

So why it works differently?

And how can I stop the propagation process and just send the file as soon as possible?

**Comment by jsumners** [comment]
I might be wrong -- https://www.fastify.io/docs/latest/Hooks/#respond-to-a-request-from-a-hook

**Comment by Forux** [comment]
It does not work at all (reply.res.end after sendFile) it cause this:

```js
{"level":40,"time":1580453432114,"pid":20876,"hostname":"DESKTOP-NACQR8C","reqId":24,"msg":"response will send, but you shouldn't use res.writeHead in stream mode","v":1}
{"level":40,"time":1580453432118,"pid":20876,"hostname":"DESKTOP-NACQR8C","reqId":25,"msg":"response will send, but you shouldn't use res.writeHead in stream mode","v":1}
{"level":40,"time":1580453432121,"pid":20876,"hostname":"DESKTOP-NACQR8C","reqId":24,"err":{"type":"NodeError","message":"write after end","stack":"Error [ERR_STREAM_WRITE_AFTER_END]: write after end\n    at write_ (_http_outgoing.js:594:17)\n    at ServerResponse.write (_http_outgoing.js:586:15)\n    at PassThrough.ondata (C:\\VRNET\\VRnet\\web\\site\\v2\\node_modules\\readable-stream\\lib\\_stream_readable.js:662:20)\n    at PassThrough.emit (events.js:209:13)\n    at addChunk (C:\\VRNET\\VRnet\\web\\site\\v2\\node_modules\\readable-stream\\lib\\_stream_readable.js:297:12)\n    at readableAddChunk (C:\\VRNET\\VRnet\\web\\site\\v2\\node_modules\\readable-stream\\lib\\_stream_readable.js:279:11)\n    at PassThrough.Readable.push (C:\\VRNET\\VRnet\\web\\site\\v2\\node_modules\\readable-stream\\lib\\_stream_readable.js:240:10)\n    at PassThrough.Transform.push (C:\\VRNET\\VRnet\\web\\site\\v2\\node_modules\\readable-stream\\lib\\_stream_transform.js:139:32)\n    at PassThrough.afterTransform (C:\\VRNET\\VRnet\\web\\site\\v2\\node_modules\\readable-stream\\lib\\_stream_transform.js:88:10)\n    at PassThrough._transform (C:\\VRNET\\VRnet\\web\\site\\v2\\node_modules\\readable-stream\\lib\\_stream_passthrough.js:38:3)"},"msg":"response terminated with an error with headers already sent","v":1}
```

**Comment by jsumners** [comment]
Can you provide a complete example than can be run by `node index.js`?

**Comment by Eomm** [comment]
Removing the `async` works for me:

```
const fastify = require('fastify')({ logger: true })

fastify.register(require('fastify-static'), {
  root: __dirname
})

fastify.addHook('onRequest', function (request, reply) {
  reply.sendFile('README.md')
})

fastify.get('/', (request, reply) => {
  console.log('HANDLER')
})

fastify.listen(3001)
```

> So why it works differently?

Because an async function has 3 state:
- pending
- reject
- resolved

your `async` function will resolve with `undefined` and the `next` is called under the hood.
Calling the next, the handler is executed.

@mcollina Maybe should we not run the `next` when the promise is fulfilled and the `reply` is sent?

**Comment by Forux** [comment]
https://github.com/Forux/fastify-error

ts source and compiled js both there

to run:
1. npm i
2. node server.js

then
1. http://localhost:4010/test.txt you will see "1234"
2. http://localhost:4010/test.txt?compress=br browser will download file with "12345678" but in the console you will see this error

```json
{"level":40,"time":1580490660677,"pid":22972,"hostname":"DESKTOP-NACQR8C","reqId":1,"err":{"type":"FastifyError","message":"FST_ERR_REP_ALREADY_SENT: Reply was already sent.","stack":"FastifyError [FST_ERR_REP_ALREADY_SENT]: FST_ERR_REP_ALREADY_SENT: Reply was already sent.\n    at _Reply.Reply.send (C:\\VRNET\\example\\node_modules\\fastify\\lib\\reply.js:104:26)\n    at PassThrough.<anonymous> (C:\\VRNET\\example\\node_modules\\fastify-static\\index.js:79:13)\n    at PassThrough.emit (events.js:209:13)\n    at ReadStream.Readable.pipe (_stream_readable.js:779:8)\n    at SendStream.stream (C:\\VRNET\\example\\node_modules\\send\\index.js:799:10)\n    at SendStream.send (C:\\VRNET\\example\\node_modules\\send\\index.js:708:8)\n    at onstat (C:\\VRNET\\example\\node_modules\\send\\index.js:730:10)\n    at FSReqCallback.oncomplete (fs.js:167:5)","name":"FastifyError [FST_ERR_REP_ALREADY_SENT]","code":"FST_ERR_REP_ALREADY_SENT","statusCode":500},"msg":"Reply already sent","v":1}
```

**Comment by Forux** [comment]
And also, as I understood if I will always not call next - other requests will be blocked?

So I need to what? Reject promise?

**Comment by Eomm** [comment]
Here a working example:

```
fastify.addHook('onRequest', async function (request, reply) {
  // only for test, in an async context we should throw an Error
  return Promise.reject(new Error('err'))
})
```

and it works with a simple `function` aswell.

Returning `Promise.reject()` has no sense, but this is a bug since you are avoiding this check:

https://github.com/fastify/fastify/blob/7fa4bddca07aac18e0600cff40d97b95a96ab970/lib/hooks.js#L80-L82

since `err` is empty and the request flow continue
