### ISSUE TITLE
Misbehavior of wildcard route

### ISSUE THREAD

**Issue by milad-abbasi** [fastify/help#137]
## 🐛 Bug Report
By registering the path below any path that start with "a" will match this route.
`/a`
`/abc`
`/a/bc`
`/a/bc/de`
`/abc/ANYTHING/HERE/WILL/MATCH`
All the above paths will get routed to the registered handler.

```js
const fastify = require('fastify')({ logger: true });

fastify.get('/a/*/b', async (req, reply) => {
    return 'Ok';
});

fastify.listen(3000);
```

## Expected behavior

Path that must match:
`/a/AnythingHere/b`

Paths that must **NOT** match:
`/ab/AnythingHere/b`
`/a/AnythingHere`
`/a/AnythingHere/c`

## Your Environment

- *node version*: 12.14.1
- *fastify version*: 2.11.0
- *os*: Ubuntu 18.04

**Comment by Eomm** [comment]
Why you didn't use `/a/:whatever/b`?

**Comment by milad-abbasi** [comment]
> Why you didn't use `/a/:whatever/b`?

I was wondering why this is not working, Also there is another issue about that:  
```js
const fastify = require('fastify')({ ignoreTrailingSlash: true });

fastify.get('/a/c', async (req, reply) => {
    return req.raw.url;
});

fastify.get('/a/:whatever/b', async (req, reply) => {
    return req.raw.url;
});

fastify.listen(3000);
```
A path of `/a/c/b` will **NOT** get a match but `/a/AnythingExcept"c"/b` will match.
This happens when `ignoreTrailingSlash` option is set to `true`
Should I open another issue for this?

**Comment by Eomm** [comment]
> I was wondering why this is not working

This is explained [here](https://github.com/delvedor/find-my-way/#supported-path-formats), I think in the first case with `*` you should use the regexp instead.

The second case depends on [match order](https://github.com/delvedor/find-my-way/#match-order)

> This happens when ignoreTrailingSlash option is set to true

This should be investigated why the router act like this, instead

**Comment by milad-abbasi** [comment]
> The second case depends on [match order](https://github.com/delvedor/find-my-way/#match-order)

Yes it depends on match order but it's not getting a match it gets 404

**Comment by nwoltman** [comment]
@milad-abbasi [That](https://github.com/fastify/help/issues/137#issuecomment-582335257) definitely looks like a bug, especially since it only happens when `ignoreTrailingSlash` is `true`. Please open an issue over in the [`find-my-way`](https://github.com/delvedor/find-my-way) repo 🙂

**Comment by Eomm** [comment]
Closing due it is a find-my-way issue: https://github.com/delvedor/find-my-way/issues/145
