### ISSUE TITLE
Keycloak middleware protect

### ISSUE THREAD

**Issue by chenchuraviteja** [fastify/help#138]
give me idea to how to use keycloak connect logic for middleware authentication purpose

**Comment by mcollina** [comment]
I don't know, I've never used keycloak with Fastify.

**Comment by Eomm** [comment]
For what I know the communication between a server and keycloak is via OpenID standard
So I think an openid client could do the job

In general, a "native" (aka no middleware's express)  OpenId integration would be great to have in fastify

**Comment by chenchuraviteja** [comment]
> I don't know, I've never used keycloak with Fastify.

ok, but give me any suggestions to how to work on multiple tenants

**Comment by mcollina** [comment]
There is no imperative tense in Open Source.

**Comment by jsumners** [comment]
@chenchuraviteja please stop demanding work. We do not know your technology stack or your project goals. We will try to assist with specific questions that directly pertain to Fastify, but we will not be your https://softwareengineering.stackexchange.com/ on GitHub.
