### ISSUE TITLE
Using plugins with typescript 

### ISSUE THREAD

**Issue by NickClicknClear** [fastify/help#139]
First of all thanks for the great framework. It's exactly what I've been looking for. 

I'm trying to work out how to use a plugin when using Typescript

If I do something like this

index.ts
```
const server = fastify({})

// Adds a foo to the Fastify instance 
server.register(myPlugin)

// Uses a foo
server.register(myRoute)
```

myRoute.ts

```
export default async function routes (fastify) {
  fastify.get('/myroute', async (request, reply) => {
    const foo = fastify.foo
    // Do stuff with foo
  }
}
```

Typescript doesn't know that Fastify should have a 'foo' property because of the plugin. 

What is the correct way to ensure that the route handler knows it should have a foo on the Fastify instance?

Thanks in advance!

**Comment by Ethan-Arrowood** [comment]
https://www.fastify.io/docs/latest/TypeScript/#authoring-plugin-types

Make use of declaration merging to tell your type interpreter the new fastify instance types

**Comment by NickClicknClear** [comment]
Brilliant, that works thank you!
