### ISSUE TITLE
Disable logging per route

### ISSUE THREAD

**Issue by emilbayes** [fastify/help#140]
Hi,

Is it possible to disable logging on a per route basis? In my instance I have a health check that is not worth logging requests to and from, and it's just polluting my logs.

(Also, when opening an issue here, the prefilled template said this was not the right place to ask questions so I think the template might be wrong :) )

**Comment by mcollina** [comment]
It's in the docs ;)! https://www.fastify.io/docs/latest/Routes/#custom-log-level

**Comment by robcresswell** [comment]
The previous link seems to 404, but this should work if others stumble across this issue:

https://www.fastify.io/docs/latest/Reference/Routes/#custom-log-level
