### ISSUE TITLE
serverless

### ISSUE THREAD

**Issue by kivi** [fastify/help#142]
Can you please update the documentation for Serverless or for Testing to the new ESM Modules? https://www.fastify.io/docs/latest/Serverless/#appjs

```js
function init() {
  const app = fastify();
  app.get('/', (request, reply) => reply.send({ hello: 'world' }));
  return app;
}

if (require.main === module) {
  // called directly i.e. "node app"
  init().listen(3000, (err) => {
    if (err) console.error(err);
    console.log('server listening on 3000');
  });
} else {
  // required as a module => executed on aws lambda
  module.exports = init;
}
```

`require.main` is not defined anymore. We have to use something else to run that app.js as standalone or serverless. Or in order run tests `listen()` should not be startet, but `export default init;`  could always exported.

#### Context

* *node version*: v13.8.0
* *fastify version*: >=2.10.0
* *mjs*: using ESM

**Comment by jsumners** [comment]
PRs are welcome. But it should be an extra example, not a replacement of the current one.
