### ISSUE TITLE
Deploy a monorepo with Fastify microservices into production.

### ISSUE THREAD

**Issue by vorillaz** [fastify/help#144]
Hello all this a long one, way too specific use case and maybe a long shot but as @delvedor suggested we can also create a section into the documentation settings.

For the past few months, I am developing an application which is actually a monorepo. I have some micro frontend apps consuming Sapper along with Fastify and lots of independent APIs which are using Fastify, actually, each microservice is a standalone Fastify server.

I was using ZEIT's Now for development and staging as was stated into the docs (https://github.com/fastify/fastify/blob/master/docs/Serverless.md#zeit-now) but due to some platform changes, we were locked out.

Are there any tutorials, tips or even platform suggestions that they could help us deploy and scale our application in production? I had attended NodeConf's Fastify workshop (https://github.com/delvedor/fastify-architecture-workshop) with a similar mindset.

Eventually, I want to create a solution where each microserver will be independent and I could scale each one on demand. Maybe an example with Kubernetes and Cloudflare load balancer could work but I am not quite sure as I have not found any reasonable examples or solutions.

Any help or suggestions would be highly appreciated.

**Comment by mcollina** [comment]
What do you mean "we were locked out"?

I agree that having a real-world example with some automation as an example would be highly helpful.

**Comment by vorillaz** [comment]
Hey, @mcollina thanks for the quick response. ZEIT changed their approach and they do not support monorepos any more, they are promoting lamda functions instead, actually consuming their own convention. Thus we need to find another approach for development and production.
Our monorepo looks like this:
```
app/
├── api1
├── api2
├── sapper
├── static
└── shared
```
`api1` and `api2` are tiny fastify apps, each one spins up a fastify server exposed to a port. `sapper` is our main app which also uses fastify along with sapper. Finally, static are some plain scripts served and `shared` are commonly shared utilities and helpers across the monorepo.

Using ZEIT's Now we were able to spin up each microservice and static app and handle routing, local development, and deployments through `now.json`. 

Right now I am trying to figure out how we can create a similar environment that scales horizontally. I am mostly trying to set up a local dev environment and actually searching for a solution for scalable deployments. Therefore, I am actually seeking for tips, tutorials, pieces of information or gotchas in order to design a proper architecture for my application.
Finally, any recommendations about running Fastify on production mode would be great.

**Comment by mcollina** [comment]
Have you tried AWS CDK to define the deployment using AWS Fargate and AWS ECS? I can’t help much with that, but it would be a good place to start/look into.
Il 16 feb 2020, 20:26 +0000, Theodore Vorillas <notifications@github.com>, ha scritto:

**Comment by StarpTech** [comment]
Hi @vorillaz I can recommend [Google Cloud run](https://cloud.google.com/run). It's like a lightweight Heroku companion.

Combine it with Github Actions https://github.com/marketplace/actions/cloud-run and you have a fully scalable and reliable CI/CD pipeline.

**Comment by vorillaz** [comment]
Thanks a lot @StarpTech and @mcollina, you were really helpful. Closing this one.
