### ISSUE TITLE
I'm not sure what I'm doing wrong. after() is not being fired in tests.

### ISSUE THREAD

**Issue by chanced** [fastify/help#146]
I'm not sure what I'm missing. My app is loaded and functions properly when it is being run. However, `after(cb)` does not fire within a test environment. 

I have the following test:
```js

// test.ts

import expect from 'expect';
import Fastify from 'fastify';
import core from '../../src/app';
test('after fires', done => {
  const app = Fastify();
  app.register(core);
  app.after(() => {
    console.log('after'); // <--- is never reached
    expect(true).toBeTruthy();
    return done();
  });
});


```
I wasn't exactly sure how to export a FastifyInstance that could be loaded elsewhere. The idea here is that I'm planning on breaking up the app into smaller services that I can import for a monolith.

```js
// app.ts
import Fastify from 'fastify';
import plugins from './plugins';
import routes from './routes';
import fp from 'fastify-plugin';

export interface AppConfig {
  mongo?: { url: string; database: string };
}

export default fp(async (app, config?: AppConfig) => {
  config = config || {};
  const mongoConfig = config.mongo
    ? config.mongo
    : {
        url: process.env.MONGO_URL || 'mongodb://localhost:27017',
        database: process.env.MONGO_DB || 'pear'
      };
  app.register(plugins.jwt);
  app.register(plugins.blipp);
  app.register(plugins.mongo, mongoConfig);
  app.register(routes);
});
```
However, everything works as expected here:

```js
// server.ts
require('dotenv').config();
import Fastify from 'fastify';
import core from './app';
import prettyms from 'pretty-ms';
import path from 'path';
// Require the framework

const start = async () => {
  try {
    const startTime = Date.now();
    const app = Fastify({
      logger: true
    });
    app.register(core);
    app.after(() => {
      console.log('After was called');
    });
    await app.listen(Number.parseInt(process.env.APP_PORT) || 3000);
    app.blipp();
    const timeToLoad = prettyms(Date.now() - startTime);
    app.log.info(`App start time: ⌛ ${timeToLoad}`);
  } catch (e) {
    throw e;
  }
};

try {
  start();
} catch (e) {
  console.error(e);
}
```

**Comment by chanced** [comment]
Ugh, I just figured out how to get it to fire. 

If I inject a request into the fastify service it executes otherwise it sits idle.

Is this expected behavior

**Comment by Eomm** [comment]
You need to trigger the application loading to get the `after` called

```
test('after fires', done => {
  const app = Fastify();
  app.register(core);
  app.after(() => {
    console.log('after'); // <--- is never reached
    expect(true).toBeTruthy();
    return done();
  });

  app.ready(err => {
    t.error(err)
  })
});
```

**Comment by chanced** [comment]
@Eomm That also works. Both seem a bit counter-intuitive or, at minimum, a bit unclear.

Regardless, it works for me and that's what matters. Thanks!

**Comment by Eomm** [comment]
[Here](https://github.com/fastify/fastify/blob/master/docs/Testing.md#testing) you can find more info about this behaviour.

Feel free to open a PR to improve docs in order to be more clear for everyone 👍

**Comment by chanced** [comment]
@Eomm I didn't mean to come across as negative or condescending. Overall I love fastify so far!

I'm not sure my problem is with the docs, perse, but rather the behavior of the app. It isn't obvious that `fastify.ready(callback)` would have a consequence. 

It isn't obvious that `after` wouldn't be called without further action, like processing a request or having `ready` called downstream.

**Comment by chanced** [comment]
Thanks again 👍
