### ISSUE TITLE
Use of bind(this)

### ISSUE THREAD

**Issue by paulogr** [fastify/help#147]
Hello!

Is it ok to use `bind(this)` to pass fastify context to another modules?

I have some modules on my application the have to been executed dynamically based on input parameters.

For this to work I did create a plugin with a function decorator to receive the input and return the specified module, but I still want to use on the returned module some shared plugins like database, http, fastify sensible, etc...

Is it a good approach?

Thanks!

**Comment by mcollina** [comment]
Can you make a code example? It's a bit hard to understand what you are trying to do.

**Comment by paulogr** [comment]
Sure!

My app has a concept of multiple platforms, each platform has its own implementation of business cases.

```
// platform1.js

module.exports = function () {
  return {
    install () {
    },
    uninstall () {
    },
    publish () {
    }
  }
}

// platform2.js
// **has the same methods with its own specific implementation**

module.exports = function () {
  return {
    install () {
    },
    uninstall () {
    },
    publish () {
    }
  }
}
```

I have difficult to implement a platform as a plugin, because of every platform has the same methods names and add as decorators can cause problems, right?

So what I did.

```
const platforms = {
  platform1: require('./platform1')
  platform2: require('./platform2')
}

module.exports = async function (app, opts) {
  app.decorate('getPlatform', function (platformId) {
    return platforms[platformId].bind(this)
  })
}
```

This way I can manage to execute the methods of the chosen platform, it works, but the part I'm not very sure about is the usage of **bind(this)** or if there is another better way to do that.

It is clear now?

Thank you for the help!

**Comment by mcollina** [comment]
Why cannot a platform be a plugin? Plugins have been built with that purpose.

**Comment by paulogr** [comment]
It's hard to explain...

sure i can put it as a plugin, like this you mean

```
// platformX.js

module.exports = async function (app, opts) {
  const platform = {
    install () {
    },
    uninstall () {
    },
    publish () {
    }
  }
  app.decorate('platform-x', platform)
}
```
so I can do this without the need of bind

```
module.exports = async function (app, opts) {
  app.register(require('./platforms'))
  app.decorate('getPlatform', function (platformId) {
    return this[platformId]
  })
}
```

But now suppose my platform methods, `install`, `uninstall` and `publish` are big and I want to put them in separate files for each platform.

Do you recommend write those methods as plugins too? If not, it's ok to use bind(this) to pass fastify context for those modules?

If I do so, the method names would collide or if I don't use fastify-plugin they wouldn't be available for the parent scope.

My problem is always on the "second level plugin", I mean, when a plugin needs to be compose by another plugins.

Problem 1) name collision of decorated methods
Problem 2) if not use `fastify-plugin` they are not available to the parent scope.

Thanks again.

**Comment by mcollina** [comment]
I would still pass them as arguments.

```js

module.exports = function buildInstall (app) {
  return function install () {

  }
}
```
----

> Problem 1) name collision of decorated methods

You'll need to add some prefixes to your methods.

> Problem 2) if not use fastify-plugin they are not available to the parent scope.

That's on purpose, it's encapsulation at play.

**Comment by paulogr** [comment]
Thank you for your help @mcollina!

It helps, but I opened another issue, with another question, another way to show my difficult.
