### ISSUE TITLE
Question about encapsulation

### ISSUE THREAD

**Issue by paulogr** [fastify/help#148]
I can't wrap my mind about how encapsulation works on Fastify, my fault, the docs says:

`
By default, register creates a new scope, this means that if you do some changes to the Fastify instance (via decorate), this change will not be reflected to the current context ancestors, but only to its sons.
`

I can't imagine a scenario where child context could be benefit from parent.

Let me try to explain myself.

```
// plugin1.js

module.exports = async function (app, opts) {
  app.decorate('feature1', function () {
    console.log('feature1')
  })
}
```

```
// service.js

module.exports = async function (app, opts) {
  app.register(require('./plugin1')
}
```

I know I can't use `feature1` inside service.js, unless I wrap it in fastify-plugin.

**My question is, how can I express a child context inside service.js that can use plugin1?**

If I register another plugins inside service.js, they couldn't be benefit from plugin1 too.

```
// service.js

module.exports = async function (app, opts) {
  app.register(require('./plugin1')
  app.register(require('./another-plugin')
}
```

Why I just don't use fastify-plugin? Because I want to use plugin encapsulation, just don't know how.

Thanks!

**Comment by mcollina** [comment]
I don't understand what you are trying to achieve. You have to use `fastify-plugin` if you want to expose a decorator to the outher scope breaking the encapsulation.

If you want to achieve a mixed model where plugin1 has some routes that are encapsulated and some public decorated value, you can do it by using two nested plugins https://github.com/mcollina/fastify-gql is an example of that.

**Comment by Eomm** [comment]
> My question is, how can I express a child context inside service.js that can use plugin1?

You can't if you don't break encapsulation

THis schema shows how it works, every "circle" see only the thing registered inside of it or in the parent scope:

![image](https://user-images.githubusercontent.com/11404065/75930874-e4bc0a00-5e73-11ea-9b37-cee3de15f0dc.png)

You can't get the "circle" green from the "circle" yellow for example..... unless you break the encapsulation.

I made a plugin for this [fastify-explorer](https://github.com/Eomm/fastify-explorer): it simply keep a pointer to all the instance/aka circle that are being created, but I would not suggest it in production.
