### ISSUE TITLE
Dynamically registering and removing routes

### ISSUE THREAD

**Issue by vorillaz** [fastify/help#149]
Hello everyone, I have a rather weird issue. I am actually building a development tool which under the hood uses fastify. I need to somehow register and remove routes dynamically based on a manifest generated from another process.

My manifest looks like this:

```json
{
  "/foo": "this is a response",
  "/bar/:id": "this is a response for bar id",
  "/qux": "this is a response",
}
```
Since the manifest changes during development as new items are added or removed I am a bit stuck.
Is there any chance I could dynamically parse these routes and use fastify's routing mechanism?
Thanks in advance.

**Comment by jsumners** [comment]
The route tree is frozen when the server is started because routing is provided by https://www.npmjs.com/package/find-my-way

**Comment by vorillaz** [comment]
Hello, @jsumners thanks for the quick response.
@mcollina suggested opening an issue as it would be great to document the entire idea behind this example.
My initial idea was registering the routes on demand, since this not possible I was thinking that it would be ideal to validate the manifest routes against a wildcard endpoint. Something like:
```js
const routes = {
  "/foo": "response",
  "/bar/:id": "another response"
}

fastify.get('/*', (request, reply) => {
  // validate the route, extract the appropriate params and reply to the client
  // or move to the next route
}))
```
But I am not sure where I should get started.

**Comment by vorillaz** [comment]
I just checked the `find-my-way` package which can work along with a wildcard endpoint.

**Comment by vorillaz** [comment]
The idea of adding a wildcard route and match the appropriate resolution it works but is messy.
I am using `fastify.get('/*', handler)` along with [url-matcher](https://www.npmjs.com/package/url-matcher) and [query-string](https://www.npmjs.com/package/query-string) but this idea looks like abusing the built-in functionality of fastify's routing. 

Should I reconsider my initial purpose of HMR, restart the server and attach any routes on startup?

**Comment by Eomm** [comment]
I think it would be possible, it seems `find my way` supports it:

```
const t = require('tap')
const FindMyWay = require('find-my-way')

t.test('dynamics path', t => {
  const findMyWay = FindMyWay()
  const fixedPath = function staticPath () {}
  const varPath = function parameterPath () {}
  findMyWay.on('GET', '/a/b', fixedPath)
  t.equals(findMyWay.find('GET', '/a/b').handler, fixedPath)

  findMyWay.on('GET', '/a/c', varPath)
  t.equals(findMyWay.find('GET', '/a/c').handler, varPath)

  t.equals(findMyWay.find('GET', '/a/z'), null) // ops missing route
  setTimeout(() => {
    // add route after a while
    findMyWay.on('GET', '/a/z', fixedPath)
  }, 100)

  setTimeout(() => {
    // now the route exists!
    t.equals(findMyWay.find('GET', '/a/z').handler, fixedPath)
    t.end()
  }, 1000)
})
```

We should think if:
- we could ship this feature in core as opt-in feature
- build a plugin for this where there will be a router totally detached by the server one

**Comment by mcollina** [comment]
@Eomm I think so. This seems a popular enough feature that we should support. Note that certain features will likely not be available such as 

1. plugin loading (currently each route use `after`, which is a like a plugin in avvio lingo, so there is some work there)
2. shared schemas

I think we might be able to implement some opt-in behavior for this: we should take care in not leaking memory.

**Comment by vorillaz** [comment]
Hey @Eomm, thanks for the response. I am still struggling to pipe the `find-my-way` router with the fastify lifecycle and also take care of the statically attached routes.

**Comment by cyb3rs4pi3n** [comment]
@vorillaz try using [fastify-url-data](https://github.com/fastify/fastify-url-data)
You can get the path data and then based on the path call appropriate methods to handle the request

**Comment by cyb3rs4pi3n** [comment]
example code:

```
fastify.register(require('fastify-url-data'), (err) => {
  if (err) throw err
})

fastify.get('/*', (req, reply) => {
  const urlData = req.urlData()
  if(urlData.path === "<your route path here>"). //check the path
  { // do the stuff here
      reply.send({hello: 'world'})
  }
  .......... // more cases
})
```

**Comment by Eomm** [comment]
Only as memo:
this feature should have many security checks is it will open to injection

**Comment by jakehamilton** [comment]
Hi folks, was this ever worked on? I'm building out a system that needs to register and unregister routes at runtime. I think the routing library used under the hood supports removing routes and listeners, but I'm not sure if Fastify does anything else with the registered routes.

**Comment by pcfreak30** [comment]
I've run into this now as well. I can see `find-my-way` *supports* it... but fastify does not directly expose the router object reference currently, so I cant call `off`.

**Comment by lohfu** [comment]
It seems pretty clear from the following comment that there are guards in place to prevent this functionality: https://github.com/fastify/fastify/blob/c44ba740d21900cef3b5708481f8719b98793923/lib/route.js#L169-L171

@mcollina Is it even feasible to try to implement this functionality? If so, I wouldn't mind taking a stab at it, but I would probably require some hand holding...

**Comment by JVKdouk** [comment]
Would love to get any updates on this feature. I'm using Fastify for a custom CMS and it requires re-registering routes for a better development experience. This feature would open up the doors for lazy loading and hot realod of routes

**Comment by sku0x20** [comment]
my specific use case is using fastify as mock/fake server for e2e tests.

- start mock sever before any tests
- add/remove paths test to test basis
- no global paths

find-my-way seems to be working. idk the caveats with this approach though.
