### ISSUE TITLE
Detect the end of a request

### ISSUE THREAD

**Issue by NetOperatorWibby** [fastify/help#15]
_Coming from Gitter_

#### What are you trying to achieve or the steps to reproduce?

I have an analytics plugin that works in Express and I want to make it work for my new fastify-based app. In Express, I achieve this by placing my plugin after the body parser and other middleware.

```js
"use strict";

const fp = require("fastify-plugin");

module.exports = exports = fp(async (fastify, opts, next) => {
  fastify.addHook("preHandler", (request, reply, next) => {
    console.log(request.raw.url); // appears as many times as you have images/css/&c
    next();
  });

  fastify.addHook("onSend", (request, reply, payload, next) => {
    console.log(request.raw.url); // appears as many times as you have images/css/&c
    next();
  });

  fastify.addHook("onResponse", (res, next) => {
    console.log("hi"); // appears as many times as you have images/css/&c
    next();
  });

  next();
}, { fastify: "1.5.x" });
```

#### What was the result you received?

As mentioned in the code above, I get multiple responses.

#### What did you expect?

I just want ONE response object that gives me the URL.

#### Context

* *node version*: 10.3.0
* *fastify version*: 1.5.0
* *os*: macOS

**Comment by delvedor** [comment]
Hi! I'm sorry but I don't understand very well your issue.
What are you trying to achieve?
Every hook you register will be executed for every request.
Checkout our [request lifecycle](https://www.fastify.io/docs/latest/Lifecycle/) diagram.

**Comment by NetOperatorWibby** [comment]
Using the `preHandler` and `onSend` functions as examples. When you visit a page in an app, you'll see something like this in the console:

```bash
/about
/assets/css/style.css
/assets/scripts/vendor/zepto.js
/assets/scripts/app.js
/assets/media/images/grid-bg.png
/assets/media/images/logo.svg
```

There are 6 requests there. To be clear, I saw the same thing in Express apps until I set my plugin last in app instantiation. Here's an example:

```js
const app = express()
  // ...after setting views, body parsing, &c
  .use(my-plugin("ANALYTICS-SITE-ID"));
```

In Express, at the very end of app instantiation I get just one `request` object. I want to emulate this in `fastify`. I hope this is clearer.

**Comment by nwoltman** [comment]
@NetOperatorWibby It's still unclear exactly when you want your plugin to run. Should it run only for certain routes? It would help if you posted an example of it working correctly in Express so we could see what it is you're trying to achieve.

**Comment by NetOperatorWibby** [comment]
Here's the source of my plugin: https://git.inc.sh/IdeasNeverCease/chewit

**Comment by nwoltman** [comment]
Alright, I think I understand now. You want your plugin to run on all routes but not on responses for [static assets](https://git.inc.sh/NetOperatorWibby/express-boilerplate/src/branch/master/server/app.js#L30).

To accomplish this in Fastify, users of your plugin will need to create a new encapsulation level using `fastify.register()` so that your plugin will only run on their routes and not on their static assets.

```js
const Fastify = require('fastify');
const path = require('path');

const fastify = Fastify();

// Register static assets
fastify.register(require('fastify-static'), {
  root: path.join(__dirname, 'assets'),
  prefix: '/assets/',
});

// Encapsulate routes and your plugin
fastify.register((fastify, options, next) => {
  // Register your plugin
  fastify.register(require('chewit'), {
    chewID: 'chew-id',
  });

  // Register routes
  fastify.get(/* ... */);

  next();
});
```

**Comment by NetOperatorWibby** [comment]
*smacks head*

I didn't even think about this. Thanks for taking the time to walk me through this as I fumbled through asking questions.

**Comment by nwoltman** [comment]
@NetOperatorWibby No problem! Happy to help 🙂
