### ISSUE TITLE
onRequest error throwing

### ISSUE THREAD

**Issue by borabaloglu** [fastify/help#150]
Hi, I am using onRequest and preHandler to check tokens and set user information to the body etc.

Here is my onRequest and preHandler codes: 

```javascript
const handleAuthOnRequest = async (request) => {
  const payload = await helpers.decryptToken(request.cookies.token, request.headers["user-agent"]);
  request.user = payload;
};

const handleAuthPreHandler = async (request) => {
  if (request.body) {
    request.body.userId = request.user.userId;
    request.body.username = request.user.username;
    request.body.email = request.user.email;
  } else {
    request.body = {
      userId: request.user.userId,
      username: request.user.username,
      email: request.user.email,
    };
  }
};

...

server.route({
  method: "GET",
  url: "/me",
  onRequest: handleAuthOnRequest,
  preHandler: handleAuthPreHandler,
  handler: async (request, reply) => userControllers.finder.findOneById(request, reply),
});

```

If the token is undefined or null or expired, helpers.decryptToken throws an error. The problem is that, it is not catched by global error handler. However, it's sent to client with status 200 because it didn't pass into global error handler. Here is the code of error handler:

```javascript
// server refers to fastify object
server.setErrorHandler(async (error, request, reply) => {
  reply.status(500);
  reply.send(error);
});
```
Can you help me please?

**Comment by mcollina** [comment]
Would you mind to add a self-runnable example to reproduce your problem?

**Comment by borabaloglu** [comment]
Here is a screenshot of terminal and browser:

![image](https://user-images.githubusercontent.com/25693822/75877225-40f93c80-5e28-11ea-89e6-a0f01d03ebd6.png)

![image](https://user-images.githubusercontent.com/25693822/75877259-553d3980-5e28-11ea-8ad9-07a001ad047b.png)

Is it OK for you? I may not understand you :/

**Comment by mcollina** [comment]
Would you mind to write a simple example that we can run that shows your problem? From our tests the logic is there to handle this case.

**Comment by borabaloglu** [comment]
https://github.com/borabaloglu/fastify-onRequest-global-error

You can download and run this code. It is working on localhost:5000.

Or you can take a look to this gist:

https://gist.github.com/borabaloglu/00b2326c82f4473f622fd06be1294bb0

I hope it will help you. I did a little experiment while waiting answer, it may happened because of throwing an object, not an Error. When I changed the

```javascript
throw {
  code: 1234
}
```

with,

```javascript
throw new Error("1234");
```

It works.

**Comment by mcollina** [comment]
You should throw errors, not objects. It's really an antipattern in JS.

Il giorno mer 4 mar 2020 alle ore 13:16 Bora Baloglu <
notifications@github.com> ha scritto:
