### ISSUE TITLE
provide an avvio instance to fastify constructor/factory

### ISSUE THREAD

**Issue by osher** [fastify/help#151]
## 💬 Questions and Help

Hi. 

My use-case is a CLI that starts with basic tools like logger and config, and based on that config decides if or not to become a web-application. It may become a a web-application, a queue-consumer, or a TCP server, or just do some work as a CLI tool without any additional interfaces.
Therefore - a design goal is to separate my web context from my logic services, so they can be offered as a plugin and be run in any context, given that such a context adapter is found.

Another design goal is that the front-facing interface loads last, after all the services have loaded successfully.

I have just came across fastify and avvio - and I'm very excited!

Is there a built-in by-design way I can start with a context wrapped with avvio, loading plugins as I initiate the process, and - given I detect that I have to load a web interface - pass it to fastify together with all the services it has already loaded, which can then be used in fastify endpoints?

thanks!

**Comment by mcollina** [comment]
Unfortunately This is not possible because we customize Avvio quite a bit in Fastify. However it should be fine if you nest them (wrap Fastify in an avvio plugin). Let me know if you go that route and if you got any issues with it.

**Comment by osher** [comment]
I see. I'm glad I asked...

Well, I suppose I could just wrap Fastify in an avvio plugin.
 
My first thought was to handle the initiation sequence outside of the web context myself, and when I get to load a web-interface - I'll pass all the services initiated so far on my IOC bag to the web-interface layer, which will in turn bridge the gap by decorate the fastify instance with all the services found on that ioc bag.

I was just hoping it would be supported out of the box in some manner, especially if I use the same underlying mechanisms...

If you did not hear me complaining - that's what I ended up doing :)
