### ISSUE TITLE
Production-ready config

### ISSUE THREAD

**Issue by Altiano** [fastify/help#153]
What do I need to configure to make fastify a production-ready?
besides HTTPS

**Comment by Eomm** [comment]
All the options are [documented here](https://github.com/fastify/fastify/blob/master/docs/Server.md#factory), also how to set HTTPS.

The config is based on your network architecture.

Because my prod config is simply:

```
fastify({
  logger: myLogger,
  disableRequestLogging: true
}
```
But is based on my needs..
