### ISSUE TITLE
Different body validation schemas depending on Content-Type

### ISSUE THREAD

**Issue by zmeyc** [fastify/help#154]
Is it possible to use different body validation schemas depending on Content-Type?

For example, if URL is /user/123 and Content-Type is application/user-brief+json, use

```
  body: {
    type: 'object',
    properties: {
      user_id: { type: 'string' },
      username: { type: 'string' }
    }
  },
```

if URL is /user/123 and Content-Type is application/user-detailed+json

```
  body: {
    type: 'object',
    properties: {
      user_id: { type: 'string' },
      username: { type: 'string' },
      address: { type: 'string' },
      other_details: ...
    }
  },
```

Should I create separate routes? If yes, how to branch in them depending on Content-Type?

**Comment by Eomm** [comment]
I think it is doable with this plugin: [fastify-schema-constraint](https://github.com/Eomm/fastify-schema-constraint/#usage)

**Comment by zmeyc** [comment]
Thank you!
