### ISSUE TITLE
Fastify instance and request have different loggers

### ISSUE THREAD

**Issue by isaldin** [fastify/help#156]
Hi, guys! I have a question related to logger.
It's strange, but I have a two different loggers in server object and request object.

Init fastify:
```js
import fastify, { FastifyInstance } from 'fastify';
import pino from 'pino';
const server: FastifyInstance<Server, IncomingMessage, ServerResponse> = fastify({
  logger: pino({ level: 'debug' }), // there is not a difference how to setup logger. {logger: true} has same effect too
});
```

For example
```js
server.addHook('preHandler', (req, _reply, done) => {
  console.log({ req: req.log, server: server.log });
});
```
has output
```
{
  req: Pino {
    trace: [Function: noop],
    debug: [Function: noop],
    info: [Function: noop],
    warn: [Function: LOG],
    error: [Function: LOG],
    fatal: [Function: fatal],
    ...
  },
  server: Pino {
    trace: [Function: noop],
    debug: [Function: LOG],
    info: [Function: LOG],
    warn: [Function: LOG],
    error: [Function: LOG],
    fatal: [Function: fatal],
    ...
  }
}
```

* *node version*: v12.16.1
* *fastify version*: 2.12.1
* *os*: Mac
* starting with ts-node

I was looking for in issues something related to this problem, but nothing was found

(sorry for my English)

**Comment by mcollina** [comment]
> It's strange, but I have a two different loggers in server object and request object.

This is normal because every request gets its own child logger with the request id set.
What I do not understand is why the `debug` level is not propagated correctly.

**Comment by mcollina** [comment]
I cannot reproduce your issue. Can you please upload a fully running example in pure JavaScript? Thanks.

**Comment by isaldin** [comment]
I'm so sorry. It was my mistake: my route had logLevel 'warn'
