### ISSUE TITLE
Issues creating Stripe webhooks with signature checking

### ISSUE THREAD

**Issue by NetZeroApp** [fastify/help#158]
#### You have already researched for similiar issues?

Yes, I found someone experiencing a similar issue: https://github.com/fastify/fastify/issues/1965

However, it didn't help me fix the issues I'm having. Some advice would be appreciated!

#### What are you trying to achieve or the steps to reproduce?

I'm trying to set up Stripe webhooks with signature checking (https://stripe.com/docs/webhooks/signatures) but I keep getting the same error: `No signatures found matching the expected signature for payload. Are you passing the raw body you received from Stripe?`.

Here's my code to compare to the Stripe example on their page:

```js
// Stripe stuff
const endpointSecret = process.env.STRIPE_ENDPOINT_SECRET
const stripe = require('stripe')(process.env.STRIPE_SECRET)

// Webhook endpoint
fastify.post('/webhook', async (request, reply) => {
  const sig = request.headers['stripe-signature']

  let event
  try {
    event = stripe.webhooks.constructEvent(request.body, sig, endpointSecret)
  } catch (err) {
    console.log(err.message)
    throw new Error(err.message)
  }

  switch (event.type) {
    case 'payment_intent.succeeded':
      // const paymentIntent = event.data.object
      console.log('PaymentIntent was successful!')
      break
    default:
      console.error('Event type not supported')
      return
  }

  reply.code(200).send({ received: true })
  return
})
```

Having done some research and debugging, I believe it's something to do with the `request.body` being passed to `constructEvent`, especially since I can confirm the `endpointSecret` and `sig` variables are both correct. It's what is suggested in other similar issues that people have experienced using the Stripe API, but they were all using Express.

#### What was the result you received?

This error:

`No signatures found matching the expected signature for payload. Are you passing the raw body you received from Stripe?`

#### What did you expect?

A console log: `PaymentIntent was successful!`

#### Context

* *node version*: 12.7.0
* *fastify version*: 2.12.1
* *os*: Mac
* *any other relevant information*: None that I know of, I'm not doing anything particularly difficult on the server!

Thanks in advance, this is the only issue I've really stumbled across when using Fastify, loving it so far!

**Comment by Ethan-Arrowood** [comment]
Is constructEvent async? You may be missing an `await` keyword

**Comment by Eomm** [comment]
You need to give a string as the first parameter
```
// fast solution
stripe.webhooks.constructEvent(JSON.stringify(request.body), sig, endpointSecret)
```

Be careful to resubmit request's body without checking it (with a json schema for example)


PS: it would really great if you could arrange an example with fastify [in the official docs!](https://github.com/stripe/stripe-node#webhook-signing)

**Comment by NetZeroApp** [comment]
> Is constructEvent async? You may be missing an `await` keyword

Thanks @Ethan-Arrowood , I tried it with both `await` and without. The official docs use it without, so I'm going with that for now!



> You need to give a string as the first parameter
> 
> ```
> // fast solution
> stripe.webhooks.constructEvent(JSON.stringify(request.body), sig, endpointSecret)
> ```
> 
> Be careful to resubmit request's body without checking it (with a json schema for example)

Thanks @Eomm, I'll give it a go after my upcoming meeting and let you know. And I'll add the checking once it's working 👍

**Comment by NetZeroApp** [comment]
@Eomm just following up that this still isn't working, but it's not necessarily a deal-breaker. I'm still stumped but it's quite difficult to determine whether it's a Fastify issue or an issue with Stripe (though, they haven't had any issues reported).

Thanks for your help, though!

**Comment by Eomm** [comment]
Sorry, try this one:

```
Buffer.from(JSON.stringify(request.body))
```

I [read the docs of bodyparser](https://github.com/expressjs/body-parser#bodyparserrawoptions) and it returns a `Buffer` not a string as I thought (since in the express example `bodyParser.raw({type: 'application/json'})` is used.

Note the this is not the fastest solution (too many conversion..), but it should work 👍

**Comment by NetZeroApp** [comment]
@Eomm thanks but that still doesn't work! No bother, right now, as I have other issues...

I won't be revisiting this for a while if you want to close it?

Thanks!

**Comment by Eomm** [comment]
This seems strange!

Please, keep us updated if you find the solution!

**Comment by emma-clicknclear** [comment]
Hey all, found a solution for this and wanted to share!

Firstly, install the raw-body package. Then in your webhook route file, add the following:

```ts
import rawBody from 'raw-body'

const router: Plugin = (fastify, options, next) => {

  fastify.addContentTypeParser('application/json', (req, done) => {
    rawBody(req, {
      length: req.headers['content-length'],
      limit: '1mb'
    }, (err, body) => {
      if (err) return done(err)
      done(null, body)
    })
  })

  fastify.route<DefaultQuery, DefaultParams, DefaultHeaders, DefaultBody>({
    url: '/',
    method: 'POST',
    handler: async (req) => {
      try {
        event = stripe.webhooks.constructEvent(
          req.body,
          req.headers["stripe-signature"],
          STRIPE_WEB_KEY
        );
      } catch (err) {
        throw new UnauthorizedError(`⚠️  Webhook signature verification failed.`);
      }
      return true
    }
  })

  next()
}
```

This is in TypeScript, so adjust as necessary. Bear in mind that adding the contentTypeParser at a root level or having other routes depending on req.body to be JSON will result in errors, so it is best to sit the webhook on its own.

**Comment by Eomm** [comment]
Thanks for sharing!

If you have the chance, it would be interesting to understand what change from `req.body` and `req.body` with the default content parser since there is not JSON schema, I would expect the same but it seems not 😓

**Comment by bykof** [comment]
Here is the ES6 version (without typescript):

I wrapped it inside a single register to have the contentTypeParser only for my /webhook route

```
import rawBody from 'raw-body'

fastify.register((fastify, opts, done) => {
    fastify.addContentTypeParser('application/json', async (req, done) => {
      try {
        const body = await rawBody(req, {
          length: req.headers['content-length'],
          limit: '1mb'
        })
        return done(null, body)
      } catch (err) {
        return done(err)
      }
    })
    fastify.post('/webhook', paymentWebhook)
    done()
  })
```

and inside my paymentWebhook function: 

```
export const paymentWebhook = (request, reply) => {
  const signature = request.headers['stripe-signature']
  let event

  try {
    event = Stripe.webhooks.constructEvent(
      request.body,
      signature,
      process.env.STRIPE_WEBHOOK_SECRET
    )
  } catch (err) {
    return reply.code(400).send(`Webhook Error: ${err.message}`)
  }

  // Handle the event
  switch (event.type) {
    case 'payment_intent.succeeded':
      const paymentIntent = event.data.object
      console.log('PaymentIntent was successful!')
      break
    default:
      return reply.code(400).send()
  }

  return reply.send({ received: true })
}
```

**Comment by Skogsfrae** [comment]
I encountered the same problem.
The reason why `JSON.stringify(req.body)` does not work is that stripe json is prettified and padded, while `JSON.stringify` parse the object as a plain string.
Stripe signature check computes sha256 of the raw payload, so the lack of white characters in `JSON.stringify(req.body)` results in a different sha256 than the expected one.

It would be useful to have the unparsed body in the request object as well.

**Comment by Skogsfrae** [comment]
UPDATE:
With the merge of PR #2286 in fastify 2.15.0 it's now possible to get the raw body of the request without additional libraries.
This works out of the box:

```javascript
(fastify, opts, next) => {
  fastify.addContentTypeParser(
    'application/json',
    { parseAs: 'buffer' },
    function (req, body, done) {
      try {
        var newBody = {
          raw: body
        }
        done(null, newBody)
      } catch (error) {
        error.statusCode = 400
        done(error, undefined)
      }
    }
  )

  fastify.post('/stripe/myhook', {
    handler: async (req, res) => {
      const sig = req.headers['stripe-signature']
      const webhookSecret = 'whsec_d....'

      const event = stripe.webhooks.constructEvent(req.body.raw, sig, webhookSecret)
      .....
    }
  })

  next()
}
```

**Comment by tot-ra** [comment]
The problem with the last suggestion is that its global, so if you have `/graphql` endpoint, then it may get broken.
I used https://www.npmjs.com/package/fastify-raw-body as a workaround to get raw body only in specific endpoint

**Comment by jekh** [comment]
> The problem with the last suggestion is that its global, so if you have `/graphql` endpoint, then it may get broken. I used https://www.npmjs.com/package/fastify-raw-body as a workaround to get raw body only in specific endpoint

If you register @Skogsfrae 's solution as a plugin, it will be scoped to the requests within that plugin and won't be global. Using `fastify-raw-body` is also a good solution.

Since Stripe's `constructEvent` parses the raw request buffer in the process of verifying the webhook signature, you don't need to manually parse JSON.parse the raw request.body. The `addContentTypeParser` can be simplified to:
```ts
  fastify.addContentTypeParser(
    "application/json",
    { parseAs: "buffer" },
    function (_req, body, done) {
      try {
        done(null, body)
      } catch (error) {
        error.statusCode = 400
        done(error, undefined)
      }
    }
  )
```

There's no need for the "raw" property on the body if it's just being used for Stripe webhooks. The webhook can be validated and parsed like this:
```ts
fastify.post("/my/stripe/webhook/endpoint", async function (request, reply) {
  const stripeEvent = stripe.webhooks.constructEvent(
        request.body,
        request.headers["stripe-signature"],
        stripeWebhookSecret)
```

**Comment by victor-pagnozi** [comment]
> UPDATE: With the merge of PR [fastify/fastify#2286](https://github.com/fastify/fastify/pull/2286) in fastify 2.15.0 it's now possible to get the raw body of the request without additional libraries. This works out of the box:
> 
> ```js
> (fastify, opts, next) => {
>   fastify.addContentTypeParser(
>     'application/json',
>     { parseAs: 'buffer' },
>     function (req, body, done) {
>       try {
>         var newBody = {
>           raw: body
>         }
>         done(null, newBody)
>       } catch (error) {
>         error.statusCode = 400
>         done(error, undefined)
>       }
>     }
>   )
> 
>   fastify.post('/stripe/myhook', {
>     handler: async (req, res) => {
>       const sig = req.headers['stripe-signature']
>       const webhookSecret = 'whsec_d....'
> 
>       const event = stripe.webhooks.constructEvent(req.body.raw, sig, webhookSecret)
>       .....
>     }
>   })
> 
>   next()
> }
> ```

I had the same error today and this code solve the error!!! Tkss

**Comment by m3k3r1** [comment]
> UPDATE: With the merge of PR [fastify/fastify#2286](https://github.com/fastify/fastify/pull/2286) in fastify 2.15.0 it's now possible to get the raw body of the request without additional libraries. This works out of the box:
> 
> ```js
> (fastify, opts, next) => {
>   fastify.addContentTypeParser(
>     'application/json',
>     { parseAs: 'buffer' },
>     function (req, body, done) {
>       try {
>         var newBody = {
>           raw: body
>         }
>         done(null, newBody)
>       } catch (error) {
>         error.statusCode = 400
>         done(error, undefined)
>       }
>     }
>   )
> 
>   fastify.post('/stripe/myhook', {
>     handler: async (req, res) => {
>       const sig = req.headers['stripe-signature']
>       const webhookSecret = 'whsec_d....'
> 
>       const event = stripe.webhooks.constructEvent(req.body.raw, sig, webhookSecret)
>       .....
>     }
>   })
> 
>   next()
> }
> ```

THANK YOU !!! You are still saving lives 4 years later

**Comment by MikePresman** [comment]
omg thank you for this thread, i was at my wits end
