### ISSUE TITLE
How to Configure CORS Asynchronously in fastify-cors

### ISSUE THREAD

**Issue by chaitanya-apty** [fastify/help#159]
#### How can I add corsOptionsDelegate to fastify-cors
In default cors package of express, there is a way you can add cors options asynchronously which enables the developer to read the headers/origins of an HTTP request.
This feature enables todo certain prechecks as whitelist origins, bypass cors etc

```js
// Something like this (Below screenshot is from Express-cors Lib)
var whitelist = ['http://example1.com', 'http://example2.com']
var corsOptionsDelegate = function (req, callback) {
  var corsOptions;
  if (whitelist.indexOf(req.header('Origin')) !== -1) {
    corsOptions = { origin: true } // reflect (enable) the requested origin in the CORS response
  } else {
    corsOptions = { origin: false } // disable CORS for this request
  }
  callback(null, corsOptions) // callback expects two parameters: error and options
}

Now we will call delegate options as : cors(corsOptionsDelegate)
```

#### My Question!
How to achieve the same functionality with fastify-cors package!
As there is no documentation for that!

Is there any alternative way to achieve?
#### Context

* *node version*: 10.16
* *fastify version*: 2.13
* *fastify-cors*: 3.0.2

**Comment by Eomm** [comment]
You should be able to archive it like this:

```
fastify.register(require('fastify-cors'), { 
  origin: ['http://example1.com', 'http://example2.com']
})
```

Note that you can pass also regexp instead of strings

**Comment by chaitanya-apty** [comment]
@Eomm ,
My use case is different!
As I have mentioned in the request, I need to check for the headers of a request!

**Comment by chaitanya-apty** [comment]
@Eomm ,
YOu can refer my use case here : https://expressjs.com/en/resources/middleware/cors.html#configuring-cors-asynchronously

**Comment by Eomm** [comment]
So you what to skip the CORS for some requests

This should skip CORS: pass to the callback false without the error 

origin: (origin, cb) => { if(/localhost/.test(origin)){ // Request from localhost will pass cb(null, true) return } cb(null, false) }

**Comment by Eomm** [comment]
PS if you need the request as input to the function we need a pr to support it, since only the origin header is pass as argument
