### ISSUE TITLE
How to use fastidy schema and allOf

### ISSUE THREAD

**Issue by SkeLLLa** [fastify/help#16]
#### What are you trying to achieve or the steps to reproduce?

I'm trying to merge two definitions into one using `allOf`. According to this https://github.com/fastify/fast-json-stringify/blob/0325292709882c8b523137649760b02c95460199/test/allof.test.js it works with full schema definition. And I want to get it work with references.

```js
  fastify.addSchema({
    $id: 'objA',
    type: 'object',
    properties: {
      a: {
        type: 'string',
        description: 'a',
      },
    },
  });
  fastify.addSchema({
    $id: 'objB',
    type: 'object',
    properties: {
      b: {
        type: 'string',
        description: 'b',
      },
    },
  });
    fastify.addSchema({
    $id: 'all',
    type: 'object',
      allOf: [
        {$ref: 'objA#'},
        {$ref: 'objB#'},
      ],
  });
```

#### What was the result you received?
When using `all#` schema it fails with error `data.allOf[0].$ref should be string`. If I supply wrong id (without `#` for example) it says that `Schema with id 'wrong_objA' does not exist!`

#### Context

* *node version*: 9
* *fastify version*: 1.6.0
* *os*: Linux

**Comment by PavelPolyakov** [comment]
I have an example which works for me, but it doesn't include `$ref`:

```javascript
fastify.post('/route', {
    schema: {
      body: {
        type: 'object',
        properties: {
          email: {
            allOf: [
              { type: 'string', format: 'email' },
              { type: 'string', pattern: '^(?!.*@mailinator\.com).*$' },
            ],
          },
        },
      },
    },
  }, handler);
```

**Comment by PacoDu** [comment]
This is what I use to getaround `$ref` unavailability in fastify:

```javascript
'use strict'

const defs = {
  id: {
    type: 'string',
    pattern: '^[a-f0-9]{24}$'
  },
  title: {
    type: 'string',
    pattern: '^[\w ]*[^\W_][\w ]{0,50}$',
  }
}

const schema = {
  $id: 'story',
  type: 'object',
  properties: {
    id: defs.id,
    title: defs.title,
  }
}

module.exports = {
  schema,
  defs
}
```

**Comment by Eomm** [comment]
In the master version you have only to write:
```js
fastify.addSchema({
  $id: 'all',
  type: 'object',
  allOf: [
    'objA#',
    'objB#'
  ]
})
```

This is not a standard feature of json-schema.

I'm working to improve the docs and make them more clear for issues like this one 👍
