### ISSUE TITLE
Struggling to deploy my app to Heroku

### ISSUE THREAD

**Issue by NetZeroApp** [fastify/help#160]
#### You have already researched for similar issues?

Yes! More than I'd like to admit...

#### What are you trying to achieve or the steps to reproduce?

I'm trying to deploy my server to Heroku (as a `staging` server right now) and although it is building, it seems to be closing the connection as soon as a request is made. I'm using Parcel to do the bundling (this worked with our old Koa server) and I feel this may be the culprit. If so, what are you or others using to bundle your server(s) and do you have a config? Right now, I feel our API is still relatively simple...

Here is my `server.js` file:

```js
'use strict'

require('dotenv').config()
require('make-promises-safe')

const fastify = require('fastify')({
  https: process.env.NODE_ENV === 'development' ? false : true,
})
const helmet = require('fastify-helmet')
const Sentry = require('@sentry/node')

// Sentry
const pkg = require('../package.json')
Sentry.init({
  dsn: process.env.SENTRY_DSN,
  environment: process.env.NODE_ENV,
  release: `netzero-api@${pkg.version}`,
})

// Fastify sentry hook
fastify.addHook('onError', (request, reply, error, done) => {
  // Only send Sentry errors when not in development
  if (process.env.NODE_ENV !== 'development') {
    Sentry.captureException(error)
  }
  done()
})

// Helmet
fastify.register(helmet, {
  hsts: false,
})

// Authentication
fastify.register(require('fastify-auth'))
const verifyJWT = require('./lib/verify')
fastify.decorate('verifyJWT', verifyJWT)

// Routes
fastify.register(require('./routes/health'))
fastify.register(require('./routes/auth'))
fastify.register(require('./routes/billing'))
fastify.register(require('./routes/purchases'))

// Set up and start server
const port = process.env.PORT || 4000
const start = async () => {
  try {
    await fastify.listen(port, '0.0.0.0')
    console.log(`🚀 Listening on port ${fastify.server.address().port}`)
  } catch (err) {
    console.error(err)
    Sentry.captureException(err)
    process.exit(1)
  }
}
start()
```

In the case of this file, I've tried disabling all routes apart from `health`, removing Sentry and authentication and none of it has worked. I'm wondering if it's to do with my `build` process, so here is part of my `package.json`:

```json
{
  "main": "dist/server.js",
  "scripts": {
    "test": "test",
    "dev": "cross-env NODE_ENV=development DATABASE_URL=$(heroku config:get DATABASE_URL -a netzero-staging) REDIS_URL=$(heroku config:get REDIS_URL -a netzero-staging) nodemon --exec babel-node src/server.js",
    "build": "parcel build src/server.js --target node",
    "start": "node dist/server.js"
  }
}
```

#### What was the result you received?

The following error from Heroku:

`2020-03-29T14:19:19.571338+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/health" host=netzero-staging.herokuapp.com request_id=7f9a4ee3-e65a-40a1-bdb4-984d632e8c52 fwd="90.253.58.253" dyno=web.1 connect=0ms service=3ms status=503 bytes=0 protocol=https`

#### What did you expect?

I expected to see a 200 response.

#### Context

* *node version*: 12.16.1
* *fastify version*: 2.13.0
* *os*: Whatever Heroku uses (probably Linux)
* *any other relevant information*: I'm using parcel to bundle the server. Is there a different recommended bundler (and config) to get this working?

**Comment by mcollina** [comment]
What’s in your /health route?

**Comment by NetZeroApp** [comment]
> What’s in your /health route?

Hi @mcollina and thanks for the fast response. Here it is!:

```js
async function routes(fastify) {
  fastify.get('/health', async (request, reply) => {
    try {
      reply.code(200).send({ status: 'ok' })
    } catch (err) {
      throw new Error(err)
    }
  })
}

module.exports = routes
```

**Comment by mcollina** [comment]
You do not need the try catch and async there (however that’s unlikely to be the problem in your case).

I do not know what’s the issue, it’s definitely in your application as I’ve used Fastify on Heruku multiple times. I would recommend you to build a simple example that we can run that shows your issue.

**Comment by NetZeroApp** [comment]
Thanks @mcollina I'll throw something together a bit later on. Out of curiosity, when you deployed to Heroku did you use a bundler? If so, which and what was your config?

**Comment by NetZeroApp** [comment]
Just an extra comment to say it's not my bundler, it's 100% part of the application *somewhere*. It runs locally without issue, though, which only makes this more confusing.

**Comment by Eomm** [comment]
Do you upload also the dot env file?

**Comment by NetZeroApp** [comment]
@Eomm and @mcollina I finally found this issue. It was with this:

```js
const fastify = require('fastify')({
  https: process.env.NODE_ENV === 'development' ? false : true,
})
```

Changing it to the following fixed it for me:

```js
const fastify = require('fastify')({
  https: process.env.NODE_ENV !== 'production' ? false : true
})
```

It was a simple fix, in the end, just a shame it took me 2 days to find it...
