### ISSUE TITLE
I built a fastify plugin, but cannot meet the plugin criteria

### ISSUE THREAD

**Issue by mkinoshi** [fastify/help#163]
### Context

I built a fastify plugin that is working on our current production environment. [Here](https://github.com/mkinoshi/fastify-gcloud-trace) is the plugin repo. I plan to support more features related to OpenCensus API or Stackdriver API in the future. Since I thought it would be useful to some other people, I wanted to contribute this plugin as a fastify community plugin. However, this plugin is built on top of [Stackdriver Trace for Node.js](https://github.com/googleapis/cloud-trace-nodejs), and this package requires node version 8 or higher. This means that my plugin cannot support node version 6, and it doesn’t follow the fastify plugin guideline.

### Questions

What do you think it the best course of action I should take if I want to contribute this plugin to the community? If you have any idea or if I am missing something, please let me know! Any feedback to the plugin itself will be also very welcome.

**Comment by Ethan-Arrowood** [comment]
Good news: we are dropping (if not have already dropped) support for versions 6 and 8! Looks like something in our docs needs updated. Would you like to submit a pr to update our docs as well as include your plugin? We can then give it a proper review there

**Comment by mkinoshi** [comment]
@Ethan-Arrowood, awesome that is great to hear! I'm happy to update the documentation as well regarding the supported versions. However, I actually did not find a clear mention of what Node versions should be supported in the documentation. [It](https://github.com/fastify/fastify/blob/master/CONTRIBUTING.md#plugins) It says "the Node.js compatibility must match with the Fastify's master branch." I went into the master branch and  checked the engine version specified in `package.json` and `.travis.yml`, and assumed that Fastify still supports version 6. 

Should I add a clear mention of what versions should be supported in the documentation? I think it is probably nice to update `package.json` and `.travis.yml` in that case.

**Comment by Ethan-Arrowood** [comment]
Yes version 2 needs 6 and 8 support: https://www.fastify.io/docs/latest/LTS/

But version 3 which is right around the corner is dropping 6: https://github.com/fastify/fastify/blob/next/docs/LTS.md#schedule

**Comment by mkinoshi** [comment]
I see, sorry I missed that section. It seems clear enough from the documentation. Should I just create a PR for my plugin in the `next` branch ? I'm pretty new to this community, and open source projects in general, so there are still things that I'm not familiar with.

**Comment by mkinoshi** [comment]
I can also create a PR once version 3 is out too.

**Comment by mcollina** [comment]
Go ahead and send the PR, we should probably update the criteria. New plugins should not support deprecated Node.js versions.

**Comment by Ethan-Arrowood** [comment]
Yes target `next` branch; that will become version 3 soon. Let me know if you need any help at all making your contribution! I'm happy to help :)
