### ISSUE TITLE
Unable to run bundle emitted by webpack

### ISSUE THREAD

**Issue by shinlos** [fastify/help#165]
#### You have already researched for similiar issues?
Checked for issues within the repo regarding webpack

I have also tried `babel-loader` on top of `ts-loader` but this does not seem to resolve the issue

#### What are you trying to achieve or the steps to reproduce?

I'm using webpack to emit a bundle, which does so successfully
However, running this bundle results in an error. I am using the [Getting-Started example provided on the repo](https://github.com/fastify/fastify/blob/master/docs/Getting-Started.md#your-first-server) which is the content of my `index.ts`, the lone file in this project

webpack.config.js
```js
module.exports = [
  {
    mode: 'development',
    entry: './index.ts',
    target: 'node',
    module: {
      rules: [
        {
          test: /\.ts$/,
          use: [{ loader: 'ts-loader' }],
        },
      ],
    },
    output: {
      path: __dirname + '/dist',
      filename: 'server.js',
    },
  },
]
```

#### What was the result you received?

```
...
webpack:///./node_modules/fastify/lib/contentTypeParser.js?:31
  this.cache = lru(100)
               ^

TypeError: lru is not a function
    at new ContentTypeParser (webpack:///./node_modules/fastify/lib/contentTypeParser.js?:31:16)
    at build (webpack:///./node_modules/fastify/fastify.js?:154:27)
    at eval (webpack:///./index.ts?:9:16)
    at Module../index.ts (C:\Users\Shinlos\Documents\GitHub\node\dist\server.js:97:1)
    at __webpack_require__ (C:\Users\Shinlos\Documents\GitHub\node\dist\server.js:20:30)
    at C:\Users\Shinlos\Documents\GitHub\node\dist\server.js:84:18
    at Object.<anonymous> (C:\Users\Shinlos\Documents\GitHub\node\dist\server.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
```

#### What did you expect?

Running this bundle `node server.js` throws the error `TypeError: lru is not a function` but I'm not certain how to approach this error at all

Running the original example code as a `.js` file with `node index.js` does work, but I tend to use webpack with my typescript projects, and have been relying on the same configuration file without any issues

Apologies in advance if this is not an error concerning fastify

Any help with this would be greatly appreciated!

#### Context

* *node version*: 12.13.1
* *fastify version*: 2.13.0
* *webpack version*: 4.42.1
* *webpack-cli version*: 3.3.11
* *ts-loader version*: 6.2.2
* *os*: Windows

**Comment by mcollina** [comment]
I do not know how to help unfortunately. This looks like a webpack problem.
