### ISSUE TITLE
How do I access fastify context within hooks?

### ISSUE THREAD

**Issue by guruvi** [fastify/help#168]
I looked for some resources online but couldn't get anything as such. Although I got the below code somewhere in the doc, this doesn't seem to work

```
fastify.addHook('onRequest', function (request, reply, done) {
  const self = this // Fastify context
  done()
})
 ```

I've decorated fastify instance with methods for connecting to database. I have replicated the issue with a small code snippet below.

```
// Require the framework and instantiate it
const fastify = require('fastify')({ logger: true })

fastify.decorate("testing", "testing");

const hook1 = (request, reply, done) => {
  const fastify = this;
  console.log("invoking preHandler hook1");

  console.log("hook1: ", fastify.testing);
  done();
};

fastify.addHook('preHandler', (request, reply, next) => {
  const fastify = this;
  console.log("preHandler: ", fastify.testing);
  
  console.log("invoking preHandler");
  next();
});

// Declare a route
fastify.get('/', {preHandler: hook1}, async (request, reply) => {
  return { hello: 'world' }
})

// Run the server!
const start = async () => {
  try {
    await fastify.listen(3000)
    fastify.log.info(`server listening on ${fastify.server.address().port}`)
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()
```

This should have worked as per the documentation. But it didn't.

* *node version*: v12.16.1
* *fastify version*: >=2.11.0
* *os*: Mac

**Comment by jsumners** [comment]
```js
fastify.addHook('onRequest', function (request, reply, done) {
  const self = this // Fastify context
  done()
})
```

That is not in the documentation:

https://github.com/fastify/fastify/blob/98328a422cdbd65ea2769c44dca3a2a2fff01332/docs/Hooks.md

Please provide a link to where you found such documentation because it is incorrect. The `this` context within an `onRequest` hook is the Fastify request object.

**Comment by guruvi** [comment]
PFB the link from where I found that:
https://www.fastify.io/docs/v2.0.x/Hooks/#scope

I've a method that have access to the database and the method is decorated to the fastify instance. Is there any way I could access that method inside the hook?

**Comment by jsumners** [comment]
🤔 pretty sure it’s bound to the request object. I ran into this just a few days ago. I just decorated the info I needed onto the request object.

**Comment by guruvi** [comment]
Sorry my bad! I used arrow function. in the note it is written.

> Note: using an arrow function will break the binding of this to the Fastify instance.

I really appreciate your help!
