### ISSUE TITLE
tap-tests cause plugin to be loaded twice

### ISSUE THREAD

**Issue by jerrythomas** [fastify/help#171]
#### You have already researched for similar issues?
Yes and I didn't find a matching issue.

#### What are you trying to achieve or the steps to reproduce?
I want to use fastify-metrics as a plugin in a fastify app. 

Adding fastify-metrics to a fastify-cli generated app is easy and it works. However when I add a secondary test to an existing test file, tests run into a problem . App works fine but tests fail.

I wrote a script that generates a minimal example that simulates this issue. 
```bash
fastify generate issue
cd issue
yarn install
yarn upgrade --latest
npm test

# add fastify-metrics plugin
yarn add fastify-metrics
awk '/Place here/{print;print "  fastify.register(require(\"fastify-metrics\"), { endpoint: \"/metrics\" });";next}1' app.js > tmp && mv -f tmp app.js
npm test

# add a duplicate test
FILE=test/services/example.test.js
awk 'NR>=6 && NR<=17' $FILE | sed 's/example/example2/g' >> $FILE
npm test
```

#### What was the result you received?
```text
FAIL  test/services/example.test.js
 ✖ Cannot add the default metrics twice to the same registry

  node_modules/prom-client/lib/defaultMetrics.js                       
  47 |                                                                 
  48 | 	if (last) {                                                    
> 49 | 		throw new Error(                                              
     | --------^                                                       
  50 | 			'Cannot add the default metrics twice to the same registry'  
  51 | 		);                                                            
  52 | 	}                    
```
When you run this script you will notice that the tests are successful for the first two runs. In the third run when there are two tests in the same test file we get the error "Cannot add the default metrics twice to the same registry".

#### What did you expect?
I expected that only the new test should fail. What is the reason that the metrics plugin seems to be added twice. How can I correct this for tests?

```bash
npm start
```
the application runs and I am also able to access the /metrics URL. 
```bash
fastify print-routes app.js
```
```text
└── / (GET)
    ├── metrics (GET)
    └── example (GET)

```

#### Context

* *node version*: v13.12.0
* *fastify version*: 1.5.0
* *os*: Mac
* *any other relevant information*:

**Comment by mcollina** [comment]
This is dependent on fastify-metrics, which is outside of this org.

cc @SkeLLLa

**Comment by SkeLLLa** [comment]
@jerrythomas that's actually a limitation from prom-client. 

For testing I could recommend you to mock, skip registering fastify-metrics at all or disable default metrics. It's not necessary to test them via unit tests.

**Comment by jerrythomas** [comment]
How do you "skip registering fastify-metrics" for the tests? The tests are using the helper method which in turn loads the app.js. Should I register this plugin in a different way?

**Comment by AlexanderTserkovniy** [comment]
@jerrythomas how did you actually achieve that? Just wrapped the `app.register(metricsPlugin, { endpoint: '/metrics' });` into the `if` statement? Or there is NODE_ENV=`something`, which cause it avoiding register?

**Comment by jerrythomas** [comment]
@AlexanderTserkovniy 
Yes. I wrapped the register call in an if statement. NODE_ENV !== 'test'.

**Comment by SkeLLLa** [comment]
> @jerrythomas how did you actually achieve that? Just wrapped the `app.register(metricsPlugin, { endpoint: '/metrics' });` into the `if` statement? Or there is NODE_ENV=`something`, which cause it avoiding register?

You can just pass that check to metrics plugin options to `enableDefaultMetrics: process.env.NODE_ENV === 'testing'` param. Or event both with `enableRouteMetrics`.

**Comment by AlexanderTserkovniy** [comment]
Lovely, thanks guys! Wrapped exactly this way:

> @AlexanderTserkovniy
> Yes. I wrapped the register call in an if statement. NODE_ENV !== 'test'.
