### ISSUE TITLE
How can I access fastify's schema validation function?

### ISSUE THREAD

**Issue by jerrythomas** [fastify/help#173]
#### What are you trying to achieve or the steps to reproduce?

I would like to utilize the built-in schema validation functions to handle additional schema validations not covered by the route data. 

I also want to add additional validation for example: the one below
```js
function validateSnakeCase(schema, value) {
  if (typeof (value) === 'string') {
    validateSnakeCase.errors = [
      {
        keyword: 'snakecase',
        params: { keyword: 'snakecase' },
        message: 'value should be in snakecase',
      },
    ];
    const re = new RegExp('^[a-z]+(([a-z]|_)*[a-z]+)*$');
    return re.test(value);
  }
  return true;
}
```
I can do this using the pattern option, but this allows me to give a more user-friendly error message. I want this to validation to work on the schema routes as a standard and I also want to use the same validator to validate some other data within the app. For example, I want to fetch data from DB and validate that the data matches a schema. 

The [documentation](https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md) mentions the following code

```js
const fastify = require('fastify')()
const Ajv = require('ajv')
const ajv = new Ajv({
  // the fastify defaults (if needed)
  removeAdditional: true,
  useDefaults: true,
  coerceTypes: true,
  allErrors: true,
  nullable: true,
  // any other options
  // ...
})
fastify.setValidatorCompiler(({ schema, method, url, httpPart }) => {
  return ajv.compile(schema)
})
```

I have created a new project using `fastify-cli`. 
Where do I add this code? I tried adding it to the generated app.js. 

#### What was the result you received?

I get the following error.

```bash
  fastify.setValidatorCompiler(({ schema, method, url, httpPart }) => {
          ^

TypeError: fastify.setValidatorCompiler is not a function
```

Once this is configured, what function `fastify.schemaValidator?` can I access to call this validation function? Should I create a custom plugin to expose this validator?

#### Context

* *node version*: 13.13
* *fastify version*: >=^2.0.0
* *os*: Mac
* *any other relevant information*: Used fastify-cli to generate the project. yarn install and yarn upgrade to install the packages.

**Comment by Eomm** [comment]
There are a lot of questions 😀

Right now the docs in master are updated to the future fastify `v3.0` so you should check out the [docs for v2.0](https://www.fastify.io/docs/v2.13.x/Validation-and-Serialization/)

> For example, I want to fetch data from DB and validate that the data matches a schema.

all the function around schemas, must by sync so, to archive this feature there are two options:
- do it in a `preHandler` hook
- read the data from the db and cache it before the fastify start, so you can use the cached data in your sync function (it works for `enum` let's say, not for checking if an `userId` exists, you need to use a `preHandler` hook in this case)

> fastify.setValidatorCompiler(({ schema, method, url, httpPart }) => {

you need to change the code like the following, in v3 it has been renamed and accept more parameters:

```
fastify.setSchemaCompiler(function (schema) {
  return ajv.compile(schema)
})
```

> Once this is configured, what function fastify.schemaValidator? can I access to call this validation function?

you can access the function, that generates the validation function through ajv
for example you can't access the validation function for the body of the route `/hello/world`
but you can generate the same function using `fastify.schemaCompiler` as getter (check the docs).
I used it fo [this plugin](https://github.com/Eomm/fastify-schema-constraint/blob/master/plugin.js) if you want to see a more complete example.

**Comment by jerrythomas** [comment]
Thank you for the help @Eomm. I was able to create a plugin wrapper on this function to achieve what I wanted. Didn't realize that I was looking at the wrong version of docs.
