### ISSUE TITLE
Error handler bug?

### ISSUE THREAD

**Issue by ankology** [fastify/help#175]
Regards! Looking at [Errors Docs](https://www.fastify.io/docs/master/Errors/)
Using this code with GET the error handler works well:

```
app.get('/', () => {
  throw new Error('SAMPLE');
});
```
But, if i change to POST (tried with PUT, etc) the server crashes and error handler does not intercept it..
```
app.post('/', () => {
  throw new Error('SAMPLE');
});
```
Using async handler with POST works..
That behavior works just for GET method, when using "static" throw? Or is a bug? Thanks!

Edit: v2.13.1

**Comment by Eomm** [comment]
> That behavior works just for GET method, when using "static" throw? Or is a bug? Thanks!

That is a behaviour expected: in sync functions, (usually) you manage the errors in callbacks.

In the future fastify v3 this has change and all the errors from async and sync functions will be handled by the custom error handler.

In fact, you linked master, that shows the (future) v3 docs 👍

**Comment by ankology** [comment]
@Eomm Right! Thanks
