### ISSUE TITLE
Disable Plugin Timeout

### ISSUE THREAD

**Issue by dnlup** [fastify/help#176]
#### What are you trying to achieve or the steps to reproduce?

I am trying to disable the plugin timeout when I am in dev mode (`NODE_ENV=development`) because a plugin is very slow to start (https://github.com/fastify/fastify-nextjs) in this scenario.
The module `avvio` supports this (https://github.com/mcollina/avvio#avvioinstance-options-started) but Fastify doesn't (https://github.com/fastify/fastify/blob/master/fastify.js#L264).

```js
const fastify = require('fastify')({ pluginTimeout: 0 })
```

#### What was the result you received?

The timeout remains `10000`.

#### What did you expect?

The timeout to be disabled.

#### Context

* *node version*: 12
* *fastify version*: >=2.x
* *os*: Mac
* *any other relevant information*:

**Note:** I understand if this behavior is by design. I am asking to be sure.

**Comment by mcollina** [comment]
This is by design. In no case a plugin that does not load correctly would produce a working application.

I would recommend to set it to 60s or similar based on `NODE_ENV` in your case.

**Comment by dnlup** [comment]
Thank you @mcollina .
