### ISSUE TITLE
How to use route config for setNotFoundHandler?

### ISSUE THREAD

**Issue by PierBover** [fastify/help#178]
#### You have already researched for similiar issues?
Yes. I have looked at the docs and searched for issues.

#### What are you trying to achieve or the steps to reproduce?

My HTML routes have a `config` object that I'm using on custom hooks to decorate the `request` object.

When the `setNotFoundHandler` is triggered the custom hooks are also triggered, as expected, but these hooks are not receiving the `config` object that they need to work.

I saw in the docs it's possible to use a `beforeHandler` hook so I thought I could use an `onRequest` hook to decorate the request before the custom hooks but it wasn't triggered.

So what would be a solution for this?

Isn't there a way to simply define a regular route and tell fastify to use it when no other route is matched?

#### Context

* *node version*: 12
* *fastify version*: 2.13.1
* *os*: Mac

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by PierBover** [comment]
I tried defining a route with the `/*` url but I got this error...

```
Method 'GET' already declared for route '/*'
```

It seems Fastify is already using it internally.

**Comment by PierBover** [comment]
So no hooks are actually triggered. I reporte a bug:

https://github.com/fastify/fastify/issues/2228

**Comment by Eomm** [comment]
> It seems Fastify is already using it internally.

Fastify doesn't add any route by default.
Check your plugins to verify what routes are being registered.

**Comment by PierBover** [comment]
So I did `console.log(fastify.printRoutes())` and you're right. When enabling the `fastify-static` plugin it seems to create a route with the `/*` url.

With `fastify-static`:
```
└── / (GET)
    ├── * (GET)
    ├── api/v1/login (POST)
    │   └── / (POST)
    ├── log
    │   ├── in (GET)
    │   │   └── / (GET)
    │   └── out (GET)
    │       └── / (GET)
    └── user/settings (GET)
        └── / (GET)
```
Without:
```
└── / (GET)
    ├── api/v1/login (POST)
    │   └── / (POST)
    ├── log
    │   ├── in (GET)
    │   │   └── / (GET)
    │   └── out (GET)
    │       └── / (GET)
    └── user/settings (GET)
        └── / (GET)
```

The hooks problem I had also seems to be a bug with `fastify-static` which I've reported here:

https://github.com/fastify/fastify-static/issues/126

**Comment by mcollina** [comment]
This is actually a bug: https://github.com/fastify/fastify/issues/2229.
