### ISSUE TITLE
Why do we not have access to the Fastify instance in request/reply decorators?

### ISSUE THREAD

**Issue by jsumners** [fastify/help#179]
Consider this:

```js
fastify.decorate('someCache', singletonCacheObject)
fastify.decorateRequest('validate', function (input) {
  const cacheItem = ... // no way to get the `input` item from the cache
})
```

**Comment by mcollina** [comment]
Normally you do, it's in the closure:

```js
cons fp = require('fastify-plugin')
module.exports = fp(async function (app) {
  fastify.decorateRequest('validate', function (input) {
    return app.cache(input)
 })
})
```

What's your usecase?

**Comment by jsumners** [comment]
Okay, that's understandable. But consider:

*plugin/index.js*:
```js
const fp = require('fastify-plugin')
const cacheFactory = require('some-cache')
const validate = require('./validate')

module.exports = fp(async function (app) {
  app.decorate('someCache', cacheFactory())
  app.decorateRequest('validate', validate)
})
```

*plugin/validate.js*:
```js
module.exports = function validate(input) {
  // no closure to get cache
}
```

This structure allows the `validate` function to be tested independently, e.g.:

*test/plubin/validate.test.js*:
```js
const tap = require('tap')
const validate = require('../plugin/validate')

tap.test('foo', async t => {
  const result = validate.call({ someCache: {mocked: true} }, 'input')
  t.is(result, 'a thing')
})
```

**Comment by mcollina** [comment]
I would do:

```js
const fp = require('fastify-plugin')
const cacheFactory = require('some-cache')
const validate = require('./validate')

module.exports = fp(async function (app) {
  const cache = cacheFactory()
  app.decorate('someCache', cache)
  app.decorateRequest('validate', validate(cache))
})
```

You can still test validate independently and wrap it in a closure.

I know it's not ideal, however adding that would add yet another field in the `Request` and `Reply` objects, and I would love to _lower_ them instead.

**Comment by jsumners** [comment]
> I know it's not ideal, however adding that would add yet another field in the Request and Reply objects, and I would love to lower them instead.

I'm going to think on this some more. I'm not happy with the closure solution (the path I was already using) as it can complicate testing. My inclination is that `Request` and `Reply` should inherit from `Fastify` so that `this.cache` will resolve up the chain.

**Comment by mcollina** [comment]
That's not going to be possible, as they already have an inheritance chain.
