### ISSUE TITLE
how to know when response schema is not matched

### ISSUE THREAD

**Issue by PavelPolyakov** [fastify/help#18]
#### What are you trying to achieve or the steps to reproduce?

According to the documentation it's possible to validate the responses of your endpoints:
https://www.fastify.io/docs/latest/Validation-and-Serialization/#validation

Which leads to the state, that your real response object will be striped according to the response schema. The extra parts would be just silently omitted.

#### What did you expect?
Is there a way to log these cases? So the developer knows, that the response he returns doesn't match
 the response schema definition and probably something should be changed (either schema or the code itself)

#### Context
* *fastify version*: 1.9

**Comment by mcollina** [comment]
> Which leads to the state, that your real response object will be striped according to the response schema. The extra parts would be just silently omitted.

Can you please make an example with code?

> Is there a way to log these cases? So the developer knows, that the response he returns doesn't match
the response schema definition and probably something should be changed (either schema or the code itself)

We are currently relying on [ajv](https://github.com/epoberezkin/ajv) for this part, and I do not think there is a way to know if/which properties have been dropped.

**Comment by PavelPolyakov** [comment]
This is what I mean:
https://repl.it/repls/SolidSecondaryRom

**Comment by mcollina** [comment]
Thanks for the code example. Your problem is related to serialization and not validation. 
The good news is this feature is implemented in https://github.com/fastify/fast-json-stringify. The bad news is that it is a feature we support: we prevent non-whitelisted data to leak to end users. Moreover, detecting it would be extremely expensive.

I would recommend writing unit tests for your feature, either with `fastify.inject()` or using a full http client.

**Comment by PavelPolyakov** [comment]
Thanks,

Yep, that was part of the original reason for the question - since these tests are not pure unit tests, since they test not your handler but fastify+handler = looks more like integration test.

Thanks for the information!

**Comment by PavelPolyakov** [comment]
@mcollina ,
what were you referring to here:
> The good news is this feature is implemented
?

**Comment by mcollina** [comment]
Serialization lives in https://github.com/fastify/fast-json-stringify.

**Comment by PavelPolyakov** [comment]
I understood that, but does it support notifying the caller about the fact that the object which is being serialized doesn't match the schema?

**Comment by mcollina** [comment]
It does not, because that's _a feature_. If we detected and logged that, it would be very expensive to do so.
