### ISSUE TITLE
Unregister plugin?

### ISSUE THREAD

**Issue by supertiger1234** [fastify/help#181]
Is is possible to unregister a plugin? 
I'm trying to make it so I can update a plugin with routes in it so I don't need to restart my server all the time to make changes.

**Comment by jsumners** [comment]
No. The Fastify uses [`avvio`](https://www.npmjs.com/package/avvio) to handle loading of plugins. Once the instance has been started it is immutable.

**Comment by supertiger1234** [comment]
ah rip, back to express i go.
