### ISSUE TITLE
[feat] new plugin for opentracing

### ISSUE THREAD

**Issue by maumercado** [fastify/help#183]
## 🚀 Feature Proposal

A fastify plugin for Jaeger distributed tracing system.

## Motivation

Fastify does not provide a plugin to support jaeger, although there are clients we can use, it's better to provide an encapsulated version of this functionality.

## Example
```
const fastify = require('fastify')()

fastify.register(require('fastify-jaeger'), {
  serviceName: 'my-service-name'
})

fastify.get('/', (req, reply) => {
  reply.send({ hello: 'world' })
})

fastify.listen(3000, err => {
  if (err) throw err
  console.log('Server listenting on localhost:', fastify.server.address().port)
})

**Comment by jsumners** [comment]
https://github.com/fastify/fastify/issues/2097

**Comment by jsumners** [comment]
Closing because you posted this twice.
