### ISSUE TITLE
[feat] new plugin for opentracing

### ISSUE THREAD

**Issue by maumercado** [fastify/help#184]
## 🚀 Feature Proposal

A fastify plugin for Jaeger distributed tracing system.

## Motivation

Fastify does not provide a plugin to support jaeger, although there are clients we can use, it's better to provide an encapsulated version of this functionality.

## Example
```
const fastify = require('fastify')()

fastify.register(require('fastify-jaeger'), {
  serviceName: 'my-service-name'
})

fastify.get('/', (req, reply) => {
  reply.send({ hello: 'world' })
})

fastify.listen(3000, err => {
  if (err) throw err
  console.log('Server listenting on localhost:', fastify.server.address().port)
})
```

I have already created such functionality here => https://github.com/maumercado/fastify-jaeger

https://www.npmjs.com/package/fastify-jaeger -> packaged already published here.

I was wondering if it would be better for the fastify team to take over the project, and rename as well if it's better, I can modify the fastify-jaeger npm namespace if need be.

**Comment by jsumners** [comment]
https://github.com/fastify/fastify/issues/2097

**Comment by mcollina** [comment]
I don’t understand what are you recommending @jsumners.

**Comment by jsumners** [comment]
Just that it is under discussion.
