### ISSUE TITLE
Apply Hooks only to some routes

### ISSUE THREAD

**Issue by hazam** [fastify/help#185]
I studies the doc and trying to wrap my head aroud the new scope building. 
What I understood is that if in my plugin I register the hooks like that

```
module.exports = function (fastify, opts, done) {
  fastify.addHook(....)
  fastify.get('/route1', handler1)
  fastify.post('/route2', handler2)
  done()
}
```

the hook will run for the two routes. While if register it in two different plugins

```
module.exports = function (fastify, opts, done) {
  fastify.addHook(....)
  done()
}
module.exports = function (fastify, opts, done) {
  fastify.get('/route1', handler1)
  fastify.post('/route2', handler2)
  done()
}
```

Then it won't run due to scope encapsulation. So i need to use fastify-plugin on the hook plugin to have it "global" (or is it parent context only?)

But then I have this init pattern in my server.js

```
fastify.register(autoload, { dir: path.join(__dirname, 'plugins') })
    .register(autoload, {
      dir: path.join(__dirname, 'services'),
      options: { prefix: 'api/' }
    })
```

And right now the only solution to have the hooks declared in the `/plugins` folder to bet ran in the routes declared in the `/services` folder, is to declare them with fp, then making them global.

What's the pattern to have the hooks running ONLY for some routes?
Thanks

**Comment by mcollina** [comment]
You can also pass them as options to the route definition itself.

**Comment by hazam** [comment]
Ok then that the actual hooks don't need to be set via plugin but simple functions that are required and set in the route definition. This would make explicit that a given route expects some hook to be ran, but also would require each route to specify basically the same list of hooks, except one or two (think about the /api/healthcheck route)

What about hooks that are needed by most of the routes, but not all?

**Comment by mcollina** [comment]
I typically place them inside different intermediate plugins, sometimes in different folders.

**Comment by hazam** [comment]
Thanks for the info Matteo, things are clesr.
Should i close the issue?

**Comment by mcollina** [comment]
yes!
