### ISSUE TITLE
CodeQL

### ISSUE THREAD

**Issue by subesokun** [fastify/help#187]
Now that GitHub code scanning is available (in public beta) I was wondering what Fastify's opinion is on providing official Fastify CodeQL queries. In the GitHub Satellite keynote, they've shown [an example query](https://youtu.be/FhZTPM9ysWk?t=4863) that checks if you access the file system as part of a request without rate limiting. This is just an example, but such kind of queries could be helpful for projects using Fastify to avoid known security pitfalls on their side. Writing and keeping all the queries up-to-date with the Fastify releases sounds not like an easy task though.

Some helpful links:
https://github.com/github/codeql/blob/master/javascript/ql/src/semmle/javascript/frameworks/HttpFrameworks.qll
https://github.com/github/codeql/blob/master/javascript/ql/src/semmle/javascript/frameworks/Express.qll

**Comment by mcollina** [comment]
I don't think we have the bandwidth to take this on. I would recommend if you would like to open an issue on CodeQL and ask for this framework to be added. I'm happy to review/help them identify common problems if they want to.

**Comment by mcollina** [comment]
cc @Ethan-Arrowood

**Comment by Ethan-Arrowood** [comment]
I agree with @mcollina. We don't have the bandwidth to take this on ourselves, but happy to help facilitate if someone else wants to lead the effort. Happy to run point on that personally too

**Comment by subesokun** [comment]
Understandable and I appreciate your hard work. I'll open an issue on CodeQL/Semmle for supporting Fastify and let's see what happens.

Not sure if I'll find the time or not for writing an exemplary CodeQL query for Fastify but what could be a useful check? Something that you really should avoid but often gets done wrong in a Fastify application.

**Comment by mcollina** [comment]
Mixing callbacks and async in plugins, hooks and routes.

**Comment by subesokun** [comment]
Something like that? If you do it intentionally, it's difficult to come up with bad examples :)

```javascript
fastify.get('/', function (request, reply) {
    const doSomethingAsync = Promise.resolve()
    doSomethingAsync
        .then(() => reply.send({ hello: 'world' }))
        .catch(() => reply.code(500).send('kaboom'))
})
```

**Comment by mcollina** [comment]
I mean:

```js
// this is a plugin
module.exports = async function (app, cb) {
  cb()
}
```

or

```js
fastify.get('/', async function (request, reply) {
  reply.send({ hello: 'world' }) // not recommended.
  // return { hello: 'world' } // recommended
})
```

**Comment by subesokun** [comment]
I see. Yes if you don't read the docu about [promise resolution](https://github.com/fastify/fastify/blob/master/docs/Routes.md#promise-resolution) then you can easily make that mistake.

**Comment by mcollina** [comment]
@Ethan-Arrowood can you please coordinate? Thank you so much.

**Comment by intrigus-lgtm** [comment]
(I'm not affiliated with github or codeql)
As far as I know modeling the fastify libraries or writing specific queries for it, could be rewarded with the "All for one, one for all" [bounty](https://securitylab.github.com/bounties) i.e. some money :)

**Comment by subesokun** [comment]
It looks like Fastify will be supported soon 🎉 https://github.com/github/codeql/pull/3527

**Comment by esbena** [comment]
Author of https://github.com/github/codeql/pull/3527 here.

Yup. Fastify is now in our generic server model (Express/Connect/Koa/...). 
So applications that use Fastify will now also be checked for server-side vulnerabilities such as path-injections, reflected XSS, ...

---

We can easily leverage the model to make a query that flag:

```js
fastify.get('/', async function (request, reply) {
  reply.send({ hello: 'world' }) // not recommended.
  // return { hello: 'world' } // recommended
})
```
But our focus is mostly on tasks that benefit security queries.

---

If you happen to know of past vulnerabilities that involve Fastify applications, we would be happy to know of them to ensure that our Fastify modelling is adequate for actual vulnerabilities.

**Comment by mcollina** [comment]
I would add something that tells devs to add validations to their routes. Essentially routes that are accessing the params, the querystring or the body without providing any validations should be flagged.

Schema loaded remotely should be flagged. I’m not sure if you can detect this.

**Comment by subesokun** [comment]
As the basic support for CodeQL is now available (https://github.com/github/codeql/pull/3527) this issue can be closed.

Maybe the Fastify documentation can be extended to mention the CodeQL support with an example that shows how you can integrate the security scanner into your repository.

Special thanks to @esbena !

**Comment by mcollina** [comment]
A PR to our docs would be well accepted.
