### ISSUE TITLE
ERR_AVVIO_PLUGIN_TIMEOUT and fastify v3 ( async / await question)

### ISSUE THREAD

**Issue by matth-c3** [fastify/help#188]
Hello, 

Im currently testing the @next branch with fastify v3 to try out the async/await support for register and after following the  [PR](https://github.com/fastify/avvio/pull/92) in avvio.

I created a plugin that takes some time to start that can often take more than 10seconds. 

For now I increased `pluginTimeout` but as v3 includes async / await when registering a plugin does `pluginTimeout` should not be ignored  in that case ?

Thanks.

**Comment by mcollina** [comment]
Can you please make an example? Also, there was a bad bug that it was fixed recently, so maybe you did hit that - try updating your full dependency tree.

**Comment by matth-c3** [comment]
Hello @mcollina ,

Sure : 

`#main` is the main script and `#plugin` is the plugin that is register in #main . 

the plugins simulate a long operation of 20 seconds with `pluginTimeout ` set with the default value of 10 seconds.

 

```
#main 

const fastify = require('fastify')({ logger: true })

// Run the server!
const start = async () => {
  try {

    fastify.decorate('Tools', {
      sleep: (ms) =>  new Promise((resolve) => {
        setTimeout(resolve, ms);
      })
    });

    await fastify.register(require('my-plugin'))


    fastify.get('/', async (request, reply) => {
      return { hello: 'world' }
    })

    await fastify.listen(3000)
    fastify.log.info(`server listening on ${fastify.server.address().port}`)
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()

```




```
#plugin 
const fp = require('fastify-plugin')

module.exports = fp( async function (fastify, opts, done) {
  fastify.decorate('utility', () => {})
  const { Tools } = fastify
  await Tools.sleep(20000)
  done()
}, '0.x')

```

Thanks

**Comment by mcollina** [comment]
You can change it in the constructor:

```js
const fastify = require('fastify')({ logger: true, pluginTimeout: 20000 })
```

Note that your plugin code has a bug:

```js
const fp = require('fastify-plugin')

module.exports = fp( async function (fastify, opts, done) {
  fastify.decorate('utility', () => {})
  const { Tools } = fastify
  await Tools.sleep(20000)
  // done() <-- don't do this
}, '0.x')
```

**Comment by matth-c3** [comment]
Hello @mcollina , 

Yes sorry for the mistake in the example. But as initially asked, as it's suppose to be a promise (async / await), `pluginTimeout` should not be ignore  in that case ? 

For now I just set pluginTimeout to `120000`.

Thanks.

**Comment by mcollina** [comment]
The pluginTimeout is there to catch for a database that is not connecting or similar, so it's good to stay there.

How long does it take for your plugin to load? I picked the 10s default arbitrarily, and we can definitely increase it.

**Comment by matth-c3** [comment]
Hello @mcollina , 

For now between 12 to 17 seconds but i will increase over time ( up to 1 or 2 minutes). I basically sync some data ( DB / Cache ) during the registration of the plugin. 

Maybe instead of using a different default value, `0` could be use to set unlimited time ? ( I did not look at `avvio` source code, this is not applicable for obvious reason that I dont know yet :) )

Thanks.

**Comment by mcollina** [comment]
A value of `0` to disable it will be ok.
