### ISSUE TITLE
add hook pass extra parameter

### ISSUE THREAD

**Issue by moeinrahimi** [fastify/help#189]
I'm trying to run a preHandler function to check request authorization and i need to pass extra parameter in addition to fastify addHook default parameters.
```js
fastify.addHook('preHandler',auth.hasRole(["admin",'support']))

const hasRole = (roles) => {
  return function (req, reply, next) {

    if (!roles) return next()
    console.log("hasRole -> roles", roles)
    if(!Array.isArray(roles)) roles = [roles]
    for (let i = 0; i < roles.length; i++) {
      const role = roles[i];
      if (roles.includes(role)) {
        return next()
      }
    }
    console.log("hasRole -> req, reply, next", req, reply, next)
    return reply.code(401).send({success: false, message: 'not authorized', statusCode: 401})
  }

}
```

this is something i used to in express, not sure if it's the right way to do for fastify.

**Comment by mcollina** [comment]
I don't understand the question. It seems this code should work.

**Comment by moeinrahimi** [comment]
passed parameters are null. (req,reply,next)

**Comment by mcollina** [comment]
Can you please post a full example? Your example _should_ work, as it's equivalent of:

```js
fastify.addHook('preHandler',auth)

const roles = ['admin', 'support']
function auth (req, reply, next) {

    if (!roles) return next()
    console.log("hasRole -> roles", roles)
    if(!Array.isArray(roles)) roles = [roles]
    for (let i = 0; i < roles.length; i++) {
      const role = roles[i];
      if (roles.includes(role)) {
        return next()
      }
    }
    console.log("hasRole -> req, reply, next", req, reply, next)
    return reply.code(401).send({success: false, message: 'not authorized', statusCode: 401})
  }
```

**Comment by moeinrahimi** [comment]
I managed to make it work like this, only one more question, is this the preferred way for such tasks?
like checking request jwt token before handling request .
```
  fastify.addHook('preHandler', (req, res, next) => {
    auth.hasRole(req, res, next,rolesToCheck)
  })
```

**Comment by mcollina** [comment]
I would put this in `onRoute` instead (if you do not need the parsed body). Otherwise it's ok.

**Comment by jsumners** [comment]
Don’t you mean `preValidation`

**Comment by mcollina** [comment]
Also that :). It really depends on your auth strategies.

**Comment by moeinrahimi** [comment]
preValidation looks good, thanks for helping.

**Comment by NourMaherT** [comment]
@moeinrahimi A true genius. Thanks!!

> I managed to make it work like this, only one more question, is this the preferred way for such tasks? like checking request jwt token before handling request .
> 
> ```
>   fastify.addHook('preHandler', (req, res, next) => {
>     auth.hasRole(req, res, next,rolesToCheck)
>   })
> ```
