### ISSUE TITLE
JSON Hyper-Schema

### ISSUE THREAD

**Issue by acarballo-cs** [fastify/help#19]
#### What are you trying to achieve or the steps to reproduce?
Does fastify support json-hyperschema? https://datatracker.ietf.org/doc/draft-handrews-json-schema-hyperschema/

**Comment by mcollina** [comment]
I just looked hyperschema up, so very likely there is nothing to support it directly. If you would like to investigate what will take to support it, if it could be done in a plugin, etc, we’ll be very happy to hear and help alon the implementation.

**Comment by acarballo-cs** [comment]
I'm looking into the plugin system and investigating current json-hyperschema implementations (https://github.com/mokkabonna/json-hyper-schema)
