### ISSUE TITLE
Help a noob: Cannot start typescript fastify 3.0 server with plugins

### ISSUE THREAD

**Issue by dhobi** [fastify/help#190]
#### You have already researched for similiar issues?
Yes, I've tried.

#### What are you trying to achieve or the steps to reproduce?
I'm trying to run a fastify 3.0 server (typescript) with the following plugins:
fastify-static
fastify-basic-auth
Both plugins are mentioned to be fastify 3.0 ready.

Minimal demo here: https://github.com/dhobi/fastify-demo
npm install
npm run start

#### What was the result you received?
```
Error: plugin must be a function or a promise
    at assertPlugin (fastify-demo/node_modules/avvio/boot.js:194:11)
```

Some observations:
- It works without the plugins.
- If I change the import/from to require calls for plugins, the register() pass the plugin check but the following server.basicAuth is undefined:

```
fastify-demo/node_modules/fastify/fastify.js:408
      if (fn.constructor.name === 'AsyncFunction' && fn.length === 3) {
             ^
TypeError: Cannot read property 'constructor' of undefined
```

#### What did you expect?
An awesome running fastify server with plugins.

#### Context

* *node version*: v12.16.2
* *fastify version*: 3.0.0-rc.2
* *os*: Mac
* *any other relevant information*: None that I'm currently aware of

**Comment by mcollina** [comment]
This should work, plugin loading is async:

```js
async function build () {
const server = fastify();

server.register(fastifyStatic, {
    root: path.join(__dirname, 'admin', 'public'),
    prefix: '/admin/public/',
});
await server.register(fastifyBasicAuth, {
    validate: (username, password, req, reply, done) => {
        if (username === 'fastifydemo' && password === 'fastifydemo') {
            done()
        } else {
            done(new Error('No access'))
        }
    },
    authenticate: true
});
server.addHook('onRequest', server.basicAuth);
return server
}
```

**Comment by dhobi** [comment]
Thanks for this! 👍 
This boots up the server just fine when registering the plugins with 
```
require('fastify-static')
require('fastify-basic-auth') 
```

The [typescript documentation](https://github.com/fastify/fastify/blob/master/docs/TypeScript.md) mentions that importing a plugin with "import/from" should just work fine as well. The compiler doesn't complain and my IDE resolves the types but I get this at runtime:

`Error: plugin must be a function or a promise`

I have updated my small demo repo to show the issue.

**Comment by mcollina** [comment]
Debugging that is above my TS skills. 

Maybe @Ethan-Arrowood or maybe @thomheymann

**Comment by thomheymann** [comment]
You need to enable `esModuleInterop` option in your tsconfig for this to work

**Comment by dhobi** [comment]
Yep, that's it! I was not aware of that setting. 👍 
Thanks for the fast(ify) help! @mcollina @thomheymann 

I see that 
`npx typescript --init`
would have set this flag correctly for me so I don't think an update to the documentation is necessary.

Thanks again!
