### ISSUE TITLE
using Fastify with node's http module

### ISSUE THREAD

**Issue by erfanium** [fastify/help#191]
How can I use Fastify instanse with node's http module? 
like this with express:
```js
const app = express()
app.get('*', ...)

http.createServer(app).listen(3000)   // instead of app.listen
```

I got type error with Fastify (I'm using typescript)

**Comment by jsumners** [comment]
https://www.fastify.io/docs/v2.14.x/Server/#serverfactory

**Comment by erfanium** [comment]
@jsumners 
Unfortunately, this does not meet my needs.
I want to use two fastify app with the same port number

**Comment by erfanium** [comment]
@jsumners
Unfortunately, this does not meet my needs.
I want to use two fastify app with the same port number
