### ISSUE TITLE
How can i forward the contentType is formdata？

### ISSUE THREAD

**Issue by monsterboom** [fastify/help#193]
first, i know i should use fastify-multipart.
But, i want to forward to another api. 
for example, use node-fetch:
const FormData = require('form-data');
const form = new FormData();
form.append('a', 1);
form.append('file', file) // how can i get the file
const options = {
    method: 'POST',
    body: form,
    headers: form.getHeaders()
}
fetch('https://httpbin.org/post', options)

------------------------------------------

**Comment by mcollina** [comment]
I don’t really understand what are you planning to do or what the question is. Can you please clarify? node-fetch is a client library.

**Comment by monsterboom** [comment]
> I don’t really understand what are you planning to do or what the question is. Can you please clarify? node-fetch is a client library.

I'm sorry I didn't make it clear. I will try my best to clarify.

My node service frame is Fastify. As middleware, to forward another service, and I use node-fetch to forward. When the Content-Type is application/json, I can be very simple to get the body. But now, I should forward an api function is to upload file. I know how to upload by node-fech , and I've put the code on it.

I know the api which is to upload file, Content-Type is multipart/form-data. So i use fastify-multipart. But I don't know what to do next.

Maybe it's a stupid question, but I hope to learn from it. thank you.
