### ISSUE TITLE
[Question] official plugin used in fastify-cli-generated project

### ISSUE THREAD

**Issue by JoHuang** [fastify/help#195]
Like fastify-redis, where should I put it in fastify-cli-generated project.
Should I put it in `app.ts`? Or create a plugin wrapping it in `plugin/` folder?

And how to close it when app is terminating?

**Comment by Eomm** [comment]
Could you elaborate?

> And how to close it when app is terminating?

Are you looking for the [`onClose` hook](https://github.com/fastify/fastify/blob/master/docs/Hooks.md#on-close)?
