### ISSUE TITLE
How to send back image from fastify?

### ISSUE THREAD

**Issue by CodTicker** [fastify/help#196]
Ive saved an image to my mysql database and now I want to return this image to my front end. 

I have created the following handler and schema that should return a buffer: 

```
const db = require('../../assets/models/index');

//
// Typescript definitions

interface ImageSuccess {
  image: Buffer;
}

interface postParams {
  id: String;
}
//
// Schemas

const getSchema = S.object()
  .title('Get lotteries')
  .description('A description for this route')
  .prop('id', S.string().required());

const successResponseSchema = S.object()
  .title('About 200 response')
  .description('Some description')
  .prop('image', S.object());
//
// Route options

const opts: RouteShorthandOptions = {
  schema: {
    description: 'Banana',
    tags: [RouteTags.USER],
    params: getSchema.valueOf(),
    response: {
      200: successResponseSchema.valueOf(),
      '4xx': errorResponseSchema.valueOf(),
    },
  },
};

//
// Handler

const handler = async (req, reply) => {
  const p: postParams = req.params;

  console.log('ID', p.id);

  const parser = uuIdParserT();

  const img = await db.images.findByPk(parser.setValueAsBIN(p.id));

  const response: ImageSuccess = {
    image: Buffer.from(img.dataValues.imageData),
  };

  reply.send(response);
};

export default (server: FastifyInstance) =>

  server.get<null, ImageSuccess>('/:id', opts, handler);
```

I am making a get request where Im sending in a Id. I get back the buffer from the database call BUT when returning it to the frontend it is an empty object. Im not getting any errors but I simply dont know how to make this work. 

The request from the frontend looks like: 

```
  const tryFetch = async (event: any) => {
    event.preventDefault();

    const t = await axios({
      method: 'GET',
      url: 'http://localhost:4000/cool/uploadHandler/id=11ea9a21-d438-9eeb-a070-00ff98e8d5ab',
    });
  };
```

I read a few articles saying that I need to fetch the data from my db, return a buffer and then base64 encode in the frontend to show the image. im new to this so I might be totaly off. 

Any help is deeply appreciated. 

EDIT: 

images table is like this: 

```
Id: BINARY(16)
imageData: MediumBlob
Name:String 
```

package..json: 

 ```
   "dependencies": {
        "@types/pg": "^7.11.2",
        "apollo-server-fastify": "^2.13.1",
        "app-module-path": "^2.2.0",
        "axios": "^0.19.0",
        "bcrypt": "^4.0.1",
        "bytebuffer": "^5.0.1",
        "cls-hooked": "^4.2.2",
        "cls-proxify": "^1.0.1",
        "dataloader": "^2.0.0",
        "dotenv": "^8.2.0",
        "fastify": "^2.14.1",
        "fastify-compress": "^0.11.0",
        "fastify-cors": "^2.1.3",
        "fastify-file-upload": "^2.0.1",
        "fastify-gql": "^3.8.0",
        "fastify-helmet": "^3.0.2",
        "fastify-multipart": "^1.0.6",
        "fastify-plugin": "^1.6.0",
        "fastify-swagger": "^2.5.1",
        "fluent-schema": "^0.7.5",
        "graphql": "^14.6.0",
        "graphql-type-datetime": "^0.2.4",
        "graphql-upload": "^10.0.0",
        "httperrors": "^2.3.0",
        "jsonwebtoken": "^8.5.1",
        "jwks-rsa": "^1.8.0",
        "mysql": "^2.18.1",
        "mysql2": "^2.1.0",
        "node-cache": "^5.0.0",
        "pino": "^5.13.5",
        "pino-pretty": "^3.2.2",
        "sequelize": "^5.21.9",
        "stream-to-blob": "^2.0.1",
        "uuid": "^3.3.3",
        "uuid-parse": "^1.1.0",
        "validator": "^11.1.0"
```

**Comment by jsumners** [comment]
Personally, I'd store images on the file system instead of a database. But, regardless, if you want to return a buffer of image data to a requesting client, you should do so as a stream -- https://www.fastify.io/docs/latest/Reply/#streams

**Comment by CodTicker** [comment]
Feel a bit stupid asking this but as far as Ive understood right now: 

I need to send back a stream/buffer but the link you sent shows me how use fs methods when there is an actuall file on the filserver. In my case i have a bloob/bufffer from the db, what do I do then?

**Comment by mcollina** [comment]
```js
reply.send(bufFromTheDb)
```

**Comment by CodTicker** [comment]
After some time I came to the following: 


```
const handler = async (req, reply) => {
  const p: postParams = req.params;

  const parser = uuIdParserT();

  const img = await db.images.findByPk(parser.setValueAsBIN(p.id));

  const myStream = new Readable({
    read() {
      this.push(img.dataValues.imageData);
      this.push(null);
    },
  });

  const response = myStream;

  reply.header('Content-Disposition', 'attachment; filename=' + img.dataValues.Name);
  reply.header('Content-Length', img.dataValues.Length);
  reply.type('application/octet-stream');
  reply.send(response);
};
```

Which I assume should work BUT when Im trying to display the image in the browser like: 

```
            <img
              src="http://localhost:4000/cool/uploadHandler/id=11ea9c43-1e36-7242-a070-00ff98e8d5ab"
              className="imageUpload"
            />
```

Nothing gets displayed. And when puting the above URL in the browser it downloads the file but when I try to open it then I get "Unsupported file format"

**Comment by jsumners** [comment]
That's not the usage I understood from the original post. Given that you want to reference this as the source of an `img` element, you should be using data encoding for the image data -- https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

Basically (not real code):

```js
const encodedBuffer = imgBuffer.toString('base64')
const toSendBuffer = Buffer.from(`data:image/jpeg:base64,${endodedBuffer}`)
reply.send(toSendBuffer)
```

And your frontend will need to generate an appropriate `img` element with the source attribute set to the string data.

**Comment by CodTicker** [comment]
Kind of transformed into this after a long while of searching. I will try the above.

**Comment by CodTicker** [comment]
The above attempt gave me an encoded base64 representation of the image but still nothing.

starting to question the way Im saving the image, is this correct: 

Mysql type for imageData is MEDIUMBLOB

code: 

```
        const { filename, mimetype, createReadStream } = await file;
        const stream = await createReadStream();
        const streamData = await readStream(stream);
        const buff = Buffer.from(streamData);

     readStream func: 

      export const readStream = async (stream, encoding = 'utf8') => {
          stream.setEncoding(encoding);

          return new Promise((resolve, reject) => {
           let data = '';

           // eslint-disable-next-line no-return-assign
           stream.on('data', chunk => (data += chunk));
           stream.on('end', () => resolve(data));
           stream.on('error', error => reject(error));
      });
     };


        await db.images.create(
            {
              Name: filename,
              imageData: buff,
              Length: stream.bytesRead,
              Type: mimetype,
            },
            { transaction: param }
          );
```
Im new to this and been at this for days. I know im asking alot but hoping for a miracle at this point.

**Comment by jsumners** [comment]
As I said, I wouldn't write the image to the database. Indeed, I haven't written image data to a database in almost two decades. 

I'm not sure what your latest snippet is doing. There isn't enough context for me.

**Comment by CodTicker** [comment]
Latest snippet is a handler that is responsible for uploading files. 
Basics: 

1.  Get the file. 
2. Create a stream
3. read the stream (streamData)
4. Turn the data into a buffer. 
5 Save file data in the db.  

I understand what you are saying, im trying to learn this and doing my best but im stuck.

**Comment by CodTicker** [comment]
Data is being sent via an axios request and I attach formData to it. The handler itself is a grapql resolver which recives the file. 

I can assue you that the file is being recived from the font-end. Im just not sure Im saving it correctly with the db(mysql) in mnd.

**Comment by jsumners** [comment]
I don't know anything about axios or graphql. What I can tell you is that the example in https://www.npmjs.com/package/fastify-multipart is pretty much complete for this. The only difference would be to update the `onEnd` callback to base64 encode the data and store it in the database.

**Comment by KerwinChina** [comment]
Hi, I use reply.header('Content-Type', 'image/png'); reply.send(qrCodeBuffer) success for me.
