### ISSUE TITLE
Best way to inspect logs in a test suite?

### ISSUE THREAD

**Issue by gnarea** [fastify/help#198]
#### You have already researched for similiar issues?

[Yes](https://github.com/fastify/fastify/issues?q=is%3Aissue+test+log++).

#### What are you trying to achieve or the steps to reproduce?

I'm writing tests using `fastify.inject()` and I'd like to make sure `request.log.xyz()` gets called with the data I expect. How can I achieve that?

I can access the Pino logger after the `fastify.inject()` call (via `response.raw.req.log`), but by that point it's already too late: I can't mock the logger, nor can I see the log entries.

I can try to find a way to mock Pino or Fastify early on, but is there a better way to do this?

#### Context

* *node version*: 12
* *fastify version*: 2.14.1
* *os*: Ubuntu

**Comment by jsumners** [comment]
If I need to inspect logs I usually do something like:

```js
tap.beforeEach((done, t) => {
  const logLines = []
  const stream = split2(data => {
    logLines.push(JSON.parse(data))
  })
  const logger = pino({...options}, stream)
  const server = fastify({ logger })

  t.context.logLines = logLines
  t.context.server = server

  done()
})

tap.test('foo', async t => {
  await t.context.server.inject('/foo')
  t.is(t.context.logLines.length, 5)
})
```
