### ISSUE TITLE
how to hijack reply on onSend hook properly?

### ISSUE THREAD

**Issue by PavelPolyakov** [fastify/help#2]
#### What are you trying to achieve or the steps to reproduce?
What I want to do:
1. server `swagger-ui-dist` as static using `fastify`. This can be done using https://github.com/fastify/fastify-static .
2. when it serves `index.html` of that folder, I want to change content on the fly, so I can inject my swagger definition

Something like:
```js
const swaggerUiAssetPath = require('swagger-ui-dist').getAbsoluteFSPath();
const fs = require('fs');

module.exports = function (fastify, opts, next) {
  const files = {
    specification: fs.readFileSync(
      `${process.cwd()}/var/swagger.yaml`,
      'utf8',
    ),
    index: fs
      .readFileSync(`${swaggerUiAssetPath}/index.html`, 'utf8')
      .replace(
        'http://petstore.swagger.io/v2/swagger.json',
        `${opts.url}/swagger/swagger.yaml`,
      ),
  };

  fastify.register(require('fastify-static'), {
    root: swaggerUiAssetPath,
    prefix: `/swagger/`, 
  });

  fastify.get(`/swagger/swagger.yaml`, (request, reply) => {
    reply.send(files.specification);
  });

  fastify.addHook('onSend', (request, reply, payload, next) => {
    if (request.raw.url === `/${opts.path}/`) {
      // payload == SendStream 
      // how can I hijack it?
      // something like reply.send(files.index) , <== this doesn't work and it is OK
    }

    next();
  });

  next();
};


```

#### What was the result you received?
According to the documentation:
```
Note: If you change the payload, you may only change it to a string, a Buffer, a stream, or null.
```

So I can not use simple `reply` functionality, which is preferred. At the same time I don't see how can I replace something inside the stream. I can send it as a string, but since headers will be missing browser would not render it properly.

#### What did you expect?
I'd like to use `reply` at this point. Any solution is appreciated of course.

#### Context

* *node version*: 8
* *fastify version*: latest
* *os*: Mac

Thanks for the help!

**Comment by delvedor** [comment]
Hi!
Why not use [`fastify-swagger`](https://github.com/fastify/fastify-swagger)?

You can't use `reply.send` inside `onSend` because you have already called `reply.send` ;)
If needed you can alter the payload in the following way:
```js
fastify.addHook('onSend', function (req, reply, payload, next) {
  const newPayload = yourUtilityThatAltersThePayload(payload)
  next(null, newPayload)
})
```
If the payload is a stream you can check how we do it in [`fastify-compress`](https://github.com/fastify/fastify-compress/blob/master/index.js#L74-L113).

**Comment by PavelPolyakov** [comment]
@delvedor thanks for the fast reply.
It may sound strange but I want to draft my swagger manually.

Thanks, so I see you `pump` two streams together, and look like I need to dance around that stream as well.

**Comment by PavelPolyakov** [comment]
I still find it confusing that you can do something with `reply` in `onSend`, like it's done in this plugin:
https://github.com/lolo32/fastify-response-time/blob/master/index.js . But you can not change the actual payload using `reply` interface.

**Comment by delvedor** [comment]
@PavelPolyakov you can use the entire reply interface except for `send`.
If you need to alter the payload you should pass the modified payload as second parameter to the `next` callback.
