### ISSUE TITLE
next function in route handler.

### ISSUE THREAD

**Issue by justablob** [fastify/help#20]
How about a `next` function in Fastify? Express and Koa have it and it really is useful. Imagine this code: 

```js
  fastify.get("/static/**", (req, rep) => {
    let filePath = path.join(process.cwd(), "src", req.raw.url)
    if (!req.raw.url.includes("..") && fs.existsSync(filePath)) {
      let type = mime.getType(filePath)
      rep.type(type).send(fs.createReadStream(filePath))
    } else {
      rep.code(404)
    }
  })
```

In this case, all requests on `/static/*` are handled by this route. What if the file does not exist though? In this case, we could use a `next()` after `rep.code(404)` which would continue looking for a router and eventually end up at the 404 handler:

```js
  fastify.get("/**", (req, rep, next) => {
    let filePath = path.join(process.cwd(), "src", req.raw.url)
    if (!req.raw.url.includes("..") && fs.existsSync(filePath)) {
      let type = mime.getType(filePath)
      rep.type(type).send(fs.createReadStream(filePath))
    } else {
      rep.code(404)
      next()
    }
  })
```

It would return a Promise which resolves after all lower-sitting routes finish. I will maybe follow this up with a PR if I am in the mood.

**Comment by justablob** [comment]
I would also like to add that I have seen the existing issue about this but it only focused on a work-around, not an actual implementation.

**Comment by mcollina** [comment]
Fastify is based on deterministic routing. So, we don't have the info on what route to match after the current one.

**Comment by justablob** [comment]
Aww, that's a bummer... Fastify was looking really good at first but this makes me not able to use it in this project. Luckily it's not my only project :)
