### ISSUE TITLE
Graceful shutdown with close() and onClose hook

### ISSUE THREAD

**Issue by JoHuang** [fastify/help#200]
Usually we call `close()` when received `SIGTERM`, and onClose is triggered at the same time.

However, here's some issue.
Assuming I have a DB connection to close.

1. Call `close()` when received `SIGTERM`. All following requests receive 503 to prevent new requests. We want the processing requests to be done, so we'll `process.exit(0)` later (maybe 10 secs or so)
2. All processing requests still need some time (10 secs) to be done. However the DB plugin receive `onClose` hook, so it's time to close DB connection, and this causes the processing requests fail. And the goal of Graceful shutdown cannot be achieved.

My question is how to really achieve Graceful shutdown? 
Should I count 10 secs in the DB plugin too?

**Comment by mcollina** [comment]
Did check out https://github.com/hemerajs/fastify-graceful-shutdown/blob/master/index.js?

@StarpTech maybe you can help?
