### ISSUE TITLE
Is not a function sequelize on Fastify

### ISSUE THREAD

**Issue by dcalixto** [fastify/help#201]
#### What are you trying to achieve or the steps to reproduce?

Setup the Sequelize on Fastify using the fastify-sequelize or just the pg is showing `is not a function` on controller

So, i've tried just the pg and the controller plus the pg connection works ok, but when i try to separate it as controller and use sequelize i can't get the connect controller function

someone can help?

user Controller

    const fastify = require('fastify')()
    const User = require("../database/models/user")
    
    
    const boom = require("boom");
    
    
    
    const createUser = async (req, reply) => {
        try {
            let user = new User(req.body);
            let newUser = await user.save();
            return newUser
    
        } catch (err) {
            throw boom.boomify(err)
        }
    }
    
    
    
    module.exports = { createUser};

router

    const users = require("../controller/userController");
    
    
    async function routes(fastify, options) {
    
      fastify.post("/users", users.createUser);
    
    }
    
    module.exports = routes;

model

    'use strict';

    
    module.exports = (sequelize, DataTypes) => {
      const User = sequelize.define('User', {
        username: DataTypes.STRING,
        password: DataTypes.STRING,
        email: DataTypes.STRING
      }, {});
      User.associate = function(models) {
        // associations can be defined here
      };
      return User;
    };

index.js

    fastify.register(require("./routes/userRoutes"));
    
    
    const fsequelize = require("fastify-sequelize");
    
    const sequelizeConfig = {
      instance: "sequelize", // the name of fastify plugin instance.
      autoConnect: true, // auto authentication and test connection on first run
    
      // other sequelize config goes here
      dialect: "postgres",
      host: "127.0.0.1",
      database: "api"
      //port: 5432
    
      // SQLite only
      //storage: 'path/to/db.sqlite'
    };
    
    fastify.register(fsequelize, sequelizeConfig).ready();
    
    // Run the server!
    const start = async () => {
      try {
        await fastify.listen(3001);
      } catch (err) {
        fastify.log.error(err);
        process.exit(1);
      }
    };
    start();

```js
// Wrap code in markdown source tags
```

#### What was the result you received?
configure properly sequelize with fastify
#### Context

* *node version*: v14.3.0
* *fastify version*: >=1.5.0
* *os*: Manjaro
* *any other relevant information*:

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by jsumners** [comment]
That’s not a core plugin. Please contact the author of that plugin.
