### ISSUE TITLE
Feature: WebSocket proxying

### ISSUE THREAD

**Issue by coreyfarrell** [fastify/help#202]
## 🚀 Feature Proposal

The ability to proxy WebSockets to include forwarding of cookies / other headers.  This would need to attach to a route for when WebSockets are only supported at specific URL path's.

Sorry to post to the `help` repo but I'm not sure the best repository for this (an existing package or a new one).

## Motivation

I have a legacy perl daemon which has an embedded HTTP server which exposes most API's via normal GET and POST.  One feature of the API is exposed through WebSocket's.  The perl daemon was designed to have nginx on it's front-end and does not support publishing static files.  My goal is to use fastify to fully test the web front-end, the only piece remaining is the ability for fastify to proxy websocket requests.

**Comment by jsumners** [comment]
https://github.com/fastify/fastify-http-proxy/pull/89

**Comment by coreyfarrell** [comment]
@jsumners thanks for your response (sorry for my slow reply).  My question is answered so I'm going to close this issue.  Hopefully at some point soon I'll have time to try adding support for header forwarding and rewrite.
