### ISSUE TITLE
Duplicate handler calls when awaiting promises

### ISSUE THREAD

**Issue by evanradcliffe** [fastify/help#203]
I am exposing POST endpoints with a handler function and pass in context config dynamically based on the endpoint to keep the code DRY. These require api calls so I am using promises. It seems this handler is being called multiple times when looking at logs. Some simple code showing my findings:

#### Steps to reproduce
```js
fastify.post('/test', async (req, res) => {
  const response = await new Promise(resolve => setTimeout(resolve, 100));
  console.log('test log');
  return {
    foo: 'bar'
  }
})
```

#### What was the result you received?

```
test log
test log
```

#### What did you expect?

**BUT** if I comment the promise and otherwise keep the same syntax, I only see the log once.

```js
fastify.post('/test', async (req, res) => {
  // const response = await new Promise(resolve => setTimeout(resolve, 100));
  console.log('test log');
  return {
    foo: 'bar'
  }
})
```

#### Received

```
test log
```

I know there has been some confusion about the use of `async` and promises with this handler so I have been reading around the [docs](https://github.com/fastify/fastify/blob/master/docs/Routes.md#async-await) and [issues](https://github.com/fastify/fastify/issues/1864) to better understand but whether I use return or res.send() I am seeing the foo response object fine, only the duplicate calls are happening with promises.

#### Context

* *node version*: `v8.12.0`
* *fastify version*: `^2.11.0`
* *os*: macOS Mojave `10.14.6 (18G103)`

**Comment by mcollina** [comment]
I missed this, sorry. You are probably calling the callback of a hook twice, or using both an async function and a callback.

**Comment by evanradcliffe** [comment]
`Notice: the done callback is not available when using async/await or returning a Promise. If you do invoke a done callback in this situation unexpected behaviour may occur, e.g. duplicate invocation of handlers.` from [Hooks](https://github.com/fastify/fastify/blob/master/docs/Hooks.md#hooks).

I had a hook signature like `app.addHook('onRequest', async (req, res, done) => {` and was calling `done();`

Thanks @mcollina !

**Comment by mitul45** [comment]
I'm having the same issue, I'm writing a plugin which does some stuff on `onResponse` hook and I'm calling `done();` at the end.

The problem is I don't know who is going to consume this plugin and how they are defining *their* routes i.e. either using `async/await` or not. How can I make sure to not throw warning in this case?

**Comment by Eomm** [comment]
You write the hook function so it is up to you.

> The problem is I don't know who is going to consume this plugin and how they are defining their routes

I assume the user will provide an input function to your plugin: as before it is up to you to check:
- if the input function is an async function or not 
- if the function returns a promise or not

**Comment by mitul45** [comment]
I think I got confused, let me explain a bit more. I have a plugin similar to this:
```ts
const plugin = (fastify, pluginOptions, done) =>  {
  fastify.addHook('onResponse', (request, reply, done) => {
    // synchronous code
    done();
  })
}
```

And then someone using it like following (in async route defination):
```ts
const app = fastify().register(plugin);
app.route('/sample', async (req, rep) => {
  return { hello: 'world' };
})
```

Would this still throw a warning?

**Comment by snx-mfallon** [comment]
Route Handler:

```
 fastify.post('/cart', { preHandler: [authorizeJwt, verifyUser] }, async function (request, reply) {

        try {

            console.log("CART POST!");
            
            const product = await Product.findById("6509aaa9c3d4fca0465f0505");

            return product;

        } catch (e) {

            console.log(e);
            return { message: e.message };

        }


    })
```

**Middleware functions:** 

```
module.exports.authorizeJwt = (req, res, done) => {

    let token = req.headers['abc-access-token'];

    if (!token) {

        return res.status(403).send({ message: "No token provided!" });

    }

    jwt.verify(token, APP_SECRET_KEY, (err, decoded) => {

        if (err) {

            return catchError(err, res);
        }

        req.userId = decoded.id;

        done();

    });
}

module.exports.verifyUser = async (req, res, done) => {

    const user = await User.findById(req.userId);

    if (!user || !user.verified) {

        res.status(403).send({ message: "Unauthorized!" });

    }

    done();

}
```

Whenever I comment out the middleware functions from my route options parameter I no longer get double calls.. should I be calling `done()` in my preHandler middleware functions?

**Comment by kibertoad** [comment]
@snx-mfallon You either call done, or make the method async, but not both.
