### ISSUE TITLE
reply.redirect not including custom headers

### ISSUE THREAD

**Issue by mikehajj** [fastify/help#204]
how can I add custom headers to a reply, then execute reply.redirect?

i tried doing something similar to the following:

reply.header('info', '{ "a": "b"}');
reply.redirect(custom_URL);

I noticed that the API that receives the redirect request does not have headers['info'].

any idea if this is a bug or if I'm doing something wrong?

**Comment by mcollina** [comment]
Likely you might have hit a bug? Would you like to send a PR? I think se should fix this in the upcoming v3.

**Comment by Eomm** [comment]
This snipper works as expected in v3:

```js
const fastify = require('fastify')({ logger: true })

fastify.get('/', function (req, reply) {
  reply.send('ok')
})
fastify.get('/redirect', function (req, reply) {
  reply.header('hello', 'world')
  reply.redirect('/')
})

fastify.inject('/redirect', (_, res) => {
  console.log(res.headers)
})
```

Please, provide a running example to replicate the issue
