### ISSUE TITLE
Item schema type not applying to numbers in an array

### ISSUE THREAD

**Issue by awarmfastbear** [fastify/help#205]
#### You have already researched for similiar issues?
It's not uncommon that somebody already opened an issue or in best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/fastify/fastify/issues) at first before submitting a new one.

#### What are you trying to achieve or the steps to reproduce?

I am testing a simple route where I only want to be able to accept 3 strings in an array like:

["MSFT", "NFLX", "TSLA"]

However if I send an array of:

[ 1, "MSFT", "NFLX" ]

It's also accepted with a 200 and the 1 turns into a string when printed on the local console.

Why is the 1 being accepted when the schema says it needs to be a string?

From what I understand of the JSON List validation schema this should be possible:
https://json-schema.org/understanding-json-schema/reference/array.html#id5

>List validation is useful for arrays of arbitrary length where each item matches the same schema. For this kind of array, set the items keyword to a single schema that will be used to validate all of the items in the array.

curl output of this passing:

```
Mclovin@MSI MINGW64 ~
$ curl --header "Content-Type: application/json" \
>   --request POST \
>   --data '[1,"test"]' \
> http://localhost:4000/batch_stocks
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    17  100     7  100    10     31     45 --:--:-- --:--:-- --:--:--    76
Success

Mclovin@MSI MINGW64 ~
$ curl --header "Content-Type: application/json" \
>   --request POST \
>   --data '[1,2,3]' \
> http://localhost:4000/batch_stocks
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100     7  100     7     33     33 --:--:-- --:--:-- --:--:--    66
Success
```

```js
'use strict'

const batchStocksSchema = {
  body: {
    type: 'array',
    maxItems: 3,
    items: { type: "string" },
    additionalProperties: false,
  },
}

module.exports = async function (fastify, opts) {

  fastify.post('/batch_stocks', {
    schema: batchStocksSchema
  }, async function (request, reply) {
    try {
      console.log(request.body)
      return reply
        .code(201)
        .send('Success')

    } catch (e) {
      return reply
        .code(400)
        .send('Bad Request')
    }
  })
}
```

#### What was the result you received?

A 201 success

#### What did you expect?

A 400 request due to the number not being a string

#### Context

* *node version*: v12.16.3
* * "fastify": "^2.13.0",
* *os*:  Windows 10
* *any other relevant information*:

I am testing with Postman and curl.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by jsumners** [comment]
The default schema validation options will coerce types -- https://github.com/fastify/fastify/blob/f0a6e3d51a43fd081aa36ac7443f0f5543bc8a34/docs/Validation-and-Serialization.md#validator-compiler

So `1` is being coerced to `'1'`.

**Comment by awarmfastbear** [comment]
This makes a lot more sense! Thank you
