### ISSUE TITLE
How do I process API calls to a route sequentially?

### ISSUE THREAD

**Issue by davingreen** [fastify/help#207]
New to fastify (and JS servers in general), but starting to get the hang of it. 

I have a use-case where I need to process calls to an endpoint sequentially. For example, I have multiple apps that call the endpoint `/do-next-task` where the service will check for the next task in a database table and complete it. (Let's assume tasks are not specific to one app and that a task can involve asynchronous operations like database updates.)

But, several apps call the endpoint `/do-next-task` at the same time, how do I force fastify to complete the first response before processing the next request (so that the same task is never being done twice)? Or will fastify do this by default?

Maybe put another way: I need a route that should never process more than one response at a time, even if a response takes time...

Thanks!

**Comment by mcollina** [comment]
This does not work out of the box. You'll need to write yourself some code to handle this.

I would recommend to use https://www.npmjs.com/package/piscina in you route with only one worker thread.
Or use https://www.npmjs.com/package/fastq with only 1 query.

**Comment by StarpTech** [comment]
This is a common problem for a message queue. If you handle it server-side you can't scale up your server without coordinate that process manually. Therefore if your server crashes for any reason you have no way to resume. You can do it with the tools @mcollina recommended but it's very limited regarding reliability and scaling.

**Comment by Eomm** [comment]
For these kinds of task, I used to work with [bull](https://www.npmjs.com/package/bull) under the hood, to avoid manually synchronization across servers

You can have as many fastify instances as your scalability need, the endpoint should only check the state of a job asking to bull and reply accordingly and it implement restart of jobs if server crash, enqueue, max concurrency job etc..

**Comment by davingreen** [comment]
Thanks for the thoughtful replies!

I'm looking into fastq for a temporary fix and bull for long-term. My app will probably need a more event-driven model before I got to scale, but I like this progression.
