### ISSUE TITLE
Which fastify version to use

### ISSUE THREAD

**Issue by gc** [fastify/help#209]
Hi. I was wondering what fastify version you would recommend I use, if I'm just about to start making an api with fastify. v2 or v3? If I use v2 I know I will probably at some point upgrade to v3, but i dont know whats the status on v3, what does it bring/change and how stable it is. I use typescript and I dont mind if some plugins arent up to date for v3. Wouldnt be too nice for me to finish the api in v2 and then v3 releases, would rather just write it in v3 first

**Comment by Ethan-Arrowood** [comment]
I may be biased, but use v3 😉 it is in release-candidate stage now so while some breaking changes still might land it should be stable enough to start working on.

**Comment by jsumners** [comment]
Please use our LTS policy to make your decision -- https://github.com/fastify/fastify/blob/d38c247fd48f0f9180798cae11f935b3a5eb19f7/docs/LTS.md

**Comment by delvedor** [comment]
v3 is expected to be released this week or the next one, so I would recommend v3! ;)

**Comment by gc** [comment]
Thank you! I think its a good idea for me to use v3.
