### ISSUE TITLE
`onResponse` hook is not called in rare cases

### ISSUE THREAD

**Issue by giltayar** [fastify/help#210]
#### You have already researched for similiar issues?

Yup. Looked everywhere.

#### What are you trying to achieve or the steps to reproduce?

I want to "log" (to Redis) something at the end of each response. So I use the `onResponse` hook, combined with `setErrorHandler` to do this.

#### What was the result you received?

In very rare cases, specifically when Firefox is trying to refetch a cached resource (weird, right?), the route handler ends correctly (I log the start and end of it), and yet the `onResponse` does not get called, nor does the `setErrorHandler` callback get called.

Unfortunately, this is a very rare issue (0.1%, and _only_ in production), so I can't reproduce it.

#### What did you expect?

`onResponse` or error handler should be called whatever.

#### Context

* *node version*: 12
* *fastify version*: 2.15.1
* *os*: Linux (Docker on Kubernetes)
* *any other relevant information*: (I think) its only when Firefox is trying to refetch a cached resource, so maybe it's aborting the request?

I'm going to try to do an `await reply` in the route handler instead, but I'd rather it be dealt with in a more regular way.

Frankly, this should be a bug request, but I _may_ be misunderstanding `onResponse`, and I can't file a bug request that is _so_ vague.

**Comment by mcollina** [comment]
It would be good if you could reproduce (with code), otherwise it will be impossible for us to fix :(.

**Comment by giltayar** [comment]
@mcollina I know! And I tried! But this request for help is not so much to file a bug (which I wouldn't dare to do with no reproduction...) but rather to request help on understanding the `onResponse` hook: to understand whether my understanding that all requests end up either in `onResponse` or in the error handler, and to ensure that there is no way that a request started yet didn't end up in one of those two places.

**Comment by mcollina** [comment]
It might happen that a request does not end up there if you use the raw objects from
node core

**Comment by Eomm** [comment]
Could it be related to this?

https://github.com/fastify/fastify/blob/9bcacb37822e5832d245e162162949ad1fea6e36/fastify.js#L381

I'm not sure if this is caught by the error handler

**Comment by giltayar** [comment]
@Eomm Yes! It's weird enough to be something like that (as I said above: "i'ts only when Firefox is trying to refetch a cached resource, so maybe it's aborting the request").

Unfortunately, given the `clientError` error being triggered on the server, there's not a lot I _can_ do (assuming Fastify adds an event for this) because I don't know what the current request is. Worse. If I understand `clientError` correctly, it's so low-level that I _can't_ figure out what the current request is.

So unless someone can think of a way to tie the `clientError` to the current request, so as to send it an `onResponse`, I'd have to unfortunately close this issue and go cry in a corner, because, at least for me, `onResponse` becomes 99.9% reliable, but note more than that. 😞

If someone _can_ think of a way to tie the `clientError` to the current request, I'd gladly implement it in a PR.

**Comment by giltayar** [comment]
If there's a way to go over all "current" request objects, look at their sockets, and find the one with the socket given in the error, then it might be possible to tie the error to a request.

**Comment by Eomm** [comment]
In v3 you can customize it
https://github.com/fastify/fastify/blob/master/docs/Server.md#clienterrorhandler

I don't remember why we didn't backport it

**Comment by giltayar** [comment]
Makes sense.

Unfortunately, that doesn't solve the `onResponse`/error handler problem, where it's not guaranteed that every request that started will always get to either the `onResponse` hook or the error handler.

**Comment by jsumners** [comment]
You cannot guarantee a request will ever be "completed". It doesn't matter what framework you are using in whatever language.

**Comment by Ethan-Arrowood** [comment]
> You cannot guarantee a request will ever be "completed"

One of the best parts of working with web servers 😅
