### ISSUE TITLE
Response schema removes from your response?

### ISSUE THREAD

**Issue by gc** [fastify/help#211]
I spent a long time debugging why my routes/middlewares were causing my route to send a response containing only `{}`, after a while i just started deleting everything piece by piece until it stopped, and I realized it was the response schema - fastify removes stuff from your response if its not in your schema?

I had 2 questions, (1) is this documented somewhere? if so i probably just missed it and its my fault. (2) can i change this behaviour? for example, if i have a schema for my route, if I expect my route to have that exact schema as a response, logically I'd want to throw an error if im not following my exact planned schema? so i can know that my route isnt returning what i expect it to.

Thank you

**Comment by jsumners** [comment]
The AJV defaults are described at https://www.fastify.io/docs/v2.15.x/Validation-and-Serialization/#validator-compiler

**Comment by Eomm** [comment]
You need to use this plugin [fastify-response-validation](https://github.com/fastify/fastify-response-validation) to archive your need.

The response schema is managed by [fast-json-stringify](https://github.com/fastify/fast-json-stringify), for this reason the output is strict.
If you want to return a "dynamic" json, you need to set the schema as follows:

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "additionalProperties": false
}
```

If you would like to improve our docs, it is appreciated!

**Comment by gc** [comment]
Cool, thanks :)
