### ISSUE TITLE
Question: render error output according to custom serializer?

### ISSUE THREAD

**Issue by sdevalk** [fastify/help#212]
#### You have already researched for similiar issues?
Yes.

#### What are you trying to achieve or the steps to reproduce?
If an error is thrown in my custom content type parser, I want to render an error according to my custom serializer and custom error handler. Instead, Fastify renders an error according to the default JSON serializer. How can I change this?

File: `package.json`
```json
{
    "dependencies": {
      "fastify": "3.0.0-rc.5",
      "fastify-accepts-serializer": "3.0.0",
      "fastify-plugin": "2.0.0"
    }
  }
```

File: `server.js`
```js
'use strict';

const assert = require('assert');
const fastify = require('fastify');
const fp = require('fastify-plugin');

// Simple class, just for demonstration
class Renderer {
    obj;
    constructor(obj) {
        this.obj = obj;
    }
    render() {
        return this.obj.message;
    }
};

// --------------------

async function setErrorHandlers(fastify) {
    fastify.setErrorHandler((error, request, reply) => {
        const renderer = new Renderer(error);
        reply.code(500).send(renderer);
    });
    fastify.setNotFoundHandler((request, reply) => {
        const renderer = new Renderer({ message: 'Not found!' });
        reply.code(404).send(renderer);
    });
}

const pluginErrorHandler = fp(setErrorHandlers);

// --------------------

async function setSerializer(fastify) {
    fastify.register(require('fastify-accepts-serializer'), {
        serializers: [
            {
                regex: /^application\/custom$/,
                serializer: (body) => {
                    assert(body instanceof Renderer, 'Not an instance of Renderer');
                    return body.render();
                }
            }
        ],
    });
}

const pluginSerializer = fp(setSerializer);

// --------------------

async function setParser(fastify) {
    fastify.addContentTypeParser(
        'application/custom',
        async (request, payload) => {
            if (request.url === '/pang') {
                throw Error('Bad payload');
            }
        }
    );
}

const pluginParser = fp(setParser);

// --------------------

async function startServer() {
    const server = fastify({ logger: true });

    server.register(pluginSerializer);
    server.register(pluginErrorHandler);
    server.register(pluginParser);

    server.get('/ping', {}, async (request, reply) => {
        const renderer = new Renderer({ message: 'Ping!' });
        reply.send(renderer);
    });

    server.post('/pong', {}, async (request, reply) => {
        throw Error('Pong!');
    });

    server.post('/pang', {}, async (request, reply) => {
        reply.send();
    });

    await server.listen(3000, '0.0.0.0');
}

(async () => {
    try {
        await startServer();
    } catch (err) {
        console.error(err);
    }
})();
```

#### What was the result you received?

1. Start the server: `node server.js`
2. Execute `curl -i -H "Accept: application/custom" localhost:3000/ping` --> the string `Ping!` with `content-type: application/custom` is returned. Perfect!
3. Execute `curl -i -H "Accept: application/custom" localhost:3000/missing` --> the string `Not found!` with `content-type: application/custom` is returned. Perfect!
4. Execute `curl -i -d "{1: 2}" -H "Content-Type: application/custom" -H "Accept: application/custom" localhost:3000/pong` --> the string `Pong!` with `content-type: application/custom` is returned. Perfect!
5. Execute `curl -i -d "{1: 2}" -H "Content-Type: application/custom" -H "Accept: application/custom" localhost:3000/pang` --> the output `{"obj":{}}` with `content-type: application/json; charset=utf-8` is returned.

#### What did you expect?

I expect step 5 to return the string `Bad payload` with `content-type: application/custom`.

#### Context

* *node version*: 12
* *fastify version*: 3.0.0-rc.5
* *fastify-accepts-serializer version*: 3.0.0
* *fastify-plugin version*: 2.0.0
* *os*: Linux

**Comment by Eomm** [comment]
> Instead, Fastify renders an error according to the default JSON serializer. How can I change this?

I think it should be a bug. We should reproduce it without the plugin to understand if it is a problem in the core or in the plugin itself
