### ISSUE TITLE
Any way to ignore auto slash in nested registered prefixes?

### ISSUE THREAD

**Issue by ankology** [fastify/help#213]
```
const app = fastify({

    ignoreTrailingSlash: false
});

app.register((app, opts, done) => {

    app.register((app, opts, done) => {

        app.get('.route', (request, reply) => {

            reply.send('data');
        });

        app.register((app, opts, done) => {

            app.get('.route', (request, reply) => {

                reply.send('data');
            });

            done();

        }, {prefix: '.c'})

        done();

    }, {prefix: '.b'})

    done();

}, {prefix: 'a'});
```
```
Result: 
└── /
    └── a/.b
        ├── .route (GET)
        └── /.c.route (GET)
```

The code will register the route as **/a/.b.route** and **/a/.b/.c.route** exists some way to ignore slash to nested registers to make a route like **/a.b.route** and **/a.b.c.route** ?

**Edit 1**
Doing this make it works for both scenarios (with prefix starting with ```/``` or ```.```) but is a bad practice, but override the default addition of a slash for the routes:
```
app.addHook('onRegister', (instance) => {

      const routePrefixSymbol = Object.getOwnPropertySymbols(instance)[5];
      instance[routePrefixSymbol] = instance.prefix.replace(/(\/\.)/g, `.`);
});
```

**Comment by mcollina** [comment]
We designed `prefix` to use `/` as a delimiter. I think your use case is not supported. I'm not 100% sure of all the consequences of supporting this directly, but if you would like to give it a stab I would be very happy to review.

**Comment by ankology** [comment]
Sure! Thanks
