### ISSUE TITLE
Infer RequestGenericInterface values from a typed schema

### ISSUE THREAD

**Issue by pandaniell** [fastify/help#218]
#### You have already researched for similiar issues?
Yes

#### What are you trying to achieve or the steps to reproduce?
I am trying to make the values in `RequestGenericInterface` infer from a typebox schema

I tried to comment out all `RouteShorthandMethods` in `types/instance.d.ts` and create my own declarations

```ts
import { Static, TSchema } from "@sinclair/typebox";
import {
  ContextConfigDefault,
  FastifyInstance,
  FastifyLoggerInstance,
  FastifySchema,
  RawReplyDefaultExpression,
  RawRequestDefaultExpression,
  RawServerBase,
  RawServerDefault,
  RouteHandlerMethod,
  RouteShorthandOptions,
} from "fastify";

declare module "fastify" {
  interface FastifyInstance<
    RawServer extends RawServerBase = RawServerDefault,
    RawRequest extends RawRequestDefaultExpression<
      RawServer
    > = RawRequestDefaultExpression<RawServer>,
    RawReply extends RawReplyDefaultExpression<
      RawServer
    > = RawReplyDefaultExpression<RawServer>,
    Logger = FastifyLoggerInstance
  > {
    get: Route<RawServer, RawRequest, RawReply>;
    head: Route<RawServer, RawRequest, RawReply>;
    post: Route<RawServer, RawRequest, RawReply>;
    put: Route<RawServer, RawRequest, RawReply>;
    delete: Route<RawServer, RawRequest, RawReply>;
    options: Route<RawServer, RawRequest, RawReply>;
    patch: Route<RawServer, RawRequest, RawReply>;
    all: Route<RawServer, RawRequest, RawReply>;
  }
}

interface Schema extends FastifySchema {
  body?: TSchema;
  querystring?: TSchema;
  params?: TSchema;
  headers?: TSchema;
  response?: {
    [code: number]: TSchema;
    [code: string]: TSchema;
  };
}

interface Route<
  RawServer extends RawServerBase = RawServerDefault,
  RawRequest extends RawRequestDefaultExpression<
    RawServer
  > = RawRequestDefaultExpression<RawServer>,
  RawReply extends RawReplyDefaultExpression<
    RawServer
  > = RawReplyDefaultExpression<RawServer>
> {
  <
    U extends Schema,
    RequestGeneric extends {
      Body?: Static<U["body"]>;
      Querystring?: Static<U["querystring"]>;
      Params?: Static<U["params"]>;
      Headers?: Static<U["headers"]>;
    },
    ContextConfig = ContextConfigDefault
  >(
    path: string,
    opts: Omit<
      RouteShorthandOptions<
        RawServer,
        RawRequest,
        RawReply,
        RequestGeneric,
        ContextConfig
      >,
      "schema"
    > & { schema?: Partial<U> },
    handler: RouteHandlerMethod<
      RawServer,
      RawRequest,
      RawReply,
      RequestGeneric,
      ContextConfig
    >
  ): FastifyInstance<RawServer, RawRequest, RawReply>;
}

export const schema = (typeboxSchema: Schema) => typeboxSchema;
```

#### What was the result you received?
```ts
import { Type } from "@sinclair/typebox";

server.get(
  "/",
  { schema: schema({ params: { id: Type.String() } }) },
  (request, response) => {
    const id = request.params.id;
  }
);
```
The parameters do not infer properly

#### What did you expect?
I would like to achieve inference through models instead of having to declare the generic on every method myself in order to type the query / params etc

#### Context

* *node version*: 14
* *fastify version*: ^3.0.2
* *os*: Mac, Windows, Linux
* *any other relevant information*:

**Comment by mcollina** [comment]
I don't understand this issue. I think you are trying to integrate typebox with JSON schema, and I think they are two fundamentally different specs and implementations.

Adding a similar capability to fluent-schema would be nice.

Maybe @Ethan-Arrowood has some idea.

**Comment by pandaniell** [comment]
> 
> 
> I don't understand this issue. I think you are trying to integrate typebox with JSON schema, and I think they are two fundamentally different specs and implementations.
> 
> Adding a similar capability to fluent-schema would be nice.
> 
> Maybe @Ethan-Arrowood has some idea.

They are supossed to work together https://github.com/fastify/fastify/issues/1668#issuecomment-594998612 my issue is mostly focussed on typings, as you can see in the example, the `Query` interface gets passed into the `.get` generic, I'd like to get rid of that since the type could be inferred from the schema as well like I tried in my code example, it would be nice if we could declare a schema and have the request query / parameters be inferred from it

**Comment by mcollina** [comment]
> They are supossed to work together

That issue is still open, and there are no automated tests to prove/verify that :(. It does not surprise me it got broken.

Would you like to send a PR to fix this and add tests?

**Comment by pandaniell** [comment]
I managed to fix my original issue, all I had to do was change `export const schema = <T extends Schema>(typeboxSchema: T) => typeboxSchema`, which allows me to do the following:
```typescript
server.get(
  "/",
  {
    schema: schema({
      params: Type.Object({
        id: Type.String(),
      }),
    }),
  },
  (request, response) => {
    // id is inferred as `string?`
    const id = request.params?.id;
  }
);
```
I lack the knowledge of testing / typebox / fastify to write tests (only been using it for a few days), otherwise I would have loved to create them, I tested lots common use cases (not automated) and they all seemed to work fine so I am happy with this setup, thanks for the fast response!

**Comment by Ethan-Arrowood** [comment]
Yeah this is a hard issue, because not all of our users pass in their schema in this way; some will use .json files and pass in that and I'm not sure how the types work in those cases. 

This work looks great, if you'd like to send a PR with your edits we can look them over together and see if they can be included without breaking the current types. We'd love this sort of schema/type support

**Comment by pandaniell** [comment]
I think it will be pretty hard to make them work together, it would introduce a lot of conditional types making it hard to read, I think it currently is as good as it is, the way it's set up now with generics allow users to overwrite the default typings to work with a custom lib, it might be worth to consider testing something like typebox fully and maybe integrate it with fastify / make it the default optional lib for schemas (something like `@fastify/json-schema`) which overrides the typings and exports a helper function like in this issue, typebox seems to have a MIT license

**Comment by Ethan-Arrowood** [comment]
Great idea @pandaniell - as Matteo said, this might have a good home in https://github.com/fastify/fluent-schema

If you're interested in contributing there instead the fastify contributor team would be happy to help you out!

**Comment by pandaniell** [comment]
I see, would you be interested in migrating this to typebox? If so, I could work on a PR with a base setup and ask for input on tests

**Comment by Ethan-Arrowood** [comment]
Ahh I see Typebox replaces fluent-schema... hmm okay then no I don't see this a contribution there. It may be best to make your own fastify plugin. Something like fastify-typebox with adds these types and maybe exposes the typebox module through the fastify object

**Comment by pandaniell** [comment]
I will check plugins out, thanks!
