### ISSUE TITLE
Plugin shows server.x is not a function

### ISSUE THREAD

**Issue by pandaniell** [fastify/help#220]
#### What are you trying to achieve or the steps to reproduce?
I created the following [plugin](https://github.com/foodsy-app/fastify-typebox/blob/master/index.ts), when I import it, I get a error saying `server.typeboxSchema is not a function`, did I export it wrong or missed something in the plugin docs?

```typescript
// Using import because linter complains about require
import fastifyTypebox from "@foodsy-app/fastify-typebox";

const server = fastify({ logger });

server.register(fastifyTypebox);

server.get(
  "/",
  {
    schema: server.typeboxSchema({
      querystring: Type.Object({ id: Type.Number({ minimum: 5 }) }),
    }),
  },
  async (request) => request.query?.id
);
```

#### What was the result you received?
`server.typeboxSchema is not a function`

#### Context

* *node version*: >=14
* *fastify version*: ^3.0.2
* *os*: Windows

**Comment by Eomm** [comment]
You must wait the plaing loading:

```
server.register(fastifyTypebox).after(()=>{
  server.get(
  "/",
  {
    schema: server.typeboxSchema({
      querystring: Type.Object({ id: Type.Number({ minimum: 5 }) }),
    }),
  },
  async (request) => request.query?.id
  );
})
```

The plugins registered are loaded when you start the server.

There are [other options](https://github.com/fastify/fastify/blob/master/docs/Plugins.md#asyncawait) like `await server.register(fastifyTypebox)` etc..

**Comment by pandaniell** [comment]
Totally missed that, thanks!
