### ISSUE TITLE
avvio logs clutter

### ISSUE THREAD

**Issue by davingreen** [fastify/help#221]
Just installed and ran. Why am I seeing all these avvio logs? Can I turn those off?

`  
avvio exec bound root +0ms
  avvio enqueue bound root bound _after +2ms
  avvio enqueue bound root /c/.../fastify/app.js +1ms
  avvio thenify +0ms
  avvio enqueue bound root bound _after +2ms
  avvio exec bound _after +0ms
  avvio setting up timeout bound _after 10000 +0ms
  avvio setting up ready timeout bound _encapsulateThreeParam 10000 +3ms
  avvio exec completed bound _after +5ms
  avvio finish bound _after null +1ms
  avvio check bound _after 0 0 null +1ms
  avvio loaded bound _after +1ms
  avvio exec /c/.../fastify/app.js +1ms
  avvio setting up timeout /c/.../fastify/app.js 10000 +0ms
  avvio enqueue /c/.../fastify/app.js /c/.../fastify/node_modules/fastify-autoload/index.js +1ms
  avvio enqueue /c/.../fastify/app.js /c/.../fastify/node_modules/fastify-autoload/index.js +1ms
  avvio exec: resolving promise /c/.../fastify/app.js +0ms
  avvio exec completed /c/.../fastify/app.js +0ms
  avvio finish /c/.../fastify/app.js undefined +1ms
  avvio exec /c/.../fastify/node_modules/fastify-autoload/index.js +0ms
  avvio setting up timeout /c/.../fastify/node_modules/fastify-autoload/index.js 10000 +0ms
  avvio exec: resolving promise /c/.../fastify/node_modules/fastify-autoload/index.js +1ms
  avvio check /c/.../fastify/app.js 1 1 null +0ms
  avvio delayed /c/.../fastify/app.js +0ms
  avvio enqueue /c/.../fastify/node_modules/fastify-autoload/index.js /c/.../fastify/plugins/support.js +160ms
  avvio exec completed /c/.../fastify/node_modules/fastify-autoload/index.js +1ms
  avvio finish /c/.../fastify/node_modules/fastify-autoload/index.js undefined +0ms
  avvio exec /c/.../fastify/plugins/support.js +0ms
  avvio setting up timeout /c/.../fastify/plugins/support.js 10000 +1ms
  avvio exec: resolving promise /c/.../fastify/plugins/support.js +0ms
  avvio check /c/.../fastify/node_modules/fastify-autoload/index.js 0 1 null +0ms
  avvio delayed /c/.../fastify/node_modules/fastify-autoload/index.js +1ms
  avvio exec completed /c/.../fastify/plugins/support.js +0ms
  avvio finish /c/.../fastify/plugins/support.js undefined +0ms
  avvio check /c/.../fastify/plugins/support.js 0 0 null +0ms
  avvio loaded /c/.../fastify/plugins/support.js +0ms
  avvio drain /c/.../fastify/node_modules/fastify-autoload/index.js +0ms
  avvio check /c/.../fastify/node_modules/fastify-autoload/index.js 0 0 null +0ms
  avvio loaded /c/.../fastify/node_modules/fastify-autoload/index.js +1ms
  avvio exec /c/.../fastify/node_modules/fastify-autoload/index.js +0ms
  avvio setting up timeout /c/.../fastify/node_modules/fastify-autoload/index.js 10000 +0ms
  avvio exec: resolving promise /c/.../fastify/node_modules/fastify-autoload/index.js +0ms
  avvio enqueue /c/.../fastify/node_modules/fastify-autoload/index.js /c/.../fastify/routes/root.js +71ms
  avvio enqueue /c/.../fastify/node_modules/fastify-autoload/index.js /c/.../fastify/routes/example/index.js +1ms
  avvio exec completed /c/.../fastify/node_modules/fastify-autoload/index.js +0ms
  avvio finish /c/.../fastify/node_modules/fastify-autoload/index.js undefined +0ms
  avvio exec /c/.../fastify/routes/root.js +1ms
  avvio setting up timeout /c/.../fastify/routes/root.js 10000 +0ms
  avvio enqueue /c/.../fastify/routes/root.js bound _after +1ms
  avvio exec: resolving promise /c/.../fastify/routes/root.js +1ms
  avvio check /c/.../fastify/node_modules/fastify-autoload/index.js 1 1 null +0ms
  avvio delayed /c/.../fastify/node_modules/fastify-autoload/index.js +0ms
  avvio exec completed /c/.../fastify/routes/root.js +0ms
  avvio finish /c/.../fastify/routes/root.js undefined +0ms
  avvio exec bound _after +0ms
  avvio setting up timeout bound _after 10000 +0ms
  avvio setting up ready timeout bound _encapsulateThreeParam 10000 +252ms
  avvio exec completed bound _after +2ms
  avvio finish bound _after null +0ms
  avvio check /c/.../fastify/routes/root.js 0 1 null +1ms
  avvio delayed /c/.../fastify/routes/root.js +0ms
  avvio check bound _after 0 0 null +0ms
  avvio loaded bound _after +0ms
  avvio drain /c/.../fastify/routes/root.js +0ms
  avvio check /c/.../fastify/routes/root.js 0 0 null +0ms
  avvio loaded /c/.../fastify/routes/root.js +0ms
  avvio exec /c/.../fastify/routes/example/index.js +2ms
  avvio setting up timeout /c/.../fastify/routes/example/index.js 10000 +0ms
  avvio enqueue /c/.../fastify/routes/example/index.js bound _after +2ms
  avvio exec: resolving promise /c/.../fastify/routes/example/index.js +1ms
  avvio exec completed /c/.../fastify/routes/example/index.js +1ms
  avvio finish /c/.../fastify/routes/example/index.js undefined +0ms
  avvio exec bound _after +0ms
  avvio setting up timeout bound _after 10000 +1ms
  avvio setting up ready timeout bound _encapsulateThreeParam 10000 +9ms
  avvio exec completed bound _after +2ms
  avvio finish bound _after null +0ms
  avvio loading complete bound _after +0ms
  avvio check /c/.../fastify/routes/example/index.js 0 1 null +0ms
  avvio delayed /c/.../fastify/routes/example/index.js +0ms
  avvio check bound _after 0 0 null +1ms
  avvio loaded bound _after +0ms
  avvio drain /c/.../fastify/routes/example/index.js +0ms
  avvio check /c/.../fastify/routes/example/index.js 0 0 null +0ms
  avvio loaded /c/.../fastify/routes/example/index.js +0ms
  avvio drain /c/.../fastify/node_modules/fastify-autoload/index.js +0ms
  avvio check /c/.../fastify/node_modules/fastify-autoload/index.js 0 0 null +0ms
  avvio loaded /c/.../fastify/node_modules/fastify-autoload/index.js +0ms
  avvio drain /c/.../fastify/app.js +1ms
  avvio check /c/.../fastify/app.js 0 0 null +0ms
  avvio loaded /c/.../fastify/app.js +0ms
  avvio exec bound _after +0ms
  avvio setting up timeout bound _after 10000 +0ms
  avvio setting up ready timeout bound _encapsulateThreeParam 10000 +5ms
  avvio resolving promise bound root +2ms
  avvio exec completed bound _after +10ms
  avvio finish bound _after null +0ms
  avvio exec completed bound root +1ms
  avvio finish bound root undefined +0ms
  avvio check bound _after 0 0 null +0ms
  avvio loaded bound _after +0ms
  avvio check bound root 0 0 null +0ms
  avvio loaded bound root +1ms
  avvio root plugin ready +13ms
  avvio setting up ready timeout bound _encapsulateThreeParam 10000 +1ms
  avvio setting up ready timeout bound _encapsulateThreeParam 10000 +1ms
  avvio setting up ready timeout bound _encapsulateThreeParam 10000 +0ms
  avvio thenify returning null because we are already booted +0ms
  avvio loading complete bound root +7ms
  avvio loading complete bound root +0ms
  avvio thenify returning null because we are already booted +13ms
  avvio thenify returning null because we are already booted +1ms
`

Thanks!

**Comment by mcollina** [comment]
avvio uses the `debug` module. You likely have `DEBUG=*` in your env.
