### ISSUE TITLE
Is it possible to register handlebars helpers with point-of-view?

### ISSUE THREAD

**Issue by ikex** [fastify/help#222]
I've read this entire template before posting my question, but wasn't able to find any documentation on it. I wonder if it's possible (or is it planned?) to register custom handlebars helpers with point-of-view. Or is it possible to register it manually?

https://handlebarsjs.com/api-reference/runtime.html#handlebars-registerhelper-name-helper

**Comment by Eomm** [comment]
Yes you can, here a fast snippet:

```js

const fastify = require('fastify')()
const handlebars = require('handlebars')

handlebars.registerHelper('foo', function () { return 'hello' })

fastify.register(require('point-of-view'), {
  engine: {
    handlebars: handlebars
  }
})

fastify.get('/', (req, reply) => {
  reply.view('./templates/my.hbs') // {{foo}}
})

fastify.listen(3000)

```
