### ISSUE TITLE
[Question] Indent JSON output ?

### ISSUE THREAD

**Issue by KaKi87** [fastify/help#224]
Hello,

I was wondering if it would be possible to indent JSON body returned with `reply.send` ?

Thanks.

**Comment by mcollina** [comment]
It's not really possible right now unless you do it yourself.

why/when would you do that?

**Comment by KaKi87** [comment]
Sometimes I create really simple GET endpoints that I directly use in my browser, for instance, https://api.kaki87.net/dns/fastify.io and https://api.kaki87.net/whois/fastify.io, so it's readable on my personal computer because I have a specific Chrome extension to parse and color-highlight it, but it won't be readable on my phone or anyone else's device. Thanks

**Comment by mcollina** [comment]
That would not be possible with fast-json-stringify and the schema output. Unfortunately  I don't think it's easy to implement this and keep existing functionality working.

**Comment by KaKi87** [comment]
> unless you do it yourself

How do I do that ?
Thanks.
