### ISSUE TITLE
Helmet 4 with fastify-helmet

### ISSUE THREAD

**Issue by EvanHahn** [fastify/help#225]
[fastify-helmet](https://github.com/fastify/fastify-helmet) is a port of Helmet to Fastify. I maintain Helmet and am planning on releasing the next major version on Sunday, 2020-08-02 (a few days from now).

Can I offer any help upgrading fastify-helmet to Helmet 4 when it comes out? (If helpful, you can install the release candidate with `npm install helmet@next`.)

Let me know if I should open an issue on fastify-helmet or do something else! If you'd prefer to drop me a line, you can [contact me via email and other things](https://evanhahn.com/contact).

**Comment by jsumners** [comment]
I think a PR to `fastify-helmet` would be most welcome.

**Comment by EvanHahn** [comment]
Looks like this is done in https://github.com/fastify/fastify-helmet/pull/84. I'll close this issue and move discussion there!

Thanks for the quick response.
