### ISSUE TITLE
Core Plugins: fastify-request-context

### ISSUE THREAD

**Issue by goodvir** [fastify/help#229]
Hello, `npm` is missing a version with` fastify 3.x` support, 
there is a commit that says the changes have been made: 
**Commits on Jul 19, 2020** [Upgrade to fastify 3](https://github.com/fastify/fastify-request-context/commit/239e0ca8b02208634291b9d07a7f577ba6af86a5)

**Comment by mcollina** [comment]
@kibertoad would you mind to release a new version?

**Comment by kibertoad** [comment]
@mcollina Will give it a shot today, sorry for the delay.

**Comment by kibertoad** [comment]
Released in 2.0.0
