### ISSUE TITLE
How sign out with fastify-oauth2

### ISSUE THREAD

**Issue by jenkasia** [fastify/help#232]

**Comment by Eomm** [comment]
Usually, you store the token in a cookie, so you may create an endpoint `logout` that deletes the cookie

**Comment by jenkasia** [comment]
> Usually, you store the token in a cookie, so you may create an endpoint `logout` that deletes the cookie

It's don't help me

**Comment by jsumners** [comment]
Neither can we without any real information. What have you attempted? What errors do you see?

**Comment by jenkasia** [comment]
> Neither can we without any real information. What have you attempted? What errors do you see?

Ok, i use fastify-oauth2 for implement google auth to my project, 

`const server = fastify();

server.register(oauthPlugin, {
  name: 'googleOAuth2',
  scope: ['profile email'],
  credentials: {
    client: {
      id: process.env.GOOGLE_OAUTH_CLIENT_ID,
      secret: process.env.GOOGLE_OAUTH_CLIENT_SECRET,
    },
    auth: oauthPlugin.GOOGLE_CONFIGURATION,
  },
  startRedirectPath: '/api/auth/google',
  callbackUri: 'http://localhost:5001/api/auth/google/callback',
});

server.get('/api/auth/google/callback', {}, async function (req, res) {
  // Fastify instance gets decorated with this method on OAuth plugin initialization
  const token = await server.googleOAuth2.getAccessTokenFromAuthorizationCodeFlow(req);
  // Redirect to a route serving HTML or to your front-end
  res.send({ access_token: token.access_token });
});

server.get('/api/logout', {}, async function (req, res) {
  // Redirect to a route serving HTML or to your front-end
  res.setCookie('token', '', {
    expires: new Date('01-01-1997'),
  });
  res.redirect('http://localhost:3000');
});
`
When I authenticate firstly I redirect to google page to authorization, but then when I logout and again I get token without authorization in google

**Comment by Eomm** [comment]
Why do you have callback with 5001 port and logout with 3000?

I think you are not cleaning the cookie. Did you check it in chrome reading the set-cookie response headers?

**Comment by jenkasia** [comment]
5001 -server port
3000 - client
cookie is cleaning 
![Screenshot 2020-08-07 at 17 29 07](https://user-images.githubusercontent.com/28841600/89656070-b7b4cd00-d8d3-11ea-8f5b-9a3fa6ae7048.png)

**Comment by billypon** [comment]
@jenkasia i have the same problem, have you solved it?
