### ISSUE TITLE
Have problem with register router

### ISSUE THREAD

**Issue by jenkasia** [fastify/help#234]
I get token, with fastify.googleOAuth2.getAccessTokenFromAuthorizationCodeFlow(req), but when I send request to protected route, like this: 
```
export async function router(fastify: FastifyInstance, opts, next): void {
  fastify.get(
    '/',
    {
      preValidation: [fastify.authenticate],
    },
    async (request, reply) => {
      reply.send('pong');
    }
  );
  next();
}
```
i get this response: {
    "statusCode": 401,
    "error": "Unauthorized",
    "message": "Authorization token is invalid: jwt malformed"
}

How I can fix this that my token will be usable for protected route?

**Comment by mcollina** [comment]
where are you parsing your jwt token?

**Comment by jenkasia** [comment]
> where are you parsing your jwt token?

Maybe nowhere, I can not find it the info in the documentation, can you help me?

**Comment by mcollina** [comment]
It is impossible to help without seeing your code really :(

**Comment by jenkasia** [comment]
> It is impossible to help without seeing your code really :(

```
export function router(fastify: FastifyInstance, opts, next): void {  
fastify.get('/auth/google/callback', {}, async function (req, res) {
    const token = await fastify.googleOAuth2.getAccessTokenFromAuthorizationCodeFlow(req);
    res.send({ token: token.access_token });
  });

  next();
}

```

**Comment by mcollina** [comment]
To the best of my knowledge, that has nothing to do with jwt. also, check how `authenticate` is defined.

**Comment by jenkasia** [comment]
> To the best of my knowledge, that has nothing to do with jwt. also, check how `authenticate` is defined.
Ok, here  i working with jwt and it return me token on client, with this token i can go to protected routes, but if i use oauth2, i get token too, but it token does not help me to go to protected routes
```
export default fp((fastify, opts, next) => {
  fastify.register(fastifyJWT, {
    secret: process.env.JWT_SECRET,
  });
  fastify.decorate('authenticate', async (req, res) => {
    try {
      await req.jwtVerify();
    } catch (err) {
      res.send(err);
    }
  });
  next();
});
```
PS. Sorry for my English 🙈

**Comment by mcollina** [comment]
In your authenticate function you need to check if there is a JWT token or a oauth2 access token.

**Comment by jenkasia** [comment]
> oauth2

Ok, how I can check is oauth2 token exist?

> In your authenticate function you need to check if there is a JWT token or a oauth2 access token.
