### ISSUE TITLE
Why is my onRequest handler throwing?

### ISSUE THREAD

**Issue by gc** [fastify/help#237]
```ts
import { onRequestHookHandler } from 'fastify';

import { decrypt } from '../util';
import { clientSecret } from '../config';

export const authenticate: onRequestHookHandler = (request, reply) => {
	const token = request.headers.authentication;

	if (!token || Array.isArray(token)) {
		return reply.unauthorized('No authorization token.');
	}

	try {
		const result = decrypt(token, clientSecret);
		request.auth = result;
	} catch (_) {
		return reply.badRequest();
	}
};
```
This is a `onRequest` handler.

I expect that fastify should return a response like:
```ts
{
"statusCode": 401,
"error": "Unauthorized",
"message": "No authorization token."
}
```

as im using fastify-sensibles `reply.unauthorized`, instead its an internal server error, and `No authorization token` is returned as an error. In `setErrorHandler` if i console.log the error, the exact error is `No authorization token` string.

Not sure what im doing wrong.

**Comment by mcollina** [comment]
You need to use an async function and throw.

**Comment by gc** [comment]
So should I use Async every time for all onRequest hooks, or only because I want to throw? 

Side note: Its really confusing to me... Should I return nothing, return the reply, return the error, use done(), throw it, use Async or not, it feels confusing to me, from what I see, what im supposed to do isn't often unclear (all around fastify , not just hooks) for me.

**Comment by gc** [comment]
I'm doing this now, and it hasn't changed or fixed the result:

```ts
import { onRequestHookHandler } from 'fastify';

import { decrypt } from '../util';
import { clientSecret } from '../config';

export const authenticate: onRequestHookHandler = async (request, reply) => {
	const token = request.headers.authentication;

	if (!token || Array.isArray(token)) {
		throw reply.unauthorized('No authorization token.');
	}

	try {
		const result = decrypt(token, clientSecret);
		request.auth = result;
	} catch (_) {
		throw reply.badRequest();
	}
};
```

**Comment by StarpTech** [comment]
I can't reproduce it.

```js
const fastify = require('../fastify')()
fastify.register(require('fastify-sensible'))
fastify
  .addHook('onRequest', async function (request, reply) {
    console.log('onRequest')
    throw fastify.httpErrors.notFound()
  })
fastify.get('/', opts, function (req, reply) {
  reply.send({ hello: 'world' })
})
fastify.listen(3000, function (err) {
  if (err) {
    throw err
  }
  console.log(`server listening on ${fastify.server.address().port}`)
})
```

Result:

```
{"statusCode":404,"error":"Not Found","message":"Not Found"}
```

**Comment by gc** [comment]
Okay... I found the cause:
```ts
server.setErrorHandler((error, request, reply) => {
	console.error(error.message);
	reply.internalServerError(`A very bad error just occurred! ${error.message}`);
});
```

Commenting this out fixes it. I thought this would only run in internal-server-error cases, and not for a 401. I added this code because, if any error is thrown (e.g. saving data to a db throws) in my routes i want to return that above, but ofcourse if im throwing `reply.unauthorized` id want to return that instead. any ideas how i can achieve that?

**Comment by StarpTech** [comment]
Please post your full code next time.

**Comment by gc** [comment]
hey i had a question at the end of my comment 😄 should i make a new issue?

**Comment by StarpTech** [comment]
As stated in the [`docs`](https://github.com/fastify/fastify/blob/5f8111c1cc1c80b0650184b0591efc94bd219e53/docs/Errors.md#catching-uncaught-errors-in-fastify). Any thrown error is delegated to the default or custom error handler.

**Comment by gc** [comment]
Yes I saw that, but my question isn't answered by that, I don't want to handle errors for cases like this because it's not an unexpected error and I'm handling it already by returning 401

**Comment by StarpTech** [comment]
Please open a new issue and describe exactly what you are trying to implement.
