### ISSUE TITLE
 fluent-schema - Generate a schema from JSON file

### ISSUE THREAD

**Issue by xyz-mtl** [fastify/help#238]
I'm looking for a generation of schema from JSON data.
Is it possible to use the module fluent-schema ?
I would like to validate a POST request based on JSON file.

Thank you

**Comment by Eomm** [comment]
There is not this feature: from a JSON to a JSONSchema like [this](https://www.liquid-technologies.com/online-json-to-schema-converter)
I saw that all the modules that offer it, are quite old (like [generate-schema](https://www.npmjs.com/package/generate-schema))

The output could be helpful at the beginning, but you may refactor it manually for special cases or enums for example.
