### ISSUE TITLE
fastify-multipart: wait for async operation to finish before calling `done`

### ISSUE THREAD

**Issue by mjgreen145** [fastify/help#239]
We are trying to use fastify-multipart to upload images to our server, and send them straight on to 3rd-party storage. This is an example:

```ts
async uploadImage(request: FastifyRequest<UploadImageRequest>): Promise<UploadResponse[]> {
  return new Promise(async (resolve, reject) => {
    const uploadResponses: UploadResponse[] = [];

    const handler = (field: string, file: ReadableStream) => {
      const uploadStream = this.imageService.uploader.upload_stream(
        (error, result) => {
          if (error || !result) {
            logger.error('Error uploading image to storage', error);
            reject(error);
            return;
          }
          uploadResponses.push(result);
        }
      );

      file.pipe(uploadStream);
    };

    const done = (error: Error | undefined) => {
      if (error) {
        logger.error('Error handling image file', error);
        reject(error);
        return;
      }
      resolve(uploadResponses);
    };

    request.multipart(handler, done);
  });
}
```

This code takes a request, and for each file (there may be multiple), uploads it to storage via another stream (`uploadStream` in this example). This stream has some asynchronous actions under the hood, as data will be going over a network.

When the upload stream completes, it calls back with the result of the upload, which we collect in `uploadResponses` - this is what we eventually want to resolve with, and return to the client.

However, `multipart` calls the `done` callback as soon as the input read stream has finished being consumed, which is before the upload stream has finished.

Is there a way to have `multipart` wait for the `hander`/upload stream to finish before calling the `done` callback?

#### Context

* *node version*: 12
* *fastify version*: >=3
* *fastify-multipart version*: >=2.0.3

**Comment by mcollina** [comment]
you need to use https://nodejs.org/api/stream.html#stream_stream_pipeline_source_transforms_destination_callback instead of .pipe and resolve/reject when the calback is done.

**Comment by mjgreen145** [comment]
Thanks @mcollina.

Sadly this doesn't quite do what we need - perhaps I can explain myself better with another example (similar to before but with some debug logs):

```ts
private async uploadImage(request: FastifyRequest<UploadImageRequest>): Promise<UploadResponse[]> {
    return new Promise(async (resolve, reject) => {
      const uploadResponses: UploadResponse[] = [];
      let files = 0;

      const handler = (field: string, file: ReadableStream) => {
        files++
        console.log('got file', files);
        if (field !== 'image') {
          reject(invalidFormErrorMessage);
          return;
        }
        const writeStream = this.imageService.uploader.upload_stream(
          {
            folder: request.params.apiKey,
          },
          (error, result) => {
            if (error || !result) {
              logger.error('Error uploading image to storage', error);
              reject(error);
              return;
            }
            uploadResponses.push(result);
            console.log('got response', uploadResponses.length);
          }
        );

        file.pipe(writeStream);
      };

      const next = (error: Error | undefined) => {
        if (error) {
          logger.error('Error handling image file', error);
          reject(error);
          return;
        }
        resolve(uploadResponses);
      };

      request.multipart(handler, next);
    });
```

Whether we use `pipe` and use the callback from our `uploadStream`, or `pipeline` and the callback passed to that, those callbacks are _per file_, not on the whole request. If I upload 5 files at once, we get an output which looks like this:

```
got file 1
got file 2
got file 3
got response 1
got response 2
got file 4
got file 5                // multipart `done` callback fired after this
got response 3
got response 4
got response 5
```

As soon as the main request read stream as been consumed by `multipart`, the `done` callback is called, even though we've only had chance to receive 2 out of 5 responses from uploading individual files.

I don't believe there's a way of knowing up-front how many files are in the request, as the data is streamed, so we can't wait for a certain number of upload responses before resolving our main Promise.

Does that make more sense?

**Comment by mjgreen145** [comment]
I think we have a solution here. Essentially:

* Keep a count of the number of files as `handler` is called for each one
* Keep a count of the number of upload responses, as the callback is called
* Keep a boolean of whether the request stream has ended - which we flip from `false` to `true` in the `multipart` `done` callback.
* Only if the request stream has been read, _and_ the number of responses matches the number of files, then resolve the Promise.

This works, and looks somewhat similar to the source code of `fastify-multipart` itself, but it would be interesting to know if there's a better/cleaner way

**Comment by mcollina** [comment]
Yes, exactly. We are working on a better API in https://github.com/fastify/fastify-multipart/pull/140
