### ISSUE TITLE
Validation on PATCH reqeuests

### ISSUE THREAD

**Issue by tomclark** [fastify/help#24]
#### What are you trying to achieve or the steps to reproduce?

Apologies if this is just me being dumb, or there's a more correct way to approach this problem, but when I send a PATCH request to an existing object, I can't figure out how to use the schema validation to prevent consumers of my API adding invalid or nonsense properties. 

For example, I have a schema for a blog, which has well defined properties such as username. When I issue a PATCH request, I'm able to send additional propertied that will then be saved against the object in the database. Sending a PATCH request with { "randomProperty": "some nonsense" } as the request's body will result in that property being created on the database record - I'd like to prevent that. 

Furthermore - and perhaps more importantly - is that the API consumer could conceivably spell a valid property name wrong and instead of the object being patched correctly, a new property would be added - { "userName": "tom" } rather than { "username": "tom" }.

I've tried adding removeAdditional:true and additionalProerties:false to the schema but it doesn't seem to make any difference. 

Can I even do this using the schema validation?

#### What was the result you received?

API consumers are able to add extra, unwanted properties to objects in my database,

#### What did you expect?

I'd like the schema validation (or some mechanism) to prevent the user from adding spurious properties to an object so that the properties for all objects of a particular type are consistent.

#### Context

* *node version*: 8
* *fastify version*: 1.9.0
* *os*: Mac

**Comment by mcollina** [comment]
Can you please add a full example?
Il giorno ven 7 set 2018 alle 21:59 Tom Clark <notifications@github.com> ha
scritto:

**Comment by tomclark** [comment]
Sure, and thanks for the super quick reply. My schema looks a bit like this (some fields removed to protect the innocent and simplify things, but I hope it demonstrates the principle):

```
fastify.addSchema({
    $id: 'blog',
    type: 'object',
    properties: {
      _id: { type: 'string' },
      title: { type: 'string' },
      text: { type: 'string' },
      description: { type: 'string' },
      tags: {
        type: 'array',
        items: 'tags#', // Another schema defined elsewhere
      username: { type: 'string' }
    },
    removeAdditonal: true, // added in an attempt to make this work
    additionalProperties: false, // added in an attempt to make this work
    required: [
      'title',
      'description',
      'username',
    ]
  })
```
The schema is wrapped in a fastify-plugin and AutoLoaded when the server starts.

The route looks like this:

```
fastify.route({
    method: 'PATCH',
    url: '/blog/:id',
    schema: {
      querystring: {
        id: { type: 'string' }
      },
      body: {
        type: 'object',
        properties: {
          title: { type: 'string' },
          text: { type: 'string' },
          description: { type: 'string' }
        }
      }
    },
    response: {
      204: 'blog#',
      400: 'error#',
      500: 'error#'
    },
    handler: async (req, res) => {
      await col.findOneAndUpdate({ _id: ObjectId(req.params.id) }, { $set: req.body })
        .then(result => {
          res.code(204).send(result.value)
        })
        .catch(err => {
          res.code(500).send(err)
        })
    }
  })
```

Note I don't want people to be able to edit tags at this point, just the title, text, and description.

I then use Postman to execute a PATCH request to the URL:

http://localhost:3000/blog/5b8e9ff46546d16873882f0a (where that's the object ID)

with the body:

```
{
  "testProp": "blah"
}
```

What I'd expect to happen is for the user to get some kind of error message (preferably a 400 but I'm not particularly fussed as long as it doesn't go through), but instead, the request goes through and I end up with a record in my database that has the existing fields of title, text, description, and tags - and a new property called testProp with the value blah. I can keep doing that to add more and more fields.

Again, apologies if I'm obviously doing something wrong here and I hope my example makes sense. I'm relatively new to Fastify and certainly to JSON schemas. What I have noticed is that if I add testProp in a POST, it is ignored, so I assumed the behaviour would be the same with PATCH.

Should I instead be removing unknown/invalid properties from req.body in a beforeHandler or the handler itself, or otherwise sanitising the request's body?

Thanks again.

**Comment by tomclark** [comment]
Oh man! That has sorted it instantly, obviously (well, clearly not obviously to me, but now I understand the format of the schema much better).

Thanks so much for spotting that and helping me out. I really do appreciate it. I'm refactoring this app from Mongoose to use the Node native driver because I was desperate to use all the schemary goodness and learn about that too, so this has made my evening. 👍

Please have an internet beer on me. Greetings from Scotland.

**Comment by nwoltman** [comment]
You're welcome! Glad to help 😄

**Comment by oncletom** [comment]
Thank you!

It was not obvious to me that the body should also have a type, and properties.

**Comment by PierBover** [comment]
@nwoltman just to confirm, `additionalProperties: false` has to be added on each route even though the the AJV constructor already has `removeAdditional: true`. Correct?

@mcollina would you accept a PR to clarify this in the docs?

**Comment by nwoltman** [comment]
@PierBover It's been over two years since I wrote that response, so I don't really remember, but that sounds correct.
