### ISSUE TITLE
middle plug

### ISSUE THREAD

**Issue by borodadada** [fastify/help#240]
Hello, in my project middlewares not work. Version fastify 2 all fine.
I try
```
//add middle
.....
fastify.register(require('middie'))
fastify.register( require('fastify-favicon'), { path: path.join(__dirname, 'public') } );
fastify.register( require('fastify-static'), { root: path.join(__dirname, 'dist'), prefix: '/dist/', decorateReply: false } )
fastify.register( require('fastify-static'), { root: path.join(__dirname, 'public'), prefix: '/public/', decorateReply: false } )
....
```
after
```
...
    // dev middleware
    const clientCompiler = webpack(clientConfig)
    const devMiddleware = require('webpack-dev-middleware')(clientCompiler, {
        publicPath: clientConfig.output.publicPath,
        noInfo: true
    })

    fastify.use(devMiddleware);
....
```
error
node_modules\fastify\fastify.js:397
    throw new FST_ERR_MISSING_MIDDLEWARE()
    ^
FastifyError [Error]: You must register a plugin for handling middlewares, visit fastify.io/docs/latest/Middleware/ for more info.

whats problem?

**Comment by jsumners** [comment]
https://github.com/fastify/fastify/blob/e4d8773421a00ff16290b8f83d7270e931c40513/docs/Migration-Guide-V3.md#changed-middleware-support-2014

**Comment by borodadada** [comment]
problem in without await ?

**Comment by TeckFreak** [comment]
@borodadada
Sorry, I'm late for this. But you or whoever faces this issue in future, you can try this:

```
fastify.register(require('middie')).then(() => {
        fastify.use(require('cors'));
        fastify.use(require('helmet'));

        console.log("Middleware Added.")
});
```
