### ISSUE TITLE
Catch only unintended errors?

### ISSUE THREAD

**Issue by gc** [fastify/help#241]
Heres some example/mock code for a route, to demonstrate my question. Also please consider the case that this is in a `onRequest` hook.
```ts
async handler(request, reply) {
   const isAuthorized = checkAuth(request);
   if (!isAuthorized) {
      throw reply.unauthorized('You are not authorized!');
   }

   await database.saveValue(request.body.data);
   reply.send({ success: true });
}
```

My Goal:
If `database.saveValue` throws, I want to handle it in `setErrorHandler` or somewhere else, BUT I dont care about `throw reply.unauthorized` in my error handler, because its already being handled because throwing that tells fastify to return something like `{statusCode: 401, ...}`. However, if the database.saveValue fails and throws an error, thats a really bad thing I want to catch and handle.

I know I could theoretically `.catch` or `try{}catch{}` it here, but i want to handle it in a global/centralized way. 

My ideal goal is to return a internal server error for any thrown error (NOT for the reply.unauthorized, because theres nothing unexpected happening there), and just log the error but not tell the requester what the error was.

`setErrorHandler` doesnt work for me because it catches EVERY error, including that `reply.unauthorized`, and i dont know how or if i can modify it to ignore ones like th ose.

**Comment by StarpTech** [comment]
In https://github.com/fastify/fastify-sensible you can disable the error handler and use your own. Does it help?

**Comment by gc** [comment]
I already have the fastify-sensible error handler disabled. and `setErrorHandler` doesnt work for me because it catches EVERY error, including that reply.unauthorized, and i dont know how or if i can modify it to ignore ones like those

**Comment by StarpTech** [comment]
> If database.saveValue throws, I want to handle it in setErrorHandler or somewhere else, BUT I dont care about throw reply.unauthorized in my error handler, because its already being handled because throwing that tells fastify to return something like {statusCode: 401, ...}.

This is confusing. As soon as you throw you saying: "Stop! This should not continue and we delegate this case to our error handler."

> I know I could theoretically .catch or try{}catch{} it here, but i want to handle it in a global/centralized way.

This is the correct way! You describe a local problem nothing which can be described as a pattern.

**Comment by StarpTech** [comment]
But anyway you have still the flexibility to differentiate between HTTP errors and e.g driver errors. You can check this in the error handler.

```js
err instanceof req.httpErrors.HttpError 
```

**Comment by Eomm** [comment]
or you could just check the `reply.code ===undefined || reply.code >= 500` in the error handler to manage only the error that matter for you
