### ISSUE TITLE
Question: npm assets

### ISSUE THREAD

**Issue by zekth** [fastify/help#243]
using `npm i fastify` it downloads the packages fitting the specs in `.npmrc` and `.npmignore`:

```
.editorconfig
.gitattributes
.git
.DS_Store
.gitignore
.github
.nyc_output
coverage/
tools/
azure-pipelines-npm-template.yml // Seem those can be deleted
azure-pipelines-yarn-template.yml // Seem those can be deleted
azure-pipelines.yml // Seem those can be deleted
CODE_OF_CONDUCT.md
CONTRIBUTING.md
.dependabot
```

Question is, is there a real benefit of shipping tests with the npm package? If so why not consider a `fastify@light` package?
I'm asking this because of some security scanners i was forced to introduce step like so in the build process of one docker image (and i guess i'm not the only one): 
```
rm -rf ./node_modules/fastify/test/https/fastify.key
```

Reference:
- Security scanne: https://www.twistlock.com/use-cases/docker-security-platform/

**Comment by jsumners** [comment]
Yes, please remove the azure files. We no longer use that.

**Comment by mcollina** [comment]
> Question is, is there a real benefit of shipping tests with the npm package? 

Releases on github are mutable while releases on npm are not. By including the tests in the npm release, anybody could eventually restart development of this module from there.

> I'm asking this because of some security scanners i was forced to introduce step like so in the build process of one docker image

That's the first time I hear this. Why is it complaining about that?

**Comment by zekth** [comment]
extract of the report:
```json
	"compliances": [
				{
					"title": "Private keys stored in image",
					"severity": "high",
					"cause": "Found: /server/node_modules/fastify/test/https/fastify.key"
				}
			],
```

**Comment by mcollina** [comment]
Something we can do about that is to automatically generating a key if it's missing before running the tests.

**Comment by zekth** [comment]
I have no strong opinion on this, just sharing previous issue.
