### ISSUE TITLE
Is there way to use multiple handler with same path?

### ISSUE THREAD

**Issue by lamualfa** [fastify/help#245]
## Problem

I want to use [Sapper](https://github.com/sveltejs/sapper) with [Fastify Static](https://github.com/fastify/fastify-static). I have to register new route and pass `request` & `reply` argument into Sapper middleware function. And the following code I wrote to do this:

#### [Edited]
```js
// Register Sapper routes
const middleware = sapper.middleware()
fastify.all('/*', async (req, reply) => {
  await new Promise((resolve, reject) =>
    middleware(req.raw, reply.raw, (error) => {
      if (error) return reject(error)
      
      // Continue to the next route or plugin
      // In `express` we have `next` function
      return resolve()
    })
  )
})

// Register public folder
fastify.register(require('fastify-static'), {
  root: path.resolve('public')
})
```

After running the above code I get the following error:

```bash
AssertionError [ERR_ASSERTION]: Method 'GET' already declared for route '/*'
```
## Question

Is there way to use multiple handler in same path? or is there another way to integrate Fastify with Sapper **without using `fastify-middleware` or other Express middleware?** I tried to use the Fastify plugin completely.

## Reference

- https://github.com/sveltejs/sapper/issues/1018

**Comment by Eomm** [comment]
I would try to setup the [`wildcard`](https://github.com/fastify/fastify-static#wildcard) option if you have some static file to serve.
I'm assuming that the public files must be served by `fastify-static` and no one else.

The two handler problem should be clarified: who should serve `/url`? the middleware or fastify-static? is this a dynamic behaviour?

--- 

As test this should works:

```
fastify.all('/*', async (req, reply) => {
  middleware(req.raw, reply.raw, (error) => {
    if (error) {
      reply.send(error)
      return
    }
    // does the middleware consume the reply?
    // if yes, we have done
    // if no: reply.send('something')
  })
})
```

**Comment by lamualfa** [comment]
I want  if the middleware does not find a page that matches the url that was accessed (e.g `/manifest.json`), Fastify will forward the requested request to the `fastify-static` plugin. Then `fastify-static` will try to find if there is a file in the public folder that matches the url that was accessed.

### Example:

#### Case 1:

1. User accesses `/contact`
2. Sapper middleware will check if there is a svelte page (`contact.svelte`) in the routes folder
3. If there is, then the middleware will respond to the Svelte page.

#### Case 2:

1. User accesses `manifest.json`
2. Sapper middleware will check if there is a Svelte page in the routes folder
3. Because Sapper cannot find a suitable page, it calls the `done` function.
4. I want Fastify to pass the request to the next plugin that is `fastify-static` when the `done` function is called
5. `fastify-static` will check if there is a file named `manifest.json`
6. If exist, response the file. if there is, then the response file. otherwise, return the `404` or continue on the next route.

##### Example:

```js
// Register Sapper routes
const middleware = sapper.middleware()
fastify.all('/*', async (req, reply) => {
  await new Promise((resolve, reject) =>
    middleware(req.raw, reply.raw, (error) => {
      if (error) return reject(error)

      // Continue to the next route or plugin
      // In `express` we have `next` function
      return resolve()
    })
  )
})

// Register public folder
fastify.register(require('fastify-static'), {
  root: path.resolve('public')
})
```

**Comment by Eomm** [comment]
I would try `wildcard: false` or something like that:

```
  fastify.register(fastifyStatic, {
    root: path.join(__dirname, '../static'),
    serve: false
  })

  fastify.all('/*', async (req, reply) => {
  await new Promise((resolve, reject) =>
    middleware(req.raw, reply.raw, (error) => {
      if (error) return reject(error)

      // Continue to the next route or plugin
      // In `express` we have `next` function
      return serveHtml(req, reply)
    })
  )
})
  fastify.setNotFoundHandler(serveHtml)

  function serveHtml (request, reply) {
    // use the request path
    reply.sendFile('index.html')
  }
```
