### ISSUE TITLE
fastify-websocket: getting URL params

### ISSUE THREAD

**Issue by zmeyc** [fastify/help#248]
Using fastify-websocket I'm trying to get parameter from URL of form "/path/:ticket":

I can access the URL:
```
 fastify.get('/path/:ticket', { websocket: true }, function wsHandler(
    connection,
    req
  ) {
    console.log(req.url)
```
url is `/path/525327589768`

But is it possible to fetch :ticket itself? In non-websocket handler it would be `request.params.ticket`, but in wsHandler `req` is of type IncomingMessage and doesn't have params.

There's a full form which allows using both handler and wsHandler, but how to pass params to wsHandler? By attaching them to `request.raw`?

```
fastify.route({
  method: 'GET',
  url: '/hello',
  handler: (req, reply) => {
    req.raw.params = req.params
  },
  wsHandler: (conn, req) => {
    const params = req.params
  }
})

**Comment by 2ico** [comment]
Is this still working?
