### ISSUE TITLE
Plugin namespacing and path prefix

### ISSUE THREAD

**Issue by zmeyc** [fastify/help#249]
I registered a plugin under a prefix:
```
fastify.register(websocketsPlugin, { prefix: '/ws' })
```

And wanted to decorate fastify with helper method which needs to be accessible globally:
```
const websocketsPlugin = async (fastify, _options) => {
  fastify.decorate('shutdownAllWebsocketsGracefully', (): void => { ... })
  fastify.post('/some-routes', ...)
```

As expected, helper method `shutdownAllWebsocketsGracefully` is inaccessible outside of plugin context because of plugin namespacing.

If I wrap the plugin into `fastify-plugin`:
```
import fp from 'fastify-plugin'
export default fp(websocketsPlugin)
```
routes are no longer registered under `/ws` prefix.

What is the recommended way of solving this issue? Should I create two separate plugins, one with prefix for routes and another one wrapped into fastify-plugin with global functions?

**Comment by mcollina** [comment]
That's the best practice, yes. We should probably document this better in the docs. Would you like to send a PR?

**Comment by zmeyc** [comment]
@mcollina Thanks for confirming! Sure, I'll think where to add this.

**Comment by jsumners** [comment]
The simple solution is:

```js
fastify.register(async f => f.register(plugin, { prefix: '/foo' }))
```

**Comment by zmeyc** [comment]
Not stale, I'll get back to it soon.
