### ISSUE TITLE
body validation depending on the params

### ISSUE THREAD

**Issue by PavelPolyakov** [fastify/help#25]
#### What are you trying to achieve or the steps to reproduce?

Imagine I have the next route:
`POST /cc/:country` where I can post `city` in the payload.

I want to declare the json-schema validation for this route, which depends on the `param` country.
So for the country `UA`, the city is enum from `Kharkov` and `Kiev`. And for the country `DE` the city is enum from `Berlin` and `Hamburg`.

Is it possible to do it in some reasonable way? Without declaring two different routes. I mean staying within the boundaries of the json-schema validation and route declaration NOT beforeHandlers.

This is what I've tried.

```js
fastify.post('/cc/:country', {
    schema: {
      params: {
        type: 'object',
        properties: {
          country: { type: 'string' },
        },
        required: ['country'],
      },
      body: {
        type: 'object',
        properties: {
          if: {
            properties: {
              country: { type: 'string', const: ['UA'] },
            },
          },
          then: {
            properties: {
              city: { type: 'string', enum: ['Kharkov', 'Kiev'] },
            },
          },
          else: {
            properties: {
              city: { type: 'string', enum: ['Berlin', 'Hamburg'] },
            },
          },
        },
      },
    },
  }, (request, reply) => reply.send({ params: request.params, body: request.body }));
```

#### What was the result you received?
validation for the body property `city` is just missing

#### What did you expect?
that city validation depends on the param `country`

#### Context
* *fastify version*: >=1.9.0

Any suggestions are welcome!

Regards,

**Comment by mcollina** [comment]
Have you tried debugging the JSON Schema with simple AJV?

**Comment by PavelPolyakov** [comment]
no, but I've discovered that in fastify the validation is called per group

https://github.com/fastify/fastify/blob/master/lib/validation.js#L78

so I don't think that my assumption can work, since `body` doesn't know about the `params`, does it?

also I didn't find any way to dynamically compose the schema based on the request.

**Comment by mcollina** [comment]
No it won't.

**Comment by PavelPolyakov** [comment]
any general suggestion how you'd handle such case?

**Comment by mcollina** [comment]
I'd write it in code in my route. I typically keep the validation just about the format of the data that is being sent, and not about its semantics. I validate the semantics in code.

**Comment by PavelPolyakov** [comment]
Thanks
