### ISSUE TITLE
when using onResponse: cannot handle response properly

### ISSUE THREAD

**Issue by facugon** [fastify/help#250]
#### You have already researched for similiar issues?

Yes

#### What are you trying to achieve or the steps to reproduce?

I'm using fastify as request proxy to avoid having to rewrite the original request information (headers, body, etc).
Think of my use case as a simple gateway for internal use.

The problem is when using **onResponse** to handle the proxy request, the original response object is being used and modified, but I don't need the original request to be modified since I'm handling it by my self.
When getting the proxy response I need to do something else with it.

For example if the proxy request failed, it tries to immediately give a response.
The Proxy also modifies the headers with proxy Api response.

```js
// I'm parsing the response to obtain the ID, and then do something with it
    const redirectRequest = (req) => {                                                       
      return new Promise( (resolve, reject) => {                                             
        proxy(req, new FakeResponse(), req.url, {                                            
          base: app.config.api_url,                                                   
          /**
           * @param {IncomingMessage} origReq original request                               
           * @param {FakeResponse} fakeRest mocked response. avoid overriding original headers
           * @param {IncomingMessage} apiRes supervisor api response                         
           */
          onResponse: (origReq, fakeRes, apiRes) => {                                        
            let str = ''                                                                     
            apiRes.on('data', d => { if (d) { str += d } })                                  
            apiRes.on('end', () =>  {                                                        
              try { 
                apiRes.rawBody = str
                apiRes.body = JSON.parse(str)                                                
                resolve(apiRes)
              } catch (err) {                                                                
                console.error(err)
                reject(err)                                                                  
              }
            })                                                                               
            //res.status(200).json({ })                                                      
          }
        })
      })
    }

```

```js
// somewhere else
// ...
          let response = await redirectRequest(req)                                          
    
          const model = response.body                                                          

```

#### What was the result you received?

This works OK.
I managed to avoid Headers overriding using a FakeResponse Class.
But when the proxy request failed it blows up.  I can also handle it using the fake response object.

#### What did you expect?

I'm sure I'm doing something that fastify was not expected to achieve.

Should I stop using fastify for this use case?

Thanks

#### Context

* *node version*: 14
* *fastify version*: fast-proxy 1.7.0
* *os*: Linux
* *any other relevant information*:

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by mcollina** [comment]
Use fastify-http-proxy, not fast-proxy.

**Comment by facugon** [comment]
Thanks for answer!
