### ISSUE TITLE
caching with a file-system based cache

### ISSUE THREAD

**Issue by punkish** [fastify/help#252]
#### You have already researched for similiar issues?

From the docs, the recommended way seems to be to use `fastify-caching` with `abstract-cache` and one of its backend adapters. From what I can find, the only adapters available are `ab-redis` and `ab-mongodb`. 

#### What are you trying to achieve or the steps to reproduce?

I want to use neither of those (at least at this time) and instead use a file-system based cache where each request/response is stored in a separate file (kinda like what [persistent-cache](https://github.com/LionC/persistent-cache) does.

Q1. Is there an `abstract-cache` file-system adapter out there already that I may have missed in my searches?

Q2. What are the disadvantages, if any, if I decided to invest in something like such as `persistent-cache` or [keyv](https://github.com/lukechilds/keyv) + [keyv-file](https://github.com/zaaack/keyv-file) or [cacache](https://github.com/npm/cacache)?

#### Context

I am coming from the `hapijs` world which, while I enjoyed it very much, I also found to be highly opinionated. I seemed to be doing things the `hapi` way rather than the `javascript` way. I am experimenting with `fastify` and am finding it to be much simpler and easier to develop with. But I want to make sure that I have the flexibility to work with non-fastify-blessed plugins and modules without running into big problems.

**Comment by mcollina** [comment]
> Q1. Is there an abstract-cache file-system adapter out there already that I may have missed in my searches?

I never researched this unfortunately.

> Q2. What are the disadvantages, if any, if I decided to invest in something like such as persistent-cache or keyv + keyv-file or cacache?

The main disadvantage is that two instances of the server could have their caches out of sync. By using a shared database you make sure they are in sync.

**Comment by jsumners** [comment]
I haven't written such an adapter, nor have I been informed of any existing. It's true that `fastify-caching` is essentially the Fastify version of Hapi's caching mechanism (`catbox`). I might not have done a good job in that endeavor 🤷‍♂️.

As Matteo says, you will complicate caching amongst multiple server instances if you start caching locally (same thing if you rely on the in-memory default cache).
