### ISSUE TITLE
Bitcoin investment website pretending to be Fastify

### ISSUE THREAD

**Issue by qt-sergal** [fastify/help#253]
Hi!
This isn't technically a bug/issue with Fastify itself, but I think it would make sense to file an issue anyways.
I have been recently searching for the Fastify documentation on Google and to my own surprise, found a financial website pretending to be Fastify, using the exact same logo(and name), while promising great returns on bitcoin investments.
Obviously, for someone who used Fastify before, this wouldn't be a problem, but for those who only just heard of it, it may be an issue.
Perhaps, it would make sense to clarify it somewhere and warn people?
Website in question - https://fastify.cc/

**Comment by StarpTech** [comment]
@qt-sergal thanks for reporting.

**Comment by mcollina** [comment]
I don't know where to warn people without creating a backlink back to the spammer from the official website.
If you have an idea, would you mind to help and open a PR to the website?
