### ISSUE TITLE
File upload ignores bodyLimit

### ISSUE THREAD

**Issue by friksa** [fastify/help#254]
When I upload a file just over 5M, it fails with 
413 (Payload Too Large)

This is not a multi-part form post.  Instead it is a Http5 FileReader POST.

```js
  const tls = {
    cert: fs.readFileSync(config.https.tls.cert),
    key: fs.readFileSync(config.https.tls.key),
  };

  const fastifyAdapter = new FastifyAdapter({
    https: tls,
    bodyLimit: 10000000,
  });

  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    fastifyAdapter,
  );
  app.setGlobalPrefix('/api');
  app.enableCors();
```

#### What was the result you received?
413 (Payload Too Large)

#### What did you expect?
Controller to get access to the uploaded binary data.

#### Context

* *node version*: 10
* *fastify version*: 3.2.1
* *os*: MacOS 10.15.5
"@nestjs/platform-fastify": "^7.4.2",
    "@nestjs/common": "^7.4.2",
    "@nestjs/core": "^7.4.2",

Thanks!

**Comment by friksa** [comment]
After some more digging, it seems that bodyLimit is not completely ignored...

When I do _not_ set the bodyLimit, I am not able to upload a 1.1M file... 

When I set the bodyLimit to 10000000 (10M), I am able to upload the same 1.1M file, but a 5.7M file fails with 413: Payload Too Large. 

So it seems that there is something else also enforcing a maximum payload size?

**Comment by friksa** [comment]
Got it resolved... if I set the mime-type on the submit to 'application/octet-stream', then it honors the bodyLimit.

**Comment by Eomm** [comment]
Thanks to reporting, it will be useful to others 👍
