### ISSUE TITLE
Best practice for Server.push in HTTP2 with fastify?

### ISSUE THREAD

**Issue by eouia** [fastify/help#258]
#### What are you trying to achieve or the steps to reproduce?

I'm building a little SPA. HTTP2 and the fastify look so promising so I tried. But I lost my way in `Server Push HTTP2`.

I built an HTTP2 & Fastify server and it can serve usual service well. Now, I want to add `Server Push` for some assets(`JS`, `CSS`) with `/` to get more performance. Those files are scattered in several directories and used optionally, so using `fastify-auto-push` looks not proper. 
Those files will be cached and controlled by the service-worker of the browser.

```js
var assets = [ ... assetItems]

// example of asset Item
/*
{
  type: 'js',
  url: '/packages/core/assets/js/default.js',
  contentLength: 12345,
  lastModified: 'Mon, 31 Aug 2020 08:05:20 GMT',
  contentType: 'application/javascript',
  filePath: '/some/where/packages/core/assets/js/default.js'
}
*/


indexHandler (req, reply) {
  const stream = req.raw.stream
  for (var a of assets) {
    stream.pushStream(
      { ":path": a.url },
      (err, stream) => {
        if (err) throw err
        const header = {
          "content-length": a.contentLength,
          "last-modified": a.lastModified,
          "content-type": a.contentType
        }
        stream.respondWithFile(path.join(a.filePath))
        stream.on('close', ()=>{
          console.log('ending file', a.filePath)
        })
        stream.end()
      }
    )
  }
  reply.type('text/html').send(myIndexHTML) // this will serve main HTML of '/'
}
```
`indexHandler` will be used as a handler of `/` on fastify
My problem might be due to `for ... loop`. Because when callback of `pushStream()` is invoked, already the loop is finished so the last `a` will be used. That is not my want.
Who can lead me to the best practice of using `server push` in this case? I'm not sure even using `pushStream` is proper.

#### Context

* *node version*: 14.9
* *fastify version*: latest
* *os*: Mac

**Comment by Eomm** [comment]
I didn't play with it recently to suggest a best practice, but changing `var` to `const` should fix your issue regarding async execution

**Comment by eouia** [comment]
Do you mean `const stream = req.raw.stream`? I'll try it. thanks. After the test, I'll close this issue or continue discusstions.

**Comment by eouia** [comment]
I tried this way and it worked. To share my experience, leave here.

```js
async serveIndex (myIndexHTML, myAssets) {
  const sendFile = (stream, obj) => {
    return new Promise((resolve, reject) => {
      const headers = {}
      if (obj.contentLength) headers['content-length'] = obj.contentLength
      if (obj.lastModified) headers['last-modified'] = obj.lastModified
      if (obj.contentType) headers['content-type'] = obj.contentType
      if (obj.etag) headers.ETag = obj.etag
      stream.respond({ ':status': 200, 'content-type': obj.contentType })
      stream.end(fs.readFileSync(obj.filePath))
      stream.on('close', () => {
        resolve()
      })
    })
  }
  const pushFile = (stream, obj) => {
    return new Promise((resolve, reject) => {
      stream.pushStream({ ':path': obj.url }, (err, pushStream) => {
        if (err) {
          throw err
        }
        sendFile(pushStream, obj).then(() => {
          resolve()
        })
      })
    })
  }
  reply.type('text/html').send(myIndexHTML)
  const stream = req.raw.stream
    for (var a of myAssets) {
    await pushFile(stream, a)
  }
}
```

**Comment by Eomm** [comment]
> Do you mean `const stream = req.raw.stream`? I'll try it. thanks. After the test, I'll close this issue or continue discusstions.

I meant ` for (var a of assets) {` to ` for (const a of assets) {`

But the function closure works too
