### ISSUE TITLE
middie: middleware is not invoked unless fastify.route is defined

### ISSUE THREAD

**Issue by hqproto** [fastify/help#260]
#### What are you trying to achieve or the steps to reproduce?
I'd like to use an library with a middleware function with the typical (req, res) signature. 

```js
export default async function (fastify, opts) {
  await fastify.register(import('middie'));

  fastify.use((req, res, next) => {
    console.log('neither this nor the following function are invoked unless a fastify route is defined');
    next();
  });

  fastify.use(libraryFn);

  // above middleware functions are only invoked if a route is defined, e.g.:
  // fastify.get('/', (request, reply) => {
  //    return
  // })
}
```

#### What was the result you received?
Middleware function is not invoked unless a fastify route handler is defined.

#### What did you expect?
Middleware function would be invoked without a fastify route handler defined as documented in the official examples.

#### Context

* *node version*: 14.10.1
* *fastify version*: 3.4.1
* *os*: Windows
* *any other relevant information*:
I've fiddled with this and scoured the web for several hours. Any hints are greatly appreciated.

**Comment by mcollina** [comment]
The problem is likely within the docs, the code works as intended. Middlewares in fastify are run only if a route is executed. In your case, you are wrapping the middleware in a plugin which encapsulates all its routes - however there are none. Use fastify-plugin to break encapsulation and your middleware will be triggered.

**Comment by hqproto** [comment]
Matteo, thanks for taking the time out of your day to respond to my question.

In this case, I didn't really need express-style middleware or to break encapsulation. After sleeping on it, I realized this is all that was needed:

```js
  fastify.all('*', ({ raw: req }, { raw: res }) => {
    libraryFn(req, res)
  });
```

Thank you for all your effort toward building Fastify and the community around it -- both have been a pleasure to work!
