### ISSUE TITLE
understanding schema and validation

### ISSUE THREAD

**Issue by punkish** [fastify/help#262]
#### You have already researched for similar issues?

yes, but I can't find anything that helps

#### What are you trying to achieve or the steps to reproduce?

I am just trying babysteps with creating a schema and using it to validate they querystring. I created a brand new project and installed nothing by `fastify`. Then I used the example code from the fastify website's welcome page

```js
const fastify = require('fastify')({ logger: true })

fastify.route({
  method: 'GET',
  url: '/',
  schema: {
    // request needs to have a querystring with a `name` parameter
    querystring: {
      name: { type: 'string' }
    },
    // the response needs to be an object with an `hello` property of type 'string'
    response: {
      200: {
        type: 'object',
        properties: {
          hello: { type: 'string' }
        }
      }
    }
  },
  // this function is executed for every request before the handler is executed
  preHandler: async (request, reply) => {
    // E.g. check authentication
  },
  handler: async (request, reply) => {
    return { hello: 'world' }
  }
})

const start = async () => {
  try {
    await fastify.listen(3000)
    fastify.log.info(`server listening on ${fastify.server.address().port}`)
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()
```

#### What was the result you received?

When I go to `http://127.0.0.1:3000/` in my browser, it displays `{"hello":"world"}`.

#### What did you expect?

 I was expecting the application to carp telling me that a query param called `name` was required. In fact, I can type anything, for example, `http://127.0.0.1:3000/?foo=bar` and it still does not throw an error. If I change the response property from `{ hello: { type: 'string' } }` to `{ goodbye: { type: 'string' } }`, then I get an empty object `{}` as a response because I am sending back `{ hello: 'world' }`. But here too, I was expecting an error, and an empty object is not really an error. 

#### Context

* *node version*: 12.18.3
* *fastify version*: 3.4.1
* *os*: Mac

**Comment by punkish** [comment]
update: If I change my schema to the following then it works as I expected

```js
querystring: {
            type: 'object',
            properties: {
                'name': { type: 'string' }
            },
            required: ['name']
        }
```

Is the format I've been using wrong? If so, perhaps the fastify website welcome page code snippet needs to be updated.

**Comment by Eomm** [comment]
The property must be added to the `required` array to be mandatory, otherwise, it will be optional as you find out.

>  If so, perhaps the fastify website welcome page code snippet needs to be updated.

Any improvements are always appreciated, that page should reference this file https://github.com/fastify/fastify/blob/master/docs/Getting-Started.md

> What I really want is to either allow a query with no params, or if a param is provided, then it better match what is in the schema. Else send back an error.

You should use [`if/then/else`](https://json-schema.org/understanding-json-schema/reference/conditionals.html) in this case

**Comment by punkish** [comment]
thanks @Eomm, I will study the [if/then/else](https://json-schema.org/understanding-json-schema/reference/conditionals.html) docs. In the meantime, I have discovered that I can use the following, and it works. Is there a downside to this?

```js
preValidation: async (request, reply, done) => {
                
                let check = false
                const q = request.query
    
                if (Object.keys(q).length) {
                    for (let p in q) {
                        if (p in resource.schema) {
                            check = true
                            break
                        }
                    }
    
                    if (!check) {
                        reply.code(400).send(new Error('you submitted an invalid query'))
                    }
                }
    
                done()
            }
```

**Comment by Eomm** [comment]
> Is there a downside to this?

I would use code to validate complex data.
The downside is: more code, more bugs 😄 

The benefit of using a json schema is that:

- it is standard
- it can be evolved easier than custom code
- it provides API documentation (via swagger)

**Comment by Ethan-Arrowood** [comment]
Also, _speed_. It is important to not preoptimize so your preValidation hook may be a great solution for your server, but the schema validation built into Fastify is fast and can even improve the speed of your routes.

**Comment by mmarti** [comment]
I actually ran into this same issue a few days ago when I was taking a first stab at using Fastify's validation feature.  From the docs:

> All the validations can be a complete JSON Schema object (with a type property of 'object' and a 'properties' object containing parameters) or a simpler variation in which the type and properties attributes are forgone and the parameters are listed at the top level (see the example below).

It'd be great if it was called out that if you want to actually require a parameter you have to use the long form.  In other words, the example in the docs won't generally work how people expect it to, especially if the type is `string`, because all query string params can be coerved/parsed as a string.

I'd be fine creating a small PR that added a callout for that if it'd be merged?

**Comment by punkish** [comment]
@mmarti in addition to what you mention (needing to use the long form in order to specify a *required* param), my issue is that the example conveys (to me, at least) a misrepresentation. It seems to say that if you want to validate your query (or params or body), you can and should use the schema as shown. But, if I use the schema as shown, it validates nothing for me. As I mentioned, if I say my querystring can have (not *must have*) a param called **name**, I expect the validator to complain if I provide some other param, but it allows other params.

Ultimately, my requirement is really simple – either allow requesting a resource *without* any params, or if the user provides one or more params, they have to be specified in the schema. Seems like what is shown in the example is not enough for that. In fact, what is shown in the example seems to do nothing at all for queries though it does seem to monitor and affect the response.

**Comment by jsumners** [comment]
> I'd be fine creating a small PR that added a callout for that if it'd be merged?

We welcome any improvements to documentation (or in general). But I will not offer a guarantee that PRs will be merged without first seeing them. Code review is still important.

**Comment by mmarti** [comment]
> We welcome any improvements to documentation (or in general). But I will not offer a guarantee that PRs will be merged without first seeing them. Code review is still important.

Of course :P I more so was talking about if callouts like that were generally acceptable in the docs, or if there was some other preferred place / solution for things like that.  I'll see if I can get a small PR sent out when I get some free time. :)

**Comment by jsumners** [comment]
👍
