### ISSUE TITLE
[TypeScript] 'FastifyPlugin' is deprecated

### ISSUE THREAD

**Issue by ynwd** [fastify/help#264]
What is the solution of this warning?

![Screenshot from 2020-09-17 06-16-06](https://user-images.githubusercontent.com/10122431/93401863-7558b580-f8ad-11ea-8f30-7b393234ad61.png)

```
Generic plugin type.

@deprecated — union type doesn't work well with type inference in TS and is therefore deprecated in favor of explicit types. See FastifyRegister.
```

**Comment by mcollina** [comment]
cc @fox1t @Ethan-Arrowood

**Comment by fox1t** [comment]
Hi @ynwd change your import to
```ts
import { FastifyPluginCallback } from 'fastify'
```
And use it as type. We have also 
```ts
import { FastifyPluginAsync } from 'fastify'
```
for the async plugins.

**Comment by fox1t** [comment]
I am going to change this deprecation warning to something like this:

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/1620916/93434681-bf02c980-f8c8-11ea-8399-67e2b17c4cda.png">

**Comment by ynwd** [comment]
Thank you @fox1t
