### ISSUE TITLE
Regular exppression routes don't allow slash in the regexp

### ISSUE THREAD

**Issue by JakeChampion** [fastify/help#267]
#### You have already researched for similiar issues?
Yep, couldn't find anything across the Fastify repos.

#### What are you trying to achieve or the steps to reproduce?

I'm trying to migrate an express project to Fastify and stumbled on our routes. We use a regex route like this:

```js
fastify.get('/v2/images/raw/:image(^https?(:|%3A)?(\\/|%2F)*.*)', function (request, reply) {
```
but it does not match against the path `/v2/images/raw/http%3A%2F%2Fblogs.ft.com%2Fthe-world%2Ffiles%2F2020%2F09%2Fnyc-school-plan-2048x1152.jpg?source=next&fit=scale-down&dpr=2&width=240` like it does with express.

#### What was the result you received?
Fastify returned a 404

#### What did you expect?
I would have expected it to match the path and handle the request

#### Context

* *node version*: 14.5
* *fastify version*: fastify@3.4.1
* *os*: Mac

**Comment by Eomm** [comment]
I can't reproduce with a fresh install, do you have other lifecycle hooks?

```
const fastify = require('fastify')({ logger: true })

fastify.get('/v2/images/raw/:image(^https?(:|%3A)?(\\/|%2F)*.*)', function (request, reply) { reply.send(request.params) })

const start = async () => {
  try {
    await fastify.listen(3000, '0.0.0.0')
    fastify.log.info(`server listening on ${fastify.server.address().port}`)
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()
```

```sh
$ curl "http://localhost:3000/v2/images/raw/http%3A%2F%2Fblogs.ft.com%2Fthe-wor       
ld%2Ffiles%2F2020%2F09%2Fnyc-school-plan-2048x1152.jpg?source=next&fit=scale-do       
wn&dpr=2&width=240"
{"image":"http://blogs.ft.com/the-world/files/2020/09/nyc-school-plan-2048x1152.jpg"}
```

**Comment by JakeChampion** [comment]
Thanks for the response @Eomm. It turns out it was a service worker issue from another project I was working, I forgot to deregister the service worker before starting on this project.
