### ISSUE TITLE
sending an object via querystring and validating against a JSON schema

### ISSUE THREAD

**Issue by punkish** [fastify/help#269]
#### You have already researched for similar issues?
yes, couldn't find anything similar to what is puzzling me

#### What are you trying to achieve or the steps to reproduce?

I have the following querystring schema

```js
location: {
        schema: {
            type: "object",
            properties: {
                radius: { type: "number" },
                lat:    { type: "number", minimum: -90, maximum: 90 },
                lng:    { type: "number", minimum: -180, maximum: 180 },
                find:   { type: "string", enum: ["near", "within"] },
                units:  { type: "string", enum: ["miles", "kms"] }
            }
        }
    }
```

The above schema validates `"location": {"find": "within", "radius": 4, "lat": -5, "lng": 32, "units": "kms"}`

#### What was the result you received?
But when I send `location={"find": "within", "radius": 4, "lat": -5, "lng": 32, "units": "kms"}` (URLencoded, of course), I get an error

```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "querystring.location should be object"
}
```

#### What did you expect?
How can I send an object via the querystring so fastify's validation mechanism will let it pass through?

#### Context

* *node version*: 12.x
* *fastify version*: >=3.4.x
* *os*: Mac

**Comment by Eomm** [comment]
In fastify, you have always many ways to accomplish tasks 😄 

You could change the query parser and call the endpoint with a "like json format":

`curl http://localhost:8080/?location[find]="near"`

```
const qs = require('qs')
const fastify = require('fastify')({
  querystringParser: str => qs.parse(str)
})

fastify.get('/', {
  schema: {
    querystring: {
      location: {
        type: 'object',
        properties: {
          find: { type: 'string', enum: ['near', 'within'] }
        }
      }
    }
  },
  handler (req, res) {
    console.log('pinged!!')
    res.send(req.query)
  }
})

fastify.listen(8080)
```

Or, if you need the stringify json in the querystring, you may use the [preValidation](https://github.com/fastify/fastify/blob/master/docs/Hooks.md#prevalidation) hook to parse the string to a JSON and then let the validator does its job.

```
fastify.addHook('preValidation', (request, reply, done) => {
  request.query.location = JSON.parse(request.query.location)
  done()
})
```

Notice that JSON.parse could lead to security issue

**Comment by punkish** [comment]
thank! This is the pattern that I didn't know of `http://localhost:8080/?location[find]="near"`

Also, the hint about the `querystringParser` is very helpful.
