### ISSUE TITLE
Multiple consequent preHandler

### ISSUE THREAD

**Issue by SamSalvatico** [fastify/help#271]
#### What are you trying to achieve or the steps to reproduce?

Trying to insert two consecutive preHandlers for authentication, using fastify-auth, and authorization.

This is the metod used in fastify auth
```js
fastify
      .decorate(
        'tokenChecker',
        async (
          request: any,
          reply: FastifyReply,
          done: any,
        ) => {
            //all my wonderful code
            return done();    
          },
      );

```

This is my route declaration

```js
fastify.post(
      '/please_work',
      {
        schema: myWonderfulSchema,
        preHandler: [
          this.fastifyInstance.auth([this.fastifyInstance.tokenChecker]),
          (
            req: FastifyRequest,
            reply: FastifyReply,
            done: any,
          ) => {
            fastify.permissionsChecker(req, reply, done, a_custom_param_that_i_need);
          }
        ]
      },
      async (request: FastifyRequest, reply: FastifyReply) => this.handlerMethod(request, reply),
    );
```

#### What was the result you received?

Apparently it works, but when I set a console.log in this.handlerMethod it is written twice. So it invoke the method for each preHandler I set.

#### What did you expect?

I expect that the preHandlers are processed consequently, so the handlerMethod is invoked once.
Is there a way to achieve this? I need a preHandler executed after the auth one in which I can pass a custom param. (Like middlewares in other frameworks)

#### Context

* *node version*: "v12.18.2"
* *fastify version*: "^3.4.1",
* *os*: Ubuntu
* *fastify-auth version*: "^1.0.1"

**Comment by RafaelGSS** [comment]
Hey @SamSalvatico 

I'm not sure if I completely understand your question, let me see:

- In your case, has declared two `preHandlers` to a route and expect that the `handler` was called one time after `preHandler` right?

Can you provide a minimal reproduction code?

**Comment by SamSalvatico** [comment]
Hey @RafaelGSS thank you for your time.
I hope I can explain myself in a better way.

I have two preHandlers, one has to be processed after another if the first doesn't throw an error. In this moment they are both processed, but the method in the handler property is invoked twice, so it tries to insert a model twice in db.

**But, I found the error, It was my fault**, sorry.
The method I use in fastify auth was:
```js
fastify
      .decorate(
        'tokenChecker',
        async (
          request: any,
          reply: FastifyReply,
          done: any,
        ) => {
          if (!request.raw.headers.authorization) {
            return done(new Error('Missing token header'));
          }
          const auth = request.headers.authorization;
          const token = auth.split(' ')[1];
          await fastify.jwt.verify(token, (err: any, decoded: { email: any; password: any; }) => {
            if (
              err
              || decoded.email === undefined
              || decoded.email == null
              || decoded.password === undefined
              || decoded.password == null
            ) {
              return done(new Error('Token not valid'));
            }
            request.user = decoded;
            return done();
          });
          return done(); // pass an error if the authentication fails
        },
      );
```

But, in the fastify-auth documentation, in the README, it is clearly written that "This plugin support callback and Promise returned by the functions. Note that an async function doesn't have to use the done parameter:"
So I removed the done() in the code and now it works. It executes the fastify auth, then the other preHandler, then the method in handler.
```js

fastify
      .decorate(
        'tokenChecker',
        async (
          request: any,
          reply: FastifyReply,
          done: any,
        ) => {
          if (!request.raw.headers.authorization) {
            throw Error('Missing token header');
          }
          const auth = request.headers.authorization;
          const token = auth.split(' ')[1];
          await fastify.jwt.verify(token, (err: any, decoded: { email: any; password: any; }) => {
            if (
              err
              || decoded.email === undefined
              || decoded.email == null
              || decoded.password === undefined
              || decoded.password == null
            ) {
              throw Error('Token not valid');
            }
            request.user = decoded;
          });
          // return done(); // pass an error if the authentication fails
        },
      );
```
