### ISSUE TITLE
TypeError: lru is not a function

### ISSUE THREAD

**Issue by drieshooghe** [fastify/help#272]
## 🐛 Bug Report
We have a Serverless Typescript project.
When bundling our functions with webpack (for Node) through lerna/yarn workspaces we get the following error:
```
gateway: TypeError: lru is not a function
gateway:     at new ContentTypeParser (webpack:////Projects/api/node_modules/fastify/lib/contentTypeParser.js?:31:16)
gateway:     at build (webpack:////Projects/api/node_modules/fastify/fastify.js?:155:27)
```
However, copying the content of `tiny-lru.cjs.js` into `tiny-lru.esm.js` and into `tiny-lru.js` seems to fix this.

## Your Environment

- *node version*: v12.18.2
- *fastify version*: ~2.15
- *tiny-rlu version*: ^7.0.2
- *os*: Mac

**Comment by mcollina** [comment]
Moving to help.

**Comment by geiszla** [comment]
We have the same problem and we're using razzle without any webpack config modification. Is this an issue with fastify or should I open an issue at razzle?

**Comment by mcollina** [comment]
I think it's a razzle problem.

**Comment by schickling** [comment]
Same problem for `esbuild`.

**Comment by Eomm** [comment]
We can't do anything on the Fastify side.

In the source code: https://github.com/fastify/fastify/blob/master/lib/contentTypeParser.js
there is nothing strange we apply on that require.

If you would like to share your findings when solved, it would be useful for other people

**Comment by schickling** [comment]
As I'm using Yarn 2, I ended up patching the `tiny-lru` dependency:

File: `.patches/tiny-lru.patch`

```
diff --git a/package.json b/package.json
index 0f3b11ed8a6fdb153dbd6d9f313cca92d47cf021..f33d48dd0dc8d1c6362b36b3480320495671cb59 100644
--- a/package.json
+++ b/package.json
@@ -19,7 +19,6 @@
   "source": "src/lru.js",
   "browser": "lib/tiny-lru.js",
   "main": "lib/tiny-lru.cjs.js",
-  "module": "lib/tiny-lru.esm.js",
   "types": "tiny-lru.d.ts",
   "engines": {
     "node": ">=6"

```

Needs to be referenced in `resolutions` in the root `package.json`:

```json
  "resolutions": {
    "tiny-lru": "patch:tiny-lru@7.0.6#./.patches/tiny-lru.patch"
  }
```

**Comment by mattburton** [comment]
Another option in case it helps anyone who hits this issue - just adjust the relative paths below to your top-level `node_modules` directory:

```javascript
const path = require('path');
const nodeExternals = require('webpack-node-externals');

module.exports = {
  target: 'node',
  mode: 'production',
  externals: [
    nodeExternals({
      modulesDirs: [path.resolve(__dirname, '../node_modules')],
    }),
  ],
  resolve: {
    alias: {
      'tiny-lru': path.join(process.cwd(), "../node_modules/tiny-lru/lib/tiny-lru.cjs.js"),
    }
  }
};

```

**Comment by orlein** [comment]
@mattburton 
Your code saved me literally. Thank you!!
But now, your comment and the code are needed to be modified:
1. `node_modules` should have `tiny-lru`. so, who wants bundled file should run `npm install tiny-lru`.
2. `tiny-lru@10.0.1` uses `dist` folder, instead of `lib`. There is no `node_modules/tiny-lru/lib/tiny-lru.cjs.js`. There is `node_modules/tiny-lru/dist/tiny-lru.cjs`.

so the result is,

```javascript
const path = require('path');
const nodeExternals = require('webpack-node-externals');

module.exports = {
  target: 'node',
  mode: 'production',
  externals: [
    nodeExternals({
      modulesDirs: [path.resolve(__dirname, '../node_modules')],
    }),
  ],
  resolve: {
    alias: {
      "tiny-lru": path.resolve(
        __dirname,
        "..",
        "node_modules/tiny-lru/dist/tiny-lru.cjs"
      ),
    }
  }
};
```

Then you can bundle the whole project files into one js file, without need of any `node_modules` dependencies.
