### ISSUE TITLE
JSON schema validation with `additionalProperties` false doesn't seem to work

### ISSUE THREAD

**Issue by punkish** [fastify/help#274]
#### You have already researched for similar issues?

yes, no luck

#### What are you trying to achieve or the steps to reproduce?

I am trying to implement a schema that prevents submitting queries with parameters that are not listed in the schema. I have the following (minimum but complete, runnable code). For what it's worth, the schema shown therein validates as expected using https://www.jsonschemavalidator.net/ as well as https://jsonschemalint.com/#!/version/draft-07/markup/json

```js
'use strict'

const fastify = require('fastify')({ logger: true })

const opts = {
    schema: {
        querystring: {
            "type": "object",
            "properties": {
                "foo": { "type": "string" },
                "bar": { "type": "string" },
                "baz": { "type": "string" },
                "one": { "type": "integer" },
                "two": { "type": "integer" }
            },
            "additionalProperties": false,
            "if": {
                "anyOf": [
                    { "required": ["bar"] },
                    { "required": ["baz"] }
                ]
            },
            "then": { "required": ["one", "two"] }
        }
    }
}

fastify.get('/', opts, async (request, reply) => {
    return { hello: 'world' }
})

// Run the server!
fastify.listen(3010, function (error, address) {
    if (error) {
        fastify.log.error(err)
        process.exit(1)
    }

    fastify.log.info(`server listening on ${address}`)
})
```

#### What was the result you received?

`http://127.0.0.1:3010/?foo=snub` works, returns `{"hello":"world"}`

`http://127.0.0.1:3010/?bar=blah` works, returns `{"statusCode":400,"error":"Bad Request","message":"querystring should have required property '.one'"}`

though why it prefixes a '.' before 'one' is baffling.

`http://127.0.0.1:3010/?qux=frob` fails, returns `{"hello":"world"}`

#### What did you expect?

I was expecting the third query to fail with an error like `Property 'qux' has not been defined and the schema does not allow additional properties.`

#### Context

* *node version*: 12.x
* *fastify version*: >=3.4.x
* *os*: Mac

**Comment by punkish** [comment]
**update:** For what it's worth, I have figured out that fastify's validation mechanism is silently removing any `additionalProperties` instead of raising an error.

**Comment by jsumners** [comment]
https://www.fastify.io/docs/v3.4.x/Server/#ajv

**Comment by punkish** [comment]
oooh thanks @jsumners, that solved it. 

```js
ajv: {
        customOptions: {

            // Refer to [ajv options](https://ajv.js.org/#options)
            removeAdditional: false 
        }
    }
```
