### ISSUE TITLE
Issue with routes plugin with the same function name and autoload

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [fastify/help#279]
Hi,
I do not know if this is a bug or the expected behaviour then I decided to put a question here, maybe something is not clear to me.

#### What are you trying to achieve or the steps to reproduce?

In my application I have a folder `/routes` that is automatically loaded by using `fastify-autoload` in the root script. The folder structure is something like this:

```text
/routes
    /auth
      index.js
      schemas.js
    /products
      index.js
      query.js
      schemas.js
```

Both (and esclusively) the `routes/auth/index` and `routes/products/index` defines their own routes plugins in this way:

```javascript
const fp = require('fastify-plugin');

// keep an eye on the function name...
function route(fastify, opts, done) {
  fastify.post(
    '/auth/login', // or '/products'
    {
      // schema and opts...
      schema: {
        body: LoginRequest,
        response: { 200: LoginResponse }
      }
    },
    async function(request, reply) {
      // do stuff...
      return {something};
    }
  );
  done();
}

module.exports = fp(route);
```

#### What was the result you received?

I have noticed that autoload does not instantiate correctly all the routes if both `auth/index` and `products/index` defines the route plugin with a function named `route`. In fact autoload instantiates only the last index file by alphabetical order of the folders.

#### What did you expect?

I wasn't expecting that the function name when building a plugin really mattered. I do not understand if it is the right behaviour or I'm missing something.

#### Context

* *node version*: 12.18.0
* *fastify version*: 3.5.1
* *fastify-autoload version*: 3.3.0
* *os*: Mac

**Comment by mcollina** [comment]
Which version of fastify-plugin are you using? From my tests, this was fixed in https://github.com/fastify/fastify-plugin/pull/95 with fastify-plugin 2.1.0.

Can you please make a repro to reproduce this problem?

**Comment by giovanni-bertoncelli** [comment]
Indeed it was the `fastify-plugin` version... I've generated the project with the `fastify-cli` and it has installed an old version. Updating fixed the problem. Thanks @mcollina !
