### ISSUE TITLE
Request ID not available in 'onResponse' hook

### ISSUE THREAD

**Issue by smartiniOnGitHub** [fastify/help#28]
#### You have already researched for similiar issues?
Yes but didn't find.

#### What are you trying to achieve or the steps to reproduce?
I'm using request id as 'correlation id' for all hooks that I'm listening, but it's not available in the 'onResponse' hook, see [hooks](https://github.com/fastify/fastify/blob/master/docs/Hooks.md); even request url would be a nice to have.
In that way, it could be simpler to read the flow of events across all hooks, even when collecting all events in a single place (like a queue, to be processed later).
As an example, you can look at [fastify-cloudevents](https://github.com/smartiniOnGitHub/fastify-cloudevents), and one of its [example](https://github.com/smartiniOnGitHub/fastify-cloudevents/tree/master/example) sources.

#### What was the result you received?
I'm not able to relate log of different hooks that belongs to the same user request, for example to understand (looking only at those events) if it has been successful or not and how long it took.

#### What did you expect?
If possible to have request id and url ... or does it make sense to have all the request object available even in the 'onResponse' hook ?
Or maybe could I get request id and url in one of previous hooks and store so I can use in the 'onResponse' hook ? No problems in a multi-user requests in this case ?

#### Context

* *node version*: 8.12.0 and higher
* *fastify version*: >=0.43.0 and higher (for example latest)
* *os*: Mac, Windows, but in general all
* *any other relevant information*: nothing special.

Thanks a lot for the help,
Sandro

**Comment by delvedor** [comment]
Currently is not possible, but it will be in Fastify v2, where we standardized all of our hooks :)

**Comment by smartiniOnGitHub** [comment]
@delvedor ah ok, thanks for the info ... does it make sense to open an issue for this or is it already in plan ? Last, do you prefer to close this issue or wait for the v2 ?

**Comment by mcollina** [comment]
It's already implemented, https://github.com/fastify/fastify/pulls?utf8=%E2%9C%93&q=+is%3Apr+milestone%3Av2.0.0+.

One left to go and we can release v2.

**Comment by smartiniOnGitHub** [comment]
@mcollina this is a great news !! :-)
