### ISSUE TITLE
how to send an array in the querystring so it validates against an array schema

### ISSUE THREAD

**Issue by punkish** [fastify/help#281]
#### You have already researched for similiar issues?
yes, no hits

#### What are you trying to achieve or the steps to reproduce?

I have a querystring schema like so

```js
name: 'cols',
        schema: { 
            type: 'array', 
            items: { type: 'string' },
            description: `Columns to retreive in the result set. Provide a list like so:
- \`cols=column1&cols=column2&cols=column3\``
        }
```

#### What was the result you received?

The following validates `?cols=foo&cols=bar` but if I provide only one value `?cols=foo` I get an error `querystring/cols should be array`. How do I send an array of only one item and get through the validator? Are repeating values (`?cols=foo&cols=bar`) the only way or are there alternatives? ~~I should add that `?cols=foo&cols=` works but looks rather silly.~~

#### What did you expect?

I was expecting `?cols=foo` to not raise and error

#### Context

* *node version*: 12.x
* *fastify version*: >=3.4.x
* *os*: Mac

**Comment by mcollina** [comment]
There are a couple of ways to achieve this. 

One is to enable type coercion for arrays in Ajv: https://ajv.js.org/coercion.html. See Also https://www.fastify.io/docs/latest/Server/#ajv. We might want to consider moving to `coerceTypes: 'array'` in the v4.

The second way is to change how you pass the query string parameters. Fastify relies upon the node core querystring parser, e.g. `require('querystring')`. You might get more features moving to http://npm.im/qs which is what express uses. Then you can use `cols[]` to indicate that's an array.
See https://www.fastify.io/docs/latest/Server/#querystringparser for more details.

**Comment by punkish** [comment]
> There are a couple of ways to achieve this.
> 
> One is to enable type coercion for arrays in Ajv: https://ajv.js.org/coercion.html. See Also https://www.fastify.io/docs/latest/Server/#ajv. We might want to consider moving to `coerceTypes: 'array'` in the v4.
> 


Thanks, the above works for me. (I find the `cols[]` syntax a bit inelegant).
