### ISSUE TITLE
Troubles with unofficial plugin

### ISSUE THREAD

**Issue by mitry1974** [fastify/help#282]
Hello!

In my project I use unofficial fastify plugin - fastify-method-override" and it has some bugs.
The worst of them - it lost reply.context.config.
It looks the plugin don't setup that config during method override setup or call.
I need that plugin in my project and I'm ready to fix it.
So, the question is - where in fastify code is a place to add route config to the context of reply?

Thank you!

#### You have already researched for similiar issues?
It's not uncommon that somebody already opened an issue or in best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/fastify/fastify/issues) at first before submitting a new one.

#### What are you trying to achieve or the steps to reproduce?

I try to reproduce that bug in different conditions and I 

```js
// Wrap code in markdown source tags
```

#### Context

* *node version*: 4,5,6,7,8,9
* *fastify version*: >=0.37.0
* *os*: Mac, Windows
* *any other relevant information*:

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by StarpTech** [comment]
Did you try to fix it in the plugin?

**Comment by mitry1974** [comment]
Yes,  I try, but I need to know what is missed - what part of fastify doesn't call.
I try to understand myself, but it isn't very easy.
If anybody can point me where is a place to set config for reply object it really helps me.

**Comment by StarpTech** [comment]
Hi, @mitry1974 I suggest you discuss it in the corresponding repository. Try to provide a fully reproducible example of your problem. It's very hard to understand.

**Comment by mitry1974** [comment]
ok, thank you. Will open issue in fastify repo

**Comment by jsumners** [comment]
> ok, thank you. Will open issue in fastify repo

No, the issue lies in the plugin you are attempting to use. You should open an issue there.
