### ISSUE TITLE
What is best practice for dependency injection?

### ISSUE THREAD

**Issue by viglucci** [fastify/help#284]
What is best practice for dependency injection/lifecycle management when using Fastify?

From what I have gathered from the documentation, the way to expose services, objects, and functionality to the various parts of the application is through plugins, however I am not sure if a "plugin" is where this belongs or not.

For instance, say I have a route `/users` that relies on invoking a `UserService` which also needs to consume a `MySQLDriver` for interacting with a database. Would the idea be to add an instance of `UserService` to `fastify` using `.decorate()`?

Example:

```js
// plugins/user-service-provider.js
const fastifyPlugin = require('fastify-plugin')

function userServiceProvider(fastify, options) {
  const service = new UserService({
    driver: fastify.mysqlDriver
  });
  fastify.decorate('userService', service);
}

module.exports = fastifyPlugin(userServiceProvider);
```

```js
// routes/users/index.js
module.exports = async function (fastify, opts) {
  fastify.get('/', async function (request, reply) {
    // return JSON of all users
    return fastify.userService.getAll();
  });
};
```

Are there any fully fleshed out examples of a CRUD or other none trivial use-case that demonstrates managing the applications objects & services in this way?

**Comment by mcollina** [comment]
I would recommend https://github.com/covidgreen/covid-green-backend-api.

**Comment by jsumners** [comment]
I think you have it mostly correct. My suggestion for the code you have provided is to remember that the route handler function is bound to the server instance. So you could write:

```js
fastify.get('/', async function (request, reply) {
  return this.userService.getAll()
})
```

**Comment by RafaelGSS** [comment]
I normally use it as you sent on the example (for non-typescript applications). By the way, I have a repository with an example:

https://github.com/RafaelGSS/fastify-ms-auth

Register dependencies: https://github.com/RafaelGSS/fastify-ms-auth/blob/master/src/plugins/decorator.js#L12
Usage: https://github.com/RafaelGSS/fastify-ms-auth/blob/master/src/services/login.js#L29

**Comment by viglucci** [comment]
Thanks for the examples y'all! I'll close this out as solved.
