### ISSUE TITLE
Accessing body fields in a multipart form after saving files to disk with saveRequestFiles() 

### ISSUE THREAD

**Issue by bmo-at** [fastify/help#286]
#### You have already researched for similiar issues?
It's not uncommon that somebody already opened an issue or in best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/fastify/fastify/issues) at first before submitting a new one.

#### What are you trying to achieve or the steps to reproduce?

I'm trying to save files to disk with the saveRequestFiles() method from fastify-multipart.

This works out well, but now I want to introduce the possibility to submit additional data through fields in the body.

#### What was the result you received?

The problem I'm facing now is that after calling saveRequestFiles(), I don't have any access to those other fields in the body that aren't files. Is there any way to retrieve them?

#### What did you expect?

 I was on the verge of filing another bug report in fastify-multipart, since I really think writing the files to disk shouldn't discard other body fields.

#### Context

* *node version*: 12
* *fastify version*: 3.6.0
* *os*: Debian on WSL2
* *fastify-multipart version*: 3.2.1 

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by mcollina** [comment]
> I was on the verge of filing another bug report in fastify-multipart, since I really think writing the files to disk shouldn't discard other body fields.

I would recommend to send a PR fixing this behavior.
