### ISSUE TITLE
Convert json property name while parsing and serialization

### ISSUE THREAD

**Issue by botstar-quang** [fastify/help#288]
#### You have already researched for similiar issues?
Haven't found any clue

#### What are you trying to achieve?

I want to convert snake case to camel case for request body and convert camel case to snake case for response.

My ongoing way is manually parse object in preParsing, preSerialization hooks but I think this way will slow down fastify.

#### What did you expect?

Is there any built-in way of fastify json parser support json property name converting?

* *node version*: 12
* *fastify version*: 3.7.0
* *os*: Mac

**Comment by L2jLiga** [comment]
Have you tried to use [`Content-Type` Parser](https://github.com/fastify/fastify/blob/master/docs/ContentTypeParser.md#content-type-parser) and [Serializer Compiler](https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md#serializer-compiler)

**Comment by rickerp** [comment]
@botstar-quang did you manage to get it working using [Content Type Parser](https://github.com/fastify/fastify/blob/master/docs/ContentTypeParser.md#content-type-parser) ? I did manage with Serializer Compiler
