### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Skn0tt** [fastify/help#289]
## 🐛 Bug Report

I'm trying to get the Schema validation working, but Fastify throws whenever I make a request:

```
TypeError: Cannot read property 'length' of undefined

      at next (node_modules/fastify/lib/route.js:407:32)
      at preParsingHookRunner (node_modules/fastify/lib/route.js:438:3)
      at runPreParsing (node_modules/fastify/lib/route.js:389:5)
      at Object.routeHandler [as handler] (node_modules/fastify/lib/route.js:349:7)
      at Router.lookup (node_modules/find-my-way/index.js:356:14)
```

## To Reproduce

1. Clone https://github.com/quirrel-dev/quirrel/tree/transition-to-owl
2. Go to `/api` and run `npm test`
  (the tests require Redis running on `localhost:6379`, you can start one using `docker run -d --name redis -p 6379:6379 redis`)

## Expected behavior

I expect Fastify to successfully answer my requests.

## Your Environment

- *node version*: 14.13.0
- *fastify version*: 3.7.0
- *os*: Mac

**Comment by Skn0tt** [comment]
@Ethan-Arrowood asked if it works without the Schema: Yes, it does.

It seems to me that in [this line](https://github.com/fastify/fastify/blob/2737f436974d28e6917aeb244cc8d0686821512c/lib/route.js#L388), `context.preParsing` is undefined in my case.

As a workaround, I was able to fix this issue by adding `this.preParsing = null` in [`context.js`](https://github.com/fastify/fastify/blob/2895b81386e595511360d8c849e3a6d204e40b41/lib/context.js#L7).

**Comment by Ethan-Arrowood** [comment]
So I think this is an issue with the import. Why are you using `import * as thatSchema from './that.json'`? I'd debug and make sure this is importing as expected.

**Comment by Skn0tt** [comment]
I've added `console.log({ EndpointJobIDParamsSchema })` to `queues.ts` and it logged the following:

```js
{
  EndpointJobIDParamsSchema: {
      '$schema': 'http://json-schema.org/draft-07/schema#',
      title: '/queues/:endpoint/:id params',
      type: 'object',
      properties: { id: [Object], endpoint: [Object] },
      required: [ 'id', 'endpoint' ],
      additionalProperties: false
    }
}
```

That seems correct to me, doesn't it?

**Comment by mcollina** [comment]
@Skn0tt I have tried and I cannot reproduce based on the provided instructions. Could you include a simplified example in a single file? Thanks

**Comment by Ethan-Arrowood** [comment]
Yes this is what I suspected @Skn0tt - you might need to pass `thatSchema.EndpointJobIDParamsSchema` to the route. But also a more simplified example can help us narrow down the issue you're facing

**Comment by Skn0tt** [comment]
That hasn't been the problem, apparently. It was that I specified my response schema like so in another route:

```ts
fastify.get("/anything", { schema: { response: thatSchema } }, ...)
```

instead of 

```ts
fastify.get("/anything", { schema: { response: { 200: thatSchema } } }, ...)
```

It makes sense in hindsight, but I wasn't able to find the error by looking at the error messages.

I'll provide a minimal repro nonetheless and take a look if I can provide a PR to make the developer mistake easier to spot :D
