### ISSUE TITLE
Understand why randomly cannot connect to mongo cluster using fastify-mongodb

### ISSUE THREAD

**Issue by SamSalvatico** [fastify/help#291]
#### What are you trying to achieve or the steps to reproduce?

Hi, I'm facing a curious problem since I've started to use fastify-mongodb. Randomly I cannot connect to my mongodb atlas cluster. I'm not saying that the problem is fastify-mongodb, I only need to understand why it happens apparently random because it is driving me crazy.
E.g. Debugging the application connects correctly. Stop it. Start it. Cannot connect.
This is my code:
```js
const myConn = 'mongodb+srv://user:pwd@mycluster-jm9lj.mongodb.net/thedb?connectTimeoutMS=61000'
server.register(require('fastify-mongodb'), {
      // force to close the mongodb connection when app stopped
      // the default value is false
      forceClose: false,
      url: myConn,
    });
```

#### What was the result you received?

When It cannot connect it returns: 
```
Error: ERR_AVVIO_PLUGIN_TIMEOUT: plugin did not start in time: /media/sam/Dati/Progetti/Cws/Node/ufarmer/iotmobile_ufarmer_backend/node_modules/fastify-mongodb/index.js
    at Timeout._onTimeout (/media/sam/Dati/Progetti/Cws/Node/ufarmer/iotmobile_ufarmer_backend/node_modules/avvio/plugin.js:122:19)
    at listOnTimeout (<node_internals>/internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {code: 'ERR_AVVIO_PLUGIN_TIMEOUT', fn: ƒ, stack: 'Error: ERR_AVVIO_PLUGIN_TIMEOUT: plugin did n…  at processTimers (internal/timers.js:492:7)', message: 'ERR_AVVIO_PLUGIN_TIMEOUT: plugin did not sta…ackend/node_modules/fastify-mongodb/index.js'}
```

#### What did you expect?

I need to receive a more clear error: "Okay, AVVIO PLUGIN cannot start. But which one is the problem about the cluster?"
Is already available a way to achieve it?

#### Context

* *node version*: v12.18.2
* *fastify version*: "^3.5.1"
* *os*: Ubuntu 20.04
* *fastify-mongodb*: ^2.0.1

**Comment by mcollina** [comment]
You are specifing `connectTimeoutMS=61000` so your timeout in 61 seconds. Avvio would time out in 10s. Those two need to match: check out https://www.fastify.io/docs/latest/Server/#plugintimeout. You'd need to pass `pluginTimeout: 62000` to your fastify constructor.

**Comment by ngandwe1995** [comment]
I had the same issue when I was running my server on the local, after deploying to GCP the problem disappeared
