### ISSUE TITLE
question about ban prop for fastify-rate-limit

### ISSUE THREAD

**Issue by sell** [fastify/help#296]
#### What are you trying to achieve or the steps to reproduce? none, just a question

Hello, so how does the ban work? I tried using it, and it just unbans the user after the timeWindow expires, what is the point of using it rather than just sending a 429 request, when it'll just stop sending the 403 when the user is unbanned aka when timeWindow is over?

here is my setup:
```js
fastify.register(require('fastify-rate-limit'), {
  max: 1,
  ban: 1,
  timeWindow: 10000,
  skipOnError: true,
  addHeaders: {
    'x-ratelimit-limit': true,
    'x-ratelimit-remaining': true,
    'x-ratelimit-reset': true,
    'retry-after': true
  }
});
```

it's 1 for testing, but yeah it'll unban user after 10 seconds, so kind of confused.

**Comment by mcollina** [comment]
I'm not entirely sure I can help. I would recommend to read the source code and maybe make a more specific question. There might be bug there as well.

**Comment by Eomm** [comment]
> when it'll just stop sending the 403 when the user is unbanned aka when timeWindow is over?

The `ban` has been introduced here
https://github.com/fastify/fastify-rate-limit/issues/63

Some (evil) clients ignore the 429 error response but will slow down with 403
Moreover you could add one `onSend` hook that track the 403 response and a `onRequest` hook that will ban permanently the client
