### ISSUE TITLE
Question on Javascript version to use

### ISSUE THREAD

**Issue by lesar** [fastify/help#297]
#### You have already researched for similiar issues?
yes

#### Context

* *node version*: v14.12.0
* *fastify version*: >=3.7.0
* *os*: Ubuntu 20.04
* *any other relevant information*: on rpi4

I see that you use commonJS for import  

I have read on readme  you use Node v10.16 and on [node.green](https://node.green/) I look at column 10.23 that is good for v10.16 and almost all es2015 is supported  

what js version are you using to write fastify and plugin fastify  
what version have I to use to write fastify plugin

regards,
Leonardo

**Comment by RafaelGSS** [comment]
Hey @lesar. Sorry, I don't understand the real question here. You can write a plugin in any nodejs version that fastify supports officially (>= 10)

**Comment by lesar** [comment]
ok, so es2015 is good.
thank you
