### ISSUE TITLE
Can't access a fastify server without using a reverse proxy

### ISSUE THREAD

**Issue by NotWoods** [fastify/help#298]
#### What are you trying to achieve or the steps to reproduce?

I'm running a fastify server on a Raspberry Pi 4 under Debian/Raspberry Pi OS, and I'm unable to access the server from other computers on the same local network. While I can make requests from the Raspberry Pi itself using `curl`, I can't access it from other computers. As a workaround, I'm currently using a reverse proxy program on the Pi.

#### What was the result you received?

Expect that `http://<pi-ip-addr>:3000` will send a request to the server and get a response.

#### Context

* *node version*: 14
* *fastify version*: 3.7.0
* *os*: Raspberry Pi OS
* *any other relevant information*:

Some things I've already tried:
- Running a server with `python3 -m http.server` works fine, I can access it normally
- Running a server with `npx http-server` also works fine.
- Changing the port doesn't have an effect
- There are no indications in the server logs to show that it hears the request
- Just copying the quick start script on fastify.io has the same problems, so it doesn't seem to be caused by my code.
- As far as I can tell, there is no firewall on the Raspberry Pi. It shouldn't be enabled by default.

**Comment by mcollina** [comment]
Fastify only listen to localhost by default, you need to pass 0.0.0.0 to list to all networks.

**Comment by NotWoods** [comment]
Thank you, that fixed it 😄
