### ISSUE TITLE
Change server option in middleware

### ISSUE THREAD

**Issue by YuriGal** [fastify/help#299]
Very new to Fastify, so pretty much [this](https://stackoverflow.com/questions/64705839/change-server-option-in-middleware)

Really appreciate any pointers.

**Comment by jsumners** [comment]
A plugin is not middleware.

**Comment by YuriGal** [comment]
> A plugin is not middleware.

Thank you for correcting me, I am still learning.

ok, so I have a plugin like this, that does its own request logging

```
import { FastifyInstance, FastifyRequest } from 'fastify';
import fp = require('fastify-plugin');

export const requestLoggerPlugin = fp(
  async (app: FastifyInstance): Promise<void> => {
    app.addHook('onRequest', async (req: FastifyRequest) => {
      req.log.info({test: 'Hello world' });
    });
  },
);
```

And I use it like this
```
const fastify = require('fastify')({logger:true});
const simplifiedLogger = require('./highbond-simplified-logger');  
fastify.register(simplifiedLogger);
```
it works, and custom request logger is outputted. But because `{logger:true}` fastify does default info logging of every request as well. I'd like to disable it, but only if plugin is registered. Any help is appreciated.

**Comment by jsumners** [comment]
I'm not going to try to read TypeScript.

Currently, request logging can only be disabled at the root level. You're welcome to propose a PR to change this.

**Comment by YuriGal** [comment]
I appreciate you going above and beyond your duty with the very detailed help in this issue.

**Comment by Eomm** [comment]
> I'd like to disable it, but only if plugin is registered

You know in the upper scope if you are going to register it:

```
const isProd = false

const fastify = require('fastify')({ logger: isProd })

if( isProd === false ){
  fastify.register(simplifiedLogger)
}
```

The pattern you would like to propose has too many side effect: it doesn't let the user that uses your plugin to choose what is the best for the application.

I would suggest to checkout the [`serializers` options of the logging](https://github.com/fastify/fastify/blob/master/docs/Logging.md#log-redaction)

I think this would be even better and let you to write:

```js
const fastify = require('fastify')({ logger: simplifiedLogger(options) })
```

where `simplifiedLogger` is a factory that build a custom `pino` logger that print less or more output based on options
