### ISSUE TITLE
how to make route registration to wait till plugin is registered

### ISSUE THREAD

**Issue by PavelPolyakov** [fastify/help#3]
#### What are you trying to achieve or the steps to reproduce?

Imagine I have a plugin, which decorates fastify instance with method, which I want to use as `beforeHandler` afterwards.

This is an example of the test which works:
```js
const server = require('fastify')();

// imagine it decorates the server with `beforeDecorator`
server.register(require('../index'), {});

server.register((fastify, opts, next) => {
	// eslint-disable-next-line no-unused-vars
	fastify.get('/protected', {
		beforeHandler: [fastify.beforeDecorator()]
	}, async (request, reply) => ({
		access: 'granted',
	}));
	next();
});

await server.ready();
// server.inject()
```

#### What was the result you received?
If I omit the plugin wrapper for the route registration
```js
const server = require('fastify')();


server.register(require('../index'), {});

server.get('/protected', {
	beforeHandler: [server.keycloakVerify()]
}, async (request, reply) => ({
	access: 'granted',
}));

await server.ready();
// server.inject()
```

I'll receive this:
```
server.keycloakVerify is not a function
```

meaning that plugin was not yet able to decorate the server.
In addition, I can not wait till the server is ready, since you can not add routes afterwards.

```
Cannot add route when fastify instance is already started!
```

#### What did you expect?
I expect there is a way to register the routes right away, not wrapping them into the plugin EVEN if the decorator is added from the plugin.

What do you think about it?

Regards,

#### Context

* *node version*: 8.9
* *fastify version*: 1.1.1
* *os*: Mac
* *any other relevant information*:

**Comment by mcollina** [comment]
You can use `fastify.after()`:

```js
const server = require('fastify')();

server.register(require('../index'), {});
server.after(function () {
  server.get('/protected', {
	beforeHandler: [server.keycloakVerify()]
  }, async (request, reply) => ({
	access: 'granted',
  }));
});

await server.ready();
// server.inject()
```

Side note, a better pattern to handle authentication is defined in https://jrfom.com/posts/2018/03/07/fastify-story/.

Generally you should wrap your routes in plugins.

**Comment by PavelPolyakov** [comment]
Thanks @mcollina,

The documentation is missing `after`:
https://www.fastify.io/docs/v1.1.x/Server-Methods/

(actually it's mentioned there, but I think it's not that easy to connect all the points)
