### ISSUE TITLE
Protect an endpoint exposed by a plugin

### ISSUE THREAD

**Issue by KidkArolis** [fastify/help#30]
#### What are you trying to achieve or the steps to reproduce?

I'm trying to combine `fastify-bearer-auth` with `fastify-metrics` with little luck.

This doesn't work as it protects the entire app with a token, but I want to only limit it to /metrics endpoint:

```js
const bearerAuth = require('fastify-bearer-auth')
const metrics = require('fastify-metrics')

app.register(bearerAuth, { keys: [config.metrics.secret] })
app.register(metrics, { blacklist: '/metrics', endpoint: '/metrics' })

// my regular routes
app.get('/my-stuff', handle)
```

This doesn't work as the metrics plugin can no longer see the requests in my app since it's scoped now:

```js
const bearerAuth = require('fastify-bearer-auth')
const metrics = require('fastify-metrics')

app.register(async function (app) {
  app.register(bearerAuth, { keys: [config.metrics.secret] })
  app.register(metrics, { blacklist: '/metrics', endpoint: '/metrics' })
})

// my regular routes
app.get('/my-stuff', handle)
```

I don't see a way to compose these plugins together, does that mean the only way is to open up their code and merge them that way?

**Comment by KidkArolis** [comment]
Did this for now, but wondering if there's a more elegant way:

```js
const bearerAuth = require('fastify-bearer-auth')
const metricsAuth = bearerAuth.internals.factory({ keys: [config.metrics.secret] })
if (env === 'production') {
  app.addHook('preHandler', (req, res, next) => {
    if (req.req.url.startsWith('/metrics')) {
      metricsAuth(req, res, next)
    } else {
      next()
    }
  })
}
```

**Comment by mcollina** [comment]
How about this:

``` js
const bearerAuth = require('fastify-bearer-auth')
const metrics = require('fastify-metrics')

app.register(async function (app) {
  app.register(bearerAuth, { keys: [config.metrics.secret] })
  app.register(routes)
})

app.register(metrics, { blacklist: '/metrics', endpoint: '/metrics' })

async function routes (app) {
  // my regular routes
  app.get('/my-stuff', handle)
}
```

**Comment by KidkArolis** [comment]
Thanks for responding! Really appreciate it. Been actually enjoying using fastify quite a bit.

Your suggestion would work if i wanted to protect my route but leave metrics unprotected.

Im trying to do the opposite, protect the metrics endpoint which is created internally by the metrics plugin.

Feels like the plugins dont compose that way. Or rather, the metrics plugin is quite special in that it needs to know about top level scope. I guess the metrics plugin could perhaps take the top level scope as an optional option, although doesnt feel like idiomatic fastify. But also what i did perhaps is just fine?

**Comment by mcollina** [comment]
Just swap them:

```js
const bearerAuth = require('fastify-bearer-auth')
const metrics = require('fastify-metrics')

app.register(async function (app) {
  app.register(bearerAuth, { keys: [config.metrics.secret] })
  app.register(metrics, { blacklist: '/metrics', endpoint: '/metrics' })
})

app.register(routes)

async function routes (app) {
  // my regular routes
  app.get('/my-stuff', handle)
}
```

**Comment by KidkArolis** [comment]
But now, the metrics plugin is scoped and therefore doesn’t observe lifecycle events from any of my routes, right?

**Comment by mcollina** [comment]
Oh, now I understand, you should disable the metrics endpoint, and define your own, like so:

```js
const bearerAuth = require('fastify-bearer-auth')
const metrics = require('fastify-metrics')

app.register(metrics, { blacklist: '/metrics', endpoint: false })


app.register(async function (app) {
  app.register(bearerAuth, { keys: [config.metrics.secret] })

     fastify.route({
        url: endpoint,
        method: 'GET',
        schema: {hide: true},
        handler: (_, reply) => {
          reply.type('text/plain').send(app.metrics.client.register.metrics());
        },
      });

})

app.register(routes)

async function routes (app) {
  // my regular routes
  app.get('/my-stuff', handle)
}
```

(I've not tested this, check fastify-metrics source code, and maybe open an issue there - it's not one of the officially supported plugins)

**Comment by KidkArolis** [comment]
Yes! That's the one. Ok, that makes sense, should have read the metrics code more carefully to spot those `fastify.decorate` calls. I'll give this a go, thanks!
