### ISSUE TITLE
Using generics with "RouteShorthandOptionsWithHandler" object

### ISSUE THREAD

**Issue by suchcodemuchwow** [fastify/help#300]
After reading [using-generics](https://www.fastify.io/docs/latest/TypeScript/#using-generics) I tried:

![Imgur](https://i.imgur.com/P7Sk3CL.png)

It works well with route method handler but it gives an error with the RouteShorthandOptionsWithHandler. I am not really experienced in Typescript so I might miss some point or is it an actual bug ?

**Comment by L2jLiga** [comment]
What is signature of `usersController.create` ?

**Comment by suchcodemuchwow** [comment]
It is RouteShorthandOptionsWithHandler and looks like that 
```typescript
const create: RouteShorthandOptionsWithHandler = {
    schema:{...}
    handler: async(req,res)=>{...}
}
```

**Comment by L2jLiga** [comment]
I think you can try this:

```typescript
const create = {
  schema: <Route schema>{},
  handler: async (request:FastifyRequest<{ Body: IUser }>, reply: FastifyReply) => {}
}
```

**Comment by suchcodemuchwow** [comment]
Ohh great definitely it's gonna work 👍🏽  Haven't even thought
