### ISSUE TITLE
what is the different between fastify-error and fastify-warning，which should i choose to deal with http error 

### ISSUE THREAD

**Issue by radiorz** [fastify/help#301]
what is the different between fastify-error and fastify-warning，which should i choose to deal with http error

**Comment by radiorz** [comment]
also  can i use @hapi/boom with fastify，i am so confused，please help me

**Comment by L2jLiga** [comment]
- [`fastify-warning`] is for fastify internal usage first of all, you can use it in your code to generate warnings (which are actually strings) and emit them accross your app (by using `process.emitWarning` as it said in README.
- [`fastify-error`] is almost same but it creates an `Error` objects and you have to throw them on your own whenever you want
- [`fastify-sensible`] is plugin which helps you to reply with http errors and this one is very simillar to [`@hapi/boom`]

[`fastify-warning`]: https://www.npmjs.com/package/fastify-warning
[`fastify-error`]: https://www.npmjs.com/package/fastify-error
[`fastify-sensible`]: https://www.npmjs.com/package/fastify-sensible
[`@hapi/boom`]: https://www.npmjs.com/package/@hapi/boom

**Comment by jsumners** [comment]
> * [`fastify-warning`](https://www.npmjs.com/package/fastify-warning) is for fastify internal usage first of all

All of our published modules are designed to be used by anyone. We merely develop them for our own usage first.

**Comment by L2jLiga** [comment]
Yeah, I understand this :)
But I think it has quite specific use cases and first of all required in fastify, for issue's use case I would use fastify-sensible.

**Comment by radiorz** [comment]
thanks a lot  i will try fastify-sensible instead of @hapi/boom.
