### ISSUE TITLE
passport js support

### ISSUE THREAD

**Issue by borodadada** [fastify/help#302]
Hello, i can try use passport js google, 
```
fastify.get('/auth/google', passport.authenticate('google', { scope: ['https://www.googleapis.com/auth/plus.login'] }));
```

error

{"statusCode":500,"error":"Internal Server Error","message":"next is not a function"}

passport js - is express? i need add express server? or ?

fastify-passport Status Alpha. Pre-any-release

**Comment by mcollina** [comment]
Use https://github.com/fastify/fastify-passport.

**Comment by borodadada** [comment]
thx man fastify-express work fine!
