### ISSUE TITLE
how can i save logs to database ，are there any plugins?

### ISSUE THREAD

**Issue by radiorz** [fastify/help#303]
systemlogs when user do something

**Comment by delvedor** [comment]
You should not save the logs in a db in the same process, as it will slow down your server.
Fastify should always log to stdout or to a file.
You can then pipe the Fastify process to a pino transport (such as https://github.com/pinojs/pino-elasticsearch) and rely on it for sending logs to an external db.
For example:
```
node index.js | pino-elasticsearch --node https://user:pwd@localhost:9200
```
If you are using Elasticsearch, you can also use [elastic beats](https://www.elastic.co/beats/).

**Comment by radiorz** [comment]
maybe i can use a middleware to deal with logs,my project isnt a huge stuff.

**Comment by radiorz** [comment]
i write a simple plugin (onSend handler) so that i can save logs now. because my project is small,it is ok right now.
