### ISSUE TITLE
Invalidate point-of-view complied template cache programmatically?

### ISSUE THREAD

**Issue by lanyusan** [fastify/help#304]
#### What are you trying to achieve or the steps to reproduce?

I was working with point-of-view and marko engine. I found out after I updated template, the view engine wouldn't recompile the template. The server has to be restarted.

And it is a requirement  not only for development, but also production. My use case is to allow web page author to edit template online and a render sever, which I am trying to develop with point-of-view, should re-render the template.

**Is there a way to invalidate point-of-view compiled template cache programatically so updated template would be recompiled?**

#### What was the result you received?

Updated template wasn't recompiled when refreshing.

#### What did you expect?

Updated template should be used to generate the page when refresh page.

#### Context

* *node version*: 14.5
```
    "fastify": "^3.7.0",
    "fastify-static": "^3.3.0",
    "marko": "^4.23.9",
    "point-of-view": "^4.6.0"
```

* *os*: Linux

**Comment by mcollina** [comment]
I don't think this feature is implemented in point-of-view. Would you like to send a PR?

(I would not really recommend templates to be recompiled dynamically as you are likely exposing yourself to security issues).

**Comment by lanyusan** [comment]
I have looked at the code. It looks marko engine bypassed your cache. It is a bug of marko loader. I may raise a pr to marko instead.
