### ISSUE TITLE
Random Default value when register schema

### ISSUE THREAD

**Issue by SamSalvatico** [fastify/help#308]
Hi, I have a field in a schema like this:
```js
products: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          product_id: { type: 'string' },
          product_quantity: { type: 'number' },
          present_for_certificate: { type: 'string' },
          child_id: { type: 'number', default: Math.random()*100 }
        }
      },
    }
```
So, when I put an array of products without child_id I expect to get a different child_id between them.
But the child_id is the same because I noticed that the value is generated when the schema is registered.

Is there a way to achieve this without needs to write code wherever I need a child id?

Thank you

* *fastify version*: ^3.7.0

**Comment by mcollina** [comment]
Check out https://www.npmjs.com/package/ajv. It's our validator. This might be supported there.
