### ISSUE TITLE
fastest path send file from server

### ISSUE THREAD

**Issue by borodadada** [fastify/help#309]
Hello, i write mini code for send file from server, first i try use for image files for site
```
    //get file from store
    fastify.get('/file/:name', async (request, reply) => {
        if( request.params.name ){
            const res = await store.getFile(request.params.name)
            if(res)
                reply.header('Content-Type', res.type).send(res.file)
        }
        reply.code(500).send({ 'code 500': "nobody's home" })
    });
```
For open file - fs.existsSync

Question: it's fast? or plugin static + folder more fast ? I think this method more useful

**Comment by mcollina** [comment]
I recommend to use `fastify-static` instead. Serving files properly is _complex_.

**Comment by borodadada** [comment]
thank you
