### ISSUE TITLE
how can i use fastify-routes  for sub routes(2seperate children routes)

### ISSUE THREAD

**Issue by radiorz** [fastify/help#310]
### index.js
 const routes = require('./routes')
  routes(fastify).forEach((route, index) => {
 fastify.route(route)
### routes/index.js
// map routes
  const modulesRouter = [user, activationcode,CALog,SystemLog].map(create => create(fastify))
  return modulesRouter.reduce((total, item) => {
    total.push(...item)
    return total
  }, [])
### user.js
module.exports = (fastify) => {
  return [
    {
      method : 'GET',
      url    : '/api/users',
      handler: userController.getUsers,
      schema : documentation.getUsersSchema,
      preValidation: [fastify.authenticate]
    },
}

**Comment by mcollina** [comment]
This is not really clear, what would you like to achieve?

**Comment by radiorz** [comment]
Thank you for your reply.I am new to fastify. I want to separate routes into files, such as users and products. Do I need fastify-routes? The document tell me that fastify-routes is a way to map routes,what is it? how can i use it? I really need a example to reference.

**Comment by mcollina** [comment]
fastify-routes is needed to pretty-print routes. It's normally not needed in any applications.
