### ISSUE TITLE
I try fastify-sensible to replace boom ，but how can i use it to deal with all error？

### ISSUE THREAD

**Issue by radiorz** [fastify/help#311]
such as 
controller.js

```
const getusers = async  function (req) {
  ...
  try {
  ... 
  if(!id){
    throw this.httpErrors.notFound('id not found')
  }
  if( otherstuff){
   throw this.httpErrors.conflict('xxx conflict')
  }
...
}
catch(err){
  // when  i use boom before
   boom.boomify(err)
  //how to use sensible to deal with different error  
}
```

**Comment by radiorz** [comment]
//how to use sensible to deal with different error  in "catch"

**Comment by L2jLiga** [comment]
Hi there! Can you quickly describe what you want achieve inside `catch` block?

**Comment by radiorz** [comment]
thanks for reply. I want to reply error【throw this.httpErrors.notFound('id not found') and throw this.httpErrors.conflict('xxx conflict'),】，if i boom.boomify (err) it will return correctly the some error。

**Comment by L2jLiga** [comment]
fastify can handle errors itself, so if you throw some of http errors then response will have appropriate status code and body, example:

*status code*: 409
*reponse body*: `{"statusCode":409,"error":"Conflict","message":"xxx conflict"}`


In case you need customize response body you can disable [custom error handler](https://github.com/fastify/fastify-sensible#custom-error-handler) in fastify-sensible options and write your own.
In case you need an extra steps to proceed error you can rely on properties such as `statusCode` or `status`, for example `conflict`  error properties: `{ status: 409, statusCode: 409, message: 'xxx conflict', expose: true }`

**Comment by radiorz** [comment]
`const changePassword = async function(req, reply) {
  try {
    const { username } = req.params
    const model = req.body
    const { password, newpassword, comfirmpassword } = model
    let user = await User.findOne({ where: { username, password } })
    if (!user) {
      // 404
      throw this.httpErrors.notFound("user not found or password didnt match")
    } else if (comfirmpassword !== newpassword) {
      // 409
      throw this.httpErrors.conflict("comfirm password didnt match new password")
    } else {
      const update = await User.update(
        { password: newpassword },
        { where: { username } }
      )
      if (update[0]===1){
        return {
          statusCode:'200',
          message:'changed password successfully',
        }
      }else{
        throw this.httpErrors.badRequest('unknown req errors')
      }
    }
  } catch (err) {
    throw Boom.boomify(err)
  }`
such as this ,there will be many different errors when using apis,i try to deal with it using  if else to throw an error ,but there are some errors I did not foresee，so i use try catch to deal with all errors to insure that all error should be returned。

**Comment by radiorz** [comment]
`const changePassword = async function(req, reply) {
  try {
    const { username } = req.params
    const model = req.body
    const { password, newpassword, comfirmpassword } = model
    let user = await User.findOne({ where: { username, password } })
    if (!user) {
      // 返回404 信息
      throw this.httpErrors.notFound("user not found or password not correctly")
    } else if (comfirmpassword !== newpassword) {
      // 返回409 信息错误
      throw this.httpErrors.conflict("comfirm password didnt match new password")
    } else {
      const update = await User.update(
        { password: newpassword },
        { where: { username } }
      )
      if (update[0]===1){
        return {
          statusCode:'200',
          message:'change password successfully',
        }
      }else{
        throw this.httpErrors.badRequest('unknown req errors')
      }
    }
  } catch (err) {
    throw Boom.boomify(err)
  }
}`

**Comment by radiorz** [comment]
```
const changePassword = async function(req, reply) {
  try {
    const { username } = req.params
    const model = req.body
    const { password, newpassword, comfirmpassword } = model
    let user = await User.findOne({ where: { username, password } })
    if (!user) {
      // 404
      throw this.httpErrors.notFound("user not found or password not correctly")
    } else if (comfirmpassword !== newpassword) {
      // 409
      throw this.httpErrors.conflict("comfirm password didnt match new password")
    } else {
      const update = await User.update(
        { password: newpassword },
        { where: { username } }
      )
      if (update[0]===1){
        return {
          statusCode:'200',
          message:'change password successfully',
        }
      }else{
        throw this.httpErrors.badRequest('unknown req errors')
      }
    }
  } catch (err) {
    throw Boom.boomify(err)
  }
}
```

**Comment by radiorz** [comment]
are there any good ways to deal with those errors,an middleware or plugin?

**Comment by mcollina** [comment]
It's really unclear what you are trying to achieve. Please make a full example.

**Comment by radiorz** [comment]
@mcollina  changePassword is an route's handler for changing user's password. in this handler,there are three main arguments :'password (the old one),new password,comfirmpassword', if the password isn't correct ,reply 404error.if the new password isn't equal to comfirmpassword,reply 409error.
and if there were other errors ,let boom to deal with it, it would return a 500 error .
but now i dont want to use boom and i'd like to use fastify-sensible. how can i do to deal with  all these errors with fastify-sensible.

any other good suggestions is great.

**Comment by L2jLiga** [comment]
I think omiting `try { } catch (err) { }` is ok option, fastify will threat such errors as 500 with "Something went wrong" message

**Comment by mcollina** [comment]
Just removing `Boom` would do what you want to achieve.

**Comment by radiorz** [comment]
thanks. i remove the Boom and try catch structure, it still work . the message is a little different but i think it's ok
