### ISSUE TITLE
How to respond with the default ajv validation response without making it a human readable string? 

### ISSUE THREAD

**Issue by vajahath** [fastify/help#312]
Fastify doc [says](https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md#validation-messages-with-other-validation-libraries):
> Fastify's validation error messages are tightly coupled to the default validation engine: errors returned from ajv are eventually run through the schemaErrorsText function which is responsible for building human-friendly error messages.

I'd like to respond with the same ajv response rather than responding with a human-readable string. Is there a way to bypass this human-readable text conversion easily?

I looked at the [schemaErrorFormatter](https://github.com/fastify/fastify/blob/master/docs/Server.md#schemaerrorformatter). But it only supports `Error` return types.
```ts
(errors: FastifySchemaValidationError[], dataVar: string) => Error
```
I tried
```ts
const opt: FastifyServerOptions = {
  schemaErrorFormatter(errors, dataVar) {
    const myerr = errors.map(e => ({ datapath: e.dataPath, msg: e.message }));
    return myerr;
  },
}
```
Because it only supports `Error` return types, the above snippet won't ts compile.

**Comment by Eomm** [comment]
The `schemaErrorFormatter` aims to build a good `message` output, so it is not what you need.

In your case you need to define your own error handler:

```js
  app.setErrorHandler(function (error, request, reply) {
    if (error.validation) {
      reply.send(error.validation)
      return
    }

    const res = reply.raw
    if (res.statusCode >= 500) {
      reply.log.error({ req: reply.request.raw, res: res, err: error }, error && error.message)
    } else if (res.statusCode >= 400) {
      reply.log.info({ res: res, err: error }, error && error.message)
    }
    reply.send(error)
  })
```

So the output will be:

```
[{"keyword":"enum","dataPath":".foo","schemaPath":"#/properties/foo/enum","params":{"allowedValues":["bar"]},"message":"should be equal to one of the allowed values"}]
```

I'm writing a blog post about error handling and customization 👍

**Comment by Eomm** [comment]
Just as follow up: [here all](https://dev.to/eomm/fastify-error-handlers-53ol) the error handling cases are explained

Closing
