### ISSUE TITLE
How to reply just a 200 statusCode in async/await handler without using `reply` object?

### ISSUE THREAD

**Issue by erfanium** [fastify/help#313]
https://www.fastify.io/docs/latest/Routes/#promise-resolution

Here it says that I can't return `undefined` value in async/await handler, so I need to use `reply` object: `reply.send()`
Is there any way to send 200 empty response without use `reply` object?

**Comment by erfanium** [comment]
Something like would be great:

```js
const OK = symbol.for('ok')

async handler() {
   return OK
}
```

**Comment by mcollina** [comment]
You can return an empty string.

**Comment by erfanium** [comment]
@mcollina 
It doesn't behave exactly like `reply.send()`, It will add `content-type: text/plain; charset=utf-8` header to response that not good, I don't want to reply any content

**Comment by mcollina** [comment]
The current implementation is the result of a series of tradeoffs, I'll be extremely hesitant in adding anything at this point in time.

Adding one `if` is simple, adding 10 will make everything harder to implement.

Calling `reply.send()` seems a very good tradeoff. `reply` is available in all handlers and it's very simple to use:

```js
function handler (req, reply) {
  await myFunc()
  return reply.send()
}
```

This seems very simple already.

**Comment by erfanium** [comment]
@mcollina I solved my problem in another way, but I think this problem needs further investigation, for example in `onSend` hook, `null` used to [clear](https://www.fastify.io/docs/latest/Hooks/#onsend) the payload. but it request handler, `null` is a valid json!
In fact, ‍‍`null` has different meanings in different places, I think with a global symbol, we can solve this issue better

**Comment by jsumners** [comment]
That sounds like a separate issue. We should be defaulting "empty" declarations that could be sent to the client to `undefined`.
