### ISSUE TITLE
Are there any best practices or examples  using fastify to build a admin project api server.

### ISSUE THREAD

**Issue by radiorz** [fastify/help#314]
Although there are some of  fastify server examples, but most of them are still using the old version of fastify,and they even don't update anymore ...
Are there any best practices or examples  using fastify to build a admin project api server which can help us to learn fastify quickly.
if there are any forums or github project ,please contact me . thanks a lot

**Comment by mcollina** [comment]
There is not much at this point. Any good contributions will be welcome.

**Comment by catalinpit** [comment]
Hey! Could you tell me what you refer to by "admin project API"? Thank you!

**Comment by radiorz** [comment]
@catalinpit  which means backstage pages for  managing serves.

**Comment by Ethan-Arrowood** [comment]
@radiorz it would be great to see one of these examples recreated using fastify. You could even make use of something like `fastify-express`
