### ISSUE TITLE
fastify-nextjs loop in console

### ISSUE THREAD

**Issue by acg-thp** [fastify/help#316]
#### You have already researched for similiar issues?
It's not uncommon that somebody already opened an issue or in best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/fastify/fastify/issues) at first before submitting a new one.

(I found one stackoverflow but not same issue posted)
https://stackoverflow.com/search?q=%5Bfastify%5D+nextjs&s=a53d83a7-d20d-44cc-8e97-59d70c1430e1

https://stackoverflow.com/questions/61543938/fastify-with-nextjs

IF needed I can try write up the test and have it fail but this may not be a bug, it probably is something wrong with how I have something configured?

#### What are you trying to achieve or the steps to reproduce?

Describe your issue here, include as much detail as neccessary to reproduce the issue
or implement a missing functionality. If you are reporting a bug, you will get faster response
if you submit a pull request with a failing test.

```js
fastify
  .register(require('fastify-nextjs'))
  .after(() => {
    fastify.next('/index')
  })
```
^-- Iv added this and similar approaches into either a plugin or in the add your own code section on the app.js in the example fastify application

#### What was the result you received?
Loaded env from DIRSTACK\.env (Repeats this, DIRSTACK is just my directory stack )
#### What did you expect?
To launch?

#### Context
Running Fastify Server attempting to add nextjs plugin into the application but cannot launch server.

* *node version*: 12.18.2
* *fastify version*: >=3.0.0
* *os*: Windows
* *any other relevant information*: I am unsure how to use the fastify-nextjs plugin, are then any examples using it with the default fastify project example?

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by mcollina** [comment]
Can you please include a full server?

**Comment by acg-thp** [comment]
I can upload the source but I have not checked it into version control yet if that is what you mean?

```json
{
  "name": "centural_systems",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "test": "tap test/**/*.test.js",
    "start": "fastify start -l info app.js",
    "dev": "fastify start -w -l info -P app.js",
    "build": "next build"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "db-migrate": "^0.11.11",
    "db-migrate-pg": "^1.2.2",
    "dotenv": "^8.2.0",
    "fastify": "^3.0.0",
    "fastify-autoload": "^3.0.2",
    "fastify-cli": "^2.0.2",
    "fastify-nextjs": "^5.1.0",
    "fastify-plugin": "^2.0.0",
    "fastify-postgres": "^3.2.0",
    "fastify-swagger": "^3.5.0",
    "next": "^10.0.1",
    "pg": "^8.5.0",
    "pg-promise": "^10.7.3",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  },
  "devDependencies": {
    "tap": "^14.0.0"
  }
}
```
Ill get the source into version control and add to a repository soon and drop a link.

**Comment by Eomm** [comment]
What is your stacktrace?
