### ISSUE TITLE
can i use fastify.assert to replace if else and fastify.httpErrors

### ISSUE THREAD

**Issue by radiorz** [fastify/help#319]
in fastify.sensible 
we have two different ways to reply errors.
fastify.httpErrors you need to use “if else” to Judge whether to continue the execution
but when using fastify.asserts ,you dont need to use if else so that the code will be much more beautiful.
so i'd like to use asserts.

but some comments says that asserts is just used for debug the error which won't happen(illegal error).
if at release version,maybe i shouldn't use asserts to deal with the error (normal error).
can i use assert to replace if else and fastify.httpErrors.

**Comment by mcollina** [comment]
Which comments? Can you add links?

**Comment by radiorz** [comment]
[like this](https://stackoverflow.com/questions/1081409/why-should-i-use-asserts)
in my language , they say C++ will remove asserts in release version.
but with nodejs,i dont need to 'build' a release version,so should i use asserts to throw errors,or are there any ways to deal with errors-throwing without if else.

**Comment by mcollina** [comment]
I would recommend you to not draw conclusion from a languange (c++) and port it to another (JS). 

use httpErrors if you want to have specific http error codes in the reponse. Using an assert will lead to a 500 to the client.

**Comment by radiorz** [comment]
thanks for your advice.
