### ISSUE TITLE
newbie: second example in home page, doesnt work as expected

### ISSUE THREAD

**Issue by andreaneri** [fastify/help#32]
#### You have already researched for similiar issues?
nope

#### What are you trying to achieve or the steps to reproduce?
curl -D - http://localhost:3000/

```js
// Wrap code in markdown source tags
const fastify = require('fastify')({
  logger: true
})

fastify.route({
  method: 'GET',
  url: '/',
  schema: {
    // request needs to have a querystring with a `name` parameter
    querystring: {
      name: { type: 'string' }
    },
    // the response needs to be an object with an `hello` property of type 'string'
    response: {
      200: {
        type: 'object',
        properties: {
          hello: { type: 'string' }
        }
      }
    }
  },
  // this function is executed for every request before the handler is executed
  beforeHandler: async (request, reply) => {
    // E.g. check authentication
  },
  handler: async (request, reply) => {
    return { hello: 'world' }
  }
})

const start = async () => {
  try {
    await fastify.listen(3000)
    fastify.log.info(`server listening on ${fastify.server.address().port}`)
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()
```

#### What was the result you received?
HTTP/1.1 200 OK
content-type: application/json; charset=utf-8
content-length: 17
Date: Thu, 29 Nov 2018 07:59:44 GMT
Connection: keep-alive
#### Context
i expect kind of:
HTTP/1.1 400 BAD REQUEST

becouse,
schema there is a required parameter in query string;

* *node version*: v10.5.0
* *fastify version*: 2.0.0-rc.0
* *os*: Mac
* *any other relevant information*:

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by lgertel** [comment]
I think that it's because query strings are optional. Have you tried with params instead?
Here we always pass information via body, instead other options...

**Comment by nwoltman** [comment]
Object properties are optional by default. You can require certain properties to be present by using the [`required`](https://github.com/epoberezkin/ajv/blob/master/KEYWORDS.md#required) keyword:

```js
querystring: {
  type: 'object',
  properties: {
    name: { type: 'string' }
  },
  required: [ 'name' ]
},
```

**Comment by andreaneri** [comment]
@nwoltman your tip solved, thanks

**Comment by nwoltman** [comment]
Great to hear @andreaneri 😄

(Also, could you close this issue? I don't seem to have the power to do that.)

**Comment by andreaneri** [comment]
done
