### ISSUE TITLE
could i use yaml in my fastify project？i just want to complete my schema more quickly？

### ISSUE THREAD

**Issue by radiorz** [fastify/help#320]
as we all know，we can use json schema to do the validation etc..
but can i use yaml to do this things?

**Comment by zekth** [comment]
You can uses `js-yaml` to convert your yaml to json.

see : https://github.com/nodeca/js-yaml

**Comment by jsumners** [comment]
If writing JSON is too arduous, I suggest using https://github.com/fastify/fluent-schema. If you write your schemas in yaml, you'll need to convert them to JSON _before_ you submit them to the JSON Schema validator. When using baseline Fastify, that means converting before you write your handler definitions. That would be really clunky in my opinion.
