### ISSUE TITLE
Is there a way to yield route to next one?

### ISSUE THREAD

**Issue by lanyusan** [fastify/help#321]
#### What are you trying to achieve or the steps to reproduce?

I have a use case where a url might be matched and handled by multiple routes. I wish a route handler could yield it to next one when it decides it doesn't wand to do it.

For example

/a/b/c -> could be an exact match
/a/:id/c -> match anything.

The first route handler could decide if it wishes to handle it and then yield to a more general one.

I couldn't find out from doc.

Thanks

**Comment by L2jLiga** [comment]
Hi, fastify uses [`find-my-way`](https://github.com/delvedor/find-my-way) for routing and I also don't see possibility to yield route to next matched. What I can suggest here is to use kind of strategy here:

```javascript
const handlerB = (req, res) => { }
const handlerForId = (req, res) => { }

fastify.get('/a/b/c', (req, res) => iWantHandleThis(req) ? handlerB(req, res) : handlerForId(req, res))
fastify.get('/a/:id/c', (req, res) => handlerForId(req,res))
```
