### ISSUE TITLE
Ability to pass route handling to the next matching route (like express next()/next('route'))

### ISSUE THREAD

**Issue by mgcrea** [fastify/help#322]
I'm looking for a way to add some kind of auth middleware to a whole subset of routes.

Tried to add a global matcher without route handler, but typescript won't let me, eg.

```js
fastify.all(
  '/users',
  { preValidation: someCustomPreValidation() }
);
// [...other /users protected routes]
```

And I did not find in the docs how to specify a handler that pass to the next matching route without replying, eg. something like:

```js
fastify.all(
  '/users',
  { preValidation: someCustomPreValidation() },
  (request, reply) => {
     reply.next(); 
  }
);
// [...other /users protected routes]
```

Is it something that is possible today with fastify?

**Comment by Eomm** [comment]
> Is it something that is possible today with fastify?

Yes, but I think you need to switch mindset from express.
I would suggest exploring the plugin [system doc](https://www.fastify.io/docs/latest/Plugins-Guide/#register) and my [Encapsulation chapter](https://dev.to/eomm/fastify-demo-goes-to-production-499c) to get all the insight info.

Regarding your issue there is a couple of solution to archive it:

- using the [`onRoute`](https://www.fastify.io/docs/latest/Hooks/#onroute) hook where you will be able to push the `preValidation` function only to those `routeOptions.routePath` that start with the subset url you want
- create an encapsulated context where you register an instance hook like:

```js
fastify.register((instance, opts, done) => {
  instance.addHook('preValidation', (request, reply, done) => {
    // only the routes defined with `instance` will run this hook
    done()
  })
  instance.get('/users', ()=>{ return 'hello' })
  done()
})

fastify.get('/cars', ()=>{ return 'hello' }) // this will not trigger the hook
```

Notice that:

- preValidation run before any JSON schema validation [Checkout the lifecycle doc to spot these details](https://www.fastify.io/docs/latest/Lifecycle/)
- `fastify.all` register an endpoint for every HTTP method, it does not any meta manipulation. For these tasks you will find out that hooks will let you do what you need

**Comment by mgcrea** [comment]
Thank you for such a quick and thorough reply!

Really like how powerful hooks are, glad to leave my express mindset behind 👍
