### ISSUE TITLE
dir array in fastify-autoload

### ISSUE THREAD

**Issue by YuriFontella** [fastify/help#324]
#### What are you trying to achieve or the steps to reproduce?

I looked in the documentation for something where I could just autoload my root folder.

```js
app.register(autoload, {
  dir: [
    path.join(__dirname, 'src/plugins'),
    path.join(__dirname, 'src/routes')
  ]
})
```

#### What was the result you received?

The "path" argument must be of type string. Received an instance of Array

#### What did you expect not to do?

```js
app.register(autoload, {
  dir: path.join(__dirname, 'src/plugins')
})

app.register(autoload, {
  dir: path.join(__dirname, 'src/routes')
})
```

#### Context

* *node version*: 14.15
* *fastify version*: 3.8.0
* *os*: Linux

**Comment by RafaelGSS** [comment]
Can you provide a reproduction code?

**Comment by mcollina** [comment]
This is more a massive feature it seems. Autoload does not support this.

**Comment by YuriFontella** [comment]
@RafaelGSS my intention was to know if there was a way to declare the autoload register only once.

**Comment by RafaelGSS** [comment]
I get it. Autoload does not support this. This feature is to prevent some bug or is it only to turn the code more _readable_?

**Comment by Ethan-Arrowood** [comment]
@YuriFontella the reason we make you call it once for each directory is that there are a collection of configuration options that get tied to the autoload. Bundling all of that together is not something the library supports

**Comment by YuriFontella** [comment]
@RafaelGSS exactly, but now I understand the reasons, thank you @Ethan-Arrowood.
