### ISSUE TITLE
Is there a way to split app logs from access logs

### ISSUE THREAD

**Issue by Sidd27** [fastify/help#329]
I m trying to split app logs with access logs
app logs are the one which dev put it implicitly
access logs are any request which is made to access the server

**Comment by RafaelGSS** [comment]
Hi, can you explain better your goal? preferably with code

**Comment by jsumners** [comment]
I think it's pretty clear. He wants to log access logs in the traditional Apache HTTPD manner (http://httpd.apache.org/docs/current/logs.html#accesslog) that are routed to a different destination from the application level logs. One _could_ use `pino-multi-stream` for that, but I think it's far better to work with more current logging practices. Ship all logs to the same destination in a parseable format (JSON), and then filter logs according to what you want to see.
