### ISSUE TITLE
Send index.html if no route is found

### ISSUE THREAD

**Issue by BofEmptiness** [fastify/help#33]
Hi!

How can i send index.html file on any request that is not defined previosly?

In express i just added something like this to the end of code:
```js
fastify.route({
  method: 'GET',
  url: '*',
  handler: (req, res) => {
    res.sendFile(path.join(__dirname, '../public/index.html'))
  }
})

index.html handles the routing with react router, but i need to send index.html somehow on first request

**Comment by delvedor** [comment]
Hi!
For sure! You just need to configure the [`notFoundHandler`](https://www.fastify.io/docs/latest/Server/#setnotfoundhandler) :)
```js
'use strict'

const fastify = require('./fastify')()

fastify.get('/', async (req, reply) => ({ hello: 'world' }))

fastify.setNotFoundHandler((request, reply) => {
  reply.type('text/html')
  reply.send('<html><body>hello</body></html>')
})

fastify.listen(3000)
```

This will be used automatically if the 404 is generated by the router, if yoiu are using Fastify v2 and you want to invoke it also from your route handlers you need to use `reply.callNotFound()`.

**Comment by BofEmptiness** [comment]
It's not working @delvedor 
fastify.setNotFoundHandler((req, res) => {
  reply.type('text/html')
  res.sendFile(path.join(__dirname, '../public/index.html'))
})

if i just sendFile, i get 404 not found :/

**Comment by delvedor** [comment]
Can you tell us a little bit more of your working environment?

- Node.js version
- Fastify version
- Installed plugins

**Comment by BofEmptiness** [comment]
Client react

package.json:
```
{
  "name": "server",
  "version": "1.0.0",
  "main": "server.js",
  "scripts": {
    "start": "nodemon server.js"
  },
  "dependencies": {
    "fastify": "^1.13.0",
    "fastify-static": "^0.14.0",
    "node-fetch": "^2.3.0",
    "pg": "^7.6.1",
    "winston": "^3.1.0",
    "winston-daily-rotate-file": "^3.5.1"
  }
}
```

server:
```
const fastify = require('fastify')({
  ignoreTrailingSlash: true,
  caseSensitive: false, // for rotes like /Foo or /foo, all route params like /foo/:name will be lowercased as well
  http2: true,
  https: {
    allowHTTP1: true,
    key: fs.readFileSync('./tls/cert.key'),
    cert: fs.readFileSync('./tls/cert.pem')
  }
})

fastify.listen(settings.env.port, 'localhost', (err, address) => {
  err
    ? logger.error({
        info: 'fastify server error 1',
        address: address,
        message: err
      })
    : console.log(
        `Server started`
      )
})
```

Static:
```
fastify.register(require('fastify-static'), {
  root: path.join(__dirname, '../public')
})
```


// 
```
fastify.setNotFoundHandler((req, res) => {
console.log('working')
  res
    .code(200)
    .sendFile(path.join(__dirname, '../public/index.html'))
})
```

Static files working and index loading if i get '/' route.
If i get another route i get 'working in console', but in browser i see:
https://lh3.googleusercontent.com/-pEmnZXqaWe4/XAEutwOmOzI/AAAAAAAACUw/aR41QBi8u-sQJf7JF72iBHuSHgpcltxBQCHMYCw/s0/TeamViewer_2018-11-30_15-36-06.png

If i do like this, it's working and i can see object in browser with 200 status code:
```
fastify.setNotFoundHandler((req, res) => {
  res.send({hi: 'max'})  //it's works
})
```

I think there is some problem with sendFile, but don't understand what is it.

**Comment by delvedor** [comment]
Can you paste a single file with the minimum amount of code to reproduce the issue? Thanks!

**Comment by BofEmptiness** [comment]
@delvedor yes, please:

```
const fs = require('fs'),
  path = require('path')

const fastify = require('fastify')()

fastify.listen(3000, 'localhost', (err, address) => {
  console.log('Server started')
})

fastify.register(require('fastify-static'), {
  root: path.join(__dirname, '../public')
})

fastify.setNotFoundHandler((req, res) => {
  console.log('called but not send index html')
  res.code(200).sendFile(path.join(__dirname, '../public/index.html'))
})

```

and any index.html in public folder:
```
<!DOCTYPE html>
<html>
  <head>
    <base href="/" />
  </head>

  <body>
    <div >HI!</div>
  </body>
</html>
```

**Comment by delvedor** [comment]
`fastify-static` by default will try to match any request, you should add the `prefix` option to fix that issue.

This example works:
```js
const path = require('path')
const fastify = require('fastify')()

fastify.listen(3000, 'localhost', (err, address) => {
  if (err) throw err
  console.log('Server started')
})

fastify.register(require('fastify-static'), {
  root: path.join(__dirname, './public'),
  prefix: '/public'
})

fastify.setNotFoundHandler((req, res) => {
  res.code(200).sendFile('index.html')
})
```

**Comment by BofEmptiness** [comment]
@delvedor thanks.

It's working like this:
res.code(200).sendFile('index.html')

But doesn't like this:
res.code(200).sendFile('../public/index.html')
and
res.code(200).sendFile(path.join(__dirname, '../public/index.html'))

Strange for me :/
