### ISSUE TITLE
Alternative to connect-mongodb-session for fastify

### ISSUE THREAD

**Issue by workflow2** [fastify/help#331]
Hi, there is an alternative to connect-mongodb-session for fastify, with express I used to use this package to store my session to the db. How I can do the same with fastify?

**Comment by L2jLiga** [comment]
Hi @workflow2,

You can take a look on [middie](https://github.com/fastify/middie) it's middleware engine for fastify which allows you to use express middleware

**Comment by workflow2** [comment]
> Hi @workflow2,
> 
> You can take a look on [middie](https://github.com/fastify/middie) it's middleware engine for fastify which allows you to use express middleware

Thanks @L2jLiga I know about middie, but as far as i know this plugin is made for express it may create problems, i prefer a full fastify solution instead of using express middlewares

**Comment by workflow2** [comment]
I've found that this package here https://github.com/SerayaEryn/fastify-session uses the same stores that can be used on express as stated under the store option:

> Compatible to stores from express-session.
