### ISSUE TITLE
how to install fastify-cli by yarn?

### ISSUE THREAD

**Issue by radiorz** [fastify/help#332]

**Comment by L2jLiga** [comment]
Hi there, some description would be definitely helpful.

If you want to install fastify-cli globally via yarn then you should ensure that yarn binaries directory in PATH environment variable
If you want to install it to the project then just use `yarn add`

Refs:
https://classic.yarnpkg.com/en/docs/cli/global/
https://dev.to/c33s/yarn-global-package-install-location-16p4
https://stackoverflow.com/questions/40317578/yarn-global-command-not-working
