### ISSUE TITLE
how to make multiple route to 1 direct index.js route

### ISSUE THREAD

**Issue by ahsandev2019** [fastify/help#334]
hello i have multiple route, my api used by several app, i separate it to multiple file like 
mobile.js, desktop.js , main.js, dataabc.js , then i require it on index.js(server) with some prefix too.

how to make it all my route registered in index.js inside folder route?  
so i can import only 1 file on index.js

this is my folder 
![Screenshot from 2020-12-05 10-17-30](https://user-images.githubusercontent.com/67857968/101232302-86160c00-36e3-11eb-966b-7fdbad646477.png)

**Comment by L2jLiga** [comment]
Hello, you can try [`fastify-autoload`](https://github.com/fastify/fastify-autoload) for this

**Comment by ahsandev2019** [comment]
can you give me example?

**Comment by aseerkt** [comment]
@ahsandev2019  Did you get it working?
