### ISSUE TITLE
How to export swagger documentations to markdown？

### ISSUE THREAD

**Issue by radiorz** [fastify/help#335]
i want to export swagger documentations. how to do to achive this goal?

**Comment by Ethan-Arrowood** [comment]
@radiorz have you checked out [fastify-swagger](https://github.com/fastify/fastify-swagger)?

**Comment by radiorz** [comment]
@Ethan-Arrowood  hello.i use fastify-swagger to created swagger docs automatically.but i didnt find "markdown"  in its project
![image](https://user-images.githubusercontent.com/24271959/102155706-0e9c6580-3eb7-11eb-84ba-00571e7094e6.png)

**Comment by L2jLiga** [comment]
Hi @radiorz, are you looking for something like this?
https://github.com/adobe/jsonschema2md

**Comment by radiorz** [comment]
thanks for reply @L2jLiga  can json schema2md be used in .js files？
