### ISSUE TITLE
Accessing fastify.log in a nextJS page

### ISSUE THREAD

**Issue by BritainRox** [fastify/help#337]
#### What are you trying to achieve or the steps to reproduce?

I am starting out with fastify-nextjs and would like to reuse decorators and plugins that a registered on the fastify instance, and logger for fastify instance in page components. 

```js
export default class Home extends React.Component {

    static async getInitialProps(params) {
		fastify.log.debug('Loading initial properties');
	}
	// more code
}
```

#### Context

* *node version*: 14
* *fastify version*: >=3.0.0
* *os*: Windows
* *any other relevant information*:

**Comment by mcollina** [comment]
Unfortunately that's not possible at the moment.
