### ISSUE TITLE
How to add AJV keywords properly? 

### ISSUE THREAD

**Issue by yantrab** [fastify/help#338]
#### What are you trying to achieve or the steps to reproduce?

Hi , i trying to trim all the strings in the schema - 
i added the keyword-
```
    const app = fastify({
      ajv: {
        customOptions: {
          keywords: {
            notEmptyString: {
              validate: (_, data, parentData, path, o, u) => {
                o[u] = data.trim();
                return o[u].length > 0;
              }
            }
          }
        }
      }
    });
```
and adding ```schema["notEmptyString"] = true;``` to the schema.
 
it is work perfect, but i got  warning from AJV -     meta-schema not available

#### What was the result you received?
    console.warn
      meta-schema not available

      at Ajv.validateSchema (node_modules/fastify/node_modules/ajv/lib/ajv.js:170:17)
      at Ajv._addSchema (node_modules/fastify/node_modules/ajv/lib/ajv.js:307:10)
      at Ajv.compile (node_modules/fastify/node_modules/ajv/lib/ajv.js:113:24)
      at Ajv.validateKeyword (node_modules/fastify/node_modules/ajv/lib/keyword.js:138:43)
      at Ajv.addKeyword (node_modules/fastify/node_modules/ajv/lib/keyword.js:33:10)
      at addInitialKeywords (node_modules/fastify/node_modules/ajv/lib/ajv.js:474:10)
      at new Ajv (node_modules/fastify/node_modules/ajv/lib/ajv.js:72:22)
      at ValidatorCompiler (node_modules/fastify/lib/schema-compilers.js:30:15)

source code is [here](https://github.com/yantrab/strongly)
#### Context

* *node version*: 13
* *fastify version*:"^3.9.2"
* *os*: Ubuntu
* *any other relevant information*:

**Comment by Eomm** [comment]
The repo has a lot of logic and it is not straightforward to debug it.
Could you add a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

Maybe [`fastify-autoload`](https://github.com/fastify/fastify-autoload) could help you

**Comment by yantrab** [comment]
Hi @Eomm , just run this code:
import fastify from "fastify";
```
const app = fastify({
  ajv: {
    customOptions: {
      keywords: {
        notEmptyString: {
          validate: (_, data, parentData, path, o, u) => {
            o[u] = data.trim();
            return o[u].length > 0;
          }
        }
      }
    }
  }
});

app.get("/a", { schema: { body: { date: { notEmptyString: true, type: "string" } } } }, () => {});
app.listen(4000);

```
and you will can see the "meta-schema not available" warning in the log

**Comment by Eomm** [comment]
I think you need to provide a custom `ajv` instance and call the [`ajv.addKeyword`](https://github.com/ajv-validator/ajv/blob/v6/CUSTOM.md)

There is not a [`keywords` option](https://github.com/ajv-validator/ajv/tree/v6#options) as input

**Comment by rporcon** [comment]
It's (now ?) possible to add custom keyword with the `keywords` array in the fastify [ajv option](https://www.fastify.io/docs/latest/Server/#ajv).
For example below I added the `even` keyword:

```javascript
const ajv = {
  keywords: [
    {
      keyword: 'even',
      type: 'number',
      schemaType: 'boolean',
      code(cxt) {
        const { data, schema } = cxt;
        const op = schema ? `!==` : `===`;
        cxt.fail(`${data} %2 ${op} 0`);
      }
    }
  ],
  plugins: [require('ajv-formats'), [require('ajv-keywords'), ['transform']]]
};
```

I use fastify 3.21.0 and AJV 8 ([see Ajv 8 as default schema validatior in the doc](https://www.fastify.io/docs/latest/Server/#ajv-8-as-default-schema-validator))

In your case since you only wanted to trim the results, you could also have use the plugin [ajv-keywords](https://github.com/ajv-validator/ajv-keywords) and add the `transform` keyword, which then you can use in your schema to trim: `transform: ["trim"]` (see ajv-keywords doc for more details)
