### ISSUE TITLE
custom versioning header for all endpoints without routing penalty

### ISSUE THREAD

**Issue by shakeelosmani** [fastify/help#341]
#### What are you trying to achieve or the steps to reproduce?
Is it possible to add a custom header for every route in API for example that reads the node js package version and exposes that as the header value. Something like X-Api-Version and value set to 1.0.0 reading from package.json. Specifically when routes are defined in this manner:
```js
import { FastifyInstance } from 'fastify';
import { HealthCheckController } from './controllers/health-check/HealthCheckController';
import { AccountController } from './controllers/account/AccountController';

const Router = async (fastify: FastifyInstance) => {
  fastify.register(HealthCheckController, { prefix: '/api/v1/health-check' });
  fastify.register(AccountController, { prefix: '/api/v1/account' });
};

export { Router };
```

* *node version*: 4,5,6,7,8,9
* *fastify version*: >=0.37.0
* *os*: Mac, Windows

**Comment by mcollina** [comment]
You can add an header in a hook:

```js
app.addHook('onRoute', async (req, reply) => {
  reply.header('x-api-version', '42')
})
```
