### ISSUE TITLE
Async post not working 

### ISSUE THREAD

**Issue by philosofonusus** [fastify/help#343]
#### What are you trying to achieve or the steps to reproduce?

POST request on route only pending 

```js
    fastify.post("/token", async (request, reply) => {
        try {
            const {token} = request.body
            if (!token) return null;
            const verified = jwt.verify(token, config.get("jwtSecret"));
            if (!verified) return null;
            const user = await User.findById(verified.id);
            if (!user) return null;
            const {name, email, role, favourites, id} = user
            return reply.code(200).send({name, email, role, favourites, id})
        } catch (e) {
            return reply.code(400).send(null)
        }
    });
```

#### What was the result you received?

[1] {"level":30,"time":1609881403187,"pid":13170,"hostname":"tentacle","reqId":1,"req":{"method":"POST","url":"/api/auth/token","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":46842},"msg":"incoming request"}
and pending on the request
#### What did you expect?
returning some data
#### Context

* *node version*: 4,5,6,7,8,9
* *fastify version*: >=0.37.0
* *os*: Mac, Windows
* *any other relevant information*:

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by mcollina** [comment]
I don't think returning null the way you are doing is achieving anything.

**Comment by philosofonusus** [comment]
> I don't think returning null the way you are doing is achieving anything.
Its written in my code on the client side

If i send some request body to route its always pending

**Comment by philosofonusus** [comment]
```
    fastify.post("/token", async (req, res) => {
        try {
            const {token} = req.body
            if (!token) return null
            const verified = jwt.verify(token, config.get("jwtSecret"));
            if (!verified) return null
            const user = await User.findById(verified.id);
            if (!user) return null
            const {name, email, role, favourites, id} = user
            return {name, email, role, favourites, id}
        } catch (e) {
            return null
        }
    });
```
I did that but it still doesnt work

**Comment by mcollina** [comment]
```

fastify.post("/token", async (req, res) => {
            const {token} = req.body
            if (!token) return 'no token'
            const verified = jwt.verify(token, config.get("jwtSecret"));
            if (!verified) return 'not verified'
            const user = await User.findById(verified.id);
            if (!user) return 'no user'
            const {name, email, role, favourites, id} = user
            return {name, email, role, favourites, id}
    });

```

(There are many more things that should be fixed here, I'm just focusing on one thing at a time).

**Comment by philosofonusus** [comment]
I agree
I have just removed body parser, and it started working

**Comment by philosofonusus** [comment]
Anyway, thank you for your responses.
