### ISSUE TITLE
Microservices API Gateway

### ISSUE THREAD

**Issue by admapop** [fastify/help#345]
#### You have already researched for similiar issues?
Yes.

#### What are you trying to achieve or the steps to reproduce?

I am doing some research on fast, reliable and flexible JS backend frameworks to replace our current implementation with [Express Gateway](https://www.express-gateway.io).

I've skimmed the documentation but at first glance it wasn't clear if one can build a microservice/proxy API gateway with Fastify. Specifically, the paradigm of Pipelines, Policies, Proxy (request and response forwarding between client and private API).

I will most likely try to build something similar with Fastify, but any tips or information on it beforehand would be very helpful!

🙏🏻

Thanks !

**Comment by jsumners** [comment]
That is what https://github.com/fastify/fastify-http-proxy is for.
