### ISSUE TITLE
Type "number" in schema allows null values by fastify, but not Ajv.

### ISSUE THREAD

**Issue by vajahath** [fastify/help#348]
## 🐛 Bug Report
I want not to allow `null` values for a `body` property.
Please see the following simple snippet in which I tried to compare results of fastify and ajv **for the same schema and input**:

```js
const fastify = require("fastify")({});

const Ajv = require("ajv");
const ajv = new Ajv();

const bodySchema = {
  type: "object",
  required: ["age"],
  properties: {
    age: {
      type: "integer",
    },
  },
};

const payload = {
  age: null, // <- setting age to null
};

// ajv result
console.log("AJV validation: ", ajv.validate(bodySchema, payload));

// fastify result
fastify.route({
  method: "POST",
  url: "/",
  schema: {
    body: bodySchema,
  },
  handler: async (req) => {
    console.log("Inside handler", req.body);
    return { insideHandler: true };
  },
});

fastify
  .inject({
    method: "POST",
    url: "/",
    payload,
  })
  .then((res) => {
    console.log("resp status", res.statusCode);
    console.log("res body", res.payload);
  })
  .catch((err) => console.log("err", err));

```
#### Results
Bad result:
```js
const payload = { age: null };
```
```
AJV validation:  false ❌
Inside handler { age: 0 }
resp status 200 ✅
res body {"insideHandler":true}
```
If ajv fails, I thought fastify will also fail.

Good results:
```js
const payload = { age: 3 };
```
```
AJV validation:  true ✅
Inside handler { age: 3 }
resp status 200 ✅
res body {"insideHandler":true}
```

```js
const payload = { age: 'meow' };
```
```
AJV validation:  false ❌
resp status 400 ❌
res body {"statusCode":400,"error":"Bad Request","message":"body.age should be integer"}
```

So looks like fastify internally changes the `age` to `0`. How can I prevent this and return 400 with built in validation?

## Your Environment

- *node version*: 14.5
- *fastify version*: 3.10.1
- *os*: Windows

**Comment by mcollina** [comment]
The Fastify _serializer_ is [`fast-json-stringify`](http://npm.im/fast-json-stringify): it is not a validator in any form or fashion: it assumes _you_ are generating is correct. It does all it can to make the data you are passing conform to the schema, e.g. coercing `null` to `0`. If it's not possible to shape the data, it will throw: however it is very lenient and not spec-compliant.

This is useful to remove unwanted fields and make sure the output conforms to a given output. It's also faster than JSON.stringify.

**Comment by L2jLiga** [comment]
I think issue here with default AJV settings in fastify: it enabled coercion hence ajv coerce null on input to 0, you need to disable it

**Comment by vajahath** [comment]
Thanks friends.
So for clarity, can we say this: _Fastify **first** serializes the data and **then** validates it_?
(I'm assuming this because if the data would have gone through ajv first, it would have thrown, which is not the case here.)

https://www.fastify.io/docs/latest/Validation-and-Serialization/ While reading it at least I got intuition that first fastify first validates and then serializes. Because, throughout the docs serialization comes second to validation.

**Comment by mcollina** [comment]
I'm sorry, I made a mess explaining things and reading your example.

> Fastify first serializes the data and then validates it?

No, it's not correct.

You can find the lifecycle of a request in https://www.fastify.io/docs/latest/Lifecycle/.

Fastify receives the input, it validates it, then it executes the handler which produces a result body. Ajv is the validator.

As @L2jLiga said, We pass a few options to Ajv, you can find them documented in https://www.fastify.io/docs/latest/Server/#ajv. Specifically, we pass in `coerceTypes`, which coerces the types passed if possible.

**Comment by vajahath** [comment]
Done! It's very clear now. Thanks everyone ⭐ !
I'm closing this.
