### ISSUE TITLE
Hi can you help fastify.route execute the function twice

### ISSUE THREAD

**Issue by frontenddima** [fastify/help#349]
#### Hi can you help fastify.route execute the function twice
I can't understand why the function is executed 2 times. I posted the entire function in which this error occurs. I would be very grateful for your help!

* *node version*: v14.15.1
* *fastify version*: >=3.9.1
* *os*: Windows
* *any other relevant information*:

**code debug link to video -> [https://drive.google.com/file/d/1dYCk3QgAx36nAF2UGKByDgH7dip-xDnP/view?usp=sharing](url)

Photo link controller 
 [https://drive.google.com/file/d/1EJ4imtJYGrPfDWoDBMpVJtwMj1yxjrhf/view?usp=sharing](url)
[https://drive.google.com/file/d/1raJCmlqESeiGzAYcTc0tuqMMuxcWaRPJ/view?usp=sharing](url)
[https://drive.google.com/file/d/1rn5e0AdfJIlliCOKzwOth94Hd0HEG_G9/view?usp=sharing](url)

**Comment by zekth** [comment]
Please share the code and context in the issue.

**Comment by frontenddima** [comment]
> Please share the code and context in the issue.

Hi thanks for the answer solved the problem :_) in preHandler it was necessary to pass done
