### ISSUE TITLE
What do you prefer using fastify-cli or start it form scratch?

### ISSUE THREAD

**Issue by mandaputtra** [fastify/help#35]
What do you prefer for big app and long run apps?

**Comment by mandaputtra** [comment]
How to pass fastify params on the handler?

```
module.exports = async function(fastify, opts) {
  fastify.route({
    method: "GET",
    url: "/login",
    handler: AuthController.login
  });

  fastify.route({
    method: "GET",
    url: "/register",
    handler: (req, res) => {
      fastify.someSupport();
    }
  });
};
```

**Comment by mcollina** [comment]
We recommend not to split the route definition from the function itself. Those are tightly coupled and belong together.

What do you mean with

> How to pass fastify params on the handler?

---

Anyway, if you use a normal function you'll have the fastify instance as `this`:

```js
async function login (request, reply) => {
  return this.someSupport();
};
module.exports.login = login;
```

**Comment by mandaputtra** [comment]
Owh dont know if can access fastify instant using this. nice then. I'm using fastify CLI but dont know how to pass the fastify instance. 

so you prefer to handle the logic on route? and not split them? basically im. just split it with in other file. So i cam had more clear route on the service folder on fastify CLI.

**Comment by mandaputtra** [comment]
What do you prefer using fastify-cli or start it from scratch?

**Comment by mcollina** [comment]
I typically prefer from scratch, following a similar approach of fastify-cli.

**Comment by mandaputtra** [comment]
nice, I've do it from starch but end up like my express app. thanks

**Comment by delvedor** [comment]
Personally, I prefer to start with `fastify-cli` and then eject if needed :)
