### ISSUE TITLE
Custom error messages with ajv-errors

### ISSUE THREAD

**Issue by frodoe7** [fastify/help#350]
#### What are you trying to achieve or the steps to reproduce?
I have a single POST endpoint

```javascript
  fastify.post('/register', {
    schema: {
      summary: 'Register a new user',
      description: "Use this route to register a new user",
      tags: ['user'],
      body: {
        type: 'object',
        required: ['name'],
        properties: {
          name: {
            type: 'string'
          },
        },
        errorMessage: {
          required: {
            name: 'Your name is required',
          }
        }
      },
    }
```

I call the endpoint without providing a name

#### What was the result you received?
I got this response
body should have required property 'name'

#### What did you expect?
the expected result to get my custom error message
Your name is required

#### Context
based on the [docs](https://www.fastify.io/docs/latest/Validation-and-Serialization/#validation)

> add custom error messages for each property of a schema by supplying custom AJV options.

```javascript
const fastify = Fastify({
  ajv: {
    customOptions: { jsonPointers: true },
    plugins: [
      require('ajv-errors')
    ]
  }
})
```

because , I use a ready generated template from Fastify-cli
looks I have to pass these options within the command ([Reference](https://github.com/fastify/fastify-cli#options))
but , there's no a clear way to pass these ajv options within Fastify-cli

* *node version*: 10.15.1
* *fastify version*: >=3.0.0
* *os*: Mac
* *fastify-cli version*:2.7.0

**Comment by mcollina** [comment]
Unfortunately you'd have to eject from fastify-cli as it's not possible to pass those options through.

**Comment by frodoe7** [comment]
@mcollina , It was not the answer that I hope to read - looks , I will have to write this custom functionality by hand
thank you anyway.

**Comment by mcollina** [comment]
It would be great to add some of this to fastify-cli - what's missing is somebody to develop the feature.
