### ISSUE TITLE
Response schema vs explicit pruning out props in response object

### ISSUE THREAD

**Issue by naseemkullah** [fastify/help#353]
Hello!

I love fastify's built-in schema validation.

But I have not always used response schemas in the past and have the habit of removing properties from an object before returning it (if required).

Can I now 100% rely on response schema validation to prune the unwanted object props for me (except in cases where pruning is conditional of course)?

**Comment by L2jLiga** [comment]
Hi there,

I think you can rely on Fastify serializer, at least I use it in one of my projects in production :)

```javascript
const FastJsonBuild = require('fast-json-stringify')
const stringify = FastJsonBuild({ type: "object", properties: { message: { type: "string" } } })

const result  = stringify({ message: "test", additional: "test" })

console.log(result) // {"message":"test"}
```

**Comment by naseemkullah** [comment]
Thanks @L2jLiga 

That's great, doing both the declarative (schema) and imperative (pruning in code) does feel like belt+suspenders, will only use schema for this moving forward!
