### ISSUE TITLE
Why 'preValidation' hook is triggered also on not existing routes?

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [fastify/help#359]
Hi,
I detected a strange behaviour on a hook I've created. I was wondering if this is the expected outcome.
The hook declared is one of type `preValidation` and has authentication purpouses. When I'm calling an endpoint on my API that has not a specific route declared, the hook gets triggered anyway causing errors different from the 404 expected from the client. Is there a way to declare hooks only on valid routes in my API? Is this the expected behaviour?

**Comment by RafaelGSS** [comment]
On Fastify, the 404 routes have an entire lifecycle than a common route. I'd recommend you to add a [handler 404](https://www.fastify.io/docs/v1.14.x/Server/#setnotfoundhandler) and declare your `preValidation` hook in the next scope.

**Comment by giovanni-bertoncelli** [comment]
Ok thanks.
I have something like this:
```javascript
 const app = Fastify(config.fastify);

  // registering /404 handler
  app.setNotFoundHandler({
    preValidation: (req, reply, done) => {
      // your code
      done();
    },
    preHandler: (req, reply, done) => {
      // your code
      done();
    }
  }, function(request, reply) {
    console.error('404!!');
   return Promise.reject(404);
    // Default not found handler with preValidation and preHandler hooks
  });

  // registering /plugins folder
  await app.register(autoload, {
    dir: path.join(__dirname, 'plugins')
  });

  // registering /routes folder in /api
  await app.register(autoload, {
    dir: path.join(__dirname, 'routes'),
    ignorePattern: /methods/gi,
    options: { prefix: `/${config.server.prefix}` }
  });
```

In the folder `plugins` I have that preValidation hook and in the `routes` folder the defined routes.
This is not working... Why is that?

**Comment by Eomm** [comment]
> This is not working... Why is that?

Because you are in two different contexts: it is like two independent folders that don't share any data.
[Here more details on the encapsulation model](https://github.com/fastify/fastify/blob/master/docs/Encapsulation.md)

**Comment by giovanni-bertoncelli** [comment]
@Eomm Sorry, I haven't understand. So what it would be like?
