### ISSUE TITLE
FST_ERR_SCH_SERIALIZATION_BUILD Failed building the serialization schema for route due to error schema is invalid: data.properties should be object

### ISSUE THREAD

**Issue by ponez** [fastify/help#361]
#### You have already researched for similiar issues?
Yes

#### What are you trying to achieve or the steps to reproduce?

Hi, I'm trying to use fluent-schema (fluent-json-schema) in my route like this 
```ts
app.patch(`/${root}/item/:itemId`,{schema: item_schema},items);
```
my schema looks like this 
```ts
import schema from "fluent-json-schema";
const body = schema
  .object()
  .prop(
    "itemTitle",
    schema.string().required()
  );

const response = schema
  .object()
  .prop(
    "payload",
    schema
      .object()
      .prop("itemTitle",schema.string().required())
  );

export item_schema = {
  body,
  response,
};
```

#### What was the result you received?
when I use response schema it throws an error like this
```ts
FST_ERR_SCH_SERIALIZATION_BUILD Failed building the serialization schema for route due to error schema is invalid: data.properties should be object
```
#### What did you expect?
well I expected it to work just fine as i used non fluent schema before 
```ts
  const response = {
    response: {
      type: "object",
      properties: {
        payload: {
          type: "object",
          properties: {
            itemTitle: { type: "string" },
          },
          required:["itemTitle"]
        },
      },
    },
  };
```
#### Context

* *node version* :v14.15.1
* *fastify version*: >=3.9.2
* *os*:  Windows

**Comment by Eomm** [comment]
The response object in the route should have the HTTP status code:

```
response: {
  '2xx': {
      type: "object"
      .....
}
```

**Comment by ponez** [comment]
> The response object in the route should have the HTTP status code:
> 
> ```
> response: {
>   '2xx': {
>       type: "object"
>       .....
> }
> ```

I don't think that's the case because 
```ts
  const response = {
    response: {
      type: "object",
      properties: {
        payload: {
          type: "object",
          properties: {
            itemTitle: { type: "string" },
          },
          required:["itemTitle"]
        },
      },
    },
  };
```
works just fine same goes for fluent schema body my problem is the response WITH fluent schema , if I use non-fluent schema for response app works just fine!

**Comment by mcollina** [comment]
Can you try with:

```js
const response = schema
  .object()
  .prop(
    "payload",
    schema
      .object()
      .prop("itemTitle",schema.string().required())
  ).valueOf()
```

**Comment by ponez** [comment]
> Can you try with:
> 
> ```js
> const response = schema
>   .object()
>   .prop(
>     "payload",
>     schema
>       .object()
>       .prop("itemTitle",schema.string().required())
>   ).valueOf()
> ```

I did and still getting the same err 
```
FST_ERR_SCH_SERIALIZATION_BUILD
```
and json output 
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "payload": {
      "type": "object",
      "properties": {
        "itemTitle": {
          "type": "string"
        }
      },
      "required": [
        "itemTitle"
      ]
    }
  }
}
```

**Comment by mcollina** [comment]
@ponez unfortunately I do not think https://github.com/fastify/help/issues/361#issuecomment-773145038 and https://github.com/fastify/help/issues/361#issuecomment-773128864 can be both valid at the same time. Which one it is? The schema are the same.

I highly recommend you to post full examples that we can run to reproduce the problem.

**Comment by ponez** [comment]
> @ponez unfortunately I do not think [#361 (comment)](https://github.com/fastify/help/issues/361#issuecomment-773145038) and [#361 (comment)](https://github.com/fastify/help/issues/361#issuecomment-773128864) can be both valid at the same time. Which one it is? The schema are the same.
> 
> I highly recommend you to post full examples that we can run to reproduce the problem.

My bad [#361 (comment)](https://github.com/fastify/help/issues/361#issuecomment-773128864) generated json is from 
```
const response = schema
  .object()
  .prop(
    "payload",
    schema
      .object()
      .prop("itemTitle",schema.string().required())
  );
```
not that non-fluent that I mentioned, non-fluent is valid and working but fluent isn't and [#361 (comment)](https://github.com/fastify/help/issues/361#issuecomment-773145038) JSON is generated from that code you gave me

**Comment by mcollina** [comment]
I highly recommend you to post full examples that we can run to reproduce the problem.

**Comment by ponez** [comment]
here I made an example for what I'm trying to achieve 
```
import fastify from "fastify";
import schema from "fluent-json-schema";

const app = fastify({ logger: true });
const root = "v4";

const body = schema
  .object()
  .prop("itemTitle", schema.string().maxLength(255).minLength(10).required());
const response = schema
  .object()
  .prop(
    "payload",
    schema.object().prop("itemTitle", schema.string().required())
  )
  .valueOf();
/* 
const response = schema
  .object()
  .prop(
    "payload",
    schema
      .object()
      .prop("itemTitle", schema.string())
  );

*/

const workingResponse = {
  // this one works just fine without any problemo
  response: {
    type: "object",
    properties: {
      payload: {
        type: "object",
        properties: {
          itemTitle: { type: "string" },
        },
        required: ["itemTitle"],
      },
    },
  },
};

const itemTitleSchema = {
  body,
  response,
};
console.log(
  JSON.stringify(response.valueOf(), undefined, 2), // for generating json schema
  JSON.stringify(body.valueOf(), undefined, 2)
);

app.patch(
  `/${root}/item/:itemId`,
  {
    schema: itemTitleSchema,
  },
  (req, res) => {
    const info = req.body;
    console.log(info);
    res.code(200);
    //just a simple controller for the example code
  }
);
export async function start() {
  try {
    await app.listen(3000);
  } catch (error) {
    app.log.error(error);
    process.exit(1);
  }
}
```

**Comment by mcollina** [comment]
You are missing the `response` wrapper:

```
const response = {
  response: schema
    .object()
    .prop(
      "payload",
      schema.object().prop("itemTitle", schema.string().required())
    )
    .valueOf()
}
```
