### ISSUE TITLE
Merging schemas with ajv-merge-patch ignores required field

### ISSUE THREAD

**Issue by ZigaStrgar** [fastify/help#362]
#### You have already researched for similiar issues?
Yes, but haven't found something similar.

#### What are you trying to achieve or the steps to reproduce?
Using `fastify`, with `ajv-merge-patch` plugin and when I'm trying to merge two schemas only properties get merged, without `required` array. The source is "typed" while `with` is being used with `$ref`.

```js
// app.js
const app = fastify({
    logger: true,
    ajv: {
         plugins: [
            require('ajv-merge-patch'),
        ],
    },
});

// routes.js
fastify.addSchema({
    $id: 'credentials',
    type: 'object',
    required: ['email', 'password'],
    properties: {
        email: { type: 'string', format: 'email' },
        password: { type: 'string', minLength: 8 },
    },
});

fastify.route({
   method: 'POST',
    url: '/register',
    schema: {
        body: {
            $merge: {
                source: {
                    type: 'object',
                    required: ['firstName', 'lastName'],
                    properties: {
                        firstName: { type: 'string', minLength: 2 },
                        lastName: { type: 'string', minLength: 2 },
                    },
                },
                with: {
                   $ref: 'credentials#',
                },
            },
         },
    },
    handler: controller.register,
});
```

#### What was the result you received?
When submitting the request with the missing `firstName` or `lastName` there is no `required` error thrown, while for `email` and `password` there is.

```json
// Request body data
{"email": "jane.doe@email.com", "password":"password", "lastName":"Doe"} // No errors
```

But if you set the `firstName` or `lastName`, but the `minLength` rule fails, an error is thrown with the proper message.

```json
// Request body data
{"email": "jane.doe@email.com", "password":"password", "lastName":"Doe", "firstName": "J"} // 400 Bad Request - body.firstName should NOT be shorter than 2 characters, body should pass "$merge" keyword validation
```

#### What did you expect?
With any of the mentioned parameters missing I would expect the `required property '[property name]'` error.

#### Context

* *node version*: 15.7.0
* *fastify version*: ^3.9.2
* *os*: Mac
* other plugins used: `fastify-auth`

**Comment by Eomm** [comment]
Could you add the `ajv` configuration code?

**Comment by ZigaStrgar** [comment]
@Eomm I've updated the issue with `app.js` code, and I am pasting the same thing here.

```js
// app.js
const app = fastify({
    logger: true,
    ajv: {
         plugins: [
            require('ajv-merge-patch'),
        ],
    },
});
```

**Comment by Eomm** [comment]
I would check an `ajv` snippet code to understand if this is the expected behaviour by the plugin

Your whole setup looks good!

**Comment by ZigaStrgar** [comment]
I've gone through the documentation of `ajv` and they follow the RFC for JSON Merge and it is by design to overwrite arrays. Thank you for your help and insights!
