### ISSUE TITLE
 [Homebridge UI] Error: Cannot find module 'fastify'

### ISSUE THREAD

**Issue by dcaccount** [fastify/help#364]
Hello,

I have upgraded one Homebridge plugin and now the log shows following error that I cannot solve.

> [4/2/2021, 08:39:37] [Homebridge UI] Error: Cannot find module 'fastify'
feb 04 08:39:37 rpinvr131 homebridge[561]: Require stack:
feb 04 08:39:37 rpinvr131 homebridge[561]: - /usr/lib/node_modules/homebridge-config-ui-x/dist/main.js
feb 04 08:39:37 rpinvr131 homebridge[561]: - /usr/lib/node_modules/homebridge-config-ui-x/dist/bin/fork.js
feb 04 08:39:37 rpinvr131 homebridge[561]: [4/2/2021, 08:39:37] [Homebridge UI] Caught Unhandled Rejection Error :: Details Below
feb 04 08:39:37 rpinvr131 homebridge[561]: Error: Cannot find module 'fastify'
feb 04 08:39:37 rpinvr131 homebridge[561]: Require stack:
feb 04 08:39:37 rpinvr131 homebridge[561]: - /usr/lib/node_modules/homebridge-config-ui-x/dist/main.js
feb 04 08:39:37 rpinvr131 homebridge[561]: - /usr/lib/node_modules/homebridge-config-ui-x/dist/bin/fork.js
feb 04 08:39:37 rpinvr131 homebridge[561]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
feb 04 08:39:37 rpinvr131 homebridge[561]:     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
feb 04 08:39:37 rpinvr131 homebridge[561]:     at Module.require (internal/modules/cjs/loader.js:952:19)
feb 04 08:39:37 rpinvr131 homebridge[561]:     at require (internal/modules/cjs/helpers.js:88:18)
feb 04 08:39:37 rpinvr131 homebridge[561]:     at Object.76495 (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:99573:18)
feb 04 08:39:37 rpinvr131 homebridge[561]:     at __webpack_require__ (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:99732:42)
feb 04 08:39:37 rpinvr131 homebridge[561]:     at Object.48519 (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:79551:17)
feb 04 08:39:37 rpinvr131 homebridge[561]:     at __webpack_require__ (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:99732:42)
feb 04 08:39:37 rpinvr131 homebridge[561]:     at /usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:99760:18
feb 04 08:39:37 rpinvr131 homebridge[561]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:99761:12) {
feb 04 08:39:37 rpinvr131 homebridge[561]:   code: 'MODULE_NOT_FOUND',
feb 04 08:39:37 rpinvr131 homebridge[561]:   requireStack: [
feb 04 08:39:37 rpinvr131 homebridge[561]:     '/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js',
feb 04 08:39:37 rpinvr131 homebridge[561]:     '/usr/lib/node_modules/homebridge-config-ui-x/dist/bin/fork.js'

I would not like to reinstall Homebridge, can you please advise how to solve it?

Thanks,
Dan

**Comment by mcollina** [comment]
We don't have a clue of what homebridge is. I highly recommend you to contact them
