### ISSUE TITLE
Should AJV removeAdditional work?

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [fastify/help#368]
Hi,
I have a question: I've seen that the default options for the AJV validation plugin inside fastify include `removeAdditional: true` (see [docs](https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md#validator-compiler)). Maybe I've misunderstood the porpouse of this configuration key but when I try to use that the additional keys are not omitted from the result. I've seen this behaviour both with request and response validation, even with `additionalProperties(false)`. 

Here an example:

```javascript
const Fastify = require('fastify');
const autoload = require('fastify-autoload');
const path = require('path');
const S = require('fluent-json-schema').default;

async function build() {
  const app = Fastify();

  app.post('/', {
    body: S.object().prop('test', S.string()).additionalProperties(false),
    response: {200: S.object().prop('test', S.string()).additionalProperties(false)}
  }, (request, reply) => {
    console.log(request.body);
    return Promise.resolve(request.body)
  })

  return app;
}

async function main() {
  const app = await build();
  await app.listen(3000);
}

main()
```

Try a POST on the root of this server with a JSON object like `{"test": 1, "additional": 2}`, the `additional` key will be both present in the `req.body` and in the response.

**Comment by mcollina** [comment]
You found yourself a bug in fluent-json-schema.

Consider the following:

```js
const S = require('.')

console.log(S.object().additionalProperties(false).prop('test', S.string()).valueOf())
```

```json
{
  '$schema': 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  properties: { test: { additionalProperties: false, type: 'string' } }
}
```

vs

```js
const S = require('.')

console.log(S.object().prop('test', S.string()).additionalProperties(false).valueOf())
```

```json
{
  '$schema': 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  properties: { test: { additionalProperties: false, type: 'string' } }
}
```

**Comment by mcollina** [comment]
Can you please confirm that inverting the order actually fixes this?

**Comment by giovanni-bertoncelli** [comment]
Checking now.. In the meantime I think the comment below is wrong since the first statements, for me, results in:

```javascript
{
  '$schema': 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  additionalProperties: false,
  properties: { test: { type: 'string' } }
}
``` 

While the second it's the one I get too.

**Comment by giovanni-bertoncelli** [comment]
@mcollina I think that actually there is that bug on `fluent-json-schema`, but that is only a part of the whole problem since even moving the statement does not get the properties omitted...

Try with this:
```javascript

const Fastify = require('fastify');
const autoload = require('fastify-autoload');
const path = require('path');
const S = require('fluent-json-schema').default;

async function build() {
  const app = Fastify();

  // try movin  of the `.additionalProperties()` stmt
  // under the `.prop()`
  const body = S.object()
  .additionalProperties(false)
  .prop('test', S.string())

  const response = body;

  console.log(body.valueOf())

  app.post('/', {
    body,
    response: {200: response}
  }, (request, reply) => {
    console.log(request.body);
    return Promise.resolve(request.body)
  })

  return app;
}

async function main() {
  const app = await build();
  await app.listen(3000);
}

main()
```

**Comment by mcollina** [comment]
You need to wrap things inside a `schema` property:

```
  app.post('/', {
    schema: {
      body,
      response: {200: response}
    }
  }, (request, reply) => {
    console.log(request.body);
    return Promise.resolve(request.body)
  })
```

**Comment by giovanni-bertoncelli** [comment]
Well that's sure my mistake! 😆 
Now I'm able to reproduce the fluent schema bug and reverting the order for `additionalProperties` does the tricky..
Do you want me to open an issue?

**Comment by mcollina** [comment]
That would be amazing, thanks!
