### ISSUE TITLE
Integrate fastify with log4js which sends log to Graylog not working

### ISSUE THREAD

**Issue by nigam3008** [fastify/help#369]
I am trying to integrate log4js with Fastify wherein log4js will be sending logs to Graylog using GELF appended.
It looks like even after passing logger it not being used. Even after changing the logLevel in log4js, it is not reflecting the changes in Fastify.

```js

const log4js = require('./monitoring/logger');
const log = log4js.getLogger();
const fastify = require("fastify")({
    logger: log});

// Logger file

const log4js = require('log4js');

log4js.configure({
    appenders: {
        gelf: {
            type: '@log4js-node/gelf',
            facility: process.env.GRAYLOG_FACILITY,
            host: process.env.LOGGING_SERVER, // optional; default: 127.0.0.1
            port: process.env.LOGGING_PORT_UDP,
            customFields: {
                '_environment': process.env.ENVIRONMENT,
                '_instance': 'testapp',
                '_host': process.env.POD_NAME,
                'origin': "application",
                'node': process.env.POD_NAME,
                'server': process.env.POD_NAME,
                'instance': 'testapp',
                'environment': process.env.ENVIRONMENT
            }
        },
        console: {
            type: 'console'
        }
    },
    categories: {
        default: {
            appenders: ['gelf', 'console'],
            level: log4js.levels.ALL
        }
    }
});

module.exports = log4js;
```

#### What was the result you received?
When we are using the logger directly it is able to display logs and able to send logs to graylog. 
When we are using fastify.log it is logging to console but not sending logs to graylog.
When we trigger any URL, then logs are appearing in the console but not sending to graylog.

#### What did you expect?
The expectation is to display logs in both consoles and send them to Graylog.

#### Context

* *node version*: v14.15.5
* *fastify version*: >=3.11.0
* *os*: Mac, Windows, Linux

**Comment by mcollina** [comment]
We do not officially support log4js, nor graylog transport. I don't really have a clue on what it is going wrong.

**Comment by nigam3008** [comment]
It is my understanding that we can provide a custom logger in Fastify which satisfies the abstract-logging Logger interface. 

It is the responsibility of Log4j to transport logs to Graylog.
In this scenario, it seems that Fastify is not able to trigger a custom logger methods which in our case is log4js.

**Comment by jsumners** [comment]
Actually, the docs state that the logger must support specific methods, not that it must adhere to the `abstract-logging` interface -- https://www.fastify.io/docs/latest/Server/#logger

`log4js` does not provide a `child` method.

**Comment by lewispham** [comment]
Is there any chance that fastify will support log4js?

**Comment by mcollina** [comment]
it seems unlikely, however you could write an adapter.
