### ISSUE TITLE
Is there a benefit of using the fastify-auth plugin with a single authentication strategy?

### ISSUE THREAD

**Issue by bluenote10** [fastify/help#373]
I hope this is the right platform to ask a question like that...

The [fastify-auth](https://github.com/fastify/fastify-auth) plugin description states:

> This module does not provide an authentication strategy, but it provides a very fast utility to handle authentication (also multiple strategies) in your routes, without adding overhead.

This makes me wonder: Does the plugin provide a (performance?) benefit in a use case with only a single authentication strategy? 

If only a single authentication strategy is needed (i.e., no chaining with `and`/`or`) the natural solution would probably be to simply write a dedicated `preHandler` for that. The description suggests the plugin does something magical resulting in a lower overhead compared to a normal `preHandler`. Is that the case? Or does the "very fast" / "without overhead" mainly refer to the chaining case?

**Comment by mcollina** [comment]
> > This module does not provide an authentication strategy, but it provides a very fast utility to handle authentication (also multiple strategies) in your routes, without adding overhead.
> 
> This makes me wonder: Does the plugin provide a (performance?) benefit in a use case with only a single authentication strategy? 

Absolutely not, it does nothing magical.

> 
> If only a single authentication strategy is needed (i.e., no chaining with `and`/`or`) the natural solution would probably be to simply write a dedicated `preHandler` for that. The description suggests the plugin does something magical resulting in a lower overhead compared to a normal `preHandler`. Is that the case? Or does the "very fast" / "without overhead" mainly refer to the chaining case?

It mainly refer to the chaining case. FWIW, I recommend to use `onRequest`, not `preHandler`.

**Comment by bluenote10** [comment]
Okay perfect thanks, that clarifies it all!
