### ISSUE TITLE
[Help] fastify.validatorCompiler is null

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [fastify/help#374]
## 💬  Question here 

Is there a way to know exactly when `fastify.validatorCompiler` is not null and is ready? Since it seems not to be added through the decorate API and I have to use it internally for validation in a not-covered scenario sometimes I get the ajv instance, sometimes `null`... If there is no way how can I rely on the internal AJV instance of Fastify?

**Comment by jsumners** [comment]
Without an example to look at, all I can suggest is to explore the new https://www.fastify.io/docs/latest/Server/#schemacontroller option.

**Comment by giovanni-bertoncelli** [comment]
Mmm I can try to write a snippet:
```javascript
// myplugin.js
function plugin(fastify, opts, done) {
  fastify.decorate('customValidator', (objectToValidate, schema) => {
     const { validatorCompiler } = fastify;
     // there is no way to know if fastify.validatorCompiler is not null....
     const validator = validatorCompiler({
       schema
     });
    return validator(objectToValidate);
  })
}
```

**Comment by jsumners** [comment]
Your plugin would need to be registered after `fastify.setValidatorCompiler(aCompiler)`. I cannot assume you are doing that without a full minimal example. https://github.com/fastify/fastify/issues/2446 is a good example of showing the full context of an issue and keeping it narrow.

**Comment by Eomm** [comment]
The compilers are ready, after the ready event.

Here there are the tests that cover this behaviour:

https://github.com/fastify/fastify/blob/d1972a6ba6f06bd462f33dfd7a338eed969b51e5/test/schema-feature.test.js#L1074-L1077

This is needed because the ajv instance is built async and when needed and it is not created by default

**Comment by giovanni-bertoncelli** [comment]
Thank you @Eomm. I figured that out.
