### ISSUE TITLE
[HELP] How can I access current fastify instance anywhere

### ISSUE THREAD

**Issue by peixin** [fastify/help#375]
I am a new user of fastify.

I wan to use `fastify.config` or `fastify.log` in other file e.g. utils, service. and I don't want to pass the instance layer by layer to that file.

How can I do?
Thanks.

**Comment by RafaelGSS** [comment]
You should store the fastify/log reference in some struct/variable and just use it.

**Comment by peixin** [comment]
> You should store the fastify/log reference in some struct/variable and just use it.

Thanks Reply. 

I did follow this..  and the `struct/variable` must be assigned after `fastify.ready` hooks. otherwise other files will use to it prematurely

For example

```
// global-1.js
export default  { app: null }
```

```
// global-2.js
export const fastifyInstance = null;
```


```
// index.js
import Global from "./global-1.js";
import { fastifyInstance } from "./global-2.js";


fastify
  .register(require("fastify-env"), options)
  .register(require("./api"), { prefix: "/api" })
  .ready(() => {
    Global.app = fastify;
    fastifyInstance = fastify;
  });
```

```
//api.js
import Global from "./global-1.js";
import { fastifyInstance } from "./global-2.js";

function test() {
	console.log(Global.app.config); // ok
	console.log(fastifyInstance.config); // fastifyInstance is null, but I like this way
}

```


But I think this method is not elegant enough.. there is definitely a better solution. what are the best practice? like flask `current_app`?

**Comment by RafaelGSS** [comment]
Why you should use the fastify instance outside of HTTP land? I mean, you can just use `fastify.log` in every scope.

**Comment by peixin** [comment]
```javascript
// api/index.js

import utils from "./utils";

const testHandler = async (request) => {
  const { url, ts } = request.query;
  const text = await utils.getText(url, ts);
  return { text };
};

export default async (fastify)=> {
  fastify.get("/api", { schema:{...} }, testHandler);
};

```

```javascript
// api/utils.js
export const getText = async () => {
	fastify.log.info("something");
	return `env is: ${fastify.config.env}`
}
```

Like some of the code above, but I don't want to pass `fastify instance` layer by layer to the `utils` level or even deeper.

**Comment by RafaelGSS** [comment]
Ok, you can apply several design patterns for it, for instance, it should work for you:
```js
// api/log.js
const log;

export function logger(fastify) {
  if (fastify) {
    log = fastify.log
  }
  return log
}

export default logger
```

```js

import log from "./log";

export const getText = async () => {
    fastify.log.info("something");
    return `env is: ${fastify.config.env}`
}
```

There are many possibilities, this is just a poor example.

But, also, it's not related to fastify itself, the fastify doesn't provide a global context, you should do it for yourself.

**Comment by peixin** [comment]
Thanks, I understand.

**Comment by Shyam-Chen** [comment]
Ref: https://nodejs.org/dist/latest-v16.x/docs/api/globals.html#global

```ts
// ./src/app.ts
import type { FastifyInstance, FastifyServerOptions } from 'fastify';
import fastify from 'fastify';

declare let global: typeof globalThis & { fastifyInstance: FastifyInstance };

const app = async (options: FastifyServerOptions = {}) => {
  const app = fastify(options);
  global.fastifyInstance = app;
  return app;
};

export default app;
```
