### ISSUE TITLE
Cannot read property 'file' of undefined with fastify-multipart

### ISSUE THREAD

**Issue by arthur-fontaine** [fastify/help#378]
Hello!

I have an issue with [`fastify-multipart`](https://github.com/fastify/fastify-multipart/).

Here is my server-side code:
```js
...
export default async (fastify: FastifyInstance, opts: unknown) => {
   fastify.post('/', async (request, reply) => {
      const file = await request.file({
         limits: {
            fileSize: 20 * 1024 * 1024 * 1024 //20GB
         }
      });

      const fileStream = file.file;
...
```

And I get this error:
```json
{
   "level":50,
   "time":1614297706558,
   "pid":64275,
   "hostname":"MacBook-Pro-de-user-2.local",
   "reqId":12,
   "req":{
      "method":"POST",
      "url":"/file",
      "hostname":"127.0.0.1:3000",
      "remoteAddress":"127.0.0.1",
      "remotePort":57938
   },
   "res":{
      "statusCode":500
   },
   "err":{
      "type":"TypeError",
      "message":"Cannot read property 'file' of undefined",
      "stack":"TypeError: Cannot read property 'file' of undefined\n    at .../dist/routes/file/index.js:63:33\n    at Generator.next (<anonymous>)\n    at fulfilled (.../dist/routes/file/index.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
   },
   "msg":"Cannot read property 'file' of undefined"
}
```

It occurs only when I write a `await file.arrayBuffer();` at client-side. When I don't, I have what I want, without error.

My client-side code:
```js
...
const formData = new FormData();

this.filelist.forEach(async (file) => {
   await file.arrayBuffer();
   // formData.append(file.name, await encrypt(file, 'abcdef', window));
   formData.append(file.name, file);
});

try {
   const result = await this.$axios.$post(
      `${process.env.HIBERAPI_URL}/file`,
      formData,
      {
         headers: {
            'Content-Type': 'multipart/form-data'
         },
         onUploadProgress: (progressEvent) => {
            const percentCompleted = Math.round(
               (progressEvent.loaded * 100) / progressEvent.total
            );
            this.uploadProgress = percentCompleted;
         }
      }
   );
...
```

As I already said, when I comment the line `await file.arrayBuffer();` or when I write only `file.arrayBuffer();` (without `await`), the error doesn't occur.

I have no idea why this error occurs... If it is a Fastify error, or a mistake in my client-side code... So if someone can help me... I can't write a lot in that issue because I don't know the source of the problem (I don't even know if I am at the right place for the problem...), so ask me some precision on few points if you want ;).

* *node version*: 12.16.1
* *fastify version*: ^3.0.0
* *os*: Mac
* *fastify-multipart version*: ^4.0.0
* *@nuxtjs/axios version*: ^5.12.2

---

PS: sorry if there is some english mistakes ^^

**Comment by mcollina** [comment]
Can you please include a full example to reproduce the problem?

It seems you have quite a complex setup, including some significant transpiling.

**Comment by arthur-fontaine** [comment]
For the Axios request (using TypeScript):
```ts
// const filelist: File[] = [ /* a File object */ ];
const filelist = [new File([""], "filename")];
const formData = new FormData();

filelist.forEach(async (file) => {
	await file.arrayBuffer(); // doesn't work if this line is not commented
	formData.append(file.name, file);
});

await axios.$post(
	`http://localhost:3000/file`,
	formData,
	{
		headers: {
			'Content-Type': 'multipart/form-data'
		}
	}
);
```

For the Fastify route:
 - `/routes/file/index.ts`:
 ```ts
 export default async (fastify: FastifyInstance, opts: unknown) => {
	fastify.post('/', async (request, reply) => {
		const file = await request.file({
			limits: {
				fileSize: 20 * 1024 * 1024 * 1024 //20GB
			}
		});

		const fileStream = file.file;
		
		return reply
			.code(200)
			.header('Content-Type', 'application/json; charset=utf-8')
			.send({
				hello: 'world'
			});
	})
}
```

And the Fastify plugin for multipart:
 - `plugins/multipart.ts`:
 ```ts
 'use strict';

import fp from 'fastify-plugin';
import fm from 'fastify-multipart';

export default fp(async function (fastify, opts) {
	fastify.register(fm);
});
```

The other part of the Fastify app is just the files created by the `npm init fastify`command.

---

I think that it's what you want.

**Comment by mcollina** [comment]
We need some code that runs out of the box.. if there are multiple files, put them in a public github repo.

This is a good guide on how to create a reproducible example: https://stackoverflow.com/help/minimal-reproducible-example.

**Comment by arthur-fontaine** [comment]
Oh sorry it was late and I didn't understand what you wanted exactly ^^'

You can find a full example here: https://github.com/arthur-fontaine/Lab/tree/main/Fastify-Bug-Reproducible-Example

Here are the routes:
 - `/`: the root of the api and the route where the example make a request
 - `/example/works`: the example that works
 - `/example/doesnt-work`: the example that doesn't work

The only one difference on the example that works and the other one is just the line 20 who is commented on the one that works and not on the other one.

**Comment by mcollina** [comment]
I think this would do the trick for you:

```js
			const filelist = [new File([''], 'filename')];
			const formData = new FormData();
			(async () => {
			await filelist.map(async (file) => {
				await file.arrayBuffer(); // doesn't work if this line is not commented
				formData.append(file.name, file);
			});
				await axios.post(`/`, formData, {
					headers: {
						'Content-Type': 'multipart/form-data',
					},
				});
			})();
```

**Comment by arthur-fontaine** [comment]
Oh yes! It seems that it doesn't work, but thanks to your answer, I find that it's because `forEach` isn't `async`.

That's the way how I resolve the issue:
```ts
for await (const file of this.filelist.map((file) => file.arrayBuffer())) {
	formData.append(file.name, file);
}
```
