### ISSUE TITLE
Add custom data into Context object for integrating with type-graphql

### ISSUE THREAD

**Issue by lewispham** [fastify/help#380]
## 💬  Question here 

I'm having troubles with passing custom data into Context object on each incoming request. https://github.com/fastify/fastify/blob/be4ec2d193e38ffd93a786f808e516374eb46597/lib/context.js

The current fastify hooks only provide the `request` and `reply` arguments. But `type-graphql` decorator `@Ctx` will only extract the `Context` object so I can not bind data into `request` or `reply`. I tried with passing data into `request.context` on `preHandler` event but it does not work unfortunately.

```js
        app.addHook("preHandler", async (request, reply) => {
            request.context.customContext ={a: "b"}; // does not work
        });
```
Is there a way to pass custom data into the `Context` object?

## Your Environment

- *node version*: 15.10.0
- *fastify version*: >=3.12.0
- *os*: Linux
- *type-graphql version*: 1.1.1

**Comment by mcollina** [comment]
Can you please provide a full example of what you are trying to do? `context` is shared across requests so it's better not to add properties to it within the hooks.

I don't understand how `type-graphql` relates to this as I'm not aware of what it does or what it is useful for.

**Comment by lewispham** [comment]
@mcollina I'm trying to integrate `mercurius` with `type-graphql`. Everything is ok until I need to pass some variables (db connection, selected language, analytics, etc) into `type-graphql` resolvers. This is what I'm trying to do.

```
// index.ts
        import fastify from "fastify";
        import mercurius, { MercuriusOptions } from "mercurius";
        import { buildSchema } from "type-graphql";
        import { UserResolver } from "./user/UserResolver";

        const app = fastify({
            logger: true
        });
        app.addHook("preHandler", async (request, reply) => {
            request.customRequestContext = {
                 database,
                 language,
                 analytics
           };
            
        });
        app.register(mercurius, {
            schema: buildSchema({
            resolvers: [UserResolver]
        })
        } as MercuriusOptions);


// UserResolver.ts
import { Resolver, Mutation, Arg, Ctx, Args } from "type-graphql";
import { UserService } from "./UserService";
import { User } from "./User";
@Resolver()
export class UserResolver {
    @Mutation(() => User)
    async createUser(@Args() addUserData: CreateUserArgs, @Ctx() ctx: any): Promise<User> {
        // Variable `ctx` is expected to be the object `request.customRequestContext`
        // But it's actually the Context object instead
        return new UserService(ctx).add(addUserData);
    }

}
```

As you can see from the above code, I'm trying to pass `customRequestContext` into `UserResolver.createUser`. The problem is that `type-graphql` decorator `@Ctx` is returning the fasitfy `Context` object instead of my expected variable. I have already asked this question on `type-graphql` but the owner has confirmed that I need find a fastify solution for passing `customRequestContext` into the Context object.

This is my conversation with type-graphql 's owner.
<img width="589" alt="Screen Shot 2021-03-02 at 19 34 21" src="https://user-images.githubusercontent.com/7781091/109649327-55ccf500-7b8e-11eb-992b-fed441e740d0.png">

Since I'm quite new to both fastify and type-graphql. I don't really know who can help me with the above issue.

**Comment by mcollina** [comment]
I would recommend to open this issue in mercurius. I'm not sure you'd find the help you need here.

(I also won't know where to start in helping you, this seems an issue really relative to typed-graphql)

**Comment by MichalLytek** [comment]
@mcollina This issue is not related to TypeGraphQL.

What TypeGraphQL is translating normal GraphQL JS resolve call:
```ts
resolve: (root, args, context, info) =>
```
into the class version:
```ts
myQuery(@Root() foo: Foo, @Args() bar: BarArgs, @Context() context: FooBarContext, @Info() info: GraphQLResolveInfo) {}
```
there is literally no magic here regarding injecting the context:
https://github.com/MichalLytek/type-graphql/blob/v1.1.1/src/resolvers/helpers.ts#L38-L42

**Comment by MichalLytek** [comment]
I think the @lewispham question is about mercurius, not fastify. 
He wants to put some arbitrary data (like dataloaders or user token) into the GraphQL context.

**Comment by MichalLytek** [comment]
@lewispham Have you tried reading the docs?
https://mercurius.dev/#/docs/context

**Comment by fox1t** [comment]
@lewispham, as @MichalLytek pointed out you should use the "Mercurius context" and not the fastify request/response one.

**Comment by lewispham** [comment]
@MichalLytek @mcollina @fox1t  Thanks a lot for your help. I actually thought that this can be achieved with fastify hooks, which obviously led me into a wrong direction 🤦
