### ISSUE TITLE
API to get the number of opened connections.

### ISSUE THREAD

**Issue by DenisVoloshin** [fastify/help#381]
I have a Fastify server that is deployed on the Kubernetes cluster 
The server is hit with a bunch of requests (20K per sec). 
At some moment our clients start getting timeouts. While investigating the issue, I'm wondering if there is any built-in API
that returns the current number of all open connections. I'm looking for something like 

Node build-in http server has
```js
var server = http.createServer(app);     
  server.getConnections(function(error, count) {
    console.log(count); 
});
```
Thanks

**Comment by mcollina** [comment]
That API does not exist and it's not provided by node core. Adding it would slow us down significantly, so it's not provided.

These are useful modules you can use to help the situation:

https://www.npmjs.com/package/under-pressure
https://www.npmjs.com/package/fastify-routes-stats

Depending on your architecture it might be one of a few different problems, could you describe it in more details? 

---

There are also a few articles:

https://www.nearform.com/blog/integrating-backpressure-into-the-infrastructure/
https://www.nearform.com/blog/managing-load-in-node-js-with-under-pressure/
https://nodejs.org/en/docs/guides/dont-block-the-event-loop/
