### ISSUE TITLE
 fastify-passport: project status

### ISSUE THREAD

**Issue by franciscolourenco** [fastify/help#382]
## 💬  Question here 

Trying to evaluate wether fastify-passport might be a viable option in it's current state.
The README states the project is in alpha.

I'm wondering if there is anyone using fastify-passport in production and if there are any known issues with the plugin.
Any predictions on when/if the plugin will be out of alpha? 

Thanks!

**Comment by mcollina** [comment]
I think it's totally viable, even if I didn't use this myself.

@airhorns, have you got fastify-passport in prod? Should we bump it to 1.0.0?

**Comment by airhorns** [comment]
I sure do have it in prod! I think it might be a bit premature for a 1.0.0 in that I would like to reserve the right to make some more breaking changes, especially if we want to add support for other session storages, but I do think we could soften that notice a bit! I say we say it's in beta!

**Comment by airhorns** [comment]
https://github.com/fastify/fastify-passport/commit/58ba12186a13d8c385fe33ac86ebafc0664357eb

**Comment by Niewdanka** [comment]
Is it still in beta status?

**Comment by mcollina** [comment]
Nope, closing this
