### ISSUE TITLE
checkmarx security scan is flagging fastify for storing private key in build.

### ISSUE THREAD

**Issue by iOgef** [fastify/help#384]
#### You have already researched for similar issues?
Yes - the closest I can see is that this was brought up here:
https://github.com/fastify/help/issues/243
and the ticket was closed as stale. 

#### What are you trying to achieve, or the steps to reproduce?

We would like the test folder to be excluded from the build, or, not store a private key. 

#### What was the result you received?

```js
	"compliances": [
				{
					"title": "Private keys stored in image",
					"severity": "high",
					"cause": "Found: /server/node_modules/fastify/test/https/fastify.key"
				}
			],
```

#### What did you expect?

no medium or high compliance issues. 

#### Context

* *node version*: 12.18.3
* *fastify version*: >=3.12.0, have not tested on lower versions
* *os*: doesnt matter
* *any other relevant information*:

**Comment by jsumners** [comment]
Clearly a test key that we need for unit tests.
