### ISSUE TITLE
Can't access schemas with $ref

### ISSUE THREAD

**Issue by guerrap** [fastify/help#385]
#### You have already researched for similar issues?

Yes

#### What are you trying to achieve, or the steps to reproduce?

I'm defining schemas within the `fastify.register()` API, as follows:
```js
fastify.register(require("fastify-swagger"), {
    routePrefix: "/swagger",
    openapi: {
        info: {
            title: "my-app",
            description: "description",
            version: "1.0.0",
        },
        host: "localhost",
        schemes: ["http"],
        consumes: ["application/json"],
        produces: ["application/json"],
        components: {
            schemas: {
                MySchema: {
                    type: "object",
                    properties: {
                        message: {
                            type: "string",
                        },
                    },
                },
            },
        },
    },
    uiConfig: {
        docExpansion: "full",
        deepLinking: false,
    },
    exposeRoute: true,
});
```
The swagger UI correctly shows the `MySchema` in the bottom section, but I can't figure out how to reference them in my routes definitions.

```js
fastify.post(
    "/api",
    {
        schema: {
            ...
            body: {
                myfield: {
                    schema: {
                        $ref: "#/components/schemas/MySchema",
                    },
                },
            },
        },
    },
    (req, res) => {}
);
```

#### What was the result you received?

The `fastify-swagger` correctly parses the schema (no errors), but then in the UI the schema is not linked, the `$ref` does not work.

![image](https://user-images.githubusercontent.com/9011637/110644450-634d3500-81b5-11eb-87d4-6445f54ab9e0.png)

#### What did you expect?

I'd expect to see the `mySchema` prop defined as `MySchema`, referenced by the `$ref`.
Is this the currently expected behavior? Am I missing something?

#### Context

* *node version*: v15.11.0
* *fastify version*: 3.13.0
* *fastify swagger*: 4.4.0
* *os*: Linux

**Comment by griffincox** [comment]
I'm having the same issue.

**Comment by Eomm** [comment]
Please open a new detailed issue adding a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).
