### ISSUE TITLE
Calling fastify.inject from within route handler gives error

### ISSUE THREAD

**Issue by gk1** [fastify/help#387]
#### You have already researched for similar issues?
I have searched the fastify repo issues, here, and also general google fu, no answer that helps

#### What are you trying to achieve, or the steps to reproduce?
If i try to call fastify.inject within a route handler it returns an error that i do not understand. I would rather use inject than have to copy/paste code from other routes to be handled within this route, or have to decorate the app.

```js
'use strict'

export default async (app) => {
  app.route({
    method: 'GET',
    url: '/inject',
    schema: {
      hide: true, // don't show
      tags: ['/'],
      description: 'test area for app.inject commands - did not work'
    },
    attachValidation: true,
    handler: async (req, res) => {
      try {
        const irval = await app.inject({ method: 'GET', url: 'http://localhost:8000/' })
        // const irval = await app.inject({ method: 'POST', url: '/auth/login', body: { username: 'Username', password: 'Password' } })
        res.send(irval)
      } catch (error) {
        res.status(500)
        res.send(error)
      }
    }
  })
}

```

#### What was the result you received?
```
        /** can't call inject from a route handler?
         {
           "statusCode": 500,
           "error": "Internal Server Error",
           "message": "Converting circular structure to JSON\n    --> starting at object with constructor 'Response'\n    |     property 'socket' -> object with constructor 'Writable'\n  >
         }
         */

```
#### What did you expect?
I expected the result of the sample route to be returned. I am using fastify.inject elsewhere in like emitted events and it works perfectly, just not from within a route handler.
#### Context

* *node version*: 14.5
* *fastify version*: >=3.9.2
* *os*: Linux(Ubuntu 20.04)
* *any other relevant information*:

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by jsumners** [comment]
```js
const response = await fastify.inject({ url: '/foo', method: 'GET' })
res.send(response.json())
```

**Comment by gk1** [comment]
Thanks!! that did the trick.
