### ISSUE TITLE
How to remove headers from fastify request?

### ISSUE THREAD

**Issue by pramodhts** [fastify/help#388]
How to remove headers from fastify request?

- *node version*: 10, 12, 13
- *fastify version*: >=2.0.0
- *os*: Mac

**Comment by mcollina** [comment]
Isn't https://www.fastify.io/docs/latest/Reply/#removeheaderkey sufficient?

**Comment by pramodhts** [comment]
I am trying to remove it from request.headers before forwarding it to another API by using reply.from (from fastify-reply-from)

**Comment by mcollina** [comment]
This should do the trick: https://github.com/fastify/fastify-reply-from#rewriterequestheadersoriginalreq-headers
