### ISSUE TITLE
fastify.setSchemaErrorFormatter callback param type mismatch

### ISSUE THREAD

**Issue by jdboix** [fastify/help#389]
#### You have already researched for similar issues?
Yes

#### What are you trying to achieve, or the steps to reproduce?

I'm trying to write a custom validation error message while using json schema validations for a server. When trying to write a custom validation error using `fastify.setSchemaErrorFormatter` I discovered that type the callback receives doesn't seem the one that it is being passed later on. 

I wrote a function with the following signature:

```js
(errors: FastifySchemaValidationError[], dataVar: string) => Error
```

And passed it as a parameter to `fastify.setSchemaErrorFormatter`.

#### What was the result you received?
When logging `errors` to see what was the content of the objects I saw that these had more fields than those described in  `FastifySchemaValidationError`. While digging through the type definitions it seemed to follow `ValidationResult`'s structure rather than the one that it is being initially expected.

#### What did you expect?
Either for `fastify.setSchemaErrorFormatter` to accept `(errors: ValidationResult[], dataVar: string) => Error` or return the appropriate object structure if those shouldn't be accessed.

#### Context

* *node version*: 12.13.0
* *fastify version*: ^3.0.0
* *os*: Mac

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by jdboix** [comment]
After looking further into it, I found out that `FastifySchemaValidationError` is just mapping out a subset of the attributes returned by the Ajv validation function, which returns this type:

```ts
interface ErrorObject<K extends string = string, P = Record<string, any>, S = unknown> {
  keyword: K
  dataPath: string
  instancePath?: string
  schemaPath: string
  params: P
  // Added to validation errors of "propertyNames" keyword schema
  propertyName?: string
  // Excluded if option `messages` set to false.
  message?: string
  // These are added with the `verbose` option.
  schema?: S
  parentSchema?: AnySchemaObject
  data?: unknown
}
```
https://github.com/ajv-validator/ajv/blob/595b1ca96ecd4006c4fbe0f20d3375f5b09cce93/lib/types/index.ts#L82

I'll open up a PR adding these further attributes to Fastify's type.

**Comment by Eomm** [comment]
> After looking further into it, I found out that `FastifySchemaValidationError` is just mapping out a subset of the attributes returned by the Ajv validation function, which returns this type:
> 
> ```ts
> interface ErrorObject<K extends string = string, P = Record<string, any>, S = unknown> {
>   keyword: K
>   dataPath: string
>   instancePath?: string
>   schemaPath: string
>   params: P
>   // Added to validation errors of "propertyNames" keyword schema
>   propertyName?: string
>   // Excluded if option `messages` set to false.
>   message?: string
>   // These are added with the `verbose` option.
>   schema?: S
>   parentSchema?: AnySchemaObject
>   data?: unknown
> }
> ```
> 
> https://github.com/ajv-validator/ajv/blob/595b1ca96ecd4006c4fbe0f20d3375f5b09cce93/lib/types/index.ts#L82
> 
> I'll open up a PR adding the missing attributes to Fastify's type.

Side note: we are using ajv6, so that type should be this one: https://github.com/ajv-validator/ajv/blob/v6.12.6/lib/ajv.d.ts
