### ISSUE TITLE
How to set log level on an a logger passed from the outside?

### ISSUE THREAD

**Issue by elig-salt** [fastify/help#390]
I'm passing a Pino instance into Fastify.
Pino is set to log level "info", and I want fastify to write it's logs under the "debug" level.
Meaning I don't want to see Fastify's logs unless I set the Pino logger's (the one I'm passing from the outside) level to "debug" as well.
Is this possible?

Thanks.

**Comment by Eomm** [comment]
Are you looking for [disableRequestLogging](https://www.fastify.io/docs/latest/Server/#disablerequestlogging)?

**Comment by elig-salt** [comment]
Yes that would do, thank you !
