### ISSUE TITLE
415 Unsupported Media Type on multipart/form-data POST

### ISSUE THREAD

**Issue by bhavelyn** [fastify/help#391]
#### You have already researched for similar issues?
Yes. but I could not find a solution

#### What are you trying to achieve, or the steps to reproduce?

When posting a request with `fetch` from the browser, I get this error:  `415 Unsupported Media Type on multipart/form-data`

On the Server, I am using `fastify-multipart` as following:

```js
import multipart from "fastify-multipart";

fastify.register(multipart, {
    limits: {
      fileSize: 1000000 * 5, // For multipart forms, the max file size (5mb)
      files: 10, // Max number of file fields
    },
    attachFieldsToBody: true,
  });
  ``` 
  
 Attaching fields to body because I need to know other values in the form.

My request code looks like following:
```js
// Event handler for input file change

const handleAvatarFileSelection = async (evt: ChangeEvent<HTMLInputElement>) => {
    if (!evt?.target?.files?.length) {
      return;
    }
    const file = evt.target.files[0];

    if (file) {
      const formData = new FormData();
      formData.append("file[0]", file);
      formData.append("userid", user?.uid || "");

      const uploadResponse = await fetch(`${beApiURL}/v1/upload-static-files`, {
        method: "POST",
        headers: {
          "Content-Type": "multipart/form-data",
          authorization: userToken || "",
        },
        body: formData,
      });

      if (uploadResponse.ok) {
        const res = await uploadResponse.json();
        console.log("file uploaded", res.data);
      }
    }
  };
```

The craziest thing is that if I make a new request from Insomnia client, that works fine.
In addition, if I copy the request as Curl from Browser and post that from insomnia then it also Does NOT work.

I am just not understanding how to send the request correctly from the JS.

#### What was the result you received?
415 Unsupported Media Type on multipart/form-data 

#### What did you expect?
The request to complete successfully

#### Context

* *node version*: 15.2.1
* *fastify version*: 3.12.0
* *os*: Ubuntu
* *any other relevant information*:
EDIT: I see in the browser network tab that the data is being sent to the server as following:
![payload](https://user-images.githubusercontent.com/71679724/111263674-8600a300-8626-11eb-82ba-f5b5ed46c0f5.png)

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by bhavelyn** [comment]
Well, I installed and used Axios and that **worked** fine.

So the real question is how do I achieve it using the browser `Fetch` ? 
To me both the requests in the networks tab on browser look the same.

however, this is not a Fastify issue. but if I can get some help on this it will be awesome.

thanks.

**Comment by mcollina** [comment]
I think https://stackoverflow.com/questions/35192841/how-do-i-post-with-multipart-form-data-using-fetch will help.

**Comment by bhavelyn** [comment]
If someone else comes here,

In my case, removing `"Content-Type": "multipart/form-data"` from fetch headers solved the issue.

Also using Axios was fine.
