### ISSUE TITLE
Help: how to enable logger from fastify-cli

### ISSUE THREAD

**Issue by mariusa** [fastify/help#392]
## 💬  Question here 

The logging docs are quite clear when using fastify
https://www.fastify.io/docs/latest/Logging/

but I don't see how to enable logging when using fastify-cli
https://github.com/fastify/fastify-cli

That is, in app.js (plugins setup), without server.js

Would you please give an example in docs?

**Comment by mcollina** [comment]
Check out https://github.com/fastify/fastify-cli/blob/e72819ed2111ef382b4c5fddff48c13a8d815185/help/start.txt#L17

```sh
fastify -l info app.js
```

**Comment by mariusa** [comment]
One more question please: info logged in the terminal is shown with \n, instead of new lines, which makes it harder to read.
Using linux (fedora) and fastify-cli. Any suggestions on how to fix this?

![2021-03-16_18-25](https://user-images.githubusercontent.com/1283842/111344408-048c2d80-8685-11eb-9bed-e5da3e52d1ee.png)

**Comment by mcollina** [comment]
How could we make the docs more discoverable? it's written in the same link I pasted above, a few lines down: https://github.com/fastify/fastify-cli/blob/master/help/start.txt#L29.

**Comment by mariusa** [comment]
I'm sorry for missing that. I googled instead of reading all the options https://www.google.com/search?q=fastify+log+new+line didn't have an answer. Thanks for your time!
