### ISSUE TITLE
decorate request? or reply?

### ISSUE THREAD

**Issue by jessekrubin** [fastify/help#393]
Hello I am using fastify with typescript and loving it.

I have a best/better practices question.

In the case where I could use either `decorateRequest` or `decorateReply` should I prefer one over the other?

**Comment by climba03003** [comment]
It depends on your usage. They are both the same.

If the information comes with request, then I prefer `decorateRequest`.
e.g. `user` information

If the information is only used for reply, then I prefer `decorateReply`.
e.g. `createError`, helps with creating custom error.
