### ISSUE TITLE
Listen on HTTP and HTTPS for a single fastify  app

### ISSUE THREAD

**Issue by hellower** [fastify/help#395]
How can I implement it in fastify?

Below is express sample.
----------------------------- express sample ------------------------------------
var register = function (app) {
    // config middleware
    app.configure({

    });

    // config routes
    app.get(...);
};

var http = express.createServer();
register(http);
http.listen(80);

var https = express.createServer({ key: /* https properties */ });
register(https);
https.listen(443);

**Comment by mcollina** [comment]
It's not stricly possible. You should include all your logic inside a plugin and then register it to both instances.

I would advise against it anyway and go https-only.

**Comment by climba03003** [comment]
[`Use A Reverse Proxy`](https://github.com/fastify/fastify/blob/master/docs/Recommendations.md#use-a-reverse-proxy)

**Comment by hellower** [comment]
Thanks!
