### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by woss** [fastify/help#397]
## 💬  Question here 

What is the correct way to type and to implement the multipart upload with extra fields and then read them from the body? I know how to do that with the multer but this is a bit different.

If I can not use the `attachFieldsToBody: true,` ( Memory performance ) that would be great, if that's not possible then I'm fine with that. 

I've been checking the examples but can't figure it out. 

I'm talking about typing the route in the Typescript.

Thank you.

## Your Environment

- *node version*: v14.16.0
- *fastify version*: ^3.14.0
- *os*: Linux - Debian 10 WSL2

**Comment by mcollina** [comment]
Is this a typescript problem? If not, https://github.com/fastify/fastify-multipart/blob/master/examples/example.js not cover your case?

**Comment by woss** [comment]
no, it doesn't. i went through all the examples before I filed this question. 
this is the file I am working on now https://gitlab.com/kelp_digital/ipfs-files-management/-/blob/improvement-and-new-routes/src/routes/ipfs/files/write.ts and this is the image from the fields i'd like to get from the body
![image](https://user-images.githubusercontent.com/80440/111977135-b3f05680-8b02-11eb-89ea-425a881e5465.png)

**Comment by mcollina** [comment]
This block should do what you need: https://github.com/fastify/fastify-multipart/blob/772fdf901b980efd116ce3dc8c3b6651fd2a6099/test/multipart.test.js#L27-L47.

**Comment by woss** [comment]
This is what i get when `console.log(part.fields.path)` ![image](https://user-images.githubusercontent.com/80440/111991584-c4a9c800-8b14-11eb-9e5d-446bd6eabef2.png)
How can I read the value since the `path.value` doesn't exist. 
I'm trying to upload the file to IPFS and I need the path value. 

Thanks for the link but that still doesn't answer the original question. 

How do I type it in TS and getting the extra fields values?

**Comment by woss** [comment]
so after double-checking the `index.d.ts` i noticed the `addToBody` which is NOWHERE to be mentioned. What it does it puts the fields to the body and they can accessed and typed like this:

```ts
export default async function routes(fastify: FastifyInstance) {
  fastify.post<{
    Body: {
      fileName: string
      path: string
    }
  }>('/ipfs/files/write', async (req, reply) => {
    if (!req.isMultipart()) {
      reply.code(400).send(new Error('Request is not multipart'))
    }
    console.log(req.body.path)
    console.log(req.body.fileName)

    reply.send('yep')
  })
}
```
And this is possible by init the plugins like this:

```ts
fastify.register(import('fastify-multipart'), {
  addToBody: true
})
```

**Comment by mcollina** [comment]
> so after double-checking the index.d.ts i noticed the addToBody which is NOWHERE to be mentioned. 

Would you like to send a PR?

**Comment by woss** [comment]
sure, why not. 

I'll check the code and see the diff between the `addToBody` and `attachFieldsToBody` then probably improve this part https://github.com/woss/fastify-multipart#parse-all-fields-and-assign-them-to-the-body
