### ISSUE TITLE
media type versioning

### ISSUE THREAD

**Issue by PavelPolyakov** [fastify/help#4]
Hello, 

General question, I would like to hear the opinion of the framework maintainers on this topic.

In the original fastify documentation there is an example of [prefixing the routes with versions](https://www.fastify.io/docs/latest/Routes/#route-prefixing).

However, there are different strategies to do API versioning, one of which is media types versioning. [Zanaldo](http://zalando.github.io/restful-api-guidelines/#114) and [GitHub](https://developer.github.com/v3/) for example are doing so.

What is your view on this? And how would you, high level, implement the routing (or versioning) based on the media type? Meaning - route is the same every time, but acts different based on the `Accept` incoming header.

Maybe we can later create a plugin for this purpose.

Looking forward to your opinion.

Regards,

**Comment by delvedor** [comment]
I'm working on a plugin to support routing based on the `Accept` header, but it is not ready yet.

The problem is that you will loose the validation/serialization feature, because it will be the same for all the versioned routes (because the url is the same).

Furthermore a routing based on the `Accept` header is way slower than the one based on the route url, because of the `semver` module that you will use.

**Comment by PavelPolyakov** [comment]
@delvedor
Good to know that. You are right that there will be some complexities with validation. It doesn't seem that currently any dynamic validation is supported: https://www.fastify.io/docs/latest/Validation-and-Serialization/ . 🤔 

I also thought that maybe it can be done this way - there is one incoming route, BUT underneath it will be calling another routes through the `server.inject`. Which also mean that all the other routes should also be declared as the real routes. 

But this looks a little bit less neat than it may be.

**Comment by delvedor** [comment]
> Good to know that. You are right that there will be some complexities with validation. It doesn't seem that currently any dynamic validation is supported: https://www.fastify.io/docs/latest/Validation-and-Serialization/ . 🤔

Dynamic validation is not directly supported, but you can easily achieve it by using the [`beforeHandler`](https://github.com/fastify/fastify/blob/master/docs/Hooks.md#beforehandler).

> I also thought that maybe it can be done this way - there is one incoming route, BUT underneath it will be calling another routes through the server.inject. Which also mean that all the other routes should also be declared as the real routes.

This could be a solution, but is very complex, and you should use another nested router to avoid route conflicts.
