### ISSUE TITLE
Remove dependencies on outdated tools

### ISSUE THREAD

**Issue by smartiniOnGitHub** [fastify/help#40]
#### You have already researched for similiar issues?
yes but did't find info.

#### What are you trying to achieve or the steps to reproduce?

I'm running Fastify tests with the [citgm](https://www.npmjs.com/package/citgm) tool, to ensure it won't break with next releases of Node.js (like 12).

```bash
~/work/temp> npx citgm fastify@latest
```

#### What was the result you received?
This is the output of the tool:

```bash
 martinis@MLBLQ31900  ~/work/temp  npx citgm fastify@latest
npx: installed 243 in 43.267s
info:    starting            | fastify@latest      
info:    lookup              | fastify             
info:    lookup-found        | fastify             
info:    fastify lookup-replace| https://github.com/fastify/fastify/archive/fc768bfe7d39b3f5b48a067160c0b9f9d939e7b0.tar.gz
info:    fastify npm:        | Downloading project: https://github.com/fastify/fastify/archive/fc768bfe7d39b3f5b48a067160c0b9f9d939e7b0.tar.gz
info:    fastify npm:        | Project downloaded fastify-1.13.3.tgz
info:    fastify npm:        | npm install started 
warn:    fastify npm-install:| npm                 
warn:    fastify npm-install:| WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
warn:    fastify npm-install:| npm                 
warn:    fastify npm-install:| notice created a lockfile as package-lock.json. You should commit this file.
info:    fastify npm:        | npm install successfully completed
info:    fastify npm:        | test suite started  
info:    passing module(s)   |                     
info:    module name:        | fastify             
info:    version:            | 1.13.3              
info:    done                | The smoke test has passed.
info:    duration            | test duration: 111008ms
```

#### What did you expect?
To not have dependencies to outdated tools.

#### Context

* *node version*: LTS (8.15.0), and don't know if even with next (12)
* *fastify version*: 1.13.3
* *os*: Mac, Linux
* *any other relevant information*: nothing special.

**Comment by smartiniOnGitHub** [comment]
Not sure this is a problem, hope this helps identifying something to update (for 2.0.0 and maybe even for a 1.13.x) release. Thanks for the help.

**Comment by mcollina** [comment]
I don't understand the issue. CircularJSON is a dependency of eslint, which we depend on via standard. What are you suggesting with this issue?

**Comment by smartiniOnGitHub** [comment]
Hi, sorry weren't sure what Fastify dependency had it; my trouble here was to understand if we can do something to remove that outdated dependency ... so thanks for that info; time to ask ESLint guys to update it (or propose it for them) and close the help request here, sounds good ?

**Comment by mcollina** [comment]
+1!

**Comment by smartiniOnGitHub** [comment]
Just see that here is already a bug open there for it: [circular-json in maintenance](https://github.com/royriojas/flat-cache/issues/22), let's see ... thanks again. Bye
