### ISSUE TITLE
Configure Fastify project created with `npm init fastify` to listen to all interfaces

### ISSUE THREAD

**Issue by DonaldKellett** [fastify/help#400]
One can install Fastify using `npm install fastify` and configure the server manually, or initialize a structured project from the get go using `npm init fastify`.

With the former method, one would typically invoke `fastify.listen()` which defaults listening to `localhost` only; however, an optional parameter could be passed to listen to other interfaces, e.g. `fastify.listen(PORT, '0.0.0.0')` to listen to all interfaces on the specified port.

However, with the latter method (which also defaults listening to `localhost` only), I have checked `app.js` plus all the files under `plugins/` and `routes/` but could not find where to configure the server to listen to other interfaces. I'm probably missing something obvious here, but is there some line of code or some command line option to specify which interfaces the server should listen to?

Any hints would be much appreciated. Thanks!

## Environment

- Node version: `10.23.1`
- Fastify version: `3.14.0`
- Operating System: Linux (CentOS 8 Stream)

**Comment by mcollina** [comment]
`fastify -a 0.0.0.0 app` should do the trick!

**Comment by DonaldKellett** [comment]
Thanks for the quick reply, passing `-a 0.0.0.0` to `fastify` did the trick!

**Comment by jsumners** [comment]
`npm init fastify` is basically an alias for `fastify-cli` -- https://github.com/fastify/create-fastify/blob/bbf634588d17e5af144b7dd46a1e2d998b416903/cmd.js
