### ISSUE TITLE
Need help with fastify-jwt

### ISSUE THREAD

**Issue by harshmandan** [fastify/help#401]
#### What are you trying to achieve, or the steps to reproduce?

Hi, I'm coming from express where I had two separate middlewares for decoding two separate cookies. I need that functionality in fastify as well.

Here are my two code snippets

```js
const token = await reply.jwtSign({ _id: found.user._id, t: "p" });
				reply.header("Cache-Control", "private")
					.setCookie("ptoken", token, {
						sameSite: "none",
						secure: true,
						httpOnly: true,
						maxAge: 9000000,
						signed: true,
					})
					.send({ code: 200, user});
```

```js
const token = await reply.jwtSign({ sid: entity._id, t: "p" });
				reply.header("Cache-Control", "private")
					.setCookie("stoken", token, {
						sameSite: "none",
						secure: true,
						httpOnly: true,
						maxAge: 9000000,
						signed: true,
					})
					.send({ code: 200, user});
```

I have a middleware like function I'm using as a prevalidator in another file:

```js
export default async (request, reply) => {
    try {
        await request.jwtVerify();

    } catch(e) {
        reply.code(401).send({code:401});
    }

  };
```

Here's my router as well:
```js
import publisherAuthRoutes from './publisher/auth.js';
import cookie from '../decorator/cookie.js';

async function publicPublisherRoutes(app) {
    app.addHook('preValidation', cookie);
    app.register(publisherAuthRoutes, { prefix: '/p/auth' });
}

export default async function routes(app) {
  app.register(publicPublisherRoutes);
}


```

But I can decode the JWT present in the authorization header here only.
I saw the docs but got a little confused because `fastify.jwt.decode` isn't available in this file. So how do I pass a custom token, in my case ptoken and stoken to decode for validation? Is there a better way to do it? Should I use jsonwebtoken for this purpose because that was working for me in express?

#### Context

* *node version*: 14
* *fastify version*: 3.8.0
* *os*:  Windows
* *any other relevant information*:

**Comment by climba03003** [comment]
Create a decorator for `request` after you register `fastify-jwt`. So, you can link the `decode` function to `request`.

**Comment by mcollina** [comment]
Can you include a full example to reproduce your problem?
