### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by abhishekdhadwal** [fastify/help#402]
how to validate a multipart file with json fluent schema ??

**Comment by climba03003** [comment]
built-in `ajv` cannot validate `binary` or `stream`.
You need to use a custom validator or add new keyword for the validation.

**Comment by abhishekdhadwal** [comment]
is there any example fro that ??

**Comment by climba03003** [comment]
How to use a custom validator:
https://github.com/fastify/fastify/blob/main/docs/Validation-and-Serialization.md#validator-compiler

How to implement custom format:
https://ajv.js.org/api.html#ajv-addformat-name-string-format-format-ajv

**Comment by climba03003** [comment]
Feel free to reopen the issue if you have further question
