### ISSUE TITLE
How to handle error that occurred after reply.send(stream)

### ISSUE THREAD

**Issue by vimutti77** [fastify/help#403]
## 💬  Question here 
I want to implement an API to download a file from AWS-S3.
```js
const stream = s3
  .getObject({
    Bucket: bucket,
    Key: path,
  })
  .createReadStream()

reply.send(stream)
````
This code works fine when there is a file on the path. But when there is no file, It will log the error and reply
`{"statusCode":404,"code":"NoSuchKey","error":"Not Found","message":"The specified key does not exist."}`

What I want is to not log the error and reply with a different message. How can I do that?

## Your Environment

- *node version*: 14
- *fastify version*: ^3.14.1
- *os*: Windows

**Comment by mcollina** [comment]
You can use [`serErrorHandler()`](https://www.fastify.io/docs/latest/Server/#seterrorhandler) - errors will be routed there.
