### ISSUE TITLE
collection.findOne works as expected but collection.find is returning an error

### ISSUE THREAD

**Issue by nicholasoxford** [fastify/help#404]
#### You have already researched for similar issues?
I have tried to find similar issues, but without success. I was going to file a bug in the Fastify mongodb repo, but thought it's probably me and not a bug. 

#### What are you trying to achieve, or the steps to reproduce?

When using collection.findOne({}, (err, result) => return result), everything works as expected. When passing in find(), 

```
 imageGet: get('/imageGet', (req, reply) => {
      const db = fastify.mongo.db

      db.collection('images', onCollection)

      function onCollection (err, col) {
        if (err) return reply.send(err)
        // col.findOne works
        col.find({}, (err, user) => {
          if (err) {
            reply.send(err)
          }
          console.log('user', user)
          reply.send(user)
        })
      }
    }
```

#### What was the result you received?

I get 

`The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Object` 

when passing in no arguments. 

#### What did you expect?

Ann array of objects

#### Context

* *node version*: 15
* *fastify version*: >=3.13
* *os*: Mac
* *any other relevant information*:

The repo to reproduce
[fastlyDream](https://github.com/nicholasoxford/fastlyDream)

**Comment by mcollina** [comment]
fastify-mongodb just use https://www.npmjs.com/package/mongodb. I would recommend reproducing just using the mongodb library and ask for help there.

Looking at the docs http://mongodb.github.io/node-mongodb-native/3.6/api/Collection.html#find it seems this function does not accept a callback.

**Comment by nicholasoxford** [comment]
If there so happens to be someone looking for the answer, here is my solution.

```
imageGet: get("/imageGet", (req, reply) => {
      const db = fastify.mongo.db;
      db.collection("images", onCollection);
      var imgArray = [];
      //  Has to be async
      async function onCollection(err, col) {
        // find returns a cursor 
        const imgCursor = col.find({});
        for await (const data of imgCursor) {
          imgArray.push(data);
        }
        reply.send(imgArray);
      }
    }),
```
