### ISSUE TITLE
Blocking botnet requests

### ISSUE THREAD

**Issue by pv93** [fastify/help#406]
## 💬  Question here 

Hi,

Our exception monitoring tool is picking up a ton of Fastify errors that are the result of botnets requesting various URLs.

I was wondering if there is an accepted way to 'catch' such requests. 

For example, we get requests where the Content-Type header can be all sorts of unsupported formats. In those cases, Fastify throws us errors like these:

-- Unsupported Media Type: application/x-www-form-urlencoded

What's the proper way to handle such errors, while not preventing legitimate exceptions from reaching our monitoring tool?

- *node version*: 15
- *fastify version*: >3.6.0
- *os*: Linux
- *any other relevant information*

**Comment by Eomm** [comment]
Only you have the data to analyze your traffic and business-logic to make some hard choice like creating an `onRequest` hook that drops all the request without the right `content-type`

For sure you may customize the `setErrorHandler` and `setNotFoundHandler` to minimize this noise, but you must be cautious to not hide legitimate request

**Comment by pv93** [comment]
Hmm okay -- so maybe one way to solve this is:

Implement a handler for the error FST_ERR_CTP_INVALID_MEDIA_TYPE using `setErrorHandler`. In this handler we say:

-- if this request does not go to any of our registered routes, drop the request, otherwise it's a legitimate error and we want to report on it.

Does that make sense?
