### ISSUE TITLE
Fastify? Nestjs? AWS?

### ISSUE THREAD

**Issue by WaterBleu** [fastify/help#409]
I've used Nestjs with express in the past.
Now onto the new project seems like Fastify is recommended.
However the team decided to go serverless.
I'm somewhat overwhelmed with all the plugins and different ways of doing things.
I've researched and seems like there are some articles that allows me to do it but with technologies evolving some are no long relevant.
I'm hoping to better assess with few questions.

1. Does Fastifty, Nestjs, Serverless, AWS lambda mixes well?
- I'm having trouble understanding how it all stacks with each other and if this is a good idea at all
- The goal is to utilize serverless and AWS as backend api server.
 

#### Context

* *node version*: 9
* *fastify version*: 3.12.0
* *os*: Mac

**Comment by mcollina** [comment]
You can use https://github.com/fastify/aws-lambda-fastify to run your Fastify server with AWS Lambda lambda.
