### ISSUE TITLE
Question about Req/Reply lifecycle

### ISSUE THREAD

**Issue by matthyk** [fastify/help#410]
## 💬  Question here 

I am currently developing a framework based on Fastify. One core feature in content negotiation. This is implemented by selecting the appropriate handler within a Fastify route handler again based on the accept header. This is shown in simplified form in the example below. Another feature is that each handler logic is implemented in its own class. For this, each service class has access to the request and reply object. 

And now the following situation occurs: 
Some user sends a request to the below described endpoint with the accept header `application/json`. The service class `MyFirstService` is initialized and the request and reply object is passed. Then some asynchronous database function is executed to wait for. In the meantime, another user also makes a request to the endpoint with the accept header `text/html`. To process this request the class `MySecondService` is initialized and the request and reply object is passed. Then a simple synchronous function is executed. Then the response is sent to the user. Then sometime AFTER the second request has already been answered the asynchronous function from the first request is ready. Now the first request can finally be answered.

What is not quite clear to me about this szernario is whether it is safe the way i do it. Do the two classes `MyFirstService` and `MySecondService` each have completely separate request and reply objects or do they just share the reference to the same objects?

Is it feasible to implement it in this way in general?
```js
const fastify = require('fastify')( { logger: { level: 'debug' } } )

class MyFirstService {

    constructor(req, reply) {
        this.req = req
        this.reply = reply
    }

    async doSomething() {
        this.reply.code(200)
        return await this.queryDatabase()
    }

    queryDatabase() {
        return new Promise(resolve => {
            setTimeout(resolve, 5000)
        })
    }
}

class MySecondService {

    constructor(req, reply) {
        this.req = req
        this.reply = reply
    }

    doSomething() {
        this.reply.code(204)
        return ''
    }
}

fastify.route({
    method: 'GET',
    url: '/',
    handler: async (req, reply) => {
        if(req.headers.accept === 'application/json') {
            const result = await new MyFirstService(req, reply).doSomething()

            reply.send(result)
        } else {
            const result = new MySecondService(req, reply).doSomething()

            reply.send(result)
        }
    }
})

fastify.listen(3000)

````

## Your Environment

- *node version*: 14
- *fastify version*: >=3.0.0
- *os*: Mac

**Comment by jsumners** [comment]
Each request receives its own `Request` and `Reply` instances. There is a caveat: the `context` can be share between requests. But you should not have to worry about that if you are using proper decorators.
