### ISSUE TITLE
bodyLimit for Post Request

### ISSUE THREAD

**Issue by xyz-mtl** [fastify/help#411]
Hi,
I would like to implement a custom bodylimit for a specfic route:
 fastify.post("/",{ bodyLimit: 22485760 }, (request, reply)
But the answer is the same : ✨ Request body is too large
Is it possible to put a custom limit ?
Thank you

**Comment by mcollina** [comment]
Could you please create a reproducible example? Ideally send the form data from Node.js itself.

**Comment by xyz-mtl** [comment]
> Could you please create a reproducible example? Ideally send the form data from Node.js itself.

Sure. I will provide an example next week.
