### ISSUE TITLE
Global auth (API gateway)

### ISSUE THREAD

**Issue by huevoncito** [fastify/help#412]
## 💬  Question here 
I have an application which is essentially an API gateway which delegates traffic to other microservices. The middleware does one of three things:

- Check authentication
- Dispatch the request to an external service
- Allow request to proceed to other routes within the gateway application (eg. authenticate, users, etc)

It looks like this.

```js
/*
 For any route that is not authenticate...
*/
app.use(/^\/(?!authenticate).*/,

  //Webhooks received from external services cannot be authenticated in the normal flow 
  function (req, res, next) {

    const { baseUrl, method } = req;

    //URL whitelist
    const safeUrls = [ '...' ];

    //if it's a post request and the url is in the white list, let it go through
    if ( safeUrls.includes( baseUrl )  ) {
      return dispatchToService(req, res, next, { skipAuth: true });
    }
    
   //otherwise proceed with authentication
    next();
  },

  /*
    Authenticate with passport
  */
  passport.authenticate('strategy', { opts }),

  //some routes are local, so we call next and hit them directly. Otherwise, dispatch to microservice. Either way, user is already authenticated
  function (req,res, next) {
    if ( req.baseUrl == '/users' || req.baseUrl == '/services' ) {
      next();
    } else {
      //dispatch to a service
      dispatchToService(req, res, next);
    }
  }
);

//if dispatchToService was not triggered, these are hit. User is already authenticated.
app.post('/authenticate',. ..)
app.get('/users', ...)
app.get('/services', ..)
````
I'm trying to achieve the same thing with `fastify-passport` but it's not working. The examples in `fastify-passport` all use the preValidation hook at the route level, but I'm looking for something more global. Middleware (using `middie` doesn't work because my middleware must respond to requests in certain situations and `middie` disables the response API.

So instead, I thought we could replace the middleware with `onRequest` hooks.

I've tried to approximate the express functionality as follows:

```js
   const app = Fastify();

  //init passport
  // set up secure sessions for fastify-passport to store data in
  app.register(fastifySecureSession, { key: fs.readFileSync(path.join(__dirname, 'secret-key')) });

  // initialize fastify-passport and connect it to the secure-session storage. Note: both of these plugins are mandatory.
  app.register(fastifyPassport.initialize())
  app.register(fastifyPassport.secureSession())

  fastifyPassport.use( passportStrategy );

//the original code had 3 middleware functions, so I'm using three hooks

//you don't need to be authenticated here
 app.addHook('onRequest', handlerToSkipAuthWhenNeeded );

 //authenticate
 app.addHook('onRequest', fastifyPassport.authenticate());

//must be authenticated from here on our
 app.addHook('onRequest', dispatchToService)

//then the routes
app.register(require('./routes/users'))
app.register(require('./routes/authenticate'))

...

```

However this doesn't work. All requests come back "unauthorized." When I try to use the `preValidation` hook at the route level, it works. But the whole point is not to do that.

Sorry if the answer is obvious. I'm new to fastify.

Thanks!

**Comment by mcollina** [comment]
Thanks for reporting! It _seems_ you are registering the authenticate hook also for the `/authenticate` route - making it impossible for your user to authenticate. You'll have to do something like:

```js
fastify.register(async function (app) {
  // authenticated routes
  app.addHook('onRequest', fastifyPassport.authenticate())
  app.register(require('./user'))
})

app.register(require('./authenticate'))
```

**Comment by huevoncito** [comment]
That did it. Thanks for your extremely fast help and the great framework.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
