### ISSUE TITLE
Help - fastify-reply-from - retry on ECONNRESET

### ISSUE THREAD

**Issue by artur-ma** [fastify/help#413]
## 💬  Question here 

We are using `fastify-reply-from` in our gateway, from time to time we get `ECONNRESET`, we would like to retry those requests (especially `GET`) requests, is there a way to do that? 
I'm also not sure after the first try if the request stream still holds the data to retry to proxy the request again.

## Your Environment

- *node version*: 14
- *fastify version*: 3.14.0
- *os*: Alpine
- *fastify-reply-from*: 5.2.0

**Comment by mcollina** [comment]
What version of fastify-reply-from are you using? With what settings? How many ECONRESET are you getting?

Retrys are not supported right now. It might be possible to retry the GET requests as they are idempotent.

**Comment by artur-ma** [comment]
> What version of fastify-reply-from are you using? With what settings? 
We are using 5.2.0 **without** undici

> How many ECONRESET are you getting?

Currently not much, about 300 in 7 days, but it can raise with more traffic

**Comment by mcollina** [comment]
Which version of Node.js are you using?
You might want to set `'lifo'` scheduling in the agent https://nodejs.org/dist/latest-v14.x/docs/api/http.html#http_new_agent_options
