### ISSUE TITLE
ts-node shoot error Property 'foo' does not exist on type 'FastifyInstance<…>'

### ISSUE THREAD

**Issue by LeeMoonki** [fastify/help#415]
## 💬  ts-node shoot error `Property 'foo' does not exist on type 'FastifyInstance<…>'`

I'm making a fastify plugin using fastify decorator. Following is my sample code.

```javascript
import { FastifyPluginAsync } from 'fastify';
import fp from 'fastify-plugin';

interface RegistFooOptions {
  barValue: string;
}

const registFooPlugin: FastifyPluginAsync<RegistFooOptions> = async (
  fastify,
  options
) => {
  fastify.decorate('foo', {
    bar: options.barValue,
  });
};

export default fp(registFooPlugin);

```

And I use it in `server.ts` like

```javascript
fastify.register(registFooPlugin, {
 barValue: 'bar!',
});
```

Following the [comment](https://github.com/fastify/fastify/issues/1417#issuecomment-458601746), I also defined the `projectdir/@types/index.d.ts`

```typescript
/* eslint-disable @typescript-eslint/no-unused-vars */
import fastify from 'fastify';

declare module 'fastify' {
  export interface FastifyInstance<
    HttpServer = Server,
    HttpRequest = IncomingMessage,
    HttpResponse = ServerResponse
  > {
    foo: {
      bar: string;
    };
  }
}

```

Then, I could use the decorated value `foo.bar` in fastify route like below

```javascript
interface IBody {...}
fastify.post<{ Body: IBody }>('/', async function (request, reply) {
    const {...} = request.body;
    const barValue = await this.foo.bar;

    console.log(barValue); // expect to show 'bar!'

    return { success: true };
  });
```
it means that **there is no typescript lint error**.

**But when I run server with ts-node the following error occurred**

`Property 'foo' does not exist on type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance>'` 

How can I fix this error ?

## Your Environment

- *node version*: 14.15.5
- *fastify version*: ^3.12.0
- *os*: Mac
- *@types/node*: ^14.14.31
- *ts-node*: ^9.1.1

**Comment by mcollina** [comment]
cc @fastify/typescript

**Comment by zekth** [comment]
You're declaring `FastifyInstance<Server, IncomingMessage, ServerResponse>` not `FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance>`

**Comment by LeeMoonki** [comment]
> You're declaring `FastifyInstance<Server, IncomingMessage, ServerResponse>` not `FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance>`

I replaced the `Instance Fastify<...>` with
```typescript
declare module 'fastify' {
  export interface FastifyInstance<
    HttpServer = Server,
    HttpRequest = IncomingMessage,
    HttpResponse = ServerResponse,
    Logger = FastifyLoggerInstance
  > {
    foo: {
      bar: barValue;
    };
  }
}
```
, but still the error comes up.
```
error TS2339: Property 'foo' does not exist on type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance>'.

13     const barValue = await this.foo.bar;
```

Additionally, here is my `tsconfig.json`

```json
{
  "compilerOptions": {
    "lib": ["es2019", "es2020.promise", "es2020.bigint", "es2020.string"],
    "module": "commonjs",
    "target": "es2019",
    "typeRoots": ["@types"],

    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "exclude": ["node_modules"],
}
```

**Comment by climba03003** [comment]
The problem is in your `tsconfig.json` files, `"typesRoots": ["@types"]` which restrict TypeScript to only find the folder in `./@types` but not `node_modules/@types`. Which means that `@types/node` is not imported and you cannot augment the types without `@types/node`.

You can solve it by one of the following ways:
1. Use `"typesRoots": ["@types", "node_modules/@types"]` 
2. Remove `"typesRoots"`
3. Add `"types": ["@types/node"],`

**Comment by LeeMoonki** [comment]
> The problem is in your `tsconfig.json` files, `"typesRoots": ["@types"]` which restrict TypeScript to only find the folder in `./@types` but not `node_modules/@types`. Which means that `@types/node` is not imported and you cannot augment the types correctly without `@types/node`.
> 
> `typesRoots` is a very restrictive options, only use it when you really know what types should be included and which types is really needed. Otherwise, I would recommend using `types` and it will not affect the `types` import from your code.
> 
> You can solve it by one of the following ways:
> 
> 1. Use `"typesRoots": ["@types", "node_modules/@types"]`
> 2. Remove `"typesRoots"`
> 3. Add `"types": ["@types/node"],`

I tried to run the project with following config

```json
{
  "compilerOptions": {
    "lib": ["es2019", "es2020.promise", "es2020.bigint", "es2020.string"],
    "module": "commonjs",
    "target": "es2019",
    "types": ["@types/node"],

    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "exclude": ["node_modules"],
}
```

but still unsloved...
I also tried to insert `"typeRoots": ["@types", "node_modules/@types"] into the config but this don't resolve the issue.

**Comment by climba03003** [comment]
Then, please provide a reproducible code example for us to analysis the issue. I can solve it by using `types` in my computer.

**Comment by LeeMoonki** [comment]
> Then, please provide a reproducible code example for us to analysis the issue. I can solve it by using `types` in my computer.
> 
> You can check my example for this issue from https://github.com/climba03003/repo-help-415.

The real code is in [this repository](https://github.com/LeeMoonki/sei-whale/tree/dev/services/server), you can run by `yarn dev`. I tried again, but not work. Thanks for your help !!

**Comment by climba03003** [comment]
Use this for the augmentation, you don't need to specify the types for `Server, Request, Response, Logger` and export.
```ts
declare module 'fastify' {
  interface FastifyInstance {
    services: {
      user: IUserApplicationService;
    };
  }
}
```

**Comment by LeeMoonki** [comment]
> Use this for the augmentation, you don't need to specify the types for `Server, Request, Response, Logger` and export.
> 
> ```ts
> declare module 'fastify' {
>   interface FastifyInstance {
>     services: {
>       user: IUserApplicationService;
>     };
>   }
> }
> ```

Error comes up though I change with it.

**Comment by climba03003** [comment]
I think you should clean your environment and reinstall all the packages. I can build it without any error.
![image](https://user-images.githubusercontent.com/23028015/115179731-9369eb00-a106-11eb-8d5f-8be549e0b55b.png)

**Comment by LeeMoonki** [comment]
@climba03003 

First of all, I couldn't run `tsc -p tsconfig.json` with error `error TS5014: Failed to parse file 'tsconfig.json/tsconfig.json': Unexpected token u in JSON at position 0.` and if we run ts-node without `-T` option(`--transpile-only`), i.e. `ts-node server.ts`, the error shown again.

**Comment by climba03003** [comment]
I have no way to assist you further as I cannot reproduce your error. The fix and the command result I have posted in the above comment.

Note: I am running the command inside `services/server` directory and I am not using docker.

**Comment by RafaelGSS** [comment]
Just to feedback:

I've cloned the repository and made the following steps and it works as expected:

```sh
sei-whale/services/server$ git status
On branch dev
Your branch is up to date with 'origin/dev'.

sei-whale/services/server$ yarn install
yarn install v1.22.5

sei-whale/services/server$ yarn dev
yarn run v1.22.5
$ nodemon
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts
[nodemon] starting `ts-node -T server.ts`
[1618835131529] INFO (17699 on rafaelgss): Server listening at http://0.0.0.0:3000

sei-whale/services/server$ yarn build
yarn run v1.22.5
$ tsc -p tsconfig.json
Done in 1.21s.
```

Likely is something wrong with your environment.

**Comment by LeeMoonki** [comment]
What I want is that run the fastify server using `ts-node` without `-T` option, i.e. `ts-node server.ts` not `ts-node -T server.ts`. When I run without `-T` option the error comes up. The above results still run with `ts-node -T server.ts`

**Comment by climba03003** [comment]
I figure out whats is the main problem. The `@types/index.d.ts` is never imported as the type reference when you are using `ts-node server.ts`.

Please move the type to any file that will actually executed with `server.ts`. I have move it to `services\app\UserApplicationService.ts` and it works fine.

**Comment by LeeMoonki** [comment]
> I figure out whats is the main problem. The `@types/index.d.ts` is never imported as the type reference when you are using `ts-node server.ts`.
> 
> Please move the type to any file that will actually executed with `server.ts`. I have move it to `services\app\UserApplicationService.ts` and it works fine.
> 
> Note: Do not separate the type and the logic when you are using TypeScript. It will not recognize any `d.ts` file when it is not actually imported.

Yes, it works ! Thank you so much!

**Comment by Albert-Gao** [comment]
Really great thread, is there a way we type the `decorateRequest()` method? Thanks :)

**Comment by YChebotaev** [comment]
Same problem with me

<img width="538" alt="Screenshot 2023-11-29 at 18 08 24" src="https://github.com/fastify/help/assets/5302856/91dbdaef-0347-4c34-b7bb-c7552b3b05c0">

<img width="790" alt="Screenshot 2023-11-29 at 18 08 40" src="https://github.com/fastify/help/assets/5302856/a03a46e9-443e-46a5-b09e-b563712a0da0">
