### ISSUE TITLE
Why body schema doesn't work for PATCH request

### ISSUE THREAD

**Issue by bizprat** [fastify/help#416]
While reading the docs about fastify routing, visited the page [validation and serialization](https://www.fastify.io/docs/v2.2.x/Validation-and-Serialization/).

Here I found that body schema validation will only work for POST or PUT request.

The exact line written under "Validation" section.
> body: validates the body of the request if it is a POST or a PUT.

So my question is, What to do if I want to use PATCH request?
![Screenshot](https://user-images.githubusercontent.com/41962643/115263854-642d9b00-a153-11eb-9dcb-1ad31b8fac83.png)

**Comment by Eomm** [comment]
It works, the docs are wrong: would you like to send a PR to fix it?

```
const fastify = require('fastify')()

fastify.patch('/', {
  schema: {
    body: {
      type: 'object',
      properties: {
        foo: { type: 'integer' }
      }
    }
  }
}, async (request, reply) => {
  return request.body
})
fastify.inject({
  url: '/',
  method: 'PATCH',
  payload: {
    foo: 'not a numbers'
  }
}, (err, res) => {
  console.log(res.payload)
  // {"statusCode":400,"error":"Bad Request","message":"body.foo should be integer"}
})

```

The body is not validated only on GET and HEAD fwik

**Comment by bizprat** [comment]
Thanks @Eomm  for the confirmation.

I have already sent PR to fix it.
