### ISSUE TITLE
Request parameter sepcified as formData type in fastify-swagger is not found on the post request 

### ISSUE THREAD

**Issue by DenisVoloshin** [fastify/help#420]
**The problem description** 

My Fastify server is Restful API (using fastify-swagger the version mentioned below)
The swagger specification is provided as a YAML file.
I'm trying to implement a post request and pass the formData parameter. 
I tried various swagger configurations unfortunately without success.
Note, another post param type works properly like header or body.
I create a very simple test to demonstrate the issue I run into.
Probably I'm missing something trivial. Pls take a look and run my test.

**Server**
```js
let fastify = require('fastify')();

/**
 * Setup an fastify server and define port to listen all incoming requests for this application
 */
const setUpFastify = () => {

    fastify.setNotFoundHandler((request, reply) => {
        reply.code(404).type('text/html').send();
    });

    fastify.post('/sample/post', function (req, reply) {
        reply.status(req.params["formDataParam"] ? 200 : 500).
        send(req.params["formDataParam"] ? req.params["formDataParam"] : "param undefined");
    });

    /*******************************************/
    // Run the server!
    const start = async () => {
        try {
            await fastify.register(require("fastify-swagger"), {
                mode: 'static',
                exposeRoute: true,
                routePrefix: '/sample',
                specification: {
                    path: './swagger/form-data-test.yaml'
                }
            });

            fastify.listen(8080, () => {
                fastify.swagger();
                console.log(`Worker listening on ` + 8080 + ` PID: ${process.pid}`)
            });
        } catch (err) {
            fastify.log.error(err);
            process.exit(1)
        }
    };

    start();
};
const setupServer = () => {
    setUpFastify();
};

setupServer();

module.exports = {
    fastify: fastify
};
```

 **swagger specification**
```yaml
openapi: 3.0.0
info:
  version: "1.0.0"
tags:
  - name: Actions
paths:
  /sample/post:
    post:
      tags:
        - Actions
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - in: header
          name: x-api-key
          schema:
            type: string
          required: false
        - in: formData
          name: formDataParam
          schema:
            type: string
          required: true
      responses:
        200:
          description: 'Returns OK  is processed successfully'
        404:
          description: 'Returns  on error '
          content:
            application/json:
              schema:
                type: object
                example: {}
        400:
          description: 'Bad request format'
        505:
          description: 'Fatal server error'

```

#### What was the result you received?
_formDataParam_ is undefined while handling a post request, the reuquest has no params

#### What did you expect?
_formDataParam_ should have a value.

#### Context

* *node version*: v12.13.1
* *fastify version*: 3.15.0
* *fastify-swagger*: 4.7.0
* *os*: Mac

**Comment by mcollina** [comment]
Adding a _static_ swagger spec does not do anything to your route. You need to configure your route properly and even add the validation schema as it won't be added automatically.

**Comment by climba03003** [comment]
You are using `OpenAPIv3` and the `formData` from `parameter` is the syntax for `Swagger2.0`. That's why it cannot show in the UI.
Please do not mix the syntax for `OpenAPIv3` and `Swagger2.0`.

Read More: https://swagger.io/docs/specification/describing-request-body

**Comment by DenisVoloshin** [comment]
thanks for the quick response, I will try you recommendations, I knew that was missing something stupid
