### ISSUE TITLE
ts-node with fastify

### ISSUE THREAD

**Issue by TriStarGod** [fastify/help#421]
## 💬  Question here 
I used fastify-cli to setup a typescript project
`npx fastify-cli generate daflop-fastify-ts --lang=ts`

However, I'm having issues with dev experience. When I run `npm run dev`, it executes `"tsc && concurrently -k -p \"[{name}]\" -n \"TypeScript,App\" -c \"yellow.bold,cyan.bold\"  \"tsc -w\" \"fastify start -w -l info -P dist/app.js\""`, but the dev experience is annoying when the cache causes errors anytime I rename things (which I do often).

I'm trying to use `nodemon` with `ts-node`. How would I re-implement this dev with these packages?

## Done so far

I created a nodemon.json file with
```
{
	"watch": ["src"],
	"ignore": [],
	"ext": "ts,js",
	"exec": "fastify start -w -l info -P ts-node src/app.ts"
}
```

## Your Environment

- *node version*: 14.15.4
- *fastify version*: 3
- *os*: Windows

**Comment by mcollina** [comment]
cc @fastify/typescript

**Comment by TriStarGod** [comment]
My solution was to not to use fastify-cli's start. I instead created a server.ts file

```
// File used to run fastify without fastify-cli (ie fastify start) and for potential ts-node integration
const server = f(ISDEV ? { logger: true } : {});
server.register(app);
server.listen(ENV.PORT || 3000, (ex) => {
	if (ex) {
		server.log.error(ex);
		process.exit(1);
	}
});
```

And run nodemon with config

```
{
	"watch": [
		"src"
	],
	"ignore": [],
	"ext": "ts,js",
	"exec": "ts-node src/server.ts | pino-colada"
}
```

Still would like the "correct" solution

**Comment by climba03003** [comment]
I do not use `fastify-cli` and I start my server with the command below.
`nodemon src/index.ts --watch src`

I think your problem can be solve by https://github.com/fastify/fastify-cli/pull/352

**Comment by TriStarGod** [comment]
@climba03003 I was using fastify-cli `generate` option (ie `npx fastify-cli generate fastify-ts --lang=ts` ). Unfortunately, it didn't include a server file and would run with command `"dev": "fastify start -w -l info -P ts-node src/app.ts"`. It was a bit too magical. Anyway, I think I like my new setup with `server.ts` since I was wondering if it handled server shutdowns properly. Thanks your input!
