### ISSUE TITLE
Default handler

### ISSUE THREAD

**Issue by tones31** [fastify/help#426]
I have been using 2.1 for a while and had a default handler such as 

```js
fastify.register(wss, {
    handle: (connection) => {
        // do stuff
    }
});
```

I see in 3.x that this on longer works and was wondering what the migration process is. I don't really understand how I can use HTTP routes with a websocket client as it just sends text/binary, so maybe I am missing something. All of my websocket messages are currently JSON objects with something like `event: 123` and a big ol' switch statement to handle the message. 

Is there a migration doc somewhere or can I get that default handler back somehow? Thanks.

**Comment by Eomm** [comment]
I think this should work, check the wildcard on the route

```
fastify.register(require('fastify-websocket'), {
  options: { maxPayload: 1048576 }
})


fastify.get('/*', { websocket: true }, (connection /* SocketStream */, req /* FastifyRequest */) => {
  connection.socket.on('message', message => {
    // message === 'hi from client'
    connection.socket.send('hi from wildcard route')
  })
})
```

Looking a bit at the plugin, It seems that the feature is no longer supported, but a double-check would be better

**Comment by tones31** [comment]
Oh, how did I post this on fastify's github. Oops. Thanks though, I will close this.
