### ISSUE TITLE
How to type custom body in preValidation hook

### ISSUE THREAD

**Issue by StarpTech** [fastify/help#427]
## 💬  Question here

As titled.

```ts
interface Custom {
  Body: { service_name: string }
}

export const checkUserServiceScope: preValidationHookHandler = function (req: FastifyRequest<Custom>, res, next) {
  if (req.user && !req.user.services.find((service) => service === req.body.service_name)) {
    const err = InvalidServiceScope(req.body.service_name)
    return next(err)
  }
  next()
}

export default function registerSchema(fastify: FastifyInstance) {
  fastify.post<{ Body: RegisterRequest }>(
    '/schema/push',
    { schema, preValidation: [checkUserServiceScope] },
    async (req, res) => {
...
````

Error:

```ts
Type '(req: FastifyRequest<CustomBody, Server, IncomingMessage>, res: FastifyReply<Server, IncomingMessage, ServerResponse, RouteGenericInterface, unknown>, next: HookHandlerDoneFunction) => void' is not assignable to type 'preValidationHookHandler<Server, IncomingMessage, ServerResponse, RouteGenericInterface, unknown>'.
  Types of parameters 'req' and 'request' are incompatible.
    Type 'FastifyRequest<RouteGenericInterface, Server, IncomingMessage>' is not assignable to type 'FastifyRequest<CustomBody, Server, IncomingMessage>'.
      Type 'RouteGenericInterface' is not assignable to type 'CustomBody'.
        Types of property 'Body' are incompatible.
          Type 'unknown' is not assignable to type '{ service_name: string; }'.

57 export const checkUserServiceScope: preValidationHookHandler = function (req: FastifyRequest<CustomBody>, res, next) {
```

## Your Environment

- *node version*: 14
- *fastify version*: >=3
- *os*: Linux

**Comment by climba03003** [comment]
```ts
import * as Fastify from "fastify";

interface Custom {
  Body: { service_name: string };
}

const checkUserServiceScope = function (
  req: Fastify.FastifyRequest<Custom>,
  res,
  next
) {
  next();
};

function registerSchema(fastify: Fastify.FastifyInstance) {
  fastify.post<Custom>(
    "/schema/push",
    {
      schema: {},
      preValidation: [checkUserServiceScope],
    },
    async function () {}
  );
}
```

**Comment by StarpTech** [comment]
Hi, @climba03003 thanks for the workaround. This requires typing `res`, `next` manually.

```ts
export const checkUserServiceScope = function (
  req: FastifyRequest<ServiceScopedPayload>,
  res: FastifyReply,
  next: HookHandlerDoneFunction,
) {
```

It would be great to ignore internals.
```ts
export const checkUserServiceScope: preValidationHookHandler<Request, Reply> = function (req, res, next) {
....
```

**Comment by climba03003** [comment]
> Hi, @climba03003 thanks for the workaround. This requires typing `res`, `next` manually.
> 
> ```ts
> export const checkUserServiceScope = function (
>   req: FastifyRequest<ServiceScopedPayload>,
>   res: FastifyReply,
>   next: HookHandlerDoneFunction,
> ) {
> ```
> 
> It would be great to ignore internals.
> ```ts
> export const checkUserServiceScope: preValidationHookHandler<Request, ...> = function (req, res, next) {
> ....
> ```

Yes, passing the RouteGenericInterface as first  parameter would be great. But it will be a breaking change and I do not expect it will comes that soon.

**Comment by StarpTech** [comment]
Nevermind. I got it. The route type `fastify.post<{ Body: RegisterRequest }>` specifies the schema 👍

**Comment by StarpTech** [comment]
I have to correct myself. Why is `req` inside `checkUserServiceScope` not aware of `RegisterRequestContext` ?

```ts
fastify.post<RegisterRequestContext>(
    '/schema/push',
    { schema, preValidation: [checkUserServiceScope] },
    async (req, res) => {
````

**Comment by climba03003** [comment]
> 
> 
> I have to correct myself. Why is `req` inside `checkUserServiceScope` not aware of `RegisterRequestContext` ?
> 
> ```ts
> fastify.post<RegisterRequestContext>(
>     '/schema/push',
>     { schema, preValidation: [checkUserServiceScope] },
>     async (req, res) => {
> ```

TypeScript is not smart enough to infer the types from outside.

**Comment by StarpTech** [comment]
> If you do not extract the function and use inline function, it will work correctly.

Indeed
