### ISSUE TITLE
Custom Auth Plugin getting undefined in Route Definition 

### ISSUE THREAD

**Issue by healthyl** [fastify/help#43]
Im setting up a Fastify Rest-Api and wrote a Plugin to encapsulate my authentication logic which is based on JWT. Im using the preHandler Hook on each route that i want to protect but it seems that the beforeHandler or my plugin just gets ignored since i can just make a request without a token at all and get the data.

I looked up every piece of documentation but still cannot get it running. If i just console.log() my function fastify.authenticate i get an undefined.

This is my plugin customJwtAuth:
```
const fp = require('fastify-plugin')

async function customJwtAuth(fastify, opts, next) {

//register jwt 
 await fastify.register(require('fastify-jwt'),
    {secret: 'asecretthatsverylongandimportedfromanenvfile'})

fastify.decorate('authenticate', async function(request, reply) {
 try {
   const tokenFromRequest = request.cookies.jwt

  await fastify.jwt.verify(tokenFromRequest, (err, decoded) => {
     if (err) {
       fastify.log.error(err)
       reply.send(err)
    }
     fastify.log.info(`Token verified: ${decoded}`)
  })
  } catch (err) {
  reply.send(err)
  fastify.log.error(err)
  }
 })
next()
}
module.exports = fp(customJwtAuth, {fastify: '>=1.0.0'})
```
I register this plugin like this in my main server.js file:
```
  const customJwtAuth = require('./plugin/auth')
  fastify.register(customJwtAuth).after(err => {if (err) throw err})
```
Then i apply my function like this to the routes:
```
const fastify = require('fastify')
const productHandler = require('../handler/productHandler')

const productRoutes = [
  {
  method: 'GET',
  url: '/api/product',
  beforeHandler: [fastify.authenticate],
  handler: productHandler.getProducts
  }, ... ]
```
The api shouldnt return any Data if the request doesnt include a signed jwt or without a jwt at all.

**Comment by nwoltman** [comment]
Your `customJwtAuth` plugin is an `async` function and it uses an `await` statement. This means that your `fastify.decorate('authenticate', ...)` line will happen on a later tick of the event loop, so your decorator is getting registered, but it gets registered *after* you try to use it in your route definition.

Using `await` in your plugin is unnecessary

```js
//register jwt 
 await fastify.register(require('fastify-jwt'),
    {secret: 'asecretthatsverylongandimportedfromanenvfile'})
```

because `fastify.register()` does not return a promise (it returns `fastify`). If you remove `await` from that line, everything should work as expected.

Also, using both an `async` plugin function and the `next()` plugin callback is unnecessary. You only need to choose one of those. Since you can remove the `await` keyword, you can also remove the `async` keyword from your `customJwtAuth` function.

**Comment by healthyl** [comment]
Hi! Thank you for taking time to help me! I removed all async's and await's from the plugin and im getting another error now. 

```
opts.beforeHandler[i] = h.bind(_fastify)      
                         ^
TypeError: Cannot read property 'bind' of undefined
    at opts.beforeHandler.forEach (C:\Users\Alienware\Desktop\fastify-backend\node_modules\fastify\fastify.js:627:39)
    at Array.forEach (<anonymous>)
    at afterRouteAdded (C:\Users\Alienware\Desktop\fastify-backend\node_modules\fastify\fastify.js:626:30) ....
```
I defined the routes in an array like this :
``` 
const productRoutes = [
  {
  method: 'GET',
  url: '/api/product',
  beforeHandler: [fastify.authenticate],
  handler: productHandler.getProducts
  }, ... ]
```
in my main server.js i iterate over the array and and register each route like this:
``` 
productRoutes.forEach((route) => {
    fastify.route(route)
   })
```
Thank you very much in advance!

**Comment by nwoltman** [comment]
Oh I see another problem now. Where you define your routes:

```js
const fastify = require('fastify')
const productHandler = require('../handler/productHandler')

const productRoutes = [
  {
  method: 'GET',
  url: '/api/product',
  beforeHandler: [fastify.authenticate],
  handler: productHandler.getProducts
  }, ... ]
```

you're trying to define the routes on the `fastify` package instead of the instance that you registered the plugin on. You'll need to pass the `fastify` instance you created in `server.js` down to where you define your routes for it to work properly. You can do that in a clean way by making your routes like a plugin:

```js
const productHandler = require('../handler/productHandler')

function productRoutes(fastify, opts, next) {
  fastify.route({
    method: 'GET',
    url: '/api/product',
    beforeHandler: [fastify.authenticate],
    handler: productHandler.getProducts
  })
  // etc.

  next()
}

module.exports = productRoutes
```

server.js
```js
const customJwtAuth = require('./plugin/auth')
const productRoutes = require('./productRoutes')

fastify.register(customJwtAuth).after(err => {if (err) throw err})
fastify.register(productRoutes)
```

**Comment by healthyl** [comment]
Thank you very much mate for your time and effort, its working now. You're a lifesaver!

**Comment by nwoltman** [comment]
Awesome! Glad it's working now 😃

**Comment by Vignesh1696** [comment]
/home/ibytecode/Desktop/git-repo/review-api/node_modules/fastify/lib/route.js:208
        opts.handler.bind(this),
                     ^

TypeError: opts.handler.bind is not a function
    at Object.afterRouteAdded (/home/ibytecode/Desktop/git-repo/review-api/node_modules/fastify/lib/route.js:208:22)
    at /home/ibytecode/Desktop/git-repo/review-api/node_modules/fastify/lib/route.js:170:25
    at Object._encapsulateThreeParam (/home/ibytecode/Desktop/git-repo/review-api/node_modules/avvio/boot.js:468:7)
    at Boot.timeoutCall (/home/ibytecode/Desktop/git-repo/review-api/node_modules/avvio/boot.js:379:5)
    at Boot.callWithCbOrNextTick (/home/ibytecode/Desktop/git-repo/review-api/node_modules/avvio/boot.js:360:19)
    at Boot._after (/home/ibytecode/Desktop/git-repo/review-api/node_modules/avvio/boot.js:235:26)
    at Plugin.exec (/home/ibytecode/Desktop/git-repo/review-api/node_modules/avvio/plugin.js:89:17)
    at Boot.loadPlugin (/home/ibytecode/Desktop/git-repo/review-api/node_modules/avvio/plugin.js:187:10)
    at Task.release (/home/ibytecode/Desktop/git-repo/review-api/node_modules/fastq/queue.js:140:16)
    at worked (/home/ibytecode/Desktop/git-repo/review-api/node_modules/fastq/queue.js:182:10)
    at /home/ibytecode/Desktop/git-repo/review-api/node_modules/avvio/plugin.js:190:7
    at done (/home/ibytecode/Desktop/git-repo/review-api/node_modules/avvio/plugin.js:136:5)
    at check (/home/ibytecode/Desktop/git-repo/review-api/node_modules/avvio/plugin.js:147:7)



i had this issue in fastify js,can any one help me!!!!

**Comment by RafaelGSS** [comment]
We need some context and essentially a reproduction code. If the problem doesn't correlation with this issue, I suggest you open a new issue.
