### ISSUE TITLE
set fastify-swagger version programmatically 

### ISSUE THREAD

**Issue by DenisVoloshin** [fastify/help#430]
Trying to set fastify-swagger version programmatically which is provided via ENV VAR

The fastify-swagger is based on openapi: 3.0.0

Here is the code I use to register and init fastify-swagger, the swagger specification is provided as a YAML file

```js
             await fastify.register(require("fastify-swagger"), {
                mode: 'static',
                exposeRoute: true,
                routePrefix: '/deployment',
                specification: {
                    path: './swagger/deployment-api.yaml'
                },
                openapi: {
                    info: {
                        version: '2.1.0' // here I want to provide a dymanic value like (version: VERSION)
                    }
                }
            });

            fastify.listen(port, localhost ? localhost : "localhost", () => {
                fastify.swagger();
                logger.info(`Worker listening on ` + port + ` PID: ${process.pid}`)
            });
```

#### What was the result you received?

The result is -  I don't see the version value shows up in the UI.

#### Context

* *node version*: 12.13.1
* *fastify version*: >=3.15.0
* *os*: Mac
* *any other relevant information*:

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by DenisVoloshin** [comment]
no sure I got your comment, did you address it to me, if yes, I'm not a contributor.

**Comment by mcollina** [comment]
You could be one! :)

**Comment by DenisVoloshin** [comment]
Thanks, sounds tempting... very tempting, will be glad to contribute but then I have to stop sleeping :).
So you are saying, at the moment the version value update dynamically it's not supported?
Probably there is a workaround that comes to your mind.
I would expect to see it as a basic functionally

**Comment by mcollina** [comment]
Not that I know of.

**Comment by climba03003** [comment]
> 
> 
> Thanks, sounds tempting... very tempting, will be glad to contribute but then I have to stop sleeping :).
> So you are saying, at the moment the version value update dynamically it's not supported?
> Probably there is a workaround that comes to your mind.
> I would expect to see it as a basic functionally

`Static` mode means everything is static and which all comes from the specification file. If you need something `dynamic`, you should use `dynamic` mode. Mixing `static` and `dynamic` mode is hard and easy to mess up.

The workaround should be dynamic generate the static file.
