### ISSUE TITLE
setErrorHandler question

### ISSUE THREAD

**Issue by diwic** [fastify/help#435]
## 💬  How does one integrate error handling?

Hi and thanks for providing a help forum!

I'm new to fastify and I'm trying to understand how `setErrorHandler` works.

What I'm trying to do is: If the schema validation failed or similar, it's okay to tell the client what went wrong, but if the client managed to cause an internal server error, don't tell the client the details.

Something like:

```js
app.setErrorHandler(function (error, request, reply) {
    const statusCode = ???;
    if (statusCode >= 400 && statusCode <= 500) {
        console.warn(error);
        // The client did something wrong, okay to tell it what it is
        return doFastifysNormalErrorHandling();
    }
    // The error is within the server, don't tell the client what it is
    console.error(error);
    reply.code(statusCode || 500).send("500 Internal server error");
});
```

I've tried to use `error.statusCode` to figure out what type of error it is, but it seems to be "undefined" for a schema validation error. Also I'm not sure what I should call instead of `doFastifysNormalErrorHandling`, according to the documentation, `fastify.errorHandler` only logs the error without sending it.

## Your Environment

- *node version*: 14
- *fastify version*: >= 3.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by mcollina** [comment]
You can check the `err.validation` and a `err.validationContext` property.

**Comment by diwic** [comment]
After some further reading in fastify's source code I found that `reply.raw.statusCode` was set to 400 on validation errors, so I was able to do something like:

		app.setErrorHandler((error, request, reply) => {
			const statusCode = error.statusCode || error.status || reply.raw.statusCode;
			if (statusCode >= 400 && statusCode < 500) {
				console.warn(`Sending error ${statusCode} for ${request.url}: ${error.message}`);
				reply.code(statusCode).send(error);
				return;
			}
		        console.error(`Error while handling ${request.url}: ${error}`);
			reply.code(500).send("500 Internal server error");
		});
