### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by abhishekdhadwal** [fastify/help#439]
how can i use joi with fastify

**Comment by climba03003** [comment]
Check the document
https://github.com/fastify/fastify/blob/main/docs/Validation-and-Serialization.md#using-other-validation-libraries

**Comment by abhishekdhadwal** [comment]
![Screenshot from 2021-05-12 15-48-07](https://user-images.githubusercontent.com/41069780/117959306-802ef180-b339-11eb-8c5a-ec6487b780db.png)
not working

**Comment by climba03003** [comment]
`fastify-swagger` do not work with any custom validator. You need to find your own way.

**Comment by abhishekdhadwal** [comment]
okk
