### ISSUE TITLE
Global error handling

### ISSUE THREAD

**Issue by PacoDu** [fastify/help#44]
Is there any way to disable fastify encapsulated error handling (c.f. https://www.fastify.io/docs/v2.0.x/Server/#seterrorhandler) ? 
This can be painful to manage error in an application that is encapsulated in multiple sub modules (`fastify-plugin`) without having the possibility to manage errors in a centralized error handler (for example to manage http status code depending on the error type).

#### What are you trying to achieve or the steps to reproduce?

I would like to be able to disable encapsulated error handling in order to declare a global error handler in my main plugin.

#### index.js
```js
const app = Fastify({
  logger,
  pluginTimeout: 10000
})

app.register(require('./app.js'))

app.setErrorHandler(mainErrorHandler) // Does not catch anything

app.listen(process.env.PORT || 3000, process.env.IP || '127.0.0.1', (err) => {
  if (err) {
    app.log.error(err)
    process.exit(1)
  }
})
```

#### app.js
```javascript
module.exports = async app => {
  // Register token plugin
  app.register(require('./plugins/token'))
  
  // Register auth plugin
  app.register(require('./plugins/auth'))

  // // Register user service
  app.register(require('./services/user'))
  
  // Register GQL endpoint
  app.register(require('./gql'))
}
```

#### Context

* *node version*: 11
* *fastify version*: >=1.13.0

**Comment by delvedor** [comment]
Hello!
If you declare the error handler in the top level, it should work as "global".
Can you upload a full example to reproduce?

**Comment by PacoDu** [comment]
Hello !

You are right, this works if the plugin doesn't declare an error handler ! But if the plugin declare an error handler there is no way for the higher level application to override this behavior.

This is a complete example:

#### index.js
```javascript
'use strict'

const Fastify = require('fastify')

const app = Fastify({
  logger: {
    prettyPrint: true
  }
})

app.setErrorHandler(async (error, req, reply) => {
  console.log('MAIN ERROR HANDLER')
  reply.status(500)
  reply.send()
})

app.register(require('./submodule'))

app.inject({
  method: 'GET',
  url: '/submodule'
})
```

#### submodule.js
```javascript
'use strict'

module.exports = async (app, opts) => {
  app.setErrorHandler(async (error, req, reply) => {
    console.log('SUBMODULE ERROR HANDLER')
    reply.status(500)
    reply.send()
  })

  app.get('/submodule', async (req, reply) => {
    throw Error('test')
  })
}
```

If you don't remove `setErrorHandler` from the plugin it will print `SUBMODULE ERROR HANDLER` and never go through the main error handler.
Thanks for the clarification, at least this works for my custom plugins :+1:

**Comment by mcollina** [comment]
That works exactly as expected. If a plugin specify an error handler, that should always take precedence. That's true and consistent with all APIs in Fastify that are encapsulated. There is no ovveride. The correct approach is what I've suggested in https://github.com/mcollina/fastify-gql/pull/28, let the plugin provide an option to disable the installed error handler.

**Comment by PacoDu** [comment]
Yes, when I wrote this issue it was not clear for me if this was due to my usage of setErrorHandler or the library I was using. 

In my case I wasn't able to catch errors due to fastify-gql error handler. That's why I wrote this PR on fastify-gql as everything is handled through one route managed by the plugin.

I think we can close this issue now, this statement clarified my problem:
> If you declare the error handler in the top level, it should work as "global".

And the fact that if a plugin define an error handler it can't be catched by an higher plugin.

Thanks for the quick help !

**Comment by akloketa** [comment]
how to correct this error       ////////////////////////////
[*] Service: facebook 
[*] Checking if username exists...
Traceback (most recent call last):
  File "/usr/local/bin/brut3k1t", line 11, in <module>
    load_entry_point('brut3k1t==3.0.1', 'console_scripts', 'brut3k1t')()
  File "build/bdist.linux-x86_64/egg/brut3k1t/__main__.py", line 89, in main
  File "build/bdist.linux-x86_64/egg/brut3k1t/web.py", line 47, in execute
  File "build/bdist.linux-x86_64/egg/brut3k1t/web.py", line 56, in usercheck
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by naveen1337** [comment]
But I want to write my own custom error message in all place, I don't want to accidentally expose my app errors in production
