### ISSUE TITLE
Exaple doesn't work

### ISSUE THREAD

**Issue by hs-dev-web** [fastify/help#442]
I tried this example mentioned in the docs:

https://github.com/fastify/example/blob/HEAD/validation-messages/custom-errors-messages.js

but the error message I got was:

> querystring should have required property 'name'

instead of: 

> 'my custom message'

why is that?

### And one thing, you should tell people to install ajv-errors@1 instead of the latest one which is not support ajv@6 used by fastify

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue?

**Comment by luisorbaiceta** [comment]
I just created a pull request solving this issue. As about the version of ajv-errors I don´t think It is something concerning the fastify framework. If you are customizing the default behaviour of the ajv instance with another third party plugin, you are the one responsible for doing this checks
