### ISSUE TITLE
Help regarding replyOptions.queryString in a fastify-http-proxy proxy

### ISSUE THREAD

**Issue by jenseneducation-mattias-von-vogelsang** [fastify/help#443]
## 💬  Question here 

Greetings! I have a small node.js server with fastify in which I want to proxy requests to an external API with fastify-http-proxy. This external API wants their api key as a query parameter. I want to add this query parameter containing the apikey in the server proxy, not from the actual request coming from the front-end. However, it seems impossible since replyOptions.queryString overrides the original request queries, when I try to add the api key since it does not seem to have access to request.query. Any help would be appreciated, hard to find information regarding this. The proxy works as intented if the original request has the apikey as query parameter.

```js
let originalRequestQueries = {};

fastify.register(proxy, {
  upstream: CONFIG.externalApi,
  prefix: '/api/stocks',
  undici: true,
  replyOptions: {
    queryString: {
      ...originalRequestQueries,
      apikey: CONFIG.apiKey,
    },
  },
  preHandler: async (req, reply) => {
    try {
      await req.jwtVerify();
      originalRequestQueries = req.query;
      console.log(originalRequestQueries);
    } catch (err) {
      throw boom.boomify(err);
    }
  },
});
````

If possible add a link to sample codes for error reproduction (github or replit)

## Your Environment

- *node version*: 15.12.0
- *fastify version*: 3.15.1
- *os*: Mac

**Comment by mcollina** [comment]
Could you add a failing example that I can run?

**Comment by jenseneducation-mattias-von-vogelsang** [comment]
Absolutely, give me a minute and I'll get one up on github for you

**Comment by jenseneducation-mattias-von-vogelsang** [comment]
https://github.com/jenseneducation-mattias-von-vogelsang/fastify-proxy-example
here is a very small example repository

here is the API we are using, its free to sign up for a api-key if you would be so kind to do that: https://twelvedata.com/

**Comment by mcollina** [comment]
This use case is not supported by fastify-http-proxy, you might have to use https://github.com/fastify/fastify-reply-from directly or send a PR to fastify-http-proxy:
https://github.com/fastify/fastify-http-proxy/blob/984f677e6cc85e03fd2ea5ac22873e4a6e73ab54/index.js#L183-L187 needs to call some new option method.

**Comment by jenseneducation-mattias-von-vogelsang** [comment]
Thanks, I'll look into it.

**Comment by jenseneducation-mattias-von-vogelsang** [comment]
I got it to work by adding this into the preHandler function, if anyone else stumbles into this:

```
      req.raw.url = `${req.raw.url}&apikey=${CONFIG.apiKey}`;
```
instead of any req.query changes, which did not work.
