### ISSUE TITLE
Fastify vs "semantically correct RESTful web services"

### ISSUE THREAD

**Issue by BrandonKMLee** [fastify/help#444]
## Question

Restify claimes to be "Semantically Correct", which is a feature recommended by the Uni I am in.
Does Fastify support this feature as well?

**Comment by zekth** [comment]
Yes it does. It's all yours to be semantically correct in your api definition. See: https://www.w3.org/2001/sw/wiki/REST

**Comment by BrandonKMLee** [comment]
Wait so RESTify has some sort of "force checking"?
I mean to follow the REST spec is good and all, but what is going on with their "semantically correct" selling point?

**Comment by Eomm** [comment]
I would ask Restify team what they mean tbh

REST is an architecture so it is up to the developer to implement it. 
The Fastify framework is fully featured to create a RESTUfull application
