### ISSUE TITLE
How to write this plugin with an async syntax

### ISSUE THREAD

**Issue by Albert-Gao** [fastify/help#446]
The following code works fine
```javascript
export const applyDecorators = (fastify, _, done) => {
    fastify.decorateRequest("user", null);

    fastify.addHook("onRequest", (req, reply, done1) => {
      prisma.user
        .findUnique({
          where: {
            id: "ckor2n7290000we1if1vniusj",
          },
        })
        .then((user) => {
          if (user) {
            req.user = user;
          } else {
            reply.unauthorized();
          }
        })
        .catch((err) => {
          reply.unauthorized();
        })
        .finally(() => {
          done1();
        });
    });

    nonAuthRoute.forEach((route) => fastify.route(route));

    done();
  };
```

So basically, I just want to decorate the request with an extra property called `user` which is from the authed user, this is an async procedure, so I wonder how to do that with fastify, thanks

Is there any way I can rewrite this with an async example? Can not find it in the documentation, thanks :)

**Comment by L2jLiga** [comment]
Hey-hey, I cannot find much documentation as well, anyway:

Check `Usage` section of `fastify-plugin` repository: https://github.com/fastify/fastify-plugin#usage
Check `async/await` and `ESM support` sections  of `fastify` plugins documentation: https://github.com/fastify/fastify/blob/main/docs/Plugins.md#asyncawait

Also, your plugin could be rewritten this way:

```javascript
export const applyDecorators = async (fastify) => {
    fastify.decorateRequest("user", null);

    fastify.addHook("onRequest", async (req, reply) => {
      const user = await prisma.user.findUnique({
        where: {
          id: "ckor2n7290000we1if1vniusj",
        },
      })
      .catch(() => {
        throw fastify.httpErrors.unauthorized();
      });

      if (!user) throw fastify.httpErrors.unauthorized();

      req.user = user;
    });

    nonAuthRoute.forEach((route) => fastify.route(route));
  };
```

**Comment by Albert-Gao** [comment]
Thank u so much! Much more clear now, just a quick question, do I need to call `done()` after some thing like `rely.send()` or `reply.badRequest()`

**Comment by mcollina** [comment]
You should __never__ call `done()` if you use `async`.

**Comment by Albert-Gao** [comment]
@mcollina Yes, thanks, 100% sure about that, but what about `reply.send()`? I

**Comment by mcollina** [comment]
Fastify can figure out it has already send a response.
However you can also skip it.

Here is what I recommend:

```js
app.addHook('onRequest', async (req, reply) => {
  if (req.something) {
    reply.send('something')
  }
  return reply // important!
})
