### ISSUE TITLE
Can I use fastify-soap-client with more than one webservice?

### ISSUE THREAD

**Issue by rodmoreno** [fastify/help#447]
#### You have already researched for similar issues?
Yes

#### What are you trying to achieve, or the steps to reproduce?

I'm developing a web services that needs consume third-party web services built on SOAP so I noticed that exists a plugin to decorates a soap client and I already use to connect to one provider but now I need connect to another provider using SOAP too.

It's possible?

**Comment by L2jLiga** [comment]
Depends on your use case, if you need to use them in same context/routes then it's better to use plain SOAP client, otherwise you can check [Encapsulation docs](https://github.com/fastify/fastify/blob/main/docs/Encapsulation.md) and use this feature if it suitable for you
