### ISSUE TITLE
Why does fastify's req/sec drop from 64k to 39k?

### ISSUE THREAD

**Issue by philosofonusus** [fastify/help#449]
I just want to know

**Comment by mcollina** [comment]
What code are you referring about?

**Comment by philosofonusus** [comment]
I'm talking about benchmarks

**Comment by mcollina** [comment]
Which benchmarks? Link?

**Comment by Eomm** [comment]
I think we are talking about the last git action execution:
https://github.com/fastify/benchmarks/commit/8d111c3bd399c372d1468843b6070787d42f5db1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

I could be worth re-run it, I remember some issue on that node version v14

**Comment by philosofonusus** [comment]
> I think we are talking about the last git action execution:
> 
> https://github.com/fastify/benchmarks/commit/8d111c3bd399c372d1468843b6070787d42f5db1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
> 
> 
> 
> I could be worth re-run it, I remember some issue on that node version v14

I think you can, because on my virtual machine 2cpu 6gb ram 
Node v14 results were a little bit higher
