### ISSUE TITLE
Do I really have to call Done() inside a plugin?

### ISSUE THREAD

**Issue by hs-dev-web** [fastify/help#453]
In Getting Started page, the example doesn't call done():

[https://www.fastify.io/docs/latest/Getting-Started/#your-first-plugin](https://www.fastify.io/docs/latest/Getting-Started/#your-first-plugin)

```
// our-first-route.js

async function routes (fastify, options) {
  fastify.get('/', async (request, reply) => {
    return { hello: 'world' }
  })
}

module.exports = routes
```

While in Plugins Guide page, you said it's a **must** to call done():

[https://www.fastify.io/docs/latest/Plugins-Guide/](https://www.fastify.io/docs/latest/Plugins-Guide/)

> As you probably know, the required plugins must expose a single function with the following signature
> 
> `module.exports = function (fastify, options, done) {}`
> 
> Where fastify is the encapsulated Fastify instance, options is the options object, and done is the function you must call when your plugin is ready.

**Comment by mcollina** [comment]
A plugin is asynchronous. Either you return a promise or you call done.

Making your function `async` will make your function return a `Promise`, so there is no need to call done.
