### ISSUE TITLE
Is there a release schedule?

### ISSUE THREAD

**Issue by ghinks** [fastify/help#457]
I was wondering if there was a **release** schedule of some kind. I see regular point releases. However some guiding documentation or issues on the timelines for new major versions would be useful. If there are is another place you can point me to please do so.

**Comment by mcollina** [comment]
As a general rule, we plan for at least a major a year to drop old Node.js releases. It's done when it's done as we do not have the resources to commit to a fixed schedule. We use Github milestones to track the progress. 

The development of the next major happens on the `next` branch.

Some of this is in https://github.com/fastify/fastify/blob/main/docs/LTS.md, but not all... a PR to improve it would be awesome.

**Comment by ghinks** [comment]
Many thanks
