### ISSUE TITLE
Attach fluent-schema to dynamic/unknown properties.

### ISSUE THREAD

**Issue by crispinkoech** [fastify/help#458]
Hey,

So I have this object with date strings as keys, and objects as the value for each date.

Something like this:
```js
{
    "2020-10-01": {
        a: 1,
        b: 2,
        c: 3,
    },

    "2020-10-02": {
        a: 1,
        b: 2,
        c: 3,
    },
}
```
Is there a way to describe a fluent schema to validate such an object, where I don't have the exact name of the props? From what I can see in `fluent-schema` docs, you have to specify a prop key when attaching a schema.

What I'm looking for might be something like this:

```js
const mySchema = S.object()
    .prop(/\d{4}-\d{2}-\d{2}/, S.Object().prop('a', S.number()).prop('b', S.number())); // i.e apply this schema to all properties in the parent object.
```

Doesn't have to regex to capture all possible keys, but something that can achieve this. Is there such a feature within `fluent-schema`?

**Comment by climba03003** [comment]
https://json-schema.org/understanding-json-schema/reference/object.html#id4

**Comment by crispinkoech** [comment]
Thanks @climba03003, I loooked at the `additionalProperties` section and it's exactly what I needed :+1:
