### ISSUE TITLE
How can I use fastify-swagger when i use modules(put controller/routes/schema together) not routes and routes/documentation?

### ISSUE THREAD

**Issue by radiorz** [fastify/help#459]
![image](https://user-images.githubusercontent.com/24271959/119759787-6c5bc180-bedb-11eb-91ff-0c89afdef302.png)

I put a module file together and I found fasity-swagger doesnt work. How can I make fastify-swagger create documentations appear? 
![image](https://user-images.githubusercontent.com/24271959/119759840-839aaf00-bedb-11eb-800e-ed0bca65860f.png)

I just use fastify-swagger like this:
```
fastify.register(require('fastify-swagger'), swagger)
```
and the swagger config like this:
```
module.exports = {
  routePrefix: '/documentation',
  exposeRoute: true,
  swagger: {
    info: {
      title: 'fastify',
      description: 'fastify',
      version: '1.3.0'
    },
    host: 'localhost',
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],

  }

```

**Comment by climba03003** [comment]
I cant really help without a reproducible code example.

I can only give the following advice.
1. `fastify-swagger` must register before all route inserted because it need to collect the registered route.
2. all registered route need to provide `schema` in route option in order to get displayed correctly.
3. only the default `ajv` validator is supported, because `fastify-swagger` do not understand custom schema format.

**Comment by radiorz** [comment]
thank you @climba03003 , I just change routes filename to  modules and then  the swagger routes disappeared. you can try it.
I register it before route
I do like this way:
```
...
app.register(require('fastify-swagger'), swagger)
app.register(require('./plugin/authenticate')).then(() => {
  const routes = require('./modules')
  routes(app).forEach((route, index) => {
    app.route(route)
  })
})
...
.........
const start = async () => {
  try {
    await sequelize.sync()
    app.log.info('Database sync correctly')
    await app.listen(PORT, '0.0.0.0')
    app.swagger()
  } catch (err) {
    app.log.error(err)
    process.exit(1)
  }
}
start()


```

**Comment by radiorz** [comment]
Thanks for your advice. I found that is my own problem.. I fixed my code and the  swagger ui turn to be good.
