### ISSUE TITLE
Validation from Swagger / OpenAPI file

### ISSUE THREAD

**Issue by marcel-se-best** [fastify/help#460]
Hello,

is there a way to setup the schema validation from a Swagger / OpenAPI file instead of JSON-Schema?

Kind regards,
Marcel

**Comment by kibertoad** [comment]
[Yes](https://www.npmjs.com/package/openapi-validator-middleware).

**Comment by zekth** [comment]
There is also : https://github.com/seriousme/fastify-openapi-glue
