### ISSUE TITLE
Generate static OAS 3.0 specification with fastify-swagger

### ISSUE THREAD

**Issue by calvinl** [fastify/help#463]
Hello Fastify team! 

I was wondering if it was possible to use fastify-swagger to generate a static JSON or YAML file that I can check into a repository. I personally don't like the interface of swagger-ui and would like to use some alternatives such as ReDoc or Stoplight. 

Besides starting the server and grabbing the /documention/json file, is there a way to do this via command line? It would be great to have a CI pipeline generate the file and check it into version control somewhere. 

Thanks for any tips/advice!

**Comment by mcollina** [comment]
you can generate it by calling `fastify.swagger()` after `.ready()` is done.

**Comment by calvinl** [comment]
Thanks @mcollina! Is that in the docs? I didn't see that. If not, I can create a PR for that. 

On another note, is there a way to disable the UI and/or add basic auth to it (or the JSON/YAML routes)?

**Comment by mcollina** [comment]
Yes, there is a way to disable the UI. Check the docs :P.

**Comment by mcollina** [comment]
There isn't one, but adding a route to just return the JSON/YAML is straightforward: https://github.com/fastify/fastify-swagger/blob/master/lib/routes.js#L81-L99
