### ISSUE TITLE
Is it possible to re/move reqId from the log message?

### ISSUE THREAD

**Issue by zimmicz** [fastify/help#464]
#### You have already researched for similar issues?
I have.

#### What are you trying to achieve, or the steps to reproduce?

I would like to remove the reqId from the log message entirely or move it somewhere else (e.g. nested property data.reqId). Is it possible? Is there a workaround if it isn't?

* *node version*: 14
* *fastiy version*: ^3.15.1
* *os*: Linux Mint

**Comment by zekth** [comment]
You can customize the logger by using `serializers` property. See : https://www.fastify.io/docs/latest/Logging/

**Comment by zimmicz** [comment]
Thanks @zekth, but I'm already using these for a different purpose, but I haven't found a way to reach the reqId from there. Do you have a working example?

**Comment by zekth** [comment]
Sorry i misinterpreted your need. So in your case you need to use `disableRequestLogging` and reproduce the behaviour in a different way like
```js

const fastify = require('.')({
  disableRequestLogging: true,
  logger: true
})

fastify.get('/', (request, reply) => {
  reply.send({ hello: 'world' })
})

fastify.addHook('onRequest', (req, reply, done) => {
  req.log.info({ url: req.raw.url, foo: req.id }, 'received request')
  done()
})

fastify.addHook('onResponse', (req, reply, done) => {
  req.log.info({ url: req.raw.originalUrl, statusCode: reply.raw.statusCode, bar: req.id }, 'request completed')
  done()
})

fastify.listen(3000, (err, address) => {
  if (err) throw err
})

```

see : https://www.fastify.io/docs/latest/Server/#disablerequestlogging

**Comment by zimmicz** [comment]
Yep, I have already tried that, no matter what you do, you still get the `reqId` in the log message.

**Comment by zekth** [comment]
You need to declare your own `pino` logger instance otherwise it uses the default factory my bad.
```js


const logger = require('pino')();
const fastify = require('fastify')({
  disableRequestLogging: true,
  logger: logger
})

fastify.get('/', (request, reply) => {
  reply.send({ hello: 'world' })
})

fastify.addHook('onRequest', (req, reply, done) => {
  logger.info({ url: req.raw.url, foo: req.id }, 'received request')
  done()
})

fastify.addHook('onResponse', (req, reply, done) => {
  logger.info({ url: req.raw.originalUrl, statusCode: reply.raw.statusCode, bar: req.id }, 'request completed')
  done()
})

fastify.listen(3000, (err, address) => {
  if (err) throw err
})
```

**Comment by zimmicz** [comment]
Magnificent, thanks a lot!

**Comment by Eomm** [comment]
Another trick is use the `undefined` id

```
const fastify = require('fastify')({
  logger: true,
  genReqId: function (req) { return undefined }
})
fastify.get('/', async () => 'asd')
fastify.listen(8080)

```

Note that you can customize the field with [`requestIdLogLabel`](https://www.fastify.io/docs/latest/Server/#requestidloglabel)

**Comment by climba03003** [comment]
> 
> 
> Magnificent, thanks a lot!
> 
> Even though it's a bit odd that I can't use the `logger` provided to the fastify constructor directly via `req.log`.

`req.log` is a child logger from `logger` which already passed the `reqId` is param. So, use `fastify.logger` for it.
