### ISSUE TITLE
How to set expiration time while using fastify-redis

### ISSUE THREAD

**Issue by ExpressGradient** [fastify/help#469]
#### You have already researched for similar issues?
yes

#### What are you trying to achieve, or the steps to reproduce?
I'm trying to implement caching using the [fastify-redis](https://github.com/fastify/fastify-redis) package and I can't find any documentation on how to set expiration time to a key using the package.

Question: How to set an expiration time to a key?

#### Context

* *node version*: 14.15.0
* *fastify version*: >=3.17.0
* *os*: Windows

Thanks.

**Comment by mcollina** [comment]
fastify-redis wraps ioredis. Check their docs, as well the redis website.

**Comment by ExpressGradient** [comment]
Thanks, found the solution.
