### ISSUE TITLE
Sending a reply from middleware and ending fastify lifecycle

### ISSUE THREAD

**Issue by aarjae** [fastify/help#47]
I am writing a middleware to authenticate a request to the server. I have managed to access the request properties in the request object, but I can't access the ```code``` and ```send``` methods in the reply object.

```js
module.exports = async (request, reply, next) => {
    const authToken = request.headers.authToken;

    if(authToken !== process.env.SECURITY_KEY){
        reply.send(boom.unauthorized("Invalid auth token"));
    }else{
        next()
    }

    console.log(reply);
};
```

I get TypeError: reply.send is not a function whenever I make a request to the server

I expected an error response to be sent  back to the client and for the fastify lifecycle to end

I am running 
* * Node v1v0.15.0
* *fastify 1.13.4
* *os*:Linux

I am using middlewares to do authentication. It is probably not the best way, and if so, please advise on a better way to do this

**Comment by aarjae** [comment]
Okay so I figured it out. I need to call the next method with an Error object and that works. But then, is this the best way to do simple request authentication?
I will keep this open for a while

**Comment by mcollina** [comment]
Check out https://github.com/fastify/fastify-bearer-auth, that should do what you need.

**Comment by aarjae** [comment]
Cheers, that worked great
