### ISSUE TITLE
is it possible to create fastify soap server?

### ISSUE THREAD

**Issue by Sivanathan2903** [fastify/help#470]
I've been looking for the supporting documentation for creating the SOAP web services using fastify, with just node and express I was exploring some of the available packages like "node-soap" which is good for plain node application but I found that fastify adds the extra features on top of NodeJs, so thought of creating the SOAP based web services using fastify. I've not seen any documentation in the official fastify page. Can someone please advise me on, creating the SOAP based services using fastify is possible and any documentation available?

The below are the package version i've been using...

* *node version*: 10.16.3
* *fastify version*: >=3.15.1
* *os*: Windows

**Comment by mcollina** [comment]
It would likely be possible, but it's not documented anywhere.
