### ISSUE TITLE
Set response content-type in FastifySchema

### ISSUE THREAD

**Issue by Letiste** [fastify/help#473]
Hello, 
I'm trying to generate a swagger documentation from my routes, which are dynamic.
I would like to specify the content-type of the response dynamically (as my routes are dynamics) but I didn't succeed to put it in the FastifySchema.

### Code

How my routes are generated:
```ts
const challenges = readdirSync(path.join(__dirname, '../challenges')).map((file) => require(path.join(__dirname, '../challenges', file)));

for (const challenge of challenges) {
    fastify.get(`/${challenge.functionName}`,{schema: getSchema, }, async (_, reply) => {
      reply.view('/view/index.ejs', {
        languages,
        challenge,
        helpers: require(path.join(__dirname, `../dist/helpers/${challenge.functionName}`))
          .helpers,
          themes
      });
    });
}
```

My `getSchema`:
```ts
export const getSchema = {
  response: {
    200: { description: 'HTML page for the corresponding challenge', type: "string" },
  },
};
```

I've thought of something like this: 
```ts
export const getSchema = {
  response: {
    200: {
      description: 'HTML page for the corresponding challenge',
      content: {
        'text/html': {
          schema: {
            description: 'HTML output',
            type: 'string',
          },
        },
      },
    },
  },
};
```
But couldn't make it work.

Does anyone have an idea ?
Thanks.

* *node version*: v14.15.5
* *fastify version*:3.18.0
*  *fastify-swagger version*: 4.8.0

**Comment by climba03003** [comment]
Use produces property.
https://github.com/fastify/fastify-swagger/blob/master/examples/options.js#L183-L199

**Comment by lohfu** [comment]
> Use `produces` property. https://github.com/fastify/fastify-swagger/blob/master/examples/options.js#L183-L199

Please in the future, link to a specific commit rather than master branch. I assume that link is no longer pointing to what you were referring to. Thanks otherwise
