### ISSUE TITLE
light-my-request with Express Application

### ISSUE THREAD

**Issue by jmcdo29** [fastify/help#476]
## 💬  Question here 

Is there a way to use light-my-request with Express applications? In the end, I want to be able to use light-my-request with NestJS regardless of the adapter, but I seem to be running into trouble with using it with Express.

I understand light-my-request is generally for Fastify, so if it's not possible I understand, but thought I'd see if I was just misconfiguring something. 

You can either use the below code or use the minimum reproduction repository I've attached if you need to run anything.

```js
const express = require('express');
const { inject } = require('light-my-request');

describe('express-lmr', () => {
  it('should return Hello World!', async () => {
    const app = express();
    app.use('/', (_req, res, _next) => {
      res.send('Hello World!');
    });
    const response = await inject(app, { method: 'GET', url: '/' });
    expect(response.statusCode).toBe(200);
    expect(response.payload).toBe('Hello World!');
  });
});
```

[jmcdo29/lmr-express](https://github.com/jmcdo29/lmr-express-repro)

## Your Environment

- *node version*: 14
- *light-my-request*: 4.4.1
- *os*: Mac

**Comment by mcollina** [comment]
Unfortunately express monkeypatches their main classes and light-my-request is not aware of that. It _might_ be doable, but we had no incentive in actually trying to achieve this.

**Comment by jmcdo29** [comment]
I was afraid something like that might be the answer. Thanks for your time.

**Comment by MiguelGuthridge** [comment]
Since this issue is one of the top search results when searching the web for "does light-my-request work with express", I'm adding a comment here to mention that using Express with light-my-request works correctly now.
