### ISSUE TITLE
Point-of-view Handlebars Layouts

### ISSUE THREAD

**Issue by Zhongy1** [fastify/help#477]
## 💬  Question here 
I was setting up point-of-view and handlebars today. I was reading the documentation for configuring handlebars layouts, but it seems like you can only specify one layout. Is this intended, or is there a way to specify more layouts that I do not know of?

## Your Environment

- *node version*: 14.15.0
- *fastify version*: >=3.18.0
- *point-of-view version*: 14.15.0
- *os*: Mac

**Comment by punkish** [comment]
hello,

The way I do it is to not set a layout in the options, like so

```js
 const options = {
    engine: {
        handlebars: Handlebars
    },
    root: path.join(cwd(), 'views'),

    /*
     * we don't declare 'layout' here because we set 
     * route-specific custom layout in the route source 
     * wherever applicable
     */
    //layout: './layouts/main.hbs',

    // this will add the extension to all the views
    viewExt: 'hbs',
    options: {
        partials: {
            meta: './partials/meta.hbs',
            head: './partials/head.hbs',
            foot: './partials/foot.hbs'
        }
    }
};
```

and then, set the desired layout in the actual `reply` in the route handler, like so

```js
const template = './layouts/main';
return reply.view(template, { content });
```

I am using Fastify 4 and `@fastify/view 7.0.0`

**Comment by simoneb** [comment]
@Zhongy1 did you solve the issue?
