### ISSUE TITLE
Full text search with mongoDB

### ISSUE THREAD

**Issue by Dubask** [fastify/help#478]
Im trying to get a Full Text Search working through Fastify and Mongoose. But it returns an empty array.

There is no info online about this, so I just played with it for a while. in db.ts I set the:
`useCreateIndex: true`

The Model (Benefit.ts):

```
export class Benefit extends BaseModel {
    _id: ObjectID;

    @prop({required: true, unique: true, index: true, text: true}) <-- set index & text to true
    name: string;

    @prop({index: true, text: true})
    details: string;

    const BenefitModel = getModelForClass(Benefit);
    BenefitModel.createIndexes(err => console.log('ERROR', err)); <-- this is what I tried // err=null
    export default BenefitModel;

```

The Route Setup:
```
export class BenefitController {
    protected routes: fastify.RouteOptions[];

constructor() {
        this.routes = [];
        this.setupRoutes();
    }

public getRoutes(): fastify.RouteOptions[] {
     return this.routes;
    }

protected setupRoutes(): void {
        this.routes.push({
            method: 'POST',
            url: '/searchBenefit',
            handler: this.searchBenefit,
        });
}
new BenefitController().getRoutes().forEach((route: fastify.RouteOptions) => {
        fastify.route(route);
    });
```
    
The indexs seems to be defined properly. when I use listIndexes(), I get:
```
{ v: 2, key: { _id: 1 }, name: '_id_', ns: 'some-address.db.benefits' },
  {
    v: 2,
    unique: true,
    key: { name: 1 },
    name: 'name_1',
    ns: 'some-address.db.benefits',
    background: true
  },
  {
    v: 2,
    key: { details: 1 },
    name: 'details_1',
    ns: 'some-address.db.benefits',
    background: true
  },
  {
    v: 2,
    key: { _fts: 'text', _ftsx: 1 },
    name: 'details_text',
    ns: 'some-address.db.benefits',
    background: true,
    weights: { details: 1 },
    default_language: 'english',
    language_override: 'language',
    textIndexVersion: 3
  }
  ```
  
  
The actual search (Benefit.controller.ts):
```
const searchResults = await benefitService.find(
     {$text: {$search: textSearch}}, <-- textSearch is valid and comes as a string
     {score: {$meta: 'textScore'}},
     );
```
  

The return is with status 200, but empty:
```
{
    "status": 1,
    "results": []
}
```

What am I missing?

Thanks!

**Comment by RafaelGSS** [comment]
Sorry, I don't get the `fastify` question here. Looks like the issue is under mongodb query.

**Comment by Dubask** [comment]
Thank for commenting.

In mongodb all I need to do is add 'createIndex' at the end of the schema.
In fastify it doesnt work, and I need to set the index it in the model props as shown above.

Hence, it means that fastify is changing the way indexes are created, so maybe it changes other things, that prevent the full text search from operating properly.
I would like to know, what else I need to do, or define, in order for mongoDB to understand (through fastify), that Im trying to get something with the index that is defined through the fastify library.

**Comment by jsumners** [comment]
Fastify changes nothing with MongoDB. The `fastify-mongodb` plugin merely decorates the Fastify instance with the upstream MongoDB client.
