### ISSUE TITLE
How to hide routes generated by fastify-proxy-http in swagger UI

### ISSUE THREAD

**Issue by hanks** [fastify/help#479]
## Question

`fastify-proxy-http` will generate the routes for all the http methods, we could use [`httpMethods`](https://github.com/fastify/fastify-http-proxy#httpmethods) parameter to adjust this, but how to to hide them in the swagger UI?

Because  [hiding routes in swagger UI](https://github.com/fastify/fastify-swagger#hide-a-route), we should pass the `{ hide: true }` or `hiddenTag` to the route schema, but `fastify-proxy-http` does not support `schema` parameter, and seems also [declined the PR](https://github.com/fastify/fastify-http-proxy/pull/123) to add `schema` support.

<img width="408" alt="Screenshot 2021-07-01 at 23 57 31" src="https://user-images.githubusercontent.com/759107/124194173-5dfb5980-dac8-11eb-9831-09bc0b1b58b4.png">

**Comment by climba03003** [comment]
https://github.com/fastify/fastify-swagger#options
use `hideUntagged`.
