### ISSUE TITLE
Register custom middleware

### ISSUE THREAD

**Issue by stephan9mertel** [fastify/help#483]
I'm migrating a project from fastify 2 to fastify 3. In my code I have a custom middleware that I include like this in version 2:
```ts
const server = fastify();
server.use(getMyMiddleware());
```
When migrating to v3, this code fails with the error `FastifyError: You must register a plugin for handling middlewares, visit fastify.io/docs/latest/Middleware/ for more info.` When checking the linked documentation, it tells me that I need the corresponding plugin for the middleware I want to use.

As I said, I'm using a customized middleware forming part of my code base. Any idea how I can make this work with v3?

* *node version*: 14
* *fastify version*: 3.18.1
* *os*: ubuntu 18
* migrating from fastify version 2.2.0

**Comment by Asjas** [comment]
You need to register and use `middie` as it's a middleware engine. Upgrading from Fastify v2 to v3 would require you to use this. 🙂 

https://github.com/fastify/middie

**Comment by stephan9mertel** [comment]
Many thanks @Asjas , works nice! I only had to adapt my code to the asyncronous call, but no problem.
