### ISSUE TITLE
How to set connectionTimeout using fasityfi-cli

### ISSUE THREAD

**Issue by thr3a** [fastify/help#484]
I'm creating an application using a platform generated by fastify-cli, but I can't find a place to set the [connectionTimeout](https://www.fastify.io/docs/master/Server/#connectiontimeout).

```javascript
'use strict'

const path = require('path')
const AutoLoad = require('fastify-autoload')

module.exports = async function (fastify, opts) {
  // NOT WORKING!!!!
  opts.connectionTimeout = 2 * 1000

  fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'plugins'),
    options: Object.assign({}, opts)
  })

  fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'routes'),
    options: Object.assign({}, opts)
  })
}
```

How can I set the [connectionTimeout](https://www.fastify.io/docs/master/Server/#connectiontimeout) when using fastify-cli?

## Your Environment

- *node version*: 14
- *fastify version*: 3.0.0
- *os*: Linux

**Comment by RafaelGSS** [comment]
Why do you want to register these factory options in a specific scope? It's commonly used when you create the app:

```js
const fastify = Fastify({ connectionTimeout: xxx })
```

**Comment by Eomm** [comment]
This should help https://github.com/fastify/fastify-cli#start

```
module.exports.options = {
  connectionTimeout: 2000
}
```

**Comment by thr3a** [comment]
Thank you very much.
