### ISSUE TITLE
How to use transactions?

### ISSUE THREAD

**Issue by marvix** [fastify/help#485]
How to use transactions with fastify-mongodb?

* *node version*: 16.3
* *fastify version*: >=3.19.1
* *os*: Mac
* *any other relevant information*:

**Comment by climba03003** [comment]
It is unrelated to `fastify-mongodb` and `fastify`. `fastify-mongodb` is a tools to bind the `mongodb` driver to `fastify` instance. You can use it just like normal `mongodb`.

https://docs.mongodb.com/manual/core/transactions/


Note that `transaction` require your database setup as `shards`.
