### ISSUE TITLE
Lint errors due to "server.register(require(...))"

### ISSUE THREAD

**Issue by stephan9mertel** [fastify/help#486]
When implementing a middleware like suggested in https://www.fastify.io/docs/latest/Middleware/ my linter is complaining because the code breaks the following rules:

https://eslint.org/docs/rules/global-require
https://github.com/typescript-eslint/typescript-eslint/blob/v4.28.2/packages/eslint-plugin/docs/rules/no-var-requires.md

My code:
```ts
    const server = fastify(serverOpts);
    await server.register(require("middie"));
    (server as any).use(fastifyTracingMiddleware(tracer, ["/"]));
```

Is there any way to fix this without disabeling those rules?

- *node version*: 14
- *fastify version*: 3.18.1
- *os*: Linux

**Comment by Eomm** [comment]
Are you using ejs?

Anyway the links you have provided are suggesting how to fix those errors

**Comment by stephan9mertel** [comment]
Hi @Eomm, thanks for pointing me again to those links. You're right, it's indeed solvable with what is written there. My problem was that I tried the import like this:
```ts
import middie = require("middie");
```
However, it should be like this for fastify to accept it as an argument for the "register" method:
```ts
import middie from "middie";
```
Many thanks!
