### ISSUE TITLE
How to implement request-scoped context

### ISSUE THREAD

**Issue by pedrolcn** [fastify/help#491]
Most request-context libs out there, either for express or fastify seem to rely on AsyncLocalStorage or cls. eg:
 - https://www.npmjs.com/package/express-http-context
 - https://www.npmjs.com/package/cls-request-context
 - https://www.npmjs.com/package/fastify-http-context
 - https://www.npmjs.com/package/fastify-request-context
 
 Why is AsyncLocalStorage or cls required at all, couldn't we just stick the context into the request/reply object ? Is the object reused or does it leak in some form ?

**Comment by kibertoad** [comment]
@pedrolcn You can, but that requires carrying the context manually across all the layers. Beauty of AsyncLocalStorage is that you don't need to, you can directly import storage instance from whenever and access the request context.
If request/reply object approach works for you, you can do just that, no need for any plugin, just augment the type and add a decorator.
