### ISSUE TITLE
fastify-jwt, how change the secret when signing new token (refresh token)

### ISSUE THREAD

**Issue by marvix** [fastify/help#492]
I could not find any way how to change the token secret when signing a new token, I need to create a refresh token, and for security, it should be created with a new secret.

The `jsonwebtoken` showing that possible here [https://github.com/auth0/node-jsonwebtoken/blob/master/README.md#jwtsignpayload-secretorprivatekey-options-callback](url)

**Comment by climba03003** [comment]
It is not possible for `fastify-jwt` because it accept key pair as secret. It needs to be initialize before `jsonwebtoken` can be used.

If you need to use mulitple `jsonwebtoken` in your application, use it directly.

**Comment by climba03003** [comment]
Close as duplicate of #467
