### ISSUE TITLE
reply.removeHeader doesn't work

### ISSUE THREAD

**Issue by NorthHub** [fastify/help#494]
I want to remove the etag header, but it doesn't work
`reply.removeHeader('etag')`

**Comment by jsumners** [comment]
https://stackoverflow.com/help/how-to-ask

**Comment by NorthHub** [comment]
I asked the question normally and described the problem. Fastify does not remove the default headers, it only allows you to edit them. If you have no desire to answer, let others help

**Comment by jsumners** [comment]
You have given us zero context around the problem. Simply stating "thing doesn't work" does not give anyone any place to start on helping you. I closed the issue accordingly. If you are able to improve your question, ideally with a minimal reproduction, feel free to reopen.

**Comment by NorthHub** [comment]
**Example 1**

```
import createFastify from "fastify";

const fastify = createFastify({
  logger: true,
});

fastify.get("/", async (request, reply) => {
  reply.removeHeader('Date') // doesn't work
  return { hello: 'world'}
});

fastify.listen(9000);
```

**Example 2**

```
import createFastify from "fastify";
import fastifyStatic from "fastify-static";
import path from "path";

const fastify = createFastify({
  logger: true,
});

fastify.register(fastifyStatic, {
  root: path.resolve(),
});

fastify.get("/", async (request, reply) => {
  reply.removeHeader("etag"); // doesn't work 
  // or
  reply.removeHeader("Cache-Control"); // doesn't work
  
  reply.sendFile("example.html");
});

fastify.listen(9000);
```

**Comment by mcollina** [comment]
You cannot remove something that is not already there. You can check with the hasHeader function.

If you want to remove headers that set by others part of code, you should use the onSend hook.
