### ISSUE TITLE
When to await in fastify.register()?

### ISSUE THREAD

**Issue by ahgentil** [fastify/help#495]
## 💬  Question here 

My understanding is that if a plugin is implemented using an `async function()` or, if not, it has an explicit `done()` call then one should do `await fastify.register()`.

And what about chaining register calls?
Is `await fastify.register(p1).register(p2).register(p3)` the same as 
```
await fastify.register(p1);
await fastify.register(p2);
await fastify.register(p3);
```
?

And to finish, where does the `await fastify.after()` fit in here?
Is:
```
await fastify.register(p1);
await fastify.after();
await fastify.register(p2);
```
the same as:
```
await fastify.register(p1);
await fastify.register(p2);
```
?

Isn't `p1` fully registered just with `await fastify.register(p1)`. Is there the need for `await fastify.after()` to be sure that when `p2` is being registered, `p1`was already fully registered?

Thank you in advance.

**Comment by climba03003** [comment]
All registration is run in asynchronously. When the `plugin` require something inside another `plugin` for setup, you need to `await` it.

For example `fastify-helmet` and `fastify-swagger`. `fastify-helmet` needs  the `swaggerCSP` for options, then we either use `.after` or `await`.

```js
// error example
fastify.register(fastifySwagger)
fastify.register(fastifyHelmet, {
  contentSecurityPolicy: {
    directives: {
      // it will throw error here
      "script-src": fastify.swaggerCSP.script
    }
  }
})

// runnable example - 1
await fastify.register(fastifySwagger)
fastify.register(fastifyHelmet, {
  contentSecurityPolicy: {
    directives: {
      // it will throw error here
      "script-src": fastify.swaggerCSP.script
    }
  }
})

// runnable example - 1
fastify.register(fastifySwagger)
await fastify.after()
fastify.register(fastifyHelmet, {
  contentSecurityPolicy: {
    directives: {
      // it will throw error here
      "script-src": fastify.swaggerCSP.script
    }
  }
})
```
