### ISSUE TITLE
Fastify Swagger: How to set different content types for different responses?

### ISSUE THREAD

**Issue by okv** [fastify/help#496]
#### You have already researched for similar issues?
Yes

#### What are you trying to achieve, or the steps to reproduce?

I'm using [Problem JSON](https://datatracker.ietf.org/doc/html/rfc7807) format for error responses.
Thus, when it's a 2xx response I need to set a response content type to **application/json**, for error responses (e.g. HTTP status 400, bad request) I need to set it to **application/problem+json**. 
The only option to set response's content type that I've seen so far is `produces` on an endpoints level:

```js
  produces: [
    'application/json',
    'application/problem+json',
  ]
```

#### What was the result you received?

In that case all responses will have both content types which not what I really need.

#### What did you expect?

Would be great to have a chance to **specify response's content type** (e.g. via `produces`) on a **response** (not an endpoint) level.

#### Context

* *node version*: 14
* *fastify version*: 3.19.1
* *os*: Linux
* *any other relevant information*: fastify-swagger: 4.8.3

**Comment by climba03003** [comment]
It is currently not possible to set per response. Feel free to send PR to improve `fastify-swagger`.

**Comment by okv** [comment]
Alright, I will try to take a look at it, thanks.
