### ISSUE TITLE
How to set fileSize limit per-router with fastify-multipart ?

### ISSUE THREAD

**Issue by Geequlim** [fastify/help#497]
#### What are you trying to achieve, or the steps to reproduce?

I want to set a default file size limit to `2MB` and larger for some specified api to allow user upload large files. How can I achieve this?

I try to set default limit size and call `request.file`  as mentioned in the documentation but it doesn't work.

```ts
//  Set default size limit to 2MB when register the midlleware
fastify.register(multipart, {
	attachFieldsToBody: true,
	throwFileSizeLimit: true,
	limits: {
		fieldNameSize: 256,
		fileSize: 2 * 1024 * 1024, 
		headerPairs: 256
	}
});
```

```ts
fastify.post('/upload/files', async function (req, reply) {
  try {
    const file = await req.file({ limits: { fileSize: 100 * 1024 * 1024} })
    reply.send()
  } catch (error) {
    // error instanceof fastify.multipartErrors.RequestFileTooLargeError show not thrown then I upload a 10MB file but it does
  }
})
```

#### What was the result you received?
The file limit error show not thrown then I upload a 10MB file but it does.

#### What did you expect?

Some way to set file size limt for specified api.

#### Context

* *node version*:  14
* *fastify version*: >=3.15.1
* *os*: Windows

**Comment by Eomm** [comment]
It seems related to 
https://github.com/fastify/fastify-multipart/issues/250

We must investigate: would you like to work on it?
