### ISSUE TITLE
Is routes autoload only load index.js file?

### ISSUE THREAD

**Issue by chuoke** [fastify/help#498]
## 💬  Question here 

hi, I separated the routes into separate files but autoload just loaded index.js.

```js
routes/some/
          /index.js
          /first.js
          /secode.js
````

how should I do for this case?

**Comment by digitalmio** [comment]
Fastify does *not* provide file-based routing. You'll need to specify it yourself, as per docs https://www.fastify.io/docs/latest/Routes/
If you build some custom file-based routing or using some 3rd party plugin, we would need more info to help you solve the problem

**Comment by chuoke** [comment]
I use yarn to create a project
```
yarn create fastify

yarn
```

And then, I do not change anything,  just create some routes copy from the example, such as:
```
routes
├─example
│     └─index.js
└─tests
│     ├─index.js
│     └─sub.js
└─root.js
```

When starting dev, there is no ` sub ` route, and I console all routes:
```
GET : /
GET : /example
GET : /tests
```

If I add the ` sub ` to `tests/index.js` or `tests/sub/index.js`, the `sub` route is loaded.

**Comment by climba03003** [comment]
@chuoke Please check the description from [`fastify-autoload`](https://github.com/fastify/fastify-autoload/tree/a4e9432fd30d39fc01a65765358a893ffb34168d#global-configuration).

> Each script file within a directory is treated as a plugin unless the directory contains an index file (e.g. index.js). In that case only the index file (and the potential sub-directories) will be loaded.

If `index` file is exist, it will ignore all the others in the same directory.

**Comment by chuoke** [comment]
Sorry, I didn't find that description.

Thank you.
