### ISSUE TITLE
Help: how to set log destination from fastify-cli?

### ISSUE THREAD

**Issue by MeFelixWang** [fastify/help#499]
## 💬  Question here 

I want to export log into files.

According to the doc, I can enable logging by pass parameters to npm scripts, but I didn't see how to set logging destination there.

Any examples?

Thanks!

**Comment by climba03003** [comment]
I believe it is use the `module.exports.options` and enable `--options` flag.
https://github.com/fastify/fastify-cli#start

**Comment by VBetsun** [comment]
you can't pass log destination through CLI, but you can write your own logging module and use it like follows:
```json
"scripts": {
    "start": "fastify start --loggingModule=fileLogger.js app.js"
}
```
and in `fileLogger.js`
```js
module.exports = require('pino')('./out.json')
```
for more information, please, visit [pino](https://github.com/pinojs/pino/blob/master/docs/api.md#destination)

**Comment by MeFelixWang** [comment]
@VBetsun Thanks for response, I will try to make a module to solve this. And sorry for the delay.

**Comment by MeFelixWang** [comment]
I'm using typescript template, there are some codes in `app.ts`:

```
export type AppOptions = {
  // Place your custom options for app below here.
} & Partial<AutoloadPluginOptions>;
```
 I think this means if I add custom options like below:

```
export type AppOptions = {
  // Place your custom options for app below here.
  logger: {
    level: "info",
    file: "./logs.json"
  }
} & Partial<AutoloadPluginOptions>;
```
it will work. 

But actually nothing changed. 

Is this a bug?

@climba03003 Sorry for the delay.

**Comment by climba03003** [comment]
> type

You are exporting `type`, `type` have no effect for runtime.

**Comment by MeFelixWang** [comment]
My bad, sorry!

What if I set the custom options as default value to `opts` like:

```
const app: FastifyPluginAsync<AppOptions> = async (
  fastify,
  opts = {
    // @ts-ignore
    logger: {
      // @ts-ignore
      level: "info",
      // @ts-ignore
      file: "./logs.json"
    }
  }
): Promise<void> => {
  // Place here your custom code!

  // Do not touch the following lines

  // This loads all plugins defined in plugins
  // those should be support plugins that are reused
  // through your application
  void fastify.register(AutoLoad, {
    dir: join(__dirname, 'plugins'),
    options: opts
  })

  // This loads all plugins defined in routes
  // define your routes in one of these
  void fastify.register(AutoLoad, {
    dir: join(__dirname, 'routes'),
    options: opts
  })

};
```

it won't work neither.

Any suggestions? 

Thanks!@climba03003

**Comment by climba03003** [comment]
> onst app: FastifyPluginAs

`fastify-cli` treat the entry file as `plugin`, so I think it is not a good option to do it.

**Comment by MeFelixWang** [comment]
Kind of confusion, seems like no way out.

Do you mind share your solution to this problem?

Thanks! @climba03003

**Comment by climba03003** [comment]
I think my solution is very clear in the first comment. It is just exporting option with flag `--options
```
module.exports.options = {
  logger: { level: 'info', file: './logs.json' }
}
```

**Comment by MeFelixWang** [comment]
Thanks so much, it works! @climba03003 

How stupid I am, I mixed up files!  : (
