### ISSUE TITLE
How to correctly write middleware that correctly wraps a request

### ISSUE THREAD

**Issue by danielberndt** [fastify/help#5]
Hello,

I've just released my first app using fastify and found that it becomes unresponsive after a while. The reason seems to be idle psql connections that for which a transaction has not been committed/rollbacked.

I wrapped most of my requests using a custom made middleware. And I suspect that I misunderstood which lifecycle to use. What do I have to do to guarantee that every opened transaction will be closed. Either by committing if no error happened, or by rolling back if an error has happened in the stack below.

Here's my current (simplified) code:

```js
function connectPg(fastify) {
  fastify.addHook("preHandler", async function(req, reply) {
    const client = await this.pg.pool.connect();
    req.db = client.query.bind(client);
    await req.db("BEGIN;");
    return;
  });

  fastify.addHook("onSend", async (req, res) => {
    if (!req.db) return; // "preHandler hasn't been called!?"
    if (res.res.statusCode < 400) {
      await req.db("COMMIT;");
    } else {
      await req.db("ROLLBACK;");
    }
    req.client.release();
    return;
  });
}
```

**Comment by delvedor** [comment]
Can you give us a minimum example that reproduces the issue?

**Comment by danielberndt** [comment]
Unfortunately, I can't reproduce the issue myself. It only happens in the wild. Particularly with a route that's often called by the google crawler bot. So maybe it has to do with closing the connection while the request is still ongoing.
(I did some tests on my local machine, but closing the Chrome browser tab in the middle of a request, called both, `req.req.on("close", cb)` as well as the `onSend` hook. So I couldn't reproduce it that way either)

I'll put together a minimal example of the route that's most likely to be the culprit.

**Comment by danielberndt** [comment]
here's a full code sample:

```js
import fastify from "fastify";
import fastifyPostgres from "fastify-postgres";

function connectPg(fastify) {
  fastify.addHook("preHandler", async function(req, reply) {
    const client = await this.pg.pool.connect();
    req.db = client.query.bind(client);
    await req.db("BEGIN;");
    return;
  });

  fastify.addHook("onSend", async (req, res) => {
    if (!req.db) return; // "preHandler hasn't been called!?"
    if (res.res.statusCode < 400) {
      await req.db("COMMIT;");
    } else {
      await req.db("ROLLBACK;");
    }
    req.client.release();
    return;
  });
}

const legacyRedirects = async (instance, options, next) => {
  connectPg(instance);

  instance.get("/static/media/userpics/:piq", async (request, reply) => {
    const m = request.params.piq && request.params.piq.match(/^piq_(\d+)(.*).png/);
    if (!m) return Promise.reject({status: 404});
    const [, id, postfix] = m;
    const piq = await Pictures.find(request.db, parseInt(id, 10));
    if (!piq) return Promise.reject({status: 404});
    reply.redirect(301, `${piq.basePath}${postfix || "_o"}.png`);
  });

  if (next) next();
};


const app = fastify({});
app.register(fastifyPostgres, {});
app.register(legacyRedirects);
app.listen(9393, err => {
  if (err) throw err;
  console.log(`server listening on ${app.server.address().port}`);
  if (process.send) process.send("ready");
});
```

**Comment by delvedor** [comment]
@danielberndt sorry I didn't understand, can you reproduce the issue with the code above?
Can you also reproduce it without postgres?

**Comment by mcollina** [comment]
Can you provide full steps to reproduce? You can use autocannon to create some load!

**Comment by delvedor** [comment]
Quick question, where are your storing the `client` object inside request?
```js
  fastify.addHook("onSend", async (req, res) => {
    if (!req.db) return; // "preHandler hasn't been called!?"
    if (res.res.statusCode < 400) {
      await req.db("COMMIT;");
    } else {
      await req.db("ROLLBACK;");
    }
    req.client.release(); // <= where did you stored the client?
    return;
  });
```

**Comment by danielberndt** [comment]
Ah sorry, updated the example, to make more sense.

And no, I couldn't reproduce the issue locally, it happens in production though, about one unclosed transaction every 10 minutes, having a load of a few calls per second. 

Here's a more minimal example, I'm going to test:

```js
import fastify from "fastify";

let count = 0

function connectPg(fastify) {
  fastify.addHook("preHandler", async function(req, reply) {
    count += 1;
  });

  fastify.addHook("onSend", async (req, res) => {
    count += -1;
  });
}

const legacyRedirects = async (instance, options, next) => {
  connectPg(instance);

  instance.get("/test", async (request, reply) => {
    if (Math.random() < 0.2) return Promise.reject({status: 404});
    await new Promise(res => setTimeout(res, Math.random() * 100))
    reply.redirect(301, `/other-route`);
  });

  if (next) next();
};


const app = fastify({});
app.register(fastifyPostgres, {});
app.register(legacyRedirects);
app.listen(9393, err => {
  if (err) throw err;
  console.log(`server listening on ${app.server.address().port}`);
  if (process.send) process.send("ready");
});
```

My assumption is that `count` won't get back to zero after something weird happens. I'll check whether I can reproduce it locally.

**Comment by mcollina** [comment]
You should remove `if (next) next();` line. It's not needed.

**Comment by danielberndt** [comment]
Ah, okay, I've got it reproduced:

```js
const fastify = require("fastify");
const autocannon = require('autocannon')

let open = 0, count = 0;

function connectPg(fastify) {
  fastify.addHook("preHandler", async function (req, reply) {
    count += 1;
    open += 1
  });

  fastify.addHook("onSend", async (req, res) => {
    open += -1;
  });
}

const legacyRedirects = async (instance, options, next) => {
  connectPg(instance);

  instance.get("/test", async (request, reply) => {
    if (Math.random() < 0.2) return Promise.reject({ status: 404 });
    await new Promise(res => setTimeout(res, Math.random() * 100))
    reply.redirect(301, `/other-route`);
  });
};


const app = fastify({});
app.register(legacyRedirects);
app.listen(9393, err => {
  if (err) throw err;
  console.log(`server listening on ${app.server.address().port}`);

  autocannon({
    url: `http://localhost:${app.server.address().port}/test`,
    connections: 10,
    pipelining: 1,
    duration: 10
  }, (err, res) => {
    console.log(err, res);
    console.log("open/count", `${open}/${count}`)
    app.close();
  })
});
```

I would expect that `open/count` would be `0/XXX`, but instead it's something like `495/2481`

**Comment by danielberndt** [comment]
Ah, okay, the issue disappears if I reject with a non-404 status. Interesting!

**Comment by mcollina** [comment]
That sounds like a bug in fastify, good spot 🎉 !

**Comment by mcollina** [comment]
@danielberndt you seem on the right track, if you want to dig deeper and send a PR, go ahead! Otherwise one of us will look into it asap.

**Comment by danielberndt** [comment]
Sorry, there's still plenty of other things I need to do right now. I just released an all new version of quite an old [website](https://piq.codeus.net/) using all new web-stuff, and now all the old browsers and even the google bot are yelling at code that they can't parse 😅
I'll create an issue on the fastify repo so we can keep track.
