### ISSUE TITLE
Multiple API documentation in one Swagger file.

### ISSUE THREAD

**Issue by pktai** [fastify/help#500]
How to organise/build a Swagger UI interface for a directory which contains many Swagger definition .json/.yml files?.  I have seen how it's implemented in the stackoverflow [link](https://stackoverflow.com/questions/39521627/how-to-organise-build-a-swagger-ui-interface-for-a-directory-which-contains-many). I tried like it doesn't work. Can you give me the solution?

Version:  **FastifyAdapter** from **@nestjs/platform-fastify** : _8.0.2_
**fastify-swagger**: _4.8.3_
![image](https://user-images.githubusercontent.com/36804773/127295015-6c034c18-1249-46ef-933e-bf55fb48a6cc.png)

**Comment by climba03003** [comment]
The `index.html` for `swagger-ui` is built before publish. It is not possible to change the `url`. If you need this feature, feel free to send PR to `fastify-swagger`.
