### ISSUE TITLE
Help  how to make authorization optional

### ISSUE THREAD

**Issue by willin** [fastify/help#501]
## 💬  Question here 

a clear , consise and brief decription of your question

http://localhost:4000/graphql

{"statusCode":401,"error":"Unauthorized","message":"No Authorization was found in request.headers"}

```js
// example codes if any
 app.addHook('onRequest', (request) => request.jwtVerify());
````

If possible add a link to sample codes for error reproduction (github or replit)

https://github.com/mandiwise/apollo-federation-auth-demo/blob/master/index.js#L13

i wonder whether there is a config like express plugin:

```
    credentialsRequired: false
```

to make authorization optional

## Your Environment

- *node version*:  16
- *fastify version*: 3.0.2
- *os*: Mac
- *any other relevant information*

**Comment by mcollina** [comment]
A very simple try catch will do:

```js
app.addHook('onRequest', async (request) => {
  try {
    return await request.jwtVerify()
  } catch {
  }
})
```
