### ISSUE TITLE
Async route handlers get queued up

### ISSUE THREAD

**Issue by nostalgicdodo** [fastify/help#502]
Hi,

When I do asynchronous work in a route handler, all subsequent requests to the **same** route get queued up.
Consider the following:
```js

const fastify = require( "fastify" )()

let requestCount = 0

fastify.get( "/one", function ( request, reply ) {

	requestCount += 1
	console.log( "Requests: " + requestCount )

	if ( requestCount % 2 === 1 ) {
		setTimeout( function () {
			reply.send( { message: "wait" } )
		}, 5000 )
	}
	else
		reply.send( { message: "ok" } )

} )

fastify.get( "/two", function ( request, reply ) {
	return { message: "two" }
} )

fastify.listen( 9996 )
	.then( function ( httpPort ) {
		console.log( "HTTP server is listening at " + httpPort + "." );
	} )
	.catch( function ( e ) {
		console.error( e );
		process.exit( 1 );
	} )
```

Here, every odd numbered request to `/one` waits for 5 seconds before returning a response.
Every even numbered request returns with a response immediately.

However, when I make a second request, I do not get an immediate response. It waits until the first request is handled (i.e. 5 seconds) and then responds back.
But if in the meantime, I make a request to `/two` (while the request to `/one` is still processing), I get a response right away. So it is not queuing the route handling for all routes, only the `/one` route.

Is this the expected behavior or am I doing something incorrectly?

**Comment by mcollina** [comment]
How do you make those requests? This is likely due to your client or your operating system.

**Comment by nostalgicdodo** [comment]
You are right.
I'm using MacOS Catalina. This is the case when I visit the routes on Firefox and Chrome. I think they're doing some sort of optimization by queuing tabs that are addressed to the same URL.

However, when I use cURL or Safari, it works correctly as expected.

Thank you so much. I've been scratching my head on this for a whole day now.
