### ISSUE TITLE
[fastify-secure-session] Question regarding the claim of the session to be stateless

### ISSUE THREAD

**Issue by mbrt-yeah** [fastify/help#505]
Hello, 

in the [introductory text](https://github.com/fastify/fastify-secure-session#fastify-secure-session) of the plugin it says the following "Create a secure stateless cookie session for Fastify ...".

However, in my understanding, the session which is then persisted as a client side cookie is actually stateful given the possibility to add/read information to/from it via the `request.session.[get|set]` methods. 

Am I understanding something wrong here or should the introductory text be corrected?

Thanks and regards, M

**Comment by zekth** [comment]
> client side cookie is actually stateful

Not really as you bring the state of the session with you request, so the service does not have any reference of the session outside the cookie handling.

**Comment by mbrt-yeah** [comment]
> Not really as you bring the state of the session with you request, so the service does not have any reference of the session outside the cookie handling.

Ah O.K. I'm beginning to understand (hopefully). 

So a session is stateless if it is not persisted on the server side (as it is the case with this plugin) but just send to the client as a cookie?

And the fact that I can add several information to the session (e.g. current number of items in my shopping cart etc.) doesn't have anything to do with it being "stateless" or "stateful"?

Thanks and regards, M.

**Comment by zekth** [comment]
Session is stateless when the client send informations to the server for it to retrieve everything it needs. Usually it's an identifier which leads the server to request a shared memory space (DynamoDb, Redis, etc...). In `fastify-secure-session` the session is completely encrypted in the cookie. So the client sends its own session to the server.

> And the fact that I can add several information to the session (e.g. current number of items in my shopping cart etc.) doesn't have anything to do with it being "stateless" or "stateful"?

Indeed. The concept of statelessness is how and where you get the session informations. (Well it's not only for sessions, it's for anything you want)

**Comment by mbrt-yeah** [comment]
O.K. I got it now. Thanks for your help.

Regards, M
