### ISSUE TITLE
How to document response schema for fastify-errors?

### ISSUE THREAD

**Issue by mielp** [fastify/help#507]
## 💬  Question here 

I want to document the response schema for when an error occurs. Currently, my errors are generated with `fastify-error`, and my documentation with `fastify-swagger`.

When my code throws an error such as the following:

```js
import createError from "fastify-error";

const InvalidQuery = createError(
  "QUERY_FORMAT_ERROR",
  "The query was not formatted correctly",
  400
);
// ... in handler:
throw new InvalidQuery();
```

The front-end receives a JSON error like so:

```json
{"statusCode":400,"code":"QUERY_FORMAT_ERROR","error":"Bad Request","message":"The query was not formatted correctly"}
```

I want this error code and format in my Swagger documentation. So I create a schema and use it to describe the `response` for a route:

```js
const invalidQuerySchema = {
  description: "The query was not formatted correctly",
  type: "object",
  properties: {
    statusCode: { type: "number" },
    code: { type: "string" },
    error: { type: "string" },
    message: { type: "string" },
  },
};

instance.get("/", {
  schema: {
    response: { 400: invalidQuerySchema }
  }
}, async (req, res) => {
  throw new InvalidQuery();
});
```

The error now appears as expected in the swagger documentation, but the error payload returned by the server is now wrong. Whenever I query this route, the "correct" error serialization doesn't happen, and the error thrown does not have `statusCode`, `code` or `error` properties, it only has a `message`.

```json
{"message":"The query was not formatted correctly"}
```

Is there a way to be able to throw correct `fastify-error` objects, while having a good documentation for these errors?

## Your Environment

- *node*: 14
- *fastify*: 3.20.1
- *fastify-error*: 0.3.1
- *fastify-swagger*: 4.8.4

**Comment by VBetsun** [comment]
@mielp Could you please provide a minimum reproduction repository (and make it available through Github)?

**Comment by mielp** [comment]
Hi! I tried to do just that and could not reproduce the issue with the code I wrote above.

The issue still happens in a private project, so I've been trying to understand the issue there. After tinkering with it a little, it seems the issue happens with *some* of the errors created with `createError`, but most errors are okay. Quite literally, I created error constructors in two files with the exact same parameters, and imported them both for use in the request handler, and used exactly the same way: one is always correctly serialized, the other is always incorrectly serialized.

I will keep trying to write a minimal reproduction example -- or come up with an explanation and a solution for my issue if it's caused by a misuse on my side.

**Comment by mielp** [comment]
Update - this is not an issue with `fastify-errors` nor with `fastify-swagger`. In other parts of my application, I have a dependency on a library ([pkgcloud](https://github.com/pkgcloud/pkgcloud)) that uses internally the [`errs` npm package](https://www.npmjs.com/package/errs) (sidenote, `errs` has been unmaintained for almost 7 years).

As it turns out, `errs` defines a `toJSON` method on the global `Error` prototype, which gets called by `fast-json-stringify` when serializing error objects using a schema.

Global prototype pollution strikes again I guess 🤷‍♀️

Possible solution: manually define a `toJSON` prototype that does nothing:

```js
Object.defineProperty(Error.prototype, "toJSON", {
  enumerable: false,
  writable: true,
  value: function () {
    return this;
  },
});
```

I'm closing this issue as I won't need further help on this, and it turned out to be unrelated to Fastify packages. See you around! ✨
