### ISSUE TITLE
Long type inlays on Phpstorm/Webstorm

### ISSUE THREAD

**Issue by stfullstack** [fastify/help#508]
I'm taking advantage of Typescript using fastify, I have an tiny issue with type inlays where when I create a route the hinting is wider than my screen. Any advice on how to avoid this without duplicating code:

![image](https://user-images.githubusercontent.com/83694847/128220729-045b04fd-eb2e-4df5-bca5-fbbb9ca9ec28.png)

**Comment by jsumners** [comment]
How is this a problem for Fastify? This seems like an editor problem to me.

**Comment by stfullstack** [comment]
Hi thanks for your answer. 

The editor is picking up the types from fastify library. I am looking for someone who has also encountered this and come up with a solution.

Cheers
