### ISSUE TITLE
Document for `fastify-rate-limit` about rate-limiting 404s may have problem

### ISSUE THREAD

**Issue by idlist** [fastify/help#509]
## 💬  Question here 

Tried the plugin `fastify-rate-limit` and used the code in the document:

```js
fastify.setNotFoundHandler({
  preHandler: fastify.rateLimit()
}, function (request, reply) {
  reply.code(404).send({ hello: 'world' })
})
```

However, this code would throw this Error:

```
TypeError: server.rateLimit is not a function
```

Tried a little bit more and found this would work (and this setting of `preHandler` is also consistent with the official website):

```js
fastify.setNotFoundHandler({
  preHandler: () => {
    fastify.rateLimit()
  }
}, function (request, reply) {
  reply.code(404).send({ hello: 'world' })
})
```

If it is the problem of the document, could you please fix it? Thanks.

## Your Environment

- *node version*: 16
- *fastify version*: 3.19.2
- *os*: Windows

**Comment by mcollina** [comment]
This will do the trick:

```js
await fastify
fastify.setNotFoundHandler({
  preHandler: fastify.rateLimit()
}, function (request, reply) {
  reply.code(404).send({ hello: 'world' })
})
```

It's documented in how the plugin system works.

**Comment by idlist** [comment]
I see... but since my production environment does not support top-level await yet, I guess I'm gonna stick to my method.

Thanks again.
