### ISSUE TITLE
[ERR_ASSERTION]: Method 'GET' already declared for route '/'

### ISSUE THREAD

**Issue by nurdism** [fastify/help#51]
Hey I've been running into `[ERR_ASSERTION]: Method 'GET' already declared for route '/'` 
[Heres an example of what I'm doing](https://gist.github.com/nurdism/e04a95b7807e7368e24a06951de20dce), is this a bug or am I doing something wrong?  Looking at [this repo](https://github.com/fastify/fastify-example-twitter), its had the same routes declared [here](https://github.com/fastify/fastify-example-twitter/blob/master/tweet/index.js#L14) and [here](https://github.com/fastify/fastify-example-twitter/blob/master/timeline/index.js#L9) ([both prefixed here](https://github.com/fastify/fastify-example-twitter/blob/master/index.js#L101-L103)) so no idea whats going on with the example code above.

* *node version*: 10.15.1
* *fastify version*: ^1.13.4
* *os*: Windows

**Comment by delvedor** [comment]
Hello!
The `prefix` option will not work if you use `fastify-plugin` with it :)
https://www.fastify.io/docs/latest/Plugins/#route-prefixing-option

**Comment by nurdism** [comment]
Ahh ok, thats what I was missing. I'm curious, whats the difference from doing:

```js
const test1 = p(async function (f,o, next) {
  f.get ('/', function (req, rep) {
    rep.send({ hello: 'world', test1: true })
  })
  next()
},{
  name: 'test1'
})
```
and 
```js
const test1 = async function (f,o, next) {
  f.get ('/', function (req, rep) {
    rep.send({ hello: 'world', test1: true })
  })
  next()
}

const meta = {
  name: 'test1',
  decorators: {
    fastify: ['mongo', 'service.user', 'service.token']
  }
}

test1[Symbol.for('fastify.display-name')] = meta.name
test1[Symbol.for('plugin-meta')] = meta
```
I was looking through the code for `fastify-plugin` and it basically does the same thing?

**Comment by Eomm** [comment]
What change is the scope where the plugin acts for the decorate method.
[Here](https://github.com/fastify/fastify/blob/1.x/docs/Plugins.md#handle-the-scope) you can find all the details you need.

**Comment by nurdism** [comment]
Ahh, I see. Neato, thanks for the info!
