### ISSUE TITLE
Fastify-express

### ISSUE THREAD

**Issue by Code-Vader** [fastify/help#510]
Greetings

I was wondering since Fastify-express takes care of the 'use' function for middleware is there a function for the 'express.set' in fastify-express. An example is for the view engine or would fastify-pointofview be the way to go about it?

app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');

**Comment by MetCoder95** [comment]
I would say that I heavily suggest you go directly with `point-of-view`. Fastify doesn't provide a view engine by default neither a way to set static folders
