### ISSUE TITLE
How to implement "remember me" with fastify session?

### ISSUE THREAD

**Issue by oldtinroof** [fastify/help#511]
This was already raised on the old repo for fastify-session: https://github.com/SerayaEryn/fastify-session/issues/106, but the person who raised it solved it for their own custom session store, with no other answers.

#### What are you trying to achieve, or the steps to reproduce?

I'd like to be able to control the age of the cookie programatically to only return a long lived cookie if a user selects a "remember me" option.

I took the above persons suggestion for amending the session constructor and applied this with patch-package which works for now:

```
this.cookie = new Cookie(prevSession.cookie || cookieOpts)
this[maxAge] = prevSession.expires ? new Date(prevSession.expires).getTime() : cookieOpts.maxAge
```

Then setting the max age of the cookie in my auth route with:

```
if (remember) {
  req.session.cookie.maxAge = COOKIE_AGE;
}
```

I'm using connect-pg-simple for my session store, and wondered if there was a way to handle changing the maxAge of the cookie within a route without patching?

#### Context

node version: 14.6.1
fastify version: 3.14.2
@fastify/session version: 6.1.0

**Comment by zekth** [comment]
Isn't `request.sessiin.touch()` solving your case?

**Comment by oldtinroof** [comment]
Nope, it doesn't seem to do anything... I think the original issue on the old repo mentioned that too.

**Comment by zekth** [comment]
Oh sorry i get it. You mean having a cookie config PER session which makes you able to set the maxAge / Expires depending on business conditions. Currently that is not possible and it makes sense to implement it.

**Comment by oldtinroof** [comment]
Ah great, thanks for the clarification! I'm happy to put a PR together with the working changes if that helps?

**Comment by zekth** [comment]
Sure go for it :)

**Comment by patilanz** [comment]
Hello, any updates on this topic?

**Comment by zbo14** [comment]
I think we can close bc [this PR](https://github.com/fastify/session/pull/53) is now merged.
