### ISSUE TITLE
`async/await` flow control

### ISSUE THREAD

**Issue by cusxio** [fastify/help#512]
https://www.fastify.io/docs/latest/Routes/#promise-resolution

## Question

When using an async handler, the doc says `Do not return any value.`, but is it safe to return `reply.send` or `reply.redirect` ?

## Example

Is the code example below valid?

```js
fastify.route({
  method: "GET",
  url: "/confirm",
  async handler(req, res) {
    if (!token) {
      return res.redirect('/');
    }

    if (token === "invalid") {
      throw httpError();
    }

   return { msg: "Ok!" };
  },
});
```

or is something like this needed?

```js
fastify.route({
  method: "GET",
  url: "/confirm",
  async handler(req, reply) {
    if (!token) {
       reply.redirect('/');
    } else if (token === 'invalid') {
      throw httpError()
    } else {
      return { msg: "Ok!" }; 
    }
  },
});
```

**Comment by climba03003** [comment]
The document said use either `return {}` or `reply.send` in a single handler. Do not use both at the same time.

**Comment by cusxio** [comment]
I'm not talking about using both handlers though.

I'm mainly asking about **returning** `reply.redirect` or `reply.send` in an async function.

i.e. is `return reply.redirect('/')` or return `return reply.send({})` valid?

---

For example, is the code below "correct"?
https://github.com/ryands17/fastify-prisma/blob/db20fc59196ff801259dcf59619bf5d6460f3108/src/controllers/auth.ts#L32-L34

**Comment by climba03003** [comment]
> 
> 
> I'm not talking about using both handlers though.
> 
> I'm mainly asking about **returning** `reply.redirect` or `reply.send` in an async function.
> 
> i.e. is `return reply.redirect('/')` or return `return reply.send({})` valid?
> 
> For example, is the code below "correct"?
> https://github.com/ryands17/fastify-prisma/blob/db20fc59196ff801259dcf59619bf5d6460f3108/src/controllers/auth.ts#L32-L34

Yes, `return reply.send` and `return reply.redirect` is valid. As `reply` is a PromiseLike object.

**Comment by cusxio** [comment]
Good to know! Thank you.

I guess I was just really confused with the docs.

![Screenshot 2021-08-22 at 10 08 41 PM](https://user-images.githubusercontent.com/6487613/130358186-2f976fc6-f177-49ce-9bf5-cacdfb005505.png)
