### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by davidschmitt** [fastify/help#513]
## Why am I getting timeouts on a fastify-express route?

I'm seeing timeout messages in the log and I'm trying to understand if this is:

1. normal
2. a bug in my code
3. or a bug in fastify-express.

The answer is important to me because fastify-express is preventing some of my normal Fastify routes from working (hangs right after preParsing hook fires), and I'm trying to troubleshoot what is going on (possibly a separate issue).

I understand fastify-express is not a long term (or production) solution, but right now it is not even working in a development environment for me, and that is a big loss for converting our existing code.

Here's a sample from the log:
```
{"level":30,"time":1629667708921,"pid":45105,"hostname":"toolbox","reqId":"req-2","req":{"method":"POST","url":"/authMs","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":35122},"msg":"incoming request"}
{"level":40,"time":1629667708922,"pid":45105,"hostname":"toolbox","reqId":"req-2","msg":"=== [onRequest] ==="}
Express route handler starting (req-2)
Response send() & end() complete.
Express route handler (send() & end() & next()) complete (req-2)
{"level":40,"time":1629667709394,"pid":45105,"hostname":"toolbox","reqId":"req-2","msg":"=== [preParsing] ==="}
{"level":40,"time":1629667709397,"pid":45105,"hostname":"toolbox","reqId":"req-2","msg":"=== [onResponse] ==="}
{"level":30,"time":1629667709397,"pid":45105,"hostname":"toolbox","reqId":"req-2","res":{"statusCode":200},"responseTime":475.74829199910164,"msg":"request completed"}
{"level":40,"time":1629667714398,"pid":45105,"hostname":"toolbox","reqId":"req-2","msg":"=== [onTimeout] ==="}
```

Here's the relevant parts of the code I'm using:

```js
import FastifyExpress from "fastify-express";
import { Router } from "express";

// Function that generates Express response
async function authMs(req, reply): Promise<void> {
   // Details removed for brevity
  res.status(200);
  res.send(data);
  res.end();
  console.log("Response send() & end() complete.");
}

const router = Router();
router.route("/authMs").post((req, reply, next) => {
  const id = (req as unknown as { id: string }).id;
  console.log(`Express route handler starting (${id})`);
  authMs(req, reply).finally(() => {
    next();
    console.log(`Express route handler (send() & end() & next()) complete (${id})`);
  })
});

const fastify = Fastify({  logger: true  });
fastify.addHook("onTimeout", (request, reply, done) => {
  request.log.warn("=== [onTimeout] ===");
  done();
});
// Repeat above addHook code for all the other possible hooks

await fastify.register(FastifyExpress);
fastify.use(this.router);
fastify.express.disabled("x-powered-by");

```

## My Environment

- *node version*: 14.17
- *fastify version*: 3.20.2
- *fastify-express version*: 0.3.3
- *express version*: 4.17.1
- *os*: Linux

**Comment by climba03003** [comment]
When using `fastify-express`, it should not fall into the normal `fastify` lifecycle.
The `preParsing` and `onTimeout` is not trust-able as all those works is done by `express`.

**Comment by davidschmitt** [comment]
Thanks @climba03003 , is there something I can configure to stop the `fastify` lifecycle get trigger?

On a separate note, I realized the `next()` call in the Express route handler doesn't belong.  I added it as part of my testing, but removing it does not change the onTimeout appearing in the log.

**Comment by mcollina** [comment]
Can you please include an example that we can run to trigger the problem?

**Comment by davidschmitt** [comment]
Below is a simple TypeScript example that demonstrates the behavior.  A couple notes:

1. A timeout only occurs on some runs of the server (i.e. `node .`)
2. If a timeout occurs, it seems to occur for all requests handled by that server process.
3. Based on that it seems like a race condition somewhere (perhaps during registration?)

```js
import Fastify from "fastify";
import FastifyExpress from "fastify-express";
import { Request, Response, Router } from "express";

async function sendResponse(req: Request, res: Response): Promise<void> {
  res.status(200).send(`pong ${Date.now()}`).end();
}

async function start(): Promise<void> {
  const router = Router();
  router.get("/ping", (req, res) => {
    sendResponse(req, res);
  });

  const fastify = Fastify({ logger: true });
  fastify.addHook("onTimeout", (request, reply, done) => {
    request.log.warn("=== onTimeout ===")
    done();
  });
  fastify.addHook("onResponse", (request, reply, done) => {
    request.log.warn("=== onResponse ===")
    done();
  });

  await fastify.register(FastifyExpress);
  fastify.use(router);
  fastify.express.disabled("x-powered-by");

  fastify.listen(8080, (err, address) => {
    if (err) {
      fastify.log.error(err);
      process.exit(1);
    }
    fastify.log.warn(`Server listening at ${address}`);
  });
}
```

And here's the output I saw when I hit http://localhost:8080/ping from my browser:

```
{"level":30,"time":1629739013020,"pid":16252,"hostname":"toolbox","msg":"Server listening at http://127.0.0.1:8080"}
{"level":40,"time":1629739013020,"pid":16252,"hostname":"toolbox","msg":"Server listening at http://127.0.0.1:8080"}
{"level":30,"time":1629739023182,"pid":16252,"hostname":"toolbox","reqId":"req-1","req":{"method":"GET","url":"/ping","hostname":"localhost:8080","remoteAddress":"127.0.0.1","remotePort":52766},"msg":"incoming request"}
{"level":40,"time":1629739023195,"pid":16252,"hostname":"toolbox","reqId":"req-1","msg":"=== onResponse ==="}
{"level":30,"time":1629739023195,"pid":16252,"hostname":"toolbox","reqId":"req-1","res":{"statusCode":200},"responseTime":12.52398999966681,"msg":"request completed"}
{"level":40,"time":1629739028200,"pid":16252,"hostname":"toolbox","reqId":"req-1","msg":"=== onTimeout ==="}
```

**Comment by davidschmitt** [comment]
Full disclosure - because of this and the more serious problem we encountered with normal fastify routes hanging after adding fastify-express we have decided to forgo `fastify-express` completely.  I'm happy to close this issue if the fastify team doesn't with to pursue it at this time.

**Comment by Eomm** [comment]
I would try

```diff
- res.status(200).send(`pong ${Date.now()}`).end();
+ res.send(`pong ${Date.now()}`):
```

https://expressjs.com/it/4x/api.html#res.end

**Comment by davidschmitt** [comment]
I tried that change @Eomm (send() without status() nor end()), but I still see the same onTimeout occur:

{"level":30,"time":1630328121250,"pid":11443,"hostname":"toolbox","reqId":"req-1","req":{"method":"GET","url":"/ping","hostname":"localhost:8080","remoteAddress":"127.0.0.1","remotePort":37370},"msg":"incoming request"}
{"level":40,"time":1630328121256,"pid":11443,"hostname":"toolbox","reqId":"req-1","msg":"=== onResponse ==="}
{"level":30,"time":1630328121256,"pid":11443,"hostname":"toolbox","reqId":"req-1","res":{"statusCode":200},"responseTime":5.8079959999304265,"msg":"request completed"}
{"level":40,"time":1630328126257,"pid":11443,"hostname":"toolbox","reqId":"req-1","msg":"=== onTimeout ==="}

However, I'm going to close this issue since we are no longer using fastify-express
