### ISSUE TITLE
Parse body as json not working via .inject()

### ISSUE THREAD

**Issue by petef19** [fastify/help#514]
#### What are you trying to achieve, or the steps to reproduce?

Have a small fastify server up and running. Running simple unit test via `Jest` using the `.inject` method to run fake queries.

Read the docs and interpreted them that `content-type` of `application/json` is parsed by default. However, I have to use `JSON.parse` on the `body` object manually to decode the data.

Also tried to manually add the json parser to fastify, but same result.
```
fastify.addContentTypeParser('application/json', {parseAs: 'string'},
  (req, body, done) => {
  try
  {
      const json = JSON.parse(body as string)
      done(null, json)
  }catch(err)
  {
      err.statusCode = 400
      done(err, undefined)
  }
});
```

#### What was the result you received?

here's an example what `Jest` receives in the expect assertion: `Received: "{\"bar\":\"foo\",\"baz\":\"foobar\"}"`

#### What did you expect?

`{"bar":"foo","baz":"foobar"}`

#### Context

* *node version*: 14.16.0 x64
* *fastify version*: 3.19.2
* *Win 10 x64*

Is it possible to auto-parse the response from `.inject()` ?

Thanks.

**Comment by mcollina** [comment]
Can you upload a self-contained example (no jest) that we can execute to verify this behavior?

**Comment by petef19** [comment]
@mcollina 
thanks for the quick reply. 

I updated my original post, it was unclear what I was actually referring to. I'm running fake queries via `.inject()` in my unit tests and was wondering whether it's possible to auto-parse the response that it returns (e.g. json) ?

**Comment by climba03003** [comment]
> 
> I updated my original post, it was unclear what I was actually referring to. I'm running fake queries via `.inject()` in my unit tests and was wondering whether it's possible to auto-parse the response that it returns (e.g. json) ?

It is just like how `fetch` is used. You need to call `.json` for the parsed json response.
Please check how `light-my-request` API in https://github.com/fastify/light-my-request#injectdispatchfunc-options-callback
```js
const response = await fastify.inject()
const json = await response.json()
```

**Comment by petef19** [comment]
> ```js
> const response = await fastify.inject()
> const json = await response.json()
> ```

thank you, this works w/ a response of `content-type: application/json` !
