### ISSUE TITLE
Help to choose between fastify-static and nginx

### ISSUE THREAD

**Issue by philosofonusus** [fastify/help#519]
We have a highly loaded application that handles a lot of video images in particular. What would you recommend, to use nginx static or fastify-static? If you have benchmarks it would be great

**Comment by kibertoad** [comment]
For production, if performance is important - definitely nginx. See https://stackoverflow.com/questions/44796056/whats-the-better-approach-serving-static-files-with-express-or-nginx (caveats similar to express apply)

**Comment by jsumners** [comment]
Dedicated file servers like nginx are the way to go for static resources. Node.js is not meant to fill that role.

**Comment by philosofonusus** [comment]
Thank you all
