### ISSUE TITLE
Difficulty returning text/plain from request with application/json

### ISSUE THREAD

**Issue by DavidLGoldberg** [fastify/help#520]
### Context
We have a proxy for : https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http#request-1

If you notice the response is only application/json in the error case.

### Fastify
When I pass in a Content-Type of 'application/json' fastify wants to serialize the output and my response of

```
reply.send('Accepted')
```
or
```
return 'Accepted'
```
returns an error complaining about trying to deserialize 'Accepted' (it's looking for JSON)

In my schema, I've tried various variants.  Is this "mixed mode" (that's what I'm calling it) swap between application/json (input) and "text/plain" output possible with fastify?  The custom providers for text/plain seem to be concerned with the text/plain -> text/plain scenario.  What am I missing?  I am pretty new to fastify.

I've scanned the source for mention of the 'Accept' request header, but only found that's referenced in the tests.  It'd be nice if fastify could swap to a text/plain provider for a response given 'text/plain' as the only value in an 'Accept' header for instance.  Would such a PR be accepted (if it's not already an option/process I'm missing)?

(Somewhat related to):
https://github.com/fastify/fastify/issues/3123

**Comment by zekth** [comment]
Can you share an example of your schema + api code?
I tried to reproduce the case but haven't had a chance to get the issue.

**Comment by DavidLGoldberg** [comment]
User error :)

Some fumbling with curl tools etc.  Thanks.  Sorry about that.
