### ISSUE TITLE
fastify-cookie + middie setup

### ISSUE THREAD

**Issue by bjufre** [fastify/help#521]
## 💬  Question here 

We're migrating an Express app over to Fastify, and we're rewriting some of the middlewares and how logic is handled. Nonetheless, we hit some issues or what we think are some issues when trying to have a setup with `fastify-cookie` + `middie`. We register the `cookie` plugin first and then the `middie` one. And then in a custom `middleware` we try to read the `req.cookies` which ends up being `undefined`.

```js
// plugins.js
import fastifyCookie from 'fastify-cookie'
import fastifyFormbody from 'fastify-formbody'
import fastifyHelmet from 'fastify-helmet'
import { ipAddress } from './ipAddress'
import locals from './locals'
import middie from 'middie'
import qs from 'qs'
import { store } from './store'

const OPS_DNSPREFETCH = { allow: false }
const OPS_FRAMEGUARD = { action: 'deny' }
const OPS_HSTS = {
  includeSubDomains: true,
  maxAge: 31536000,
  preload: true
}

export const plugins = async(app) => {
  // See here: https://helmetjs.github.io/#how-it-works
  // for which measures are active by default.
  app.register(fastifyHelmet, {
    // Active measures
    dnsPrefetchControl: OPS_DNSPREFETCH,
    frameGuard: OPS_FRAMEGUARD,
    hsts: OPS_HSTS,

    // Be explicit about disabled security
    // measures just in case...
    //
    /* eslint-disable sort-keys */
    crossOriginResourcePolicy: false,
    crossOriginOpenerPolicy: false,
    contentSecurityPolicy: false,
    expectCt: false,
    permittedCrossDomainPolicies: false,
    referrerPolicy: false
    /* eslint-enable sort-keys */
  })
  app.register(fastifyFormbody, {
    parser: str => {
      return qs.parse(str)
    }
  })
  app.register(fastifyCookie)
  await app.register(middie)

  // CUSTOM PLUGINS
  app.register(locals)
  app.register(ipAddress)
  app.register(store)
}
````

```js
// Middleware cookies.js
import set from 'lodash/set'
import { buildCookieName, dictionary, getCookieOptions, getFallbacks } from '~/utils/cookies'

const USER_SEGMENTATION_COOKIES = [
  dictionary.CSF.id,
  dictionary.CDF.id,
  dictionary.POLYMERE.id,
  dictionary.POLYMERE_CRIT.id
]

const getValues = (req, cookie, fallbacks, formattedName) => {
  const { id, legacyName, parse } = cookie
  const fallbackValue = fallbacks[id]

  if (legacyName) {
    const legacyValue = req.cookies[legacyName]
    const value = req.cookies[formattedName] || parse(legacyValue) || fallbackValue // <= TRYING TO READ `req.cookies` throws error

    return { value }
  }

  return { value: req.cookies[formattedName] || fallbackValue } // <= TRYING TO READ `req.cookies` throws error
}

const cookies = (req, res, next) => {
  if (req !== 'undefined' && !(res._headerSent || res.headersSent)) {
    const fallbacks = getFallbacks()
    const options = getCookieOptions()

    Object.values(dictionary).forEach((cookie) => {
      const { id } = cookie
      const formattedName = buildCookieName(cookie)
      const { value } = getValues(req, cookie, fallbacks, formattedName)

      res.cookie(formattedName, value, options)

      const stateKey = USER_SEGMENTATION_COOKIES.includes(id) ? 'user.segmentation' : 'app'

      set(res, `locals.preloadedState.${stateKey}.${id}`, value)
    })
  }

  next()
}
```

Although this is just an example of the explicit `cookies` middleware, we have a couple more that rely/depend on the cookies being available in the `request` object.

## Extra
Note that we have set up a custom localhost domain so that we can test and develop without problems when using cookies.

## Your Environment

- *node version*: v14.15.0 
- *fastify version*: 3.20.2
- *os*: Mac

**Comment by mcollina** [comment]
`fastify-cookie` reads the cookies and place them in `fastify` own Request object. `middie` uses the Node.js core `IncomingMessage` and therefore it does not know about the cookies. Some changes would be needed to expose the Fastify object inside middie middlewares, but I think it would be possible if you'd like to send a PR.

**Comment by bjufre** [comment]
@mcollina That sounds feasible. How would you like it to look like? I mean from the user's perspective the usage of middie should change? Or are users expected to keep using middie like as they currently do? Or do we want `middie` to become a fastify middleware? And then users can always use the `req.raw` or `reply.raw` if they need to?

I'm basically wondering how the API would look like from the user POV if we change this 🤔

**Comment by bjufre** [comment]
@mcollina how would something like this look like:

```js
function build() {
  const app = Fastify()

  await app.register(require('middie'))

  return app
}

build.then(app => {
  app.use(someFastifyMiddleware)
  
  // This would allow to opt-out of the Fastify Request and Reply objects and go have direct access to
  //  the Node.js Request & Response objects.
  app.use(someRawMiddleware, { raw: true })
})
```

WDYT? That would make quite explicit which middlewares are expected to run like with a layer of compatibility with Nodejs request-response or directly with Fastify's.

**Comment by bjufre** [comment]
I was looking at the code, and although it can be done I think that it might add a little bit of complexity, which might not be necessary.

Another approach that I was thinking, is that we can use encapsulation so that if a user wants to use the `raw` approach for the middlewares, the user could do so by passing `{ raw: true }` as option to the `await fastify.register(require('middie'), { raw: true })` 🤔
