### ISSUE TITLE
Using `fastify-rate-limit` with `fastify-bearer-auth`; setting seperate limit headers for 401 Unauthorized responses?

### ISSUE THREAD

**Issue by Fdawgs** [fastify/help#522]
## 💬  Question here 

I would like to rate-limit 401 responses to add an extra hurdle for clients attempting to brute-force endpoints trying to guess a bearer token.
I am using both [`fastify-bearer-auth`](https://github.com/fastify/fastify-bearer-auth) and [`fastify-rate-limit`](https://github.com/fastify/fastify-rate-limit).

```js
const fastify = require('fastify')();

// Import plugins
const bearer = require('fastify-bearer-auth');
const rateLimit = require('fastify-rate-limit');

const keys = new Set(['a-super-secret-key', 'another-super-secret-key']);

const server = async () => {
	fastify
		.register(rateLimit)
		.register(bearer, { addHook: false, keys });

	fastify.get(
		'/foo',
		{ preHandler: fastify.verifyBearerAuth },
		(req, reply) => {
			reply.send({ authenticated: true });
		}
	);

	fastify.listen({ port: 8000 }, (err) => {
		if (err) {
			fastify.log.error(err.message);
			process.exit(1);
		}
	});
};

server();
````

Using the above code for the server, if i make a GET request, the 401 response inherits the server's rate limits:
```
> GET /foo HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: insomnia/2021.5.0
> Authorization: Bearer invalidkey
> Accept: */*

< HTTP/1.1 401 Unauthorized
< surrogate-control: no-store
< cache-control: no-store, max-age=0, must-revalidate
< pragma: no-cache
< expires: 0
< x-ratelimit-limit: 1000
< x-ratelimit-remaining: 985
< x-ratelimit-reset: 52
< content-length: 82
< content-type: application/json; charset=utf-8
< Date: Tue, 31 Aug 2021 13:45:21 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
```

I can obviously customize the 404 response to use a separate rate limiter:

```js
	fastify.setNotFoundHandler(
		{
			preHandler: fastify.rateLimit({ max: 10, timeWindow: 60000 }),
		},
		(req, res) => {
			res.notFound(`Route ${req.method}:${req.url} not found`);
		}
	);
```

Is the same possible with a 401 (or other error) response?

## Your Environment

- *node version*: 14.17.5
- *fastify version*: 3.20.2
- *os*: Windows

**Comment by mcollina** [comment]
I don't think this is currently supported by fastify-rate-limit. I'm not even sure what API we would need to expose to let users implement this.

**Comment by Eomm** [comment]
The rate limit is assigned to the route, not to the route's reply status code.

I would use the rate-limit's `max` function option to choose the max requests number:

```
if(req.userid){
  return 1000
} else {
  return 10
}
```

**Comment by MetCoder95** [comment]
See what are you trying to implement here, faced similar needs based on business requirements. We ended having a rough implementation using Redis instead. Being honest the ergonomics can be pretty weird if `fastify-rate-limit` tries to provide an API that handles the rate-limit store based on HTTP status codes. Maybe having another handler that works with the `onResponse` hook, but being disabled by default and implemented on-demand (pretty similar to the function that decorates `fastify` instance.)

Even tho, the API will look quite weird 😅

**Comment by Fdawgs** [comment]
> 
> 
> The rate limit is assigned to the route, not to the route's reply status code.
> 
> I would use the rate-limit's `max` function option to choose the max requests number:
> 
> ```
> if(req.userid){
>   return 1000
> } else {
>   return 10
> }
> ```

Thanks @Eomm!

Managed to get this working using this monstrosity (not a complete example, the auth function is not fully implemented):

```js
async function server() {
	await fastify
		.register(bearer, {
			auth: async (key, req) => {
				if (keys.includes[req.headers.authorization]) {
					req.userid = "valid";
					return true;
				}

				req.userid = "invalid";
				return false;
			},
			keys,
		})
		.register(rateLimit, {
			max: async (req, key) => {
				if (req.userid === "valid") {
					return 1000;
				}
				return 10;
			},
		});

	fastify.route({
		method: "GET",
		url: "/foo",
		onSend: fastify.rateLimit(),
		handler: async (req, res) => {
			res.send({ hello: "world" });
		},
	});

	await fastify.listen({ port: 8000 });
}

server();


```
