### ISSUE TITLE
Deploy fastify to Azure CI

### ISSUE THREAD

**Issue by wikin** [fastify/help#523]
Hello,
pls do you have any guide how to set up deploy task for Azure App Service? I previously run it on Express, I try to switch to Fastify, but deployed file server.js did not start (yes, I used command `node server.js` in release pipe).  

I even try to add config ENABLE_ORYX_BUILD = false

here is my list of files, interesting is only file server.js is created and deployed by me

```
lrwxrwxrwx 1 nobody nogroup      13 Sep  1 13:02 _del_node_modules -> /node_modules
-rwxrwxrwx 1 nobody nogroup      27 Sep  1 13:01 package-lock.json
-rwxrwxrwx 1 nobody nogroup 1150671 Sep  1 10:29 server.js
```

Tnks for any help.

**Comment by Eomm** [comment]
Did you set the host parameter?
https://github.com/fastify/fastify/blob/main/docs/Server.md#listen
