### ISSUE TITLE
fastify-auth examples using `preHandler`

### ISSUE THREAD

**Issue by xdc0** [fastify/help#524]
Why does `fastify-auth` usage documentation uses `preHandler`?

The usage section of [fastify-auth](https://github.com/fastify/fastify-auth#usage) uses `preHandler` as examples, could yo confirm if this is the recommended hook? Looking at [fastify's lifecycle](https://www.fastify.io/docs/latest/Lifecycle/), it seems to me that a better example would be `onRequest` or `preParsing` otherwise if your routes have, for example, a validation schema, the validation will run before authentication that is configured on a `preHook` so unauthenticated requests bodies will always be validated.

Of course, every application might call for a specific hook to use, but wouldn't it be `onRequest` or `preParsing` a better default for examples? [`fastify-basic-auth`](https://github.com/fastify/fastify-basic-auth#usage) uses `onRequest` on their usage examples. Is there something on `fasify-auth` that requires it to be registered as a `preHandler` hook?

Thank you for your time.

**Comment by mcollina** [comment]
preHandler is more generic as some auth mechanisms requires data to be present in the request body. I would use onRequest in most cases.
