### ISSUE TITLE
fastify response schema validation throws error

### ISSUE THREAD

**Issue by jithinktom** [fastify/help#529]
When my response does not match with the schema defined, it throws an error and breaks the application. I want a solution to log this as an error/warning, instead of breaking the application.

![image](https://user-images.githubusercontent.com/10219327/133468642-125fbd73-0234-4da4-ab73-aba9962c70a3.png)

As you can see in the image, `relatedKeywords` is type array. But from my code, for some reason, it was populated as object. I get this error then:
<img width="1424" alt="Screenshot 2021-09-15 at 9 35 08 PM" src="https://user-images.githubusercontent.com/10219327/133469288-f1f59942-b373-4379-b94b-61665301b439.png">

**Comment by mcollina** [comment]
Please add a runnable example to reproduce.

**Comment by kibertoad** [comment]
Stale issue.
