### ISSUE TITLE
Logger options not working

### ISSUE THREAD

**Issue by chisanupolwo** [fastify/help#531]
I try to apply the logger system on the fastify by adding the path of the logger file. But the logger still does not effect on the file. The fille still blank. The code below is the way I try to implement the log system.

import { join } from 'path';
import AutoLoad, {AutoloadPluginOptions} from 'fastify-autoload';
import { FastifyLoggerOptions, FastifyPluginAsync } from 'fastify';

export type AppOptions = {
  // Place your custom options for app below here.
} & Partial<AutoloadPluginOptions> & Partial<FastifyLoggerOptions>;

const app: FastifyPluginAsync<AppOptions> = async (
    fastify,
    opts
): Promise<void> => {
  // Place here your custom code!
  opts.level = 'info'
  opts.file = 'logger'
  fastify.log.info('Test log')
  // Do not touch the following lines

  // This loads all plugins defined in plugins
  // those should be support plugins that are reused
  // through your application
  void fastify.register(AutoLoad, {
    dir: join(__dirname, 'plugins'),
    options: opts
  })

  // This loads all plugins defined in routes
  // define your routes in one of these
  void fastify.register(AutoLoad, {
    dir: join(__dirname, 'routes'),
    options: opts
  })

};

export default app;
export { app }

**Comment by climba03003** [comment]
`fastify-autoload` do not have options for `level` and `file`.
Please check the document carefully how it works.
