### ISSUE TITLE
Pipe url provided in a query URL as a response

### ISSUE THREAD

**Issue by pukhalski** [fastify/help#533]
Hello team, 
using `axios` I am trying to pipe any provided URL data as a response with no success.

```
app.get('/', (request, reply) => {
    return axios
      .get(request.query.uri, {
        responseType: 'stream'
      })
      .then(result => result.data.pipe(reply.send))
 })
```

**Comment by climba03003** [comment]
You cannot pipe to the `reply.send` as it will not consume the stream directly. Instead, you should `reply.send(<stream>)` and the function will helps you to pipe the correct stream.

**Comment by pukhalski** [comment]
@climba03003  thank you, however the example below doesn't work as well :)

```
app.get('/', (request, reply) => {
    return axios
      .get(request.query.uri, {
        responseType: 'stream'
      })
      .then(result => reply.send(result.data))
 })
```

**Comment by climba03003** [comment]
> @climba03003  thank you, however the example below doesn't work as well :)
> 
> ```
> app.get('/', (request, reply) => {
>     return axios
>       .get(request.query.uri, {
>         responseType: 'stream'
>       })
>       .then(result => reply.send(result.data))
>  })
> ```

You should not return the axios.

**Comment by climba03003** [comment]
I dont know why you cannot pipe it but when I test it works properly.
https://replit.com/@climba03003/fastify-axios-stream#index.js

**Comment by pukhalski** [comment]
Works fine with content type header proxied Thanks!
