### ISSUE TITLE
Additional properties weren't removed when using json-schema-to-ts

### ISSUE THREAD

**Issue by meotimdihia** [fastify/help#538]
## 💬  Question here 
This is my Ajv configs
```js
const ajv = new Ajv({
  removeAdditional: true,
  useDefaults: true,
  coerceTypes: "array",
  nullable: true,
})
fastify.setValidatorCompiler(({ schema }) => {
  return ajv.compile(schema)
})
```
```js
  const params = {
    type: "object",
    require: ["slug"],
    properties: {
      slug: { type: "string" }
    },
    additionalProperties: false // <-- if I miss this line, additional properties will show up.
  } as const

```

## Your Environment

- *node version*:  14
- *fastify version*: >=3.20.1
- *os*: Windows

**Comment by Eomm** [comment]
You need to set `removeAdditional: 'all'` if you dont' want to set the `additionalProperties: false` flag on schemas

https://ajv.js.org/options.html#options-to-modify-validated-data

**Comment by meotimdihia** [comment]
@Eomm thanks, `removeAdditional: 'all'` works but Typescript doesn't detect it.
And doesn't show errors when I am using the wrong properties unless I add `removeAdditional: 'all'` to the schema. 
Did we have a way to solve this?
