### ISSUE TITLE
fastify-auth & fastify-bearer-auth customize error response

### ISSUE THREAD

**Issue by jonahsnider** [fastify/help#539]
## 💬  fastify-auth customize error response

I'm using fastify-auth and fastify-bearer-auth like below:

```js
fastify.register(bearerAuthPlugin, {
	addHook: false,
	keys: new Set(['my api key']),
	errorResponse: (error: Error) => {
		switch (error.message) {
			case 'missing authorization header':
				return { message: 'some message' };
			default:
				return { message: 'some other message' };
		}
	},
}),
fastify.register(authPlugin),
```

```js
route.preHandler = fastify.auth([fastify.verifyBearerAuth]);
````

With fastify-bearer-auth v5 this code worked fine, but upgrading to v6 [changed the behavior](https://github.com/fastify/fastify-bearer-auth/pull/91) to instead respond with an empty response object (`{}`) instead of my custom responses.

How can I get the custom response to be sent with v6 of fastify-bearer-auth?

## Your Environment

- *node version*: 16.10.0
- *fastify version*: 3.21.6
- *os*: Linux
- *fastify-auth version*: 1.1.0
- *fastify-bearer-auth version*: 6.0.0

**Comment by mcollina** [comment]
Can you provide a full example to reproduce this problem?

**Comment by jonahsnider** [comment]
Sorry there was a mistake in my original description. When I remove the response schema (which conflicted with what fastify-auth is outputting) the actual response is

```json
{
  "statusCode": 401,
  "error": "Unauthorized",
  "message": "missing authorization header"
}
```

I'll try and make an example later today.

**Comment by jonahsnider** [comment]
Here's a simple example of this issue: [project.zip](https://github.com/fastify/help/files/7270905/project.zip)

Running the example starts a simple server with a protected route. Sending an unauthorized request will respond with
```json
{
  "statusCode": 401,
  "error": "Unauthorized",
  "message": "invalid authorization header"
}
```

on v6 of fastify-bearer-auth. v5 will run `errorResponse()` and respond with:
```json
{
  "error": "auth error",
  "extraData": {}
}
```

**Comment by VBetsun** [comment]
if you only need a previous response structure you can make it by:
```diff
await fastify.register(bearerAuthPlugin, {
-  addHook: false,
    keys: new Set(["secret"]),
    errorResponse: (error) => {
      return {
        error: "auth error",
        extraData: error,
      };
    },
  });
  await fastify.register(authPlugin);

  fastify.after(() => {
    fastify.route({
      method: "GET",
      url: "/",
-    preHandler: fastify.auth([fastify.verifyBearerAuth]),
+    preHandler: fastify.verifyBearerAuth,
      handler: async (request, reply) => {
        reply.send({ message: "hello world!" });
      },
    });
  });
```
