### ISSUE TITLE
Upstream prematurely closed connection while reading response header from upstream

### ISSUE THREAD

**Issue by ReTWi** [fastify/help#54]
Only on production with NGINX i've got this error if i send request object as response:
`2019/02/08 13:13:20 [error] 15816#15816: *8 upstream prematurely closed connection while reading response header from upstream, client: *deleted for this issue*, server:  *deleted for this issue*, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: " *deleted for this issue*"`

In my app logs on production i have this:
```
0|server   | TypeError: Converting circular structure to JSON
0|server   |     at JSON.stringify (<anonymous>)
0|server   |     at serialize (/var/www/knigam/node_modules/fastify/lib/validation.js:109:17)
0|server   |     at preserializeHookEnd (/var/www/knigam/node_modules/fastify/lib/reply.js:244:13)
0|server   |     at preserializeHook (/var/www/knigam/node_modules/fastify/lib/reply.js:234:5)
0|server   |     at _Reply.Reply.send (/var/www/knigam/node_modules/fastify/lib/reply.js:133:5)
0|server   |     at Object.fastify.get (/var/www/knigam/server.js:30:9)
0|server   |     at preHandlerCallback (/var/www/knigam/node_modules/fastify/lib/handleRequest.js:112:30)
0|server   |     at preValidationCallback (/var/www/knigam/node_modules/fastify/lib/handleRequest.js:101:5)
0|server   |     at handler (/var/www/knigam/node_modules/fastify/lib/handleRequest.js:70:5)
0|server   |     at handleRequest (/var/www/knigam/node_modules/fastify/lib/handleRequest.js:19:5)
```

In browser i've have 502 Bad Gateway error.

I think it's more about "TypeError: Converting circular structure to JSON", but why it's not working only on ubuntu? :/

Overall configuration:
I run node.js app on ubuntu 18.04 on localhost.
Nginx redirect request to localhost and after app give response, it's send it back.
* *node version*: 11.3.0
* *fastify version*: v2.0.0-rc.6
* *os*: ubuntu 18.04 

On localhost all works fine.
If i do like this on production, all works fine (same if i send big object):
```
fastify.get('/', (request, reply) => {
  reply.send({1:1})
})
```

My server.js code:
```
const fastify = require('fastify')({ignoreTrailingSlash: true, caseSensitive: false })
fastify.listen(3000, 'localhost', async (err, address) => {})
fastify.get('/', (request, reply) => {
  reply.send(request)
})
```

My NGINX conf:
```
server {
        charset utf-8;
        server_name **deleted for this issue**

        location / {
            proxy_pass http://127.0.0.1:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        listen [::]:443 ssl ipv6only=on; # managed by Certbot
        listen 443 ssl; # managed by Certbot
        ssl_certificate /etc/letsencrypt/live/**deleted for this issue**/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/**deleted for this issue**/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

# redirect from http to https
server {
    if ($host = **deleted for this issue**) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;

    server_name **deleted for this issue**;
    return 404; # managed by Certbot
}
```

Any ideas to try?

**Comment by mcollina** [comment]
What is the reasoning behind doing:

```js
const fastify = require('fastify')({ignoreTrailingSlash: true, caseSensitive: false })
fastify.listen(3000, 'localhost', async (err, address) => {})
fastify.get('/', (request, reply) => {
  reply.send(request)
})
```

I think the `request` object is not really meant to be transformed to JSON. Request has a circular reference in place, and it will throw an error.

**Comment by ReTWi** [comment]
I wanted to check how my request looks like after nginx proxy for future logging and get this error. So i start to look for a reason, because maybe this will heppen to other objects that I will work with. Question is it why is happening only in production on Ubuntu and not on Windows. If it's only about circular, that I don't think  I should be worried, because I don't think I will need to send objects like this.

**Comment by meranamvarun** [comment]
Hye @ReTWi, how did you fix this issue?
