### ISSUE TITLE
What's the proper TS signature for `decorateReply`

### ISSUE THREAD

**Issue by vorillaz** [fastify/help#544]
## 💬  Question here 

Hi there, once more thanks for the amazing project. I am trying to convert a project to typescript and I am struggling a lot with the typings of `decorateReply`. We are actually using lots of decorators across the application, thus it makes sense to expose  our own interfaces for `FastifyInstance`, `FastifyReply` and so on. It's weird though since we can't extend the FastifyReply decoratorated signature properly.

So in our route of the project we have our own signatures.
```typescript
// types.ts
interface MyOwnReply extends FastifyReply {
  foo?: string;
  myFn: (str: string) => MyOwnReply; // that part 
}
``` 

And a plugin that decorates the reply with a function.
```typescript
const myPlugin: FastifyPluginCallback = async (app, _opts, next) => {
  app.decorateReply("myFn", function myFn(this: MyOwnReply, str: string) {
    this.foo = 'hello';
    return this;
  });
};
export default fastifyPlugin(caching);
````

On our callsite we can't use a sample signature as:
```
// My MyOwnReply throws a typing error
app.get('/health', async (_req: FastifyRequest, reply: MyOwnReply) => {});
```

And also the a reply chain typechecking fails as well:
```typescript
reply.myFn('foo').send('baz');
```

Any help or code samples on how we could reuse and extend the `Request` and `Reply` typings would be highly appreciated.

## Your Environment

- *node version*: 10, 12, 13
- *fastify version*: >=2.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by RafaelGSS** [comment]
I strongly recommend you to follow the module augmentation instead: https://www.fastify.io/docs/latest/TypeScript/#creating-a-typescript-fastify-plugin.

```ts
declare module 'fastify' {
  interface FastifyReply {
    foo?: string;
    myFn: (str: string) => FastifyReply;
  }
}
```

**Comment by vorillaz** [comment]
Hey @RafaelGSS , this approach would "override" the types across the project. What happens if I have a monorepo setup with different fastify servers ?

**Comment by iampeterbanjo** [comment]
I have a similar question which I asked on [Stackoverflow](https://stackoverflow.com/questions/69987451/how-to-use-typescript-types-in-fastify-without-generics) but got no responses.

How can we import the generics that Fastify uses internally? Declaration merging is not possible in these examples -
- an error handler function
```
export const errorHandler: FastifyPluginCallback<any> = async function (
  fastify,
  options: any,
  next: Next
) {
  fastify.setErrorHandler(
    (
      error: FastifyError,
      request: FastifyRequest<
        RouteGenericInterface,
        RawServerBase,
        IncomingMessage,
        RawRequestDefaultExpression<RawServerBase>
      >,
      reply
    ) => { })
}
```
- a fastify test server
```
const Server = async (): Promise<FastifyServer> => {
  const server = fastify(testServerConfig);

  await server.register(database, { getDbConnection });
  await server.register(i18nPlugin);
  await server.register(sensible);
  await server.register(errorHandler);
  await server.register(customResponderPlugin);
  await server.register(accountRoutes);
  await server.ready();

  return server;
};
```
where FastifyServer is my custom type based on Fastify internals
```
export type FastifyServer = FastifyInstance<
  HttpServer,
  IncomingMessage,
  ServerResponse,
  FastifyLoggerInstance,
  HttpServer,
  IncomingMessage,
  ServerResponse
>;
```

**Comment by RafaelGSS** [comment]
It was not clear to me, why you need to specify generics in the `errorHandler` function? You can just omit it:

```diff
fastify.setErrorHandler(
    (
      error: FastifyError,
-      request: FastifyRequest<
-        RouteGenericInterface,
-        RawServerBase,
-        IncomingMessage,
-        RawRequestDefaultExpression<RawServerBase>
-      >,
+       request: FastifyRequest,
      reply
    ) => { })
```

**Comment by iampeterbanjo** [comment]
@RafaelGSS I'm using fastify@3.22.1 and when I remove the generics I get the type error
> Generic type 'FastifyRequest<RouteGeneric, RawServer, RawRequest, HttpRequest, Query, Params, Headers, Body>' requires between 4 and 8 type arguments.

**Comment by RafaelGSS** [comment]
@iampeterbanjo Can you open a new issue with a reproducible example?
