### ISSUE TITLE
Setting cookies in another domain

### ISSUE THREAD

**Issue by SaravanaKumar645** [fastify/help#545]
I have my server running on localhost:4000 and my client which is in next js running on localhost:3000 . The thing I want to achieve is that to set a cookie on my localhost:3000 whenever a request is made to the server . I have tried but it is not working with fastify .

Also it would be helpful if anyone tell me how to do that in production side also . Because I'm running my server on heroku and client on vercel .
Thanks for your replies. 🙂

**Comment by zekth** [comment]
Your cookie will always be attached to your server. On the other hand you can set the `SameSite` attribute of this cookie to `none`. Note that `none` attribute works only with `Secure` cookie. See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite
