### ISSUE TITLE
503 when a static file is changed. 

### ISSUE THREAD

**Issue by jeberly** [fastify/help#548]
#### You have already researched for similar issues?
yes

#### What are you trying to achieve, or the steps to reproduce?
I am trying serve up a Svelte app from `/app` route using fastify static files plugin. And using esbuild to recompile svelte app on save pushing html/css/js assets the directory served by `/app` 

```js
esbuild
  .build({
    entryPoints: ['app/src/main.ts'],
    bundle: true,
    outfile: 'app/dist/app.js',
    watch: {
      onRebuild(error, result) {
        clients.forEach((res) => res.write('data: update\n\n'));
        clients.length = 0;
        console.log(error ? error : '...');
      },
    },
    // banner: {
    //   js: ' (() => new EventSource("http://localhost:8000/esbuild").onmessage = () => setTimeout(() => {location.reload();},2000))();',
    // },
    plugins: [
      esbuildSvelte({
        preprocess: sveltePreprocess(),
      }),
    ],
    logLevel: 'info',
  })
  .catch(() => process.exit(1));
```

#### What was the result you received?
When a Svelte file is updated, my client side code triggers a `location.reload()`. Sometimes the index page loads fine, other times it returns a 503 `{"error":"Service Unavailable","message":"Service Unavailable","statusCode":503}`.  I verified this happens even if I trigger an update to files in static folder and I reload manually. 

#### What did you expect?
Not to return a 503. I expect? it may be restarting the server when it sees files have changed in the static directory? 

#### Context

* *node version*: 16
* *fastify version*: >=3.0.0
* *os*: Mac

**Comment by mcollina** [comment]
Could you include a full example to reproduce your problem? A repository would be perfect.
