### ISSUE TITLE
Change HTTP Method

### ISSUE THREAD

**Issue by 58bits** [fastify/help#55]
Hi all - Fastify looks lovely, so big thanks to @mcollina and contributors for this great framework. 

I have a question regarding changing the HTTP method of a request, from post to delete. 

This isn't as common a use case as it once was, but for a server-side rendered web app (for example using fastify/point-of-view), browsers that want to submit a delete request have typically post'ed the data, along with a hidden field with a name like _method - with a value indicating that this is a delete method. And then via middleware, or pre-request event, the hidden field is detected and the HTTP method 'changed' to delete, so that a common API endpoint or route for 'delete' can then be used to handle the request. How would this be achieved in Fastify? Also via a middleware plugin? Or on the onRequest hook? (or is this too late?).

**Comment by mcollina** [comment]
Unfortunately this is not supported, and not possible within fastify itself. You should be able to implement this feature using https://www.fastify.io/docs/latest/Server/#serverfactory, and changing the  method there based on the query parameter.

I think we should make this simpler.

**Comment by 58bits** [comment]
Okay understood @mcollina  - thanks for taking the time to reply.

**Comment by delvedor** [comment]
> I think we should make this simpler.

The only way to make this easier is to add a new hook before the routing, but since our router provides the encapsulation, we will miss that functionality.
