### ISSUE TITLE
HTTP fallback when using HTTP2

### ISSUE THREAD

**Issue by antoniogamizbadger** [fastify/help#552]
#### What are you trying to achieve, or the steps to reproduce?

I'm trying to deploy a Fasitfy application to Elastic Beanstalk, using HTTP2. To do that, I'm using an ALB to redirect the traffic . To do the health checks, I can only choose HTTP or HTTPS, not HTTP2. So when my load balancer does health requests to the server, it fails, as it expected because I have not setup a fallback. I start the server as follows:

```js
  const fastify = Fastify({ http2: true });
```

I have seen that I can specify an HTTPS fall back as second option, but then I need to attach the certificates on the filesystem of the instance, things I do not want to do (and do not know if it's possible on Beanstalk). So I would like a way to use HTTP with a fallback to HTTP, instead of HTTPS.

**Comment by mcollina** [comment]
It's not possible by the HTTP/2 standards. You need TLS to handle the protocol selection.
