### ISSUE TITLE
How to use JSONSchema in json-schema-to-ts with Fastify

### ISSUE THREAD

**Issue by meotimdihia** [fastify/help#553]
## 💬  Question here 
I get this error: `Property 'limit' does not exist on type 'never'.ts(2339)`.  Anyone know how to fix the error.

```ts
import { FastifyInstance } from "fastify"
import { FromSchema, JSONSchema } from "json-schema-to-ts"

async function routes(fastify: FastifyInstance) {
  const querystring: JSONSchema = {
    type: "object",
    properties: {
      limit: { type: "integer" }
    },
    additionalProperties: false
  } as const

  fastify.get<{
    Querystring: FromSchema<typeof querystring>
  }>(
    "/",
    {
      schema: {
        querystring: querystring
      }
    },
    async (req, reply) => {
      console.log(req.query.limit)
    }
  )
}

module.exports = routes

````
![Code_2021-11-04_11-38-13](https://user-images.githubusercontent.com/300961/140258878-3e2602d1-4e21-43b2-b1fc-23f944535a6a.png)

## Your Environment

- *node version*: 14
- *fastify version*: >= 3
- *os*:  Windows
- *any other relevant information*

**Comment by climba03003** [comment]
The main reason is the type of `querystring` is `JSONSchema`, which means it cannot turns a generic to an actual type. Even when you use `as const`.

Remove the `: JSONSchema` should helps.

**Comment by meotimdihia** [comment]
@climba03003 Do we have another way to autocomplete for schema?

**Comment by climba03003** [comment]
The document already give you three different approach.
https://github.com/fastify/fastify/blob/main/docs/TypeScript.md#json-schema

Choose either one that best fit your needs.
