### ISSUE TITLE
Can we force Fastify to retry registering a plugin on failure?

### ISSUE THREAD

**Issue by yukha-dw** [fastify/help#554]
#### What are you trying to achieve, or the steps to reproduce?

I want to implement retrying method when fastify failed to load a plugin. Interestingly, fastify will stop trying to register a plugin after first error (which is caught and ignored).

```ts
try {
    let retry = 1;
    while (retry < 100) {
      app.log.info(`Connecting to MongoDB Server. Attempt No ${retry}`);
      try {
        // eslint-disable-next-line no-await-in-loop
        await app.register(fastifyMongodb, { url: app.config.MONGO_URL, forceClose: true });
      } catch (error) {
        app.log.warn('Error happens while trying to connect to MongoDB Server');
      }
      if (app.mongo && app.mongo.db) {
        app.log.debug(
          { connectedDb: app.mongo.db?.namespace },
          'Successfully connected to MongoDB',
        );
        break;
      } else {
        if (retry >= 100) {
          app.log.error('Failed to connect to MongoDB Server after retrying 100 times');
        }
        app.log.info('Waiting 10s before reconnecting to MongoDB Server');
        // eslint-disable-next-line no-await-in-loop
        await new Promise((f) => setTimeout(f, 10000));
        retry += 1;
      }
    }

    if (!app.mongo.db) {
      throw new Error('Invalid state of MongoDB plugin');
    }
  } catch (err) {
    app.log.error({ err }, 'Failed to connect to MongoDB');
    process.exit(1);
  }
```

#### What was the result you received?
Fastify gave up to retrying and ignores try catch.
My hunch is app instance is no longer available after error?

## Case 1
Connecting to MongoDB Server. Attempt No 1
**Error happens while trying to connect to MongoDB Server -(Only shown ONCE)-**
Waiting 10s before reconnecting to MongoDB Server
Connecting to MongoDB Server. Attempt No 2
Waiting 10s before reconnecting to MongoDB Server
Connecting to MongoDB Server. Attempt No 3
Waiting 10s before reconnecting to MongoDB Server
etc.

## Case 2
Connecting to MongoDB Server. Attempt No 1
Waiting 10s before reconnecting to MongoDB Server
Connecting to MongoDB Server. Attempt No 2
**Failed to start server () -(The outermost try catch)-**

#### What did you expect?
Fastify will retry to register a plugin on error.

#### Context

* *node version*: 14
* *fastify version*: >=3.20.2
* *os*: Windows

**Comment by climba03003** [comment]
When the plugin is fail, it means that your instance should not be started. Because part of it or even dependency is missing.

In your example, `fastify-mongodb` timeout is nearly the same as `avvio` timeout. So, it cannot be failed more than one. You can increase the plugin timeout as your wish but I do not recommend.

**Comment by zekth** [comment]
This retry pattern should be inside the plugin itself not at the instance level.

**Comment by jsumners** [comment]
It's also probably not a great idea to wait on such a core service for so long. If it isn't available when the application starts, then something is not correct.

**Comment by yukha-dw** [comment]
> This retry pattern should be inside the plugin itself not at the instance level.

I'm wondering if i can wrap a plugin with a plugin, might be the answer.

> It's also probably not a great idea to wait on such a core service for so long. If it isn't available when the application starts, then something is not correct.

ikr, but with the limitation of environment that i have right now, the only possible way is to implement retry or doing it manually.

**Comment by yukha-dw** [comment]
Thanks for all of your responses, i got 2 plausible methods now.

1. based on @KaKa (deleted) workaround, which is instead of retrying, we could increase fastify's `pluginTimeout` & mongodb's `serverSelectionTimeoutMS` to required duration.

2. using pre-configured mongodb instance and feed it to fastify-mongodb
```
const mongodb = require('mongodb')
mongodb.MongoClient.connect('mongodb://mongo/db')
  .then((client) => {
    fastify.register(require('fastify-mongodb'), { client: client });
  })
  .catch((err) => {
    if (fastify.mongo) {
      await fastify.mongo.client.close();
    }
  })
```
