### ISSUE TITLE
jest unit tests hang when using jest.useFakeTimers

### ISSUE THREAD

**Issue by rburgst** [fastify/help#555]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.23.1

### Node.js version

14.18

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Monterey

### Description

When using fastify in a jest unit test calling

```javascript
    jest
      .useFakeTimers("modern")
      .setSystemTime(new Date("2020-02-08T20:10:21.520Z"));
``` 
causes the `server.inject` call to stall forever.

### Steps to Reproduce

see repro repo: https://github.com/rburgst/fastify-jest-timers

### Expected Behavior

it should be possible to mock the current system time using `jest.useFakeTimers().setSystemTime(...)`

**Comment by mcollina** [comment]
I moved this issue to help.

**Comment by jsumners** [comment]
Please file an issue with Jest. They create a new environment. We target Node.js.

**Comment by rburgst** [comment]
just for the record, we have countless repos with both fastify and jest and so far this combination has worked pretty great. So I am quite surprised about the statement

> (Generically I do not recommend to use Jest for testing Node.js applications)

@mcollina do you have further details on why this would be the case?

**Comment by mcollina** [comment]
https://github.com/facebook/jest/issues/2549 and a lot of other issues. To be honest it works fine 99% of the time but that remaining 1% keeps biting teams across the globe and they spend days trying to understand why things do not work as they expect to work as they do when running Node.js proper.

---

Regarding your problem, I think you are missing a call to run all the pending timers: https://jestjs.io/docs/timer-mocks.

**Comment by rburgst** [comment]
hmm, for the record, using 
https://www.npmjs.com/package/jest-environment-node-single-context
seems to work as suggested in https://github.com/facebook/jest/issues/2549#issuecomment-931725883

**Comment by kibertoad** [comment]
This seems to be related to plugin registration somehow.
The part that hangs is this: ` await fastify.ready()`, and if I add fake timer increment somewhere in between, `fastify.after` block is invoked without plugins having been properly registered.

**Comment by onosendi** [comment]
It seems `jest.useFakeTimers({ advanceTimers: true })` fixes the issue. Not really sure why, though.

From the docs:

```js
  /**
   * If set to `true` all timers will be advanced automatically by 20 milliseconds
   * every 20 milliseconds. A custom time delta may be provided by passing a number.
   * The default is `false`.
   */
  advanceTimers?: boolean | number;
```
