### ISSUE TITLE
Failed to install dependencies.

### ISSUE THREAD

**Issue by krave1986** [fastify/help#556]
#### You have already researched for similar issues?
Yes, I did.

#### What are you trying to achieve, or the steps to reproduce?

1. Run fastify initializer
```
npm init fastify
```

2. Install dependencies
```
npm install
```

#### What was the result you received?

> 5712 verbose stack Error: ENOENT: no such file or directory, rename '/workspaces/IntroductionToNodejs/mock-svr/node_modules/find-my-way' -> '/workspaces/IntroductionToNodejs/mock-svr/node_modules/.find-my-way.DELETE'
> 5713 verbose cwd /workspaces/IntroductionToNodejs/mock-svr
> 5714 verbose Linux 5.4.72-microsoft-standard-WSL2
> 5715 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
> 5716 verbose node v14.18.1
> 5717 verbose npm  v6.14.15
> 5718 error code ENOENT
> 5719 error syscall rename
> 5720 error path /workspaces/IntroductionToNodejs/mock-svr/node_modules/find-my-way
> 5721 error dest /workspaces/IntroductionToNodejs/mock-svr/node_modules/.find-my-way.DELETE
> 5722 error errno -2
> 5723 error enoent ENOENT: no such file or directory, rename '/workspaces/IntroductionToNodejs/mock-svr/node_modules/find-my-way' -> '/workspaces/IntroductionToNodejs/mock-svr/node_modules/.find-my-way.DELETE'
> 5724 error enoent This is related to npm not being able to find a file.
> 5725 verbose exit [ -2, true ]

#### What did you expect?
Dependencies installed correctly.

#### Context

* *node version*: v14.18.1
* *fastify version*: failed to install
* *os*: Ubuntu in docker based on WSL2

**Comment by jsumners** [comment]
cc: @davidmarkclements

**Comment by mcollina** [comment]
I think this is due to some WSL specific problem.

**Comment by krave1986** [comment]
Ah. I don't know what happened. But when I try to install it again, everything works fine. By the way, I have node.js official docker image installed with root user being the default and only one user right now. Thanks for your attention and have a great day!
