### ISSUE TITLE
How to use subdomain param within a request?

### ISSUE THREAD

**Issue by vorillaz** [fastify/help#557]
## 💬  Question here 

Hi there,
I have a simple Fastify application sitting behind a load balancer, so I could reroute the traffic to `client-name.example.com`.
I am actually trying to parse the subdomain within the request handler in order to do some checking since the subdomains are dynamically assigned.

```js
const fastify = require("fastify")({
  logger: true,
  trustProxy: true,
});

const port = process.env.PORT || 3001;

fastify.get("/", function (request, reply) {
  console.log(request.hostname);
  reply.send("done");
});

fastify.listen(port, function (err, address) {
  if (err) {
    fastify.log.error(err);
    process.exit(1);
  }
  fastify.log.info(`API server listening on ${address}`);
});

````

Trying a simple example as the above parses the hostname but I need to manually check the hostname and extract the subdomain.

One other approach it would be checking the subdomain on the proxy and passthrough a header in order to also have the ability to add some sort of validation, 

## Your Environment

- *node version*: 16
- *fastify version*: 3.23.1
- *os*: Mac

**Comment by jsumners** [comment]
Is there a question here? The framework receives HTTP requests. HTTP request specify the target host via the `HOST` header (https://datatracker.ietf.org/doc/html/rfc2616/#section-14.23).

**Comment by mcollina** [comment]
See https://www.fastify.io/docs/latest/Routes/#host-constraints

**Comment by janacm** [comment]
Updated link: https://www.fastify.io/docs/latest/Reference/Routes/#host-constraints
