### ISSUE TITLE
fastify-oauth2 microsoft example

### ISSUE THREAD

**Issue by Manubi** [fastify/help#559]
Hi everyone!

I am trying to get fastify-oauth2 with microsoft to work, but get stuck in the `getAccessTokenFromAuthorizationCodeFlow` function as it always says can't read properties of undefined.
![CleanShot 2021-11-11 at 21 32 57](https://user-images.githubusercontent.com/20935138/141365090-58346fd3-a54f-424f-9cfd-883c94ab93a4.png)
As you can see I do get the code from the userlogin in the url bar.

<img width="1137" alt="CleanShot 2021-11-11 at 21 33 52@2x" src="https://user-images.githubusercontent.com/20935138/141365185-70e3804c-0957-49da-a2ba-afe9bda22d6c.png">

Don't really know the way forward... How should/can I debug it?
The setup looks like this. 
<img width="769" alt="CleanShot 2021-11-11 at 21 41 16@2x" src="https://user-images.githubusercontent.com/20935138/141366067-719adb20-9185-46a8-ab55-f66510c32efd.png">

Would be awesome if someone could add a microsoft example!

Thanks a lot!

**Comment by Eomm** [comment]
Did you tried moving the callback endpoint into the second file, where there is the oauth2 plugin registration?

**Comment by Manubi** [comment]
No I didn't so far.. will try it tomorrow. But why should it make a difference?

I am using auto-load that's why I thought it makes sense to split the routes and plugins... if I need to put them in the same file it kind of doesn't make sense to use auto-load?

I am new to fastify and just trying to figure out a way forward. :)

Thanks!

**Comment by Eomm** [comment]
If the route works moving it on the file, it mean that there is a loading problem.

So you should share the app structure and the auto-load configuration.

> I am using auto-load that's why I thought it makes sense to split the routes and plugins... 

It is, as said it should be a matter of app structure and configuration

**Comment by Manubi** [comment]
Hi,
the problem was indeed that the plugin and the route weren't in the same file. 
thanks for your help!
