### ISSUE TITLE
Using with Mithril

### ISSUE THREAD

**Issue by NetOperatorWibby** [fastify/help#56]
#### You have already researched for similar issues?

Yes, I have. Unfortunately, I'm the first. BTW, in this issue template y'all have some typos ("similiar" and "neccessary").

#### What are you trying to achieve or the steps to reproduce?

I would like to use Mithril with Fastify. I have need for an SPA framework and I am a newfound fan of Mithril but I have no idea how to get started.

**Comment by delvedor** [comment]
cc @ACXgit

**Comment by NetOperatorWibby** [comment]
^ I found his slides but unfortunately, there wasn't a live repo attached.

**Comment by ACXgit** [comment]
Hi, what are you trying to accomplish? In the case of a typical API (Fastify) + SPA (Mithril) setup, you only need to make the AJAX requests from the SPA to the API endpoints with [m.request](https://mithril.js.org/request.html). If instead you are looking for server side render, take a look at [mithril-node-render](https://github.com/MithrilJS/mithril-node-render).

**Comment by NetOperatorWibby** [comment]
I want to convert my Fastify app that currently does server-side rendering to an SPA with Mithril. It seems like I'd need to keep Fastify around for interfacing with APIs in my microservices elsewhere. So, the app _itself_ doesn't have any endpoints...should it?

If I'm using `mithril-node-render` for SSR, would I still need to use Fastify? I found a sample Express project using that module but I don't want to use Express. The problem though, is that Fastify isn't a drop-in replacement for Express and that's where my experimenting failed (routing).

_It's 2am where I am so I'll be back in ~6 hours_

**Comment by ACXgit** [comment]
If you just want a SPA which will interface directly with microservices, you'll just need a static HTML file with the SPA JS included in. If SEO is important to you, then an _isomorphic_ approach would be best, and in that case you'll need Fastify and `mithril-node-render`.

**Comment by NetOperatorWibby** [comment]
How would I use those together?

**Comment by ACXgit** [comment]
If you refer to this: https://isomorphic-mithril.mvlabs.it/en/
The documentation is outdated, look at [the code](https://github.com/mvlabs/isomorphic-mithril) to understand how it works with Express. It's quite easy to replace Express with Fastify, I already did it in all the projects where I used it 😄

**Comment by NetOperatorWibby** [comment]
The routing is what concerns me b/c it's not exactly the same. I'll try it again though.

**Comment by NetOperatorWibby** [comment]
From the docs:

> Express modifies the prototype of the node core Request and Response objects heavily so Fastify cannot guarantee full middleware compatibility. **Express specific functionality such as res.sendFile(), res.send() or express.Router() instances will not work with Fastify.**

The MVLabs repo uses `express.Router()` in addition to `app.use('/', router);`. Seems like I'd have to write my own plugin in order to get that project to play nice.

**Comment by NetOperatorWibby** [comment]
[Figured it out](https://git.inc.sh/NetOperatorWibby/mithril-starter)
