### ISSUE TITLE
How to wrap the entire request in a domain / async_context?

### ISSUE THREAD

**Issue by gajus** [fastify/help#561]
Roarr has a log method called [`adopt`](https://github.com/gajus/roarr#roarr-api-adopt) that uses `AsyncLocalStorage` to provide context to all descendant loggers, e.g.

```ts
import {Logger} from 'roarr';

Logger.adopt(() => {
  setTimeout(() => {
    Logger.info('foo');
  });
}, {foo: 'bar'});
```

Thanks to `AsyncLocalStorage`, even though we did not pass context to `foo` log method, this example would log:

```json
{"context":{"foo":"bar"},"message":"foo"}
```

My question is:

Is it possible to wrap the entire fastify request in a way that would persist `AsyncLocalStorage` context across the request?

**Comment by gajus** [comment]
Turns out it was as simple as:

```ts
app.addHook('preHandler', (request, reply, done) => {
  request.log.adopt(
    () => {
      done();
    },
    {
      reqId: request.id,
    }
  );
});
```

**Comment by jsumners** [comment]
https://github.com/fastify/fastify-request-context

Also, Fastify adds a request id by default: https://www.fastify.io/docs/latest/Server/#genreqid

And can be completely customized as shown in https://www.fastify.io/docs/latest/Server/#disablerequestlogging
