### ISSUE TITLE
Fastify JSON parsing for POST request to MongoDB? 

### ISSUE THREAD

**Issue by vymao** [fastify/help#563]
I'd like to add a post route in NodeJS using Fastify in order to send JSON files as documents to a MongoDB. So far, my route looks like this: 

```
    fastify.post('/newFile', function (req, reply) {
    // Or this.mongo.client.db('mydb').collection('users')
        const movies = this.mongo.db.collection('Movies')
        
        // if the id is an ObjectId format, you need to create a new ObjectId
        movies.insertOne(req.body, (err, user) => {
            if (err) {
            reply.send(err)
            return
            }
            reply.send(user)
        })
    })
```

However, sending POST requests to the server leads to this error: 
```
{"statusCode":500,"code":"14","error":"Internal Server Error","message":"BSON field 'insert.documents.0' is the wrong type 'array', expected type 'object'"}
```

I thought it might be due to a JSON parsing error so I added this: 
```
fastify.addContentTypeParser('application/json', { parseAs: 'string' }, function (req, body, done) {
    try {
      var json = JSON.parse(body)
      done(null, json)
    } catch (err) {
      err.statusCode = 400
      done(err, undefined)
    }
  })
```
but that didn't change anything. Was hoping for some guidance?

**Comment by climba03003** [comment]
Your code is perfectly fine. I just need to payload to see what's wrong with it.

`addContentTypeParser` is not needed for `application/json`

**Comment by vymao** [comment]
What do you mean by "need to payload"? Do you need the JSON input?

**Comment by climba03003** [comment]
> What do you mean by "need to payload"? Do you need the JSON input?

Yes

**Comment by simoneb** [comment]
@vymao did you solve your issue?

**Comment by george-martin** [comment]
@simoneb if you are sending a simple JSON payload, be sure to include Content-type within headers.
