### ISSUE TITLE
fastify-multipart Can't return JSON to client

### ISSUE THREAD

**Issue by JacobKorn** [fastify/help#565]
Hi I'm not sure if there is something I'm missing (this is my first time doing file uploads) so forgive me if that is the case.

My use case is receiving a file, making another request with it and then doing something with the results.

This all works fine, but when I go to send the results to the client I can't send JSON, only text. eg both `reply.send({ some: 'JSON })` and `return { some: 'JSON' }` result in the chrome network tab saying "Failed to load response data: No data found for resource with given identifier". If I do `reply.send('done... not json :(')` I can see it there fine.

Below is an example of the endpoint.

```js
fastify.route({
  method: 'POST',
  url: 'files/:id/upload',
  handler: async function (request, reply) {
    const ACCEPTED_FILE_TYPES = ['application/pdf', 'image/jpeg', 'image/png']

    const { externalAPI, internalSystems } = this
    const { id } = request.params

    const data = await request.file({ limits: { fileSize: 1_000_000 } })

    if (!ACCEPTED_FILE_TYPES.includes(data.mimetype)) {
      throw this.httpErrors.badRequest('file must be a pdf, jpg, jpeg or png.')
    }

    try {
      const buf = await data.toBuffer()
      const externalResponse = await externalAPI.sendFile(data.mimetype, buf)
      console.log(externalResponse.body) // prints the data I expect to be there.
    } catch (error) {
      this.log.error(error)
      throw this.multipartErrors.FilesLimitError()
    }

    const obj = await internalSystems.doSomething(id, externalResponse.body)

    reply.send({
      foo: 'bar',
      obj
    })
  }
})
````

I've also tried setting the content-type to application/json with `reply.header('Content-Type', 'application/json`)` but that didn't work.

## Your Environment

- *node version*: v14.17.5
- *fastify version*: 3.24.0
- *fastify-multipart version*: 5.1.0
- *os*: Linux, Pop!_OS 21.04 x86_64

**Comment by Eomm** [comment]
Do you have any `onSend` hooks or `reply-serializer` set?

**Comment by JacobKorn** [comment]
No, I haven't used those before.

**Comment by JacobKorn** [comment]
I initialized the project with fastify-cli if that makes any difference.

**Comment by JacobKorn** [comment]
As a last ditch effort I switched the library making the request from ky to axios and somehow this caused it to work as expected. I have no idea why though :shrug: 

At least it seems to not be a problem with fastify or fastify-multipart.
