### ISSUE TITLE
About Serializer Compiler in doc page ?

### ISSUE THREAD

**Issue by wesley-jun** [fastify/help#566]
I saw this written in the Validation-and-Serialization document:
> The serializerCompiler is a function that returns a function that must return a string from an input object. You must provide a function to serialize every route where you have defined a response JSON Schema.

```javascript
fastify.setSerializerCompiler(({ schema, method, url, httpStatus }) => {
  return data => JSON.stringify(data)
})

fastify.get('/user', {
  handler (req, reply) {
    reply.send({ id: 1, name: 'Foo', image: 'BIG IMAGE' })
  },
  schema: {
    response: {
      '2xx': {
        id: { type: 'number' },
        name: { type: 'string' }
      }
    }
  }
})
```

I'm a little confused？
fast-json-stringify isn’t it the default serializer?
Do I need to write this function again ？
Was hoping for some guidance..

```javascript
fastify.setSerializerCompiler(() => {})
```

**Comment by climba03003** [comment]
`setSerializerCompiler` only needed to call when you want a custom behavior for serialization.
