### ISSUE TITLE
It is possible to serialize a symbol property using the default error handler?

### ISSUE THREAD

**Issue by michael-melodyarc** [fastify/help#567]
## 💬  Question here 

The docs list the following example of tweaking what properties get serialized when sending an error back as a response:

```js
fastify.get('/', {
  schema: {
    response: {
      501: {
        type: 'object',
        properties: {
          statusCode: { type: 'number' },
          code: { type: 'string' },
          error: { type: 'string' },
          message: { type: 'string' },
          time: { type: 'string' }
        }
      }
    }
  }
}, function (request, reply) {
  const error = new Error('This endpoint has not been implemented')
  error.time = 'it will be implemented in two weeks'
  reply.code(501).send(error)
})
```

I have an error that might have a symbol property, which I want to include in the response, but otherwise ignore (i.e. I don't want it logged).  Symbols generally aren't enumerable through normal means, and things like `JSON.stringify()` will drop them, but in this one very specific case, I'm curious if there is a way to explicitly tell the serializer to include the property?

The obvious solution would be to simply construct the response myself doing something like the following, but it's a bit verbose to essentially duplicate the default error handler.  Is there a better way to achieve this?

```js
}, function (request, reply) {
  // get err somehow
  request.log.error(err);
  reply.code(500).send({
    message: err.message,
    statusCode: err.statusCode,
    myCoolProp: err[Symbol.for('my-cool-prop')],
  });
```

I realize this isn't directly related to Fastify per se, more so `ajv`, `fast-json-stringify`, or just JSON schemas in general, but I figured this was still the most sensible place to ask.  Thanks.

**Comment by michael-melodyarc** [comment]
I suppose another option would be to create a normal non-enuerable property on the error, in which case the response schema would work as expected, while still preventing `pino` from logging it.  Something like:

```js
Object.defineProperty(err, 'myCoolProperty', { value: 'cool value' });
```

**Comment by mcollina** [comment]
> I suppose another option would be to create a normal non-enuerable property on the error, in which case the response schema would work as expected, while still preventing `pino` from logging it.  Something like:
> 
> 
> 
> ```js
> 
> Object.defineProperty(err, 'myCoolProperty', { value: 'cool value' });
> 
> ```

This would be my favorite approach.

**Comment by michael-melodyarc** [comment]
Sounds good, appreciate the reply.
