### ISSUE TITLE
How to edit/manipulate fastify instance via plugin

### ISSUE THREAD

**Issue by raviSussol** [fastify/help#568]
## 💬  Question here 

I'm trying to load ssl certificates via plugin as normal other fastify plugin does other various jobs in fastify app. But in order to do I'll need to ssl certificates only during at the time of initializing fastify instance right before listening to it. So how can I achieve loading of the ssl certificates registering as a plugin?

I tried with some example code below to load ssl files but it doesn't seem to work

```ts
async function installSsl(
  fastify: FastifyInstance<Http2SecureServer, Http2ServerRequest, Http2ServerResponse>,
  options: SslOpts
) {
  const { certsDir, filenames = [] } = options;
  let sslFileNames = filenames;
  if (filenames.length === 0) {
    sslFileNames = getCertFiles(certsDir);
  }
  const readCertFile = (filename: SslFileType) => fsReadFile(resolve(certsDir, filename));
  const [key, cert] = await Promise.all(sslFileNames.map((file) => readCertFile(file)));
  fastify = f({ http2: true, https: { key, cert } });
  fastify.decorate('sslPlugin', fastify);
}
````

## Your Environment

- *node version*: 16
- *fastify version*: >=3.23.1
- *os*: Mac

**Comment by mcollina** [comment]
Unfortunately this use case is not possible. You'll need to provide the SSL certificates when creating fastify.
