### ISSUE TITLE
Any idea why my onRequest hook does not execute?

### ISSUE THREAD

**Issue by danechitoaie** [fastify/help#569]
I have the following app:

app.ts
```
import homeRoute from "./routes/home";
import apiRoute from "./routes/api";

...
    await app.register(homeRoute);
    await app.register(apiRoute, {
        prefix: "/api/",
    });
...
```

./routes/api/index.ts
```
import { FastifyInstance, FastifyPluginOptions } from "fastify";
import authenticationHook from "./hooks/authentication";
import completionRoute from "./routes/completion";

export default async (fastify: FastifyInstance, options: APIRouteOptions) => {
    await fastify.register(authenticationHook);
    await fastify.register(completionRoute);
};
```

./hooks/authentication.ts
```
export default async (fastify: FastifyInstance, _options: FastifyPluginOptions): Promise<void> => {
    fastify.addHook("onRequest", async (request: FastifyRequest, reply: FastifyReply) => {
        console.log("HERE!");
    });
};
```

./routes/completion
```
export default async (fastify: FastifyInstance, options: CompletionRouteOptions) => {
   fastify.post("/completion", { schema }, async (request: CompletionRequest, reply: FastifyReply) => {
    ...
   });
};
```

The problem is that the onRequest hook never executes. I would expect it to execute for any URL that starts with `/api/` yet it never executes, not even for `/api/completion`
Any idea how I can achieve this?

**Comment by Asjas** [comment]
The `onRequest` hook will only be scoped to the plugin itself, if you want it register the hook to run on any request that happens on the server then you have to wrap and export it with `fastify-plugin` 🙂 

https://github.com/fastify/fastify-plugin

**Comment by danechitoaie** [comment]
I want it to execute only for routes starting with `/api/` prefix. Non API routes should not require auth, so for them the hook should not execute.

**Comment by danechitoaie** [comment]
If I wrap it in fastify-plugin and register it in `./routes/api/index.ts` will it execute for upper routes as well (so for ALL) or just for lower routes? As in those under `/api/`;
