### ISSUE TITLE
Error after updating types/node to latest

### ISSUE THREAD

**Issue by smartiniOnGitHub** [fastify/help#57]
Hi all,
in another round for updating all dependencies (for Fastify v2), after updating types/node to latest
```
"@types/node": "^11.9.3"
```

when running tests now I see this error (catched by the new version):

```
test/types/index.ts:421:44 - error TS2531: Object is possibly 'null'.

421     server.log.info(`server listening on ${address.port}`)
```

sorry but I'm a TypeScript newbie ... what is the preferred way to fix this ?
Add a check if nut null or change the nullability (but not sure where) ?

After this I'll raise a PR with related changes.
Note that I updated all other packages and all is good (there is a vulnerability but a dependency of Tap, used only in dev dependencies, so not a big deal and probably fixed soon by them).

Thanks for the help,
Sandro

**Comment by smartiniOnGitHub** [comment]
As a quick fix, adding a check for not null seems to be enough ... but is it the right way there ?

**Comment by Ethan-Arrowood** [comment]
I'll take a look at this shortly

**Comment by smartiniOnGitHub** [comment]
@Ethan-Arrowood yes I see that error after updating "@types/node" to latest; I just add an additional check for address not null, but not sure if it's the right way to fix it (maybe there is a way to define that attribute in TypeScript types definition) but can't say ... tell me so i can do some change if needed. Thanks for now. Bye

**Comment by smartiniOnGitHub** [comment]
Related PR has already been discussed with fastify guys, and accepted. Thanks.
