### ISSUE TITLE
Decorator with reference object / order of same type hooks

### ISSUE THREAD

**Issue by adriano-tirloni** [fastify/help#570]
## 💬  How to add a default object to request object. 

I have a default empty object added to every request, this object is read and have new properties added to it as the request flows through the routes.

I was doing it via `decorator` in a `plugin` and registering it on app initialization:
```js
const fp = require('fastify-plugin')

module.exports = fp(async (fastify,  opts ) => {
  fastify.decorateRequest('housing', {})
})
````
But recently got a **warning** and this is the suggestion in docs:
![image](https://user-images.githubusercontent.com/6390605/144247496-ba3fd1d9-a572-49d1-a5cb-0e319f0b83b4.png)

**This raised a question:**
This object is used as a dependency on several other plugins registered after this first one, with code like this:

```js
module.exports = fp(async (fastify, opts) => {

  fastify.addHook('onRequest', async (req, rep) => {
    req.housing.type = await defineType({ token: req.headers.authorization })
    return req.housing.type || rep.unauthorized()
  })

})
```
Will the ```onRequest``` hook call maintain order of declaration/registration? 
Or is it possible that latter plugins execute before the first one?

If there is a better way of achieving this I'm listening.
Thanks!

**Comment by jsumners** [comment]
Use https://www.fastify.io/docs/latest/Decorators/#getters-and-setters

**Comment by adriano-tirloni** [comment]
> Use https://www.fastify.io/docs/latest/Decorators/#getters-and-setters

I thought it would raise the same reference type warning aswell.

**Comment by jsumners** [comment]
> > Use [fastify.io/docs/latest/Decorators/#getters-and-setters](https://www.fastify.io/docs/latest/Decorators/#getters-and-setters)
> 
> I thought it would raise the same reference type warning aswell.

No, it will not. The getter allows you to return a new object on every request, and thus avoid the problem the warning is telling you about.
