### ISSUE TITLE
Issue with AsyncLocalStorage usage in route-specific preHandler

### ISSUE THREAD

**Issue by peterdee** [fastify/help#571]
Hi. I have a problem with ALS and route-specific `preHandler`.

My use-case is the following:

- I have an `onRequest` hook that creates initial store state (`hook.js`);
- I have to access the store in my preHandler to save some additional data in the store (`pre-handler.js`);
- at some point my store does not reflect the changes that I've made to the store state in the preHandler.

Here's the code:

**server.js**
```javascript
const fastify = require('fastify');

const hook = require('./hook');
const router = require('./router');

const app = fastify({
  logger: true,
});

app.addHook('onRequest', hook);

app.register(router);

app.listen(6111);
```

**hook.js**
```javascript
const store = require('./store');

module.exports = async () => {
  store.enterWith({
    stamp: Date.now(),
  });
};
```

**router.js**
```javascript
const handler = require('./handler');
const preHandler = require('./pre-handler');

module.exports = async (instance) => {
  instance.get(
    '/',
    {
      preHandler: [preHandler]
    },
    handler,
  );
};
```

**store.js**
```javascript
const { AsyncLocalStorage } = require('async_hooks');

const store = new AsyncLocalStorage();

module.exports = store;
```

**pre-handler.js**
```javascript
const store = require('./store');

module.exports = async (_, reply) => {
  const delay = Math.random();

  await new Promise((resolve) => setTimeout(resolve, delay));

  const oldStore = store.getStore();
  store.enterWith({
    ...oldStore,
    customValue: delay,
  });
  return;
};
```

**handler.js**
```javascript
const store = require('./store');

module.exports = async (_, reply) => {
  return reply.code(200).send(store.getStore());
};
```

This code will not work, i. e. calling `store.enterWith()` in the `pre-handler.js` will result in accessing the old store state in the `handler.js`. The `customValue` field will not be added. Here's the JSON response with the store contents:

```json
// 20211207160205
// http://localhost:6111/

{
  "stamp": 1638882124844
}
```

However, commenting the following line in the `pre-handler.js`
```javascript
  await new Promise((resolve) => setTimeout(resolve, delay));
```
fixes the issue:

```json
// 20211207160413
// http://localhost:6111/

{
  "stamp": 1638882253254,
  "customValue": 0.9116639948003116
}
```

The `preHandler` function is asynchronous in both cases, but somehow calling the `await` affects the store / execution context.

I've tried to run `preHandler` as a synchronous function calling `done()` at the end and in that case it works fine, but I cannot use async / await. 

Combining the `async` with `done` results in a situation when handler function is called twice, this behaviour is described well in the Fastify documentation. 

Disabling the store and then calling `enterWith()` after that in `preHandler` does nothing if any `await` calls are made in the function, I will still get the old store state in the handler function.

Here's the repository link: https://github.com/peterdee/fastify-als

I am not sure if this is an issue or am I missing something about Fastify / preHandlers / ALS.

**Environment:**
- Node 16.2.0
- Fastify 3.24.1
- Mac OS Monterey

**Comment by kibertoad** [comment]
Have you tried using fastify-request-context? There are certain aspects of fastify that needed to be taken into consideration when integrating als into fastify. If that plugin is not an option for you, at least check how it does it.

**Comment by peterdee** [comment]
@kibertoad Hi. Thank you for the reply. I've just tried `fastify-request-context`, it allows me to change the store in the route-specific `preHandler` function, so basically it solves the issue that I have. 

I think that `fastify-request-context` module description should have a mention of the possibility to access / modify the store in the `preHandler` functions.

I will check how it works internally, hopefully I will be able to figure out what went wrong with my code.

Still, I find it pretty strange that calling `await` in an asynchronous function affects ALS making its usage unpredictable.

**Comment by kibertoad** [comment]
I think you are just losing particular context between lifecycles. Plugin explicitly preserves and reattaches it.

**Comment by peterdee** [comment]
@kibertoad Yes, I guess this is the case, somehow context is getting lost.

I'm closing the issue.
