### ISSUE TITLE
How to destroy stream with fastify-multipart

### ISSUE THREAD

**Issue by cyberwombat** [fastify/help#572]
I have this code on Heroku and while I can successfully consume a stream I do need to be able to reject the call for certain reasons. However not consuming stream causes Heroku to choke with an H18 error with a socket disconnected error. 

Here's the code:
```
const fastify = require("fastify")({
  logger: {
    level: "info"
  }
})

fastify.register(require("fastify-multipart"), {
  limits: {
    fieldNameSize: 100, // Max field name size in bytes
    //  fieldSize: 100, // Max field value size in bytes
    fields: 10, // Max number of non-file fields
    // fileSize: 1000000, // For multipart forms, the max file size in bytes
    files: 1, // Max number of file fields
    headerPairs: 2000 // Max number of .header key=>value pairs
  }
})

fastify.register(require("fastify-cors"), {
  origin: true,
  optionsSuccessStatus: 200
})

fastify.route({
  method: "POST",
  url: "/",
  schema: {
    response: {
      200: {
        type: "object",
        properties: {
          hello: { type: "string" }
        }
      }
    }
  },
  handler: async (req, reply) => {
    const data = await req.file()

    data.file.destroy()
   
    return reply.code(400).send({
      error: "BOOM"
    })
  }
})

fastify.listen(process.env.PORT || 3001, "0.0.0.0", (err) => {
  if (err) {
    fastify.log.fatal(err)
    process.exit(1)
  }
})
```
As you can see I am attempting to destroy the stream before replying but this has no effect. Am I missing something?

Here are the Heroku logs:
```
2021-12-08T15:40:20.898870+00:00 app[web.1]: {"level":30,"time":1638978020898,"pid":32,"hostname":"8b0f9dab-6a81-4700-820c-e94a88d61115","reqId":"req-3","req":{"method":"POST","url":"/","hostname":"foo.herokuapp.com","remoteAddress":"10.1.46.153","remotePort":34940},"msg":"incoming request"}
2021-12-08T15:40:22.148737+00:00 app[web.1]: {"level":30,"time":1638978022148,"pid":32,"hostname":"8b0f9dab-6a81-4700-820c-e94a88d61115","reqId":"req-3","res":{"statusCode":400},"responseTime":1249.7131190001965,"msg":"request completed"}
2021-12-08T15:40:22.557216+00:00 heroku[router]: sock=backend at=error code=H18 desc="Server Request Interrupted" method=POST path="/" host=foo.herokuapp.com request_id=7315494d-f144-4cc0-bae9-bb14f22aec13 fwd="174.205.176.140" dyno=web.1 connect=0ms service=1659ms status=503 bytes=244 protocol=https
```
A suspicion I have is that I need to wait for the actually `close` event but my attempts have not worked so far.

**Comment by mcollina** [comment]
.destroy() is likely destroying the underlining socket. Why do you need to destroy it?

**Comment by cyberwombat** [comment]
I am running some validation on other  standard fields prior to processing the stream. So I want to reject w a 400 but just returning something like ` return reply.code(400).header("Connection", "close").send("some error")` causes Heroku to choke with that error.

**Comment by cyberwombat** [comment]
@mcollina and I initially tried returning 400 from the reply without destroying w same error. Not sure how to get out of the process.

**Comment by cyberwombat** [comment]
Ok this is bad. If I consume the entire stream in a buffer first it works but clearly that wont go far. There appears to also be no way to handle too big uploads since that means destroying which doesn't work.

@mcollina  I would love if you could chime in on this especially as Heroku says this is an unfixed old Node bug: https://stackoverflow.com/a/56584271/856498

**Comment by climba03003** [comment]
> Ok this is bad. If I consume the entire stream in a buffer first it works but clearly that wont go far. There appears to also be no way to handle too big uploads since that means destroying which doesn't work.
> 

If you want to consume the stream but not accumulate it in buffer. Just `stream.resume()` and it will start flowing.
Or pipe to a `Writable` that do nothing.

**Comment by cyberwombat** [comment]
@climba03003 Can you provide an example? None of this works. 
```
await pipeline(stream, createWriteStream("/dev/null"))
return reply.code(400).header("Connection", "close").send("err")
```
```
stream.resume() // or pause(), or destroy()
return reply.code(400).header("Connection", "close").send("err")
```

**Comment by cyberwombat** [comment]
Got it! Thanks @climba03003  to get me on right track.
```
 const closeStream = async (stream) => {
      return new Promise((resolve, reject) => {
        stream.resume()
        stream.on("end", () => {
          resolve()
        })
    })
 }

await closeStream(stream)
return reply.code(400).header("Connection", "close").send("Ooops")
  ```
