### ISSUE TITLE
Fastify instance without an HTTP Server

### ISSUE THREAD

**Issue by paulorodrigues-mb** [fastify/help#573]
Is that ok to start a Fastify instance without listening for http requests?

In my project I have two entry points, one for http requests (`api.js`) and the other to consume amqp messages (`worker.js`), I want both processes to load the same plugins, but doesn´t make any sense to `listen` for http requests on the worker side.

So I started the worker.js without `server.listen` just registering the plugins and starting to consume amqp messages.

Is that ok?

Thanks!

**Comment by jsumners** [comment]
Fastify is an HTTP framework. It is impossible to start it without listening for HTTP requests.

**Comment by paulorodrigues-mb** [comment]
It seems to work well in my tests, when I connect to a MySQL and start to consume from an amqp queue the instance keep alive without need to start listening for http requets.

What I missing?

**Comment by jsumners** [comment]
I really don't understand. A "Fastify instance" _is_ an HTTP server.

**Comment by paulorodrigues-mb** [comment]
But if I don´t need to call `server.listen`?

**Comment by paulorodrigues-mb** [comment]
Take a look at my code, without listening for http but waiting for amqp messages.

```javascript
const Fastify = require('fastify')
const Autoload = require('fastify-autoload')
const closeWithGrace = require('close-with-grace')

const { join } = require('path')
const amqp = require('amqplib')

const server = Fastify({ logger: true })

;(async function () {
  closeWithGrace({ delay: 500 }, async function ({ err }) {
    if (err) {
      server.log.error(err)
    }
  })

  server.register(Autoload, {
    dir: join(__dirname, 'plugins')
  })

  await server.after()
  
  server.register(Autoload, {
    dir: join(__dirname, 'tasks')
  })

  await server.after()
  
  server.register(async function (server, opts) {
    const conn = await amqp.connect(server.config.RABBITMQ_CONNECTION_STRING)
    const channel = await conn.createChannel()
  
    await channel.assertExchange(server.config.PORTAL_EXCHANGE, 'topic')
    await channel.assertQueue(server.config.PORTAL_QUEUE)

    await channel.bindQueue(server.config.PORTAL_QUEUE, server.config.PORTAL_EXCHANGE, '*.*')

    async function onMessage (message) {
      const { fields: { routingKey }, content } = message
      
      let param

      try {
        param = JSON.parse(content)
      } catch (err) {
        param = content.toString()
      }

      const taskFn = server[routingKey]

      if (!taskFn) {
        server.log.error(`Task not found: ${routingKey}`)
        return
      }
      
      try {
        await taskFn(param)
      } catch (err) {
        channel.nack(message)
        server.log.error({ err }, `Unable to process task: ${routingKey}`)
      }
    }

    channel.consume(server.config.PORTAL_QUEUE, onMessage, { noAck: true })

    conn.on('close', function () {
      server.log.error(`Connection lost with ${server.config.RABBITMQ_CONNECTION_STRING}`)
      process.exit(1)
    })

    conn.on('error', function (err) {
      server.log.error(err)
      process.exit(1)
    })
  })

  await server.ready()

  server.log.info('Worker is ready and waiting for messages.')
})()
```

**Comment by jsumners** [comment]
If you don't call `server.listen` then your HTTP server will not listen for HTTP requests. I am at a complete loss for what you hope to accomplish with this. If you don't need to listen for HTTP requests, then you don't need to include an HTTP server framework in your application.

**Comment by paulorodrigues-mb** [comment]
Having 2 entry points means I have two process not competing each other.

**Comment by jsumners** [comment]
> But Fastify is much more than an http server

It is not.

> I very interested in use the plugin system even if I don't need http requests.

Then you want to use https://github.com/fastify/avvio

**Comment by paulorodrigues-mb** [comment]
> > I very interested in use the plugin system even if I don't need http requests.
> 
> Then you want to use https://github.com/fastify/avvio

Hmmm, do you know I can use the same plugins from Fastify directly with Avvio??

**Comment by jsumners** [comment]
> Hmmm, do you know I can use the same plugins from Fastify directly with Avvio??

That would not be possible unless you write into your application an compatible API for the plugins. Fastify plugins are specific to Fastify and the HTTP request lifecycle it provides.

**Comment by paulorodrigues-mb** [comment]
I got you.

The pattern I trying to accomplish is to have two processes sharing the same resources, in the fastify case it means sharing plugins.

I truly don´t need a HTTP server if I have no plans to listening for requests on the worker process, but its likely to use the same resources I have previous set on my another http process.

Maybe if at least avvio plugins and fastify plugins were interoperable, even if specific http hooks like `onRequest` and others doesn´t work, would be great.

**Comment by simoneb** [comment]
@paulorodrigues-mb if this works for you, go for it! @mcollina I think this can be closed
