### ISSUE TITLE
Help: Passing fastify-env config to other plugins

### ISSUE THREAD

**Issue by kobik** [fastify/help#574]
I'd like to understand how to structure the code around environment variables and config. 
When using `fastify-env` to load environment variables, it's being set on `fastify.config`, but how do I init other plugins such as `fastify-redis` using the resulted config object.

```js
fastify.register(require('fastify-env'), options)
fastify.register(require('fastify-redis'), { host: '127.0.0.1' }) // <- i'd like to use the config here
````

I know I can wrap the plugins, but kinda beats the purpose if using these plugins.

## Your Environment

- *node version*: 16
- *fastify version*: >=3.0.0
- *os*: Mac

**Comment by zekth** [comment]
Check this example: https://github.com/fastify/fastify-env/issues/108#issuecomment-891747148

**Comment by kobik** [comment]
Thanks @zekth
