### ISSUE TITLE
[question] In which life cycle of fastify is the verification of the schema, How can decrypt the body first and use schema to check?

### ISSUE THREAD

**Issue by radiorz** [fastify/help#575]
fastify
I make a body decrypt middleware and if i put it in preParsing handler it show not body, but when I put it in preValidation or other place in lifecycle else, the schema check has done. Could I decrypt the body first and enter to the schema checker？Or check only once schema is the best design of fastify?
```js
{
      method: 'POST',
      url: '/api/login', 
      preValidation: app.decryptBody,
      handler: myController.login,
      schema: loginSchema,
      onSend: [app.systemLogs]

}
```

#### Context

* *node version*: 16
* *fastify version*: 3.
* *os*: Windows
* *any other relevant information*:

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by RafaelGSS** [comment]
The `preValidation` is the right place to you decrypt the request before the validation.
