### ISSUE TITLE
Equivalent of bodyParser.json()

### ISSUE THREAD

**Issue by cyberwombat** [fastify/help#576]
I am implementing [uppy](https://uppy.io/) in a Fastify server and trying to clean up my content parsers. 

I have a standard POST route that receives/sends json and then I add the companion middleware for uppy. In order for the latter to work I need to add the express [body-parser](https://github.com/expressjs/body-parser) middleware as such:
```
fastify.use("/s3/(.*)", bodyParser.json())
fastify.use(companion.app(options))
```

This all works. However I feel that I should be able to get rid of `body-parser` and do this using Fastify native stuff.

If I change `fastify.use("/s3/(.*)", bodyParser.json())` to `fastify.use(bodyParser.json())` the uploads still work but it breaks the standard POST routes I have. If I remove the line altogether the uploads break.

What is the Fastify equivalent of `fastify.use(bodyParser.json())`?

**Comment by mcollina** [comment]
There is no need, content type parsing is already part of the framework.

I recommend not to use middlewares.

**Comment by cyberwombat** [comment]
Well if I take out `fastify.use(bodyParser.json())` it simply breaks.

**Comment by cyberwombat** [comment]
Looks like companion from uppy is way to tied to express (it loads it internally). I'll just use Express for this project :(
