### ISSUE TITLE
Is there any way to know that the client has disconnected?

### ISSUE THREAD

**Issue by karthikbalajesp** [fastify/help#577]
According this code, https://github.com/fastify/fastify/blob/8371ba04d6ee8fb320ae1535233b3a999882fe3c/lib/reply.js#L643

`  if (err != null) {
    reply.log.error({
      res: reply,
      err,
      responseTime
    }, 'request errored')
    return
  }`

request errored should have been returned, but in our case we are not seeing this anywhere in our logs even when the connection fails.

Current setup : 
HAProxy (TCP)  -> nginx -> fastify.

with this setup, according to the above code it should when client disconnects it should send "request errored". But we are not getting that.

so is there any way to know whether the client has dropped or not through fastify, we tried "onError" hook it wasn't working as well.

**Comment by Eomm** [comment]
You could check the clientErrorHandler: https://www.fastify.io/docs/latest/Reference/Server/#clienterrorhandler

**Comment by brano543** [comment]
Hello,

we have tried that, but unfortunatelly the event is not being fired. I am using fastify 3.20.1. I have also tried with the latest release with same outcome.

```
const fastify = require('fastify');
function defaultClientErrorHandler(err, socket) {
    if (err.code === 'ECONNRESET') {
        return;
    }

    const body = JSON.stringify({
        error: '400',
        message: 'Client Error',
        statusCode: 400,
    });
    this.log.error({ err }, 'client error');

    if (socket.writable) {
        socket.end(
            `HTTP/1.1 400 Bad Request\r\nContent-Length: ${body.length}\r\nContent-Type: application/json\r\n\r\n${body}`
        );
    }
}
app = fastify({
    clientErrorHandler: defaultClientErrorHandler,
    pluginTimeout: process.env.NODE_ENV === 'production' ? 60000 : 300000,
});
app.server.connectionTimeout = 115000; // request timeout after 115 seconds
app.server.keepAliveTimeout = 60000; // timeout after 60 seconds
```

The only thing which works is
```
app.addHook('onRequest', async (request, reply) => {
    request.raw.on('close', (error) => {
        app.log.info('request closed');
    });
});
```
but close event gets executed also for requests for which reply was successfully delivered.

**Comment by Eomm** [comment]
Could you try?

```
request.socket.on('error', ... )
```

**Comment by simoneb** [comment]
To the best on my understanding, there is no reliable way to tell if a client has disconnected from a plain HTTP request.

**Comment by simoneb** [comment]
You may check out https://www.npmjs.com/package/on-finished

**Comment by metcoder95** [comment]
I also made a plugin for the same purpose, called [`fastify-racing`](https://github.com/metcoder95/fastify-racing). I didn't make it for that purpose but it's something that can be easily added to the library.

In the end, what I did was have a combination of `onResponse` and listening to `socket#on('close')` to make a differentiation between when the client or server served the closed request. Happy to bring more clarity on that

**Comment by eugenio-oddone** [comment]
> 
> The only thing which works is
> 
> ```
> app.addHook('onRequest', async (request, reply) => {
>     request.raw.on('close', (error) => {
>         app.log.info('request closed');
>     });
> });
> ```
> 
> but close event gets executed also for requests for which reply was successfully delivered.

Checking the request after it is closed can help differentiate between the two in this case, although it will still execute on all requests. For instance, `request.raw.aborted` equals `false` for successful replies and for aborted requests it will equal `true`.

```
app.addHook('onRequest', async (request, reply) => {
  request.raw.on('close', () => {
    if (request.raw.aborted) {
      app.log.info('request closed')
    }
  })
})
```

It's worth noting that this only works for things like a browser closing or an intentional abort from the client. This method does not trigger if the user's internet connection is disrupted for instance.

**Comment by simoneb** [comment]
I think this can be closed since https://github.com/fastify/fastify/pull/4518 has been merged
