### ISSUE TITLE
Is there plugin similar to express-useragent?

### ISSUE THREAD

**Issue by guiaramos** [fastify/help#579]
I am just wondering if there is any plugin that does the same of express-useragent middleware?

**Comment by mcollina** [comment]
Nope but it would be a great plugin! Would you like to write it?

**Comment by guiaramos** [comment]
> Nope but it would be a great plugin! Would you like to write it?

Sure!!

**Comment by danechitoaie** [comment]
@guiaramos Looking at https://www.npmjs.com/package/express-useragent the package can be used without Express.js as well.

Basically something like: `const ua = useragent.parse(reuest.headers["user-agent"]);`

So you can setup a onRequest hook that takes the `user-agent` header and passes it to `useragent.parse()` function and then you decorate the Fastify request with it.
