### ISSUE TITLE
Best way to use callbacks with Fastify Hooks

### ISSUE THREAD

**Issue by smartiniOnGitHub** [fastify/help#58]
Hi all, a quick (general) question:
in my plugin [fastify-cloudevents](https://github.com/smartiniOnGitHub/fastify-cloudevents), I'm using all Fastify Hooks to create CloudEvent events and forward to a user-specified callback, but at the moment those callbacks have a single argument (the cloudevent generated).

To be more future-proof and to follow Node.js best practices on callbacks, I wonder if it makes sense to use callbacks that accept usual arguments (error, data), as seen [here](http://justbuildsomething.com/node-js-best-practices/#6), [here](http://fredkschott.com/post/2014/03/understanding-error-first-callbacks-in-node-js/), etc ...

So the real question for Fastify guys:
do you think it make sense to wrap my code (inside all my 'fastify.addHook()' calls) in a try/catch block, and use data or error in related block ?
Last, the call to the next callback, could be done even as last line in the try block (as 'next()') and at the end of the catch block (as 'next(err)') ? 
Do you see problems, lose of performance, etc in that way ?

Thanks a lot.

#### You have already researched for similiar issues?
Yes, but didn't find clear infos/suggestions.

#### What are you trying to achieve or the steps to reproduce?

Tell me if you need more info here.

#### Context

* *node version*: latest 8.x, latest 10.x
* *fastify version*: latest 1.x
* *os*: Mac
* *any other relevant information*: nothing.

**Comment by mcollina** [comment]
Can you make a code example?

**Comment by smartiniOnGitHub** [comment]
Sure, in the [example](https://github.com/smartiniOnGitHub/fastify-cloudevents/blob/master/example/example.js) I set as callback the `function loggingCallback (ce)` which I set into my plugin, for example to attach to the 'onRequest' hook, see line 147 [here](https://github.com/smartiniOnGitHub/fastify-cloudevents/blob/master/src/plugin.js#147), but it's not clear to me to have a more robust flow inside the plugin, if it makes sense to wrap the code inside my `fastify.addHook()` blocks in a try/catch, so be able to use callbacks that instead accept (error, data) as arguments more aligned to best practices.

But in this context, is it useful (inside Fastify/addHook) ? 
There will be some lose of performance or other problems ?
Last, would it be a good practice to call the next callback inside the try/catch block ?
After reading fastify docs and examples still is not so clear to me, sorry.
Thanks a lot for the help.

**Comment by mcollina** [comment]
I still don't understand your question :(. Can you make a tiny app as an example?
It seems you are asking for generic Node.js advice, and Fastify is currently supporting two flavours of structuring your code (callbacks and promises).

**Comment by smartiniOnGitHub** [comment]
Yes sorry it's more a generic question, so maybe the only question for you here is if it makes sense to use sync callbacks for Fastify hooks inside a try/catch block (and the same for calling the `next` callback) ... hope this would be more clear.

Current (consumer) code is in the example linked before; changes that I'm not sure would be inside the plugin, so instead of:
```
    fastify.addHook('onRequest', (req, res, next) => {
      // ...
      const ce = new fastify.CloudEvent( ... )
      // send the event to the callback
      onRequestCallback(ce)

      next()
    })
```
I wonder if something like this would be good/better (pseudo code, not yet tested):
```
    fastify.addHook('onRequest', (req, res, next) => {
      try {
        // ...
        const ce = new fastify.CloudEvent( ... )
        // send the event to the callback
        onRequestCallback(null, ce)
        next()  // is it good here (end of try) ?
      } catch (err) {
        onRequestCallback(err, null)
        next(err)  // is it good here (end of catch) ?
      }
    })
```

Hope this is more clear now, sorry for my not so clear description ...

If needed, then I could raise a PR to clarify Fastify docs for this topic.

**Comment by mcollina** [comment]
In your example, what is ` onRequestCallback`?

**Comment by smartiniOnGitHub** [comment]
it' the (user-provided) callback, configured in the plugin; for example in this case I setup the following function:
```
function loggingCallback (ce) {
  console.log(`loggingCallback - CloudEvent dump ${fastify.CloudEvent.dumpObject(ce, 'ce')}`)
}
```
and configure it like:
```
// register plugin with all its options (as a sample)
fastify.register(require('fastify-cloudevents'), {
  onRequestCallback: loggingCallback
  // other plugin config options ...
})
```

Does it makes sense ?
At the moment I'm always working using sync functions, for async flows I need to do later ...

**Comment by mcollina** [comment]
If `onRequestCallback` is a synchronous function provided by a user, you should wrap that into a try-catch, or just use an async function instead of the callback.

**Comment by smartiniOnGitHub** [comment]
So my proposal looks good ... thanks.
Sorry last question, the call to the `next` callback (for sync flows) is it good the same from inside the try/catch or you see problems/lose of performances/other ?

**Comment by mcollina** [comment]
it should be outside of the try/catch.

**Comment by smartiniOnGitHub** [comment]
ok thank you very much for all the info. Bye
