### ISSUE TITLE
Variable name that includes Fastify()

### ISSUE THREAD

**Issue by Lev-Shapiro** [fastify/help#581]
I can't understand why some humans write app = Fastify() and some write fastify = Fastify()!
In the documentation of Fastify, I can see only fastify = Fastify(), but some tutorials for using fastify ( not from documentation ) write something like app = Fastify(). So the question WHY? and how can I know in which situations I use app and in which fastify?

**Comment by sydnenaal** [comment]
Why people who lives in Saratov sometimes talk they lives in Russia, but sometimes they talk they live in Saratov?

**Comment by climba03003** [comment]
The variable name is on your decision, choose anything you like.
