### ISSUE TITLE
'Invalid body' response on JSON POST request.

### ISSUE THREAD

**Issue by rbeer** [fastify/help#582]
## 💬  Why does a seemingly valid POST body always respond with `400 Invalid body`? 

I'm trying to use schema validation with a simple POST body, but whenever the body is valid, I get a `400 Invalid Body` response.

```js
import fastify from 'fastify';
import fastifyNext from 'fastify-nextjs';

const dev = process.env.NODE_ENV !== 'production';
const port = 3000;

const server = fastify({ logger: { level: 'error' }, pluginTimeout: 300000 });

server.register(fastifyNext, { dev }).after(() => {
  server.next('/*');

  server.next('/api/auth/', {
    method: 'POST',
    schema: {
      body: {
        type: 'object',
        required: ['user', 'signed'],
        properties: {
          user: { type: 'string' },
          signed: { type: 'string' }
        }
      }
    }
  });
});

server.listen(port, (err) => {
  if (err) throw err;
  console.log(`> Listening on http://localhost:${port}`);
});
````
```bash
$ curl -X POST -H 'Content-Type: application/json' -d '{"user": "foo", "signed": "foo"}' http://localhost:3000/api/auth/
Invalid body
```

Omitting one of the two required fields gives me the expected validation error:
```bash
$ curl -X POST \
  -H 'Content-Type: application/json' \
  -d '{"user": "foo"}' \
  http://localhost:3000/api/auth/
{"statusCode":400,"error":"Bad Request","message":"body should have required property 'signed'"}
```

Removing the schema entirely makes the request go through. The error message shown below is from my own validation implementation I'm trying to replace with fastify's.
```js
server.next('/api/auth/', {
    method: 'POST',
    schema: {}
  });
```
```bash
$ curl -X POST http://localhost:3000/api/auth/
{"message":"This request must carry a `user` and `signed` message.","stack":"Error: This r...
```

I've tried all the above requests with my frontend implementation, as well as Postman. Both are working fine with my own validation, but with the same results regarding this issue. 

## Your Environment

- *node version*: 16.13.0
- *fastify version*: 3.25.2
- *fastify-nextjs*: 7.0.0
- *next*: 12.0.7
- *os*: Linux, Debian bookworm/sid

**Comment by rbeer** [comment]
Hmm... seems to be an issue with fastify-nextjs :confused: 

This works as expected:
```js
import fastify from 'fastify';

const dev = process.env.NODE_ENV !== 'production';
const port = 3000;

const server = fastify({ logger: { level: 'error' }, pluginTimeout: 300000 });

server.post(
  '/api/auth/',
  {
    schema: {
      body: {
        type: 'object',
        required: ['user', 'signed'],
        properties: {
          user: { type: 'string' },
          signed: { type: 'string' }
        }
      }
    }
  },
  (req, reply) => {
    reply.send('Ok');
  }
);

server.listen(port, (err) => {
  if (err) throw err;
  console.log(`> Listening on http://localhost:${port}`);
});
```

**Comment by rbeer** [comment]
The error is actually coming from NextJs.
https://github.com/vercel/next.js/blob/e8408c70863b6bcd05437ff92a19194788716722/packages/next/server/api-utils.ts#L158-L164

Logging the error gives the message: "InternalServerError: stream encoding should not be set",  originating from [stream-utils/raw-body/](https://github.com/stream-utils/raw-body). There is an issue about that error message and the fact that encoding is `undefined`, which it is in my case.

Is there a way to set the encoding, using fastify-nextjs?

**Comment by mcollina** [comment]
I don't think you can safely mix&match fastify validations and Next.js API endpoints.
I would recommend you to keep your APIs inside Fastify and just use Next.js for React rendering.

**Comment by rbeer** [comment]
Thanks for the answer! I will stick with my own validations then.
`schema` should better be optional then. TSC complaining is how I ran into this issue, in the first place.

https://github.com/fastify/fastify-nextjs/blob/edab8a2365b40f16f646b25a9b6a91bcef490440/index.d.ts#L26

I vaguely remember that a `@ts-ignore` and omitting the object in the call worked, earlier. So that should really just be the definition. I'll make sure and PR later, if you don't see a problem with that.
