### ISSUE TITLE
fastify-cors not working

### ISSUE THREAD

**Issue by partha-blacknight** [fastify/help#583]
Hello this is my cors config code : 
==========================================
const fastifyCors = require("fastify-cors");
// cors allow //
fastify.register(fastifyCors, {
  "origin": "*",
  "credentials": "true",
  "preflightContinue": true,
  "optionsSuccessStatus": 201,
  "allowedHeaders": "Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range",
  "methods": "GET,POST,OPTIONS,PUT,DELETE,PATCH"
});
fastify.addHook('onSend', (request, reply, payload, next) => {
  reply.header("Access-Control-Allow-Origin", "");
  reply.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept, Access-Control-Allow-Origin, Cache-Control");
  next()
});

but this error are comes when fastify api call from react app:
----------------------------------------------------------------------------------------------------------
Access to XMLHttpRequest at 'http://172.25.109.129:5000/registration' from origin 'http://172.25.109.129:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by Asjas** [comment]
You cannot use `credentials: true` and `origin: '*'` in the same CORS config. If you specify that `credentials` needs to be included then it requires that you specify the `origin` directly, you'll find that the user won't be logged in as cookies won't be sent with the requests unless you fix that.

I'd also suggest removing the `onSend` hook, you don't need to pass any headers as `fastify-cors` already does all of that, this will work as a CORS config 🙂 

```js
const fastifyCors = require("fastify-cors");

fastify.register(fastifyCors, {
  origin: "http://172.25.109.129:3000",
  credentials: "true",
});

```
