### ISSUE TITLE
Encapsulation - addHook vs decorate

### ISSUE THREAD

**Issue by onosendi** [fastify/help#584]
## 💬  Question here 

This is regarding encapsulation. Why am I able to register a hook in that context, but not a decorator? See the comments in the code below.

```js
// This works.
const foo = fp(async (fastify) => {
  fastify.addHook('preHandler', (request, reply, done) => {
    request.foo = 'foo';
    done();
  });
});

const fooRoutes = async (fastify) => {
  fastify.register(foo);

  fastify.route({
    ...
    handler: (request) => {
      console.log(request.foo);
    },
  });
};

// This doesn't work.
const bar = fp(async (fastify) => {
  fastify.decorate(
    'bar',
    (request, reply, done) => {
      request.bar = 'bar';
      done();
    },
  );
});

const barRoutes = async (fastify) => {
  fastify.register(bar);

  fastify.route({
    ...
    preHandler: [fastify.bar], // Error is here - unable to bind
    handler: (request, reply) => {
      console.log(request.bar);
    },
  });
};
````

**Comment by jsumners** [comment]
You can not `.bind` an arrow function. Use a regular function declaration and assignment.

**Comment by onosendi** [comment]
@jsumners 10-4 on that. What's weird though, is I'm using arrows in many other decorators and they work fine. I changed them to reflect your advice, though.

However, that didn't solve the issue. It seems I needed to `await fastify.register(bar)`. Doing this, I feel like I'm doing something I'm not supposed to?

```js
const barRoutes = async (fastify) => {
  fastify.register(bar);
  console.log(fastify.hasDecorator('bar'));
  // > false

  await fastify.register(bar);
  console.log(fastify.hasDecorator('bar'));
  // > true

  // Works
  await fastify.register(bar);

  fastify.route({
    ...
    preHandler: [fastify.bar],
    handler: (request, reply) => {
      console.log(request.bar);
    },
  });
};
```

**Comment by onosendi** [comment]
> You can not `.bind` an arrow function. Use a regular function declaration and assignment.

@jsumners Can you elaborate on this more? I just read through all of the documentation on plugins and decorators again, and this is the only thing I found regarding the arrow function:

https://www.fastify.io/docs/latest/Reference/Decorators/
```js
fastify.decorate('utility', fn, ['greet', 'log'])
// Note: using an arrow function will break the binding of this to the FastifyInstance.
```
But then on the plugins page, they use an arrow function as an example:

```js
module.exports = function (fastify, opts, done) {
  fastify.decorate('utility', () => {})

  fastify.get('/', handler)

  done()
}
```

**Comment by mcollina** [comment]
The hook system uses `bind()` internally as you are passing your arrow function as a preHandler.

**Comment by jsumners** [comment]
> But then on the plugins page, they use an arrow function as an example

This is a change I disagreed with. I will likely revert all such declarations to full function declarations as I update the documentation. In this specific case, it is clearly wrong. A PR to fix this one would be quite welcome.

**Comment by jsumners** [comment]
> However, that didn't solve the issue. It seems I needed to `await fastify.register(bar)`. Doing this, I feel like I'm doing something I'm not supposed to?

I don't know what `bar` is in your example, but it looks like it is a full Fastify plugin. The `.register` API is asynchronous. So if you are registering a plugin that you need _immediate_ access to in a context, then you need to `await` the registration. It is not wrong to do so and is fully supported.

**Comment by onosendi** [comment]
Thanks. You guys are awesome.
