### ISSUE TITLE
Can't make it work with `content-type: application/json`

### ISSUE THREAD

**Issue by meddario** [fastify/help#585]
## 💬  Question here 

a clear , consise and brief decription of your question

I can't make this work when i set the content-type, here a sample app:

package.json
```json
{
  "name": "fastify-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "fastify": "^3.25.3",
    "fastify-cors": "^6.0.2"
  }
}
```

```js
const fastify = require("fastify")({ logger: true });

fastify.register(require("fastify-cors"), { allowedHeaders: ["content-type"] });

fastify.get("/", (req, reply) => {
  reply.send({ hello: "world" });
});

fastify.post("/action", (req, reply) => {
  reply.type("application/json").code(200);
  console.log(req.headers);

  reply.send({ hello: "world" });
});

fastify.listen(3000);
````

* Expose with `ngrok` (you'll get an url similar to https://2f34-93-34-226-107.eu.ngrok.io)
* Go to https://www.test-cors.org/#?client_method=POST&client_credentials=false&client_postdata=%7B%22test%22%3A1%7D&server_url=https%3A%2F%2F2f34-93-34-226-107.eu.ngrok.io%2Faction&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote
* Do a test call, works
* Add `content-type: application/json` header (https://www.test-cors.org/#?client_method=POST&client_credentials=false&client_headers=content-type%3A%20application%2Fjson&client_postdata=%7B%22test%22%3A1%7D&server_url=https%3A%2F%2F2f34-93-34-226-107.eu.ngrok.io%2Faction&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote)
* Do a test call, CORS error: `Access to XMLHttpRequest at 'https://2f34-93-34-226-107.eu.ngrok.io/action' from origin 'https://www.test-cors.org' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Am i doing something wrong? Thanks in advance!

## Your Environment

- *node version*: v17.3.0
- *os*:  Ubuntu 20.04
- see package.json

**Comment by mcollina** [comment]
I think you are missing an `'origin'` option. You likely won't need the allowedHeaders for content-type.

**Comment by meddario** [comment]
Hi Matteo,

the `allowedHeaders` was a leftover from a few tests i did, the result is the same with no options:
```js
fastify.register(require("fastify-cors"));
```
which should use the defaults from https://github.com/fastify/fastify-cors/blob/master/index.js#L6 if I understand correctly.

And is also the same with the `origin` option:

```js
fastify.register(require("fastify-cors"), { origin: "*" });
```
If you want I can upload a repo with my code, but it's the same as the first message. I can't understand if I'm missing something obvious, the code is basically a copy/paste of the example on the `fastify-cors` repo https://github.com/fastify/fastify-cors#usage.

**Comment by meddario** [comment]
Hi,

I think I understood the cause... this was caused by `ngrok` doing something strange with headers... doesn't happen if I deploy on Heroku (and on any other service I think), this can be closed, if I can determine something more specific I'll update the issue.

Thank you for your time!
