### ISSUE TITLE
Performance Hit when using Node 16

### ISSUE THREAD

**Issue by yukha-dw** [fastify/help#586]
Hi, I'm trying to update node version from 14 to 16.

After further testing using vegeta, I am confused with what I found.
1. Using fastify 3.20.2 on Node 14 is the best configuration for my API.
2. Using fastify 3.20.2 on Node 16 shows significant performance hit (5% of actual performance).
3. Using fastify 3.25.3 on Node 16 shows performance hit (increased latency by 30% on average, but mostly due to instability on the beginning of the test).
4. Using fastify 3.25.3 on Node 14 has similar performance as configuration 1, but it is worse.

![perf grapf](https://user-images.githubusercontent.com/91457362/147734955-76520534-e927-47f3-bac9-da9dc19dfd19.png)

Is there any change that I should've aware? Thank you.

#### Context
* *node version*: 14, 16
* *fastify version*: 3.20.2, 3.25.3
* *os*: Ubuntu

**Comment by climba03003** [comment]
Can you provide the minimal repro of the server for us to test?

**Comment by yukha-dw** [comment]
> Can you provide the minimal repro of the server for us to test?

Unfortunately, I can't.

**Comment by mcollina** [comment]
Thanks for reporting, but without some code to test there is not much we can help with. I would recommend creating a few flamegraphs using https://clinicjs.org/ and try to spot differences.

There is probably something specific in your API or some other dependency on your system that is causing this as I have not experienced this myself.

There are _some_ differences in the performance profile between Node v14 and v16 - some things are faster others a bit slower. For most people, it got faster.
