### ISSUE TITLE
fastify-auth beforeHandler reply already sent

### ISSUE THREAD

**Issue by 58bits** [fastify/help#59]
Apologies in advance if I'm missing something obvious. 

I'd like to register/decorate fastify with an auth function using fastify-auth as...

```
.decorate('verifyJWT', function (req, reply, done) {
      req.jwtVerify()
        .then(done())
        .catch((err) => {
          reply.send(err)
        })
    })
```
And then attempt to protect the following route...

```
app.route({
    method: 'GET',
    url: '/protected',
    beforeHandler: app.auth([
      app.verifyJWT
    ]),
    handler: async (req, reply) => {
      req.log.info('Protected route')
      reply.send({ hello: 'protected world' })
    }
  })
```

The auth handler is called, but AFTER the route has already replied with ` reply.send({ hello: 'protected world' })` - and the console logger shows an error as Error: Reply already sent when the auth handler is called.

As an aside, I also tried... 

```
.decorate('verifyJWT', async function (req, reply) {
      try {
        await req.jwtVerify()
      } catch (err) {
        reply.send(err)
      }
    })
```

But when using the async await handler, while an invalid token is caught, and the correct 401 unauthorized error returned, a valid token request stops at `await req.jwtVerify()` and the request never returns at all.

Again - apologies for what is likely a n00b promise/async problem, and suggestions greatly appreciated.

**Comment by 58bits** [comment]
Lastly - a route without fastify-auth handlers works fine...
```
app.route({
    method: 'GET',
    url: '/protected2',
    handler: async (req, reply) => {
      try {
        await req.jwtVerify()
        reply.send({ hello: 'protected world 2' })
      } catch (err) {
        reply.send(err)
      }
    }
  })
```

**Comment by nwoltman** [comment]
The problem is in your decorator:

```js
.decorate('verifyJWT', function (req, reply, done) {
  req.jwtVerify()
    .then(done()) // <- Right here
    .catch((err) => {
      reply.send(err)
    })
})
```

You're calling `done()` instead of passing `done` as a parameter to `.then()`. That line should actually be:

```js
.then(done)
```

**Comment by 58bits** [comment]
Thanks for the reply @nwoltman - but making this change, still doesn't seem quite right, the route how returns the decoded token as the body, instead of `{ hello: 'protected world 2' }`
```
{
    "username": "foo",
    "iat": 1550536268
}
~~

If I remove app.auth from the equation.... then the following configuration works fine....

```.decorate('verifyJWT', async function (req, reply) {
      try {
        await req.jwtVerify()
      } catch (err) {
        reply.send(err)
      }
    })
```
```
app.route({
    method: 'GET',
    url: '/protected',
    beforeHandler: [app.verifyJWT],
    handler: async (req, reply) => {
      req.log.info('Protected route')
      // return { hello: 'protected world' }
      reply.send({ hello: 'protected world' })
    }
  })
```

Although as mentioned early, if using the async await pattern, putting app.auth back onto the rout, and the route never returns.

**Comment by 58bits** [comment]
Okay - solved. I _think_  fastify-auth must have a callback (as in `func(that.request, that.reply, that.onAuth)` and that the callback must be called. So the following works...

```js
decorate('verifyJWT', function (req, reply, done) {
      req.jwtVerify(done)
    })
```

```js
app.route({
    method: 'GET',
    url: '/protected1',
    beforeHandler: app.auth([
      app.verifyJWT
    ]),
    handler: async (req, reply) => {
      reply.send({ hello: 'protected world 1', user: req.user })
    }
  })
```
