### ISSUE TITLE
Can `fastify-http-proxy` be used to proxy MQTT over websockets?

### ISSUE THREAD

**Issue by tukusejssirs** [fastify/help#591]
## 💬  Question here 

Can `fastify-http-proxy` be used to proxy MQTT over websockets?

I’d to create an MQTT broker and a Nest app (using Fastify) and create a route (e.g. `/mqtt`) using which the frontend could communicate with the broker.

I have read fastify/fastify-http-proxy#121 and also the TODO in the `README.md` that websockets are not fully supported (yet).

## Your Environment

- *node version*: any or 16+
- *fastify version*: 3.24.1
- *os*: Linux
- *any other relevant information*

**Comment by mcollina** [comment]
The websocket support might be enough for you, check it out (it should work).

**Comment by tukusejssirs** [comment]
Thanks, @mcollina, for you answer! I’ll definitely check it out.

**Comment by tukusejssirs** [comment]
I tried it, but I could not make it work. [Here](https://github.com/tukusejssirs/nest-test/tree/test-fhp)’s a minimal reproduction.

Here’s how I tested it (all commands are to be run from the repo root):

1. Install the dependencies (`npm i`).

2. Start an MQTT broker over websockets (`node mqttBroker.js`).

3. Start the app (`npm run start`).

4. Start an MQTT client (`node mqttClient.js`).

I expect that `mqttBroker.js` outputs a new `$SYS/{id}/new/clients` topic when `mqttClient.js` is connected (just like when the client created by `nest-mqtt` connects), but it does not happen.

Could you help me out please?

**Comment by mcollina** [comment]
Thanks for reporting. We do not have the resources to support Nest.js users. Please refer to the Nest [Discord](discord.gg/NestJS) channel (support) for such questions.

---

I _think_ you are missing the `websocket` flag. However it's _very hard_ for us to support Nest users atm. 
See https://github.com/fastify/fastify-http-proxy/blob/b4575deef5fe201857a691a165c0b34a113a9c14/test/websocket.js#L30-L33.

**Comment by tukusejssirs** [comment]
Thanks, @mcollina! I suspected I missed something that simple. Adding `websocket` property and using `ws://` protocol in the MQTT broker fixed this issue.

Sorry for asking a question about an issue in an Nest app, but I thought it is more related to `fastify-http-proxy` that Nest. :man_shrugging:
