### ISSUE TITLE
Serialization schema: $ref should be a string

### ISSUE THREAD

**Issue by Lucretius** [fastify/help#6]
Node version: v9.10.1
OS: Mac 10.13.2
Fastify Version: 1.2.0

I am trying to use fastify to serialize the response from a route.  I've constructed a simple example that has the same issue as the code I am currently working on.  I create two schemas, one with a reference to the other, and add them as shared schemas in fastify.  Then, I try to use that schema for a route serialization. 

```js
const fastify = require('fastify')({ logger: true });

fastify.addSchema({
  "$id": "owner",
  "type": "object",
  "properties": {
    "description": { "type": "string" },
  }
});

fastify.addSchema({
  "$id": "pet",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "owner": {
      "$ref": 'owner#'
    }
  }
});

const schema = {
  response: {
    200: 'pet#'
  }
};

fastify.get('/pet', { schema }, async () => {
  return {
    name: "kitty",
    owner: {
      description: "a good person"
    }
  }
});

const start = async () => {
  try {
    await fastify.listen(1235);
    fastify.log.info(`server listening on ${fastify.server.address().port}`)
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
}
start();
```

The error I see is: `msg":"schema is invalid: data.properties['owner'].$ref should be string"`.  This is coming from within AJV.  A little debugging has shown me that, somewhere during the startup process - I believe when trying to register the route - AJV seems to be trying to resolve the referenced schema twice, and the $ref property is an object the second time around (as it has already been resolved).  If I don't add the dependent schema it never registers at all, and complains about a missing schema id.

**Comment by Lucretius** [comment]
Closing this issue - it appears that $ref is not an object as in JSON Schema, but a single line string.  Changing that seemed to fix the issue.

**Comment by delvedor** [comment]
Hi! Thank you for checking out Fastify!
The API to share JSON schema is slightly different fro the spec, we do not use the `$ref` key, but we do compose the schema in memory before passing it to `ajv`.
Everything is documented [here](https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md#adding-a-shared-schema) :)

So your example should be:
```js
fastify.addSchema({
  "$id": "owner",
  "type": "object",
  "properties": {
    "description": { "type": "string" },
  }
})

fastify.addSchema({
  "$id": "pet",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "owner": 'owner#'
  }
})
```
