### ISSUE TITLE
Change request URL on-the-fly

### ISSUE THREAD

**Issue by faustbrian** [fastify/help#60]
I am currently working on an application where the user-facing routes are all the same but their response/implementation can change based on the version the user requests.

Now with `hapi` it is fairly easy to simply reroute the incoming requests by calling `request.setUrl`, for example `request.setUrl(/v${request.headers.version}/posts)`.

```js
// hapi
server.onRequest = request => { request.setUrl('the url the request will really go to') }

// restify
???
```

Is there any way to do this with fastify? Overwriting the request URL or modifying the request object doesn't seem to change where the request will go to.

**Comment by Ethan-Arrowood** [comment]
If I understand this correctly there are two ways you can handle this
1. you'll need to execute a new HTTP request based on the contents of the already received request. And then forward the reply from the second request back to the client.
2. Or you can use a HTTP redirect (https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections) and tell the client to issue a new request to the correct url via proper HTTP spec

**Comment by faustbrian** [comment]
Performing an actual HTTP request to another endpoint on the same API sounds rather hacky and bad for performance and is something I would rather avoid as something like hapi allows me to simply change the endpoint the request will go to inside a middleware.

Will see if there is a non-hacky way to do it with fastify, thanks for the reply.

**Comment by mcollina** [comment]
I think you can use fastify.inject() to implement this.

I’m reopening the issue, because this seems a good feature request.

**Comment by Ethan-Arrowood** [comment]
@faustbrian could you extrapolate the request functionality into a function and then call that function from multiple requests? This would allow you to receive the users request at multiple routes and handle it however you need to.

fastify.inject() could be useful here to mock a HTTP request to another url without actually making a new request. And I agree with @mcollina this sounds like a unique use case and could be a useful feature.

**Comment by Ethan-Arrowood** [comment]
I've gone ahead and created a feature request issue on fastify/fastify 👍
