### ISSUE TITLE
How exactly can I get versioned routes to work?

### ISSUE THREAD

**Issue by pkyeck** [fastify/help#602]
#### You have already researched for similar issues?
I read through the fastify-docs and tried googling my way to a working example but couldn't find one. So here I am.

#### What are you trying to achieve, or the steps to reproduce?

I want to have two (or more) handlers for the same route based on different `Accept-Version` headers.
I found different examples for a single constraint in the docs and thought I could just duplicate it like so:

```js
fastify.put(
  '/api/endpoint',
  {
    preValidation: [checkSomething()],
    constraints: { version: '1.0.0' },
  },
  handlerV1
);

fastify.put(
  '/api/endpoint',
  {
    preValidation: [checkSomething()],
    constraints: { version: '2.0.0' },
  },
  handlerV2
);
```
But I get an error saying:

```
error:  message=Method 'PUT' already declared for route '/api/endpoint', stack=AssertionError [ERR_ASSERTION]: Method 'PUT' already declared for route '/api/endpoint'
```

In the PR that introduced versioned routes I found a different syntax:

```js
fastify.put(
  '/api/endpoint',
  {
    preValidation: [checkSomething()],
    version: '1.0.0',
  },
  handlerV1
);
```

using this I got an error saying:

```
error:  message=Method 'PUT' already declared for route '/api/endpoint', stack=AssertionError [ERR_ASSERTION]: Method 'PUT' already declared for route '/api/endpoint'
...
(node:79581) [FSTDEP008] FastifyDeprecation: You are using route constraints via the route { version: "..." } option, use { constraints: { version: "..." } } option instead.
```

so it looks like the first syntax is the correct one. but why am I getting an error then?

how can I get this to work?

any help would be much appreciated!

#### Context

* *node version*: 14
* *fastify version*: >=3.25.3

**Comment by climba03003** [comment]
```js

**Comment by pkyeck** [comment]
mmm, ok. Then I'll have to try to reproduce it on my end - starting from zero and adding all the stuff that I'm currently using.

thanks so far.

**Comment by pkyeck** [comment]
ok, working now – was a problem with `resolutions` in `package.json` :(

**Comment by stevewwillis** [comment]
I have the same issue and no 'resolutions' in my package.json. What exactly did you change in your package.json to resolve this issue?

**Comment by pkyeck** [comment]
> I have the same issue and no 'resolutions' in my package.json. What exactly did you change in your package.json to resolve this issue?

@stevewwillis can't remember, but it was v3 of fastify and I don't know if they changed anything in the meantime 🤷‍♂️
