### ISSUE TITLE
Can't use @fastify/session with connect-pg-simple

### ISSUE THREAD

**Issue by raviSussol** [fastify/help#604]
#### You have already researched for similar issues?
Not sure. The `@fastify/session` library is a continuation of [fastify-session](https://github.com/SerayaEryn/fastify-session) - using [connect-pg-simple](https://github.com/voxpelli/node-connect-pg-simple) library with [fastify-session](https://github.com/SerayaEryn/fastify-session) to store session in the Postres works fine. So I was expecting this `@fastify/session` should also be working fine with the [connect-pg-simple](https://github.com/voxpelli/node-connect-pg-simple) library. But it is throwing a type error when I assign a store to a session.

#### What are you trying to achieve, or the steps to reproduce?

Use the [connect-pg-simple](https://github.com/voxpelli/node-connect-pg-simple) with `@fastify/session` for a session to store in the Postgres

```js
import session from '@fastify/session';
import ConnectPgSimple from 'connect-pg-simple';
import {
  DATABASE_HOST,
  DATABASE_PORT,
  DATABASE_USER,
  DATABASE_PASSWORD,
  DATABASE,
  NODE_ENV,
  SESSION_MAX_AGE,
  SESSION_SECRET,
} from '../../configs/env';

const conn = new Connection({
  host: DATABASE_HOST,
  user: DATABASE_USER,
  password: DATABASE_PASSWORD,
  database: DATABASE,
  port: Number(DATABASE_PORT),
  max: 20,
  idleTimeoutMillis: 2000,
  connectionTimeoutMillis: 1000,
});
const dbPool = conn.getPool();

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const PgSessionStore = ConnectPgSimple(<any>session);
const store = new PgSessionStore({
  tableName: 'user_session',
  schemaName: 'public',
  pool: dbPool,
});

fastify.register(session, {
    secret: String(SESSION_SECRET),
    store,
    saveUninitialized: false,
    cookie: {
      httpOnly: true,
      secure: NODE_ENV === 'production',
      maxAge: Number(SESSION_MAX_AGE),
    },
  });
```

#### What was the result you received?
<img width="746" alt="Screen Shot 2022-01-16 at 10 27 35 AM" src="https://user-images.githubusercontent.com/13145522/149647621-8fa7487a-475c-4b35-b6a9-0a522b0d2f9a.png">

#### What did you expect?
Session should be working without any errors.

#### Context

* *node version*: 16.13.1
* *fastify version*: 3.23.1
* *os*: Mac
* *any other relevant information*: Postgresql

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by raviSussol** [comment]
Just to add the only reason switching session library from `fastify-session` to `@fastify/session` that it was throwing deprecated warning: `FastifyDeprecation: You are decorating Request/Reply with a reference type. This reference is s
hared amongst all requests. Use onRequest hook instead. Property: sessionStore`. Apart from that, it just works fine.

**Comment by mcollina** [comment]
Does it work in JavaScript?

**Comment by raviSussol** [comment]
@mcollina 
> Does it work in JavaScript?

Yes it does!

**Comment by raviSussol** [comment]
@mcollina It looks like the `Fastify.Session` type is not compatible with the session store of `connect-pg-simple` library. In [fastify-session](https://github.com/SerayaEryn/fastify-session) plugin, the session type has been set to `any` and is working well. But it throws series of issues like decorator warning at runtime. What should I do? Also even if the `@fastify/session` is made to be working it throws:
```
err: {
      "type": "FastifyError",
      "message": "Promise may not be fulfilled with 'undefined' when statusCode is not 204",
      "stack":
          FastifyError: Promise may not be fulfilled with 'undefined' when statusCode is not 204
              at /Users/sussol/Documents/Git/temp/emr-server/node_modules/fastify/lib/wrapThenable.js:30:30
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
      "name": "FastifyError",
      "code": "FST_ERR_PROMISE_NOT_FULFILLED",
      "statusCode": 500
    }
```
while destroying session via `request.destroySession()`

**Comment by mcollina** [comment]
The latter is not an error, it's just a warning, you are missing a `return reply` at the end of your route or similar.

Could you prepare a small example that demonstrate your problems? It's very hard to help you otherwise.

**Comment by raviSussol** [comment]
@mcollina Here's an example [repo](https://github.com/raviSussol/fastify-minimal)

**Comment by mcollina** [comment]
The implementation of the `/api/logout` route is not correct, it should be

```js
fastify.post('/api/logout', (req, rep) => {
if (req.session.userId === undefined) return rep.code(403).send({ message: 'Unauthorized' });
    req.destroySession((err) => {
    if (err) return rep.code(400).send({ message: 'There was a problem logging out' });
    return rep.send({ message: 'Log out successful' });
    });
    }
  );
```

or alternatively

```js
fastify.post('/api/logout', async (req, rep) => {
if (req.session.userId === undefined) return rep.code(403).send({ message: 'Unauthorized' });
    req.destroySession((err) => {
    if (err) return rep.code(400).send({ message: 'There was a problem logging out' });
    return rep.send({ message: 'Log out successful' });
    });
return reply
    }
  );
```

**Comment by raviSussol** [comment]
Thanks @mcollina that worked! But what about the type errors above?

**Comment by mcollina** [comment]
I have no clue, I would leave it to @fastify/typescript

**Comment by darkgl0w** [comment]
Types error are triggered because `@fastify/session` expects that the getter and setter `session` arguments implement this interface :
```ts
   interface Session {
    sessionId: string;
    encryptedSessionId: string;
    /** Updates the `expires` property of the session. */
    touch(): void;
    /** Regenerates the session by generating a new `sessionId`. */
    regenerate(): void;
    /** sets values in the session. */
    set(key: string, value: unknown): void;
    /** gets values from the session. */
    get<T>(key: string): T;
  }
```
while `connect-pg-simple` expose a session argument that implements this interface:

```ts
  interface SessionData {
      cookie: Cookie;
  }

  class Cookie implements CookieOptions {
      /** Returns the original `maxAge` (time-to-live), in milliseconds, of the session cookie. */
      originalMaxAge: number;

      maxAge?: number | undefined;
      signed?: boolean | undefined;
      expires?: Date | undefined;
      httpOnly?: boolean | undefined;
      path?: string | undefined;
      domain?: string | undefined;
      secure?: boolean | 'auto' | undefined;
      sameSite?: boolean | 'lax' | 'strict' | 'none' | undefined;
  }
```

**Comment by raviSussol** [comment]
@darkgl0w Yes that's right. I'd figured out earlier [that](https://github.com/fastify/help/issues/604#issuecomment-1050435061) but I was looking for another way to resolve this type incompatible error without forking the `@fastify/session` library to my own. Like if we can update the `Fastify.Session` to support various database session store types. But thanks for the checking up though. Looks like I may need to fork the `@fastify/session` to my own to make `connect-pg-simple` library friendly.

**Comment by darkgl0w** [comment]
@raviSussol > you can type the `connect-pg-simple` store as any and it will do the trick :d

Or you can send a PR to `@fastify/session` to widen its types compatibility range if you want 😃
