### ISSUE TITLE
[question][TS] register type

### ISSUE THREAD

**Issue by xr0master** [fastify/help#605]
## 💬  Question here 

Hey guys,
I'm a bit confused about the register type. Since it returns a like promise, there is some conflict with the documentation.

```ts
export const app = Fastify();

app.register(fastifyCors, {
  origin: process.env.ORIGIN,
});
````

![image](https://user-images.githubusercontent.com/8962340/149654326-6689ec53-0530-4ec0-b290-8fad459c06cd.png)

In other words, the TS indicates that there is a possibility of the `unhanledPromiseRejection` issue.

So, shall we do something like this?
```ts
export const app = Fastify();

app.register(fastifyCors, {
  origin: process.env.ORIGIN,
}).then(noop, noop);
```

## Your Environment

- *node version*: 16.13.2
- *fastify version*: 3.25.3
- *TypeScript*: 4.5.4

[@fastify/typescript](https://github.com/orgs/fastify/teams/typescript) FYI

P.S> thank you for the helping

**Comment by mcollina** [comment]
There is no need.

**Comment by xr0master** [comment]
@mcollina thank you for your response.
Unfortunately, "there is no need" doesn't fix the problem at the compile time.

**Comment by mcollina** [comment]
Just remove that eslint rule. Your issue is caused by your own tooling configuration.

**Comment by luisorbaiceta** [comment]
The error you are providing above is not a compilation time error but a linting error `@typescript-eslint/no-floating-promises`.

If you want to keep this rule then do as suggested and mark it as ignored. Fastify already provides an error handler so *there is no need* to add what you were suggesting

**Comment by xr0master** [comment]
@mcollina @luisorbaiceta ok, thank you guys, I will add the ignore. I'm glad to know there's no leak here.
