### ISSUE TITLE
Hooks vs. Decorators

### ISSUE THREAD

**Issue by wscherphof** [fastify/help#606]
## 💬  Question here 

I can decorate requests using fastify.decorateRequest.
I can also create an onRequest hook and extend the request object there.

What are the fundamental differences between the two approaches?

## Your Environment

- *node version*: 16
- *fastify version*: 3
- *os*: Linux

**Comment by RafaelGSS** [comment]
- `fastify.decorateRequest` allows you to add a property to the request object
- The `onRequest` is a hook that is triggered in every request (based on the scope)

Those features are completely different.

**Comment by jsumners** [comment]
Does the introduction to decorators clear things up? https://www.fastify.io/docs/latest/Reference/Decorators/

**Comment by wscherphof** [comment]
> Does the introduction to decorators clear things up? https://www.fastify.io/docs/latest/Reference/Decorators/

Ah, yes. Thanks 👍![image](https://user-images.githubusercontent.com/665662/150041413-6e2935b9-4894-4334-b34c-7fd1503387d8.png)
