### ISSUE TITLE
Support a directory of partials

### ISSUE THREAD

**Issue by thesrs02** [fastify/help#608]
#### You have already researched for similar issues?
Yes

#### What are you trying to achieve, or the steps to reproduce?
I'm trying to find a way to set a directory for partials using the fastify Point of View plugin. Currently, it allows me to set path for individual partials. I want to point it to the directory of partials so all partials could be autoloaded just like Express Handlebars.

```
app.register(pointOfView, {
    engine: {
      handlebars,
    },
    includeViewExtension: true,
    layout: "./views/layouts/layout.hbs",
    options: {
      partials: {
        head: "/views/partials/head.hbs",
        header: "/views/partials/header.hbs",
        footer: "/views/partials/footer.hbs",
        variantBlock: "/views/partials/variantBlock.hbs",
      },

      useHtmlMinifier: minifier,
      htmlMinifierOptions: {
        removeComments: true,
        removeCommentsFromCDATA: true,
        collapseWhitespace: true,
        collapseBooleanAttributes: true,
        removeAttributeQuotes: true,
        removeEmptyAttributes: true,
      },
    },
  })
```

#### What was the result you received?
N/A

#### What did you expect?
N/A

#### Context
* *node version*: 16
* *fastify version*: >=^3.26.0
* *POV version*: >=^4.16.0
* *os*: Mac
* *any other relevant information*:

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by thesrs02** [comment]
Guys, any updates?

**Comment by Eomm** [comment]
No, it is not supported

https://github.com/fastify/point-of-view/blob/2b8c3866b8b7c575c649624de4e474fc2eeb8d7e/index.js#L202

Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mcollina** [comment]
I'm sorry but apparently no one knows an answer to this problem, or had time to figure out. You could take a look at the source yourself.

**Comment by thesrs02** [comment]
I'll try to create a PR to allow this. Thanks for your response.

**Comment by Orel-A** [comment]
I've also searched for this, didn't find anything. I made my own:

```
const path = require('path');
const fs = require('fs');
const Handlebars = require('handlebars');
const templatesPath = path.join(__dirname, 'views');

const getPartials = () => {
	const partialsDir = path.join(templatesPath, 'partials');
	const partials = {};
	fs.readdirSync(partialsDir).forEach(fileName => {
		const basename = path.basename(fileName, '.hbs');
		const filePath = path.join(partialsDir, fileName);
		partials[basename] = path.relative(templatesPath, filePath);
	});
	return partials;
};

fastify.register(require('@fastify/view'), {
	engine: { handlebars: Handlebars },
	root: templatesPath,
	propertyName: 'render',
	layout: 'layout',
	options: {
		partials: getPartials()
	}
});
```
I tested this on Windows, you can try on Linux. Should work.
