### ISSUE TITLE
[Help] Regex not matching in Fastify route

### ISSUE THREAD

**Issue by bacloud22** [fastify/help#609]
I decided to port my code from Express to Fastify. the route is declared as:

`fastify.get(/^\/(donations|skills|blogs)/, async function (req, reply) {`

It was working in Express but in Fastify it is returning 404. I'm sure it has to do with regex itself as other routes inside the same plugin/file/ are working properly.

It is supposed to match `/listings/donations` or `listings/skills`... knowing that `/listings` is the prefix when attaching the whole routing plugin to the app.

[Regex working][1]

Thanks a lot

  [1]: https://regex101.com/r/Uxlqr3/1

**Comment by jsumners** [comment]
Have you read the routing documentation?
