### ISSUE TITLE
Stop processing handler after reply

### ISSUE THREAD

**Issue by Extarys** [fastify/help#61]
#### You have already researched for similiar issues?
Yes

I couldn't find the information I was looking for in the documentation.

#### What are you trying to achieve or the steps to reproduce?

Stop javascript from being executed once the reply is sent

I tried returning false and `reply.sent = true`

```js
module.exports = function(fastify, opts, next) {
	const crypto = require('crypto')
	const securePassword = require('secure-password')
	const uuidv4 = require('uuid/v4')

	fastify.post('/register', async (request, reply) => {
		// Check email
		if (!request.body.email) {
			reply.code(422).send({
				error: 'EmptyEmail',
				message: 'Empty \'email\' field.'
			})
			reply.sent = true // I tried that, didn't work
		}
		const email = request.body.email

		// Check password
		if (!request.body.password) {
			reply.code(422).send({
				error: 'EmptyPassword',
				message: 'Empty \'Password\' field.'
			})
                       
		}
		const passwordRaw = request.body.password

               // Multiple fields to verify

                // Execute database query here

	})
    next()
})
```

#### What was the result you received?
The database part is being executed after a response has been send.

#### What did you expect?
A way to strop the javascript following the send command from being executed.

#### Context

* *node version*: 10.15.1
* *fastify version*: 2.0.0
* *os*: Mac, Windows... **Linux**
* *any other relevant information*:

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by Eomm** [comment]
Hi,
to stop the function execution you need simply to add a `return` statement after the `.send` call:

An example:
```js
// Check email
if (!request.body.email) {
  reply.code(422).send({
    error: 'EmptyEmail',
    message: 'Empty \'email\' field.'
  })
  return
}
```

**Comment by Extarys** [comment]
Hey thanks @Eomm quick reply!

I tried that but I'll try again. I remember that it was simple but the errors just keep coming. The issue is probably lying somewhere else.

**Comment by Extarys** [comment]
For future information, I had a callback function buried at the beginning of the code calling some lines that where after the body check. I moved this function below the fields verification and now it's working as it should.
