### ISSUE TITLE
Mapping default values in `fluent-json-schema`

### ISSUE THREAD

**Issue by bacloud22** [fastify/help#610]
I came from Joi validation to `fluent-json-schema`

## 💬  Question here 

I use a lot of validation for checkboxes and choice radio inputs. I would like to know how to assign the two boolean values to arbitrary string values

```js
// So this is possible in Joi but not in `fluent-json-schema`
S.boolean().truthy('on').falsy('off').default(false)
```
Not only for booleans, it would be nice to have the possibility to map values as this is really handy in front and back architectures?.

Thanks a lot !

### Edit
I managed to map values using a preValidation callback.

```
function prevalidation_1(request, reply, done) {
    request.body = Object.fromEntries(
        Object.keys(request.body).map((key) => {
            if(key === 'exact') {
                const isTrue = request.body[key] == 'on' ? true : false
                return [key, isTrue]
            } else {
                return [key, request.body[key]]
            }
        })
    )
    done()
}
```

    // Example secured route
    fastify.route({
        method: 'POST',
        url: '/upload',
        preHandler: fastify.auth([
            fastify.verifyJWT,
        ]),
        preValidation: prevalidation_1,
        handler: (req, reply) => {
            req.log.info('Upload route')
            const { body } = req
            reply.send({ hello: body.exact })
        }
    })

Thanks.

**Comment by simonplend** [comment]
Fastify is using the library Ajv for validation, which supports type coercion. This means you could configure it to coerce the number `1` to the boolean `true`, if you set the value of your radio input to `1`.

This documentation explains how this works, and the Ajv option you need to set: https://ajv.js.org/coercion.html#to-boolean-type-2

You can pass Ajv options when you create your Fastify server instance: https://www.fastify.io/docs/latest/Reference/Server/#ajv

**Comment by bacloud22** [comment]
Excuse my ignorance here, as I see `fluent-json-schema` README, so this is a way to express schemas. Then It can be used with Ajv for [validation](https://github.com/fastify/fluent-json-schema#validation), but then if used with Ajv I don't know how to use it as a validation plugin in routes, (as I only see `ajv.compile(schema.valueOf())#validate(obj)`).

Furthermore, back to my issue, how can I pass options for Ajv but on routes level.
