### ISSUE TITLE
Error: Missing handler function for POST:[object Object] route.

### ISSUE THREAD

**Issue by bacloud22** [fastify/help#615]
## 💬  Question here 

Having this route registration:

```js
fastify.post({
    method: 'POST',
    url: '/gwoogl',
    schema: gwooglSchema,
    preValidation: require('../decorators/preValidation'),
    handler: async (req, reply) => {
        const { body } = req
        let listings = await QInstance.gwoogl(body.title_desc,
            body.exact, body.div_q, body.section)
        const data = { section: body.section, addressPoints: [], listings: listings }
        reply.blabla([data, 'listings', 'gwoogl'])
    }
})
````

- `preValidation` being correct, as I tested it elsewhere.
- also `reply.blabla` hook is valid, as I tested with `reply.view`: same error.
- also handler being async or not is fine (same error).
- finally declaring the route this way works fine (but I cannot send the preValidation hook)

```js
fastify.post('/gwoogl', { schema: gwooglSchema }, async (req, reply) => {});
```

## Your Environment

- *node version*: v16.13.2
- *fastify version*: latest
- *os*: Windows

**Comment by climba03003** [comment]
There is no syntax of `fastify.post(option, [handler])`.
Only `fastify.route(option, [handler])`

**Comment by bacloud22** [comment]
so sorry. you are right.

**Comment by climba03003** [comment]
Note that you should be able to do it like this
```js
fastify.post(
  '/gwoogl', 
  { 
    schema: gwooglSchema,
    preValidation: require('../decorators/preValidation')
  }, 
  async (req, reply) => {}
);
```

**Comment by bacloud22** [comment]
yea definitely much cleaner ! thank you for the follow up 😃
