### ISSUE TITLE
fastify-http-proxy: setting up dynamic upstream and dynamic authentication

### ISSUE THREAD

**Issue by pradip-interra** [fastify/help#616]
#### You have already researched for similar issues?
Yes sir. I searched in the internet and stackoverflow. did not able to figure out the answer. So checking here. In fact you may also check my posted query in stackoveflow [here](https://stackoverflow.com/questions/70895874/fastify-http-proxy-setting-up-dynamic-upstream-and-dynamic-authentication). 

#### What are you trying to achieve, or the steps to reproduce?

I would like to use fastify-http-proxy plugin with fastify-3.x.

However I am facing a few difficulties when trying to use it per my application.

Let me explain my requirement:

In my application, user is going to be presented a set of environments. When user selects a particular environment (say env-1), based on that I need to make a REST API call to another service, passing the env-1 ID to get the IP address of my upstream and the authorization token (Basic auth of username:password) for that upstream.

When user selects another environment (say env-2), I should "re-set" the new upstream and new authorization token based on env-2.

For that I would like to dynamically register the upstream and the auth token. I saw the examples of fastify-http-proxy testcases. However all the examples just adding the replyOptions during the server.register(proxy, ...) step.

I understand somehow I need to override the getUpstream and rewriteRequestHeader. However not able to get an idea how can I defer it to the later stage where based on environment selection, I can write logic by calling different services' APIs to get the upstream endpoint IP address and upstream authorization information.

Along with that, if I want to just log some information (say some telemetry information .. how much time it to proxy the request to upstream server), what is the best way to do it.

```js
const server = Fastify()
    server.register(proxy, {
      upstream: '',
      replyOptions: {
        getUpstream: function (original, base) {
          // Here I want to pass the selected environment ID
          // Based on the environment ID, will make other services' API call to get the upstream 
          return `<...>`
        }
        rewriteRequestHeaders: (originalRequest, headers) => {
           // Here I want to pass the selected environment ID
           // Based on the environment ID, will make other services' API call to get the envAuth
            return {
                ...headers,
                "Authorization": envAuth
            };
        }
      }
    })
```

#### What was the result you received?

I am not able to figure out how to achieve my usecase.

#### What did you expect?

I mentioned above. Let me summarize:

1.  I want to set the upstream and request header programmatically (by calling an API) to fastify-http-proxy, by passing some additional arguments in the getUpstream and rewriteRequestHeader methods (in my base I shall be passing the environment ID)
2.  I want to "re-set" the values of the upstream and request header (when user chooses a different environment)
3.  I want to log the time taken in the proxy.

#### Context

* *node version*: 16.5.0
* *fastify version*: 3.x
* *os*: Mac, Windows: Linux
* *any other relevant information*:

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by Eomm** [comment]
Duplicates 😀

https://stackoverflow.com/questions/70895874/fastify-http-proxy-setting-up-dynamic-upstream-and-dynamic-authentication

It is all doable, but I think there is the need for at least one PR to https://github.com/fastify/fastify-reply-from to set those functions' context binding them within the `Request` object
