### ISSUE TITLE
[Help wanted] Error handler to return the same body 

### ISSUE THREAD

**Issue by bacloud22** [fastify/help#617]
Please bear with me, this is neither a bug nor an issue with Fastify. I'm looking for help for what might be already documented. Also please close if off-topic.

## 💬  Question here 
For development environment I'm using [fastify-error-page](https://github.com/hemerajs/fastify-error-page) which is great to fix bugs.
Otherwise, I want to write an error handler that could **redirect to the same view with the same POSTed body**

For instance:
Having a search POST initiated for `listings/` it returns elements found to the same view.
If there is an error, it would like to return to the same view `listings.ejs` (this time, the URL would be `listings/search` but it's fine.
The reason is obvious, I want the user to have the same entered values not to start all over.

**I know error handler is very low level and I don't want to mess things up, this is why I'm asking if this is fine**
```js
// @@@NOT SURE ABOUT THIS@@@
const urlTemplateMap = { '/search': 'listings', ... }
const errorHandler = (error, request, reply) => {
    const statusCode = error.statusCode || 500
    let response
    const { validation, validationContext } = error
    if (validation) {
        response = {
            message: `A validation error occurred when validating the ${validationContext}...`,
            errors: validation
        }
    } else {
        response = {
            message: 'An error occurred...'
        }
    }
    // if it is a POST parse request body and redirect to same page with same parameters
    if (request.method === 'GET') {
        reply.status(statusCode).send(response)
    } else if (request.method === 'POST') {
        const { body } = request
        body.error = 'An error occurred...'
        // @@@NOT SURE ABOUT THIS@@@
        // Here I'm not sure about a fluent solution to know the corresponding
        // Also not sure if reply.view is fine inside an error handler 
        reply.view(`/templates/${urlTemplateMap[req.url]}`, body)
    }
}
```

Any help is appreciated. Thanks !

**Comment by simoneb** [comment]
can you provide a repro? understanding your use case is not easy otherwise

**Comment by naveen1337** [comment]
How can change my error message as per my business side requirement, like on input schema when an request does't have a email field, fasify automatically throws like 
`json
"msg": "body must have required property 'email'"
`
But I need to change the message be like "msg": "Email is required'"

can I do that  ?

**Comment by bacloud22** [comment]
@naveen1337 
that's Avg not Fastify, I believe. 
also I'm closing this as I don't remember what happened later.
