### ISSUE TITLE
How to secure api endpoints with firebase token

### ISSUE THREAD

**Issue by shekhardesigner** [fastify/help#62]
I need some ideas on how can I protect other routes/endpoints using firebase IDToken/auth.

So far, I have added a decorator to connect firebase in my routes.
```js
'use strict'

const fp = require('fastify-plugin')
const Firebase = require('firebase')

module.exports = fp(async function (fastify, opts, next) {
  Firebase.initializeApp({
    apiKey: process.env.FIREBASE_API_KEY,
    authDomain: process.env.FIREBASE_AUTH_DOMAIN
  })

  const { auth } = Firebase

  fastify.decorate('auth', {
    signIn: (email, password) => auth().signInWithEmailAndPassword(email, password)
  })

  next()
})
```

Now for my login route `/api/login`

```js
const signIn = async (req, reply, fastify) => {
  try {
    const { username, password } = req.body
    const userPromise = fastify.auth.signIn(username, password)

    const data = userPromise.then(data => data, error => {
      return boom.badRequest(error.message)
    })

    return data
  } catch (err) {
    boom.boomify(err)
  }
```

So far, login works perfect, I get the user object from firebase. 
Now, how do I use these resonse to authorize user in other routes. 

For eg.  I want to be able to allow access to following apis only when user is logged in.
```
GET api/logs
GET api/logs/1234
```

* *node version*: 10
* *fastify version*: >=2.x
* *os*: Mac

**Comment by mcollina** [comment]
You would need to use a lifecycle hook to validate that token. I have no experince with firebase. Check out [fastify-jwt](http://npm.im/fastify-jwt) for an example.
