### ISSUE TITLE
Route level timeouts

### ISSUE THREAD

**Issue by dsbudiac** [fastify/help#620]
Is there an equivalent to [connect-timeout](https://www.npmjs.com/package/connect-timeout) for Fastify?

I know there's the server-level option, [`connectionTimeout`](https://www.fastify.io/docs/latest/Reference/Server/#connectiontimeout), but I'd like the vary the timeout length for different routes.

I suppose I can implement something myself, but trying to see if there's a better approach. Here's my idea:

```ts
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms))

fastify.route({
  method: 'GET',
  url: '/my-route',
  onRequest: async (req, res) => {
    const ms = 5 * 1000
    req.timeout = setTimeout(() => res.code(503).send('Server Timeout'), ms)
  },
  handler: async (req, res) => {
    // Do something that takes longer than ms timeout
    await sleep(10 * 1000)
    res.send('My response!')
  },
  onResponse: async (req, res) => {
    if (req.timeout) {
      clearTimeout(req.timeout)
    } 
  }
})
```

This will also throw a `FST_ERR_REP_ALREADY_SENT` error. Not sure if I should handle that or if I can somehow gracefully stop/handle execution on the main handler function if timeout.

**Context**

- Node version: 17.4.0
- Fastify version: 3.27.0
- MacOS

**Comment by Eomm** [comment]
I would try to use the AbortSignal: https://www.nearform.com/blog/using-abortsignal-in-node-js/

If the timeout triggers, the heavy/slow operation is still ongoing and it is consuming your server resources.

**Comment by dsbudiac** [comment]
Yea. I was thinking the same thing. Just seems verbose and hacky. Especially since I'd need to handle `FST_ERR_REP_ALREADY_SENT` on timeouts still if my real handler doesn't implement AbortController.

Here's what I've come up with:

```ts
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms))

fastify.route({
  method: 'GET',
  url: '/my-route',
  onRequest: async (req, res) => {
    req.timeout = new AbortController()
    req.task = new AbortController()
  },
  handler: async (req, res) => {

    const msTimeout = 1000

    // Hijack res.send so that if request times out,
    // FST_ERR_REP_ALREADY_SENT won't be thrown
    const send = res.send
    res.send = function (payload: unknown) {
      if (req.task.signal.aborted) return res
      return send.call(res, payload)
    }

    // Timeout function
    const timeout = async () => {
      try {
        const signal = req.timeout.signal
        await timers.setTimeout(msTimeout, undefined, { signal })
        req.task.abort()
        res.code(503).send('Server Unavailable')
      } catch {}
    } 

    // Actual handler
    const task = async () => {

      // Do something that takes a while to trigger timeout
      await sleep(3000)
      res.send('Request complete!')

      // Tell the timeout signal to abort if success
      if (!req.task.signal.aborted) req.timeout.abort() 

    }

    return await Promise.race([timeout(), task()])
  
  }
})
```

**Comment by dsbudiac** [comment]
I have a more concise approach now. Involves only one `AbortController`... I still need to override res.send to prevent `FST_ERR_REP_ALREADY_SENT`. Definitely still feels a little hacky, but seems better.

```ts
const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms))
const timeout = 5 * 1000 // 5s

fastify.route({
  method: 'GET',
  url: '/my-route',
  onRequest: async (req, res) => {
    req.controller = new AbortController()
    res.raw.setTimeout(timeout, () => {
      req.controller.abort()
      res.send(new Error('Server Timeout'))
      res.send = (payload) => res
    })
  },
  handler: async (req, res) => {
    await sleep(10 * 1000) // Do some long work
    res.send('done!')
  }
})
```

**Comment by Eomm** [comment]
I think you are not using the abort controller in this example.

The scope of the abort controller is to check the signal:

```
fastify.route({
  method: 'GET',
  url: '/',
  onRequest: async (req, res) => {
    req.controller = new AbortController()
    req.signal = req.controller.signal
    res.raw.setTimeout(timeout, () => {
      req.controller.abort()
      res.send(new Error('Server Timeout'))
    })
  },
  handler: async (req, res) => {
    await sleep(10 * 1000)
    if (!req.signal.aborted) {
      return
    }
    await sleep(10 * 1000)
    if (!req.signal.aborted) {
      return
    }
    await sleep(10 * 1000)
    if (!req.signal.aborted) {
      return
    }
    return 'done!'
  },
})
```

I think it is not possible implementing it without the handler being aware of the `signal`

**Comment by dsbudiac** [comment]
Yea, I didn't show an example of _how_ I'd use the abort controller in my example... I should be able to access signal via `req.controller.signal`. I would just pass that to whatever modules I'm using in my handler that support `AbortController` signals.

**Comment by Dhruv-Garg79** [comment]
do we have route level timeouts in fastify now?
