### ISSUE TITLE
Help Testing with TypeScript

### ISSUE THREAD

**Issue by EmirBoyaci** [fastify/help#624]
Hi there,

I've checked Fastify's documentation's [about Testing](https://www.fastify.io/docs/latest/Guides/Testing/) page and couldn't find testing with TypeScript. Is there any place that I can find testing with TypeScript?

Thanks,
Emir

**Comment by Eomm** [comment]
There is not a dedicated section about it, but the logic is the same.
Did you have any issue building a test case with TS?

**Comment by EmirBoyaci** [comment]
> There is not a dedicated section about it, but the logic is the same. Did you have any issue building a test case with TS?

Yes, when I want to use tap for testing I got `SyntaxError: Cannot use import statement outside a module` error. I've searched and found --ts flag for tap and it works. There should be a documentation example for testing Fastify via tap, TypeScript. I was so sad why this doesn't work but it works now.

To reproduce error:
Create Fastify project with TypeScript and it will throw SyntaxError as above.

If you can reproduce error, I can send PR to add how to test Fastify with TypeScript to documentation page.

**Comment by EmirBoyaci** [comment]
> @EmirBoyaci Can you share more of your code and setup? Writing tests with fastify and typescript works perfectly on my end.

I'm ok with that now but I couldn't find earlier "tap --ts" run script so when you didn't set "--ts" flag it throws module error as above. If you can provide a test file as an example, it would be great for me.
