### ISSUE TITLE
[fastify-static] Nested folders with different maxAge, is it possible?

### ISSUE THREAD

**Issue by Lzok** [fastify/help#625]
Hi all, how are you?

I'm trying to configure fastify-static like I used to do in an old express project using "nested" paths but with different max-age time.
Express lines:

```js
app.use(express.static("public", { maxAge: "1h" }));
app.use(express.static("public/build", { immutable: true, maxAge: "1y" }));
````

I am playing with the following configuration of fastify-static but without the desired results
```js
const fastify = require('fastify');
const fastifyStatic = require('fastify-static');

const server = fastify({
  logger: true,
});

server.register(fastifyStatic, {
  root: path.join(__dirname, '..' , 'public', 'build'),
  prefix:'/build/',
  immutable: true,
  maxAge: '1y',
});

server.register(fastifyStatic, {
  root: path.join(__dirname, '..', 'public'),
  immutable: true,
  maxAge: '1h',
  wildcard: false,
  decorateReply: false,
});
```

## What exactly I want to accomplish?
```
./public
├── main.js
├── /build
   ├── other.js
```

I want to be able to set different `maxAge`. For all the files **but** the ones that live inside of /public/build I want for example `maxAge: '1h'` and all the files inside /public/build I want a longer maxAge, like '1y'.

Here I would expect to have 1 year of cache instead of 1 hour.
![image](https://user-images.githubusercontent.com/45211582/153272422-612c5713-2364-44bf-a8e2-50e66b58e77d.png)

Is there a way to do this?

Thanks!

## Your Environment

- *node version*: 16.13.0
- *fastify version*: 3.27.1
- *os*: Linux (Debian 11)
- *Browser*: Chrome/Chromium updated today.

**Comment by mcollina** [comment]
I don't think this is possible or easily achievable, you'd need to not have a "global" fastify-static and have one for each subdirectories.

**Comment by Lzok** [comment]
Hi! First of all, I was wrong. With the two separate lines, express behaves like the case I posted here. The solution in both cases is use the `setHeaders` options to check there if the asset requested is one inside /build/ to give it a stronger cache.

```js
const fastifyStatic = require('fastify-static');

const PUBLIC_DIR = path.join(__dirname, '..' , 'public');

const server = fastify({
  logger: true,
});

server.register(fastifyStatic, {
  root: PUBLIC_DIR,
  wildcard: false,
  setHeaders: (res, pathName) => {
    const relativePath = pathName.replace(PUBLIC_DIR, "");
    if (relativePath.startsWith("/build/")) {
      res.setHeader("Cache-Control", "public, max-age=31536000, immutable");
    } else {
      res.setHeader("Cache-Control", "public, max-age=3600");
    }
  },
});
```

![image](https://user-images.githubusercontent.com/45211582/153394347-f091b51b-c89b-4ce7-9c06-9fde4c677a5e.png)

And outside /build/:
![image](https://user-images.githubusercontent.com/45211582/153394583-79e6879a-1088-4b2a-8cae-b5a44a49f473.png)

Closing this issue but feel free to add questions or suggestions!
