### ISSUE TITLE
setValidatorCompiler vs schemaController.compilersFactory.buildValidator

### ISSUE THREAD

**Issue by galer7** [fastify/help#626]
#### You have already researched for similar issues?
I have searched, but nothing answered my question.

#### What are you trying to achieve, or the steps to reproduce?

What I'm trying to achieve would be to remove `fastify.setValidatorCompiler` and replace it with the `buildValidator` from `schemaController.compilersFactory.buildValidator`.

The documentation for `schemaController` (https://www.fastify.io/docs/latest/Reference/Server/#schemacontroller) states for `compilersFactory` that:

>     * This factory is called whenever a new validator instance is needed.
>     * It may be called whenever `fastify.register()` is called only if new schemas have been added to the
>     * encapsulation context.

My question is, how can I signal that I need a new validator instance? I require this `validatorCompiler` in some plugins which are registered before the server starts. I see that accessing `fastify.validatorCompiler` from a plugin results in an undefined value. The `compilersFactory` looks like this in my server setup:

```js
compilersFactory: {
    buildValidator: function factory(externalSchemas, ajvServerOption) {
      // This factory function must return a schema validator compiler.
      return function validatorCompiler({ schema, method, url, httpPart }) {
        return ajv.compile(schema);
      };
    },
}
```
I'm using Ajv 8.9.0, but I don't think this is important.

This is the way I call `setValidatorCompiler`, and everything is working correctly:
```js
    fastify.setValidatorCompiler(({ schema }) => {
      if (schema.$id) {
        const stored = ajv.getSchema(schema.$id);
        if (stored) {
          return stored;
        }
      }

      return ajv.compile(schema);
    });
```
As stated above, I would like to have my instance working without this (if I correctly understand what problem `schemaController.compilersFactory` wants to solve).

#### What was the result you received?

If I don't call `setValidatorCompiler` in the first plugin I register, `fastify.validatorCompiler` is undefined even with `schemaController.compilersFactory.buildValidator` set!
#### What did you expect?

As stated in the documentation:

>     * This factory is called whenever a new validator instance is needed.
>     * It may be called whenever `fastify.register()` is called only if new schemas have been added to the
>     * encapsulation context.

#### Context

* *node version*: 16.13.2
* *fastify version*: 3.27.0
* *os*: Windows
* *any other relevant information*:

**Comment by mcollina** [comment]
cc @Eomm

**Comment by Eomm** [comment]
Setting the `setValidatorCompiler` force the fastify instance to fill the `validatorCompiler` variable.

Setting the `buildValidator` factory instead does not fill the `validatorCompiler` because the factory will be used when needed.
The issue you are facing is that the factory/the `validatorCompiler` is needed during the startup phase:

- after the plugins have been registered and executed
- after the routes have been processed internally by fastify (to load the `schema` option)
