### ISSUE TITLE
Same error again: `Promise may not be fulfilled with 'undefined' when statusCode is not 204`

### ISSUE THREAD

**Issue by bacloud22** [fastify/help#627]
## 💬  Question here 

I'm having an error thrown whenever I try to reach any endpoint involving `blabla` decorator. Other endpoints are not showing any errors. I note that with the error being thrown, _I think_ there are are no functional errors on my app as far as I see.
also I note that my route handler needs to be `async`, no way around. 
The error is:

> {
   "type":"FastifyError",
   "message":"Promise may not be fulfilled with 'undefined' when statusCode is not 204",
   "stack":"FastifyError: Promise may not be fulfilled with 'undefined' when statusCode is not 204\n    at C:\\Users\\Administrator\\app\\node_modules\\fastify\\lib\\wrapThenable.js:30:30\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
   "name":"FastifyError",
   "code":"FST_ERR_PROMISE_NOT_FULFILLED",
   "statusCode":500
}

```js
async function routes(fastify, options) {
    const blabla = require('../decorators/blabla')
    fastify.decorateReply('blabla', blabla)

    fastify.get('/', async function (req, reply) {
        ...
        const data = {
            ...
        }
        reply.blabla([data, 'index', 'listings'], req)
    })
````

with

```js
function blabla(context, req) {
    if (NODE_ENV == -1) {
        this.send(context[0])
    } else {
        const userFriendlyMsg = renderer(...context)
        const route = context[1]
        this.view(`/templates/pages/${route}`, userFriendlyMsg)
    }
}
```

_Many many thanks to all Fastify team for keeping this stable and very up to date with all web standards and what users would like to see._

**Comment by mcollina** [comment]
You are missing a `return reply` at the end.
