### ISSUE TITLE
Some responses are not logged.

### ISSUE THREAD

**Issue by holmok** [fastify/help#629]
#### You have already researched for similar issues?

Doing a quick look I did not see an issue on this.

#### What are you trying to achieve, or the steps to reproduce?

I created a route that returns a promise that takes some amount of time.  When a browser hits the route multiple times before the response, only the successful response logs out.  See the code below.

```js
import Fastify, { FastifyInstance, RouteShorthandOptions } from 'fastify'

const server: FastifyInstance = Fastify({ logger: true })

const opts: RouteShorthandOptions = {
  schema: {
    response: {
      200: {
        type: 'object',
        properties: {
          status: {
            type: 'string'
          }
        }
      }
    }
  }
}

server.get('/ping', opts, async (request, reply) => {
  return await new Promise((resolve) => {
    setTimeout(() => {
      server.log.info('ping!')
      resolve({ status: 'ok' })
    }, 1304)
  })
})

const start = async (): Promise<void> => {
  try {
    await server.listen(3000)
  } catch (err) {
    server.log.error(err)
    process.exit(1)
  }
}

start().catch(console.error)

```

#### What was the result you received?

Here is the log output (`hostname` removed):
```
{"level":30,"time":1644771048389,"pid":15394,"hostname":"-","msg":"Server listening at http://127.0.0.1:3000"}
{"level":30,"time":1644771054670,"pid":15394,"hostname":"-","reqId":"req-1","req":{"method":"GET","url":"/ping","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":50979},"msg":"incoming request"}
{"level":30,"time":1644771055398,"pid":15394,"hostname":"-","reqId":"req-2","req":{"method":"GET","url":"/ping","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":50980},"msg":"incoming request"}
{"level":30,"time":1644771055980,"pid":15394,"hostname":"-","msg":"ping!"}
{"level":30,"time":1644771056703,"pid":15394,"hostname":"-","msg":"ping!"}
{"level":30,"time":1644771056705,"pid":15394,"hostname":"-","reqId":"req-2","res":{"statusCode":200},"responseTime":1306.2713341712952,"msg":"request completed"}
```

#### What did you expect?

I would expect logs with a `res` object for each request-id.  I am hoping that there is some optimization here since the remote address bailed on the initial request. So my questions are:
1) If this is an optimization, is there an event I can listen for to capture these abandoned requests?
2) ...or is this a logging bug?

#### Context

* *node version*: v16.13.1
* *fastify version*: ^3.27.1
* *os*: Mac

**Comment by mcollina** [comment]
Can you include the client to reproduce this? It seems quite vague in how the multiple requests are performed. Are you canceling the previous ones?

**Comment by mcollina** [comment]
This looks like a good feature, would you like to send a PR?

**Comment by holmok** [comment]
I'll take a swing this weekend.

**Comment by mcollina** [comment]
I would you to target the `next` branch. We'll be shipping v4 soon and the relevant code might have seen some changes. I would prefer not having to resolve conflicts along the way.

**Comment by jsumners** [comment]
We really need to get `next` rebased.

**Comment by mcollina** [comment]
I know it's an hard problem :(.
