### ISSUE TITLE
How to return an image/png using aws-fastify-lambda?

### ISSUE THREAD

**Issue by elliot-nelson** [fastify/help#630]
## 💬  Question here 

I think I'm putting all the pieces together, but I can't quite get it working...

I'm deploying a folder to an AWS Lambda function, and I've confirmed it contains the right files (bytes are all correct in the PNG).

Then I set up `fastify-static`:

```js
import FastifyStatic from 'fastify-static';

await fastify.register(FastifyStatic, {
  root: path.join(Config.appFolder, 'web', 'assets'),
  prefix: '/assets'
});
```

And my handler for Lambda:

```js
import awsLambdaFastify from 'aws-lambda-fastify';

export const WebServerFunction = awsLambdaFastify(instance, {
  binaryMimeTypes: ['image/png', 'image/jpeg']
});
```

Going to the URL `https://<url>/assets/logo.png` returns a binary file, but it is _80882_ bytes long instead of _44484_ bytes long, and can't be opened.  It does have what sort of looks like the right header and footer, but a lot of the middle is garbled and jumbled.

Is there additional code I'm missing that's part of the Lambda function? Or do I need to pair this with something special in the API Gateway definition?

## Your Environment

- *node version*: 14
- *fastify version*: >=2.0.0
- *os*: Linux
- (using AWS::Serverless::Function CloudFormation template for deployment)

**Comment by zekth** [comment]
Everything looks good: https://github.com/keycap-archivist/lambda-wishlist/blob/37dd785733450f15395c0f572dd3f537fc8c4157/src/api/controllers/wishlist.ts#L11

Can you try to serve a png without fastify static ?

**Comment by elliot-nelson** [comment]
@zekth Thanks for the example!

it looks like you are encoding in base64 manually, whereas I thought that the lambda wrapper did that automatically - so that might be my problem!

**Comment by elliot-nelson** [comment]
Closing... it turns out the code I thought was running, was not running.  (Testing in Lambda console showed "isBase64Encoded" flag was false because the file was old.)  The code I posted above worked just fine once I actually uploaded it.

Thanks for looking.
