### ISSUE TITLE
Having multiple calls on request again

### ISSUE THREAD

**Issue by bacloud22** [fastify/help#636]
I read documentation about async handlers and hooks and that `done` must not be called in case of an async function.

## 💬  Question here 

I'm having multiple calls on this request 

```js
fastify.post('/donations', postSectionHandler)
```

```js
// postSectionHandler being either
    return async (req, reply, done) => {
        console.log("*************CALLED TWICE***********")
        const { body } = req
        const { error } = validationPipeLine(req)
        if (!isEmpty(error)) {
            reply.send({ message: 'Invalid request' })
        } else {
            // Files other than images are undefined
            if (!req.file) {
                reply.send({
                    message: 'Invalid request',
                    data: body,
                    error: 'file not found'
                })
            }
            let acknowledged = await insertDocument(QInstance, req, reply, null, false)
            // done()
        }
    }
```

Thanks in advance !

**Comment by Eomm** [comment]
Could you try to remove the done argument from the postSectionHandler function?

You should not mix async and callback styles

**Comment by bacloud22** [comment]
still the same, 
About not mixing callbacks and async, I don't see another way around this, if you are talking about the [WriteStream](https://stackoverflow.com/a/39880990/1951298) the events must be called

**Comment by bacloud22** [comment]
Excuse me I just found that either NODE_ENV is < 1 or not, the error is the same. So this is weird again. 
Please let me narrow the error root again tomorrow and come back.

**Comment by bacloud22** [comment]
As I thought the problem was not with plugins at all. I cleaned the code up in this issue. Now, Let me detail the handler please.
**The problem is definitely with what the handler returns**.

I narrowed this to two cases:

```js
// this works !
let data = await insertDocument(QInstance, req, null, false)
return data
```

```js
// This makes the route being called twice !!!!
let data = await insertDocument(QInstance, req, null, false)
reply.blabla([data, 'listing', section])
return reply
```

It is to note that I also making this 
```js
reply.blabla([data, 'listing', section])
return reply
```

all over the app and it is working in other routes.

**Comment by mcollina** [comment]
I would recommend you to write a small example to reproduce so we can help you.

If your handler is called twice, you have a hook that is calling `done` twice and/or being declared `async` while also calling `done`.

**Comment by bacloud22** [comment]
@mcollina Indeed, I had a hook with a callback, where in the callback, I was calling `done()`. I turned it to simple `return`
Thanks a lot @mcollina & @Eomm.

For reference, this might help anybody... Also this piece of code, is a nice wrapper around **[Project Honey Pot](https://www.projecthoneypot.org/)**

```js
// TODO: Rate limiter && honeyPot except in process.env === 'monkey chaos'
fastify.addHook('preHandler', (req, reply, done) => {
    // TODO: req.socket ? does it work ?
    let ip = req.headers['x-forwarded-for'] || req.socket.remoteAddress
    if (ip.substr(0, 7) === '::ffff:') {
        ip = ip.substr(7)
    }
    if (NODE_ENV < 1 || ip.split('.')[0] === '127') {
        done()
    }
    const reversedIp = ip.split('.').reverse().join('.')
    dns.resolve4([process.env.HONEYPOT_KEY, reversedIp, 'dnsbl.httpbl.org'].join('.'),
        function (err, addresses) {
            if (!addresses) {
                return
            } else {
                const _response = addresses.toString().split('.').map(Number)
                // https://www.projecthoneypot.org/threat_info.php
                const test = (_response[0] === 127 && _response[2] > 50)
                if (test) {
                    reply.send({ msg: 'we hate spam to begin with!' })
                }
                return
            }
        })
})
```

**Comment by Eomm** [comment]
In the code, there is a condition when you run done and call reply.send.

Doing this is an issue because the done let the flow going further to the hander, meanwhile the dns code runs and call reply.send in an uncertain time. So the request is processed twice and you don't know which code will call send first

**Comment by bacloud22** [comment]
I see. Thanks for clarifying. 
I think somehow that send was not being called in my flow of execution because I don't have an impression of send being called twice. But yes, as a correct solution I would return after done??

**Comment by Eomm** [comment]
> Does return alone, doesn't let the handler persue with execution?

If the `done` is not called the execution will stop and the request will timeout.

Not sure about your logic, but a `return` after the `done` seems correct (unless you need to run the `dns` logic in any case)

**Comment by anishkumar127** [comment]
Thanks same issue was their im using async prehandler and onRequest , and inside also i was using the done() that was causing the issue of handler calling 2 times. now i have removed the async only using done().

one suggestion need.
which one should best way to prefer async await or done () ? in preHandler and onRequest if their is db calls or no db calls.

**Comment by Eomm** [comment]
> which one should best way to prefer async await or done () ? in preHandler and onRequest if their is db calls or no db calls.

- if there are async operations in the function => use async/await
- if there are sync operations in the function => use the callback because it is faster
- if simplicity is the key on the project => use always async/await and your team will never make a mistake

my fastify book explains it 😄
