### ISSUE TITLE
Unable to add array of origins

### ISSUE THREAD

**Issue by bmccorm2** [fastify/help#639]
Like title says, I can do this and the access-control-allow-origin header is set correctly:
`app.register(cors, { origin: 'http://localhost:8080' });`

However if i do this, the header is not set and i get CORS errors:
`app.register(cors, { origin: ['http://localhost:8080)'] });`

Any idea why the second option doesn't work?  (i need multiple origins)

**Comment by climba03003** [comment]
> Like title says, I can do this and the access-control-allow-origin header is set correctly: `app.register(cors, { origin: 'http://localhost:8080' });`
> 
> However if i do this, the header is not set and i get CORS errors: `app.register(cors, { origin: ['http://localhost:8080)'] });`
> 
> Any idea why the second option doesn't work? (i need multiple origins)

Just curious, why a close bracket inside the origin?

**Comment by bmccorm2** [comment]
I'm trying to use multiple origins by placing them into an array, as documented in the github page: https://github.com/fastify/fastify-cors#options

**Comment by Asjas** [comment]
No they are asking why you have a closing bracket in your origin. You likely made that typo in your code.

```js
['http://localhost:8080)']
```

**Comment by bmccorm2** [comment]
Oh i see!  Sorry that was a copy/paste error on my part!  To clarify:
**works:** 
`app.register(cors, { origin: 'http://localhost:8080' });`
**does not work:**
`app.register(cors, { origin: ['http://localhost:8080'] });`

I'm looking at the header response in chrome tools to check if the access-control-allow-origin header is set.

**Comment by climba03003** [comment]
Only `string` will **always** set the header. When it is `array`, `boolean`, `RegExp` and `function`, only the **match** request origin will set the header.

**Comment by lfurzewaddock** [comment]
I've used this before;

```
const originsExampleStoredInEnv =  'http://localhost:8080,http://localhost:8040';

app.register(cors, { origin: originsExampleStoredInEnv.split(',') });
```

**Comment by bmccorm2** [comment]
Thanks all for the suggestions.  It works exactly as advertised.  Noob mistake - i forgot to listen on 0.0.0.0.  It worked in lower environments because everything was running from the same machine.  I was just getting a CORS error so it threw me off track.
