### ISSUE TITLE
Custom html page for validation error?

### ISSUE THREAD

**Issue by Extarys** [fastify/help#64]
#### You have already researched for similiar issues?
Yes.

#### What are you trying to achieve or the steps to reproduce?
See below.

```js
	fastify.route({
		method: "GET",
		url: "/Fframe",
		handler: miController.staticIframe,
		schema: {
			description: "Serve the static iframe",
			tags: ["private", "static"],
			summary: "qwerty",
			querystring: {
				type: "object",
				properties: {
					k: { type: "string" },
					cw: { type: "string" },
					c: { type: "string" },
					theme: { type: "string" },
					o: { type: "string" }
				},
				required: ["k", "cw", "c"]
			}
		}
	})
```

#### What was the result you received?
Currently I get the error on a black page (Firefox):
`"querystring should have required property 'k', querystring should have required property 'cw', querystring should have required property 'c'"`

#### What did you expect?
I would like a way to customize this message and perhaps serve a little html page. Since end user may end up seeing this if someone messed up, I'd like it to be prettier.

Can this be achieved?

#### Context

* *node version*: 4,5,6,7,8,9: 10
* *fastify version*: >=0.37.0 2.0
* *os*: Mac, Windows **Linux**
* *any other relevant information*: Hmmm...

Thanks for your help!

**Comment by nwoltman** [comment]
You can send a custom error response from an error handler set with [`fastify.setErrorHandler()`](https://www.fastify.io/docs/latest/Server/#seterrorhandler).
