### ISSUE TITLE
Suppress default server.listen() console message?

### ISSUE THREAD

**Issue by dsbudiac** [fastify/help#641]
Is there a way to suppress the default console info message when calling `server.listen()` without passing a null logger?

```ts
import fastify from 'fastify'

const server = fastify({ logger: true })
server.listen(3000, () => console.log('my custom start message'))
```

"my custom start message" will log in addition to this function: https://github.com/fastify/fastify/blob/f0281948cfcb04cd1c5c93a330823278e4a1b44f/lib/server.js#L272-L288

## Environment

- *node version*: 17.6.0
- *fastify version*: 3.27.3
- *os*: MacOS

**Comment by Eomm** [comment]
you could do this trick

```
const fastify = require('fastify')({ logger: true })
fastify.log.level = 'silent'
fastify.listen(3000, () => {
  fastify.log.level = 'info'
  fastify.log.info('my custom start message')
})
```

but no: there is no option to turn it off out of the box
