### ISSUE TITLE
fastify-formbody already included

### ISSUE THREAD

**Issue by thearegee** [fastify/help#642]
Hello,

I'm trying to write a module for Fastify which adds a `POST` request endpoint to an existing web server. I need access to the `POST` body so I'm using: https://github.com/fastify/fastify-formbody

However as this module could be consumed by different people with different step ups, I can't register `formbody` globally.
So I have added it specifically to the route I need it on, however if the server already has it registered its the same issue.

You get this error:

```
throw new FST_ERR_CTP_ALREADY_PRESENT(contentType)
          ^
FastifyError [Error]: Content type parser 'application/x-www-form-urlencoded' already present.
```

So you can understand and recreate here is a simple server you can recreate.

```JavaScript
import Fastify from "fastify";
import myModule from "npm-module";
// including to see if we can handle if already added
import fastifyForm from "fastify-formbody";
const app = Fastify();
const port = 3000;

app.register(fastifyForm);
myModule(app, '/test/route');

app.get("/", (request, reply) => {
  reply.send("Hello World!");
});

app.listen(port, () => {
  console.log(`Example Fastify app listening on port ${port}`);
});
```

Then the module I want to add, I included some code to try and hack around the issue:

```JavaScript
import FastifyBodyParser from "fastify-formbody";

export default async (server, route) => {
  server.register((instance, options, next) => {
    // This is a bit ugly but for now this might work
    // checking to see if Fastify already has FastifyBodyParser
    try {
      instance.register(FastifyBodyParser).post(route, (req, res) => {
        const {body} = req;
        res.send(body)
      });
    } catch (error) {
      instance.post(route, (req, res) => {
        const {body} = req;
        res.send(body)
      });
    }
    next();
  });
};
```

#### What was the result you received?

I was hoping a try and catch would help here but it doesn't - either way that was a hack to show what I'm trying to do.

What I want to know is does Fastify already have `fastify-formbody` registered if so I don't need to, but I suppose the problem with that is, this could still be an issue depending where my module was added in the call chain.

So what I'm asking is how can I write this module without knowing if is was already registered or not?

I'm also open to this is the wrong way to write this type of module.

#### Context

* *node version*: 16 - using native modules
* "fastify": "^3.27.2"
* "fastify-formbody": "^5.2.0",
* *os*: Mac

**Comment by climba03003** [comment]
https://www.fastify.io/docs/latest/Reference/Server/#hascontenttypeparser

You can check if the content-type parser exist before register it.
