### ISSUE TITLE
API Versioning with fastify-autoload

### ISSUE THREAD

**Issue by rsax02** [fastify/help#643]
## 💬  Question here 

Hello! I'm trying to load my routes with fastify-autoload. It works as intended! But I'm trying to assign multiple prefixes to the same routes (api versioning)

```js
app.register(autoload, {
    dir: path.join(__dirname, "src"),
    options: { prefix: "/api" },
    routeParams: true,
});
````

I'm trying to do something like 

```js
app.register(autoload, {
    dir: path.join(__dirname, "src"),
    options: { prefixes: [ "/api/v1", '/api/v2' ] },
    routeParams: true,
});
````

Is it possible to do with fastify-autoload? I need to use that plugin because of the `routeParams` option.

## Your Environment

- *node version*: v17.7.1
- *fastify version*: v3.27.4
- *os*: Linux

**Comment by mcollina** [comment]
You can register autoload twice:

```js
app.register(autoload, {
    dir: path.join(__dirname, "src"),
    options: { prefix: "/api/v1" },
    routeParams: true,
});
app.register(autoload, {
    dir: path.join(__dirname, "src"),
    options: { prefix: "/api/v2" },
    routeParams: true,
});
```
