### ISSUE TITLE
fastify-swagger: How to work around an intentional circular dependency

### ISSUE THREAD

**Issue by j-gibweb** [fastify/help#645]
I have a data model with circular dependencies.
Imagine my API has a query param called `expand[]` which is an array of types that allows them to get the record they're querying for, plus the related record of that type. So `GET /owners/1?expand[]=dog` would return something like:
```
[{id: 1, ownerName: "Ted", dog: {id: 1, dogName: "Chester"}}]
```

It's just as likely that my users will attempt to `GET /owners/1?expand[]=dog`
as it is they will attempt to `GET /dogs/1?expand[]=owner`

The trouble here is that fastify-swagger doesn't appear to support circular dependencies and the community in general seems to discourage them, despite them being technically possible in the openapi spec.

Attempting to structure your schema in this way will result in a variety of errors depending on how you set the project up.
```
/Users/ryangosling/Code/my_project/node_modules/@fastify/ajv-compiler/index.js:11
    const externals = JSON.stringify(externalSchemas)
                           ^
TypeError: Converting circular structure to JSON
```
and
```
err":{"type":"RangeError","message":"Maximum call stack size exceeded"
```

[Replit link](https://replit.com/@j-gibweb/QueasyEnergeticAlgorithm#index.js)
If you issue a `GET https://queasyenergeticalgorithm.j-gibweb.repl.co/documentation/static/index.html` you see the stackoverflow error in the Replit console (holy crap! Replit is so cool!)

Finally, my question is: How are you supposed to structure your schema in a situation like this where you have a 1:1 relationship? 

I've been hunting all day and I don't see a good example of how to solve this problem technically or architecturally. The closest I've seen is sort of a hack where you'd wrap one direction of the relationship in a `S.oneOf()` or similar so the fastify serialization doesn't follow the relationship graph infinitely. 

Thanks for looking, sorry if I am lacking details. I'm happy to add whatever info is needed for clarity. 

## Your Environment

- *node version*: 12.14.1
- *fastify version*: 3.22.1
- "fastify-swagger": 4.12.6
- *os*: Mac

**Comment by climba03003** [comment]
OpenAPI support circular reference using `$ref`. Not the object itself is circular referencing to each another.

**Comment by j-gibweb** [comment]
After messing with this for a while my team has settled on the following workaround.

```
const personSchema = S.object()
  .id("person")
  .prop("name", S.string())
  .prop("friend", S.allOf([S.ref("dog")]))

const dogSchema = S.object()
  .id("dog")
  .prop("name", S.string())
  .prop("friend", S.allOf([S.ref("person")]))
```

The resulting schema is indistinguishable from a direct 1:1 relationship. 
Generated clients (Java, JavaScript) reference the model names directly, not `AllOfDog` or `AllOfPerson`, no more infinite loops. Success I think. Hopefully this helps others who encounter this problem.
