### ISSUE TITLE
getMultipartParams

### ISSUE THREAD

**Issue by SudoDios** [fastify/help#646]
Hi developers.
I am trying to upload two files to the server along with the parameters.
But the question is: 
my android codes :
```java
AndroidNetworking.upload("http://192.168.231.130/api/addAds")
            .addMultipartFile("fileOne", File("path"))
            .addMultipartFile("fileTwo", File("path"))
            .addMultipartParameter("modelToSaveMongo",myModel)
            .setPriority(Priority.HIGH)
            .build()
            .getAsString(object : StringRequestListener{
                override fun onResponse(response: String?) {
                    
                }
                override fun onError(anError: ANError?) {
                    
                }
            })
```
1- How to upload **fileOne** and **fileTwo** in two different folders (by getting the name).
2- How do I get the **modelToSaveMongo** before uploading and storing it in the database?

**Comment by Eomm** [comment]
1) https://stackoverflow.com/a/71452106/3309466

2) You need to read the parameter. This article should cover it: https://backend.cafe/fastify-multipart-upload

**Comment by SudoDios** [comment]
Nice 👌
