### ISSUE TITLE
[fastify-http-proxy] - How to dynamically set upstream by request host (tenant)

### ISSUE THREAD

**Issue by edson-nascimento** [fastify/help#648]
## 💬  [fastify-http-proxy] - How to dynamically set upstream by request host (tenant)

I'm developing a multi tenant api where:
Each tenant will have a different upstream url that must be dynamically set after identification.
I do the tenant identification by domain hostname.

```typescript
import { FastifyInstance, FastifyRequest, preHandlerHookHandler } from 'fastify';
import proxy from 'fastify-http-proxy';

async function getProxyUrlByTenant(request: FastifyRequest): Promise<string> {
  const tenant = await getTenantByHost(request.hostname);

  if (!tenant) throw new Error('Unauthorized');

  return tenant.apiUrl;
}

// Tenant routes
export async function proxyRoutes(server: FastifyInstance) {
  server.get('/status', async () => {
    return {
      status: 'active',
      at: new Date().toISOString(),
    };
  });

  // Proxy routes
  server.register(proxy, {
    upstream: await getProxyUrlByTenant(/* how get request here ? */),
    prefix: '/proxy',
  });
}
```

## Your Environment

- *node version*:  16
- *fastify version*: ^3.27.4
-  *fastify-http-proxy version*: ^6.2.2
- *os*:  Windows

**Comment by mcollina** [comment]
You can use fastify-reply-from directly. I don't think this is supported here right now. Or you could send a PR.
