### ISSUE TITLE
Detect 404s in preHandler middleware

### ISSUE THREAD

**Issue by Marsup** [fastify/help#65]
#### You have already researched for similar issues?

I have, and couldn't find anything.

#### What are you trying to achieve or the steps to reproduce?

We want to have a fastify server that defaults to secured routes, and only disables authentication when explicitly told so. To that end, we set a global `preHandler` that automatically applies an authentication middleware to all routes.

The disabling part is easy, we look for the route config in `reply.context` and disable the auth accordingly. But the secure default is trickier, as there seems to be no way to differentiate an actual route without any config (so it should be secure) from a 404. I found a correlation between 404s and `request.params` having a `*` as key but that seems rather weak.

So my question is, is there a standard way to detect 404s in a `preHandler` ?

#### Context

* *node version*: 8
* *fastify version*: 2.x
* *os*: Linux

**Comment by mcollina** [comment]
Can you please make an example? I'm a bit lost.

**Comment by Marsup** [comment]
Sure thing.

So far we have something along those lines:
```js
const server = fastify();
server.addHook('preHandler', async function authenticate(request, reply) {
  const { config } = reply.context;
  if (config.secure === false) {
    // No auth
    return request;
  }

  await validateAuth(request);
  return request;
});
```

So all routes are authenticated but those with secure=false. The problem is this middleware is called even for 404s, so the `validateAuth` gets called even when there's no point in doing so since it will end up in a 404 anyway. I'm missing a condition to skip the validation in this case. Does it help?

**Comment by Marsup** [comment]
A running example would be: https://runkit.com/embed/5wgk1i449uzm

I'd like to return 404s for those, and I can't find a way to detect those cases and skip the authentication.

**Comment by mcollina** [comment]
You should wrap your routes in a plugin, and define the 404 handler outside that plugin. Then your hooks will be defined for all the matching/secured routes.

```js
const server = fastify();
server.register(async function () {
server.addHook('preHandler', async function authenticate(request, reply) {
  const { config } = reply.context;
  if (config.secure === false) {
    // No auth
    return request;
  }

  await validateAuth(request);
  return request;
});
// routes here
})
```

**Comment by Marsup** [comment]
Our plugins are functionally scoped rather than technically, so in any given plugin you can have both authenticated and public routes. Our `preHandler` is actually in a `fastify-plugin` so that we don't have/forget to declare it anywhere. On a pre handler, fastify necessarily knows whether a request can be routed or not, right? Is my assumption that `request.params.hasOwnProperty('*')` will only be true for 404s wrong?

**Comment by mcollina** [comment]
@Marsup yes we already know if this is a 404 or not. We should really expose this to the user.

* [ ] Add `is404` in `Context`  in https://github.com/fastify/fastify/blob/master/fastify.js#L961
* [ ] Add a `is404` property in: https://github.com/fastify/fastify/blob/master/lib/request.js
* [ ] pass `is404` in the constructor in: https://github.com/fastify/fastify/blob/master/fastify.js#L326-L327
* [ ] write a bunch of test to check if it's all working

Would you like to send a PR?

**Comment by nwoltman** [comment]
@Marsup Could you explain more why @mcollina's [suggestion](https://github.com/fastify/help/issues/65#issuecomment-471476002) doesn't work for you. It looks like the right solution. By wrapping your hook and routes together in a call to `register()`, the hook will be bound only to the routes and not to the 404 handler.

**Comment by Marsup** [comment]
Maybe I'm missing something then. Let me walk you through my thoughts.

To me the best way to globally apply an authentication logic is to let our security module register its hooks through `fastify-plugin`, this way nothing can escape it. I can understand the logic of applying it through scoping (even though adding a scope layer just to shield the server's 404s from middlewares seems weird), but then you have to scatter your security plugin initialization since it can't act on siblings, right? Also, routes can still escape that with programmer mistakes, but that's a minor issue I guess.

To be clear, if you have this (each "statement" being a plugin):
```
Server
 ↪ Main plugin
   ↪ Security
   ↪ Other routes
```
Then you can't let `Security` register hooks for `Other routes`, so you have to somehow externalize the middleware and let the `Main plugin` do it, correct?

While I understand why it works that way, I can't help but think there should be a better way.

Or maybe I'm over-engineering it, you tell me :)

**Comment by nwoltman** [comment]
> but then you have to scatter your security plugin initialization

You shouldn't have to. If you create a single entry point for all of your routes, then scoping the security plugin only needs to happen once at the top level:

```js
// Root Scope
const fastify = require('fastify');
const server = fastify();

server.register(async (scopedServer) => {
  // Security Scope (everything in this scope gets the auth hook)
  scopedServer.register(require('./security');
  scopedServer.register(require('./all-routes'); // All these routes get the auth hook
});
```

Since the `./security` plugin uses `fastify-plugin`, then all routes defined in the "Security Scope" will have the auth hook.

I'm assuming this is what you meant by your question, "since it can't act on siblings, right?" Let me know if that's not what you meant.

**Comment by RafaelGSS** [comment]
Hello. 

Why not send a flag in 404 (default route)? 
I understand that can be solved in the register `preHandler` inside another scope. But, we can expose this flag or set `preHandler` only for routes found.

**Comment by ankology** [comment]
Hi! The information if a requested route is 404 is discovered before calling hooks right? I think a simple flag in request object can be very useful to avoid unecessary execution stuff when a route not exists. Just:
```if(request.is404){ //do stuff }``` like @mcollina says can solve that. Depending on implementation this can be a serious issue, in my case i need to go to database to perform large permissions search from user token (jwt in preHandler), and assuming that my service is public and allow anyone to create an account (and grab a token), its possible to make stress in the database just sending 404 routes. Maybe i'm wrong on some words because i recently start using fastify, btw thanks for the project, looks great!

**Comment by mcollina** [comment]
@ankology would you like to send a PR for https://github.com/fastify/help/issues/65#issuecomment-471491848?

**Comment by ankology** [comment]
@mcollina i back to look at that now and maybe have another existent solution to that. Using the `preParsing` hook with the `NotFoundHandler`: 
```
app.setNotFoundHandler({

    preParsing: (req, reply, next) => {

        reply.code(404).send({

            code: 'NOT_FOUND',
            message: `The route '${req.raw.url}' not exists.`
        })
    }
});
```
You think that's work well? In my tests that works! Btw i can try to make a PR for [#65 (comment)](https://github.com/fastify/help/issues/65#issuecomment-471491848) but not too quickly, i'm very busy these days!
