### ISSUE TITLE
How to always serve the one, single app, regardless of the requested subdomain?

### ISSUE THREAD

**Issue by mkhoussid** [fastify/help#651]
#### You have already researched for similar issues?
Yes

#### What are you trying to achieve, or the steps to reproduce?

I'm trying to serve different parts of my app on one server.

For instance, a user could visit,

```js
http://app.my-site.com
```
or

```js
http://admin.my-site.com
```
I'm using React on the frontend, conditionally producing the appropriate routes based on the subdomain, meaning I actually have one server serving one frontend that dynamically renders content.

When working with the webpack devserver, I'm able to enable this feature by adding the [`--allowed-hosts all`](https://webpack.js.org/configuration/dev-server/) option.

But then I build the project and try to serve it as follows:

```
app.register(require('fastify-static'), {
	root: path.join(__dirname, 'client', 'dist'),
});

app.setNotFoundHandler((request, reply) => {
	reply.sendFile(path.join(__dirname, 'client', 'dist', 'index.html'));
});
```
This works, but only locally (Heroku throws a 404 error).

After some research, I've found that express has a package for this purpose called [`express-subdomain`](https://www.npmjs.com/package/express-subdomain). Is there a similar one for fastify or should I be doing something else entirely?

#### Context

* *node version*: 14
* *fastify version*: 3.27.4
* *os*: Mac

**Comment by Eomm** [comment]
It is not clear to me your configuration nor your error.

The 404 suggests:

- Does a `hello` endpoint work?
- Does the `path.join(__dirname, 'client', 'dist', 'index.html')` exist?
- Does a single URL work?

The multiple URL suggests:

- is the CORS configurated properly?
- Are you listening to all the interfaces `0.0.0.0`? `fastify.listen(PORT, '0.0.0.0')`

**Comment by mcollina** [comment]
Are you asking if you could define specific routes for each of your subdomains? Or how to configure Heroku for your use case? Or possibly both?

**Comment by mkhoussid** [comment]
> Are you asking if you could define specific routes for each of your subdomains? Or how to configure Heroku for your use case? Or possibly both?

My fastify server serves as a REST API server and I'm using client side routing (react-router) to manage the routes on the frontend. What do you mean by defining specific routes?

I'm just a little confused as to why locally building and serving the index.html file works, but if it's deployed to some service like Heroku, it doesn't. 

If I need to add a CNAME on Heroku for each subdomain I'm using, as some answers online suggest, then I can try that. But I'm not configuring anything locally when I build and serve, and it works, so hence my confusion.

**Comment by mkhoussid** [comment]
> It is not clear to me your configuration nor your error.
> 
> The 404 suggests:
> 
> - Does a `hello` endpoint work?
> - Does the `path.join(__dirname, 'client', 'dist', 'index.html')` exist?
> - Does a single URL work?
> 
> The multiple URL suggests:
> 
> - is the CORS configurated properly?
> - Are you listening to all the interfaces `0.0.0.0`? `fastify.listen(PORT, '0.0.0.0')`

Concerning the 404, nothing works and the path to index.html exists.

As for your second point, everything is properly configured. The app works just fine if I remove this subdomain approach.
