### ISSUE TITLE
preValidationCallback and preHandlerCallback being called before controller handler finishes

### ISSUE THREAD

**Issue by cesarvspr** [fastify/help#652]
![Screenshot from 2022-03-24 20-42-26](https://user-images.githubusercontent.com/37849741/160032761-738f33b7-059d-4a0f-bf86-cfd9fa241d76.png)

preHandlerCallback is being called before controller handler finishes what gives me:
```logs
"message":"Promise may not be fulfilled with 'undefined' when statusCode is not 204","stack":"FastifyError: Promise may not be fulfilled with 'undefined' when statusCode is not 204\n    at /usr/src/app/node_modules/fastify/lib/wrapThenable.js:30:30
```
But them the response is sent as expected.
my code is:

```typescript
  async Handler(req: FastifyRequest<any>, res: FastifyReply): Promise<void> {
    const result = await this.UseCase.exec(req.query) //preHandlerCallback is being called in parallel this function
    res.send(200, result)
  }
```

**Comment by climba03003** [comment]
Either dont't `return` if it does nothing, or `return reply`.

**Comment by cesarvspr** [comment]
> Either dont't `return` if it does nothing, or `return reply`.

Would you please explain is better?

**Comment by climba03003** [comment]
> > Either dont't `return` if it does nothing, or `return reply`.
> 
> Would you please explain it better?

https://www.fastify.io/docs/latest/Reference/Routes/#async-await

I think the document is clear enough.
> When using both `return value` and `reply.send(value)` at the same time, the first one that happens takes precedence, the second value will be discarded, and a warn log will also be emitted because you tried to send a response twice.
> You cannot return `undefined`. For more details read [promise-resolution](https://www.fastify.io/docs/latest/Reference/Routes/#promise-resolution).

Simply call `return` inside `async-await` is `return undefined`.

**Comment by cesarvspr** [comment]
> > > Either dont't `return` if it does nothing, or `return reply`.
> > 
> > Would you please explain it better?
> 
> https://www.fastify.io/docs/latest/Reference/Routes/#async-await
> 
> I think the document is clear enough.
> > When using both `return value` and `reply.send(value)` at the same time, the first one that happens takes precedence, the second value will be discarded, and a warn log will also be emitted because you tried to send a response twice.
> > You cannot return `undefined`. For more details read [promise-resolution](https://www.fastify.io/docs/latest/Reference/Routes/#promise-resolution).
> 
> Simply call `return` inside `async-await` is `return undefined`.

I got your logic, but without the return the behavior is the same.

**Comment by cesarvspr** [comment]
Thank you [climba03003](https://github.com/climba03003).

The solution was put this at the begin of handler.
```typescript
await res
```

**Comment by cesarvspr** [comment]
The problem persists, the point is the when I can an exec (my use-case) as child process the preValidations stills are running.

last code I tried:
```typescript
  @GET('/endpoint')
  async Handler(req: FastifyRequest<any>, res: FastifyReply): Promise<void> {
    const result = await this.beneficiaryGetListUseCase.exec(req.query) // the preValidationCallback is running parallel this
    res.send({data: 'result'})
  }
```

the output of request is:
```json
{
    "data": "result"
}
```
the logs:
```txt
my_app       |  -------------------------- preHandlerCallback CALLED ----------------------
my_app       | {"level":50,"time":1648178904856,"pid":942,"hostname":"e621ce6dbfd1","reqId":"54760f41-a057-4d71-a13d-a535c6f32774","err":{"type":"FastifyError","message":"Promise may not be fulfilled with 'undefined' when statusCode is not 204","stack":"FastifyError: Promise may not be fulfilled with 'undefined' when statusCode is not 204\n    at /usr/src/app/node_modules/fastify/lib/wrapThenable.js:30:30\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","name":"FastifyError","code":"FST_ERR_PROMISE_NOT_FULFILLED","statusCode":500},"msg":"Promise may not be fulfilled with 'undefined' when statusCode is not 204"}
my_app       | {"level":30,"time":1648178904873,"pid":942,"hostname":"e621ce6dbfd1","labels":{"requestId":"54760f41-a057-4d71-a13d-a535c6f32774"},"logging.googleapis.com/sourceLocation":"/beneficiaries/list","logging.googleapis.com/spanId":"54760f41-a057-4d71-a13d-a535c6f32774","httpRequest":{"requestMethod":"GET","requestUrl":"/endpoint?all=true","userAgent":"PostmanRuntime/7.28.4","status":200,"latency":"0.024203840s","responseSize":"17"}}

```

**Comment by cesarvspr** [comment]
@climba03003 @mcollina would you please consider looking at my previous commnet?

**Comment by climba03003** [comment]
> @climba03003 @mcollina would you please consider looking at my previous comment?

I would say, please provide a minimal repro in this case. 
It cannot be debug without a runnable code.

**Comment by Eomm** [comment]
Did you try?

```
  @GET('/endpoint')
  async Handler(req: FastifyRequest<any>, res: FastifyReply): Promise<any> {
    const result = await this.UseCase.exec(req.query) // the preValidationCallback is running parallel this // where is the `preValidationCallback`??
    return {data: 'result'} // look at this
  }
```

**Comment by mcollina** [comment]
Is this a Nest.js app?

**Comment by jsumners** [comment]
You state that you have pre-validation and pre-handler methods defined. But you don't show them in your question. I don't know how you expect people to assist you when you provide only 1/3 of the information.

**Comment by cesarvspr** [comment]
> You state that you have pre-validation and pre-handler methods defined. But you don't show them in your question. I don't know how you expect people to assist you when you provide only 1/3 of the information.

Sorry, the internal methods pre-validation and pre-handler methods are defined inside fastify lib and called by itself during the lifecycle. Not by me.

**Comment by cesarvspr** [comment]
> Is this a Nest.js app?

Nop, it is a node-ts api application.

**Comment by cesarvspr** [comment]
> > @climba03003 @mcollina would you please consider looking at my previous comment?
> 
> I would say, please provide a minimal repro in this case. It cannot be debug without a runnable code.

Sure, I will try bringing it asap.

**Comment by cesarvspr** [comment]
> Did you try?
> 
> ```
>   @GET('/endpoint')
>   async Handler(req: FastifyRequest<any>, res: FastifyReply): Promise<any> {
>     const result = await this.UseCase.exec(req.query) // the preValidationCallback is running parallel this // where is the `preValidationCallback`??
>     return {data: 'result'} // look at this
>   }
> ```
Thank you for your suggestion but it didn't work unfortunately. 

The internal methods pre-validation and pre-handler methods are defined inside fastify lib and called by itself during the lifecycle. Not by me.

**Comment by mcollina** [comment]
What's providing the decorators?

**Comment by mcollina** [comment]
Would you be able to create an example that reproduces only using lib in this org? As you'd note that module is not maintained by us.

My guess is that's a bug there. You should be able to just use Fastify for what you want to achieve.
