### ISSUE TITLE
How to work with parsed structure from fastify-formbody?

### ISSUE THREAD

**Issue by yaneony** [fastify/help#653]
I was already looking around and google'd and was checking around how to properly work with the structure fastify-formbody deliver. 
As working with databases like MongoDB/RethinkDB I wonder how it could be processed? I've also seen the notice about "qs" library, but is that the only way to access nested array data by key?

Thanks!

**Comment by jsumners** [comment]
What is the question? The readme for the plugin clearly states that it provides facility for receiving `application/x-www-form-urlencoded` content. It also clearly states that it processes said form data into a plain JavaScript object.
