### ISSUE TITLE
attachFieldsToBody

### ISSUE THREAD

**Issue by SudoDios** [fastify/help#656]
Ho to upload file with enabled **attachFieldsToBody**?
pump is not work!!

**Comment by zekth** [comment]
Please provide a reproductible example of what you're trying to do.

**Comment by SudoDios** [comment]
i enable attachFieldsToBody to get fileds as body.
but Request.files is empty and can not be used.
```js
const parts = req.parts()
for await (const part of parts) {
        if (part.file) {
            await pump(part.file, fs.createWriteStream(part.filename))
        } else {
            console.log(part)
        }
}
```
**req.parts()** or req.files() is empty and not upload with pump
