### ISSUE TITLE
How register a plugin that has an asynchronous preHandler?

### ISSUE THREAD

**Issue by pramodhts** [fastify/help#66]
#### You have already researched for similiar issues?
Yes
#### What are you trying to achieve or the steps to reproduce?
I'm trying to forward the calls to another app using `fastify-reply-from`. Here is my sample plugin,

```js
function myPlugin(instance, options, next) {
  instance.addHook('preHandler', (request, reply, next) => {
    return Promise.resolve().then(() => {
     next()
    })
  })
  next()
}

```

and here is how I defined my routes,

```js
const fastifyReplyFrom = require('fastify-reply-from')
function routes (instance, options, next) {
  instance.register(myPlugin)
  instance.register(fastifyReplyFrom, { base: 'http://localhost:3001/' })
  instance.all('/ping/*', (request, reply) => {
    console.log('App ping')
   reply.from('/check')
  })
  next()
}

```

and  here is my app.js

```js
const fastify = require('fastify')
const app = fastify()
app.register(routes, { prefix: '/api' })

const start = async () => {
  try {
    await app.listen(3000)
    app.log.info(`server listening on ${app.server.address().port}`)
  } catch (err) {
    app.log.error(err)
    process.exit(1)
  }
}
start()
```

#### What was the result you received?

When I hit the `/ping` api I could see that its getting called twice, but, when I turn the `reply.from` to `reply.code(200).send((...))` i.e. when I remove forwarding I see it get hit only once. Not sure what i am doing wrong.
#### Context

* *node version*: 9.11.1
* *fastify version*: >=2.0.0
* *os*: Mac
* *fastify-plugin*: >=1.2.0
* *fastify-reply-from*: >=0.6.0

**Comment by nwoltman** [comment]
Your `preHandler` hook returns and Promise _and_ calls `next()`. You must choose only one. Doing both causes problems. There is a notice about this in the [hooks documentation](https://www.fastify.io/docs/latest/Hooks/).

**Comment by pramodhts** [comment]
Ah! my bad. Thanks @nwoltman.

Unfortunately that plugin is an external one built to work with express and fastify, with some asynchronous data base operation, and it calls next. Is there anyway to workaround that?

**Comment by nwoltman** [comment]
If possible, try wrapping that function that returns a promise and calls `next` with your own function that only does one of those things.

**Comment by pramodhts** [comment]
It works, thanks @nwoltman
