### ISSUE TITLE
Wildcard route

### ISSUE THREAD

**Issue by dnohr** [fastify/help#660]
#### You have already researched for similar issues?

Yes

#### What are you trying to achieve, or the steps to reproduce?

I'm trying to create this parametric route from the route, but only one of the URLs works.

```js
fastify.get('/:slug-test', async (req, res) => {
```

URL 1: /one-test = 200
URL 2: /one-two-test = 404
URL 3: /one-two-three-test = 404

Is there any way of supporting routes with the same ending "-test"?

Express does handle it, but not sure if Fastify's router supports it.

#### What was the result you received?

404 on multiple "-" url.

#### What did you expect?

All URLs should work returning under the same wildcard route.

#### Context

* *node version*: v17.8.0
* *fastify version*: v3.28.0
* *os*: Mac

**Comment by mcollina** [comment]
I'm sorry no one replied to this :(. Have you solved your problem?

**Comment by dnohr** [comment]
No worries, thanks for following up anyway @mcollina. I ended up using a modified version of the catch all route and then parsed for what I needed. I for sure would have preferred to be able to use the normal router with some regex, but couldn't make it work.

**Comment by dnohr** [comment]
This issue has been fixed since fastify v4.0.*, thanks!
