### ISSUE TITLE
To what extent is mixing callback & async/await plugin & hook formats problematic?

### ISSUE THREAD

**Issue by smallandsimple** [fastify/help#661]
## 💬  To what extent is mixing callback & async/await plugin & hook formats problematic?

In the Fastify docs section titled, ["Respond to a request from a hook"](https://www.fastify.io/docs/latest/Reference/Hooks/#respond-to-a-request-from-a-hook) there is a statement that says the following:

> It is important to **not mix callbacks and** `async`**/**`Promise`, otherwise the hook chain will be executed twice.

I would like some clarification on this.  Does this mean that a single Fastify plugin that adds hooks should only add one type of hook (i.e. async or callbacks) but not both?  Or does this mean that if a Fastify instance uses async hooks in one area, it should use them everywhere?  Or does it mean something else?

This is important because the implications also would seemingly apply to an application that uses core or third-party Fastify plugins.

**For example which plugins and/or combination of the below plugins are problematic?**
If you have some extra time, would you mind explaining why they cause a problem?
```js
fastify.register(fp((fastify, opts, done) => {
  fastify.addHook('onRequest', (request, reply, dn) => {
  // Some code
    dn()
  })
  done()
}))

fastify.register(fp( async (fastify, opts) => {
  fastify.addHook('onRequest', async (request, reply) => {
  // Some code
  })
}))

fastify.register(fp( async (fastify, opts) => {
  fastify.addHook('onRequest', (request, reply, dn) => {
  // Some code
    dn()
  })
}))

fastify.register(fp((fastify, opts, done) => {
  fastify.addHook('onRequest', async (request, reply) => {
  // Some code
  })
  done()
}))
````

## Your Environment

- *node version*: 16
- *fastify version*: >=3.x (newest)
- *os*: Mac, Linux

**Comment by climba03003** [comment]
> Does this mean that a single Fastify plugin that adds hooks should only add one type of hook (i.e. async or callbacks) but not both?

No, it means you should not mix it **inside** the hook.

> Or does this mean that if a Fastify instance uses async hooks in one area, it should use them everywhere?

No.

**Comment by smallandsimple** [comment]
> No, it means you should not mix it **inside** the hook.

I think I understand, but just to be sure, could you provide an example of **what not to do** (or just confirm the below)?
Is this what we shouldn't do?
````
fastify.addHook('onRequest', (request, reply, done) => {
  new Promise((resolve, reject) => {
    // Do Stuff
    await someFunction()
    done()
  })
})
````

Or perhaps this is what we shouldn't do?
````
fastify.addHook('onRequest', async (request, reply, done) => {
    // Do Stuff
    await someFunction()
    done()
})
````

Or perhaps we should avoid them both?
What exactly would cause the hook chain to be executed twice?

**Comment by climba03003** [comment]
1. return `Promise` inside `callback` hook, then execute `done` later. Mostly occur in database operation.

```js
const { setTimeout } = require('timers/promises')
fastify.addHook('onRequest', function (request, reply, done) {
  return setTimeout(500).then(done, done)
})
```

2. `async-await` and execute `done` inside.

```js
const { setTimeout } = require('timers/promises')
fastify.addHook('onRequest', async function (request, reply, done) {
  await setTimeout(500)
  done()
})
```
