### ISSUE TITLE
How can I parse all JSON ISODate strings (ref 8601 / 3339) into Date objects?

### ISSUE THREAD

**Issue by smallandsimple** [fastify/help#662]
## 💬  How can I parse all JSON ISODate strings (ref 8601 / 3339) into Date objects?

I frequently send dates between the Client and API.  Moving to Fastify has been great, but working with dates has me a bit tripped up.  
When I have dates coming in as strings like `2019-10-12T07:20:50.52Z`, I need to be able to validate them with the Fastify AJV instance and have them ready as date objects in the `request.body`.

My only idea for how to do this by default on every route is to write a `preHandler` hook to traverse the entire `request.body` and do a regex against all string values and converting those that match the ISOString format to dates.  That said, it seems like this should be an option already included in Fastify since I would imagine working with dates is common.  Also, it is a required step when saving a user input date into MongoDB and expecting the date to be a true ISODate format in the database.

Is something like this the only option currently available?
```js
fastify.addHook('preHandler', (req, reply) => {
    // Traverse req.body and find all strings that match ISODate string format
    // and replace them with new Date(isoDateString) 
})
````

## MEAN Stack

- *node version*: 16
- *fastify version*: >=3.x (latest)
- *os*: Mac, Linux

**Comment by climba03003** [comment]
Your assumptions is all the people is using MongoDB with fastify, but this is not the case.

It would be a good plugin for auto transform request body, but not a good internal function. The main reason is the function need to loop through all the property which is slow.

**Comment by smallandsimple** [comment]
> Your assumptions is all the people is using MongoDB with fastify, but this is not the case.

Well, I wasn't assuming that.  I was assuming that even if people don't use MongoDB, many will still need to work with dates.
If they do, it would be nice if there was an option that could be passed to Fastify to enable automatic date parsing, but I think a plugin could also work.

Perhaps I will write it. :-)

**Comment by climba03003** [comment]
Here is the function to do what you want.
```js
const regexp = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2}(?:\.\d*)?)((-(\d{2}):(\d{2})|Z)?)$/
function isISO8601Date (value) {
  return typeof value === 'string' && regexp.test(value)
}

function parseISO8601Date(body) {
  if(Array.isArray(body)) {
    return body.map(parseISO8601Date)
  } else if(typeof body === 'object' && body !== null) {
    for(const key of Object.keys(body)) {
      body[key] = parseISO8601Date(body[key])
    }
    return body
  } else if (isISO8601Date(body)) {
    return new Date(body)
  } else {
    return body
  }
}

fastify.addHook('preHandler', function(request, _, done) {
  request.body = parseISO8601Date(request.body)
})
```

Most of the time I would just cast it straightly.
```js
fastify.post('/', {}, function(request, reply) {
  // since I validate the body, it must be a iso date
  if(request.body.date) request.body.date = new Date(request.body.date)
  // db operation
  // ...
  return reply.code(200).send('ok')
})
```

**Comment by arthurfiorette** [comment]
@climba03003, Coming here for the same problem, there's any way to make it work with dates for http input in schematized routes?

All my routes has full schema properties, how can I add some postValidation hook for all routes?

Also, any libraries that does that with json schema configuration, like `fast-json-stringify` but like _fast-json-parse_?

**Comment by arthurfiorette** [comment]
My date fields are currently the following:

```js
{
  type: 'string',
  format: 'date-time'
}
```

**Comment by jsumners** [comment]
Parsing dates is an application detail. The validator should be used to validate the incoming data matches the requirements, and then that data should be parsed into its correct representation:

https://runkit.com/embed/s4scbxol70j3

```js
const Ajv = require("ajv")
const addFormats = require("ajv-formats")

const ajv = new Ajv()
addFormats(ajv)

const schema = {
  type: "object",
  properties: {
    foo: {type: "string", format: "date-time"},
  }
}
const validate = ajv.compile(schema)

const data = {foo: "2023-01-31T08:30:00.000-05:00"}
const valid = validate(data)
console.log("valid:", valid)

const date = new Date(data.foo)
console.log("date:", date)
```
