### ISSUE TITLE
Hostname using docker

### ISSUE THREAD

**Issue by TanguyOS** [fastify/help#666]
#### What are you trying to achieve, or the steps to reproduce?

I have dockerize a complexe application in which I have a fastify server listening to 0.0.0.0:3080, port are open in my container. The problem is, If I want to send requests to that server, I have to use the hostname that it generates in the logs (with logger:true), and that hostname is regenerated each time I use docker-composer up.

This server should only be available internally for my PHP web server to generate the HTML of my react app.
I absolutely need to freeze the hostname to something that won't change.

```js
import Fastify from 'fastify'

const fastify = Fastify({
  logger: true
})

fastify.listen(3080, "0.0.0.0", (err, address) => {
  console.log(`Server is running at ${address}`)
  if (err) throw err
})
```

```json
{"level":30,"time":1650268518693,"pid":295,"hostname":"f4136a455784","msg":"Server listening at http://0.0.0.0:3080"}
```

```php
<?php

 try {
    // Works
    $http = new HTTP("http://f4136a455784:3080");
    $ssr = $http->post('/render, $data);
    $ssr = $ssr["body"];
} catch (Exception $e) {
    $ssr = null;
}
```

#### What was the result you received?

"hostname":"f4136a455784" is the only way to send requests to the fastify server, but it generate a new one at each docker-composer up.

#### What did you expect?

I need the hostname to never change, or to be localhost:3080, something that I can configure once for every environment.

#### Context

* *node version*: v16.3.0
* *fastify version*:  "^3.24.0",
* *os*: alpine / docker
* *any other relevant information*: Fastify has its own docker container, the PHP app is in an other one.

**Comment by zekth** [comment]
This is related to your docker-compose config. You should use internal docker-compose dns.

See: https://docs.docker.com/compose/networking/

https://syntaxfix.com/question/5764/how-do-i-set-hostname-in-docker-compose

**Comment by TanguyOS** [comment]
That's right, problem solved, Thanks for the help 👍🏻
