### ISSUE TITLE
Is it possible to ignore fastify plugin version incompatibility errors?

### ISSUE THREAD

**Issue by EduardsE** [fastify/help#668]
I'm new to fastify. I'm often running into FastifyError: fastify-plugin: fastify-cookie - expected '>=3' fastify version, '4.0.0-alpha.3' is installed and similar errors. I know I could just use v3, but I like trying the latest stuff. And a lot of plugins for v3 would likely work with v4, but fastify won't let me try.  Is there a way to supress these errors?

**Comment by L2jLiga** [comment]
At least it's possible to override supported version

```javascript
fastifySession[Symbol.for('plugin-meta')].fastify = '^4.0.0-alpha.0';
```

**Comment by EduardsE** [comment]
@L2jLiga works great! Thank you!
