### ISSUE TITLE
Unable to download a sent file with fastify

### ISSUE THREAD

**Issue by mkhoussid** [fastify/help#669]
I have a simple endpoint as follows:

```js
fastify.get('/generate', async (request, reply) => {
     console.log('endpoint hit'); // this line is printed

     const filePath = path.join(__dirname, '..', '..', 'scripts', 'my_script.sql');

     reply.sendFile(filePath, 'scripts');
})
```
This just sends the contents of the `sql` file in text form like so:

<img width="821" alt="Screenshot 2022-05-04 at 20 42 29" src="https://user-images.githubusercontent.com/44326107/166747779-55fb5125-a632-481e-8b52-fd889bcc910a.png">

I know that [express](https://expressjs.com/en/api.html) has a `res.download` method, but I couldn't find an analog with fastify.

What am I doing wrong here? How can I download this file?

**Comment by Stepashka20** [comment]
I have the same problem.... How to send file to client? I got an error: `TypeError: res.sendFile is not a function`

**Comment by mkhoussid** [comment]
> I have the same problem.... How to send file to client? I got an error: `TypeError: res.sendFile is not a function`

I can't recall how I ended up fixing this, but try [this SO answer](https://stackoverflow.com/a/77517077/2891356) if you haven't already.
