### ISSUE TITLE
Why am I getting 415 Unsupported type even after trying addContentTypeParser or fastify-multipart?

### ISSUE THREAD

**Issue by pramodhts** [fastify/help#67]
#### You have already researched for similar issues?
Yes
#### What are you trying to achieve or the steps to reproduce?

I'm trying to send a media (png) file to another application using `fastify-reply-from` i.e. forwarding the request to another application. When I don't  have a contentParser i see the below error,

```
{
  "statusCode": 415,
  "code": "FST_ERR_CTP_INVALID_MEDIA_TYPE",
  "error": "Unsupported Media Type",
  "message": "FST_ERR_CTP_INVALID_MEDIA_TYPE: Unsupported Media Type: multipart/form-data; boundary=----WebKitFormBoundaryiiCB"
}
```

this make sense because I do not have one for `multipart/form-data`.

But, after adding one I get `socket hang up`, its not even forwarding the request. Here is how I set the contentParser

```
const Multipart = Symbol('multipart') 
fastify.addContentTypeParser('multipart', (request, done) => {
 request[Multipart] = true
  done()
})

```

and here are the request headers

```
"x-forwarded-for": "11.6.9.11",
"content-length": "57426",
"user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36",
"content-type": "multipart/form-data; boundary=----WebKitFormBoundaryiiCB",
"accept": "*/*",
"accept-encoding": "gzip, deflate",
```

**Comment by Eomm** [comment]
Did you tried to set the request header like this:

`"content-type": "multipart/form-data" `?

**Comment by chendoron** [comment]
Yes, we've tried `'*'` as well

**Comment by Eomm** [comment]
Could you give me a complete example of your setup?
In this way I can understand the problem and help you to solve 👍🏼

Because in your actual example the content parser you have added it is not reading the file stream and the "done" function is expecting the body object as second parameter

**Comment by pramodhts** [comment]
The scenario we're dealing with is a POST request with a multipart/form-data content type.
We're trying to do the least alterations to the original request and simply pipe/forward the request as a pure proxy, in that case should the below do the job?

```js
fastify.addContentTypeParser('*', function (req, done) {
  done()
})
```

We've added that piece of code to the beginning of our "router" and it doesn't seem to make any different beside helping us get past the FST_ERR_CTP_INVALID_MEDIA_TYPE error.

**Comment by nwoltman** [comment]
Digging into the `fastify-reply-from` [code](https://github.com/fastify/fastify-reply-from/blob/master/index.js) a bit, it looks like it might work if you call `done` like this in your custom content type parser:

```js
done(null, req)
```

That way, `req` (the incoming request stream) will get set to `request.body`, which will hopefully be forwarded by `fastify-reply-from` (with [this code](https://github.com/fastify/fastify-reply-from/blob/fbf81e848c206ee0a567054e06447c92e45037be/index.js#L62-L63)).

**Comment by pramodhts** [comment]
Thanks @nwoltman. It works

**Comment by chendoron** [comment]
@nwoltman 
Thanks! This solved our problem.
Our endpoints are showing green!
