### ISSUE TITLE
Performance between using `onRequest` vs `decorateRequest`

### ISSUE THREAD

**Issue by mkhoussid** [fastify/help#671]
Trying to figure out which approach yields higher performance, when comparing two ways of connecting to a Postgres database.

The first approach is using the `onRequest` hook:

Consider the below:
```
import { Client } from 'pg';

const client = new Client({
	user: process.env.POSTGRES_USER,
	password: process.env.POSTGRES_PASSWORD,
	host: process.env.POSTGRES_SERVICE,
	port: process.env.POSTGRES_PORT,
	database: process.env.POSTGRES_DB,
});
```
First approach:
```
app.addHook('onRequest', (request, reply, done) => {
	try {
		request.db = { client };

		done();
	} catch (err) {}
});
```
Second approach:
```
app.decorateRequest('db', function () {
	return { client };
});
```
Is the second approach faster, because the extra call to the `onRequest` is not made for every request sent to the server?

I'd imagine that using `decorateRequest` on server start once would be faster.

**Comment by Asjas** [comment]
The `onRequest` hook is mutating the `request` object for every request, which causes `v8` to de-optimize the `request` object. It can create a big performance loss. 🙂

`decorateRequests` will create the initial `request` object with any custom properties, so you never mutate the `request` object during any time and you can't cause the same performance issue.

As quoted from the docs: 

> Decorating core objects with this API allows the underlying JavaScript engine to optimize the handling of server, request, and reply objects. This is accomplished by defining the shape of all such object instances before they are instantiated and used.

https://www.fastify.io/docs/latest/Reference/Decorators/
