### ISSUE TITLE
Use compiled schemas outside of req and res use cases

### ISSUE THREAD

**Issue by manuelreil** [fastify/help#675]
### Situation
- I understand I can add schemas via `addSchema` and retrieve them as well by hand for other use cases than req validation and res serialization (`getSchema`).
- I would like to use these features for use cases outside of the input and output scenarios, e.g. for schema validation before I persist in MongoDB, before sending to AWS Eventbridge, SQS, etc.

### Complication
- I can create a custom instance of AJV, use `getSchema` and then compile it to a validator using this custom instance of AJV.
- This drives me into building a "registry" that stores those compiled validators, similar like Fastify does it for the req and res use cases. However, this duplication feels odd.

### Questions
- Can I somehow access the fastify instance of AJV ("decorated") so that I can avoid creating AJV instances in several places?
- Have I missed it somehow that `addSchema` actually does compile (haven't found an indication for this in code) and therefore I could retrieve a compiled one already somehow? Or trigger compilation somehow?

## Your Environment

- *node version*: 16
- *fastify version*: ^3.29.0
- *os*: Mac

**Comment by climba03003** [comment]
I think it is a duplicate feature request of https://github.com/fastify/fastify/issues/3897
If it is not, please ping me or reopen it yourself.
