### ISSUE TITLE
How to pass options into the app?

### ISSUE THREAD

**Issue by florianb** [fastify/help#68]
I'm just at the first steps playing around with Fastify. In fact i'm trying to follow the steps in the Getting Started-section of the docs. I wrote my first little plugin connecting to the database.

My plugin expects some options to be passed and since i kept the autogenerated code of the fastify-cli the plugins are being autoloaded from the corresponding folder as the copied snippet below shows. I'd like to ask where the `opts` come from and where it is possible to pass configuration-options into the server?

I already searched my way through the documentation and even tried to figure it out reading the fastify and fastify-cli-code - probably anybody has just the answer available..

```js
module.exports = function (fastify, opts, next) {
  // ...
  fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'plugins'),
    options: Object.assign({}, opts)
  // ...
```

#### Context

* *node version*: v11.9.0
* *fastify version*: >=2.0.0
* *os*: Linux

**Comment by delvedor** [comment]
You can store inside an `.env` file all of your options, then `fastify-cli` will automatically load them for you.
Finally, you can access them via `process.env.YOUR_OPTION_NAME`.

**Comment by florianb** [comment]
Thank you @delvedor! I pointed me to the fastify-cli, i was constantly running it via `npm run dev`. :cake:
