### ISSUE TITLE
How to return empty response using async-await?

### ISSUE THREAD

**Issue by gustavotoyota** [fastify/help#680]
I was expecting this to give an empty response:
```
fastify.post('/', async (request) => {
  await SomeAsyncFunction();
})
```
But I'm getting this error: `Promise may not be fulfilled with 'undefined' when statusCode is not 204`

I'm doing it this way for now:
```
const EMPTY_RESPONSE = {};

fastify.post('/', async (request) => {
  await SomeAsyncFunction();
  return EMPTY_RESPONSE;
})
```
How to return an empty response (204) with async-await style?

**Comment by RafaelGSS** [comment]
```js
fastify.post('/', async (request, reply) => {
  await SomeAsyncFunction();
  reply.send(204);
})
```

it should be enough

**Comment by jsumners** [comment]
Return the reply object.

**Comment by mcollina** [comment]
This will change in Fastify v4 and work as you intended.
