### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by michail-vestnik** [fastify/help#681]
Hi! 

There are already 100500 frameworks for node.js, why make another one? 
There are a lot of people who don't like ~~foul-smelling~~ node_modules! 
Will there be support for Deno?

![public](https://user-images.githubusercontent.com/87961969/169626179-84bf054f-0a55-49e8-b0e5-5ff0de15bb45.png)

**Comment by Eomm** [comment]
Duplicated https://github.com/fastify/fastify/issues/2173
