### ISSUE TITLE
[Decorator] Should an object be passed using a function?

### ISSUE THREAD

**Issue by budarin** [fastify/help#684]
For example: if I want to decorate a request with a property that is a plain object should I provide access to it only through a function that returns this object to prevent sharing this object by reference?

```js
fastifyInstance.decorateRequest('getCalcData', () => {});
...
fastifyInstance.addHook('onRequest', (req, res, done) => {
   const calculatedObject = caclculateDtatOnRequest(req);
   req.getCalcData = () => calculatedObject;
   done();
}
```

Otherwise, if I just assign an object, I get a warning that the object is used by reference
```js
fastifyInstance.decorateRequest('calcData', {});
...
fastifyInstance.addHook('onRequest', (req, res, done) => {
   const calculatedObject = caclculateDtatOnRequest(req);
   req.calcData = calculatedObject;
   done();
}
```

Unfortunately, this point is not sufficiently covered in the documentation

**Comment by climba03003** [comment]
I don't understand which part is not enough. The example already there.
![image](https://user-images.githubusercontent.com/23028015/170676587-f525b4ba-3a83-4fef-9288-77af7456aca9.png)

**Comment by budarin** [comment]
If you follow the part of the documentation that you presented, I get a warning that the object is shared by reference, that's why I have a question

**Comment by climba03003** [comment]
> If you follow the part of the documentation that you presented, I get a warning that the object is shared by reference, that's why I have a question

I don't see an error when I follow it. This is the part which tell you the proper way to do it.
```js
import Fastify from "fastify";
const fastify = Fastify();

fastify.decorateRequest("foo", null);
fastify.addHook("onRequest", function (request, _, done) {
  request.foo = { hello: "world" };
  done();
});

await fastify.ready();
```

**Comment by budarin** [comment]
I realized what my problem is - I'm not setting a null value in the decorator, but an object with keys equal to null - v8 recommends not changing the structure of objects for better performance, but only changing the value of keys
Am I wrong?

**Comment by climba03003** [comment]
> I realized what my problem is - I'm not setting a null value in the decorator, but an object with keys equal to null

Yes, you do not actually follow the document. Then, it pop up the warning.

> v8 recommends not changing the structure of objects for better performance (from null to object in my case), but only changing the value of keys

It is actually a property of `Request`. So, it acceptable to be `null` and then change to `object` since `null` is `object`.

**Comment by budarin** [comment]
For beginners, I would go into more detail on why it is necessary to set null in the decorator and the value in the onRequest handler - it's not very clear right away

**Comment by climba03003** [comment]
> For beginners, I would go into more detail on why it is necessary to set null in the decorator and the value in the onRequest handler - it's not very clear right away

`decorator` is actually keep the same shape for `Fastify Instance`, `Fastify Request` and `Fastify Response`.

I don't think it is possible to keep the same shape for the user defined nested object. 
And it is not say that most of the nested object is computed from input.

The reason behind for `null` is very simple.
`object` in JavaScript is reference by `reference`. So, `.decorateRequest(foo, {})` actually share the same reference of `{}`.
That is stated in document `any mutation will impact all requests, potentially creating security vulnerabilities or memory leaks.`

When it using `null`, the property here will initialize as `null` and prevent the same reference problem.
Since, each request is initialize the property as `null`. And they share the same shape as `object`.

**Comment by climba03003** [comment]
If you need even more detail. I recommend you to dig through the codebase.
It is the fastest way to understand why it should be. 
And raise a question in any part you don't understand.

**Comment by budarin** [comment]
and can I take this detailed explanation straight and put it in the documentation? :)
