### ISSUE TITLE
Allow to use `@fastify/static` with a params constraint

### ISSUE THREAD

**Issue by christian-bromann** [fastify/help#685]
#### You have already researched for similar issues?
I have searched through the docs and issues without success.

#### What are you trying to achieve, or the steps to reproduce?

If my server gets the following request:
```
curl http://localhost:3000/static/mount/src/index.ts
```
it should respond with the file content in `<root>/static/mount/src/index.ts`. However if the request is:
```
curl http://localhost:3000/static/mount/src/index.ts?stat
```

I want to run my own handler. So basically if there is a `stat` parameter I don't want to use the static middleware but my own custom one.

#### What was the result you received?

I have issues using `@fastify/static` and a custom handler for the same endpoint.

#### What did you expect?

I remember in ExpressJS you could have middlewares that either respond early or pass the request on to e.g. a static middleware. Is something similar possible?

#### Context

* *node version*: 16
* *fastify version*: >=0.37.0
* *os*: Mac, Windows
* *any other relevant information*:

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by mcollina** [comment]
You can define a preHandler hook.

**Comment by christian-bromann** [comment]
Yup, that is what I ended up doing. Thanks for clarifying.
