### ISSUE TITLE
[reply.send] Clarification about sending JSON strings

### ISSUE THREAD

**Issue by budarin** [fastify/help#686]
>If you set the Content-Type header and pass a string to send, it will be serialized with the custom serializer if one is set, otherwise, it will be sent unmodified (unless the Content-Type header is set to application/json; charset=utf-8, in which case it will be JSON-serialized like an object — see the section above).

Does this mean that if I execute the following code

```js
reply
    .type('application/json; charset=utf-8')
    .send('{ "hello": "world" }')
```
the string will be converted to JSON at first, and then the JSON is serialized to a string again using a serializer?

**Comment by mcollina** [comment]
Have you run the code? What does the code do?

**Comment by budarin** [comment]
a typo in the code  does not change the essence of the issue - the documentation does not describe clearly enough what happens when a string with an content-type equal to application/json is sent

**Comment by jsumners** [comment]
No one mentioned anything about a typo. The question was if you had tried the example to see what the result is.

**Comment by budarin** [comment]
> No one mentioned anything about a typo. The question was if you had tried the example to see what the result is.

the result is `{ "hello": "world" }`

**Comment by mcollina** [comment]
It seems the string is sent unmodified, like the doc said.

**Comment by budarin** [comment]
>  in which case it will be **JSON-serialized** like an object 

what does it mean?

**Comment by jsumners** [comment]
The purpose of the exercise was so you could see what actually happens and determine if the docs are accurate. I'd say things are working as advertised based upon the information you have posted. A string is a valid JSON representation, as are all supported primitives; see https://www.rfc-editor.org/rfc/rfc8259. 

If you find that the docs are inaccurate, please submit a PR to correct them.

**Comment by budarin** [comment]
Don't get me wrong - I'm not finding fault, I'm just reading the documentation and trying to figure out how it works, but this place in the documentation is written very tricky, so I asked to clarify it

By now I have found out the essence - the string is being forwarded without changes!
