### ISSUE TITLE
Fallback from @fastify/static to @fastify/http-proxy, *already declared for route* error

### ISSUE THREAD

**Issue by manelio** [fastify/help#688]
I'm sure this must be easy, but I'm struggling with how to get these two plugins work together:

```
import httpProxy from '@fastify/http-proxy'
import httpStatic from '@fastify/static'

// ...

app.register(httpStatic, {
  root: path.join(process.cwd(), 'public'),
})

app.register(httpProxy, {
  upstream: 'http://localhost:8080/',
})
```

This code fails with an error `Method 'GET' already declared for route '/*' with constraints '{}'`

The logic behind is: if a URL can't be served from statics folder, proxy the request.

I have seen examples of how to use `setNotFoundHandler`, but the answers are always a simple *if not found, send this file*. What I want is the request to be handled by the next plugin, as how it works with middlewares.

Thanks in advance.

**Comment by mcollina** [comment]
> What I want is the request to be handled by the next plugin, as how it works with middlewares.

That's not how Fastify works. Fastify uses deterministic routing. 
You can achieve your goal by specifying the `wildcard: false` flag in `@fastify/static` (see https://github.com/fastify/fastify-static#wildcard)

**Comment by manelio** [comment]
Thanks for your response.

But `wildcard: false` in `@fastify/static` has two implications:

- Amount of static assets is potentially huge, so globbing them and create routes could mean an unnecessary waste of memory and resources.
- New files in public folder won't be taken into account

Deterministing routing should not be a barrier for implementing some kind of failback or chain-if-not-found procedure. I find it rather odd.

I'll keep investigating (I switched to fastify from express few days ago).

Thanks,
