### ISSUE TITLE
Need help with using arrays with fastify-swagger using OAS3

### ISSUE THREAD

**Issue by varunkamra** [fastify/help#689]
#### You have already researched for similar issues?
Yes.

#### What are you trying to achieve, or the steps to reproduce?

Need to be able to use arrays and be able to pass a single value from swagger request using Open API 3 spec with fastify-swagger.
Following is the property name being used in querystring:

```js
     names: {
        type: "array",
        uniqueItems: true,
        items: {
          type: "string",
          default: "John Doe",
        },
      },
```

#### What was the result you received?

When on only one value is given in swagger request I get an error saying "querystring.names should be array"

#### What did you expect?

swagger API request executed successfully.

#### Context

* *node version*: v14.19.3
* *fastify version*: >=3.29.0
* *os*: Ubuntu 20.04

**Comment by climba03003** [comment]
Please use a custom querystring parser.
By default, `querystring` do not support array.

**Comment by kibertoad** [comment]
This is weird. fastify  + ajv support parsing arrays just fine, with correct flag in the options

**Comment by climba03003** [comment]
> This is weird. fastify + ajv support parsing arrays just fine, with correct flag in the options

You need custom `querystring` parser anyway.

`querystring.parse` only treats same name for `array`. 
If you want to follow some standard like `names[]=foo&names[]=bar`.
It will be parsed as `{ "names[]": ["foo", "bar"] }`

**Comment by kibertoad** [comment]
Yup, that's true.
it's not a standard, though, just one of several conventions out in the wild. I don't think array format is standardized anywhere in http

**Comment by varunkamra** [comment]
@climba03003 @kibertoad thank you! I actually figured out how to fix it. I followed these docs:
https://www.fastify.io/docs/latest/Reference/Validation-and-Serialization/
https://www.fastify.io/docs/latest/Reference/Server/#ajv

I ended up using this config for creating my server instance:

```
export const server = fastify({
  logger: true,
  ajv: {
    customOptions: {
      removeAdditional: true,
      useDefaults: true,
      coerceTypes: "array",
      allErrors: false,
    },
  },
});
```

Now it is working fine. I will close this issue.
