### ISSUE TITLE
async on handler from plugin

### ISSUE THREAD

**Issue by panitaxx** [fastify/help#69]
Hello, 

I am trying to add an async onrequest handler via a plugin. If it throws it goes ok but if it goes ok it hangs the request.  am I missing something?

```js
const fp = require('fastify-plugin');
const fastify = require('fastify');
const request = require('request');

function testPluginFactory(){

  async function handler(req,rep){
    console.log('handling');
    await Promise.resolve();
    return;
  }

  return handler;
}

function plugin (fastify, options, next) {
  fastify.addHook('onRequest', testPluginFactory());
  next();
}
const testPlugin = fp(plugin,{});

const app = fastify();
app.get('/',()=>({hello: 'world'}));
app.register(testPlugin,{});
app.listen(3030).then(()=>{
  request.get('http://127.0.0.1:3030',function(err,resp,body ){
    console.error('err',error);
    console.log('resp',resp);
    console.log('body',body);
  })
});
```

#### What was the result you received?

hangs. no result

#### What did you expect?

body should send test json 

#### Context

* *node version*:  10.15.0
* *fastify version*: 2.1.0
* *os*: Mac
* *any other relevant information*:

    "fastify-plugin": "1.5.0",
    "request": "^2.88.0"

**Comment by mcollina** [comment]
You either have to declare your handler as async, or call `reply.send()`. You should do:

```
app.get('/', async ()=> {
  return {hello: 'world'}
});
```

**Comment by panitaxx** [comment]
thanks. great work.
