### ISSUE TITLE
How to add CORS to single routes?

### ISSUE THREAD

**Issue by PierBover** [fastify/help#690]
I'm trying to add CORS to just a couple of routes of my app.

Apparently the way to do it with `@fastify/cors` is to use plugin encapsulation but when I add this to more than one plugin:

```
	app.register(
		corsPlugin,
		{
			origin: '*',
			methods: ['GET']
		}
	);
```

I get this error:

```
AssertionError [ERR_ASSERTION]: Method 'OPTIONS' already declared for route '/*' with constraints '{}'
```

Is this a bug or am I doing something wrong?

Edit:

I'm also using the static plugin. I've tried completely disabling it just in case but the error persists.

**Comment by jsumners** [comment]
https://www.fastify.io/docs/latest/Reference/Encapsulation/

**Comment by PierBover** [comment]
> https://www.fastify.io/docs/latest/Reference/Encapsulation/

Yes, that's what I'm doing.

**Comment by mcollina** [comment]
Can you please include a full example to reproduce?

**Comment by PierBover** [comment]
Hey @mcollina 

I was hoping there was something very obvious I was doing wrong :)

I will try to create a repro.

**Comment by mcollina** [comment]
> I was hoping there was something very obvious I was doing wrong :)

That's likely, it's just that I don't know what :)

**Comment by mcollina** [comment]
Ah I understand the problem now.
This use case is not supported by fastify-cors, but it would be great to add support for it.

I would do:

```
const fastify = require('fastify')({ logger: true });
const cors = require('@fastify/cors');

fastify.register((app, options, next) => {

    app.get('/', (request, response) => {
        response.send('no cors!')
    });

    next();
});


fastify.register((app, options, next) => {

    app.register(cors, {origin: '*'});

    app.get('/', (request, response) => {
        response.send('cors!')
    });

    next();
}, { prefix: '/cors' });

fastify.register((app, options, next) => {

    app.register(cors, {origin: '*'});

    app.get('/', (request, response) => {
        response.send('cors two!')
    });

    next();
}, { prefix: '/cors-two' });
```

**Comment by PierBover** [comment]
Thanks @mcollina I will try to make that work with the autoloader plugin!
