### ISSUE TITLE
Skipping a key when serializing response

### ISSUE THREAD

**Issue by avin-kavish** [fastify/help#696]
With `JSON.stringify()`, it is possible to skip certain keys by passing a function as the second argument to it. I.e,

```ts
function replacer(key, value)
{
    if (key == "key") return undefined
    else return value
}

JSON.stringify(x, replacer)
```

Is it possible to achieve this in fastify while using `fast-json-stringify` ?

I know I can set the serializer compiler like below to get the functionality,
```ts
fastify.setSerializerCompiler(({ schema, method, url, httpStatus }) => {
  return data => JSON.stringify(data, replacer)
})
```
I'm trying to avoid this because it would lose me the benefits of `fast-json-stringify`.

**Comment by metcoder95** [comment]
Hi! Not by exactly passing a function but here it heavily depends on your response schema you’re providing. If using the default AJV instance from Fastify, without touching the default options as well, such key will be stripped in-auto if you response schema doesn’t contain such key.

e.g.
```js
const schema = {
    type: 'object',
    properties: {
        want: { type: 'string' }
    }
}

fastify.get('/', { schema: {
    responses: {
        '2xx': schema
    }
}}, (req, reply) => {
    reply.send({
        want: 'this',
        not: 'this'
    })
})

const result = await fastify.inject({
    path: '/',
    method: 'GET'
})

console.log(result.payload) // { want: 'this' }
```

If you want to trick this even more, I suggest you to provide a custom Serializer through the SchemaController settings.

**Comment by avin-kavish** [comment]
I want it to work with `additionalProperties: true`

**Comment by avin-kavish** [comment]
Okay! Is it possible to pass a function like that to `fast-json-stringify`?

**Comment by mcollina** [comment]
It's not possible to do so. fast-json-stringify rely on schemas.
