### ISSUE TITLE
Child parent routes like expressjs

### ISSUE THREAD

**Issue by arihantdaga** [fastify/help#7]
I am new to fastify and trying to migrate an existing expressjs project to fastify. 
I Read the doumentation but i could not figure out how to use parent child routing su=ystem here for example in our expressjs file this is how i used to write - 

File users.js
```
const express = require('express');
const router = express.Router();
router.get('/list', function (req, res, next) {
// Send Users List Logic Here.
});
...
More Routes Related to user goes here
module.exports = router;

```
And in the api file
File - api.js 

```
var users = require("./users");
var books = require("./books");

app.use("/api/v1/users", users);
app.use("/api/v1/books", books);
```

For the same thing i could not find an example in fastify. In fastify i see that routes can be declared only on fastify instance. Can someone help me out here with a small example or point me in right direction ?

**Comment by arihantdaga** [comment]
@delvedor Thank you very much.

**Comment by delvedor** [comment]
You're welcome!
If you have any other question we are here :)
