### ISSUE TITLE
how i can make a crud with fastify and react?

### ISSUE THREAD

**Issue by sanaeefar-saeed** [fastify/help#70]
I need to create a react app that uses an API that made with fastify for Doing CRUD.

**Comment by Ethan-Arrowood** [comment]
These are two separate things. Your React app is considered the frontend and Fastify is considered your backend. There are many ways to develop full stack applications and in my experience you have 2 options:
1. Deploy each separately. In your React app you would use something like `fetch` or `axios` to make standard HTTP requests to your Fastify server
2. Host your React App from your Fastify instance using `fastify/fastify-static` and then make the requests to the same server

I'd encourage you to research full stack architecture to learn more. Some resources I've found useful include the [Auth0 blogs](https://auth0.com/blog/developers/).
