### ISSUE TITLE
[fluent-json-schema] Specify a property that SHOULD BE a valid JSONSchema

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [fastify/help#705]
## 💬  Question here 

Is there any way to validate a JSON Schema with fluent-json-schema? I have a parameter that should be structured as a JSON Schema, is there any way to specify that the parameter should be a valid json schema?

**Comment by Eomm** [comment]
fluent-json-schema is not a schema validator, but it is a schema builder.

I would just download the official `JSON schema` meta-schemas form https://json-schema.org/specification-links.html
Then you can provide this schema to ajv and validate your input schema object
