### ISSUE TITLE
When using `@fastify/express`, how do I give fastify routes priority?

### ISSUE THREAD

**Issue by dsbudiac** [fastify/help#708]
## 💬  When using `@fastify/express`, how do I give fastify routes priority?

I'm migrating my app from express to fastify and using the `@fastify/express` plugin. I'm moving routes over as I can... is there a way to give the fastify router priority over my express router?

```ts
import fastify from 'fastify'
import plugin  from '@fastify/express'
import express from 'express'

const server = fastify({ logger: true })
const router = express.Router();

server.get('/my-route', (req, res) => 'from fastify')
router.get('/my-route', (req, res) => res.send('from express'))

async function start() {

  await server.register(plugin)
  server.use(router)

  await server.listen({ port: 4000 })

}

start()
```

In the above code, the express router will always respond for the `/my-route`.

Obviously I should just kill the old route when migrating. But it would be helpful to have a way to give priority to the new one... or check the fastify router for any duplicates.

---

- *node version*: 18.4
- *fastify version*:4.1
- *os*: Mac

**Comment by mcollina** [comment]
That's not possible. Just remove the express routes from your code.
