### ISSUE TITLE
File size too large. Got X. Maximum is Y. Setting bodyLimit is not working.

### ISSUE THREAD

**Issue by thatanjan** [fastify/help#710]
I have built an Image uploader with React and Node.js(fastify). 
I sent the image from the front end in a base64 format to my node server. I have set the body limit like this.

```js
import fastify from 'fastify'
import { config } from 'dotenv'
import { v2 as cloudinary } from 'cloudinary'
import fastifyCors from '@fastify/cors'

config()

const app = fastify({
	logger: true,
	bodyLimit: 52428800, // 50mb
})
````

When I try to upload less than 10MB, it works fine. If the file size is more than 10MB it gives me the following error. 

```js
{
  message: 'File size too large. Got 16613234. Maximum is 10485760.',
  name: 'Error',
  http_code: 400
}
```

The full Source Code is in the following repo.
[Github Repo](https://github.com/thatanjan/react-uploader-demo)
[server file](https://github.com/thatanjan/react-uploader-demo/blob/main/server/src/index.js)

## Your Environment

- *node version*: v16.15.1
- *fastify version*: ^4.0.2
- *os*: Linux

**Comment by Eomm** [comment]
Fastify replies with 413, not 400 when the body limit is hit

I would suggest to check the `cloudinary` config and adding some logs to your the server

**Comment by thatanjan** [comment]
Sorry, my bad. Cloudinary is throwing the error because I can not upload content more than 10MB on the free plan.
