### ISSUE TITLE
FastifyError: fastify-plugin: fastify-static - expected '3.x' fastify version, '4.2.0' is installed

### ISSUE THREAD

**Issue by guerrap** [fastify/help#712]
## 💬  Question here 

After upgrading to fastify `4.2.0` I get this error:

`FastifyError: fastify-plugin: fastify-static - expected '3.x' fastify version, '4.2.0' is installed`

Even though I'm not using the `fastify-static` nor I have the dependency installed.
What could be the cause?

## Your Environment

- *node version*: 16
- *fastify version*: >=4.2.0
- *os*: Linux

I also have these other `@fastify` depency installed:

```
"@fastify/error": "^3.0.0",
"@fastify/express": "^2.0.0",
"@fastify/multipart": "^7.1.0",
"@fastify/swagger": "^6.0.0",
```

**Comment by Asjas** [comment]
Same issue https://github.com/fastify/help/issues/707

Your version of `@fastify/swagger` needs to be `7.x` to support Fastify v4.

**Comment by climba03003** [comment]
Closed as duplicate issue mention in above.
