### ISSUE TITLE
format for multi-language support 

### ISSUE THREAD

**Issue by anniemon** [fastify/help#714]
#### You have already researched for similar issues?
Yes (and found none)

#### What are you trying to achieve, or the steps to reproduce?
Want some format for multi-language support such as language selection UI..etc.
(I want to translate [fastify.io](https://www.fastify.io/docs/latest/) in Korean!)

This will (hopefully) improve and popularize fastify :) Thanks!

**Comment by mcollina** [comment]
What's the question? 

if you want, I can create you a repo similar to the Chinese one https://github.com/fastify/docs-chinese.

**Comment by anniemon** [comment]
Hi, I set the wrong upstream and made contributors section messed up. I fixed the commit history, but don't have the right to clean contributors section.  Can you bother to remove the them? Sorry.

**Comment by mcollina** [comment]
I don't think that's fixable. No worries anyway
