### ISSUE TITLE
Custom-defined session properties not accessible in the `onRequest` hook

### ISSUE THREAD

**Issue by mkhoussid** [fastify/help#716]
Hey guys, love the project, amazing work.

I have a question about the flow of the hooks. Was there a discussion in the past / is there a reason, why the `onRequest`  hook doesn't have access to the session?

I'm trying to cement a good logging mechanism/system in my app and I'd like to indicate which user, if there is one, is trying to do what (accessing `request.session.user`).

For now, I've resorted to using the `preHandler` / `preValidation` hook, but I'm still curious about the reasoning behind why I can't use the `onRequest` hook for this. I'm aware of the lifecycle of hooks and why [body would be undefined](https://www.fastify.io/docs/latest/Reference/Hooks/#onrequest), but I'm not sure why `request.session[<custom_property>]` would be undefined.

Thanks in advance!

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by mkhoussid** [comment]
Sure thing, [here it is](https://github.com/mkhoussid/multi_requests_bug).

It's a repo from a [previous issue](https://github.com/fastify/fastify/issues/4124), so you might have it cloned already. If that's the case, please pull from master.

Thanks!

**Comment by mcollina** [comment]
Your problem happens because you are registering your routes _before_ `@fastify/session` (they should be registered afterward), and you are not wrapping them in a plugin.
