### ISSUE TITLE
How to inject a header for all responses (globally)?  

### ISSUE THREAD

**Issue by theblackfort** [fastify/help#72]
#### What are you trying to achieve or the steps to reproduce?

What is the recommended way to inject a header in all the responses for all routes? 

```js
// I would like to inject the following header in every response.
    reply.header(`Some-Header`, `42`);
```

**Comment by delvedor** [comment]
The [`onSend`](https://www.fastify.io/docs/latest/Hooks/) hook is what you need :)

```js
fastify.addHook('onSend', async (req, reply) => {
  reply.header(`Some-Header`, `42`)
})
```

**Comment by theblackfort** [comment]
Thanks a lot :)
