### ISSUE TITLE
Fastify plugins for testing 

### ISSUE THREAD

**Issue by gusparr28** [fastify/help#721]
I'm using fastify-bcrypt for password encryption. When I try to test (with Jest) the service which is in charge of encrypting the password, my fastify instance can't see my bcrypt plugin registered and I got this error:

```typescript
TypeError: Cannot read properties of undefined (reading 'hash')
```
and the reason why is because bcrypt plugin isn't being found in Jest testing environment but idk how to solve it

I'll deeply appreciate any help or suggestion

Thanks!

**Comment by gusparr28** [comment]
GTK: when I do the exact same test via HTTP request with Insomnia, @fastify/bcrypt works properly, since I'm registering it in my Fastify instance. So, the issue only happens in test environment

**Comment by Asjas** [comment]
Can you provide steps to reproduce? We often need a reproducible example, e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that. 🙂

**Comment by gusparr28** [comment]
Sure, I just made a small Fastify server to simplify the use case so you guys can reproduce the issue

1. Clone this repo: https://github.com/gusparr28/fastify-plugin
2. Run `npm install`
3. Run `npm run test`

Afterwards, you'll see the error I'm getting. Appreciate your help. Thanks!

**Comment by Asjas** [comment]
Your issue is how you are registering the `fastify-bcrypt` package. You are importing it into the `index.js` file but you shouldn't be doing that, it should be the `app.js` file. 

That is why your test isn't working, the plugin is never registered. This shows that the test now works.

```js
import { app } from "./app";
import bcrypt from 'fastify-bcrypt';

export class BcryptTest {
  constructor() { }

  async bcryptTest(password: string): Promise<string> {
    await app.register(bcrypt, {
      saltWorkFactor: 12,
    });

    const hashedPassword = await app.bcrypt.hash(password);
    return hashedPassword;
  }
}
```

You need to fix your code so that the `fastify-bcrypt` plugin is registered in the `app.js` file, and not the `index.js` file. @gusparr28

**Comment by Asjas** [comment]
This is where you need to register this plugin. So that the `app` has the plugin.
https://github.com/gusparr28/fastify-plugin/blob/master/src/app.ts#L5

```js
await app.register(bcrypt, {
  saltWorkFactor: 12,
});
```

**Comment by mcollina** [comment]
Please undo all the directory structuring you have done, you are overcomplicating things and causing this problem. I'd recommend to follow the application structure as generated by fastify-cli. Anyway, here is your fix:

```js
  async bcryptTest(password: string): Promise<string> {
    await app.ready() // needed because you are not initializing your application
    const hashedPassword = await app.bcrypt.hash(password);
    return hashedPassword;
  }
```

**Comment by gusparr28** [comment]
Your suggestions worked like a charm, thanks! And yes, maybe I'm over complicating things. I just tried to make a custom directory structure. I'll check it out the one generated by fastify-cli.

I thought making a single plugins.ts file and registering all my plugins in there and them importing it before initializing the server would be a great idea.

Now, I have a doubt with the await app.ready(). Should I put an await app.close() somewhere?

**Comment by Asjas** [comment]
>Now, I have a doubt with the await app.ready(). Should I put an await app.close() somewhere?

No you do not need that as the Server will close when you stop it. That method is to manually stop the server.
