### ISSUE TITLE
Rate limiting `OPTIONS` routes in Fastify v4 throws error

### ISSUE THREAD

**Issue by Fdawgs** [fastify/help#723]
## 💬  Question here 

I am in the process of migrating APIs from Fastify v3.29.1 to v4.2.1.
Previously, I was able to use `@fastify/rate-limit` to rate limit `OPTIONS` routes created by `@fastify/cors` by setting the hook option for `@fastify/rate-limit` to "onSend" like so:

```js
const fastify = require("fastify")({
	logger: true,
});
const rateLimit = require("@fastify/rate-limit");
const cors = require("@fastify/cors");


async function server() {

	await fastify.register(rateLimit, { hook: "onSend" });

	await fastify.register(async (childContext) => {
                // This route would normally be in a seperate file and loaded using `@fastify/autoload`
		await childContext.register(cors, { methods: ["GET"] });
		childContext.route({
			method: "GET",
			url: "/foo",
			handler: () => "ok",
		});
	});

	await fastify.listen({ port: 8000 });
}

server();
````

In Fastify v4, this is still possible, however it will throw `Cannot set headers after they are sent to the client` every time a response is sent (even though it includes the rate limit headers in the response) from **ALL** routes. Not massively great as it fills up the logs with crud!

Removing the "onSend" hook from `@fastify/rate-limit` stops the errors, but in turn no longer rate-limits `OPTIONS` routes.

Any help would be greatly appreciated!

## Your Environment

- *node version*: 16.16.0
- *fastify version*: >=4.2.1
- *os*: Windows

**Comment by mcollina** [comment]
__This should not happen__. I suspect there is a bug in Fastify. Could you try to reproduce _without_ `@fastify/cors` and `@fastify/rate-limit`?

**Comment by Fdawgs** [comment]
Thanks @mcollina. Has the way "onSend" hooks work changed at all with v4?

This may explain this issue, alongside others i've been encountering?

As an example, I have had to refactor some "onSend" hooks to now either return the `payload` or `next`.
Before I could cheekily just return the response.

**Fastify v3:**
```js
		.addHook("onSend", async (req, res) => {
			if (
				res.getHeader("content-type") !== undefined &&
				!res.getHeader("content-type")?.includes("html") &&
				!res.getHeader("content-type")?.includes("xml")
			) {
				res.header(
					"content-security-policy",
					"default-src 'self';frame-ancestors 'none'"
				);
				res.raw.removeHeader("x-xss-protection");
			}

			return res;
		})
```

**Fastify v4:**
```js

		.addHook("onSend", (req, res, payload, next) => {
			if (
				res.getHeader("content-type") !== undefined &&
				!res.getHeader("content-type")?.includes("html") &&
				!res.getHeader("content-type")?.includes("xml")
			) {
				res.header(
					"content-security-policy",
					"default-src 'self';frame-ancestors 'none'"
				);
				res.raw.removeHeader("x-xss-protection");
			}

			next();
		})

**Comment by climba03003** [comment]
I cannot reproduce the issue. There are some missing information from the above code.

```
import Fastify from "fastify";
const fastify = Fastify({ logger: true });

fastify.addHook("onSend", async (request, reply, payload) => {
  if (
    reply.getHeader("content-type") !== undefined &&
    !reply.getHeader("content-type")?.includes("html") &&
    !reply.getHeader("content-type")?.includes("xml")
  ) {
    reply.header(
      "content-security-policy",
      "default-src 'self';frame-ancestors 'none'"
    );
    reply.raw.removeHeader("x-xss-protection");
  }
  return payload;
});

fastify.get("/", () => "success");

{
  const res = await fastify.inject("/");
  console.log(res.statusCode);
  console.log(res.payload);
}
```

**Comment by Fdawgs** [comment]
Apologies, seems like a red-herring. The issue was my preValidation hooks. :(
