### ISSUE TITLE
[ASK] decorateRequest

### ISSUE THREAD

**Issue by conioX** [fastify/help#725]
Hi, Guys

from the documentation here :

https://www.fastify.io/docs/latest/Reference/Decorators/

i need to add decorateRequest if i want manipulate the request object

```
// Decorate request with a 'user' property
fastify.decorateRequest('user', '')   // <------------------------ Here

// Update our property
fastify.addHook('preHandler', (req, reply, done) => {
  req.user = 'Bob Dylan'
  done()
})
// And finally access it
fastify.get('/', (req, reply) => {
  reply.send(`Hello, ${req.user}!`)
})
```

how about if i add new params to body request like this

`request.body.userInfo = {name : 'example'}`

should i use decorateRequest? and how?

**Comment by mcollina** [comment]
no problem in doing that.
