### ISSUE TITLE
how to install Ajv-keywords. FastifyError Failed building the validation schema for GET: /people, due to error Unexpected token ':' 

### ISSUE THREAD

**Issue by meotimdihia** [fastify/help#726]
## 💬  Question here 

I am getting the error: `FastifyError Failed building the validation schema for GET: /people, due to error Unexpected token ':' `
```js
const server = fastify({
  ajv: {
    customOptions: {
      removeAdditional: true,
      useDefaults: true,
      coerceTypes: "array", // This line
      allErrors: true,
      allowUnionTypes: true
    },
    plugins: [AjvErrors, [require('ajv-keywords'), ['transform']]]
  }
})
````

```js
  type IQuery = {
    q: string
  }
  const querystring = {
    type: "object",
    properties: {
      q: { type: "string", minLength: 2, transform: ["trim"] }
    }
  } as const

  fastify.get<{ Querystring: IQuery }>(
    "/people",
```

If possible add a link to sample codes for error reproduction (github or replit)

## Your Environment

- *node version*: 16
- *fastify version*: >=4
- *os*: Mac
- *any other relevant information*

**Comment by Eomm** [comment]
Could you add a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) that runs?

Without it, we are unable to help you.

**Comment by meotimdihia** [comment]
it takes more than an hour for me to figure out this problem.
I have to remove `yarn.lock` and run `yarn install` again.
I still dunno why, but it works again.
