### ISSUE TITLE
Fastify Error Code Style

### ISSUE THREAD

**Issue by Uzlopak** [fastify/help#727]
Is there some style guide regarding the Fastify Error Codes?

Sometimes we have FST_ERR_ sometimes just FST_*

Do we have some recommendations or style guide to unify this throughout the code base?

**Comment by mcollina** [comment]
Let's not _change_ error codes. FST_ is ok as a prefix from my point of view.

**Comment by Uzlopak** [comment]
No, dont worry. It is more about new Errors. So only FST as prefix?

**Comment by mcollina** [comment]
It should read something useful. What do we do in Fastify proper?

**Comment by mcollina** [comment]
We use `FST_ERR` in https://github.com/fastify/fastify/blob/main/lib/errors.js, so I think we should go with `FST_ERR` everywhere.
