### ISSUE TITLE
Using fastify-swagger together with type provider

### ISSUE THREAD

**Issue by kibertoad** [fastify/help#728]
Is the fastify-swagger functionality for generating OpenAPI documentation out of route schemas supposed to work when using type providers and their serializers validators?

Our code:
```ts
import { serializerCompiler, validatorCompiler } from 'fastify-type-provider-zod'
import type { ZodTypeProvider } from 'fastify-type-provider-zod'

  const app = fastify<http.Server, http.IncomingMessage, http.ServerResponse, pino.Logger>({
    logger: resolveLoggerConfiguration(appConfig),
  })

<...>

  app.setValidatorCompiler(validatorCompiler)
  app.setSerializerCompiler(serializerCompiler)

<...>

  app.register(fastifySwagger, {
    exposeRoute: true,
    openapi: {
      info: {
        title: 'SampleApi',
        description: 'Sample backend service',
        version: '1.0.0',
      },
      servers: [
        {
          url: `http://${
            appConfig.bindAddress === '0.0.0.0' ? 'localhost' : appConfig.bindAddress
          }:${appConfig.port}`,
        },
      ],
      components: {
        securitySchemes: {
          bearerAuth: {
            type: 'http',
            scheme: 'bearer',
            bearerFormat: 'JWT',
          },
        },
      },
    },
  })

<...>

const LOGIN_SCHEMA = z.object({
  username: z.string().max(32).describe('someDescription'),
  password: z.string().max(32),
})

    const routes = [
      {
        method: 'POST',
        url: '/login',
        handler: postLogin,
        schema: { body: LOGIN_SCHEMA, describe: 'test route' },
      }
    ],

<...>

  app.after(() => {
    const { routes } = getRoutes()
    routes.forEach((route) => app.withTypeProvider<ZodTypeProvider>().route(route))
  })
```

Validation works correctly. Routes correctly show up on swagger-ui endpoint. But their schemas are empty. Am I doing something wrong, or support for this is simply not implemented? If it's the second, I would be happy to work on implementing the support, but I would really appreciate some pointers on where should I be looking, whether this is something that needs to be addressed from fastify-swagger or from type provider side.

## Your Environment

- *node version*: 16
- *fastify version*: 4.3.0
- *@fastify/swagger version: "^7.4.1",
- *fastify-type-provider-zod version "^1.0.0",
- *os*: Windows

**Comment by mcollina** [comment]
Zod is not generating JSON Schema. All of this works well with typebox with a similar developer experience.

**Comment by kibertoad** [comment]
Resolved in https://github.com/turkerdev/fastify-type-provider-zod/pull/8
