### ISSUE TITLE
Help: @fastify/jwt return {} when set namespace property

### ISSUE THREAD

**Issue by changjingli** [fastify/help#729]
## 💬  Question here 

a clear , consise and brief decription of your question

```js
// app.js
const fastify = require('fastify')
const jwt = require('@fastify/jwt')


fastify.register(jwt, {
  secret: 'test',
  namespace: 'security',
  jwtVerify: 'securityVerify',
  jwtSign: 'securitySign'
})

fastify.register(jwt, {
  secret: 'fastify',
  namespace: 'airDrop'
})

// use them like this:
fastify.post('/sign/:namespace', async function (request, reply) {
  switch (request.params.namespace) {
    case 'security':
      return reply.securitySign(request.body)
    default:
      return reply.airDropJwtSign(request.body)
  }
})
````

```js
// user.js

fastify.post('/login', {
    schema: {
      type: 'object',
      required: ['phone', 'password'],
      properties: {
        phone: 'string',
        password: 'string'
      }
    }
  }, async function (request, reply) {
    const {phone, password} = request.body;

    return reply.securitySign(request.body) // => ouuput: {}
  })

```

If possible add a link to sample codes for error reproduction (github or replit)

## Your Environment

- *node version*: 16.16.0
- *fastify version*: >=2.0.0
- *os*: Mac
- "@fastify/autoload": "^5.0.0",
    "@fastify/jwt": "^6.3.2",
    "@fastify/mysql": "^4.0.0",
    "@fastify/sensible": "^4.1.0",
    "fastify": "^4.0.0",
    "fastify-cli": "^4.3.0",
    "fastify-plugin": "^3.0.0",

**Comment by changjingli** [comment]
Hi, the reproducible repository is https://github.com/changjingli/fastify-jwt-namaspace-return-empty-object-reproduce, open http://127.0.0.1:3333/example after running dev.

I found out `fastify.jwt.sign({'foo': 'bar'})` can return correct  token but `reply.securitySign({'foo': 'bar'})` can't, hope it is helpful for you.

Thanks a lot!

**Comment by mcollina** [comment]
@Uzlopak could you take a look?

**Comment by Uzlopak** [comment]
I think there is a misunderstanding how the plugin has to be used. reply.jwtSign or as used in the repo with the namespace securitySign does not force to send the token to the browser. It does only sign the data and returns the token. You can then send the token in the needed format to the browser.

See the example https://github.com/fastify/fastify-jwt#example-1

So to get it work in that repository you would change it to:
```
    // We generate a token using the default sign options
    const token = await reply.securitySign({'foo': 'bar'})
    return { token }
```

**Comment by changjingli** [comment]
sorry, my mistake. Thanks
