### ISSUE TITLE
Schema validation for string type

### ISSUE THREAD

**Issue by sumitgoelpw** [fastify/help#73]
#### What are you trying to achieve or the steps to reproduce?

I want to validate the JSON payload in the HTTP POST request.

```js
const jsonSchema = {
  schema: {
    body: {
      type: 'object',
      properties: {
        someKey: { type: 'string' },
        someOtherKey: { type: 'number' }
      },
      required: ['someKey', 'someOtherKey']
    },
    response: {
      200: {
        type: 'object',
        properties: {
          root: { type: 'boolean' }
        }
      }
    }
  }
}

module.exports = async (fastify, opts) => {
  fastify.post('/', jsonSchema, async (request, reply) => {
    return { root: true }
  })
}
```

#### What was the result you received?

```shell
$ curl -s -X POST -H "Content-Type: application/json" -d '{"someKey": 12, "someOtherKey": 12}' 127.0.0.1:3000 | jq
{
  "root": true
}
```

#### What did you expect?

I should get an error message that someKey should be a string.

#### Context

* *node version*: v11.14.0
* *fastify version*: 2.2.0
* *os*: macOS

**Comment by mcollina** [comment]
Types are coerced by default. You'll get a string on the other side. See https://www.fastify.io/docs/latest/Validation-and-Serialization/ for more details.
