### ISSUE TITLE
Rewrite body

### ISSUE THREAD

**Issue by advany** [fastify/help#731]
I use @fastify/http-proxy and it works wonderfully (and faster then http-proxy-middleware). The only thing I can't figure out how can I rewrite the body of a response? I need to change the html before is send back to the client.

**Comment by mcollina** [comment]
use onResponse: https://github.com/fastify/fastify-reply-from#onresponserequest-reply-res

**Comment by advany** [comment]
For anyone else having this issue. This is how I did it. I needed to remove content-length, decompress the response, change the body and then return the body uncompressed (still working on returning the body compressed).

  onResponse: async (request, reply, res) => {
        let headers = reply.getHeaders();
        let contenttype = headers['content-type'];
        if(contenttype.includes('text')) {
          reply.removeHeader('content-length');
          let contentencoding = headers['content-encoding'];
          let decompress;

          reply.removeHeader('content-encoding');

          switch (contentencoding) {
            case 'gzip':
              decompress = zlib.createGunzip();
              break;
            case 'br':
              decompress = zlib.createBrotliDecompress();
              break;
            case 'deflate':
              decompress = zlib.createInflate();
              break;
            default:
              break;
          }

          if(decompress) {
            res.pipe(decompress);
            let buffer = Buffer.from('', 'utf8');

            decompress.on('data', (chunk) => (buffer = Buffer.concat([buffer, chunk])));

            decompress.on('end', async () => {
              let body = buffer.toString();
              body = body.replace('soemthing', 'somethingelse');

              reply.send(body);
            });
          } else reply.send(res);
        } else reply.send(res);
      }

**Comment by advany** [comment]
For anyone else having this problem. I created this function and it solved it:

function change_body(request, reply, res, call_back) {
    let headers = reply.getHeaders();
    let contenttype = headers['content-type'];
    let contentencoding = headers['content-encoding'];

    if(contenttype.includes('text')) {
      let decompress;

      switch (contentencoding) {
        case 'gzip':
          decompress = zlib.createGunzip();
          break;
        case 'br':
          decompress = zlib.createBrotliDecompress();
          break;
        case 'deflate':
          decompress = zlib.createInflate();
          break;
        default:
          break;
      }

      if(decompress) {
        res.pipe(decompress);
        let buffer = Buffer.from('', 'utf8');

        decompress.on('data', (chunk) => (buffer = Buffer.concat([buffer, chunk])));

        decompress.on('end', async () => {
          let body = buffer.toString();
          if(body) {
            reply.removeHeader('content-length');
            body = call_back.call(this, body);
          }
          reply.compress(body);
        });
      } else reply.send(res);
    } else reply.send(res);
  }
  
  You will also need: 
  
  await server.register(
    import('@fastify/compress'),
    { global: false }
  )
  
  And call it using:
  
  onResponse: async (request, reply, res) => {
        change_body(request, reply, res, function(body) {
          return body.replace('Search This', 'Replace with');
        })
      },

**Comment by advany** [comment]
@mcollina would be great if this could be added to fastify like a hook or something. something like rewriteBody so please who need to change the body can easily do it
