### ISSUE TITLE
How do I add a custom format for a fastify's ajv instance?

### ISSUE THREAD

**Issue by budarin** [fastify/help#732]
## 💬  Question here 

I want to add support for extended types that are implemented in the `ajv-formats` package
I am trying to perform `ajv` initialization and describe the formats

```js
const app = Fastify({
    ajv: {
      plugins: [require('ajv-formats']
    },
});
```

the scheme:

```json
{
  "type": "object",
  "properties": {
     "id": { 
        "type" "uuid" 
     }
  }
}
```

but get an error:

```
    unknown format "uuid" ignored in schema at path "#/properties/id"

      at unknownFormat (node_modules/ajv/lib/vocabularies/format/format.ts:87:15)
      at validateFormat (node_modules/ajv/lib/vocabularies/format/format.ts:75:9)
      at Object.code (node_modules/ajv/lib/vocabularies/format/format.ts:40:10)
      at keywordCode (node_modules/ajv/lib/compile/validate/index.ts:523:9)
      at node_modules/ajv/lib/compile/validate/index.ts:265:9
      at CodeGen.code (node_modules/ajv/lib/compile/codegen/index.ts:525:33)
      at CodeGen.block (node_modules/ajv/lib/compile/codegen/index.ts:680:20)
      at iterateKeywords (node_modules/ajv/lib/compile/validate/index.ts:262:7)
      at groupKeywords (node_modules/ajv/lib/compile/validate/index.ts:241:7)
      at node_modules/ajv/lib/compile/validate/index.ts:233:38
```
the same result I get using this code

```js
const app = Fastify({
    ajv: {
        customOptions: {
          formats: {
             uuid: {
               type: 'string',
               validate: /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'/,
             },
          },
        },
    },
});
```

how can I use custom formats in fastify?

## Environment

- *node version*: v18.6.0
- *fastify version*: ^4.4.0
- *os*: any

**Comment by Uzlopak** [comment]
Well. formats are not new types. formats are formats. Maybe you should also open a issue in ajv, that they should not have an error-message `unknown format "uuid" ignored in schema` if in fact the type is unknown.

```
{
  "type": "object",
  "properties": {
     "id": { 
        "type": "string",
        "format" "uuid" 
     }
  }
}
```

**Comment by budarin** [comment]
there was a banal typo - I just missed writing `{type: 'strin'}` when writing the issue 

with a properly designed scheme, this error is reproduced

**Comment by Uzlopak** [comment]
I added a unit test to fastify. It seems that ajv-formats work as expected:

https://github.com/fastify/fastify/pull/4187/files

**Comment by budarin** [comment]
I don't understand anything - I do everything the same, but I get an error...

**Comment by budarin** [comment]
I have found the problem - it affected by another of ajv instance in app - I have an ajv instance to validate response from fetch and its presence somehow affects the instance in fastify

**Comment by budarin** [comment]
exactly the problem is in a parallel instance - if you use code from ajv-formats for it

```js
import Ajv from 'ajv';
import addFormats from 'ajv-formats';

const ajv = new Ajv();

addFormats(ajv);

... fastify app
```

then the error does not occur, but if you do not add formats to this instance and add them to the ajv instance in fastify, an error occurs

**Comment by budarin** [comment]
it seems that my question is specific to our project and justify has no problems in ajv-formats - so I close this issue
