### ISSUE TITLE
running a fastify route periodically

### ISSUE THREAD

**Issue by punkish** [fastify/help#733]
Is there a built-in mechanism to run a fastify route periodically?

#### You have already researched for similar issues?

I have looked at [fastify-cron](https://www.npmjs.com/package/fastify-cron) but I can't figure out if I can use that to call a route from within `fastify`. 

#### What are you trying to achieve, or the steps to reproduce?

To summarize, given a route as below, I would like `https://my/server/greeting` to be called periodically, say, every midnight.

```js
fastify.get('/greeting', function (request, reply) {
  reply.send({ hello: 'world' })
})
```

**Comment by mcollina** [comment]
You can call a route from within Fastify using `app.inject()`

**Comment by punkish** [comment]
thanks
