### ISSUE TITLE
Should @fastify/compress work with readable stream?

### ISSUE THREAD

**Issue by hafffe** [fastify/help#738]
## 💬  Question here 

I'm noticed when I added `@fastify/compress` as dependency and register the plugin to the Fastify instance, streams are waiting to send the content until the promise is resolved. 

I've tried to find answers about how it is intended to work but was unable to do, So the question is should this be possible or am I doing something wrong?

If `@fastify/compress` is enabled with global flag set to false Fastify replies with the content immediately and then pushes the resolved content afterwards as intended. 

Example of working example
```js
await app.register(FastifyCompress, { global: false});

	app.get('/stream', async (req, reply) => {
		const stream = new Readable();
		stream._read = () => {};

		reply.header('content-type', 'text/html; charset=utf-8');
		reply.header('transfer-encoding', 'chunked');

		reply.send(stream);
		stream.push('<h1>This should render immediately.</h1>');
		await new Promise((resolve) => setTimeout(resolve, 3000));


		stream.push('<p>This should render after 3 seconds</p>');
		stream.push(null);

		return reply;
	});
````

However if the global option is changed to true Fastify waits 3 seconds until send the content, so the request response time in this case is 3 seconds and no content is visible until everything is resolved.

Example where it's not working as expected
```js
await app.register(FastifyCompress, { global: true});

	app.get('/stream', async (req, reply) => {
		const stream = new Readable();
		stream._read = () => {};

		reply.header('content-type', 'text/html; charset=utf-8');
		reply.header('transfer-encoding', 'chunked');

		reply.send(stream);
		stream.push('<h1>This should render immediately.</h1>');
		await new Promise((resolve) => setTimeout(resolve, 3000));


		stream.push('<p>This should render after 3 seconds</p>');
		stream.push(null);

		return reply;
	});
```

A repo with full example is found here:
 [repo](https://github.com/hafffe/fastify-streams)

## Environment

- *node version*: 16, 18
- *fastify version*: >=4.2.0
- *os*: Mac

**Comment by mcollina** [comment]
This seems correct. You are not sending enough data for the compressed stream to do its job. As every block compressor, they need a minimum amount of data before generating a block. The chunk size in Node.js is 16KB by default, so everything up to 16KB will be buffered before being sent.

Note that you can specify custom compression functions (see https://github.com/fastify/fastify-compress) and set the options as you'd like.

**Comment by hafffe** [comment]
Thanks for answer, didn't know about the 16kb chunk size
