### ISSUE TITLE
Stale-Bot not active on whole org?

### ISSUE THREAD

**Issue by Uzlopak** [fastify/help#739]
It seems that StaleBot is not active on the whole organization level. It seems only 48 of 127 repos are able to be processed by StaleBot.

e.g.

https://github.com/fastify/fluent-json-schema/issues/171

should have been marked as stale long ago. 

So I assume stale bot is not active on that repo.

**Comment by Fdawgs** [comment]
Can be enabled for all repos if others think it's a good idea. I'm for it.

**Comment by Eomm** [comment]
Right now stalebot is configured on selected repos

<img width="494" alt="image" src="https://user-images.githubusercontent.com/11404065/185778771-2ce236d3-b2fc-42bd-a992-e7543ac354a2.png">

Do we want to give it access to the whole org's repos?
Just asking if someone found possible issues in past

**Comment by delvedor** [comment]
+1 on enabling it everywhere.

**Comment by Eomm** [comment]
Done
