### ISSUE TITLE
Unable to serve Create React App SPA urls

### ISSUE THREAD

**Issue by dlbrown06** [fastify/help#74]
Just a quick question. In express I would call something like this when setting up routes static files like images:

```
app.use(express.static(path.join(__dirname, '..', 'build')));
```

Then I would have a catch-all to show the `index.html` file for everything else where I don't have a route defined.

```
app.get('/*', (req, res) => {
    res.sendFile(path.join(__dirname, '..', '..', 'build', 'index.html'));
  });
```

My problem is it appears that fastify doesn't allow this. Essentially getting an error of:
```
Method 'GET' already declared for route '/*'
```

Had a hard time lookin for a resolution on this and hoping someone here could point me in the right path.

**Comment by Eomm** [comment]
Hi, 
what code did you try?

This is a quick and dirty working example:

```
const fs = require('fs')
const app = require('fastify')({ logger: true })
app.get('/*', (req, res) => {
  res.send(fs.createReadStream(__filename))
})
app.listen(3000)
```

For the `sendFile` function instead, actually, we don't [support it](https://github.com/fastify/fastify/blob/master/docs/Middlewares.md#express-middleware-compatibility) but we have a feature request opened.
This could be done via a plugin that registers a [`decorateReply`](https://github.com/fastify/fastify/blob/master/docs/Decorators.md#usage-notes) if you wanna give it a try 👍

**Comment by dlbrown06** [comment]
Hmm - Maybe I'm just over-complicating this. Essentially just trying to make this react application SEO friendly. From the single page react app, I'm able to nav to the homepage and navigate around. React router is managing the url in the address bar. However, when I refresh the page on a non-root url, I get a 404. Obviously because the fastify-static handler isn't catching it:
```
fastify.register(require("fastify-static"), {
  root: path.join(__dirname, "..", "build"),
  prefix: "/" // optional: default '/'
});
```
In express, this was handled by:
```
app.use(express.static(path.join(__dirname, '..', 'build')));

app.get('/*', (req, res) => {
    res.sendFile(path.join(__dirname, '..', '..', 'build', 'index.html'));
  });
```
So I was hoping it would work similarly with fastify. I'm not able to define the `/*` get route though because it appears that fastify-static is doing this. :(

**Comment by dlbrown06** [comment]
Or would this be better for the fastify-static module? This seems it might be more related to that:
https://github.com/fastify/fastify-static/issues/87
https://github.com/fastify/fastify-static/issues/75

**Comment by mcollina** [comment]
Setting wildcard to false will enable you: https://github.com/fastify/fastify-static/blob/master/README.md#wildcard.

This is a major difference between Fastify routing and express routing: you can’t have more than 1 wildcard at a given level.

**Comment by Eomm** [comment]
@dlbrown06 I did not know you are using the static plugin. 

I think you can archive your needs adding a onRequest hook that changes every time (some of) the requested path to index.html

The problem here is not the routing: you want to serve a file. I think the problem is that regardless the path you want always index.html right?

**Comment by TMantas** [comment]
I ran into same issue and (kinda) solved it with:
```
fastify.setNotFoundHandler(function (request, reply) {
  reply.sendFile('index.html')
})
```

let me know if you have better solutions

**Comment by mkhoussid** [comment]
> I ran into same issue and (kinda) solved it with:
> 
> ```
> fastify.setNotFoundHandler(function (request, reply) {
>   reply.sendFile('index.html')
> })
> ```
> 
> let me know if you have better solutions

Also wondering if there is a better solution.

**Comment by VottusCode** [comment]
My current and working solution, I see no problems using that.

```ts
  app.fastify.register(fastifyStatic, {
    root: STATIC_DIRECTORY,
  });

  // Not found handler
  app.fastify.setNotFoundHandler((req, res) => {
    // API 404
    if (req.raw.url && req.raw.url.startsWith("/api")) {
      return res.status(404).send({
        success: false,
        error: {
          kind: "user_input",
          message: "Not Found",
        },
      });
    }

    // Vue SPA
    res.status(200).sendFile("index.html");
  });
```

**Comment by pedroapfilho** [comment]
This is the correct link for setDefaultRoute() https://www.fastify.io/docs/latest/Reference/Server/#setdefaultroute

**Comment by waynebloss** [comment]
The `wildcard` option is not working for me at all.

```ts
api.register(fastifyStatic, {
  prefix: "/",
  root: staticRoot,
  wildcard: true,
  allowedPath(pathName: string, root, request) {
    console.log("STATIC", { pathName, root }); // These print out correctly...
    return !pathName.startsWith("/api");
  },
});
```

**Comment by Eomm** [comment]
This was a three years old issue.
Please open a new detailed issue adding a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).
