### ISSUE TITLE
Setting `app#setNotFoundHandler` when registering a scoped plugin does not work with a prefix

### ISSUE THREAD

**Issue by bacloud22** [fastify/help#742]
Following [documentation](https://www.fastify.io/docs/latest/Reference/Server/#setnotfoundhandler) example, I cannot have a specific 
`NotFoundHandler` for a specific route.

## 💬  Question here 
Prefix is ignored completely, so either with prefix or not, the behaviour is the same for all routes.
I also tried all possible orders with registration of plug-ins when the app bootstraps.

```js
  app.register(function (instance, options, done) {
    instance.setNotFoundHandler(function (req, reply) {
      reply.status(404).send({ message: 'Resource not found. Please check API documentation' })
    })
    done()
  }, { prefix: '/api' })
````

## Your Environment

- *node version*: 10, 12, 13
- *fastify version*: 4.3.0
- *os*: Ubuntu 20 & Windows server 2019

**Comment by bacloud22** [comment]
OK, I found out that [fastify-static](https://github.com/fastify/fastify-static) do not cohabit well with this.

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.
