### ISSUE TITLE
Cannot set headers after they are sent to the client Error when using passport js and Helmet 

### ISSUE THREAD

**Issue by george-martin** [fastify/help#747]
I'm using @fastify/passport in my application to authenticate users with Google authentication. It worked well and the user is authenticated. But after I tried to register helmet, the requests give me above error.

```
app.register(require('@fastify/helmet'))

// route
app.get('google', fastifyPassport.authenticate('google', { scope: ['profile'] }))
````

Kinda similar to this issue -  #493

## Your Environment

- *node version*: v16.16.0
- *fastify version*: >=^4.0.0
- *os*:  Linux

**Comment by Asjas** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by george-martin** [comment]
Hi, thanks for replying.

when I try to visit the the route, I'm facing the error.
`
const fastify = require('fastify')({ logger: true })
const fastifyCookie = require('@fastify/cookie')
const fastifySession = require('@fastify/session')
const { Authenticator } = require('@fastify/passport')
const GoogleStrategy = require('passport-google-oauth20').Strategy

const Redis = require('ioredis')
const redisStoreFactory = require('connect-redis')

const RedisStore = redisStoreFactory(fastifySession)

const store = new RedisStore({
  client: new Redis({
    enableAutoPipelining: true,
  })
})

fastify.register(fastifyCookie, {})
fastify.register(fastifySession, {
  secret: 'SECRET_KEY',
  cookie: { secure: false },
  store
})

const fastifyPassport = new Authenticator()
fastify.register(fastifyPassport.initialize())
fastify.register(fastifyPassport.secureSession())

fastify.register(require('@fastify/cors'), {
  origin: '*'
})

fastify.register(require('@fastify/helmet'), {contentSecurityPolicy: false})

fastifyPassport.registerUserDeserializer(async (user, req) => {
  return user
})

fastifyPassport.registerUserSerializer(async (user, req) => {
  return user
})

fastifyPassport.use(
  'google',
  new GoogleStrategy(
    {
      clientID: 'Google ID',
      clientSecret: 'Google Secret',
      callbackURL: '/cb'
    },
    function (accessToken, refreshToken, profile, cb) {
      return cb(null, profile)
    }
  )
)
fastify.get('/google', fastifyPassport.authenticate('google', {scope: ['profile']}))

fastify.listen(5000)
`

**Comment by george-martin** [comment]
Set helmet to global and disabled it for external authentication.
