### ISSUE TITLE
POST always timeout when using fasity in firebase function

### ISSUE THREAD

**Issue by ninjitaru** [fastify/help#75]
#### What are you trying to achieve or the steps to reproduce?

I try to use fasity with firebase function
I have setup the serverFactory and modifyCoreObjects as suggested
It is able to response on GET
but when a POST is sent, it always timeout (60 seconds)

```js
let handleRequest;
const serverFactory = (handler, opts) => {
  handleRequest = handler;
  return http.createServer();
};
const app = Fastify({
    serverFactory,
    ignoreTrailingSlash: true,
    modifyCoreObjects: false,
  });
// i have notifced that this is needed or default setErrorHandler will error out of calling info with null
app.setErrorHandler((error, request, reply) => { 
   // log error
  reply.send(error);
 });
app.get('/', async (req, res) => {
    return 'in pure get';
  });
app.post('/', async (req, res) => {
    return 'in pure post';
  });

export const functionRequestHandler = (req, res) => {
  app.ready(err => {
    if (err) throw err;
    if (handleRequest) {
      handleRequest(req, res);
    }
  });
};

// export this to firebase function
const myapp = functions.https.onRequest(functionRequestHandler);
```

#### What was the result you received?
when i post when nothing (no content-type) i got FST_ERR_CTP_INVALID_MEDIA_TYPE
when i post when content-type = 'application/json' and body of {}
i get a timeout

#### What did you expect?
i expected to see text 'in pure post' responsed

#### Context

* *node version*: firebase node 6
* *fastify version*: >=2.2.0
* *os*: Mac
* *any other relevant information*:

**Comment by mcollina** [comment]
I can’t really help - we do not support each serverless provider directly, nor they are part of our CI infrastructure.

At a glance, it seems your integration with serverFactory has some bugs.

**Comment by Eomm** [comment]
@ninjitaru recentry we added a guide on [how to use fastify with aws](https://github.com/fastify/fastify/blob/master/docs/Serverless.md)
It would be awesome if you could add a guide to use fastify with firebase!

Unfortunately, I don't have experience in firebase, but looking at the code I think there is a part that is not clear to me.

Fastify need the server object to send the response, but in the `serverFactory` you are creating a server, giving it to fastify but you are not using it with firebase so they are unknown to each others.

So I think that you need to find how to get the `server` instance from firebase and pass it to fastify via `serverFactory `.

This is a pseudocode:

```
const serverFactory = (handler, opts) => {
  // onRequest create an http server??
  const myServer = functions.https.onRequest(handler);
  return myServer;
  // maybe:
  return functions.firebaseServer // ?
};
```

**Comment by ninjitaru** [comment]
i arrived at my implemented from this gist https://gist.github.com/shwei/d34c7383a117451c07dc701ad12482f1
which has an issue linked as well, 

but thanks for the reply, this is some good leads
i will be happy to give it a shot and see how it turn out

**Comment by soultoru** [comment]
I share a solution to this problem.

[Google said](https://firebase.google.com/docs/functions/http-events#read_values_from_the_request), POST requests with application/json Content-Type body are already parsed on Cloud Functions. So, on Cloud Funcitons, we should add a custom Content-Type parser to FastifyInstance. And POST requests will be handled correctly.

```
fastify.addContentTypeParser('application/json', (request, reply, done) => {
  done(null, req.raw.body)
})
```
