### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Z3NTL3** [fastify/help#750]
I have a linux server which uses LiteSpeed.

I added my application to LiteSpeed so that litespeed will run the node application. However my application is not running even tho the host is '0.0.0.0'. I tried the same with Express JS and everything was literally fine.

Why didnt Fastify work for me?

Tried both:
``await fastify.listen({ port: 3000, host: '0.0.0.0'})``
``await fastify.listen({ port: 3000, host: '127.0.0.1'})``

**Comment by mcollina** [comment]
What error are you getting?

**Comment by Z3NTL3** [comment]
Hello,

I had some more testing and the problem is related to LiteSpeed. Once I did ``http://server-ip:3000`` it was up. I have to contact LiteSpeed support I guess.
