### ISSUE TITLE
How to add custom formats to serializer 

### ISSUE THREAD

**Issue by amarkezic** [fastify/help#751]
## Context:
We are trying to use **$ref** in response schema, but the problem is that the schemas that are being referenced use custom formats. The referencing works fine on (body, headers, qs, params) because they are all validated by **AJV** where we can add those custom formats.

The problem arises when referencing the same schemas in response (which is not validated but only serialized by fast-json-stringify).
Because referencing in fast-json-stringify uses its own instance of **AJV** (fast-json-stringify uses AJV only for special properties like [anyOf, oneOf, ref, if, else ,...], check their [docs](https://www.npmjs.com/package/fast-json-stringify) ) those custom formats are not added to this custom instance and then we get the warning in the picture below. 

## Question:
Is there a way to access this custom instance and add the custom formats ? is it even possible to add formats to serializer ? 

## Additional context
![image](https://user-images.githubusercontent.com/17450181/189353856-dee7acc5-e0d8-485a-aadc-929e20edaddb.png)

## Your Environment

- *node version*: 16
- *fastify version*: >=4.0.0
- *os*:  Linux

**Comment by mcollina** [comment]
cc @ivan-tymoshenko

**Comment by LarsenCundric** [comment]
This really is a weird thing where fast-json-stringify and fastify share the schemas added with fastify.addSchema(), but not the formats or any other custom configs...

**Comment by ivan-tymoshenko** [comment]
@amarkezic Do you want to use the custom format for the special validation cases (anyOf, oneOf, if, else) or for linking/referencing schemas to each other?

Can you send an example, please?

**Comment by amarkezic** [comment]
@ivan-tymoshenko 
I would like to link/reference schemas to each other example:

```js
const schema = {
    $id: 'test.json',
    type: 'object',
    properies: {
        id: {type: 'string', format: 'customFormat'}
    }
}

const getSingleSchema = {
    tags,
    headers,
    params,
    response: { 200: { $ref: 'test.json' } },
  };
  
```

**Comment by jsumners** [comment]
I would recommend using your own schema container for both input and output. See https://www.fastify.io/docs/latest/Reference/Server/#schemacontroller

**Comment by ivan-tymoshenko** [comment]
The problem you have is not related to the custom format. The warnings you see mean that you custom format would be ignored in validation cases (anyOf, oneOf, if, else). If you want, you can fix it by passing `ajv` option in the FJS.

This actually should work. I will check.

**Comment by amarkezic** [comment]
@ivan-tymoshenko 
Thats exactly what we did, but it seems kind of hacky. We were hoping the ajv instance would be shared within fastify.

The other problem is with adding schemas. As you see in the example below we have to add schemas to mulitple instances of ajv (FJS uses its own from what i learned) which means that we have to make a custom function to to that and not just use fastify.AddSchema()

I the addSchemaToAll Example we first addSchema to fastify instance of ajv (beacuse of swagger) then we add schema to FJS instance of ajv, and then we add schema to each validator for each httpPart

This is out current working solution:
![image](https://user-images.githubusercontent.com/17450181/189360066-02b48df7-1804-45cd-ba31-915427b24793.png)

Add schema to all:
![image](https://user-images.githubusercontent.com/17450181/189360527-78b4175c-928b-4cfa-bbcc-e6f378c84e2d.png)

**Comment by LarsenCundric** [comment]
@ivan-tymoshenko this actually seems to work. You just need to define the formats in **serializerOpts** and it stops outputting warnings.
