### ISSUE TITLE
how to combine request and request.raw calls ?

### ISSUE THREAD

**Issue by budarin** [fastify/help#752]
## 💬  Question here 

Problem when mixing calls `require.raw` and `req.<method>`

```js
fastify.register(require('@fastify/cookie'), {
  secret: "my-secret"
})

fastify.route({
  url: '/',
  method: 'GET',

  handler: (req, res) => {
     res.cookie('foo', 'bar')
  
     res.raw.statusCode = 200;
     res.raw.setHeader('Content-Type', 'text/html; charset=utf-8');
     res.raw.write(...); 
     res.raw.end(...);
  }
})
````

There is no `set-cookie` header in response

PS:
by the way, I also have a problem with types - the VS Code considers synchronous calls asynchronous

![image](https://user-images.githubusercontent.com/8055157/189450467-4ffe1319-21fb-41a8-afb9-37b9e6c3f75a.png)

## Your Environment

- *node version*: 18
- *fastify version*: >=4.5.3
- any

**Comment by jsumners** [comment]
You managed the response yourself with `res.raw.write` and `res.raw.end`. You completely skipped the Fastify machinery around sending replies. Thus, no reply hooks were invoked to set cookies.

**Comment by budarin** [comment]
But what should I do if I need to send data to the client in chunks and Fastify.response does not allow me to do this?

Use a stream instance?

**Comment by jsumners** [comment]
https://www.fastify.io/docs/latest/Reference/Reply/#streams

**Comment by budarin** [comment]
React uses pipeable stream so it need to use req.raw - reactStream.pipe(req.raw) (

**Comment by budarin** [comment]
It would be great if Fastify.reply had a write method

**Comment by Eomm** [comment]
Something like this should work:

```
const reader = new stream.Readable()
const writer = new stream.Writable({
  write(chunk, encoding, callback) {
    reader.push(chunk)
    callback()
  },
})


reactStream.pipe(writer)
reply.send(reader)
```

**Comment by budarin** [comment]
this solves the issue, but not very elegantly - adds an overhead to each request

**Comment by mcollina** [comment]
If `reactStream` is an instance of `require('stream').Readable` or compatible APIs, you can `reply.send(reactStream)` directly.

**Comment by budarin** [comment]
we also use the previous React version project where we use writing chunks of html with `res.write`in express
it usefull when at first we send headers as quickly as we can - so browser can ask server for resources while server would render the rest htm with react and then we send the rest of html

`res.write` in express - is very usefull for SSR
