### ISSUE TITLE
Fastify CLI - Write Error Logs

### ISSUE THREAD

**Issue by raviroshanmehta** [fastify/help#754]
#### Fastify CLI - Write Error Logs
I am using fastify-cli for my fastify typescript project.  As I can see in my terminal I can view all request-response logs are visible but I am not able to find any solution to write logs into files of fastify-cli generated project.  it's using the below import to initializing the app

import { FastifyPluginAsync } from "fastify";

can anyone help me with how to write logs in the file?

**Comment by mccare** [comment]
Maybe [this documentation section](https://www.fastify.io/docs/latest/Reference/Logging/#usage) helps?
