### ISSUE TITLE
@fastify/session has on npm next tag pointing to the old version. Are all packages correct tagged on npm?

### ISSUE THREAD

**Issue by Uzlopak** [fastify/help#756]
See https://www.npmjs.com/package/@fastify/session

![image](https://user-images.githubusercontent.com/5059100/191738948-9d7f2318-95bf-49ee-a5d7-f217349fad81.png)

Maybe somebody should check if all the npm tags are correctly set.

<!--
Before you submit a question we recommend you first look at our issue section (https://github.com/fastify/help/issues) to see if your question has already been answered.

**Comment by jsumners** [comment]
There's no need to keep `next` synchronized with anything. It's a tag specifically for testing an upcoming release. Once that release has been push out as `latest`, the `next` tag is available for any new testing release.

**Comment by Uzlopak** [comment]
I agree with you and I was not suggesting to point next to latest or something like that. I would also suggest to delete next. I opened the issue here, to report to you that we should maybe check the npm packages for "forgotten" tags. Because I just saw that by accident that next is tagged to 9.0.0

**Comment by jsumners** [comment]
We don't need to delete the tag. That's just extra maintenance burden we don't need.

**Comment by Uzlopak** [comment]
Ok, so if it is ok, that next points to an old version, than I wont bother.
