### ISSUE TITLE
Is it possible to customize the way handler of routes are called ?

### ISSUE THREAD

**Issue by EmrysMyrddin** [fastify/help#757]
## Is it possible to customize the way handler of routes are called ?

I'm searching for a way to really hook into the way handlers are called by fastify to allow using Generator Functions instead of Async Functions.

For now, I have to manually wrap my handlers

```js
app = fastify()
runner = generatorRunner()

app.addHook('onRequest', async (request, reply) => {
  request.runner = runner.ctx({ request, reply })
})

const generatorHandler(handler) => (req, reply) => req.runner.call(handler, req, reply)
app.get('/users/:userId', generatorHandler(function*(req, reply) {
	return yield getUser(req.params.userId)
})
```

I would like this wrapping to be automatic to avoid having to manually wrap every single handlers:

```js

// Here I want a way to customize the handler call
app.customHandler(async (handler, req, reply) => {
  return req.runner.call(handler, req, reply)
})

// Then I could use Generator functions as handlers
app.get('/users/:userId', function* (req, reply) {
	const user = yield getUser(req.params.userId)
	return user
})
````

## Your Environment

- *node version*: 18
- *fastify version*: >=4
- *os*: Mac 12.5

**Comment by Eomm** [comment]
Does a [decorator](https://www.fastify.io/docs/latest/Reference/Decorators/#decoratename-value-dependencies) help you to remove all the boilerplate?
