### ISSUE TITLE
Best practises for API structure?

### ISSUE THREAD

**Issue by PatrickHeneise** [fastify/help#76]
I'm starting a new project with fastify and was wondering if there are any best practises around regarding the structure of the project?

@mcollina pointed me towards https://github.com/fastify/fastify-cli/tree/master/templates/app which is an interesting start already, considering routes as services and everything else as plugins.

I'm wondering if I should put the schema and route definition are in one file and have one route per file, or have a router and a schema folder and separate them.

**Comment by mcollina** [comment]
There are not any official document about this, as back in the days we wanted the community to experiment, and then document the emerging design.

https://github.com/fastify/fastify-example-twitter is another example.

I don't think having one route per file is going to be easy to maintain. Most of the times when doing a change we all end up touching multiple routes. As an example, in a CRUD scenario I do the GET, POST, PUT, etc.. all in the same file. _Ideally_ that could be a microservice in the future. My personal sweet spots it's between 2 or 3 full screen scrolls.

As for the schemas, it really depends. You should have some shared definitions that are global-ish for major entities in your domain (`Product`, `Student`, ...), and some local ones (headers, etc) for route-specific stuff.

A PR to the repo would be nice.

**Comment by PatrickHeneise** [comment]
Thank you! I'm currently experimenting with the one-file-per-request idea, following the react/vue/jsx pattern of having code and design in the same file and so far I really like it. The schemas are huge and take up most of first scroll already, the actual code are usually just a few lines of composing functions.

So far I managed to make it work with multiple folders in the /services directory and loading all routes with autoload. I'll experiment with the version and prefix for each folder next time.

Not having all the available routes in a single file definitely feels wrong at this point, but given the design of `fastify.get()`, or `fastify.post()` I'd need two separate files, one for schema/options and one for the handler/function. This means for a single route a dev would need to change 3 files: schema, function, test. And chances are high to just miss to adjust the schema, leading to outdated docs.

Another issue I see coming are dynamic routes with parameters. File `a.js` is loaded before `b.js` and therefore the naming of the file defines the order of the URLs. `/user/:id` could be loaded before `/user/update`, therefore `/user/update` is unreachable. I'll see how to get around this if/when I get there.

**Comment by mcollina** [comment]
I don’t understand how the design of fastify.get or fastify.post influences this, would you mind expanding that idea?

Are you able to reuse some parts of your schemas between the routes, or you mainly copy-paste? Moreover.. have you checked fluent-schema? It’s a nice DSL to write less boilerplate for the schema.

Are you using fastify-autoload? We have recently added a dependency check in there, it might be handy.

Loads of questions :D. Good work and keep us posted. It would be good to see all your experiments published.

**Comment by PatrickHeneise** [comment]
`fastify.get(route, options, handler)`

- options includes the schema, even with commons, it's big
- handler is the code

I could separate all routes into `/schemata` and `/functions` and have entirely different files, or export schema and handler in a single file:

```
const productsList = require('./productsList')
fastify.get('/products', productsList.schema, productsList.handler)
```

I'm not really happy with this design though, still experimenting for a "pretty" solution with less code.

I am using fastify-autoload, yes. It's pretty cool! I would like to remove the `index.js` from each service folder though. I'm getting an error if the file is not there and would need to register each further route manually or run another autoload in each dir, that's contra productive. Expect a PR on that ;)

I have not seen fluent-schema. Reducing the schema definitions and redundancies would be the next step for sure.

Thanks for the guidance! I'm aiming for great developer experience. A good structure is half the work already :)

**Comment by nwoltman** [comment]
> Another issue I see coming are dynamic routes with parameters. File `a.js` is loaded before `b.js` and therefore the naming of the file defines the order of the URLs. `/user/:id` could be loaded before `/user/update`, therefore `/user/update` is unreachable.

@PatrickHeneise This won't be an issue because Fastify always matches static routes before parametric routes. See: https://github.com/delvedor/find-my-way#match-order

**Comment by PatrickHeneise** [comment]
Awesome, I didn't know that. Then there's a PR here for dynamic routing/module loading https://github.com/fastify/fastify-autoload/pull/33

**Comment by SkeLLLa** [comment]
@PatrickHeneise I've created something similar for my own needs. You may check it out https://github.com/SkeLLLa/fastify-autoload-recursive and probably find some ideas. It's not finished yet, but mostly because it lacks documentation about how to use it. But it works fine in couple of my projects.

It scans directory recursively and registers all the files. There are also some specific patterns like `*.schema.js` - for files containing shared schemas (not requests schemas) and `*.options.js` for dynamic options that will come as second param in routes plugins (for example you can define metrics there).

**Comment by PatrickHeneise** [comment]
Awesome, thanks! I found another, much simpler solution to recursively register files without any logic. So far I'm using my local fork of autoload to see how far I get. I want to start with the simple solution and then give a few alternatives, ie having schema/options filter etc.

I agree with your idea, logic shouldn't be in the route. I usually try to compose as much as possible given the repetitive nature of an API. I'll continue with the current approach and your idea and create a repo with those best practises. I hope we can collaboratively come to some sort of boilerplate (although we all dislike them somehow).

**Comment by ReTWi** [comment]
I like it like this:
```
fastifyHttps.register(async maintenanceAvailable => {
  maintenanceAvailable.register(require('./routes/ssl'))
  maintenanceAvailable.register(require('fastify-cookie'))
  maintenanceAvailable.register(require('fastify-static'), {
    root: path.join(__dirname, '../public')
  })

  maintenanceAvailable.register(
    async API => {
      // API
      API.register(require('./hooks/maintenance_manager'))
      API.register(require('./api/without_session/reader'))
      API.register(require('./api/without_session/book'))
      API.register(require('./api/without_session/auth'))
      API.register(require('./api/without_session/chapter'))
      API.register(require('./api/with_session_on_demand/chapter'))
      API.register(require('./api/with_session_on_demand/book'))

      API.register(async withSession => {
        withSession.register(require('./hooks/session_hook'))
        withSession.register(require('./hooks/role_check'))
        withSession.register(require('./api/with_session/book'))
        withSession.register(require('./api/with_session/cookieRoom'))
        withSession.register(require('./api/with_session/reader'))
        withSession.register(require('./api/with_session/theme'))
        withSession.register(require('./api/with_session/logout'))
        withSession.register(require('./api/with_session/adminka'))
        withSession.register(require('./api/with_session/patreon'))
        withSession.register(require('./api/with_session/chapter'))

        withSession.register(async withoutBan => {
          withoutBan.register(require('./hooks/ban_check'))
          withoutBan.register(require('./api/without_ban/reader'))
          withoutBan.register(require('./api/without_ban/similar'))
          withoutBan.register(require('./api/without_ban/chapter'))
          withoutBan.register(require('./api/without_ban/book'))
          withoutBan.register(require('./api/without_ban/admin'))
        })
      })
    },
    { prefix: '/api' }
  )
})
```
