### ISSUE TITLE
Request#context deprecation warning on test suite after upgrade to 4

### ISSUE THREAD

**Issue by DellaMoraWalter** [fastify/help#761]
#### What was the result you received?

After upgrade from fastify 2 to 4 a deprecation warning is traced by tap test suite.

[FSTDEP012] FastifyDeprecation: Request#context property access is deprecated. Please use "Request#routeConfig" or "Request#routeSchema" instead for accessing Route settings. The "Request#context" will be removed in `fastify@5`

I've not founded references on web for this warning.

In test log there is this suggestment:
(Use `node --trace-warnings ...` to show where the warning was created)

but honestly I've not founded how to use 'node --trace-warnings' with a project start script that inside have fastify start.

#### What did you expect?

I want to resolve warning

#### Context

* *node version*: 18.9.0
* *fastify version*: 4.6.0
* *os*: Mac, Linux

Warnings appear during test suite execution on mac and on linux container

Thanks for any help.

**Comment by jsumners** [comment]
Have you tried doing what the warning suggests?

**Comment by kibertoad** [comment]
@jsumners it may be coming from one of the plugins, e. g. fasyify-helmet only got rid of this warning today. 
@DellaMoraWalter which ones do you use?

**Comment by DellaMoraWalter** [comment]
I looked in the sources of fastify to understand what the warning refers to, in my code I don't directly use the 'context' property that raises it.
@kibertoad you are right, I tried to comment out the line introducing fastify/helmet and the warning disappears.

I was looking at the Helmet sources to learn more but... under my eyes @mcollina published a fix with version 10.0.1 that solves the problem ...wow

thanks for support
