### ISSUE TITLE
Other plugins are running in the plugin scope(@fastify/cors)

### ISSUE THREAD

**Issue by Lilja** [fastify/help#767]
#### What are you trying to achieve, or the steps to reproduce?

I want to run certain routes with CORS, others, like /healthcheck shouldn't need it because the load balancer managing the container shouldn't need it. I couldn't find anything in fastify/cors about whitelisting/opt out of routes. So my thought process was to separate them using plugins.
Something like this.
* Fastify server
  * Routes needing CORS
    * /v1/trpc
  * Routes not needing CORS
    * /healthcheck

```typescript
const trpcRoutes = fp((
  fastify: FastifyInstance,
  options: FastifyPluginOptions,
  next: (error?: FastifyError) => void
) => {
  fastify.register(import('@fastify/cors'), {/* omitted */})
  fastify.register(fastifyTRPCPlugin, { /* omitted */ })
  next();
});

const healhCheckRoutes = fp((
  fastify: FastifyInstance,
  options: FastifyPluginOptions,
  next: (error?: FastifyError) => void
) => {
  fastify.get('/healthcheck', async (req, reply) => reply.send("all good"));
  next();
});

const server = fastify({})
server.register(fp((
  fastify: FastifyInstance,
  options: FastifyPluginOptions,
  next: (error?: FastifyError) => void
) => {
  fastify.register(healhCheckRoutes);
  fastify.register(trpcRoutes, {prefix: './v1'});
});
```

#### What was the result you received?
When I curl `/healthcheck`, the `@fastify/cors` plugin will execute, even though I haven't defined it in that scope(????). Shouldn't my scope be clean from any plugins in `healthCheckRoutes`? Why is cors validation running?

<details>

<summary>Click to see curl</summary>

```
$ curl -v -H "origin: example.com" http://0.0.0.0:3000/healthcheck
*   Trying 0.0.0.0:3000...
* Connected to 0.0.0.0 (127.0.0.1) port 3000 (#0)
> GET /v1/trpc HTTP/1.1
> Host: 0.0.0.0:3000
> User-Agent: curl/7.77.0
> Accept: */*
> origin: https://example.com
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< vary: Origin
< content-type: application/json; charset=utf-8
< content-length: 74
< x-commit-sha: dev
< Date: Tue, 11 Oct 2022 12:40:31 GMT
< Connection: keep-alive
< Keep-Alive: timeout=72
<
* Connection #0 to host 0.0.0.0 left intact
{"statusCode":500,"error":"Internal Server Error","message":"Not allowed"}⏎ 
```

</details>

#### What did you expect?
No other plugins to be used(`@fastify/cors`)

#### Context

* *node version*: 18.8.0
* *fastify version*: ^4.8.1
* *os*: Mac
* *any other relevant information*:

**Comment by jsumners** [comment]
https://www.fastify.io/docs/latest/Reference/Encapsulation/

**Comment by Eomm** [comment]
You need to play with encapsulation
https://stackoverflow.com/questions/61020394/what-is-the-exact-use-of-fastify-plugin/61054534#61054534

So, the `healthCheckRoutes` must be in an isolated plugin from the `@fastify/cors`
