### ISSUE TITLE
@fastify/session using session-file-store overrides all console errors

### ISSUE THREAD

**Issue by elverskog** [fastify/help#768]
I can't find anyone posting about my issue. Any help would be much appreciated.
I'm not sure if this is the right channel but let me explain.

When I instantiate @fastify/session using session-file-store, it negates/overrides any error output in the console.
So say I forget to import something or have a typo, there is _always_ the same, as below.
If I don't have any code errors, things run fine.

_Error: Cannot set headers after they are sent to the client
    at __node_internal_captureLargerStackTrace (node:internal/errors:484:5)
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.writeHead (node:_http_server:347:21)
    at onSendEnd (/home/ee/code/bb/bb-marko/node_modules/fastify/lib/reply.js:580:7)
    at wrapOnSendEnd (/home/ee/code/bb/bb-marko/node_modules/fastify/lib/reply.js:519:5)
    at next (/home/ee/code/bb/bb-marko/node_modules/fastify/lib/hooks.js:213:7)
    at /home/ee/code/bb/bb-marko/node_modules/@fastify/session/lib/fastifySession.js:189:9
    at /home/ee/code/bb/bb-marko/node_modules/@fastify/session/lib/session.js:171:9
    at /home/ee/code/bb/bb-marko/node_modules/session-file-store/lib/session-file-helpers.js:231:33 {
  code: 'ERR_HTTP_HEADERS_SENT'
}_

If I remove the registering of the session-file-store, and just use the default memory store, I get normal error output.

**The reason I ask here** is that the @fastify/session docs points to express/session via:
"Compatible to stores from express-session."
In their list I picked session-file-store as I just need something relatively simple to run "pre-scale".

If this is not an error that can be solved with me re-configuring something, I don't think I can expect a fix from the session-file-store devs (but I can ask) as they say up top:
"Session file store for Express and Connect. Also you can use it with Koa"

If you have any recommendations for an alternate "easy setup" and "low scale" session store (e.g. that isn't on a separate port, like say Redis) that would also be great.

**Here's my basic set-up details:**
I'm using fastify with marko js btw

- Node.js v18.10.0
- marko@5.21.9
- fastify@4.7.0
- @fastify/session@10.0.0
- @fastify/cookie@8.3.0

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by elverskog** [comment]
Hey @mcollina 
Thx for the reply. Sorry for my delay
Of course in building a small reproduction of this it works :)
So I will go through the dance of adding pieces back in and (hopefully) see what is causing the issue

**Comment by mcollina** [comment]
Note if you need a simple session store.. I'd use a cookie-based solution.

**Comment by Uzlopak** [comment]
The file session store is throwing errors when a file(=session) does not exist.
https://github.com/fastify/session/issues/140

I think it happens because of this line
https://github.com/valery-barysok/session-file-store/blob/b89a42b00f24e720bb9d07cc7ddf72ef6c43c7bc/lib/session-file-helpers.js#L204

**Comment by elverskog** [comment]
Thx @Uzlopak and @mcollina 

In the short term (on dev at least) I'll likely just use something else
I'm not committed to storing sessions as files
We are using firebase as a DB, so on prod we may wind up using that

That said, I just installed and setup connect-lowdb 
Works ok BUT now I am getting the same error override (the one pasted up top)
So I'm not sure if it is session-file-store that is the issue
It may be something with with the hot-reloader, Vite etc and how that works with @fastify/session's store connection

@mcollina When you suggest a cookie store, do you mean outside of using @fastify/session?

**Comment by mcollina** [comment]
Just use https://github.com/fastify/fastify-secure-session and you should be good.

**Comment by elverskog** [comment]
thx @mcollina 
That seems to be working!
I suppose I need to read up on the options for fastify-cookie though :)
