### ISSUE TITLE
Validation: block undefined properties

### ISSUE THREAD

**Issue by PatrickHeneise** [fastify/help#77]
#### What are you trying to achieve or the steps to reproduce?

I wrote a schema for a route to create a new entity. I'd like the validation to only accept the pre-defined properties and block everything else:

```is
fastify.route({
    method: 'POST',
    url: '/test',
    schema: {
      body: {
        type: 'object',
        properties: {
          name: { type: 'string' }
        }
      }
    }
    ...
})

curl -H "Content-Type: application/json" -XPOST localhost:3000/test -d '{"test": "test"}'
```

#### What was the result you received?

This call passes even though "test" is not defined in the schema.

#### What did you expect?

The call should fail

#### Context

* *node version*: 10
* *fastify version*: >=2.3.0
* *os*: Mac

**Comment by nwoltman** [comment]
Here's the documentation for defining objects with Ajv: https://github.com/epoberezkin/ajv/blob/master/KEYWORDS.md#keywords-for-objects
You'll find the answer you're looking for there.

**Comment by PatrickHeneise** [comment]
Excellent, thanks! Didn't know exactly where to look for this.
