### ISSUE TITLE
Can't get @fastify/swagger to work using fastify generate

### ISSUE THREAD

**Issue by richardtknight** [fastify/help#770]
#### The problem
I have created a new fastify project using the scaffold with 
```js
fastify generate myproject
```

Everything else works just fine, but I've installed @fastify/swagger and I can't seem to get it to actually output anything.
I've followed all the docs I could find and as such, my app.js files looks like this:

```js
'use strict';

const path = require('path');
const AutoLoad = require('@fastify/autoload');
require('dotenv').config();

module.exports.options = {
	dotenv: true,
	data: process.env,
};

module.exports = async function (fastify, opts) {
	fastify.register(AutoLoad, {
		dir: path.join(__dirname, 'plugins'),
		options: Object.assign({}, opts),
	});

	fastify.register(AutoLoad, {
		dir: path.join(__dirname, 'routes'),
		options: Object.assign({}, opts),
	});

	fastify.register(require('@fastify/swagger'), {
		routePrefix: '/docs',
		swagger: {
			info: {
				title: 'My FirstAPP Documentation',
				description: 'My FirstApp Backend Documentation description',
				version: '0.1.0',
				termsOfService: 'https://mywebsite.io/tos',
				contact: {
					name: 'John Doe',
					url: 'https://www.johndoe.com',
					email: 'john.doe@email.com',
				},
			},
			externalDocs: {
				url: 'https://www.johndoe.com/api/',
				description: 'Find more info here',
			},
			host: '127.0.0.1:3000',
			basePath: '',
			schemes: ['http', 'https'],
			consumes: ['application/json'],
			produces: ['application/json'],
			tags: [
				{
					name: 'User',
					description: "User's API",
				},
			],
			definitions: {
				User: {
					type: 'object',
					required: ['id', 'email'],
					properties: {
						id: {
							type: 'number',
							format: 'uuid',
						},
						firstName: {
							type: 'string',
						},
						lastName: {
							type: 'string',
						},
						email: {
							type: 'string',
							format: 'email',
						},
					},
				},
			},
		},
		uiConfig: {
			docExpansion: 'none', // expand/not all the documentations none|list|full
			deepLinking: true,
		},
		uiHooks: {
			onRequest: function (request, reply, next) {
				next();
			},
			preHandler: function (request, reply, next) {
				next();
			},
		},
		staticCSP: false,
		transformStaticCSP: (header) => header,
		exposeRoute: true,
	});

	fastify.ready((err) => {
		if (err) throw err;
		fastify.swagger();
	});
};
```

Obviously the swagger object is simply copied and pasted from the docs.

I have multiple routes in one file (users.js) which resides in my "routes" folder.
Essentially a basic view all, view one, add, update, delete user setup.

```js
module.exports = async function (fastify, options) {
	// Get all users
	fastify.get(
		'/users',
		getUsersOpts,
		async (req, reply) => await getUsers(fastify, req, reply)
	);

	// Get a user
	fastify.get(
		'/user/:id',
		getUserOpts,
		async (req, reply) => await getUser(fastify, req, reply)
	);

	// Add a user
	fastify.post(
		'/user',
		addUserOpts,
		async (req, reply) => await addUser(fastify, req, reply)
	);

	// Update a user
	fastify.put(
		'/user/:id',
		updateUserOpts,
		async (req, reply) => await updateUser(fastify, req, reply)
	);

	// Delete a user
	fastify.delete(
		'/user/:id',
		deleteUserOpts,
		async (req, reply) => await deleteUser(fastify, req, reply)
	);
};

```

My understanding is that swagger should be automatically generating documentation based on the routes which should be present on the "/docs" path.

However what I get instead is

```
{"message":"Route GET:/docs not found","error":"Not Found","statusCode":404}
```

From what I've been able to find, I've got the swagger config in the right place (after the routes has autoloaded), but I've tried switching it around to before as well, with the exact same outcome.

I've searched everywhere but only really found answers relating to "fastify-swagger" which is now deprecasted and replaced by this version "@fastify/swagger".

This may be more of a swagger question potentially, but there doesn't appear to be much config required, so my immediate though was that it may be something to do with the "fastify generate" scaffold project?

#### What are you trying to achieve, or the steps to reproduce?

Describe your issue here, include as many details as necessary to reproduce the issue, 
or implement a missing functionality. If you are reporting a bug, you will get a faster response 
if you submit a pull request with a failing test.

#### Context

* *node version*: v16.17.0
* *fastify version*: ^4.0.0
* *os*: Mac

package.json
```js
{
  "name": "myproject",
  "version": "1.0.0",
  "description": "This project was bootstrapped with Fastify-CLI.",
  "main": "app.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "test": "tap \"test/**/*.test.js\"",
    "start": "fastify start -l info app.js",
    "dev": "fastify start -w -l info -P app.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@fastify/autoload": "^5.0.0",
    "@fastify/postgres": "^5.1.0",
    "@fastify/swagger": "^8.0.0",
    "dotenv": "^16.0.3",
    "fastify": "^4.0.0",
    "fastify-cli": "^5.5.0",
    "fastify-plugin": "^4.2.1",
    "pg": "^8.8.0"
  },
  "devDependencies": {
    "tap": "^16.1.0"
  }
}
```

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by kibertoad** [comment]
You are missing `exposeRoute: true,`, I think

**Comment by Asjas** [comment]
@richardtknight I don't see `swagger-ui` being used in your project. So no Swagger route will be served.

https://github.com/fastify/fastify-swagger-ui

**Comment by kibertoad** [comment]
@Asjas That depends on the version of fastify-swagger used, only 8 is missing the ui

**Comment by kibertoad** [comment]
See https://github.com/fastify/fastify-swagger/blob/master/MIGRATION.md for the latest version

**Comment by richardtknight** [comment]
> @richardtknight I don't see `@fastify/swagger-ui` being used in your project. So no Swagger route will be served.
> 
> You are using ` "@fastify/swagger": "^8.0.0",` so it's the cause of your issue - install and use `@fastify/swagger-ui`.
> 
> https://github.com/fastify/fastify-swagger-ui

Thanks, so much. I've installed swagger-ui now, and it was getting the docs page, but nothing on it.
So i shuffled my swagger objects in the app.js file to above the autoload stuff, and bingo it all appeared correctly.

Your help is much appreciated.
