### ISSUE TITLE
Question: Fastify plugin route options vs config

### ISSUE THREAD

**Issue by xxRockOnxx** [fastify/help#777]
I am currently following [fastify-helmet](https://github.com/fastify/fastify-helmet) as an inspiration for writing plugin.

You can configure `helmet` per route by doing something like:

```js
fastify.get(
  '/route-with-helmet',
  {
    helmet: {
      // ...stuff
    },
  },
  async (request, reply) => {
    return "stuff"
  }
)
```

The plugin will check if the route has `helmet` option and move it to `config`.
(It can be seen on this lines: https://github.com/fastify/fastify-helmet/blob/v10.0.2/index.js#L26-L30)

So that `onRequest`, you can get the values from `routeConfig`.
(It can be seen on this line: https://github.com/fastify/fastify-helmet/blob/v10.0.2/index.js#L38)

#### Question:

Why is it designed this way?

On the [docs](https://www.fastify.io/docs/latest/Reference/Routes/#config), you can just pass straight to `config`.

The `onRoute` hook can then be avoided if it was done this way.

#### Context

* *node version*: 16
* *fastify version*: 4
* *os*: Linux
* *any other relevant information*:

**Comment by metcoder95** [comment]
Hey! It's designed in that way to have the option to disable helmet by just passing `helmet: false` or set a custom configuration for the route by passing a full `helmet: helmetOptions` object.

It just does a validation/normalization of the helmet custom options provided when registering the routes and nothing else. This can come in handy when you offer such granular configuration over the routes and want to normalize the configuration into a specific shape that your plugin supports.

**Comment by xxRockOnxx** [comment]
@metcoder95 i'm aware of that part. my question is more of why route option vs config

i.e

```javascript
fastify.route({
  method: "POST",
  url: "/something",
  helmet: false
})
```

verus

```javascript
fastify.route({
  method: "POST",
  url: "/something",
  config: {
    helmet: false
  }
})
```

As you can seen from here: https://github.com/fastify/fastify-helmet/blob/v10.0.2/index.js#L26-L30

The plugin ultimately just moves it to `config`. Why not put it there from the first place? Backwards compatibility maybe?

**Comment by Eomm** [comment]
The onroute hook will give you the possibility to define some defaults during the plugin registration phase, meanwhile applying some custom route configuration.

The config route property is documented and helpful but it is not used every where in the fastify ecosystem 😅 I think we have the opportunity to normalize this thing as it is confusing for users! 
Its main scope is to avoid conflicts between the Fastify's parameters (such as url, method etc). So in those cases it is not an issue

**Comment by xxRockOnxx** [comment]
> The onroute hook will give you the possibility to define some defaults during the plugin registration phase, meanwhile applying some custom route configuration.

I think you can get/set the default from registration options instead like in the following:

```js
async function helmet(fastify, defaultOptions) {
  // stuff
}

fastify.register(helmet, {
  // default options
})
```

> Its main scope is to avoid conflicts between the Fastify's parameters (such as url, method etc). So in those cases it is not an issue

I see. That makes sense.

If I understand this correctly, I'm not missing out on anything but rather the ecosystem currently is not following the documented approach although nothing is wrong with it as long as it dont conflict with Fastify's parameters.

If this is the case, I think having it in `config` after all is the way to go:

- no possible conflicts
- no extra code needed for copying route options to config

---

Thanks @Eomm! I appreciate a member responding.
