### ISSUE TITLE
Do I need to expose the swagger.json manually?

### ISSUE THREAD

**Issue by alphaone** [fastify/help#778]
## 💬  Exposing the _swagger.json_ manually

I don't need `swagger-ui` in my project, but I still want to access the swagger schema information as JSON. Do I really need to expose the _swagger.json_ like this, or is there a better way to do it?

```js
await fastify.register(fastifySwagger, {
  ...
})
fastify.get(`/api-docs`, { schema: { hide: true } }, () => fastify.swagger())
````

## Your Environment

- *node version*: 18
- *fastify version*: 4.9.2
- *os*: Mac

**Comment by mcollina** [comment]
Yes, it's the right way to do it.
