### ISSUE TITLE
Using the object model for fastify-swagger examples by duplicating my route/paths definitions?

### ISSUE THREAD

**Issue by jschuur** [fastify/help#779]
I'd like to rename the response `examples` drop-down menu below and give the entries custom names rather than example1 and example2. Should that be possible with the current releases of fastify-swagger (8.0.0) and fastify-swagger-ui (1.1.0)?

![CleanShot 2022-10-24 at 15 17 25](https://user-images.githubusercontent.com/92457/197548059-4f013dbd-1576-474e-9edc-75e7f35e9273.png)

The OpenAPI 3.1.0 spec still says you can use the [object format](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#exampleObject) to name your examples, but fastify-swagger complains and says it needs to be an array:

```
/Users/joostschuur/Code/.../node_modules/fastify/lib/route.js:364
              throw new FST_ERR_SCH_SERIALIZATION_BUILD(opts.method, url, error.message)
                    ^
FastifyError [Error]: Failed building the serialization schema for GET: /api/v1/campaign/summary/:campaignId, due to error schema is invalid: data/examples must be array
```

I suspect this is happening to me because I don't define any `paths` for endpoints in the options object that I pass in to register fastify-swagger, so it's converting the [fastify route options](https://www.fastify.io/docs/latest/Reference/Routes/#routes-options) and that's the format that doesn't support an `examples` in object format, so it never gets a chance to convert it into something in the OpenAPI 3.x options for fastify-swagger?.

Fastify routes take in a JSON Schema and it only loosely defines the [examples property](https://json-schema.org/draft/2020-12/json-schema-validation.html#name-examples), without being as explicit as OpenAPI.

I would like to set up my examples like this

```json
"examples":{
   "first example":{
      "value":{
         "meta":{
            "campaignName":"Sample campaign",
            "campaignId":123
         },
         "summary":{
            "impression":234,
            "engagement":123,
            "questions_completed":1234,
            "demographics_completed":890,
            "pledge_completed":789,
            "external_link_clicked":456
         }
      }
   },
   "second example":{
      "value":{
         "meta":{
            "campaignName":"Sample campaign",
            "campaignId":123
         },
         "summary":{
            "2021-01-01":{
               "impression":234,
               "engagement":123,
               "questions_completed":1234,
               "demographics_completed":890,
               "pledge_completed":789,
               "external_link_clicked":456
            },
            "2021-01-02":{
               "impression":234,
               "engagement":123,
               "questions_completed":1234,
               "demographics_completed":890,
               "pledge_completed":789,
               "external_link_clicked":456
            }
         }
      }
   },
```

My question: Is there a best practice way around this? If I also define my endpoints via `paths` in the options object that I pass into `fastify.register` for fastify-swagger, I end up duplicating my definitions, because the two formats don't seem to be the same.

**Comment by mcollina** [comment]
There isn't a best practice around this. PRs to fastify-swagger adding some informations and tests would be handy.

**Comment by jschuur** [comment]
> There isn't a best practice around this. PRs to fastify-swagger adding some informations and tests would be handy.

I fully understand that the open sourced model is based on people pitching in to constantly make the code better, but at this point I'm still trying to understand if this is a true problem, or I just haven't discovered an existing solution :)

Sounds like it's the former here.

**Comment by climba03003** [comment]
The problem is you are placing `OpenAPI 3` format inside the `JSON Schema` which never be a possible case.

If you plan to use `@fastify/swagger` with dynamic mode, please follow the `JSON Schema` format. It will be transformed to `OpenAPI 3` inside the plugin. If the transformation behavior is wrong, you can open a issue or directly send PR for improvement.

**Comment by jschuur** [comment]
> If you plan to use `@fastify/swagger` with dynamic mode, please follow the `JSON Schema` format. It will be transformed to `OpenAPI 3` inside the plugin. If the transformation behavior is wrong, you can open a issue or directly send PR for improvement.

It looks like @fastify/swagger (via the JSON schema spec) takes the entire value of each `examples` array element and uses that as the `value` for the OpenAPI 3 definition that it transforms it to. This wouldn't leave any place to define the custom name within that array.

New idea: I can use [fastify-openapi-glue](https://github.com/seriousme/fastify-openapi-glue). This gives @fastify/swagger the richer examples format and I avoid duplicating my definitions. This could be the best practice I was looking for.

(I've also been saying 'fastify-swagger' when I meant '@fastify/swagger' of course).

**Comment by mcollina** [comment]
> It looks like @fastify/swagger (via the JSON schema spec) takes the entire value of each examples array element and uses that as the value for the OpenAPI 3 definition that it transforms it to. This wouldn't leave any place to define the custom name within that array.

It puzzles me why `@fastify/swagger` can't be improved to support this use case. Anyway, I'm glad you find your answer.

**Comment by jschuur** [comment]
> It puzzles me why `@fastify/swagger` can't be improved to support this use case. Anyway, I'm glad you find your answer.

Maybe it could. If the issue is just that @fastify/swagger currently assumes it's a JSON schema format `examples` object, a PR could certainly propose to expand this to also cover the object format in its transforms.

Would this relatively small benefit justify making a format change of this magnitude? Difficult for me to judge as someone who's only started to use fastify and the swagger plugins, which is why I took this to a discussion/issue here.

Alternatively, could the naming info be passed along otherwise? Feels clunky to fit the labels in elsewhere.

Either way, I'm glad this thread got me to indirectly discover `fastify-openapi-glue` :)

**Comment by jschuur** [comment]
I went a different route via a [transform](https://www.npmjs.com/package/@fastify/swagger#transform). I define `examples` as an array of `{name, value}` objects in my route definition and then expand that into the OpenAPI object `examples` format in the transform:

```js
transform: ({ schema, url }) => {
    if (schema?.response) {
      Object.keys(schema.response).forEach((key) => {
        const examples = schema.response[key]?.examples;

        if (Array.isArray(examples)) {
          schema.response[key].examples = examples.reduce(
            (acc, example, index) => ({
              ...acc,
              [example.name || `example ${index}`]: {
                value: example.value,
              },
            }),
            {}
          );
        }
      });
    }

    return { schema, url };
}
```

The rest of fastify doesn't care what format `examples` is as long as it's an array, and this way, `@fastify/swagger` gets the object format.

Thanks, @climba03003 for mentioning dynamic mode, since it made me check the docs again and find the transform function.
