### ISSUE TITLE
Basic auth only for autoload prefix routes

### ISSUE THREAD

**Issue by sumitgoelpw** [fastify/help#78]
I am using `fastify-autoload` and want to use `fastify-basic-auth` but I couldn't figure out the best way to apply the authentication only for routes loaded using `fastify-autoload`. I think one way is to use `preValidation` or `preHandler` hook per route basis but it would be very inefficient/error-prone. Please advise.

```js
fastify.register(AutoLoad, {
  'dir': path.join(__dirname, './routes/rest/v1'),
  'options': { 'prefix': '/rest/v1' }
})
```

* *node version*: v10.15.3
* *fastify version*: 2.3.0
* *os*: Mac, Docker Alpine

**Comment by mcollina** [comment]
The best way is to wrap the autoload registration into another plugin, and add the hooks there. Let us know if you need further help.

**Comment by MuhammadAli-208** [comment]
any other workaround here ?
