### ISSUE TITLE
HELP - PIPE STREAM and add compression to response 

### ISSUE THREAD

**Issue by Z3NTL3** [fastify/help#789]
### Environment
Node ``v16.18.1``
Linux ``Linux emre 4.15.0-196-generic #207-Ubuntu SMP Thu Oct 27 21:24:58 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux``
Fastify ``^4.8.1``

### Question/Issue
My application is sending on route ``/api/stream/:token`` an HTTP REQUEST to a specific Video Player URL, then pipes this HTTP stream and writes the data chunks into ``res.raw`` object. 

After everything is ended it should compress, but it doesn't. And yet I dont know why...

Could someone help me, I'll appreciate that!

### SRC
```js
// In '/api/stream/:token' route
  let rep = await axios({
    decompress: false,
    method: "get",
    url: iframe.playerURL,
    headers: opts,
    timeout: 5000,
    responseType: "stream",
    transformResponse(data) {
      return data.pipe(zlib.createBrotliDecompress());
    },
  });
  let HLS = rep.data;

  function rawWriter(HLS, resObj) {
    return new Promise((resolve) => {
      HLS.on("data", (data) => {
        resObj.raw.write(data);
      });
      HLS.on("end", () => {
        resObj.raw.writeHead(200, {
          "Content-Type": "text/html; charset=UTF-8",
        });
        return resolve();
      });
    });
  }
  await rawWriter(HLS, res);
  return res.compress(res.raw);
```

### Fastify/@compress Settings
```js
 await fastify.register(import("@fastify/compress"), {
    global: true,
    inflateIfDeflated: true,
    treshold: 1042,
  });
```

**Comment by Eomm** [comment]
If you write on `req.raw`, `Fastify/@compress` does acts: you need to use the fastify API to make it works.

This should work:

```
...
let HLS = rep.data;
res.type('text/html; charset=UTF-8')
return res.send(HLS)
```

**Comment by Z3NTL3** [comment]
Hey thanks :) It worked.

So through Fastify API it get precedence over ``res.raw`` (``http.ServerResponse``)?

**Comment by Eomm** [comment]
> So through Fastify API it get precedence over res.raw (http.ServerResponse)?

When you deal with native HTTP request (`res.raw`), Fastify loses its control.
It is like bypassing the framework actually - in this case you should use `hijack`, but it is a rare use case https://www.fastify.io/docs/latest/Reference/Reply/#hijack
