### ISSUE TITLE
schema.querystring with $ref

### ISSUE THREAD

**Issue by PatrickHeneise** [fastify/help#79]
#### What are you trying to achieve or the steps to reproduce?

I'm trying to include my pagination schema (`page`, `count`) to endpoints returning lists.

schemas/definitions.json:

```json
{
  "$id": "/definitions.json",
  "type": "object",
  "definitions": {
    "pagination": {
      "$id": "pagination",
      "type": "object",
      "properties": {
        "page": { "type": "number" },
        "count": { "type": "number", "maximum": 100, "minimum": 0 }
      }
    }
  }
}
```

route.js

```js
schema: {
  querystring: {
    type: 'object',
    properties: { $ref: '/definitions.json#/definitions/pagination' }
  },
  response: {
    200: {
      type: 'array',
      items: {
        $ref: '/responses.json#/definitions/Things'
      }
    }
  }
}
```

I tried various approaches, the only one which seems to work is:

```js
querystring: {
  type: 'object',
  properties: 'pagination#'
},
```

But then I'd need to have "pagination" as a separate schema which isn't very convenient. Would be great to have the same consistent $ref behaviour inside the schema.

#### What was the result you received?

```
Error: schema is invalid: data.properties['$ref'] should be object,boolean
    at Ajv.validateSchema (/api/node_modules/ajv/lib/ajv.js:177:16)
```

#### What did you expect?

Include the pagination schema in query string.

#### Context

* *node version*: 8,10
* *fastify version*: >=2.3.0

**Comment by Eomm** [comment]
Your issue is caused by the `$id` format you have chosen.

Check out [these examples](https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md#adding-a-shared-schema)
