### ISSUE TITLE
Can you add docs how to use typescript with fastify sensible?

### ISSUE THREAD

**Issue by gustawdaniel** [fastify/help#793]
I mean this plugin:

https://github.com/fastify/fastify-sensible

and this docs:

https://www.fastify.io/docs/latest/Reference/TypeScript/

It would be awesome, it you would publish working code example.

I have

```
  const app = fastify({})

  app.register(fastifySensible)
```

but still exporting simple `FastifyInstance` and do not have types for:

```
fastify.httpErrors.notFound()
```

**Comment by Uzlopak** [comment]
The export of the fastify package is not a FastifyInstance but the "FastifyConstuctor".

In your case `app` is of type FastifyInstance. So you should do `app.httpErrors.notFound()`
