### ISSUE TITLE
Fastify with bearer-auth

### ISSUE THREAD

**Issue by aminrazavi78** [fastify/help#795]
## 💬  Question here 
Hi everybody;

I have used from `@fastify/bearer-auth` for authentication in my server. When I used it, it is applied on all of my routers. I want that one of my router is not checked for authentication. What can I do for this exeption? 

My code:
```js
import fastify from "fastify"
import bearerAuthPlugin from "@fastify/bearer-auth";

export function build(opts = {}) {
	const app = fastify(opts);

       const keys = new Set(["token_1", 'token_2'])
       app.register(bearerAuthPlugin, {keys})

	app.get('/ping', async (reply) => {
		return 'pong\n';
	});


	app.get('/hi', async (reply) => {
		reply.send({authenticated: false})
		return 'hey you!\n';
	});
````

as it can be clearly seen, one of my router is request to `/ping` endpoint by `get` method. I want to this specific router wouldn't has been checked by this authentication.

Tanks for help.

## My Environment

- *node version*: 18.12.0
- *fastify version*: 3.28.0
- *@fastify/bearer-auth*: 7.0.1
- *os*: Linux (Mint)

**Comment by Asjas** [comment]
The best thing to do is to wrap the part that needs to be authenticated in a plugin as that will encapsulate it.

https://www.fastify.io/docs/latest/Guides/Plugins-Guide/

**Comment by jsumners** [comment]
https://www.fastify.io/docs/latest/Reference/Encapsulation/

**Comment by aminrazavi78** [comment]
thanks a lot.

**Comment by Eomm** [comment]
I wrote a detailed blog post about it: https://backend.cafe/the-complete-guide-to-the-fastify-plugin-system
