### ISSUE TITLE
Fastify Plugin Async Decorators Problem

### ISSUE THREAD

**Issue by Z3NTL3** [fastify/help#798]
## 💬  Question here 
On the documentation website provided by Fastify, it sentenced that we can manipulate ASYNC decorators using fastify register together with the fastify-plugin module. I did the exact thing but didnt work out and there is clearly no documentation about this anywhere. I have read multiple articles and docs provided by Fastify but this concept was only being told but not examinized with examples.
```js
    app.register(fp((fastify, opts, done) => {
        fastify.decorate('fastRESTcomp', async (header,data) => {
            const brEncoding = new RegExp('br')
            const gzipEncoding = new RegExp('gzip')
    
            if(brEncoding.test(header)){
                data = await brotli(data)
            } else if(gzipEncoding.test(header)){
                data = await gzip(data)
            } else {
                return { encoding: null, data: data}
            }
            return { encoding: brEncoding.test(header) ? 'br' : 'gzip', data: data}
    
        })
        
        done()
    }))
````

Its not working due to the Async 

## Environment

- *node version*: 16
- *fastify version*: >=^4.10.2
- *os*: Womdows

**Comment by jsumners** [comment]
What isn't working? Is there an error? You have not provided any example of usage.

**Comment by Z3NTL3** [comment]
Its not working nothing is getting returned
