### ISSUE TITLE
callback function 'Next' in request Handlers as it was in expressJs

### ISSUE THREAD

**Issue by arihantdaga** [fastify/help#8]
I am migrating my existing express app to fastify as it looked very promising to me . But since i am very new i am getting few problems. 
In our express app we used to write `next()` or `next(err)` in our main request handler function for example in following context - 

in the File `Routes.js`

```
router.get("/something", (req,res,next)=>{
try{
// Something is right then send
return res.json({Success: 1});
}
catch(err){
return next(err);
}
})

```

And then somewhere in my app.js

```
app.use("/routes",routes.js );

app.use(function(err, req, res, next) {
// I handle and modify my error object here and after that send user some public display message 

return res.status(500).json({message: "Custom Message"});
})

```

For fastify, I looked into Hooks, i see there are hooks for prehandler but there is no such thing as afterHandler. And also i want to register this same errorHandlers for all my requests and not writing it explicitly for all request. 
Is there a way to do similar things in fastify ? 
I Will be very thankful for your help.

**Comment by delvedor** [comment]
Checkout the [custom error handler](https://github.com/fastify/fastify/blob/master/docs/Server-Methods.md#seterrorhandler).

**Comment by arihantdaga** [comment]
Thank you @delvedor .  But how do i transmit error from my handler to the custom error handler. 
I wrote this in my code. 
In file `app.js`
```

fastify.setErrorHandler(function (error, request, reply) {
  console.log(error);
  reply.send({err: "Unknown Error Occured"});
})
```
And in my routes file 
```
fastify.get("/dummy", (req,res,next)=>{
    console.log("I am here"); 
    try{
        // Something
        return res.send({success: 1});
    }catch(err){
        return next(err);  // -->> next() is not a function. Then how do i transmit this to our 
    }
});
```

**Comment by delvedor** [comment]
If you are inside a standard route handler just return the error:
```js
fastify.get('/', (req, reply) => {
  reply.send(new Error('kaboom'))
})
```
Otherwise, if you are inside async route handlers return the error or throw:
```js
fastify.get('/', async (req, reply) => {
  throw new Error('kaboom')
  // return new Error('kaboom') is valid as well
})
```

There is not such thing as `next` inside route handlers.

**Comment by arihantdaga** [comment]
Okayyy.. Got it. Just one more question.
Can i send a custom error object in next(). Because many times i was sending metadata to the error object. But here i am think the next is accepting only Error Objects.
For ex - 

```
try{
}
catch(err){
return next({err:err, meta_1: "SomValue", user: "userId"});
}

```

**Comment by arihantdaga** [comment]
Okayyy.. Got it. Just one more question.
Can i send a custom error object. Because many times i was sending metadata to the error object. But here i am think the customError will be triggered only if reply.send get an Error Instance. 
For ex this is what i had in my express app- 

```
try{
}
catch(err){
return next({err:err, meta_1: "SomValue", user: "userId"});
}

```
Any alternative in fastify ?

**Comment by nwoltman** [comment]
You could add a custom property directly to the error object:

```js
try {
}
catch (err) {
  err.meta = {meta_1: "SomValue", user: "userId"};
  reply.send(err);
}
```

And then in your error handler you could have something like:

```js
fastify.setErrorHandler(function (error, request, reply) {
  const meta = error.meta;
  if (meta) {
    reply.send({err: "Known Error Occured"});
    return;
  }

  reply.send({err: "Unknown Error Occured"});
})
```
