### ISSUE TITLE
How to forse log request?

### ISSUE THREAD

**Issue by ReTWi** [fastify/help#80]
I have a pino.js module

```
let log = pino({ level: 'warn' }, pino.destination(1))
export { log }
```

And server.js
`const https = fastify({  logger: log })`

How can i force log req (most of the time on error)?

```
fastify.get('/', function(req, res) {
  req.log.warn() // no headers - {"level":40,"time":,"pid":18296,"hostname":"","reqId":1,"msg":"","v":1}
  log.warn({ req }, 'message' ) // is this the only way?
  reply.send({ hello: 'world' })
})
```

**Comment by Eomm** [comment]
This remember me this PR
https://github.com/fastify/fastify/pull/1629

> onRequest and onResponse hooks to log the information you need and not get double log messages due to the enforced logging in Fastify.

So you can archive it with a plugin that adds [hooks](https://github.com/fastify/fastify/blob/master/docs/Hooks.md#requestresponse-hooks)

**Comment by ReTWi** [comment]
@Eomm but i don't want to log all the req/res, only if something happened in code.

**Comment by Eomm** [comment]
You need to provide more info, since that was not specified in the original post.

[Here](https://github.com/fastify/fastify/blob/master/docs/Logging.md) you will find all the docs about logging.
