### ISSUE TITLE
How to write schema definition for binary response (Buffer)

### ISSUE THREAD

**Issue by alphaone** [fastify/help#801]
## 💬  Question here 

I am using `JsonSchemaToTsProvider` as a type provider and define my schema as JSONSchema. All this works amazingly well.

The only problem I have is that I am unable to define a schema for a binary response (an PNG image as a buffer).

```js
fastify.withTypeProvider<JsonSchemaToTsProvider>().get(
    '/v1/render-image',
    {
      schema: {
        description: `renders an image`,
        produces: ['image/png', 'image/jpeg'],
        response: {
          200: {
            type: 'string',
            format: 'bytes',
            description: 'Rendered image',
          },
        },
      } as const,
    },
    async (req, reply) => {
      const buffer: Buffer = await renderImage()
      reply.type(`image/png`).send(buffer)
    },
  )
````

This gives me a type error on `.send(buffer)` that `Argument of type 'Buffer' is not assignable to parameter of type 'string'`. And I can understand that the compiler is complaining.

I only need to know how to correctly define the schema for a binary (Buffer) response

## Your Environment

- *node version*: 16
- *fastify version*: 4.10.2
- *os*: MacOS

**Comment by jsumners** [comment]
The types natively supported by JSON Schema are listed at https://json-schema.org/understanding-json-schema/reference/type.html
