### ISSUE TITLE
attachValidation negates all schema validation

### ISSUE THREAD

**Issue by elverskog** [fastify/help#802]
I'm trying to modify what a Fastify route returns for schema errors, per the docs here: 
[https://www.fastify.io/docs/latest/Reference/Validation-and-Serialization/#error-handling][1]

Specifically, I am using Fastify to serve HTML pages (an MPA) and so want the error to make it back to the UI, via inserting it in the HTML server side. 

I'm following the example's format but it is completely negating all validation when I add `{ schema, attachValidation: true }` to the route. 

To test/break it, I am passing a string like "shoe" in what is supposed to be a number field, or "funkyhat" for a field with a maxLength of 1

If I use this:
`app.post("/create-item", { schema, attachValidation: true }, (request, reply) => {`
the function just continues, bypassing my conditional check for `request.validationError` (which is always undefined).

If I use this:
app.post("/create-listing", schema, (request, reply) => {
it will return the "stock" Fastify 400 error like _Error: body/email must match format \"email\"_

Any ideas? Is there some config or other step needed to make the attachValidation option work?

## Your Environment

- *node version*: 19.0.0
- *fastify version*: 4.7.0
- *os*: Linux
The site using Vite and Marko for templating

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by elverskog** [comment]
Thx @mcollina Of course. Here's the repo:
https://github.com/elverskog/attach-validation-fail-example

**Comment by climba03003** [comment]
What I can tell by checking the code, `fastify` or `JavaScript` is function properly.

https://github.com/elverskog/attach-validation-fail-example/blob/a433034212a78d1870a57058a1cd5b9344d748d9/src/pages/form/form.page.js#L13-L28

In `L15-17`, you are checking  the `validationError` and send reply back. The important point is you didn't pause the execution right there. So, no matter the `validationError` is exist or not. The others code will execute.

It is how `JavaScript` works.

**Comment by Uzlopak** [comment]
So basically add a `return` after https://github.com/elverskog/attach-validation-fail-example/blob/a433034212a78d1870a57058a1cd5b9344d748d9/src/pages/form/form.page.js#L16

**Comment by elverskog** [comment]
@climba03003 and @Uzlopak - Thx for the quick reply but this suggested change did not work for me.

In previous efforts I actually just tried just a console.log inside the check for request.validationError
But it never output anything.
Also with no if statement, _for me_, request.validationError, at top of function, when logged, is "undefined".

Per how Javascript works: from what I can see `reply`, in Fastify, _does_ actually block the code after that from running (at least in declaring a route function).

So if I put:
```
    reply.code(400).send("xyz");
    console.log("test");
```
At the top of that function, "test" is not output in the terminal...so from what I can tell without deeper analysis, not run.

In hopes of getting this solved for my project, I'm curious if you actually cloned and ran the code.
And if so, why it is behaving differently for you?
I am open to (and hoping for) the fact that I'm doing something stupid
But I don't think what you suggested is actually the issue for my codebase/environment.

**Comment by climba03003** [comment]
> from what I can see reply, in Fastify, does actually block the code after that from running (at least in declaring a route function).

It is actually wrong, the output may not be printed immediately. But, it will be executed.

https://github.com/elverskog/attach-validation-fail-example/blob/a433034212a78d1870a57058a1cd5b9344d748d9/src/pages/form/form.schema.js#L2

You changed `fastify.get('path', schema, handler )` to `fastify.get('path', { schema }, handler )`. But the `schema` still nested with `schema`.

**Comment by elverskog** [comment]
@climba03003 Awesome. Ty. That worked.
No idea what was going on with reply. When I was testing it earlier before it was not hitting the console.log and now it is.
