### ISSUE TITLE
FastifyJWT token option types

### ISSUE THREAD

**Issue by kdurek** [fastify/help#803]
## 💬  Question here 

Hello, I am authenticating throught Auth0 OAuth2 with @fastify/jwt and get-jwks
I am doing everything like in example of @fastify/jwt and everything works
My problem is typescript on options
I tried passing everything as token type but nothing seems to work
Can you help me fix that

![image](https://user-images.githubusercontent.com/21038648/205506032-d2244b8b-cdde-4d10-8754-a99fb1cb3ada.png)
![image](https://user-images.githubusercontent.com/21038648/205506303-09f4ab1e-7038-4465-9081-9b79023e2204.png)

## Your Environment

- *node version*: 18.12.1
- *fastify version*: >=4.10.2
- *os*: Mac

**Comment by mcollina** [comment]
cc @fastify/typescript

**Comment by wilkmaia** [comment]
@kdurek can you share the specific docs you were following? Maybe they might need to be updated/fixed.

Regarding your issue:

The type `TokenOrHeader`, defined [here](https://github.com/fastify/fastify-jwt/blob/master/jwt.d.ts#L81), is a [union type](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#union-types). As such, TypeScript only lets you do things that would be valid for all members of the union.

The second object of the union indeed has a `header` property. But the first one, [JwtHeader](https://github.com/nearform/fast-jwt/blob/master/src/index.d.ts#L77), does not. So you get an error.

If you are sure what you are getting (i.e. you know **for sure** that's not a `JwtHeader` but an object with the type of the second element of the union) a simple solution is to ensure the compiler that's the case. Something like the following would do the trick:

```TypeScript
    secret: (_request: FastifyRequest, token: TokenOrHeader) => {
      if ('header' in token) {
        const {
          header: { kid, alg },
        } = token
      }

      // ...
```

The problematic piece of code will only be evaluated if there's a `header` property in `token` this way.

**Comment by wilkmaia** [comment]
@kdurek I'm guessing you followed [this example](https://github.com/nearform/get-jwks#integration-examples), right? That piece of code should work fine for JavaScript. But for TypeScript you'd need to tweak it a bit based on the info I've added above. The following should do the trick:

```TypeScript
import fp from 'fastify-plugin'
import fastifyJwt from '@fastify/jwt'
import buildGetJwks from 'get-jwks'

import type { JwtHeader, TokenOrHeader } from '@fastify/jwt'
import type { FastifyRequest, FastifyInstance, FastifyPluginAsync } from 'fastify'

const getJwks = buildGetJwks()

const jwtCheck: FastifyPluginAsync = async (fastify: FastifyInstance) => {
  fastify.register(fastifyJwt, {
    decode: { complete: true },
    secret: (_request: FastifyRequest, token: TokenOrHeader) => {
      let header: JwtHeader

      if ('header' in token) {
        header = token.header
      } else {
        header = token
      }

      const { kid, alg } = header

      return getJwks.getPublicKey({
        domain: process.env.AUTH0_DOMAIN,
        alg,
        kid,
      })
    },
  })
}

export default fp(jwtCheck)
```
