### ISSUE TITLE
Escaping/Sanitizing POST data using fastify

### ISSUE THREAD

**Issue by 4e576rt8uh9ij9okp** [fastify/help#804]
Hello,
is there a way to escape the incoming form data with fastify or does it need to be done manualy aka external package?

Cheers

**Comment by jsumners** [comment]
What do you mean "escape the incoming form data"?

**Comment by 4e576rt8uh9ij9okp** [comment]
By that I mean that they shouldn't be allowed to post things like <img onerror="alert("foo")"> and similar.

**Comment by jsumners** [comment]
I have no idea what you're talking about. Please provide a minimal reproduction.

**Comment by Asjas** [comment]
You are looking for a HTML sanitizer library, it's not something Fastify does 🙂

**Comment by Uzlopak** [comment]
Avoiding reflection attacks is not something which is done by the rest api framework, like express or fastify. So there is no flag or plugin which does this out of the box. 

The way to do it properly in fastify is by strictly validating with json schema. So e.g. you have a mongo id field in your payload, then you should validate it with a regex pattern in the json schema. And if you have a freetext field, where somebody can write anything he wants, you should validate it appropriately by deciding what you want to allow and what not.

But the topic of reflection attacks is something, which you can find enough sources on google

**Comment by Uzlopak** [comment]
Google "jsonschema v7"

**Comment by 4e576rt8uh9ij9okp** [comment]
No it's just for testing...
Is it possible that I don't respond at all?
My idea would be to do a check on the frontend and then once again on the backend and if someone tries to mess with the checking aka bots trying to login I would like to just drop the request and not reply anything.

**Comment by Uzlopak** [comment]
Then you should do rate-limitting.

**Comment by climba03003** [comment]
I believe this issue already solved. So, close.
