### ISSUE TITLE
Help - fastify-proxy behind outgoing http-proxy

### ISSUE THREAD

**Issue by jaecktec** [fastify/help#806]
## 💬  Question here 

I'd like to use [fastify-proxy](https://github.com/fastify/fastify-http-proxy) as an api-gateway. However the outgoing services are only reachable through a outgoing http-proxy. 

I'm using [global-agent](https://www.npmjs.com/package/global-agent) to configure the global http agent. 
Everything works with e.g. OIDC and Passport, however the fastify-proxy fails. 

```ts
import 'global-agent/bootstrap';
import proxy from '@fastify/http-proxy';

const server = fastify({ logger: true });
  server.register(proxy, {
    prefix: '/',
    upstream: "http://some-remote,
    rewritePrefix: '/gateway/',
  });
server.listen({ port: 8080, host: '::' }, (err, address) => {
  if (err) {
    console.error(err);
    process.exit(1);
  }
});

````

## Your Environment

- *node version*: v18.12.1
- *fastify version*: 4.10.2
- *os*: docker node:lts-alpine@node:lts-alpine@sha256:9eff44230b2fdcca57a73b8f908c8029e72d24dd05cac5339c79d3dedf6b208b

**Comment by climba03003** [comment]
`fastify-http-proxy` is using `fastify-reply-from` which use `undici` by default.
Since `undici` provide it's own `global`, you need to pass the proxy agent through the [init option](https://github.com/fastify/fastify-reply-from#undici)

You can refer to `undici` to see [how to create an proxy agent](https://github.com/nodejs/undici/blob/7102eb0b7f544cee7669aaf06eb94f38b22aba86/docs/api/ProxyAgent.md)

**Comment by jaecktec** [comment]
Is there any reason why 
```
import { setGlobalDispatcher } from 'undici'

setGlobalDispatcher(...)
```

doesn't work, or is this on me?

**Comment by climba03003** [comment]
You need to pass the proxy agent through the [init option](https://github.com/fastify/fastify-reply-from#undici)

**Comment by jaecktec** [comment]
Yeah, I noticed that - I was just hoping the global agent would work, since this would make the code cleaner.
Thanks for the help, I could get it working

**Comment by climba03003** [comment]
Follow-up issue https://github.com/fastify/fastify-reply-from/issues/284
If you are interested, feel free to open PR or join the issue discussion.
