### ISSUE TITLE
How do I use Fastify Sessions with User Logins and Data?

### ISSUE THREAD

**Issue by 4e576rt8uh9ij9okp** [fastify/help#808]
I don't really know how to use the Fastify Sessions in my project.
So I want to allow the user to edit his "profile"...

So it's little confusing for me because in the example a session key is being set to true.
`req.session.authenticated = true`
and it's confusing because it's being set in "request" not in "response".

My login looks like this here:
```js
app.post("/login", {schema: {body: { $ref: "loginSchema" }}}, async function(req, rep){
    const {email, password} = req.body
    const users = this.mongo.db.collection("users")
    const userExists = await users.findOne({email}, {projection: {email: 1, password: 1, _id: 1}})

    if(!userExists) return rep.view("views/login.eta", {msg: "Email doesn't exist."})

    const valid = await bcrypt.compare(password, userExists.password)

    if(!valid) return rep.view("views/login.eta", {msg: "Password is wrong."})

    req.session.authenticated = true
    return rep.view("views/login.eta", {msg: "Logged in."})
})
```

Can I also set the user `_id` as session_authenticated is the uid being shared inside a cookie?

**Comment by climba03003** [comment]
> Can I also set the user _id as session_authenticated is the uid being shared inside a cookie?

`@fastify/session` store the data in `cookies` with encryption, which means the data will not exposed directly by checking the `cookies`.

It may exposed when your `key` for encryption leaked to the public.

**Comment by Uzlopak** [comment]
Actually.

@fastify/session stores the data on the server side in the session store. So if a client connects to the server for the first time, the server generates a random token, the session id, and send its as a cookie, the session cookie, to the client. Following calls to the server also send the session cookie. So the server checks if a session cookie is sent with the request. If so it tries to load the session from the session store and if no or invalid session cookie is sent it creates a new empfy session with new session id.

So the cookie contains only an id, which is not related any other id. The session data is in the session store.

**Comment by 4e576rt8uh9ij9okp** [comment]
> Actually.
> 
> @fastify/session stores the data on the server side in the session store. So if a client connects to the server for the first time, the server generates a random token, the session id, and send its as a cookie, the session cookie, to the client. Following calls to the server also send the session cookie. So the server checks if a session cookie is sent with the request. If so it tries to load the session from the session store and if no or invalid session cookie is sent it creates a new empfy session with new session id.
> 
> So the cookie contains only an id, which is not related any other id. The session data is in the session store.
> 

Okay, so the session generates its own ID aka "sessionId" and this sessionId is being sent in a cookie to the visitor when logged in. But how can I "bind" the generated sessionId with a mongodb Document _id without exposing the _id?

But doing something like {sessionId: _id}
So only the server knows the doc id.

**Comment by Uzlopak** [comment]
The store should use the sessionId to retrieve the session from the database. 

That is the whole point of using a random token and why we changed it accordingly in https://github.com/fastify/session/issues/52

**Comment by 4e576rt8uh9ij9okp** [comment]
> The store should use the sessionId to retrieve the session from the database. 
> 
> That is the whole point of using a random token and why we changed it accordingly in https://github.com/fastify/session/issues/52

That would mean that i need to insert the generated sessionId into the mongodb Document or use something like Redis or LokiJS?

Because I have no idea how it works with Fastify sessions. The last time I used sessions was years ago in PHP then I used JWT for my projects and now I need to use server sided Sessions because I'm using SSR instead of a PWA.

I've seen the example on fastify but I still don't understand it really.
`req.session.authenticated = true`
doesn't tell me much as it's just a boolean and no validation is being done.
If i remember in PHP you did something like session.verify(token) or something.

**Comment by Uzlopak** [comment]
You can use connect-mongo npm package to handle the connection to mongo. I personally would not use mongo, as it is significant slower than redis.

If set up correctly req.session is then an Object, which gets automatically loaded before calling the handler and saved after calling the handler. So if you then do req.session.authenticated = true, then it will be saved in the session store, so you can check if the req.session.autenticated is set to true and handle it accordingly.

**Comment by Uzlopak** [comment]
What you want to do with it?

**Comment by 4e576rt8uh9ij9okp** [comment]
Store it as a key:value.
Like mentioned before, sessionId : _id

**Comment by Uzlopak** [comment]
So you store data for storing data, because storing data is what needs to be done and everybody should store data.

**Comment by 4e576rt8uh9ij9okp** [comment]
> So you store data for storing data, because storing data is what needs to be done and everybody should store data.

How does req.session.authenticated = true proves that the user is signed up?

To the other post, so req.session is always encoded right? So if i pass a json string or object it will be encoded? So if i do {username, uid} it will be encoded and not exposed?

But that still can be cracked

This fastify/session makes no sense and you gave me barely any info on it. I have a feeling that you only reply the barely minimum you can so I keep asking and asking.

**Comment by Uzlopak** [comment]
Tbh. I was just annoyed by the fact that i asked you why you want to store the id, and you did not answer my question but just wrote an empty sentence. Thats why i answered with the above. 

If you would have answered with a reasonable argument i could try to think of how to achieve your issue. E.g. do you want to store the _id of the user in the session, to use it for your operations? Do you store the userId and fear to expose it somewere? 

But you just wrote you want to store it as a key value, which has no deeper information. 

So lets answer your questions.

> How does req.session.authenticated = true proves that the user is signed up?

This is logic you have to implement. So you after the login you put the authenticated true or whatever into the session and then you can check in the handler if the Attribute is set or not. Or you store the userId. Whatever.


> To the other post, so req.session is always encoded right? So if i pass a json string or object it will be encoded? So if i do {username, uid} it will be encoded and not exposed?

What do you mean with encoding? Your API is a request.session. request.session is an Object. The fastify-session plugin needs a sessionStore. Serialization and deserialization happens in the sessionstore. Whatever you mean with passing a json string  makes no sense. 

If you do request.session.userId = _id than you store the _id in request.session.userId. very simple. You can then read it in consequtive handler calls with request.session.userId.

The exposed sessionId will not show the userId.


Hope this helps. If not, i am out.

**Comment by climba03003** [comment]
After read through the whole issue, you are throwing out a lot of unrelated information. For example, 
1. Can I also set the user _id as session_authenticated is the uid being shared inside a cookie?

`cookies` is unrelated to what you are trying to archive.

2. To the other post, so req.session is always encoded right? So if i pass a json string or object it will be encoded? So if i do  {username, uid} it will be encoded and not exposed?

Encode of data do nothing of what you are doing, knowing it do not make thing simpler but complicated all the existing thing in your mind.

`@fastify/session` consist of two part. An API exposed in [`request.session`](https://github.com/fastify/session#requestsession) and [`Store`](https://github.com/fastify/session#store) which helps you to store the `session` inside the storage you like (For example, `mongodb`, `redis`, memory`.)

### `request.session`

It is an API modify the actual session data. You can trust the data inside in generally since it is stored inside the `database` and retrieved by `Session Id` in `cookies` **AUTOMATICALLY**.

The data inside will be the one you set from the previous request. For example, you set `session.authenticated = true` in the last request, you will get the `session.authenticated === true` in the next request.

That means your first question already answered, you can set `session.uid = user._id` if you like it. It will persist if the incoming `Session Id` is the same.

### Store

It is tell the plugin how to store your `session`. You need to implement it or use the existing store, for example `connect-mongo`.
If you use an existing store developed by the other, you don't need to know how it store.

If you are planning to do it your self, the document already tell you to implement three methods.
1. set(sessionId, session, callback)
2. get(sessionId, callback)
3. destroy(sessionId, callback)

```js
class Store {
  // sessionId is show in here
  // session is the JavaScript object, you may need to serialize for MySQL, but not MongoDB
  set(sessionId, session, callback) {
    // operation to store inside database
  }

  // sessionId from the request
  get(sessionId, callback) {
    // operation to get the session from database
  }
  
  // sessionId from the request
  destroy(sessionId, callback) {
    // operation to delete the session
  }
}
```

**Comment by climba03003** [comment]
I am not going to guide you how to use a custom Store, but I modify you code to show how the proceed.
Please read the comment.

```js
app.post("/login", {schema: {body: { $ref: "loginSchema" }}}, async function(request, reply) {
    const users = this.mongo.db.collection("users")
    // 1. check if the user already login in previous request
    if (request.session.authenticate) {
      // when it is login
      // check if the previous user is really exist
      const previousUser = await users.findOne({ _id: new ObjectId(request.session.uid) }, {projection: {email: 1, password: 1, _id: 1}})
      if(!previousUser) return reply.view("views/login.eta", {msg: "Please login again."})

      return reply.view("views/login.eta", {msg: "Logged in."})
    } else {
      // when it is not login
      const {email, password} = request.body
      const userExists = await users.findOne({email}, {projection: {email: 1, password: 1, _id: 1}})
      // return when user not exist
      if(!userExists) return reply.view("views/login.eta", {msg: "Email doesn't exist."})
      // check password
      const valid = await bcrypt.compare(password, userExists.password)
      if(!valid) return rep.view("views/login.eta", {msg: "Password is wrong."})

      // store the state of login, it can reuse in other request
      request.session.authenticated = true
      request.session.uid = userExists._id
      return reply.view("views/login.eta", {msg: "Logged in."})
    }
})
```

**Comment by 4e576rt8uh9ij9okp** [comment]
So the request.session is being stored in the class Store and if the class Store isn't defined then it defaults to memory?
request.session = in memory store

So when doing request.session.uid the _id from the database is being stored in memory on the server and the "sessionId" is being sent inside a cookie to the user?

Now the request.session.authenticate = true, meaning I need to implement my own "checking and validation of the sessionId" aka I need to get the sessionId from the session store?

Because I prefer to store the sessions in memory instead of Redis or MongoDB.

With JWT tokens you get the token and then throw it inside a .verify() if it spits out "true" then the token is valid and the user has logged in, if "false" then then it redirects to the login page.

Now how do I verify? So a "sessionId" has been sent to the user, now I need to verify the "sessionId" that it is inside the session store?

**Comment by climba03003** [comment]
> So the request.session is being stored in the class Store and if the class Store isn't defined then it defaults to memory?

Yes, it is already mentioned in the `README.md`.

> Because I prefer to store the sessions in memory instead of Redis or MongoDB.

That is why we tell you to use a **CUSTOM Store** like `connect-mongo`.

> Now how do I verify? So a "sessionId" has been sent to the user, now I need to verify the "sessionId" that it is inside the session store?

Yes, if you don't have a record in database. Then, you won't have the session.
The cookies is actually signed and verifed if you config to use `signed cookies`.

**Comment by 4e576rt8uh9ij9okp** [comment]
So when I get the request fastify/session module automatically verifies that the sessionId exists and if it does NOT EXIST then it "i assume" changes the `request.session.authenticate = false` and if it exists then request.session.authenticate = true?
By doing `req.session.authenticate = true` i tell fastify to "check the sessionId"?

> Now how do I verify? So a "sessionId" has been sent to the user, now I need to verify the "sessionId" that it is inside the session store?
> Yes, if you don't have a record in database.

So if I don't do Custom Store the sessionId AND session data is being stored in-memory inside the default session Store?

**Comment by climba03003** [comment]
> So when I get the request fastify/session module automatically verifies that the sessionId exists and if it does NOT EXIST then it "i assume" changes the request.session.authenticate = false and if it exists then request.session.authenticate = true?

Completely wrong, when you don't have a session. There is no value inside. ```request.session.authenticate // undefined```

> By doing req.session.authenticate = true i tell fastify to "check the sessionId"?

No, when a request comes. It will find and verify the `sessionId` in `cookies`, then use the `sessionId` to find the actual `session` through the `Store`.
There are nothing related to the data inside a `session`.

> So if I don't do Custom Store the sessionId AND session data is being stored in-memory inside the default session Store?

Not a must, there are numbers of different store outside including Redis.

**Comment by climba03003** [comment]
> There is always a sessionId check?

If you believe `signed cookies` is one of the check. Then, yes.
I also believe there are nothing to do, it is how `session` should works.

> Because i would basically do something like

Yes

**Comment by 4e576rt8uh9ij9okp** [comment]
Do I need to set "signed cookie"?

**Comment by climba03003** [comment]
> Do I need to set "signed cookie"?

No, when you pass `secret` the plugin will sign by default.

**Comment by climba03003** [comment]
I believe this issue is actually solved. So, close.

**Comment by 4e576rt8uh9ij9okp** [comment]
I want to redirect if someone is logged in but it doesn't work, i spent a day and yeah idk where the issue is here (i assume it's me).

```js
app.post("/login", {schema: {body: { $ref: "loginSchema" }}}, async function(req, rep){
   // Logging stuff aka db call password check etc

    req.session.authenticated = true
    req.session.uid = user._id
    return rep.redirect(302, "/dashboard")
})

app.get("/login", async (req, rep) => {
    if(req.session.authenticated) return rep.redirect(302, "/dashboard")

    return rep.view("views/login.eta")
})
```
