### ISSUE TITLE
Client ip address

### ISSUE THREAD

**Issue by divyanagrath** [fastify/help#81]
#### You have already researched for similiar issues?
It's not uncommon that somebody already opened an issue or in best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/fastify/fastify/issues) at first before submitting a new one.

#### What are you trying to achieve or the steps to reproduce?

Describe your issue here, include as much detail as neccessary to reproduce the issue
or implement a missing functionality. If you are reporting a bug, you will get faster response
if you submit a pull request with a failing test.

```js
// Wrap code in markdown source tags
```

#### Context

* *node version*: 4,5,6,7,8,9
* *fastify version*: >=0.37.0
* *os*: Mac, Windows
* *any other relevant information*:

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by divyanagrath** [comment]
I need to log the client ip address from where the request is coming. How to access that?

**Comment by Eomm** [comment]
Hi,
when you create an issue you should edit the first message replying to the questions in the text area 😃

Anyway, [here](https://github.com/fastify/fastify/blob/master/docs/Request.md#request) is the answer to your question:

```
fastify.get('/', function (request, reply) {
  console.log(request.ip)
  console.log(request.ips)
})
```

**Comment by divyanagrath** [comment]
Hi,
Oops sorry.

I tried this, but it returns server address instead of the client hitting the API.
