### ISSUE TITLE
Help request: support form method (by using hidden field)

### ISSUE THREAD

**Issue by niradler** [fastify/help#810]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi, I'm working on abstraction for me on top of fastify, [statikly](https://github.com/niradler/statikly)
I'm trying to figure out how to support more HTTP methods in form submit (natively only get/post is sponsored)
a common pattern is to use  hidden field in the form with the desired method, for example

```
 <form method="post" action="/api/todos/id">
    <input type="hidden" value="delete" name="_method_" />
    <button type="submit">Delete</button>
  </form>
```

now on the server side how can I route this to DELETE /api/todos/id (instead of POST /api/todos/id )
any tips you can share will be appreciated🥇

**Comment by L2jLiga** [comment]
According to LifeCycle routing happens at early stage before any hooks are executed hence you can't change your request to route it to another handler, see [Lifecycle](https://github.com/fastify/fastify/blob/main/docs/Reference/Lifecycle.md#lifecycle).

I see several options to make it works:
1. Add this check in some hooks and reply with corresponding handler, see [Respond to a request from a hook](https://github.com/fastify/fastify/blob/main/docs/Reference/Hooks.md#respond-to-a-request-from-a-hook)
2. Do the same but inside handler itself
3. Use some proxies ahead your Fastify server who will handle your hidden field and change method, maybe Nginx can help
4. Handle this on FE side

**Comment by niradler** [comment]
@L2jLiga Thank you very much for the response, sharing my thoughts:

[1] not suitable for my usecase
[2] I'm going to check wild card on a route and then manually run the right method handler /or maybe just hide the route configuration so post will look like it is a delete method
[3] too complex
[4] looks like the best experience will be by providing FE solution something like Remix is doing (but im trying to avoid fe work here)
