### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by qxb3** [fastify/help#811]
## 💬  Question here 

Hello! how can i have multiple typed schema that reference another schema?

So basically i need it to be typed object or an array

Something like this:

```js
schema: {
  200: {
    type: ['object', 'array'],
    properties: { $ref: 'foo' },
    items: { $ref: 'foo' }
  }
}
```

## Your Environment

- *node version*: v18.12.1
- *fastify version*: 8.2.0
- *os*: Linux

**Comment by mcollina** [comment]
You should use `anyOf`: https://json-schema.org/understanding-json-schema/reference/combining.html

**Comment by qxb3** [comment]
Thank you!!
