### ISSUE TITLE
Help Wanted: Unable to use format or max/min length criteria when validating strings

### ISSUE THREAD

**Issue by JacobWennebro** [fastify/help#813]
No matter what I try, I can't seem to get my validation working properly. I have tried installing the `ajv-formats` plugin but no matter what I try, everything will pass as long as it is a string. It completely ignores the format as well as any max or min length that I give it. Is there something I am missing?

```js
const opts = {
  schema: {
    response: {
      200: {
        type: 'object',
        properties: {
          email: {
              type: "string",
              format: "email",
              maxLength: 30
          }
        }
      }
    },
  }
}
```

#### What was the result you received?
No matter what other criteria I give my schema, as long as type is string it accepts any type of string, no matter length or format.

#### What did you expect?
For it to respect the schema and not validate strings that are not of the email format nor longer than 30 characters.

#### Context

* *node version*: 18
* *fastify version*: 4.11.0
* *os*: Windows / Ubuntu 20.04 in WSL

**Comment by climba03003** [comment]
Response is `serialization` not `validation`.
Please check https://github.com/fastify/fast-json-stringify#specific-use-cases for more info.
