### ISSUE TITLE
process.env: "No overload matches this call"

### ISSUE THREAD

**Issue by samuelastech** [fastify/help#814]
## 💬  Can't use environment variables, always facing "No overload matches this call" error.

I'm struggling with env variables in Typescript. When listening to a port:

```js
await fastify.listen({
  port: process.env.PORT,
  host: '0.0.0.0'
})
````
I get this error:

>No overload matches this call.
>  Overload 1 of 7, '(opts?: FastifyListenOptions | undefined): Promise<string>', gave the following error.
>    Type 'string | undefined' is not assignable to type 'number | undefined'.
>      Type 'string' is not assignable to type 'number'.
>  Overload 2 of 7, '(callback: (err: Error | null, address: string) => void): void', gave the following error.
>    Argument of type '{ port: string | undefined; host: string; }' is not assignable to parameter of type '(err: Error | null, address: string) => void'.
>      Object literal may only specify known properties, and 'port' does not exist in type '(err: Error | null, address: string) => void'.
>  Overload 3 of 7, '(port: string | number, address?: string | undefined, backlog?: number | undefined): Promise<string>', gave the following error.
>    Argument of type '{ port: string | undefined; host: string; }' is not assignable to parameter of type 'string | number'.

I'm using `@fastify/env`:

```js
const envSchema = {
  type: 'object',
  required: ['PORT', 'KEY'],
  properties: {
    PORT: {
      type: 'string',
      default: 3000
    },

    KEY: {
      type: 'string'
    }
  }
}

const options = {
  schema: envSchema,
  dotenv: true,
  data: process.env
}

fastify.register(env, options)
await fastify.after()
````

## Your Environment

- *node version*: 10, 12, 13
- *fastify version*: >=4.11.0
- *fastify-env version*: >= 4.2.0
- *os*: Linux, Ubuntu 22.04.1 LTS

**Comment by climba03003** [comment]
`Number(process.env.PORT)`
