### ISSUE TITLE
How to configure Logger using create-fastify

### ISSUE THREAD

**Issue by normand1** [fastify/help#821]
## 💬  Question here 

I've created a new app using the create-fastify package. That package generates an app.js file for me that looks like this:

```
'use strict'

const path = require('path')
const AutoLoad = require('@fastify/autoload')

module.exports = async function (fastify, opts) {
  // Place here your custom code!

  // Do not touch the following lines

  // This loads all plugins defined in plugins
  // those should be support plugins that are reused
  // through your application
  fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'plugins'),
    options: Object.assign({}, opts)
  })

  // This loads all plugins defined in routes
  // define your routes in one of these
  fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'routes'),
    options: Object.assign({}, opts)
  })
}
```
However, the code for customizing the logger on fastify.io looks like this:
```
const fastify = require('fastify')({ logger: true })
```

Since the logger needs to be configured at initialization of fastify and using the create-fastify template it looks like I don't have access to fastify at initialization how can I pass configuration options to fastify for initialization like the logger?

Thanks

## Your Environment

- *node version*: v18.12.1
- *fastify version*: 4.9.2
- *os*: Mac

**Comment by Asjas** [comment]
https://github.com/fastify/help/issues/392

**Comment by normand1** [comment]
Thank you!
