### ISSUE TITLE
Projection in @fastify/mongodb doesn't work in any syntax for findOne and find

### ISSUE THREAD

**Issue by giftcift** [fastify/help#825]
Here is the snippet I am trying to get back only few fields from the DB,

`const Users = this.mongo.db.collection("Users");
const isExist = await Users.find({ "email" : request.user_id },{name:1,mobile:1,email:1}).toArray();
console.log(isExist);`

 mongodb plugin ->   "@fastify/mongodb": "^6.2.0",
 OS -> Windows
 node => 14.7.6

**Comment by climba03003** [comment]
Please check the usage properly.
See https://mongodb.github.io/node-mongodb-native/5.0/interfaces/FindOptions.html#projection

You need to specify as `{ projection: { field: number } }`
