### ISSUE TITLE
Help - Update routes schema in onRoute hook

### ISSUE THREAD

**Issue by Adibla** [fastify/help#826]
It's possible to update routes schema using onRoute hooks (it changes the original routeOptions object), is there another way or could it be fine? Are there any drawbacks in this approach?
```js
fastify.addHook('onRoute', async (routeOptions) => {
        routeOptions.schema = {
      body: {
        type: 'object',
        properties: {
          name: {type: 'string'}
        },
        required: ["name"]
      }
    }
 })
````

**Comment by mcollina** [comment]
No, doing this kind of modifications is why this hook has been added.
