### ISSUE TITLE
Help: Deliver more information about why validation failed.

### ISSUE THREAD

**Issue by Matix-Media** [fastify/help#828]
## 💬  Question here 

How do make fastify return more information on a validation failure. I would want a list with properties and an error message or something. Is there a way to archive this?
## Your Environment

- *node version*: 18
- *fastify version*: >=4.12.0
- *os*: Windows

**Comment by Asjas** [comment]
https://www.fastify.io/docs/latest/Reference/Validation-and-Serialization/#schemaerrorformatter

**Comment by Matix-Media** [comment]
Thanks!
