### ISSUE TITLE
How to reply with an 1x1 image

### ISSUE THREAD

**Issue by danlin604** [fastify/help#829]
## 💬  Question here 

I would like to serve a transparent pixel on Webiny (using fastify under the hood). It seems like the code should be simple but I am seeing `The image ... cannot be displayed because it contains errors` when navigating to the endpoint.

Example 1
Firefox shows this image to be 0x0
```JavaScript
reply
  .type('image/gif')
  .send(`data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw== `);
``` 

Example 2
Firefox shows this image to be 0x0
```JavaScript
const png = new PNG.PNG({ width: 1, height: 1 });
png.data[0] = 0;
png.data[1] = 0;
png.data[2] = 0;
png.data[3] = 0;

reply
  .type('image/png')
  .send(png.pack())
```

## Your Environment

- *node version*: 16
- *fastify version*: >=2.0.0
- *os*: Windows
- I am using fastify inside webiny (webiny integrated the package)

**Comment by Eomm** [comment]
Is it correct the extra space at the end of the base64 image?

**Comment by danlin604** [comment]
It's not. The result remains the same.

**Comment by Uzlopak** [comment]
Well. You doing it wrong. 

```js
'use strict'

const fastify = require('fastify')({ logger: { level: 'trace' } })

const blankGifContent = Buffer.from('R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==', 'base64')

fastify.get('/blank.gif', (request, reply) => {
  reply
    .type('image/gif')
    .send(blankGifContent)
})

fastify.listen({ port: 3000 }, err => {
  if (err) throw err
})

```

**Comment by danlin604** [comment]
The implementation of fastify on webiny is different which might be why the above solution did not work for me.

```JavaScript
export default createApiApp({
  elasticSearch: true,
  pulumiResourceNamePrefix: "wby-",

  pulumi: app => {
    const graphQLModule = app.getModule(ApiGraphql);

    graphQLModule.addRoute({
      // name must be in kebab-case
      name: "test",
      // path must start with /
      path: "/test",
      // all http methods allowed + ANY to catch all requests
      method: "GET"
    });
  }
});
```

```JavaScript
createApiGatewayRoute(({ onGet }) => {
    onGet("/test", async (request, reply) => {
      const blankGifContent = Buffer.from('R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==', 'base64')

      return reply // Return is necessary here
        .type('image/gif')
        .send(blankGifContent)
    });
})
```

**Comment by Uzlopak** [comment]
Is your question now solved?

**Comment by danlin604** [comment]
It's not. I haven't gotten this to work yet.

**Comment by jsumners** [comment]
> The implementation of fastify on webiny is different

We do not provide support for such variants. Please contact their support.

**Comment by Eomm** [comment]
I think the `webiny` support is the best place where to ask
