### ISSUE TITLE
Fastify-swagger API versioning

### ISSUE THREAD

**Issue by SOULPWRD** [fastify/help#831]
## 💬  Question here 

Hi,

is there some standardised way how to version api endpoints in fastify-swagger? For instance I have 2 routers - v1 and v2. What is the best practice to implement api versioning using fastify-swagger (+swagger ui)?

The ideal solution is to have 2 swagger endpoints `/v1/docs` and `/v2/docs` that would serve as api documentation for both routers separately. The problem is swagger doesn't support such option that we could tell swagger "hey here's your router, treat it as a single source of truth and generate the docs accordingly". On the contrary, the single source of truth for swagger is the server instance instead.

I've also tried to implement something like [this](https://github.com/scottie1984/swagger-ui-express#load-swagger-from-url) so we could choose between api versions by selecting a specific version from a dropdown. The problem is we need to know schema urls in advance.

Thank you for your help.

## Your Environment

- *node version*: 18.12
- *fastify version*: >=4.0.0
-  *"@fastify/swagger"*: "^8.3.0",
- *"@fastify/swagger-ui"*: "^1.3.0",
- *os*: Mac, Linux

**Comment by mcollina** [comment]
Is this a swagger-ui issue or a problem on our end?

**Comment by SOULPWRD** [comment]
To be honest, I don't know. Depends on the perspective. If the standardised way of API versioning in Swagger is defined by using different endpoints like e.g. `/v1/swagger` and `/v2/swagger` then yes, it's partially a problem of @fastify/swagger or @fastify/swagger-ui. If the standardised way is to keep versions in a single document then probably it's not a problem of @fastify/swagger(-ui) at all.

My experience with swagger is very moderate. Usually when I encountered some swagger documentation with api versioning it looked like [this](https://dzone.com/articles/versioning-rest-api-with-spring-boot-and-swagger). I could choose between versions listed in a dropdown.

Though, my question is very simple. Is there some recommended way how to ensure proper API versioning using @fastify/swagger and @fastify/swagger-ui?

Thank you!

**Comment by mcollina** [comment]
The current best practice is define v1 and v2 as separate encapsulated plugins, and then
registering multiple copies of `@fastify/swagger` and `@fastify/swagger-ui` in them.

**Comment by Uzlopak** [comment]
Actually swagger/openAPI itself has no mechanics or convention to handle versioned API. Thats why swagger ui has answer for that question.

If i had to solve thia issue,  use the tag attribute and set the version there or use the path. Register swagger as usual and register swagger-ui to a specific path, and use transformSpecification to transform the spec to my needs, e.g. filter all tags based on versions or filter all the paths based on version.

**Comment by SOULPWRD** [comment]
Thank you both for your response. At least what you've just said correlates with my assumptions. I think we can close this issue. Thank you :)
