### ISSUE TITLE
Help with @fastify/env

### ISSUE THREAD

**Issue by HellpMe** [fastify/help#837]
I am not able to set the env with fastify, this error always appears, even though the properties are set to be pulled.

a clear and concise  decription of your question
![image](https://user-images.githubusercontent.com/64676117/219982213-ba025be7-bf33-4f80-8b6e-c8c42bf7503d.png)
![image](https://user-images.githubusercontent.com/64676117/219982223-c3f1b9f8-935c-49f1-9429-52bf024e89bc.png)
![image](https://user-images.githubusercontent.com/64676117/219982225-fb769b01-6dff-4f30-8c81-6bb46db559db.png)
![image](https://user-images.githubusercontent.com/64676117/219982274-70b3b8bd-3bba-4f0a-a025-d85315bc6c8e.png)

## Your Environment

- *node version*: 18.12.1
- *fastify/env version*: >=4.2.0
- *os*:  Windows

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by HellpMe** [comment]
apparently I managed to solve it, I changed fastifyEnv.d.ts to define define strings so that it recognizes it globally and can pull the metadata

**Comment by Uzlopak** [comment]
Closing this, as it should have been a d.ts file from the beginning.
