### ISSUE TITLE
Decorating Fastify instance returns undefined

### ISSUE THREAD

**Issue by n-vh** [fastify/help#838]
## 💬  Question here 

I am trying to add a decorator plugin to my whole Fastify instance so that I can use my mailing service everywhere without having to instanciate a `new MailService` every time I need it. I followed the docs and multiple external plugins integrations like `@fastify/jwt` but when trying to access it from a route it tells me it is `undefined`. 

Thank you very much because I am scratching my head since yesterday
```ts
// server.ts
import mail from '~/plugins/mail.plugin';
import { user } from '~/router/user/user.route';

app.register(mail, {
  username: 'mail',
  key: import.meta.env.VITE_MAIL_KEY,
  url: import.meta.env.VITE_MAIL_URL,
});

app.register(user);

// ~/plugins/mail.plugin.ts

const mail = (app, opts, next) => {
  const mail = new MailService(app, opts);
  app.decorate('mail', mail);

  // logs properly on the first request
  // `app.mail` is not undefined
  console.log('mail plugin loaded', opts);

  next();
};

export default mail;

// ~/router/user/user.route.ts

export const user = (app, opts, next) => {
  app.route({
    url: '/check',
    method: 'POST',
    schema: CheckUserEmailRouteSchema,
    handler: async (req, rep) => {

      // some code

      // app.mail is undefined
      const token = await app.mail.checkEmail(req.body);
    },
  });

  next();
};

````

## Your Environment

- *node version*: 18.12.1
- *fastify version*: 4.12.0
- *os*: Windows
- Using Fastify with Vite through `vite-plugin-node`

**Comment by climba03003** [comment]
Please wrap with `fastify-plugin` if you want to escape from encapsulation.

**Comment by n-vh** [comment]
Thank you very much, it is working as expected 🙏
