### ISSUE TITLE
Client ip address

### ISSUE THREAD

**Issue by divyanagrath** [fastify/help#84]
I need to log the client ip address from where the request is coming. How to access that?

Already tried 'request.ip' and 'request.ips'. But it returns server ip.

**Comment by jsumners** [comment]
It sounds to me like you are seeing your proxy's IP address. I imagine you would see an `x-forwarded-for` header with at least one IP address in it that would correspond to the information you are looking for.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

**Comment by nwoltman** [comment]
@divyanagrath Try setting the [`trustProxy`](https://www.fastify.io/docs/latest/Server/#trustproxy) option to `true`.

**Comment by divyanagrath** [comment]
@nwoltman  @jsumners With trustProxy as true, I'm getting the same IP which I was getting with 'req.ip'. 
'x-forwarded-for' header has only one IP which is the same.

**Comment by nwoltman** [comment]
@divyanagrath In that case, there's nothing that Fastify can do. It looks like Node might only have access to that one IP address. Try the [`request-ip`](https://github.com/pbojinov/request-ip) package and see if that works. If it doesn't, you may need to change your networking architecture somehow.

**Comment by ahmethann** [comment]
> I have added console.log(request.ip) in 'prehandler' hook. In logs I get same ip for all the API hits from different clients.

same for me exactly as you described, request.ip turns server ip, not clients ip

**Comment by ahmethann** [comment]
> setting the [`trustProxy`](https://www.fastify.io/docs/latest/Server/#trustproxy) option to `true`

It worked for me! Thanks

**Comment by eru123** [comment]
this works for me 👌😁👉`request.headers['x-forwarded-for']`

**Comment by jsumners** [comment]
> This works for me without setting the [`trustProxy`](https://www.fastify.io/docs/latest/Server/#trustproxy) option to `true` 👌😁👉`request.headers['x-forwarded-for']`

The `trustProxy` option enables parsing of that header so that you do not have to do it yourself. It's not complicated, but you have to be aware that there can be multiple proxies in that header.
