### ISSUE TITLE
How to Generate JSON/YAML @fastifiy/swagger file using the cli

### ISSUE THREAD

**Issue by drilonibrahimi** [fastify/help#841]
## 💬  How to generate the yaml or json file using the cli?

I want to be able to generate the json or yaml file that gets served but I want to do that using the cli. Is that possible?

**Comment by kibertoad** [comment]
https://github.com/lokalise/node-service-template/blob/main/scripts/generateOpenApi.ts

**Comment by drilonibrahimi** [comment]
> https://github.com/lokalise/node-service-template/blob/main/scripts/generateOpenApi.ts

Thanks for sharing man! This looks exactly like what I need.
