### ISSUE TITLE
WebSocket Connection and Fastify CLI project on Same Port

### ISSUE THREAD

**Issue by raviroshanmehta** [fastify/help#842]
I have created a microservice  project using fastify cli generator it's work like a charm. 

For some microservice websocket support is needed and i found https://github.com/fastify/fastify-websocket which is again a great tool from fastify. 

But due to custom requirement i am unable to use this package so i decided to move package https://www.npmjs.com/package/ws

Here let's say if i am running any ms on port 3000 than i am unable to use same port for ws connection and i am not able to find any solution for the same. 

Hence my each ms is consuming two ports one for fastify and another for ws module. 

Is there any reference or solution to use common port by ws  and cli gererated fastify project ?  If it's not possible any other solution ?

**Comment by mcollina** [comment]
this is handled inside fastify-websocket. Use that module or look into how it's set up and copy it ;).

**Comment by raviroshanmehta** [comment]
thanks for your feedback.  This was very simple and working as expected. 

```
const  server = fastify.server;
const  wss = new WebSocketServer({ noServer: true });
```
