### ISSUE TITLE
Add lowdb to fastify

### ISSUE THREAD

**Issue by Fyzbyt** [fastify/help#843]
# Using Lowdb in fastify
I am trying to use [LowDB](https://github.com/typicode/lowdb) in fastify by writing a plugin but it never works. I am quite new in using node itself as a way to write my backend code.

I ended up asking chatgpt to come up with this ↓ which doesnt work.

```js
const fp = require('fastify-plugin');
const { join, dirname } = require('path');
const { fileURLToPath } = require('url');
const { Low } = require('lowdb');
const { JSONFile } = require('lowdb/adapters/JSONFile');

function lowdbPlugin(fastify, options, done) {
    const file = join(__dirname, options.filename || 'db.json');
    const adapter = new JSONFile(file);
    const db = new Low(adapter);

    fastify.decorate('lowdb', db);

    // Read data from JSON file, this will set db.data content
    db.read().then(() => {
        // If db.json doesn't exist, db.data will be null
        // Use the code below to set default data
        // db.data = db.data || { posts: [] } // For Node < v15.x
        db.data ||= { posts: [] }; // For Node >= 15.x
    }).catch((err) => {
        // Handle error here
        console.error(err);
    });

    // Finally write db.data content to file
    fastify.addHook('onClose', () => {
        db.write().then(() => {
            console.log('Database saved!');
        }).catch((err) => {
            // Handle error here
            console.error(err);
        });
    });

    done();
}

module.exports = fp(lowdbPlugin, { name: 'fastify-lowdb' });
```

#### What was the result you received?
I recieved failure. It just doesnt work.

#### What did you expect?
I just want to use lowdb to write, read, push in json database.

#### Context

* *node version*: 18.14.2
* *fastify version*: 5.7.1
* *os*: Mac
* *any other relevant information*:

**Comment by kibertoad** [comment]
onClose hook means that you only create file after app is stopped. is that your intention?

**Comment by Fyzbyt** [comment]
Honestly I have no idea what the snippet does. It was generated by ChatGPT. I just want a simple way to use lowDB in fastify

**Comment by Fyzbyt** [comment]
ok, I found this repo https://github.com/HerrHase/lessons-learned-fastify-riotjs-lowdb which has an implication of lowDB in fastify but I dont know how I can integrate it into my project. Can anyone help guide me?
