### ISSUE TITLE
Help fastify.io's schema example is right?

### ISSUE THREAD

**Issue by sys9kdr** [fastify/help#845]
## 💬  Question here 

fasify.io's schema example is right?
I tried fasify.io's code example below.

> Request/Response validation and hooks
> https://www.fastify.io/

```js
const fastify = require('fastify')({ logger: true })

fastify.route({
  method: 'GET',
  url: '/',
  schema: {
    // request needs to have a querystring with a `name` parameter
    querystring: {
      name: { type: 'string' }
    },
    // the response needs to be an object with an `hello` property of type 'string'
    response: {
      200: {
        type: 'object',
        properties: {
          hello: { type: 'string' }
        }
      }
    }
  },
  // this function is executed for every request before the handler is executed
  preHandler: async (request, reply) => {
    // E.g. check authentication
  },
  handler: async (request, reply) => {
    return { hello: 'world' }
  }
})

const start = async () => {
  try {
    await fastify.listen({ port: 3000 })
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()
````

and try `curl` without any querystring.

```bash
curl localhost:3000
````

It was successed. But request without name querystring should be cause errors in comments.
Why is that happen?

## Your Environment

- *node version*: 19.50
- *fastify version*: `        "fastify": "^4.14.0"`
- *os*: Linux

**Comment by mcollina** [comment]
You are missing a required property in your json schema.

**Comment by sys9kdr** [comment]
Thank you. 



> You` are missing a required property in your json schema.



In this case, a comment in a fastly.io's sample is wrong?



# Bad(current)



```
    // request needs to have a querystring with a `name` parameter
```



# Good



```
    // request needs to have a querystring with a `name` parameter if `required` option is set.
    // If `required` is not set, no warning.
```

**Comment by mcollina** [comment]
Thanks! Would you like to send a PR?

**Comment by mcollina** [comment]
Go for option 1.

**Comment by sys9kdr** [comment]
I've made it. https://github.com/fastify/website/pull/393

**Comment by Uzlopak** [comment]
Merged. Should we close this issue?

**Comment by sys9kdr** [comment]
Ok thank you.

**Comment by Uzlopak** [comment]
Thanks for your work ;)
