### ISSUE TITLE
@fastify/cookie, @fastify/session sessionId is not defined or "cookieSigner.sign is not a function

### ISSUE THREAD

**Issue by officefish** [fastify/help#852]
I am trying using @fastify/cookie, @fastify/session on localhost, so I cant use secure=true  for cookie option. When I put hook=false I got no sessionId error:

"err":{"type":"TypeError","message":"Cannot read properties of null (reading 'sessionId')","stack":"TypeError: Cannot read properties of null (reading 'sessionId')\n    at getCookieSessionId (D:\\practice\\fastify\\fastify_prizma\\node_modules\\@fastify\\session\\lib\\fastifySession.js:123:29)\n    at Object.handleSession (D:\\practice\\fastify\\fastify_prizma\\node_modules\\@fastify\\session\\lib\\fastifySession.js:139:31)\n    at hookIterator (D:\\practice\\fastify\\fastify_prizma\\node_modules\\fastify\\lib\\hooks.js:290:10)\n    at next (D:\\practice\\fastify\\fastify_prizma\\node_modules\\fastify\\lib\\hooks.js:182:16)\n    at hookRunner (D:\\practice\\fastify\\fastify_prizma\\node_modules\\fastify\\lib\\hooks.js:204:3)\n    at Object.routeHandler [as handler] (D:\\practice\\fastify\\fastify_prizma\\node_modules\\fastify\\lib\\route.js:478:7)\n    at Router.callHandler (D:\\practice\\fastify\\fastify_prizma\\node_modules\\find-my-way\\index.js:398:14)\n    at Router.lookup (D:\\practice\\fastify\\fastify_prizma\\node_modules\\find-my-way\\index.js:376:17)\n    at Server.preRouting (D:\\practice\\fastify\\fastify_prizma\\node_modules\\fastify\\fastify.js:796:14)\n    at Server.emit (node:events:513:28)"},"msg":"Cannot read properties of null (reading 'sessionId')"}

when stay hook='onRequest' got another error:

,"err":{"type":"TypeError","message":"cookieSigner.sign is not a function","stack":"TypeError: cookieSigner.sign is not a function\n    at new Session (D:\\practice\\fastify\\fastify_prizma\\node_modules\\@fastify\\session\\lib\\session.js:40:23)\n    at Object.handleSession (D:\\practice\\fastify\\fastify_prizma\\node_modules\\@fastify\\session\\lib\\fastifySession.js:141:27)\n    at hookIterator (D:\\practice\\fastify\\fastify_prizma\\node_modules\\fastify\\lib\\hooks.js:290:10)\n    at next (D:\\practice\\fastify\\fastify_prizma\\node_modules\\fastify\\lib\\hooks.js:182:16)\n    at Object.fastifyCookieHandler (D:\\practice\\fastify\\fastify_prizma\\node_modules\\@fastify\\cookie\\plugin.js:69:7)\n    at hookIterator (D:\\practice\\fastify\\fastify_prizma\\node_modules\\fastify\\lib\\hooks.js:290:10)\n    at next (D:\\practice\\fastify\\fastify_prizma\\node_modules\\fastify\\lib\\hooks.js:182:16)\n    at hookRunner (D:\\practice\\fastify\\fastify_prizma\\node_modules\\fastify\\lib\\hooks.js:204:3)\n    at Object.routeHandler [as handler] (D:\\practice\\fastify\\fastify_prizma\\node_modules\\fastify\\lib\\route.js:478:7)\n    at Router.callHandler (D:\\practice\\fastify\\fastify_prizma\\node_modules\\find-my-way\\index.js:398:14)"},"msg":"cookieSigner.sign is not a function"}

My code:
```js
import fp from 'fastify-plugin'
import { fastifyCookie } from '@fastify/cookie'
import type { FastifyCookieOptions } from '@fastify/cookie'
import { fastifySession } from '@fastify/session'

const cookiePlugin = fp(async (server) => {
    
    const cookieOptions = {
        domain: server.env.ROOT_DOMAIN,
        httpOnly: server.env.COOKIE_HTTPONLY,
        path: server.env.COOKIE_PATH,
        secure: server.env.COOKIE_SECURE 
    }
    server.decorate('cookieOptions', cookieOptions)
    server.register(fastifyCookie, {
        secret: server.env.COOKIE_SIGNATURE,
        hook: 'onRequest', 
        parseOptions: cookieOptions
    } as FastifyCookieOptions)

    const secretLength = server.env.SESSION_TOKEN_LENGTH
    const secret = server.bcrypt.genSalt(secretLength)

    server.register(fastifySession, {
        secret,
        cookieName: 'sessionId', 
        cookie: { secure: false }, })
})

export { plugin as SessionPlugin }
   
```

#### Context

* *node version*: v18.14.1
* *fastify version*: >=^2.4.3
* *os*: Windows

**Comment by metcoder95** [comment]
Hey!
Can you take a look at the value you passing to `secret`?
While registering the plugin, `@fastify/cookie` is expecting an object that contains `sign` and `unsign` methods to execute such operations over a cookie, it is also important if wants to be used in combination with `@fastify/session`. See: https://github.com/fastify/fastify-cookie#custom-cookie-signer

**Comment by officefish** [comment]
You right. The problem was with secret length in session config, The cookie plugin explicitly reports the use a secret of insufficient length, while the session simply stops working correctly.
