### ISSUE TITLE
Is it possible to specify that a request body should be `text/plain`, and have it reflected in OpenAPI? 

### ISSUE THREAD

**Issue by ymeine** [fastify/help#854]
Hi folks,

I have a project where I wanted to add OpenAPI support, and for that I used [@fastify/swagger](https://github.com/fastify/fastify-swagger) and [@fastify/swagger-ui](https://github.com/fastify/fastify-swagger-ui).

So far everything was fine, but then I needed one thing: to specify for some routes that the input should be `text/plain`.

I can see both in the generated JSON spec and in the UI that it's either no input at all, or only the `application/json` one.

Take the following example: 

```javascript
const fastify = require('fastify');
const swagger = require('@fastify/swagger');
const swaggerUi = require('@fastify/swagger-ui');

async function main() {
    const app = fastify({logger: true});
    await app.register(swagger, {openapi: {}});
    await app.register(swaggerUi, {routePrefix: '/api'});

    app.post('/echo1', function(request) { return request.body; });
    app.post('/echo2', {
        schema: {body: {type: 'string'}},
    }, function(request) { return request.body; });
    
    await app.ready();
    app.swagger();
    await app.listen({port: 8080});
}
main();
```

![swagger-ui](https://user-images.githubusercontent.com/2077669/227660254-c94ad509-13d2-416f-826a-8ca8315a0483.png)

As expected, `/echo1` doesn't know what kind of input to accept, and `/echo2` expects JSON (specifically a string formatted as JSON here). I am seeing this as normal, not a bug, but I didn't find how to explicitly tell that the body should be `text/plain`. It seems to me that it is not such a rare use case.

Here's how it is defined in the generated spec (again, consistent): 

```json
{
    "openapi": "3.0.3",
    "info": {
        "version": "8.3.1",
        "title": "@fastify/swagger"
    },
    "components": {
        "schemas": {}
    },
    "paths": {
        "/echo1": {
            "post": {
                "responses": {
                    "200": {
                        "description": "Default Response"
                    }
                }
            }
        },
        "/echo2": {
            "post": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "string"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Default Response"
                    }
                }
            }
        }
    }
}
```

I am using the following versions: 

```json
{
  "@fastify/swagger": "8.3.1",
  "@fastify/swagger-ui": "1.5.0",
  "fastify": "4.15.0"
}
```

How do I add another content type in `requestBody`, from within the route definition?

**Comment by metcoder95** [comment]
Hey! Yeah, is possible 🙂 
For that, you need to indicate the `consumes` directive within your schema definition while creating a route.

Reusing your example, this is how it should look like:
```js
const fastify = require('fastify')
const swagger = require('@fastify/swagger')
const swaggerUi = require('@fastify/swagger-ui')

async function main () {
  const app = fastify({ logger: true, ajv: {
    'customOptions': {
      strict: false,
    }
  } })
  await app.register(swagger, { openapi: {} })
  await app.register(swaggerUi, { routePrefix: '/api' })

  app.post('/echo1', function (request) {
    return request.body
  })
  app.post(
    '/echo2',
    {
      schema: {
        body: {
          type: 'string',
        },
        consumes: ['text/plain']
      }
    },
    function (request) {
      return request.body
    }
  )

  await app.ready()
  app.swagger()
  await app.listen({ port: 8080 })
}

main()
```

Having the following result:
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/10200776/228696980-c64808a9-e825-4402-849f-cda15082b10a.png">

**Comment by ymeine** [comment]
Hi!

Thanks for the answer, indeed it works. But that brings to me a couple of questions: 

- where is this documented at all? I can only see the TypeScript interfaces that are augmented when importing the swagger package, but that's not proper documentation
- what is the purpose of the schema in case of plain text? It will always be a string, unless we can have a custom content type handler that would use the schema?
- how would I specify a different schema ***per*** content type?

Those are theoretical questions since right now I haven't faced myself any issue related to them.

**Comment by metcoder95** [comment]
>where is this documented at all? I can only see the TypeScript interfaces that are augmented when importing the swagger package, but that's not proper documentation

Technically, `@fastify/swagger` does support the OpenAPI sec per-se, meaning that the same capabilities can be reflected in the plugin, though is possible that some of them are missed.

>what is the purpose of the schema in case of plain text? It will always be a string, unless we can have a custom content type handler that would use the schema?

Have into account that, unless changed, Fastify uses AJV with JSON schema spec for validating the incoming request. Under the hood, fastify creates a whole object constructed from the parts of an HTTP request and uses the schema definition to validate such schema against the constructed object. In that realm, it is possible to support all the capabilities of JSON and AJV while validating an incoming payload in a form of a plain `string` (not to mention that this also helps Fastify decide how to parse the incoming HTTP request's payload).

>how would I specify a different schema per content type?

Sadly, I think we faced one of the missing parts of the plugin, as I tried several combinations without success. You can provide your own Swagger schema and use a combination of the `oneOf` Ajv capabilities to validate if the payload is either a string or a JSON serializable object.
But currently, the plugin doesn't supports that 🙁

**Comment by ymeine** [comment]
> Technically, @fastify/swagger does support the OpenAPI sec per-se, meaning that the same capabilities can be reflected in the plugin, though is possible that some of them are missed

Thanks for the clarification.

> Have into account that, unless changed, Fastify uses AJV with JSON schema spec for validating the incoming request. Under the hood, fastify creates a whole object constructed from the parts of an HTTP request and uses the schema definition to validate such schema against the constructed object. In that realm, it is possible to support all the capabilities of JSON and AJV while validating an incoming payload in a form of a plain string (not to mention that this also helps Fastify decide how to parse the incoming HTTP request's payload).

I can see the consistency in there, and I think it doesn't hurt to have a schema even for plain text.

> Sadly, I think we faced one of the missing parts of the plugin, as I tried several combinations without success. You can provide your own Swagger schema and use a combination of the oneOf Ajv capabilities to validate if the payload is either a string or a JSON serializable object.
> But currently, the plugin doesn't supports that 🙁

That's ok I guess, it's hard to provide support to all use cases. It's already great to have a plugin which does most of the job. For now I haven't faced this use case so I just cross fingers to keep it that way.

Thanks for all your answers, I can consider this issue fully resolved!
