### ISSUE TITLE
reverse session

### ISSUE THREAD

**Issue by Z3NTL3** [fastify/help#858]
Hello,

I have a question. I have pre handlers and these pre handlers do some lil heavy tasks. They update the user's cookie if it doesnt match with the cookie id in the db with the old session data. So re-populating things and updating things in DB afterwards.

My question is, can I make this approach stay rapid if I use event emitters? And my other question is what if i didnt make a event emitter functionality and just added done and then the functionality below, isnt that the same? I force fastify to continue and while the function is not returned it does the job and then it returns at the same time while the lifecycle goes forward at the same time

For example look below:
```ts
   app.addHook("onRequest", (req,res, done) => {
        api.emit(eventAPI.reverse, req)
        done()
    })
```

```ts
api.on(eventAPI.reverse, async (req: FastifyRequest) => {
    let ip = req.headers[HeaderCF['cf-connecting-ip']] ?? "null"
    let SID = req.session.sessionId

    let client = await Users.findOne({ip: ip})
    if(client !== null && client.sessionId !== SID){
        let oldSid = client.sessionId
        req.sessionStore.get(oldSid, async (err,result) => {
            if(err || result === null || typeof result === "undefined") {
                await Users.findOneAndUpdate({ip: ip}, {
                    $set: {sessionId: SID}
                })
                return
            }
            req.sessionStore.set(SID, result,async(err) => {
                if(err) {
                    console.error(err)
                    return
                }
                console.log(result)
                await Users.findOneAndUpdate({sessionId: oldSid}, {
                    $set: {sessionId: SID}
                })
                await Sessions.deleteOne({sessionId: oldSid})
                await req.session.reload()
                return
            })
        })
    } else {
        await Users.findOneAndUpdate({sessionId: SID}, {
            $set: {ip: ip}
        })
    }
})
```

**Comment by Z3NTL3** [comment]
> I would recommend against it.

So basically:
done()
... some code

Is the same as the approach with the event emitter one?

**Comment by mcollina** [comment]
Yes. If you need code to be done in the background, you should use a processing queue.

Try https://www.npmjs.com/package/fastq as an in-process one, but you should think of some persistence system.
