### ISSUE TITLE
FastifyPassport

### ISSUE THREAD

**Issue by parmeet10** [fastify/help#859]
I am using FastifyPassport, I want to send a state variable which will be in my incoming request.

```
fastify.get('/auth/google/callback', {
  preValidation: (req, res) => {
    FastifyPassport.authenticate('google'
      , {
        scope: ['profile', 'email'],
        state: req.query.state,
      })
  }
}, async (req, res) => {
  console.log(req.query.state)  // it should print "something"
  console.log('successful login')
});

```
HTTP_REQUEST: http://mydomain/auth/google/callback?state="something".

Is there any way to send in a variable which is coming in request I also tried with done() which continues the lifecycle but doesn't help.

**Comment by mcollina** [comment]
I think the following should solve your problems:

```
fastify.get('/auth/google/callback', {
  preValidation: FastifyPassport.authenticate('google'
      , {
        scope: ['profile', 'email'],
        state: req.query.state,
      })
}, async (req, res) => {
  console.log(req.query.state)  // it should print "something"
  console.log('successful login')
});

```

(Note that it's hard to help without a full repro)

**Comment by parmeet10** [comment]
In the above snippet, it is not able to access req object

**Comment by climba03003** [comment]
```js
fastify.get('/auth/google/callback', {
  preValidation: (req, res) => FastifyPassport.authenticate('google', {  scope: ['profile', 'email'],  state: req.query.state,  })(req, res)
}, async (req, res) => {
  console.log(req.query.state)  // it should print "something"
  console.log('successful login')
});
```

**Comment by parmeet10** [comment]
I am able to solve this in javascript, but when trying in typescript I am getting :

The 'this' context of type 'void' is not assignable to method's 'this' of type 'FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>'.ts(2684)
