### ISSUE TITLE
Reg. customization of logging feature(serializer)

### ISSUE THREAD

**Issue by lokeshrg** [fastify/help#86]
Currently in our app, while looking at the logs, we see the response status code and the response time along with some misc response info. But wanted to check if it would be possible to have request info(eg. URL, http method etc) in the same log so that, it could be more readable.

I did read this piece of info about logging and options of using custom serializers, but couldnt figure out a way to add request info along with response info into one.
https://github.com/fastify/fastify/blob/master/docs/Logging.md

I tried to make some changes around these lines of code : https://github.com/fastify/fastify/blob/master/lib/logger.js#L53-L70

Imaginary example of how it might work: 
a variation on https://github.com/fastify/fastify/blob/master/lib/logger.js#L65-L69
```javascript
res: function asResValue (res, req) {
    return {
      statusCode: res.statusCode,
      reqUrl: req.url,
      reqMethod: req.method
    }
  }
```

But i am not well aware of how the serializers are working here. So wanted to check here to see if that it is feasible or if should even be allowed to be done that way.

Any input/feedback is appreciated.

Thank you.

**Comment by Eomm** [comment]
> But wanted to check if it would be possible to have request info(eg. URL, http method etc) in the same log so that, it could be more readable.

No, by default you can't do it using our setup properties.

If you want to do it, you need to add a hook:

```
'use strict'

const fastify = require('./fastify')({
  disableRequestLogging: true,
  logger: {
    serializers: {
      req: function (req) {
        return {
          myUrl: req.url,
          myMethod: req.method
        }
      },
      res (res) {
        return { statusCode: res.statusCode }
      }
    }
  }
})

fastify.get('/', async () => { return 'hello' })
fastify.addHook('onResponse', (req, res, next) => {
  fastify.log.info({ req: req.raw, res: res.res })
  next()
})

fastify.listen(3000)

// will print:
// {"level":30,"time":1559981029431,"pid":2384,"hostname":"EOMM-XPS","req":{"myUrl":"/","myMethod":"GET"},"res":{"statusCode":200},"v":1}

```

For more info about serializer checkout the pino docs:
https://github.com/pinojs/pino/blob/master/docs/api.md#opt-serializers

**Comment by SaugataDutta** [comment]
@Eomm But that won't print the `responseTime` in that log statement. 

> // will print:
// {"level":30,"time":1559981029431,"pid":2384,"hostname":"EOMM-XPS","req":{"myUrl":"/","myMethod":"GET"},"res":{"statusCode":200},"v":1}


What we are trying to achieve is a single log statement that gives the req.url, req.method, res.statusCode and responseTime.

**Comment by lokeshrg** [comment]
Closing this issue as new PR is created for this feature:
https://github.com/fastify/fastify/pull/1697

**Comment by lokeshrg** [comment]
Thanks @Eomm @SaugataDutta
