### ISSUE TITLE
Remove a previously registered route

### ISSUE THREAD

**Issue by rslucena** [fastify/help#863]
My situation involves fastify/swagger and fastify, but the doubt can involve any route that does not have access to the plugin.

Previously, fastify/swagger had in its parameters a way of not displaying its created documentation route (for example /documentation), but this parameter was removed in the latest versions of the plugin.

Thinking about it, a doubt arose. Given this scenario, it is not possible for me to edit the plugin code and modify it to add the parameter again, since the maintenance team itself removed it.

How is the removal of a route done in a scenario of this type?

Assuming a third party creates a route, is there a possibility to remove that record before initializing the listener?

**Comment by Eomm** [comment]
> Assuming a third party creates a route, is there a possibility to remove that record before initializing the listener?

Yes, it is possible by adding a `onRoute` hook before registering the plugin. At that stage you should be able to inject the `hide: true` config in the route itself
