### ISSUE TITLE
How to access a transformed but non-parsed request stream in a route handler?

### ISSUE THREAD

**Issue by schantaraud** [fastify/help#864]
## 💬  Question here 

Hi - please consider the following simplified example of a file upload route:

```js
fastify.register((scope, opts, next) => {

  scope.removeAllContentTypeParsers();
  scope.addContentTypeParser('*', (request, payload, done) => {
    done();
    // done(null, payload); // Same result
  });

  scope.route({
    method: 'POST',
    path: '/upload',

    // Similar to what @fastify/compress would do with content-encoding: gzip
    preParsing: (request, reply, payload, next) => {
      return next(null, pipeline(payload, createGunzip(), err => {
        if (err) {
          console.error(`Error decompressing request: ${err.message}`);
        }
      }));
    },

    handler: async request => {
      // Doesn't work as `request.raw` is the raw request, not the "pre-parsed" payload
      await pipeline(request.raw, createWriteStream('/tmp/new-file));
    }
  });

  next();
});
```

As documented, `request.raw` is the compressed raw request. The gunzipped stream seems to be attached to the request object under a private symbol: `fastify.RequestPayloadStream`. Is there a way to access it from the handler?

Or maybe, is there a more proper way to achieve the same goal?

Thank you!

## Your Environment

- *node version*: 18.15.0
- *fastify version*: v4.15.0
- *os*: Mac, Linux

**Comment by metcoder95** [comment]
Hi!

The `request.raw` is the native `request` object from Node core.
The `preParsing` hook will always expect a stream being returned to properly parse the HTTP payload from the returned stream.
If your intention is to write the content of the request directly into the disk you can use any of the already published ecosystem plugins, or handle the request all by yourself.

This is by calling [`reply.hijack`](https://www.fastify.io/docs/latest/Reference/Reply/#hijack) at the `preParsing` hook, and intercepting the payload, so you can write it into the disk. But you should keep in mind that the rest of the hooks will be halted of execution, and the response should be done directly with `reply.raw`, which contains the `response` HTTP object from Node core.

**Comment by schantaraud** [comment]
Looks like this also works, not sure how I missed it in the first place:

```js
handler: async request => {
  await pipeline(request.body, createWriteStream('/tmp/new-file));
}
```

Thanks!
