### ISSUE TITLE
'onRequestAbort' and 'request.raw.on("close")' not firing reliably

### ISSUE THREAD

**Issue by TimShilov** [fastify/help#866]
## Summary
Hello,
I'm trying to handle cases where the user aborts the request to cancel database queries.
I've looked at:
1. https://www.fastify.io/docs/latest/Guides/Detecting-When-Clients-Abort/
2. https://www.fastify.io/docs/latest/Reference/Hooks/#onrequestabort

Both seem to not work reliably (and in my cases, they don't work at all). It seems to have something to do with `Content-Type` header.

## Reproduction code (mostly the copy-paste from documentation).

```js
const fastify = require("fastify");

const sleep = async (time) => {
    return new Promise((resolve) => setTimeout(resolve, time || 1000));
};

const app = fastify({
    logger: {
        transport: {
            target: "pino-pretty",
            options: { translateTime: "HH:MM:ss Z", ignore: "pid,hostname" },
        },
    },
});

app.addHook("onRequestAbort", async (request) => {
    console.log("Aborted!", request.raw.aborted);
});

app.post("/", async (request, reply) => {
    console.log("in handler");
    request.raw.on("close", () => {
        console.log("close");
        if (request.raw.aborted) {
            console.log("request aborted!");
        }
    });
    await sleep(3000);
    reply.code(200).send({ ok: true });
});

const start = async () => {
    try {
        await app.listen({ port: 3000 });
    } catch (error) {
        app.log.error(error);
        process.exit(1);
    }
};

start();
```

## Expected Behavior
When sending any request and aborting it I should see this output:
```
in handler
close
request aborted!
Aborted! true
```

## Actual Behavior

For this request, all works fine:
```sh
curl --request POST --url 'http://localhost:3000/'
```
When I abort the request I see the expected output.

However, for this request (same thing but with JSON content type and a body) the abort is not caught:
```sh
curl --request POST  --url 'http://localhost:3000/' --header 'Content-Type: application/json' --data '{}'
```
And the output is:
```
in handler
close
```
Also, it looks like `close` is fired right away (before 3-second delay and before me actually canceling the request).

## Question

Any idea what could cause that and how can I make it work reliably?

## Your Environment

- *node version*: v18.15.0
- *fastify version*: 4.15.0
- *os*: MacOS 13.3.1 (22E261)

**Comment by climba03003** [comment]
I think we have emphasize inside both place.
The method to detect request abort is expected to be unreliable and we have no way to detect it in a reliable way.

**Comment by TimShilov** [comment]
Thanks for the response! :-) 

> The cause is that request already consumed.

What do you mean by "request already consumed"? It is consumed when the body is parsed?

> The method to detect request abort is expected to be unreliable
Yea, I've seen that in the docs but I thought it means that it may sometimes not work or something. The hook that does not work when there's a body in request (which I assume is true for a huge portion of API endpoints) seems kinda pointless. 🤔

**Comment by climba03003** [comment]
> It is consumed when the body is parsed?

Yes.

> The hook that does not work when there's a body in request (which I assume is true for a huge portion of API endpoints) seems kinda pointless. 🤔

Yes, it is the limitation for now. Only abort in middle of stream processing would throw and can be detected.
If no more action can be done on readable side, you will never know when it aborted.

**Comment by TimShilov** [comment]
Got it.
Thank you for the explanation @climba03003!
