### ISSUE TITLE
Unit Test: Is there a way to send form-data attachments through fastify.inject?

### ISSUE THREAD

**Issue by Khanon** [fastify/help#867]
Hello,

## Summary
I trying to create an unit test to test **multipart/form-data** request using `fastify.inject`.
I don't find the way to send a FormData object with some file attached to it through `inject` method.

This is how I build the request in the `spec` file:
```ts
private injectRequest(url: string, options?: RequestOptions) {
    let formData
    if (options?.formData || options?.attachments) {
      formData = new FormData()
      if (options?.formData) {
        Object.entries(options.formData).forEach(([key, value]) => {
          formData.append(key, value)
        })
      }
      if (options?.attachments) {
        options.attachments.forEach((attachment) => {
          try {
            formData.append(attachment.key, attachment.value)
          } catch (error) {
            throw new Error('Fake Endpoint - formData append error.', error)
          }
        })
      }
    }

    this.fastify.inject({
      'POST',
      url,
      headers: { 'Content-Type': formData ? 'multipart/form-data; boundary=any' : 'application/json' },
      payload: formData ?? options?.body,
    })
      .then(response => console.log('THEN', response.body))
      .catch(error=> console.log('CATCH', error))
  }
}
```

I'm using **@fastify/multipart** to read the data, it works fine doing the request from the frontEnd app.
This is how I read the data from the server:

```ts
 protected async parseFormData(request: FastifyRequest): Promise<ParseFormDataResponse> {
    const parts = request.parts()
    const fields = {}
    const attachments = {}
    for await (const multipart of parts) {
      if (this.isMultipartFile(multipart)) {
        const multipartFile = multipart as MultipartFile
        const fileStr = await this.readFileStream(multipartFile.file)
        Object.defineProperty(attachments, multipartFile.fieldname, { enumerable: true, value: fileStr, writable: true, configurable: true })
      } else {
        Object.defineProperty(fields, multipart.fieldname, { enumerable: true, value: multipart.value, writable: true, configurable: true })
      }
    }
    return {
      fields,
      attachments
    }
  }
```

## Result
`request.parts` seem to be empty, so I receive empty data from `parseFormData`.

## Question
Is `InjectOptions.payload` the correct place to send the FormData object?
Is there a way to do this?

## Environment
My app is working on Node.js v16.20.0
Fastify version 4.6.0

Thanks in advance.

**Comment by Eomm** [comment]
Checkout the code here: https://github.com/fastify/light-my-request#example
Using https://github.com/Eomm/form-auto-content it will work 👍🏼

**Comment by Khanon** [comment]
Hi @Eomm , is there a way to use `light-my-request` with the **fastify instance and endpoints I create in my project**?

I don't find in the `README` doc of `light-my-request` how to use it with an existing fastify instance and its routes.

### Example
```ts
import Fastify, {
  FastifyInstance,
  FastifyPluginAsync,
  FastifyRequest,
  FastifyReply
} from 'fastify'
import cors from '@fastify/cors'
import multipart from '@fastify/multipart'

this.fastify = Fastify()
this.fastify.register(multipart)
this.fastify.register(cors, {
  origin: true
}).then(() => {
  // Create endpoint
  this.fastify.post('/someRoute', {
    handler: (request: FastifyRequest, reply: FastifyReply) => {
      reply.status(200)
      reply.header('Content-Type', 'application/json')
      reply.send(JSON.stringify({
        message: 'Some endpoint response'
      }))
    }
  })

  this.fastify.ready(() => {
    // How to test a `light-my-request` `inject` agains `/someRoute` POST endpoint?
    // Is there another way to test that route sending a FormData object?
  })
})
```

### Questions
How to test a `light-my-request` `inject` agains `/someRoute` POST endpoint?
Is there another way to test that route sending a FormData object?

**Comment by Eomm** [comment]
`fastify.inject` is the light-my-request interface: https://www.fastify.io/docs/latest/Guides/Testing/#benefits-of-using-fastifyinject

To write some pseudo code:

```
const formAutoContent = require('form-auto-content')
const fs = require('fs')

  const form = formAutoContent({
    myField: 'hello',
    myFile: fs.createReadStream(`./path/to/file`)
  })

 this.fastify.inject({
      'POST',
      url,
      ...form
    })
```

**Comment by Khanon** [comment]
@Eomm sorry, that's not working.

This is my code:
```ts
const myForm = formAutoContent({
  notificationData: 'value1',
  field2: ['value2', 'value2.2'] // array are supported too!!
})
myForm.headers = { 'Content-Type': 'multipart/form-data; boundary=any'}

this.fastify.inject({
  method,
  url,
  ...myForm,
  // headers: { 'Content-Type': formData ? 'multipart/form-data; boundary=any' : 'application/json' },
  // payload: formData ?? options?.body,
})
  .then(data => console.log('Then:', data.body))
  .catch(data => console.log('Catch:', data))
```

In the server I'm using @fastify/multipart to parse the *FormData* and there is not `notificationData` nor `field2` anywhere calling `request.parts()` method (check `parseFormData` above).

**Comment by Khanon** [comment]
I've seen the *FormData* fields are coming in a `Buffer` located on `_lightMyRequest.payload`.
**@fastify/multipart** package doesn't seem to be compatible with `form-auto-content`.

Some idea?

**Comment by Khanon** [comment]
Hi again @Eomm . 

I've been investigating and `@fastify/multipart` doesn't have support for `light-my-request`.
I've been reviewing the code and I think it is possible and not difficult to add compability between **@fastify/multipart** and `inject` method from **light-my-request**.
I'd be happy to contribute this implementation if you think it is okay.

**Comment by mcollina** [comment]
That would be awesome!

**Comment by Eomm** [comment]
I think the issue @Khanon is having could be around a precise use case

Here is a working example: https://github.com/fastify/light-my-request/pull/244
So, please add a failing test before editing the code

**Comment by Khanon** [comment]
Okay, thanks to @Eomm 's branch I found out what was the problem.
I wasn't attaching files, so by default `form-auto-content` was sending the request as `'application/x-www-form-urlencoded'`.
Since that wasn't compatible with **@fastify/multipart**, I was setting the `Content-type` myself as `multipart/form-data; boundary=any`.
That's wrong, `boundary` must be set as the `FormData` object defines.

### Solutions
Using `FormData` object:
```ts
const formData = new FormData()
formData.append(...)

this.fastify.inject({
  'POST',
  url,
  headers: { 'Content-Type': `multipart/form-data; boundary=${formData['_boundary']}` },
  payload: formData,
})
```

Using `form-auto-content` force **multipart/form-data** Content Type:
```ts
const myForm = formAutoContent({
  field1: 'value1',
  field2: ['value2', 'value2.2'] // array are supported too!!
}, { forceMultiPart: true })

this.fastify.inject({
  'POST',
  url,
  ...myForm,
})
```

Thanks for the help!
