### ISSUE TITLE
What is the correct way to register multiple middleware

### ISSUE THREAD

**Issue by hn4a0d** [fastify/help#87]
After reading the documentation and started a new boilerplate project to test fastify **with the structure design provided by fastify-cli generate**, I confess that it was not clear if I should treat the middleware registry.

Taking as an example the fastify-cors and fastify-compress docs, both suggest the following:
```js
fastify.register(require('fastify-cors'), { 
  // put your options here
})
fastify.register(require('fastify-compress'))
```
While the Fastify documentation suggests a different way, which caught my attention to the similarity with express when using middlewares:
```js
fastify.use(require('cors')())
fastify.use(require('dns-prefetch-control')())
fastify.use(require('frameguard')())
[...]
```
- What is the difference between using fastify.register () and fastify.use ()? Forgive me, but I could not figure it out in the documentation.
- Should middlewares be treated as plugins? If so, should they be registered using fastify-plugin? Inside de plugins folder?
- If not, would it be correct to register them in the entry file (app.js) or inside the services?
- Would it be correct to create a 'middleware.js' file responsible for the registration of each of them? Something like:

```js
'use strict'

module.exports = function (fastify, opts, next) {
  fastify.register(require('fastify-helmet'))
  fastify.register(require('fastify-cors'))
  fastify.register(require('fastify-compress'))

  next()
}
```
As you can see, many questions on this first day trying to adapt me with Fastify.

**Comment by darkgl0w** [comment]
Hello @hn4a0d 

- the `fastify.use()` method should be used when you want to use a package that's been made for Express or Restify (NB: for more information on what's compatible or not take a look [here](https://github.com/fastify/fastify/blob/master/docs/Middlewares.md#express-middleware-compatibility)) while `fastify.register()` allow you to use **encapsulated** plugins made specifically for Fastify (usually built around `fastify-plugin`).

You will certainly find an answer to your questions [here](https://github.com/fastify/fastify/blob/master/docs/Plugins-Guide.md) but in the end it will be highly dependent of the architecture of your application, as a good starting point you can experiment with a project generated with [`fastify-cli`](https://github.com/fastify/fastify-cli) which provide a clean boilerplate for your Fastify application and you can look at [`fastify-example-twitter`](https://github.com/fastify/fastify-example-twitter) repo that provide a different approach.
If you are interested in a typescript approach you can look at @Ethan-Arrowood [`Matterhorn`](https://github.com/MatterhornDev/matterhorn) boilerplate.

And last but not least you can find @delvedor [Monoliths always pay their debts](http://delved.org/monoliths-always-pay-their-debts) presentation interesting. ^^

I hope this will help you in your Fastify discovering journey :P

**Comment by Eomm** [comment]
Attention, with use the encapsulation is granted in any case.

Use have a total different signature api and doesn't have the fastify request and replay.

Spoiler: use will be deprecated from v3 (there is an issue in fastify repo for this purpose)
