### ISSUE TITLE
Typescript error with Type Provider and Date response

### ISSUE THREAD

**Issue by SeanReece** [fastify/help#871]
## 💬  Question here 

I'm using `@fastify/type-provider-typebox` to infer types from my schemas and I'm running into a type mismatch issue when trying to return a `Date` object in a response, and using `Type.String({ format: 'date-time' })` in the schema (as recommended by `fast-json-schema`). 

This results in a TS error `'Date' is not assignable to type 'string'.`

The implementation works fine since `fast-json-stringify` will call `.toISOString()` on the date object. I would prefer to let `fast-json-stringify` handle the serialization here and not have to convert it myself.

Anyone have any ideas? I know from the typescript perspective I'm returning the "wrong" type, but `@fastify/type-provider-typebox` should be aware that a schema with `format === 'date-time'` expects a Date object or a string. 🤔 

### Example code

```ts
import fastify from 'fastify'
import { Type, TypeBoxTypeProvider } from '@fastify/type-provider-typebox'

const schema = {
  response: {
    200: Type.Object({
      name: Type.String(),
      createdAt: Type.String({ format: 'date-time' }),
    }),
  },
}

const server = fastify().withTypeProvider<TypeBoxTypeProvider>()

server.get('/user', { schema }, () => { // TS ERROR Type 'Date' is not assignable to type 'string'.
  // Get user from database. Response includes a Date object
  const dbUser = {
    name: 'test',
    createdAt: new Date(),
  }
  return dbUser
})
````

### Example Response

*GET /user*
```json
{
	"name": "test",
	"createdAt": "2023-04-21T15:27:16.483Z"
}
```

### Obvious solutions (that I'd like to avoid or don't work)

- Obviously calling `new Date().toISOString()` will "fix" the error. But this isn't great since I'd much rather `fast-json-stringify` handle this. Plus, we will have much more complex responses than this contrived example.

- Change the schema to `Type.Date()`
Results in an incorrect response
```json
{
	"name": "test",
	"createdAt": {}
}
```

## Your Environment

- *node version*: 18
- *fastify version*: 4.15.0
- *os*: Mac
- *any other relevant information*

**Comment by mcollina** [comment]
cc @sinclairzx81 @fastify/typescript

**Comment by sinclairzx81** [comment]
@SeanReece Hi. 

For Dates you should use `Type.String({ format: 'date-time' })`.  The `Type.Date` type is an extended type used to represent instances of `Date` only. As Date object's have a variety of ways they can be encoded to JSON (timestamps, iso-8601), and because no formal specification exists for `JSON.stringify(new Date())`, being specific about the encoded type is currently the only reasonable option (afaik)

### Auto Encode Dates

On the topic of automatic Date encoding in `fast-json-stringify`, this is probably possible, but likely at a performance and maintainability cost (requiring checks for Date objects during the encoding of strings). Mostly for performance tho, the json  encoder should really be passed inputs immediately ready for encode (and should never non-encodable data like Date objects).

As a possible suggestion, perhaps a opt-in `pre-encode` pass could be introduced. This would allow complex data (such as dates and buffers) to be encoded as strings prior to serialization. It might also prove a fast path for applications that need to transmit a lot of complex / specific data structures without requiring fast-json-stringify to encode for such structures.
```
res.send(new Date()) -> [pre-encode] -> [fast-json-stringify] -> http ...
                              |
                        [Programmable]
                              |
           (Date to IsoString | Uint8Array to Base64)                  
``` 
But for now, I think `Type.String({ format: 'date-time' })` + `res.send(new Date().toIsoString())` is probably the most reasonable option.

Hope this helps!
S

**Comment by sinclairzx81** [comment]
@SeanReece Ah, you're right! I wasn't aware `fast-json-stringify` automatically encoded for dates (I remember looking at this a mid last year and remember there being some challenges with Date encode/decode) I may have been looking at the request parsing. My mistake :)

> My code example in the original question works as expected until .withTypeProvider<AnyTypeProvider>() is added, then we get a type error. I have also tested with JsonSchemaToTsProvider with the same result. I believe this should be supported in order to be compatible with the expected inputs of fast-json-stringify. Should we consider this a bug with the Type Provider system?

I'm not sure if this is specifically a type system issue as much as it's a type mismatch between what Fastify expects a Date to be, and what TypeBox considers Dates and Strings to be. Consider the following.

```typescript
// TypeBox Interpretation
const T = Type.String({ format: 'date-time' })  // (standard) A string with a iso8601 format
const T = Type.Date()                           // (non-standard) A Date object 
```
Neither of these types seem to satisfy the Fastify interpretation ... which appears to be a `Date` with a `string` schematic. However, you can build this type using `Type.Unsafe()`.

```typescript
const T = Type.Unsafe<Date>({ type: 'string', format: 'date-time' }) 

type T = Static<typeof T> // type T = Date (or is it?)
```
This should help get around the type errors, quick example below.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoXowIQgA81MAFKCAN2ABMMo4BfOAM0pDgHIABVgQwDOMYK1QB6GHgC0YSjXpRpUzACNiXALAAoUJFhwAYkJFi2HbgOGjUW7ToDGEAHbC4ghlQZwAvEZM2ABQAlDo6HlBeUAB0AO7AMAAWpBgU1HQMADwphCR4aQoMAHwh0QDmGDCBXOJcOAg6cO4OiRgg-ABciI1NTVAYgpCuGF0N2r0TcABMAAwzXSnRAKqu-KwYmQAi-DAYJUgqI9zCUMDOZXVs0O0wXVy0OxjKoBhczKHjE0w939pMOIF+gBHHD9MAAG1QwV8RW6nzBkOiHmctECzgwsTg212IWh4nE7kSEAAruDaHBYtAANZwURsEzSABWghc0hOZzKNjgGGcTnogiujAeu0E0R0TGCQA)

```typescript
import { Type, TypeBoxTypeProvider } from '@fastify/type-provider-typebox'
import Fastify from 'fastify'

const server = Fastify()

server.withTypeProvider<TypeBoxTypeProvider>().get('/', {
  schema: {
     response: {
        200: Type.Unsafe<Date>({ type: 'string', format: 'date-time' })
     }
  }
}, (req, reply) => {
  reply.send(new Date()) // should work if fast-json-stringify encodes for dates.
})
```
If you have success using this. It might be possible to include this Type as default (possibly `Type.StringDate()` or similar). However it would be good to check first that decode (on request) works for string formats of `date-time` before considering the type as a default (as you would expect encode/decode to be symmetric for the type)

Let me know if this helps
S

**Comment by SeanReece** [comment]
@sinclairzx81 Yes! Using Type.Unsafe works! 🎉 

Love the idea of adding a Type as default, but looks like fastify uses `secure-json-parse` as the default json parser which (from what I can tell) doesn't use the schema and uses JSON.parse internally, so the encode/decode is *not* symmetrical and the incoming property is of type string.

Consider this contrived example with `date` and `date-time` types:

```ts
import { Type, TypeBoxTypeProvider } from '@fastify/type-provider-typebox'
import Fastify from 'fastify'

// Support date and date-time
const DateString = Type.Unsafe<Date>({ type: 'string', format: 'date' })
const DateTimeString = Type.Unsafe<Date>({ type: 'string', format: 'date-time' })

const user = Type.Object({
  name: Type.String(),
  birthday: DateString,
  createdAt: DateTimeString,
})

const schema = {
  body: Type.Omit(user, ['createdAt']),
  response: {
    200: user,
  },
}

const server = Fastify().withTypeProvider<TypeBoxTypeProvider>()

.get('/', { schema }, (req, reply) => {
  // inferred type for `birthday` is `Date`
  const { name, birthday } = req.body

  console.log(typeof birthday) // string

  return {
    name,
    birthday,
    createdAt: new Date() 
  }
})
```

Thanks again for your help!
