### ISSUE TITLE
Help with `fastify-rate-limit` in a TypeScript Project

### ISSUE THREAD

**Issue by agrattan0820** [fastify/help#877]
## 💬  Question here 

Hello! I was wondering how I would implement [fastify-rate-limit](https://github.com/fastify/fastify-rate-limit) in a typescript Fastify project, the documentation uses a unique way of importing the library that I'm unsure of how to handle.

As of now I'm importing the library like this:
```typescript
import rateLimit from "@fastify/rate-limit";
```
and then using it like this in a `buildServer()` function I have that creates the fastify instance:
```typescript
// app.ts
function buildServer() {
  // ...
  app.register(rateLimit, {
    max: 100,
  });
  // ...
return app;
}
```
then run like this:
```typescript
// server.ts
const server = buildServer();

server.listen({ port: 8080, host: host }, (err, address) => {
  if (err) {
    console.error(err);
  }
  // ...
});
```

After doing this though it seems that the rate-limiting headers are not in the response (unless I'm not understanding something).
![image](https://user-images.githubusercontent.com/51346343/236326917-bcc3edd2-2ef5-44d4-ab68-05e731d4136b.png)

Thank you in advance!

## Your Environment

- *node version*: v18.9.0
- *fastify version*: ^4.13.0
- *os*: Mac

**Comment by climba03003** [comment]
`await` inside the document is intended. Not a optional thing.

![image](https://user-images.githubusercontent.com/23028015/236359458-2456115b-5360-4519-a820-cfa6b309fea7.png)
