### ISSUE TITLE
reply.send inside async function 2019 ?

### ISSUE THREAD

**Issue by RafaelGSS** [fastify/help#88]
Hello everyone!

Reading the docs about async function in handlers, I see that the return by promise/async is automatically set to the payload. Works fine. But, I have the following `decorate` that needs works on async/sync handlers.

```js
fastify.decorateReply('success', function ({ message = 'Success', data = [], code = 200, totalRecords = 0 }) {
    this.type('application/json')
    this.send(generateResponse(data, message, code, false, totalRecords))
  })
  fastify.decorateReply('error', function ({ message = 'Error', data = [], code = 400 }) {
    this.type('application/json')
    this.send(generateResponse(data, message, code, true))
  })
```

So in handlers, I just call: `reply.success({})`.

My question is: 
- Is wrong call `reply.send` inside the async function? 
- Return `return reply.success({})` is wrong in sync/async function ?

If I remember, question 1 has the following workflow: when `reply.send` is called, the `reply.sent` is set to true, and the function return `undefined` because not has `return` statement, but `reply.sent` is already set to true, so the undefined/empty payload is not send. So does not have a problem, right ?

**Comment by nwoltman** [comment]
> Is wrong call reply.send inside the async function?

Nope, that's fine.

> Return return reply.success({}) is wrong in sync/async function ?

That's fine too.

> So does not have a problem, right ?

Yes, there's no problem.

You could have also answered these questions yourself by just trying it out:

```js
const fastify = require('fastify')
const app = fastify()

app.decorateReply('success', function (data) {
  this.type('application/json')
  this.send(data)
})

app
  .get('/', async (req, reply) => {
    reply.send('hello');
  })
  .get('/success', async (req, reply) => {
    reply.success({})
  })

app.inject('/', (err, res) => {
  console.log(res.statusCode, res.body)
})

app.inject('/success', (err, res) => {
  console.log(res.statusCode, res.body)
})
```

**Comment by RafaelGSS** [comment]
Alright. But, this workflow is correct?

> when reply.send is called, the reply.sent is set to true, and the function return undefined because not has return statement, but reply.sent is already set to true, so the undefined/empty payload is not send

**Comment by nwoltman** [comment]
Yes, that is correct. This is covered in the [Promise resolution](https://www.fastify.io/docs/latest/Routes/#promise-resolution) section of the docs. If the information there isn't clear enough, please let us know (or submit a PR) to help us explain things better.

If it helps, here's the Fastify code that handles the return value of `async` handlers: https://github.com/fastify/fastify/blob/master/lib/wrapThenable.js#L21-L35

**Comment by RafaelGSS** [comment]
Sure! Thanks so much for the help!

Closing the issue.
