### ISSUE TITLE
Fastify logger with multiple transports/streams?

### ISSUE THREAD

**Issue by Kimblis** [fastify/help#880]
## 💬  Question here 

Hey. I'm trying to configure fastify with pino using multiple transports and possibly streams. My needs are the following:
1) Integrate pino with sentry, possibly using pino-sentry package
2) Integrate pino with Loki, possibly using pino-loki package.

For now I'm using the following logger config:
```ts
export const generateFastifyConfig = (env: Environment) => ({
  logger: getApiLoggerConfig(env),
  maxParamLength: 2083,
  // disableRequestLogging: [Environment.STAGING, Environment.PRODUCTION].includes(env),
  disableRequestLogging: true,
  genReqId() {
    return uuidv4();
  },
});
```

```ts
const sentryStream = createWriteStream({ ...sentryStreamConfig, environment });
    return {
      stream: sentryStream,
      transport: {
        target: 'pino-pretty',
        options: {
          translateTime: 'HH:MM:ss Z',
          ignore: 'pid,hostname',
        },
      },
    };
```

```ts
export const sentryStreamConfig = {
  dsn: process.env.SENTRY_DSN,
  messageAttributeKey: 'message',
  stackAttributeKey: 'trace',
  extraAttributeKeys: ['type', 'path', 'input', 'user'],
  maxValueLength: 250,
  sentryExceptionLevels: [Severity.Warning, Severity.Error, Severity.Fatal],
};
```
So can we use multiple transports and keep this `pino-pretty` or if we want to use loki we can use only one transport? Also how do we make it so pino would send `error`, `fatal` and `warn` logs to sentry? I tried to console.error stuff however sentry is not receiving this, so clearly something is not working. Any ideas?

- *node version*: 19
- *fastify version*: >=4.13.0
- *os*: Mac

**Comment by metcoder95** [comment]
Hey!
Have you tried creating a custom transport that targets the three streams?
See [Pino#Transports](https://getpino.io/#/docs/transports). You can either pass an instance of `pino` with the preloaded transports as well.

**Comment by Kimblis** [comment]
What worked for me was 
```ts
import { transport, multistream } from 'pino';
```

```ts
    return {
      stream: multistream([{ stream: pinoPrettyTransport }, { stream: sentryStream }, { stream: pinoLokiStream }]),
    };
```
Logger accepts `stream` which sounds like singular, however it also works with `multistream` that pino provides, and multistream accepts more than 1 stream.

If someone face the same issue I hope that helps

**Comment by metcoder95** [comment]
Great! Thanks for sharing 👍 

I would still recommend `transports` instead given its performance benefits compared to multistreams. Just as note
