### ISSUE TITLE
Unable to obtain the set session value

### ISSUE THREAD

**Issue by imsole** [fastify/help#883]
#### You have already researched for similar issues?
Yes!

#### What are you trying to achieve, or the steps to reproduce?

```js
import { Controller, Get, Req } from '@nestjs/common';
import { AppService } from './app.service';
import { FastifyRequest } from 'fastify';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(@Req() req: FastifyRequest): string {
    req.session.set('code', '132');
    console.log(req.session);
    return req.session.get('code');
  }

  @Get('/code')
  getCode(@Req() req: FastifyRequest): string {
    console.log(req.session);
    return req.session.get('code');
  }
}

```

#### What was the result you received?
null

#### What did you expect?
Obtaining session

#### Context
<img width="751" alt="image" src="https://github.com/fastify/help/assets/3367457/e6e2ba16-2f21-466f-8b2f-4e06abc3a7f7">

<img width="1130" alt="image" src="https://github.com/fastify/help/assets/3367457/117615d1-ebc7-4116-9e76-af722579edf7">

* *node version*: 18.15.0
* *fastify version*: >=4.17.0
* *os*: Mac
* *nestjs
*
```
 "dependencies": {
    "@fastify/cookie": "^8.3.0",
    "@fastify/secure-session": "^6.1.0",
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/platform-fastify": "^9.4.2",
    "fastify": "^4.17.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "29.5.1",
    "@types/node": "18.16.12",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "29.5.0",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "29.1.0",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.2.0",
    "typescript": "^5.0.0"
  },
```
**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by mcollina** [comment]
Thanks for reporting. We do not have the resources to support Nest.js users. Please refer to the Nest [Discord](https://discord.gg/NestJS) channel (support) for such questions.
