### ISSUE TITLE
How do I set up a swagger schema for proxy routing

### ISSUE THREAD

**Issue by zlx362211854** [fastify/help#884]
![image](https://github.com/fastify/help/assets/22437181/5ad30218-1309-46ad-89a0-f5a8737acde2)

I use dynamic mode to create swagger, but routes mediated through @fastify/http-proxy automatically generate the above routes, so how do I define swagger parameters for such routes

Looking forward to your reply

**Comment by mcollina** [comment]
This is not currently possible at the moment with a Fastify module. At Platformatic, we have something in the works that would greatly help with this, just wait a few more days.
