### ISSUE TITLE
fastify plugin for better-sqlite3

### ISSUE THREAD

**Issue by punkish** [fastify/help#886]
#### You have already researched for similar issues?
yes

#### What are you trying to achieve, or the steps to reproduce?

after a couple of years of using `fastify` with `better-sqlite3`, I realized today that I might be using it wrong. As of now, I have a script that creates the db connection every time a route handler needs to get data from the db. The db connection does a little bit of housekeeping such as set correct pragmas, etc. before returning a db connection. But perhaps it is better to create a connection when the `fastify` server starts so the connection is not needlessly recreated every time.

For starters, am I approaching this right way? Then, I see a few db plugins (MySQL, Redis, Postgres, and even a sqlite plugin using node-sqlite) but none for `better-sqlite3`. Before I try to create one (I've never written a plugin before), I want to know if one already exists somewhere but perhaps I am not finding it in my searches.

**Comment by Eomm** [comment]
You can checkout this plugin: https://github.com/Eomm/fastify-sqlite
There is an open issue to support a good sqlite3 interface here: https://github.com/Eomm/fastify-sqlite/issues/7


Can't recall why I dropped `better-sqlite3` when I choose the underneath module..

**Comment by punkish** [comment]
reading further, seems like @databases/sqlite uses better-sqlite3 underneath anyway

> The @databases/sqlite-sync library provides a synchronous, safe and convenient API for querying SQLite databases in node.js. Built on top of [better-sqlite3](https://www.npmjs.com/package/better-sqlite3).

https://www.atdatabases.org/docs/sqlite-sync

**Comment by punkish** [comment]
ok, I've got a basic implementation working based on the example MySQL code on fastify website. It really is super-basic so I am not even sure of its effectiveness. Is there any way to ascertain that my db connection is made when fastify starts, and it remains open as long as the server keeps on running? After all, that is the point (or at least, my point) of developing a plugin for sqlite rather than creating a new connection on every REST request

**Comment by Eomm** [comment]
Nice work!

Here are a few suggestions to make it a community plugin:

- you may move the string `'/path/to/db.sqlite'` to the `options` object so you will be able to write:

`fastify.register(fastifyBetterSqlite3, { dbPath: '/path/to/db.sqlite'} )` to improve the reusability

- `if (!fastify.betterSqlite3) {` you may `next(new Error('plugin already registered'))` it the decorator is already in place

I hope you will publish it tho 👍🏼

**Comment by punkish** [comment]
hi everyone, hi @Eomm 

I have publish [fastify-better-sqlite3](https://www.npmjs.com/package/@punkish/fastify-better-sqlite3). It has more than one options to connect to a db because I wanted it to work for my situation but also be usable by others with different needs. There are a lot of comments and also examples of how to use it. There are no tests (other than my homegrown scripts to ensure it works), but I am using it in my own project and it is working so far.

Please let me know, anyone, if you spot something egregious. Hope it helps someone.
