### ISSUE TITLE
when we use https we need ssl certificates , when we use https2 do we need it .....

### ISSUE THREAD

**Issue by nettemsarath** [fastify/help#89]
#### You have already researched for similiar issues?
It's not uncommon that somebody already opened an issue or in best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/fastify/fastify/issues) at first before submitting a new one.

#### What are you trying to achieve or the steps to reproduce?

Describe your issue here, include as much detail as neccessary to reproduce the issue
or implement a missing functionality. If you are reporting a bug, you will get faster response
if you submit a pull request with a failing test.

```js
// Wrap code in markdown source tags
```

#### Context

* *node version*: 4,5,6,7,8,9
* *fastify version*: >=0.37.0
* *os*: Mac, Windows
* *any other relevant information*:

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by nwoltman** [comment]
It's not required, however, *currently no browser supports HTTP/2 unencrypted*, so if you want your server to work with browsers, you'll need an SSL certificate.

You can learn more here: https://http2.github.io/faq/#does-http2-require-encryption
And here's some Node.js info: https://nodejs.org/dist/latest-v12.x/docs/api/http2.html#http2_server_side_example
