### ISSUE TITLE
How to kill the process when an unknown error is thrown?

### ISSUE THREAD

**Issue by MatanYadaev** [fastify/help#892]
## 💬  Question here 

I want to kill the Node process when an unknown error is thrown. By "unknown error" I mean, any generic `Error` that is not wrapped by Fastify.

How can I do it?

```ts
app.get('/throw-error', (request, reply) => {
	throw new Error('asdasd');
});

app.inject({method: 'GET', path: '/throw-error' }); // This should kill the app
```

I can do it with `setErrorHandler` but there is no built-in way to identify Fastify's errors, because they are a regular `Error` class.

```ts
app.setErrorHandler((error, request, reply) => {
	if ((!error instanceof FastifyError)) { // It doesn't work because there is no such `FastifyError`
		// Unknown error - Log the error, close the application, and exit
		logger.error('Closing application due to an error', { error });

		app.close();
		process.exit(1);
	}

	// FastifyError - Return a response with the error message
	const statusCode = error.statusCode || 500;
	reply.code(statusCode).send({
		message: error.message,
		error: error.code,
		statusCode,
	});
});
```

## Your Environment

- *node version*: 20
- *fastify version*: 4
- *os*: Mac

**Comment by mcollina** [comment]
Usually the best way to do this is to check if there is a `.statusCode` property.

**Comment by Uzlopak** [comment]
Maybe abuse prepareStackTrace and check if the Error is of type FastifyError and if not call pocess.exit()

**Comment by MatanYadaev** [comment]
@Uzlopak Can you elaborate, please?

**Comment by spellsaif** [comment]
why not write code in try-catch block and if you encounter error, just close the fastify server (fastify.close()) and exit the process with error code (process.exit(1))

**Comment by mankeheaven** [comment]
Maybe like this?

```
import Fastify, { FastifyError, errorCodes } from "fastify";

fastify.decorate('isFasitifyError', (error: FastifyError) => {
	let flag = false
	Object.keys(errorCodes).forEach( err => {
		if(err=== error.code) { // I do not test this
			flag = true
			return flag
		}
	})
	return flag
})

fastify.setErrorHandler((error, request, reply) => {
	
	if (fastify.isFasitifyError(error)) {

		fastify.close();
		process.exit(1);
	}

	// FastifyError - Return a response with the error message
	const statusCode = error.statusCode || 500;
	reply.code(statusCode).send({
		message: error.message,
		error: error.code,
		statusCode,
	});
});
```

**Comment by Uzlopak** [comment]
@mankeheaven 

Thats pretty ugly. lol
it is easier to check it like this imho


fastify.decorate('isFastifyError', (error: FastifyError) => {
  return typeof error.code === 'string' && error.code in errorCodes
})

**Comment by mankeheaven** [comment]
@Uzlopak yeah, I just provide an idea. The code can't be uglier， I agree.

**Comment by Eomm** [comment]
Remeber to await the server's close too

```
fastify.setErrorHandler(async (error, request, reply) => {
	if (!fastify.isFasitifyError(error)) {
		await fastify.close();
		process.exit(1);
	}

	return reply.code(statusCode).send(error);
});
```

> Thats pretty ugly. lol

Please, be kind 🧸


Closing as solved

**Comment by MatanYadaev** [comment]
@Eomm The solution suggested is not 100% correct: not all Fastify errors have a `code` property. There are a few cases that Fastify throws a regular `Error` instance, and not an extended error.
For example, if the response doesn't match the response schema, `fast-json-stringify` throws an error. There are a few more cases that I encountered.
