### ISSUE TITLE
How to remove the req.log and replace it with own custom logger

### ISSUE THREAD

**Issue by RjManhas** [fastify/help#896]
How to remove the req.log and replace it with own custom logger

**Comment by metcoder95** [comment]
Hey!
You can replace it when instantiating the `fastify` server through the `logger` option, see the [reference](https://www.fastify.io/docs/latest/Reference/Server/#logger).

Just be sure it is `pino` compliant towards its method so it can be used properly

**Comment by RjManhas** [comment]
how would i add more functions with types like fastify.log.success and can you give a better example of a custom logger being used, can just be console.log

**Comment by RjManhas** [comment]
i got the example working but how do i add a custom level like log.success

**Comment by RjManhas** [comment]
im in ts btw

**Comment by metcoder95** [comment]
Depending on the logging library you are using (either `pino` or another), you need to look at the library documentation to see how to extend the logging capabilities. e.g. for Pino see [`customLogLevels`](https://github.com/pinojs/pino/blob/master/docs/api.md#customlevels-object)
