### ISSUE TITLE
[fastify-caching]: Error on get method

### ISSUE THREAD

**Issue by GHNewbiee** [fastify/help#899]
Hi, I have the following very simple code. It terminates with error. Any suggestion? *Tia*

```js
import Fastify from 'fastify'
import fastifyCaching from '@fastify/caching'
import abstractCache from 'abstract-cache'

const fastify = Fastify()
const abCache = abstractCache({ useAwait: true })

await fastify.register(fastifyCaching, {cache: abCache})

fastify.addHook('onRequest', async (request, reply) => {
  console.log(request) // It works fine.
  fastify.cache.set('prevReq', request, 10000).catch(console.error) // It seems to work fine - No error

  const prevReq = await fastify.cache.get('prevReq') // HERE ERROR IS PRODUCED!!!
  console.log('prevReq: ', prevReq)
  return
})

...
```

```terminal
node[56991]: ../src/base_object-inl.h:141:static void node::BaseObject::InternalFieldSet(v8::Local<v8::String>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&) [with int Field = 3; bool (v8::Value::* typecheck)() const = &v8::Value::IsFunction]: Assertion `((*value)->*typecheck)()' failed.
 1: 0xc925e0 node::Abort() [node]
 2: 0xc9265e  [node]
 3: 0xda2292  [node]
 4: 0x137f43e v8::internal::Object::SetPropertyWithAccessor(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::Maybe<v8::internal::ShouldThrow>) [node]
 5: 0x138ea92 v8::internal::Object::SetProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin, v8::Maybe<v8::internal::ShouldThrow>) [node]
 6: 0x14f37d0 v8::internal::Runtime::SetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin, v8::Maybe<v8::internal::ShouldThrow>) [node]
 7: 0x14f4fcb v8::internal::Runtime_SetKeyedProperty(int, unsigned long*, v8::internal::Isolate*) [node]
 8: 0x7f374bed9ef6 
Aborted (core dumped)
```

**Comment by jsumners** [comment]
Why are you trying to store a reference to a previous request? It will not be available once the request is complete. See the following update to your sample that works correctly:

```js
import Fastify from 'fastify'
import fastifyCaching from '@fastify/caching'
import abstractCache from 'abstract-cache'

const fastify = Fastify()
const abCache = abstractCache({ useAwait: true })

await fastify.register(fastifyCaching, {cache: abCache})

fastify.addHook('onRequest', async (request, reply) => {
  console.log('handling incoming request') // It works fine.
  await fastify.cache.set('prevReq', {foo: 'bar'}, 10000)

  const prevReq = await fastify.cache.get('prevReq') // HERE ERROR IS PRODUCED!!!
  console.log('prevReq: ', prevReq)

  return
})

fastify.route({
  method: 'get',
  path: '/',
  async handler (req, reply) {
    await this.cache.set('foo', 'bar')
    const foo = await this.cache.get('foo')
    return reply.send(foo)
  }
})

fastify.listen({
  port: 8000
})
```

**Comment by GHNewbiee** [comment]
@jsumners Thanks for your time and response.

> Why are you trying to store a reference to a previous request. 

I want to print out the diffs of a `request` object while passing through hooks. Same I want to do for `reply ` object.

>  It will not be available once the request is complete.

Sorry, I am not an IT folk and I do not get it. We have a function with `request` argument which I can print it out on console but it is not available until the request is complete. Although, by means of some lifecycle hooks I can change it.

What I have read in the doc and understood is that only the `request.body` is not available at that miment.

Is it sure that the plugin supports complicated objects like `request`?

**Comment by jsumners** [comment]
I would suggest recording the actual details you're interested in by copying them to a new object and then comparing against that.

**Comment by GHNewbiee** [comment]
Would it be possible a note to be added in the doc that "complicated" objects like `request` are not supported (maybe because it is not the goal or something similar). Mentioning such limitation/restriction/similar (with a reason) is really a good thing. Many thanks for your time.

**Comment by jsumners** [comment]
In my opinion, such is outside of the scope of our documentation. The underlying issue here seems to be a misunderstanding of how HTTP requests work. HTTP is a stateless protocol. A request is made to a server, the server responds, and the request is ended.

**Comment by GHNewbiee** [comment]
JFYI, the key here is `inspect` from `node:util` to remove `cycles`, or whatever called, from `request` object. With `inspect(request)` the string result can easily get stored.
