### ISSUE TITLE
do we need ssl certicate for https2 and  if iam using ngnix proxy where should i use ssl certicates in the nodejs server or ngnix server ????

### ISSUE THREAD

**Issue by nettemsarath** [fastify/help#90]
#### You have already researched for similiar issues?
It's not uncommon that somebody already opened an issue or in best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/fastify/fastify/issues) at first before submitting a new one.

#### What are you trying to achieve or the steps to reproduce?

Describe your issue here, include as much detail as neccessary to reproduce the issue
or implement a missing functionality. If you are reporting a bug, you will get faster response
if you submit a pull request with a failing test.

```js
// Wrap code in markdown source tags
```

#### Context

* *node version*: 4,5,6,7,8,9
* *fastify version*: >=0.37.0
* *os*: Mac, Windows
* *any other relevant information*:

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by mcollina** [comment]
This issue seems just the template. In the title, you write:

> do we need ssl certicate for https2 and if iam using ngnix proxy where should i use ssl certicates in the nodejs server or ngnix server ???? 

I would recommend placing the https certificate on nginx. However nginx does not support http2 destination. As a result, you might want to place the certificates on your server, and do not rely on nginx but on haproxy.

**Comment by nettemsarath** [comment]
No, the ngnix is supporting htttps2 also..
