### ISSUE TITLE
Are all error codes handled from a route

### ISSUE THREAD

**Issue by RjManhas** [fastify/help#902]
Hello im setting up custom error handling and wanted to know if all of theses error codes i can response with reply.status.....
https://fastify.dev/docs/latest/Reference/Errors/

**Comment by metcoder95** [comment]
Hey! Could you elaborate?
Did you ask if those error codes can be handled within the `setErrorHandller`?

**Comment by Uzlopak** [comment]
Those are the Errors, which Fastify will throw. You are not limited to them. You can throw your own errors, if you like.
