### ISSUE TITLE
@fastify/websocket - is each route a new socket connection?

### ISSUE THREAD

**Issue by gregg-cbs** [fastify/help#910]
Hi,

I want to know if each route setup for websocket in fastify is a new socket connection?

I am trying to establish if I should have 1 socket route or if I can have multiple?

Example code:
```javascript
// multiple routes
  fastify.get('/order/websocket', { websocket: true }, (connection, req) => {
    connection.socket.on('message', message => {
      // some stuff
    })
  })
  fastify.get('/account/websocket', { websocket: true }, (connection, req) => {
    connection.socket.on('message', message => {
      // some stuff
    })
  })

// single route
  fastify.get('/websocket', { websocket: true }, (connection, req) => {
    connection.socket.on('message', message => {
      const incoming = JSON.parse(message.toString());

      if (incoming.topic === 'orders') {
        // stream orders updates to user
      }
      if (incoming.topic === 'account') {
        // stream account updates to user
      }
    })
  })
```

**Comment by gregg-cbs** [comment]
I am guessing each route would be a new socket connection from the front end because you have to subscribe to a route like this `let socket = new WebSocket("ws://localhost:4000/websocket");`

**Comment by metcoder95** [comment]
Hey! Yeah, you get it right, every request to each different route will be translated into a new web socket connection.

> So a single socket would be better and then create topics that a socket client can subscribe to.

That depends on your needs. If looking for something similar to rooms or topics, a WebSocket per route might be a good way to go. Although you can achieve the same by categorising and assigning some sort of identifier to each websocket depending on the initial message between them. Repeating myself, it depends on your needs 🙂

**Comment by gregg-cbs** [comment]
Thanks for you comment!

I reckon a single socket with a topic property to discern between districts. I worry about having multiple socket connections as I have read that some platforms like heroku limit socket connections to 600 . I have already read that some servers can handle up to 60 000 socket connections and some say up to 1 million  .

For now I dont mind doing a socket payload like this:
```
{
 topic: 'order',
 data: {...}
}
```
