### ISSUE TITLE
How to share the context from called request handler to outer service?

### ISSUE THREAD

**Issue by sujeet-agrahari** [fastify/help#912]
## 💬  Question here 

_I have a very weird question, apologies in advance!_

I have been trying to develop a node-fastify app that follows a modular architecture, every business entity will be wrapped inside a single module and everything it needs to run.

If let's say I have a `auth` module, it will contain routes, controllers, services etc. 

I like the idea of separating services from controllers because they can talk to multiple services combine and process the data before sending back the response.

Also, services can be lengthy If they need to process a lof of things. 

These are the reasons, I like to separate them.

I have laid out the architecture following the same idea. Below are the things that I did to achieve it,

1. There is a `server.js` file which feeds the app configuration, and build it, and attaches a http listener.
2. The `app.js` will register the plugins, configs, etc. configuration passed by the `server.js`

I used decorators to bind all the globally required utilities to the `app` like configs, db, http error package etc.

The idea is to cut down the frequent import of controllers and services which are frequently needed. Also, this makes the code more testable as we can mock them easily.

Now, the problem I am faceing is by default request handlers have the context of the app i.e. access to this keyword. It means we can do `this.confgi` in the controllers. 

**_But, when we call the `service` from the controller(request handler), we lose the app context. We don't have the `app` context anymore in the service, and we can't use `this` inside the service methods. So we have to import the required configs, db etc._**

**_As a fix, I am passing this as context to service methods._** 

First of all, I create a `auth.module.js` file which is responsible for stitching all the required entities for this module together

```
import AuthRoutes from './auth.routes.js';
import AuthService from './auth.service.js';
import AuthSchema from './auth.schema.js';
import AuthController from './auth.controller.js';

export default async function AuthModule(app) {
  app.decorate('authSchema', AuthSchema);
  app.decorate('authService', AuthService);
  app.decorate('authController', AuthController);

  app.register(AuthRoutes, { prefix: '/auth' });
}

// export services used by other modules
export { AuthService };
```

Now, I can register my route handler i.e. the controller,

```
const AuthController = {
  async login(request) {
    const loginData = await this.authService.login(this, request.body);
    return loginData;
  },
};

export default AuthController;
```
Above, you can see I am passing `this` keyword as the context so that the service method has access to it.

Finally below is my service file:

```
const AuthService = {
  async login(context, requestBody) {
    const { name, email } = requestBody;

    const result = await context.db.user.create({
      data: {
        name,
        email,
      },
    });
    return result;
  },
};

export default AuthService;
```

**_I don't know why I am hesitant to pass the `this` around. I am just wondering If there is any better way? A fastify way?_** 

Here is the repository which contains the full code, please do have alook and provide your suggestions, thanks.
https://github.com/sujeet-agrahari/node-fastify-architecture

## Your Environment

- *node version*: 20
- *fastify version*: 4.21.0
- *os*: Mac
- *any other relevant information*

**Comment by mcollina** [comment]
That's totally fine, `this` is set there for precisely that purpose.

However a sligly better implementation would look like:

```js
export function buildAuthController (server) {
  return {
  async login(context, requestBody) {
    const { name, email } = requestBody;

    const result = await context.db.user.create({
      data: {
        name,
        email,
      },
    });
    return result;
  },
  }
};
}
```

which you'll then construct in your Fastify plugin

**Comment by sujeet-agrahari** [comment]
So, you are suggesting making the `auth.controller` a plugin and merging the `auth.service`?

**Comment by mcollina** [comment]
that'd be one option, but just a function invoked by the actual plugin is ok G enerically controller holds to some state (db connection etcs), so you'd want to have it in a closure around them.
