### ISSUE TITLE
How do I use Typescript to show that that a `project` key exists on the request?

### ISSUE THREAD

**Issue by vedantroy** [fastify/help#913]
Hi! I'm trying to figure out how to attach a `project` object to the request using middleware + properly type it using Typescript. Here's an example:
```
const MOUNT = { prefix: "/project/:pid/job/" }

const attachProjectMiddleware = async (req: FastifyRequest, reply: FastifyReply, done: () => void): Promise<void> => {
  //@ts-ignore
  req.project = await getProject(req.params.pid as string)
  done()
}
app.addHook("preHandler", attachProjectMiddleware)
```

The 2 things I need to figure out are:
1. Is this even the correct way to add something to a request?
2. How do I correctly add Typescript types to this code, so typescript understands `req.project` is valid?

In my handler:
```
  app.post<ProjectIdRoute>(`/do_important_thing/start`, async (req, reply) => {
    // need this to typecheck
    req.project
}
```
where `ProjectIdRoute` looks like this:
```
export interface ProjectIdRoute {
  Params: {
    pid: string
  }
}
```

**Comment by mcollina** [comment]
Something like would work:

```ts
declare module 'fastify' {
  interface FastifyRequest {
    project: string
  }
}
```
