### ISSUE TITLE
How do I inspect a request AFTER rewriteRequestHeaders?

### ISSUE THREAD

**Issue by csvan** [fastify/help#915]
#### What are you trying to achieve, or the steps to reproduce?
I am using `@fastify/http-proxy` to implement an API Gateway which forwards public requests to a range of internal servers.

I use the `rewriteRequestHeaders` from `@fastify/http-reply-from` in order to modify the headers of these requests for internal purposes. 

Now, my use case is that I want to perform some custom logging of the request AFTER the headers have been modified, but just BEFORE it is sent.

I have tried using the `onSend` hook for this, which to my understanding should be the last hook executed before a request is sent. However, I cannot see the modified headers in the request argument for that hook, so it seems it is not taking the updated request into account.

Is there any way to solve this? I know I could do the logging inside the `rewriteRequestHeaders` method, but this feels like an ugly hack violating the purpose of that method.

* *node version*:  18
* *fastify version*: >=4
* *os*: Mac

**Comment by Eomm** [comment]
I think `replyOption.onResponse` give you the `request` object with the updated headers:

https://github.com/fastify/fastify-reply-from#onresponserequest-reply-res

https://github.com/fastify/fastify-reply-from/blob/7009d91f8dc9087c79957685e462ca8c931192b7/index.js#L151

**Comment by csvan** [comment]
@Eomm thanks for the kind reply, but I need to inspect the final request object _just before_ it is dispatched, `onResponse` as I understand it triggers when a response is received from upstream. My use case is integration logging so logs need to be dispatched before further processing is done upstream.

**Comment by Uzlopak** [comment]
onResponse is the last hook in the lifecycle and is triggered right before the response is sent to the clint.

**Comment by csvan** [comment]
@Uzlopak thanks, but I need to intercept the request JUST BEFORE it is sent, not after a response is dispatched from upstream

**Comment by Eomm** [comment]
It is not supported this granularity - you would need to add this feature
