### ISSUE TITLE
Do I need to install Pino as dependency to be able to customize the logger options?

### ISSUE THREAD

**Issue by sujeeet-kumar** [fastify/help#917]
My logger options looks something like below,
```
const options = {
  name: `My Service`,
  level: config.logging.stdout.level || 'info',
  timestamp: pino.stdTimeFunctions.isoTime,
  serializers: {
    err: pino.stdSerializers.err,
    req(req) {
      return getLoggingRequestMetadata(req);
    },
    res(reply) {
      return {
        statusCode: reply.statusCode,
        headers: typeof reply.getHeaders === 'function'
          ? reply.getHeaders()
          : {}
      };
    }
  }
};
```
Here, as you can see I want to use `pino.stdTimeFunctions.isoTime` and `pino.stdSerializers.err`.

But I can't use these without importing Pino which will make me install it as a dependency. 
I know Fastify has Pino as a dependency as well which can be of different versions of Pino.

Is there any way I could customize it without installing Pino? Because the versions can be different, also It will avoid having duplicate dependencies.

**Comment by mcollina** [comment]
You can't at the moment, you'd need to install pino. All package managers deduplicate this correctly if the version ranges overlap.

Fastify and pino mostly follow an aligned release cycle, so I would not worry too much about this.
