### ISSUE TITLE
When to prefer fastify.decorateRequest() over fastify.decorate()?

### ISSUE THREAD

**Issue by sujeeet-kumar** [fastify/help#918]
Should I use `decorate()` or `decorateRequest()` to add configuration, values, or functions at the request level?

 Both achieve the same result. Additionally, `this.log` and `req.log` are available in the request context in the handler.

 Is there a usage guide for determining when to use `decorate()` or `decorateRequest()`? Is there any performance impact?

Examples:

- Using decorateRequest():
 ```
fastify.decorateRequest('userId', 123);
```

- Using decorate():
```
fastify.decorate('userId', 123);

```
- Accessing values:
```
function requestHandler(request, reply) {
  request.log.info(request.userId);
  this.log.info(app.userId);
}
```

**Comment by mcollina** [comment]
the app is shared between all routes invocations, while the request is specific for an invocation. Any user-bound value should be in the request, while everything cross-user in the app.
