### ISSUE TITLE
[Question] How can I .send() multiple times like express with .write()

### ISSUE THREAD

**Issue by bretthadley** [fastify/help#92]
#### What are you trying to achieve or the steps to reproduce?

I'm trying to write multiple times to a reply like in the express example below

```js
export const ssr = async (req, res) => {
  res.write('<html><head>....</head><body>.<div id="app">');
  renderToNodeStream(app)
  .pipe(
    through(
      function write(data) {
        this.queue(data);
      },
      function end() {
        this.queue(footer);
        this.queue(null);
      }
    )
  )
  .pipe(res);
}
```

#### What was the result you received?
```js
export const ssr = async (request, reply) => {
      const stream = getApplicationStream(app);
      res.status(200)
      res.header('content-type', 'text/html')
          .send('<html><head>....</head><body>.<div id="app">')

      res.header('content-type', 'text/html')
           .send(stream)
}
```

#### What did you expect?
I expected to receive the first chunk of <html> string then as the react app renders it will stream rest of the html to browser. When I have the stream.on('end') . Push the closing html 

#### Context

* *node version*: latest
* *fastify version*: latest
* *os*: Mac

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by nwoltman** [comment]
Using `reply.send()` is similar to `res.end()` (or `res.send()`) in Express; it sends data and ends the response. To use `.write()` and `.pipe()`, you'll need to grab `res` off of the `reply` object:

```js
export const ssr = async (request, reply) => {
  const res = reply.res;
  res.write('<html><head>....</head><body>.<div id="app">');
  // ...
}
```

**Comment by nwoltman** [comment]
Closing since it seems like this was solved
