### ISSUE TITLE
What difference does it make having fastify.decorate() inside a fastify-plugin over fastify.decorate()?

### ISSUE THREAD

**Issue by sujeet-agrahari** [fastify/help#920]
I can use a `fastify-plugin` to register my `http-errors` class as below:

```
import fp from 'fastify-plugin';
import * as HttpError from '../utils/http-errors.js';

export default fp(async function httpErrorsPlugin(app, _opts) {
  // app error handler
  app.decorate('HttpError', HttpError);
}, { name: 'http-errors' });
```

Also, I can directly decorate this on the fastify app itself.
```
app.decorate('HttpError', HttpError);
```
In both cases, the context will be the same, the root app context.

_**Is there any difference between the above methods? Also, which one is recommended?**_

**Comment by Asjas** [comment]
> In both cases, the context will be the same, the root app context.
> Is there any difference between the above methods?

No, there is no difference in the above methods. 

You are using `fastify-plugin` to remove the plugin encapsulation so the result will be the exact same, the `root` context is getting the decoration. If you don't use `fastify-plugin` then the difference will be that the plugin will have the app decoration only scoped to the context of the plugin itself.

> Also, which one is recommended?

It will depend on the situation, there are no hard rules here. 🙂
