### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by hornta** [fastify/help#922]
## 💬  Question here 

I'm making an endpoint that expects to receive a single file and some other scalar fields in the FormData payload. I'm using the multipart library for this.

How can I now validate so that the endpoint can only receive ONE file? If some user tries to send too many files I want to reject it or do I have to account for that even though I will be using the `await req.file()`?

What if it eats up all of the memory? Do my questions even make sense? I'm not used to work with multipart/form-data

```js
// example codes if any
````

If possible add a link to sample codes for error reproduction (github or replit)

## Your Environment

- *node version*: 10, 12, 13
- *fastify version*: >=2.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by mcollina** [comment]
There are the limits in the options, check out the README.

https://github.com/fastify/fastify-multipart
