### ISSUE TITLE
Is it possible to disable parsing the body into JSON for a specific route?

### ISSUE THREAD

**Issue by josdejong** [fastify/help#923]
I have an application where you can upload JSON documents, which are stored as-is in a datastore. These POST requests are send with a `content-type: application/json`. Because of this, Fastify parses the `request.body` into JSON. Basically something like:

```js
app.post('/docs/:id/', {
  handler: async (request) => {
    const id = request.params.id
    const doc = request.body // must be string, but Fastify turns it into JSON when content-type is application/json
    await myDataStore.save(id, doc)
  }
})
```

I am aware of the plugin `fastify-raw-body`, which can add a `request.rawBody` field alongside the parsed `request.body` field. However, the documents I'm dealing with can be large and I do not want Fastify to parse the `request.body` in the first place: it costs needless CPU.

Is there a way to tell the build-in content type parser of Fastify to _not_ parse the body of a specific route and keep it a string (ignoring the content-type header)? Something like:

```js
app.post('/docs/:id/', {
  config: {
    parseAs: 'string'
  },
  handler: async (request) => {
    const id = request.params.id
    const doc = request.body // is string despite content-type being application/json
    await myDataStore.save(id, doc)
  }
})
```

Or do I have to `removeAllContentTypeParsers` and implement my own custom content type parser?

**Comment by metcoder95** [comment]
Hey!
It should be possible without too much effort if the text is set with `content-type: text/plain`, otherwise `fastify` will try to parse it if it receives `content-type: application/json`. Or did you find an issue using it it?

**Comment by josdejong** [comment]
Thanks for your response Carlos.

Yes I understand that using `content-type: text/plain` solves this, but it is not under my control what headers clients send to my API, and it would be quite odd to require them to use `content-type: text/plain` and not `application/json` to send _JSON_ data to my API.

Is there maybe a hook to override the `content-type` header before Fastify parses the body?

**Comment by metcoder95** [comment]
Well, if that's the case there are several ways you can achieve what you are looking for:

First, you can set a hook on the [`onRequest`](https://fastify.dev/docs/latest/Reference/Hooks#onrequest) hook to not alter the body, and treat it as a string instead of trying to parse it into a `JSON` object, although you'll require to call `request.hijack` to avoid the hooks from continuing running.

Another thing you can do is to scope the route within a `context` (using `fastify.register`), and replace the `contentTypeParser` with a custom `application/json` parser based on your needs. It is the cleanest one I believe.

**Comment by Eomm** [comment]
> Another thing you can do is to scope the route within a context (using fastify.register), and replace the contentTypeParser with a custom application/json parser based on your needs. It is the cleanest one I believe.

Totally agree on this:

```js
const app = require('fastify')({ logger: !true })

app.register(async function pluginNoParseJson (app, opts) {
  app.addContentTypeParser('application/json', {
    parseAs: 'string',
    asString: true
  }, app.defaultTextParser)

  app.post('/', async (request, reply) => {
    console.log(typeof request.body)
    return request.body + ' world'
  })

  // all the routes here will not parse the application/json input
})

app.post('/parse', async (request, reply) => {
  console.log(typeof request.body)
  return request.body
})

app.listen({ port: 8080 })
```

**Comment by josdejong** [comment]
ow that is beautiful @Eomm , thanks! It works like a charm.

Using a new context via `fastify.register` is indeed what I was looking for so I don't apply this special behavior globally, thanks @metcoder95 . I first created a custom content type parser, but then I loose for example the validation of a max bodyLimit. Next I created a `preParsing` hook that changes the `content-type` header to `text/plain` and restores this in a `preHandler` hook, that works but is quite an ugly workaround. Overriding the content type parser for `application/json` with `app.defaultTextParser` inside a scope is the best of both world 👌.

I've created a little wrapper function to apply this behavior, it now looks like:

```ts
// file: parseBodyAsString.ts
import { FastifyInstance } from 'fastify'

/**
 * Parse the request body as string (and not JSON) for 'content-type: application/json'
 *
 * Usage:
 *
 *     parseBodyAsString(app, (app) => {
 *       app.post('/docs/:id', request => {
 *         // now request.body is always a string
 *       })
 *     }
 */
export function parseBodyAsString(app: FastifyInstance, callback: (app: FastifyInstance) => void) {
  app.register(async function (app) {
    app.addContentTypeParser('application/json', { parseAs: 'string' }, app.defaultTextParser)

    callback(app)
  })
}
```

**Comment by kurtextrem** [comment]
Maybe it might make sense to be able to automatically tell from a Route Schema, if JSON is needed or not?

Currently, I wouldn't say it's a security issue, but it definitely wastes a random amount of CPU time, if you submit a large JSON content to an endpoint that does not need the body or JSON at all. If we could automatically derive from a schema "the body is not needed, so ignore the content-type header", we could automatically fix this.
