### ISSUE TITLE
Query string: several values for the same query

### ISSUE THREAD

**Issue by simonrythme** [fastify/help#925]
Hello 👋

I'm creating an endpoint which is able to handle several value for the same querystring. I created a schema with [Typebox](https://github.com/sinclairzx81/typebox):
```typescript
export const getProductRestSchema = {
  querystring: Type.Object({
    id: Type.Optional(Type.Union([Type.String(), Type.Array(Type.String())])),
    categoryId: Type.Optional(Type.Union([Type.String(), Type.Array(Type.String())])),
    familyId: Type.Optional(Type.Union([Type.String(), Type.Array(Type.String())])),
    shopId: Type.Optional(Type.Union([Type.String(), Type.Array(Type.String())])),
  }),
  response: {
    ...defaultSchema,
    200: Type.Array(productSchema),
  },
};
``` 

On this endpoint, I'm able to send several `id` in this way: `/product?id=1&id=2&id=3`.
By doing that, I'm getting an array of strings into `request.query.id`.

My REST API is mainly requested by an iOS application which is using [Alamofire](https://github.com/Alamofire/Alamofire) as HTTP request lib.
Because it using dictonnary to manage the querystrings, it's not possible to put several time the same key.

Thanks to [this stackoverflow answer](https://stackoverflow.com/a/63881567/4520019), we found a workaround but the final result is not the same: 
```bash
request.query: {
  "ids[]": [
    "1",
    "2",
    "3"
  ],
}
```

What is the best way to handle this two scenario ? Is it possible to "force" Fastify to transform the `ids[]` to `id` ?

**Comment by metcoder95** [comment]
Hey 👋 

Fastify uses Node.js's core module `querystring` to parse the URL query string from a request. Sadly, it does not support such syntax.
You can make use `qs` as work around to support the given syntax you are looking for, take a look at [the following docs](https://fastify.dev/docs/latest/Reference/Server#querystringparser) to see how to mount it on top of `fastify`
