### ISSUE TITLE
Is there required all for object props?

### ISSUE THREAD

**Issue by ReTWi** [fastify/help#93]
Is there a shortcut for required field in shema, something like:

```
schema: {
      body: {
        type: 'object',
        properties: {
             prop1: { type: 'string'},
             prop2: { type: 'integer'}
       },
       required: [prop1, prop2]  // is there a way to use all instead all the props? Like required: 'all'
}
```

**Comment by RafaelGSS** [comment]
Your example was wrong. And I don't understand what you want.

**Comment by ReTWi** [comment]
@RafaelGSS it's working in code, so i don't think it's wrong. Updated question.

**Comment by RafaelGSS** [comment]
Fastify uses [ajv](https://github.com/epoberezkin/ajv) like default [schemaCompiler](https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md#schema-compiler).

Personally, I don't think that can be util required 'all', but you could send a question in ajv issues.
