### ISSUE TITLE
deprecated fastifyRequestContextPlugin - lack of documentation(?)

### ISSUE THREAD

**Issue by rmogio-encora** [fastify/help#930]
## 💬  Deprecated fastifyRequestContextPlugin

So, I'm working on a NestJS(with typescript) project that uses fastify framework. Previously we used `"@fastify/request-context": "3.1.1"`, when migrating it to version 5.0.0, I started getting deprecated error related to `fastifyRequestContextPlugin`;

I checked the documentation present on https://github.com/fastify/fastify-request-context#getting-started, but it says to use `fastifyRequestContextPlugin`. Is there a way to get rid of this error?

This is a code snippet where I'm creating the fastify instance:
```ts
const createFastify = async (): Promise<FastifyInstance> => {
  const fastify = Fastify();

  await fastify.register(fastifyRequestContextPlugin, {
    hook: 'onRequest',
    defaultStoreValues: {},
  });

  fastify.addHook('preValidation', (request, _reply, done) => {
    requestContext.set('body', request.body);
    done();
  });

  return fastify;
};
````

And below the example from documentation, which says to use the deprecated plugin:
```ts
const { fastifyRequestContextPlugin } = require('@fastify/request-context')
const fastify = require('fastify');

fastify.register(fastifyRequestContextPlugin, { 
  hook: 'preValidation',
  defaultStoreValues: {
    user: { id: 'system' } 
  }
});
```

## Environment

- *node version*: 18.15.0
- *fastify version*: 4.22.0
- *os*: Linux
- *NestJS version*: 9.4.3

**Comment by jsumners** [comment]
There are no deprecations posted for https://www.npmjs.com/package/@fastify/request-context

Please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example). Doing so will help us diagnose your issue. It should be the bare minimum code needed to trigger the issue, and easily runnable without any changes or extra code.

You may use a GitHub repository to host the code if it is too much to fit in a [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) (or two).

**Comment by rmogio-encora** [comment]
hello!
@jsumners I'll provide a reproducible example. 

@kibertoad this is the error I'm getting:
![image](https://github.com/fastify/help/assets/69254572/d45ea35c-a441-4dd8-91e4-90b0301e0c17)

**Comment by jsumners** [comment]
The "library" _is_ the plugin. I don't know what your screenshot is referring to.

**Comment by rmogio-encora** [comment]
The `fastifyRequestContextPlugin` is marked as deprecated here: https://github.com/fastify/fastify-request-context/blob/master/types/index.d.ts#L54

I couldn't find documentation explaining how to change from `fastifyRequestContextPlugin` to `fastifyRequestContext`. Is it just replacing one to another? Do I need to do something else?

**Comment by kibertoad** [comment]
@rmogio-encora You are using the wrong import.

  /**
   * @deprecated Use fastifyRequestContext instead
   */

Probably we should clarify the message. Same library, different import.

**Comment by rmogio-encora** [comment]
@kibertoad Thank you! I'd say to also update the documentation present on GitHub, it'd be helpful.

Thanks for helping me, and sorry for the confusion :smile:

**Comment by Uzlopak** [comment]
We deprecated the fastifyXPlugin types/exports in favor of fastifyX types/exports. This was basically for streamlining all the plugins when we implemented the infamous triplet and made the types nodenext compatible. As it was more like a cosmetical change, atleast i did not force a semver-major.
