### ISSUE TITLE
Did it plan to rework Fastify to handle more requests in Bun runtime ?

### ISSUE THREAD

**Issue by qlaffont** [fastify/help#931]
#### What are you trying to achieve, or the steps to reproduce?

I was checking https://elysiajs.com/ and I checked their performance results. 

And I wanted to know that it is planned to optimize Fastify to have a performance update on Bun runtime ?

Results -> https://github.com/SaltyAom/bun-http-framework-benchmark/tree/c7e26fe3f1bfee7ffbd721dbade10ad72a0a14ab#results

**Comment by jsumners** [comment]
Fastify is developed on Node.js. We do not have any plans to support any other runtimes.
