### ISSUE TITLE
multiple sessions being created upon login with @fastify/session + @fastify/passport

### ISSUE THREAD

**Issue by jcbain** [fastify/help#932]
#### You have already researched for similar issues?
Yes

#### What are you trying to achieve, or the steps to reproduce?

In attempts to create a basic authentication flow with @fastify/session and @fastify/passport, upon logging in, two sessions per login get created and stored to the `SessionStore`. I'm curious if this is the intended behavior? In my mind, only one session should be created that has an associated passport id per login but perhaps I am misunderstanding how the flow should work. Otherwise, it seems like the SessionStore can get polluted very quickly.

In order to attempt to show what is going on, I've created a repository that has 2 auth flows: 1) with just fastify/session and one with fastify/session + fastify/passport.

1. download https://github.com/jcbain/tb-session and install the dependencies `npm install`
2. run the sever `npm run dev`
3. navigate to `/auth/passport` and login with the sample user (username: `test`, password: `password`)

This repo is just using the in memory `SessionStore` so a breakpoint can be placed in `node_modules/@fastify/session/lib/store.js` to see the number of session stored in memory upon login.

```js
// Wrap code in markdown source tags
```

#### What was the result you received?
For each login, two sessions are created in the session store using fastify/passport.

#### What did you expect?
For each login, I would expect only one session

#### Context

* *node version*: 18
* *fastify version*: >=4.22.0
* *os*: Mac
* *any other relevant information*:

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by mcollina** [comment]
Looks like a bug.

@marco-ippolito wdyt?

**Comment by jcbain** [comment]
Thank you for the confirmation. What would be the next steps? Should I open up an issue in fastify/passport? I'm also happy to create an associated PR if need be.

**Comment by marco-ippolito** [comment]
> Thank you for the confirmation. What would be the next steps? Should I open up an issue in fastify/passport? I'm also happy to create an associated PR if need be.

Open a PR linking this issue
