### ISSUE TITLE
Fluent-json-schema typescript error [help]

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [fastify/help#933]
## 💬  Question here 

I'm creating a demo project using Platformatic at the latest version (see package.json under). I'm creating some plugins for the project in which I'm using `fluent-json-schema` that seems to have some Typescript issue. In fact I'm receiving this error:

<img width="449" alt="image" src="https://github.com/fastify/help/assets/67106822/5722fa5c-78eb-4175-b2e7-317126d5fcef">

tsconfig.json:

```js
{
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true,
    "target": "es2020",
    "sourceMap": true,
    "pretty": true,
    "noEmitOnError": true,
    "incremental": true,
    "outDir": "dist"
  },
  "watchOptions": {
    "watchFile": "fixedPollingInterval",
    "watchDirectory": "fixedPollingInterval",
    "fallbackPolling": "dynamicPriority",
    "synchronousWatchDirectory": true,
    "excludeDirectories": [
      "**/node_modules",
      "dist"
    ]
  }
}
```

Package.json:

```js
{
  "scripts": {
    "start": "platformatic start",
    "dev": "platformatic start --watch",
    "clean": "rm -fr ./dist",
    "build": "platformatic compile",
    "migrate": "platformatic db migrations apply"
  },
  "devDependencies": {
    "fastify": "^4.22.2",
    "typescript": "~5.2.0"
  },
  "dependencies": {
    "@fastify/autoload": "^5.7.1",
    "@fastify/env": "^4.2.0",
    "@fastify/oauth2": "^7.4.0",
    "@platformatic/db": "^0.40.0",
    "fastify-plugin": "^4.5.1",
    "fluent-json-schema": "^4.1.1",
    "platformatic": "^0.40.0"
  },
  "engines": {
    "node": "^18.8.0"
  }
}

````

## Your Environment

- *node version*: v18.17.1
- *fastify version*: 4.22.2
- *os*: Mac

**Comment by mcollina** [comment]
Could you include a complete example?

**Comment by giovanni-bertoncelli** [comment]
Hi! Here: https://codesandbox.io/p/sandbox/node-js-k8dsq1?file=%2Findex.js%3A2%2C1 running "npm start" it gives me the same error.. but maybe it's a mistake of mine

**Comment by giovanni-bertoncelli** [comment]
sorry the sandbox got deleted.. one sec

**Comment by mcollina** [comment]
A github repo will be fine.

**Comment by giovanni-bertoncelli** [comment]
There you go: https://github.com/giovanni-bertoncelli/platformatic-demo 👍🏻

**Comment by leorossi** [comment]
Found the bug

In `fluent-json-schema` type definition there are two interfaces called `SchemaOptions`
- https://github.com/fastify/fluent-json-schema/blob/master/types/FluentJSONSchema.d.ts#L70
- https://github.com/fastify/fluent-json-schema/blob/master/types/FluentJSONSchema.d.ts#L212

One is exported the other not.

Changing that file adding the missing `export` will make it work but of course we can't do that as it's an external dependency

any clue @mcollina ? Maybe a TS option to add?

**Comment by giovanni-bertoncelli** [comment]
Maybe it can be declared only once?
