### ISSUE TITLE
Get plugin name on after callback

### ISSUE THREAD

**Issue by ehduardu** [fastify/help#936]
Hi guys!

Is it possible to get the plugin name in `.after()` API?

Something like that:

```
fastify
  .register((instance, opts, done) => {
    console.log('Current plugin')
    done()
  })
  .after((err, name) => {
    console.log('After current plugin', name)
  }) 
```

**Comment by mcollina** [comment]
Not at this point unfortunately, why do you need it?

**Comment by ehduardu** [comment]
I was thinking of using it for observability metrics, but I can get by the error message. Thanks!!!

**Comment by ehduardu** [comment]
I was thinking of using it for observability metrics, but I can get by the error message. Thanks!!!
