### ISSUE TITLE
request.body is undefined when sending request as multipart/formdata

### ISSUE THREAD

**Issue by BenjaminLindberg** [fastify/help#937]
## 💬  Question here 

When using the plugin `"@fastify/multipart"` and sending a request as `"multipart/formdata"` with postman the request.body is undefined. I've tried sending the request in many diffrent ways for ex. Curl, fetch and so on.
And to access the body i need to iterate trough the parts and in that way access the body. But doing so is pretty tedious and i've also found it unreliable since it crashes the application & also gets stuck in the async iterable loop.
**So here comes my question**: Why is request.body undefined? Is it meant to be undefined or just some bug?

If possible add a link to sample codes for error reproduction (github or replit)

 [codesandbox.io](https://codesandbox.io/p/sandbox/adoring-silence-zgddcl)

## Your Environment

- *node version*: v18.17.1
- *fastify version*: >=4.32.2
- *os*: Linux
- *@fastify/multipart: 7.5.0

**Comment by Uzlopak** [comment]
did you read the readme of @fastify/multipart?

**Comment by BenjaminLindberg** [comment]
> did you read the readme of @fastify/multipart?

Yes i have, but i think it makes no sense for a multipart parser to not parse the request body. For example in express.js with "body-parser" and "multer" it automatically does it for you.

**Comment by Eomm** [comment]
It is written in the docs:
https://github.com/fastify/fastify-multipart#parse-all-fields-and-assign-them-to-the-body

Read why you may need the control NOT to attach the request body to the body itself:

https://backend.cafe/fastify-multipart-upload

> For example in express.js with "body-parser" and "multer" it automatically does it for you.

Please, take a moment to read ["Why you should not say _«I will use X»_ to a Fastify maintainer"](https://gist.github.com/Eomm/4b72531ed9e2bdaefccf144ff9d7ce9a).

Thank you
