### ISSUE TITLE
in there a server generator for fastify started from swagger?

### ISSUE THREAD

**Issue by bozzelliandrea** [fastify/help#939]
## 💬  Question here 

Hi everyone, is there any kind of server generator (like nodejs generator or other languages) where starting from the swagger yaml file, it creates all the application skeleton with rest api and models?
(basically the opposite of @fastify/swagger)

I don't know if this already exists or could be an idea for a small project (where i can contribute)

**Comment by Uzlopak** [comment]
https://github.com/seriousme/fastify-openapi-glue
