### ISSUE TITLE
How to enable content security policy using fastify-helmet

### ISSUE THREAD

**Issue by nettemsarath** [fastify/help#94]
## 💬 Questions and Help

how to enable content security policy fro my Rest API using fastify-helmet and how it helps in security

**Comment by Eomm** [comment]
The docs could be improved, it would be great if you could arrange a PR ✌

Anyway, this archive what you need:

```
fastify.register(
  helmet,
  {
    contentSecurityPolicy: {
      directives: {
        defaultSrc: ["'self'", 'default.com'],
        ...etc...
      },
    }
  }
)
```

the options you can set are [here](https://www.npmjs.com/package/helmet-csp)
