### ISSUE TITLE
Using vi.useFakeTimers() timeouts test for POST request with payload

### ISSUE THREAD

**Issue by nikosson** [fastify/help#941]
#### What are you trying to achieve, or the steps to reproduce?
1. Create next `js` files with installed `fastify` and `vitest`.

**test/app.test.js**
```
import { afterAll, expect, test, vi } from 'vitest'
import app from '../src/app'

test('test', async () => {
  vi.useFakeTimers();
  const response = await app.inject({
    method: 'POST',
    url: '/users',
    body: {
      field: '123'
    }
  })
  expect(response.statusCode).toBe(200)
})

afterAll(async () => {
  await app.close()
})
```

**src/app.js**
```
import fastify from 'fastify'

const app = fastify()
app.post('/users', async () => {
  return {}
})

export default app
```

**src/index.js**
```
import app from './app'

async function start() {
  try {
    await app.listen({ port: 3000 })
  }
  catch (err) {
    app.log.error(err)
    process.exit(1)
  }
}

start()
```
2. Run `vitest` command in order to execute test.

#### What was the result you received?
Vitest timeout error

#### What did you expect?
Test should successfully pass.

#### Context

* *node version*: 20.8.0
* *fastify version*: >=4.5.3
* *os*: Mac
* *any other relevant information*: It works well without `vi.useFakeTimers()`, or without sending `body` in request.

**Comment by kibertoad** [comment]
I think both vitest and jest mock too much stuff by default with useFaketimers. I think it's nextTick that is breaking fastify. can you try explicitly timers mocking and only mock the methods you really need?

**Comment by nikosson** [comment]
> I think both vitest and jest mock too much stuff by default with useFaketimers. I think it's nextTick that is breaking fastify. can you try explicit timers mocking and only mock the methods you really need?

You are correct - it works good with `vi.setSystemTime()` method, for example.
Thanks for help!

**Comment by kibertoad** [comment]
FWIW, I think it will be improved in vitest 1.0.0, I think they've stopped mocking nextTick by default exactly because it's way too intrusive.
