### ISSUE TITLE
[Help] How to access the underlying instance of ajv

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [fastify/help#942]
## 💬  Question here 

How to access the underlying instance of ajv in a plugin or a route without having to call setValidatorCompiler()? 
For many reason this issue is similar to the one I opened here some years ago: https://github.com/fastify/help/issues/374, but somehow I keep fighting with this question. I want to access to the underlying fastify ajv instance (supposingly through the `fastify.validatorCompiler` decorator) but, upgrading fastify from `3.x` to `4.x`, that decorator is always null. I've tried by waiting the server to be ready but the field is always falsey. Is there any way to access ajv without setting a custom validator?

```js
// example codes if any
app.addHook('onReady', function (done) {
      // logs undefined, undefined
      console.log(this.validatorCompiler, app.validatorCompiler)
      done();
  })
````

## Your Environment

- *node version*: 20
- *fastify version*: >=4.0.0
- *os*: Mac

**Comment by Eomm** [comment]
It is null when you don't have any schema - it creates only if necessary

Thanks to these utilities: https://fastify.dev/docs/latest/Reference/Request/#validateinputdata-schema--httpstatus-httpstatus I wonder if you really need access it

**Comment by giovanni-bertoncelli** [comment]
@Eomm I've added a pull request for better documenting `validatorCompiler` usage. Let me know if it can be useful.
