### ISSUE TITLE
JSONSchema: unknown keyword "example"

### ISSUE THREAD

**Issue by its-dibo** [fastify/help#948]
I created a schema that contains an example for swagger
```
 let schema = {
  body: {
    type: 'object',
    properties: {
      email: {
        type: 'string',
        example:  'admin@gmail.com',
      },
      password: { type: 'string' },
      additionalProperties:  false,
    },
    required: ['e'mail, 'password'],
  }
}
}
```
but, I get the following error
```
due to error strict mode: unknown keyword: \"example\""
```

**Comment by Uzlopak** [comment]
This serrr comes afaik from ajv. ajv does not know the keyword example and in strict mode rejects the schema. So you could either disable strict mode by setting it accordingliy in ajv.customOptions or add the keyword example in ajv.customOptions.

https://fastify.dev/docs/v4.10.x/Reference/Server#ajv
https://ajv.js.org/options.html#strict-mode-options
https://ajv.js.org/options.html#keywords

**Comment by its-dibo** [comment]
> This error comes afaik from ajv. ajv does not know the keyword `example` and in strict mode ajv rejects the schema. So you could either disable strict mode by setting it accordingliy in `ajv.customOptions` or add the keyword example in `ajv.customOptions`. Would prefer the second.
> 
> https://fastify.dev/docs/v4.10.x/Reference/Server#ajv https://ajv.js.org/options.html#strict-mode-options https://ajv.js.org/options.html#keywords

this worked for me.

as a reference for anyone comes here later, this is the configuration to add schema props that ajv doesn't recognize
```
 let app = Fastify({
    logger: true,
    ajv: {
      customOptions: {
        keywords: ['example'],
      },
    },
  })
```
