### ISSUE TITLE
How to require one or another object property with `fluent-json-schema` ?

### ISSUE THREAD

**Issue by DamienGarrido** [fastify/help#949]
## How to require one or another object property with `fluent-json-schema`?

I'm trying to generate the following JSON schema using `fluent-json-schema`:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "anyOf": [{ "required": ["id"] }, { "required": ["account"] }],
  "properties": {
    "name": { "type": "string" },
    "id": { "type": "integer" },
    "account": { "type": "string" }
  },
  "required": ["name"]
}
```

I need the `name` property to be mandatory, and either the `id` or the `account` property to be present.

I've been able to generate the schema only by using the `raw()` method (see below).

```javascript
const { S } = require('fluent-json-schema');

const jsonSchema = S.object()
  .raw({ anyOf: [{ required: ['id'] }, { required: ['account'] }] })
  .prop('name', S.string().required())
  .prop('id', S.integer())
  .prop('account', S.string());
```

See test code on [fluent-json-schema-validate-one-of-two-properties Replit](https://replit.com/@DamienGarrido/fluent-json-schema-validate-one-of-two-properties).

**How can I generate this JSON schema without using the `raw()` method?**

## Your Environment

- *node version*: 18
- *fluent-json-schema version*: 4.2.0-beta.0
- *os*: Linux

**Comment by bortolottidev** [comment]
Hey! I achieved a possible solution with this schema:

```
const jsonSchema = S.object()
  .prop('name', S.string().required())
  .ifThenElse(
    S.object().prop('id', S.not(S.integer())),
    S.object().prop('account', S.string().required()),
    S.object().ifThen(
      S.object().prop('account', S.not(S.string())),
      S.object().prop('id', S.integer().required())
    )
  )
```

It handles one or both account & id with a valid value without using raw

**Comment by nkwib** [comment]
I've been using the following example, and it should be what you are looking for:

```js
  const jsonSchema = S.object()
    .anyOf([
      S.object().prop("id", S.integer().required()),
      S.object().prop("account", S.string().required()),
    ])
    .prop("name", S.string().required());
```

**Comment by simoneb** [comment]
I think this issue can be closed.
