### ISSUE TITLE
How is it possible to add OPEN API 3.0.0 features (Callbacks, Examples) in Fastify Route schema?

### ISSUE THREAD

**Issue by gblok** [fastify/help#95]
####  
How is it possible to add OPEN API 3.0.0 features (Callbacks, Examples) in Fastify Route schema?
or extend Route schema?

#### Context
fastify version: >=2

**Comment by mcollina** [comment]
It should be. Are you getting any error?

**Comment by gblok** [comment]
how is it, possible?
where can see example,  extend router schema?

**Comment by mcollina** [comment]
I don’t know. There is nothing in fastify that prevents this.

https://github.com/fastify/fastify-swagger supports swagger, you might want to check that out.
