### ISSUE TITLE
Can I use custom http status codes?

### ISSUE THREAD

**Issue by h2nry** [fastify/help#950]
## 💬  Question here 

**Can I use custom http status codes ?**

```js
// Case 1)
fastify.get('/custom-status-code', async (req, res) {
  return res.code(101)   // <--- Not 200 ~ 299 status code.
    .send({ ping: 'pong' })
})
```

```js
// Case 2)
fastify.setErrorHandler((err, req, res) => {
  /* blah blah blah ~ */

  res.send(err);
});

fastify.get('/always-error', async (req, res) {
  const error =  new Error("error with custom error code");
  error.statusCode = 101  

  throw error
})
```

I would like to respond with a custom status codes like 101, 102, etc. (as above)
> I know it is not good idea. but I have to do it 😭
> Some third party told me to do it... :(

---

##### Detailed Question.

**1) How to use customized http status codes ?**

*Case 1* always freezes. This may be due to using an invalid(or undefined in fastify) http status code.
I would like to use status codes like 101, 102, etc.
Therefore, a different status code must be enabled.

**2) How to customize Error Handling Policy ?**

I want to use status codes less than 400.
 
*Case 2* always responds with a 500 error because of its error handling policy.
```
# https://fastify.dev/docs/latest/Reference/Reply#errors

Note: If you are passing an error to send and the statusCode is less than 400, Fastify will automatically set it at 500.
```
So, I need to use status codes less than 400.

---

Please Help me 🤣

## Your Environment

- *node version*: 18
- *fastify version*: >=4.21.0
- *os*: Mac, Linux

**Comment by climba03003** [comment]
`101` status is telling the browser to upgrade to websocket.
So it is not possible to use it unless you are in customize client.

**Comment by h2nry** [comment]
> `101` status is telling the browser to upgrade to WebSocket. So it is not possible to use it unless you are in customize client.

I know.. I believe this is a rule that violates the [RFC-9110](https://httpwg.org/specs/rfc9110.html#overview.of.status.codes)  protocol.
This is very fu***** idea, but I have to do it because someone else wants it. 😭
So, I need to help...
Is there no other way?

**Comment by climba03003** [comment]
> Is there no other way?

If you are using browser to connect, then you have no way to bypass it.
It is related to the client instead of server.

**Comment by h2nry** [comment]
> > Is there no other way?
> 
> If you are using browser to connect, then you have no way to bypass it. It is related to the client instead of server.

Server-to-server only. Not through a web browser.

**Comment by h2nry** [comment]
Oh.. Sorry

I checked it again in detail, status code is worked as intended.

When the response value from CURL was "HTTP/1.1 101 Switching Protocols", I did not know that it was waiting for the actual switching protocol.

```bash
curl -vv -X 'POST' \
  'http://localhost/custom-status-code' \
  -H 'accept: application/json'
*   Trying 127.0.0.1:80...
* Connected to localhost (127.0.0.1) port 80 (#0)
> Host: localhost
> User-Agent: curl/8.1.2
> accept: application/json
> Content-Type: application/json
> 
< HTTP/1.1 101 Switching Protocols
< content-type: application/json; charset=utf-8
```

Sorry for the confusion. 😭

Thank you for your kindness. @climba03003
