### ISSUE TITLE
Schema validation error, when try to validate GET endpoint with querystring containing complex objects

### ISSUE THREAD

**Issue by mateusroman** [fastify/help#956]
#### What are you trying to achieve, or the steps to reproduce?
Hello!

I'm trying to perform Schema validation for a GET endpoint. I've tried the options: JSON Schema and Fluent Json Schema.

Both of them fail at the same point, where Fastify seems to be unable to handle the received object via the request correctly.

Here's how the endpoint is declared:
```ts
export default function endpointX(fastify: FastifyInstance, opts: unknown, done: () => void) {
    fastify.get(
        '/endpointX',
        {
            schema: {
                querystring: querySchemaSample,
            },
        },
        async (req: FastifyRequest, reply: FastifyReply) => {
            console.log(req.query)
            await handler(req, reply)
            done()
        },
    )

    done()
}
```

Here's how the schema is declared:
```ts
const querySchemaSample = S.object()
    .id('/endpointX')
    .title('endpointX test')
    .description('any description')
    .prop('startDate', S.string().format(S.FORMATS.DATE_TIME).required())
    .prop('endDate', S.string().format(S.FORMATS.DATE_TIME).required())
    .prop(
         'testObject',
         S.object()
             .id('#testObject')
             .prop('type', S.string().minLength(1).required())
             .prop('number', S.number().minimum(1).required()),
     )
```

Here's the curl command:
```text
http://localhost:3000/endpointX?startDate=2023-03-03T10%3A59%3A14&endDate=2023-03-03T10%3A59%3A14&testObject=%7B%22type%22%3A%20%22asd%22%7D
```

#### What was the result you received?

Error displayed:
```json
{
	"statusCode": 400,
	"code": "FST_ERR_VALIDATION",
	"error": "Bad Request",
	"message": "querystring/testObject must be object"
}
```

#### Notes
I tried to provide this object in numerous ways, and none of the attempts satisfied the schema validation.

#### What did you expect?
Acceptation and a correctly validation of object.

#### Context

* *node version*: v18.18.0
* *fastify version*: >=4.22.0
* *os*: Windows (WSL - Ubuntu 22.04.2 LTS)

**Comment by Eomm** [comment]
you can't provide an object via query string.

you need to provide a custom query string parser to do it:

https://fastify.dev/docs/latest/Reference/Server/#querystringparser

**Comment by mateusroman** [comment]
@Eomm 

Yes, you were right, with the help of the parser, everything went well. I think this solution should be made available natively. The need to use complex objects in GET requests is not uncommon.

Taking advantage of the topic at hand, there is an incompatibility with FastifySwagger, as it doesn't properly reflect the model in 
interface. 

Please see the example below:

![swagger_with_queryparser](https://github.com/fastify/help/assets/19492996/81ec2814-1d0e-4b4d-8e0d-30768011e6f4)

Nevertheless, other objects such as arrays based on enumerations also have this deficiency, simply carrying the first default value as modeling.

See the example below:
```ts
const querySchemaSample = S.object()
    .id('/endpointX')
    .title('endpointX test')
    .description('any description')
    .prop('startDate', S.string().format(S.FORMATS.DATE_TIME).required())
    .prop('endDate', S.string().format(S.FORMATS.DATE_TIME).required())
    .prop(
         'objectX',
         S.object()
             .id('#objectX')
             .prop('type', S.string().minLength(1).required())
             .prop('number', S.number().minimum(1).required()),
     )
    .prop(
        'test',
        S.array().items(
            S.object()
                .prop(
                    'testbrands',
                    S.array()
                        .items(S.string().enum(Object.values(Brand)))
                        .required(),
                )
                .prop(
                    'testorigins',
                    S.array()
                        .items(S.string().enum(Object.values(Origin)))
                        .required(),
                ),
        ),
    )
```

![swagger_with_enum_array_using_queryparser](https://github.com/fastify/help/assets/19492996/a3b11060-7b98-40fe-89b3-800dd6fdc80b)


The fields displayed in Swagger should demonstrate the possible values that can be received, as this has been indicated in the Swagger schema.

Therefore, it seems to me that the documentation does not indicate such a compatibility deficit, and in most cases, it portrays the use of HTTP methods like POST, with few cases showing the actual use of complex modeling with GET methods.
