### ISSUE TITLE
how can I diagnose ajv validation error in custom error handler 

### ISSUE THREAD

**Issue by mohammad-khooie** [fastify/help#96]
Hi
I want to diagnose ajv validation error in my custom error handler
this is first way that I test
I add this if block in my custom error handler
`if(err instanceof Ajv.ValidationError){ do some things }`
but its dosent work for me
whats the best way?

node version: 10
fastify version: 2.6.0
os: Windows

**Comment by Eomm** [comment]
Duplicate
https://github.com/fastify/fastify/issues/1773
