### ISSUE TITLE
Epub file is implicitly compressed

### ISSUE THREAD

**Issue by mrerberg** [fastify/help#960]
Hi!

I'm developing app that can receive and save files in epub format. I got an issue. If I use fastify/multipart lib to accept files in epub format, file that I received is compressed and it is not able to open it via special apps (Books for macos users).

|  Before upload  | After upload  |
|---|---|
| <img width="737" alt="Screenshot 2023-11-08 at 14 19 01" src="https://github.com/fastify/help/assets/103729911/abaf093d-4acc-4f2b-9d57-28777945fd0c">  | <img width="731" alt="Screenshot 2023-11-08 at 14 19 22" src="https://github.com/fastify/help/assets/103729911/5435a40c-0ec9-432a-a45b-cea0490bb865">  |

[Repository with sandbox to reproduce the issue](https://github.com/mrerberg/epub-test).

#### Expected behaviour

Saved file is not compressed and could be opened.

#### Context

* *node version*: 20.5.0
* *fastify version*: 4.11.0
* *os*: Mac
* *fastify/multipart*: 7.3.0

Thanks in advance for any help!

**Comment by Eomm** [comment]
How did you solve the error?
