### ISSUE TITLE
how can i add a custom hook to my plugin that will have types

### ISSUE THREAD

**Issue by RjManhas** [fastify/help#962]
Hello im making a json plugin, that basically allows you to add json files and then call functions in the routes and other stuff like that. What my issue is that I want to create a custom hook called "onRead" "onWrite" but how do I add them to the hook system.

**Comment by RjManhas** [comment]
Hello?

**Comment by simoneb** [comment]
The hooks system in fastify is not extensible, so you cannot create new hooks. Nevertheless, if your objective is to have user-space code invoked when something happens within the plugin, you can simply accept those callback functions as options in the plugin configuration at registration time and, in the plugin's code, invoke them when certain events happen. 

You can see such an example in this plugin, which accepts callback functions as options: https://github.com/fastify/fastify-circuit-breaker?tab=readme-ov-file#options
