### ISSUE TITLE
Help rendering 404 views using @fastify/view

### ISSUE THREAD

**Issue by benrobson** [fastify/help#967]
## 💬  Question here 
Using @fastify/view I am trying to render a view with the notFound handler but I can't get this to work.
I have set this but it looks to seem as it's not respecting it. I have tested by going to a route that isn't defined which ideally I would want to be rendering a point-of-view view.

```js
app.setNotFoundHandler(async function (req, res) {
    return res.view("session/notFound", {
      pageTitle: `404 Not Found`,
      config: config,
      error: error,
      req: req,
      features: features,
      globalImage: await getGlobalImage(),
      announcementWeb: await getWebAnnouncement(),
    });
  });
````

## Your Environment

- *node version*: 18.18.2
- *fastify version*: ^4.23.2
- *point-of-view version*: ^8.2.0
- *os*:  Windows

**Comment by i-suman** [comment]
@benrobson, try to write the **setNotFoundHandler** with the instance inside the fastify register. Below is code sample that may solve your problem -

`fastify.register(async function (instance, options, done) {
  instance.setNotFoundHandler(async function (request, reply) {
    const result = await axios.get('https://dummyjson.com/products');
    return reply.view("./templates/index.ejs", { data: result.data });
  })
  done();
})`

_In the above example, I have used EJS engine. And to demo async/await, I have used a dummy API call to a public product API_

Also please check if you have properly registered the engine or not. Below is an example of EJS template engine registration -

`import ejs from 'ejs'
fastify.register(import("@fastify/view"), {
  engine: {
    ejs: ejs
  },
})`

**Comment by i-suman** [comment]
@benrobson, The modification you need to do -

```
app.register(async function (instance, options, done) {
    instance.setNotFoundHandler(async function (request, reply) {
      return res.view("session/notFound", {
        pageTitle: `404 Not Found`,
        config: config,
        error: error,
        req: req,
        features: features,
        globalImage: await getGlobalImage(),
        announcementWeb: await getWebAnnouncement(),
      });
    })
    done();
  })
```

**Comment by benrobson** [comment]
> @benrobson, ideally your code should work as expected. Please make sure the template engine is properly registered -
> 
> ```js
> import ejs from 'ejs'
> fastify.register(import("@fastify/view"), {
>   engine: {
>     ejs: ejs
>   },
> })
> ```
> 
> Try to write the **setNotFoundHandler** with the instance inside the fastify register. Below is code sample that may solve your problem -
> 
> ```js
> fastify.register(async function (instance, options) {
>   instance.setNotFoundHandler(async function (request, reply) {
>     const result = await axios.get('https://dummyjson.com/products');
>     return reply.view("./templates/index.ejs", { data: result.data });
>   })
> })
> ```
> 
> _In the above example, I have used EJS engine. And to demo async/await, I have used a dummy API call to a public product API_
> 
> The modification you may try -
> 
> ```js
> app.register(async function (instance, options) {
>     instance.setNotFoundHandler(async function (request, reply) {
>       return res.view("session/notFound", {
>         pageTitle: `404 Not Found`,
>         config: config,
>         error: error,
>         req: req,
>         features: features,
>         globalImage: await getGlobalImage(),
>         announcementWeb: await getWebAnnouncement(),
>       });
>     })
>   })
> ```
> 
> **NOTE:**
> 
> 1. [point-of-view@6.3.0 has been deprecated. Please use @fastify/view@7.0.0 instead](https://www.npmjs.com/package/point-of-view)
> 2. Make sure you have installed @fastify/view (not point-of-view)
> 3. Provide more insight on the template engine being used, or check if the template is broken or not

1. I have amended the app.js to directly import the ejs in engine, the only difference is I have a views param as well.
2. Attempting to set the example you provided doesn't work and errors in the console with the following:

> {"level":40,"time":1701422834781,"pid":20348,"hostname":"DESKTOP-1G7LML2","reqId":"req-3","err":{"type":"FastifyError","message":"Reply was already sent, did you forget to \"return reply\" in \"/favicon.ico\" (GET)?","stack":"FastifyError: Reply was already sent, did you forget to \"return reply\" in \"/favicon.ico\" (GET)?\n    at _Reply.Reply.send (C:\\Users\\Ben\\Documents\\GitHub\\MSAU-zander-web\\node_modules\\fastify\\lib\\reply.js:132:26)\n    at readCallbackEnd (C:\\Users\\Ben\\Documents\\GitHub\\MSAU-zander-web\\node_modules\\@fastify\\view\\index.js:297:10)\n    at _readCallback (C:\\Users\\Ben\\Documents\\GitHub\\MSAU-zander-web\\node_modules\\@fastify\\view\\index.js:333:7)\n    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)","code":"FST_ERR_REP_ALREADY_SENT","name":"FastifyError","statusCode":500},"msg":"Reply was already sent, did you forget to \"return reply\" in \"/favicon.ico\" (GET)?"}  

I have added my app.js as well here: https://srcshare.io/6569a7a2516e1ba79b67b16c

**Comment by benrobson** [comment]
Additional version information:
"@fastify/static": "^6.11.2"
"@fastify/view": "^8.2.0"
"ejs": "^3.1.7"
"fastify": "^4.23.2"

**Comment by i-suman** [comment]
@benrobson , Please find the code sandbox below running on the exact versions you are using and the way you have registered the plugin. This might be of your help -

[Code Sandbox for setNotFoundHandler with @fastify/view](https://codesandbox.io/p/devbox/fastify-view-set-not-found-handler-6vmmgp)
