### ISSUE TITLE
Get the httpHandler for google cloud functions

### ISSUE THREAD

**Issue by Uzlopak** [fastify/help#969]
How can i retrieve the httpHandler of fastify?

Background:
When i want to use google cloud functions i need to provide a httpHandler and not the fastify server instance.

**Comment by metcoder95** [comment]
There's an issue from some time ago along the lines: https://github.com/fastify/fastify/issues/946#issuecomment-766319521

I've been tempted to write a plugin that abstracts all of these so far, but haven't dig deeper into it

**Comment by floridemai** [comment]
There is documentation on how to deal with this, just check the [Serverless](https://fastify.dev/docs/latest/Guides/Serverless/) section in the docs. It covers also integrating with Google Cloud Functions or Google Firebase Functions.

**Comment by simoneb** [comment]
I think this can be closed.
