### ISSUE TITLE
Cannot find module 'node:url'

### ISSUE THREAD

**Issue by beastmst** [fastify/help#976]
when I try yarn start:dev my code, it give me this problem

/xxxx/node_modules/fast-uri/index.js:1
Error: Cannot find module 'node:url'
Require stack:
- /xxxx/node_modules/fast-uri/index.js
- /xxxx/node_modules/fast-json-stringify/lib/validator.js
- /xxxx/node_modules/fast-json-stringify/index.js
- /xxxx/node_modules/koa2-winston/stringify_schema.js
- /xxxx/node_modules/koa2-winston/index.js
- /xxxx/main.js
- /xxxx/index.js
    at Object.<anonymous> (/xxxx/node_modules/fast-uri/index.js:3:13)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10) {
  code: 'MODULE_NOT_FOUND',

I tried change the line (in fast-uri/index.js) 
 const URL = require('node:url')
to 
  const URL = require('url')
then can run... so, what should be the issue?

node: v14.21.3.
I try run this in my mac and linux, still same result

**Comment by climba03003** [comment]
`node` prefix is added in `node@14.18.0`, please check your runtime if it is greater than it.
I see you mention about `node@14.21.3`, but sometimes it is actually not using the one you believe.

**Comment by beastmst** [comment]
yes, when i type node in command
it showed
Welcome to Node.js v14.21.3.
Type ".help" for more information.

**Comment by climba03003** [comment]
> yes, when i type node in command

You should show inside the script you run. Not from the `repl` from `node`.

**Comment by beastmst** [comment]
yes, I checked it with console.log(process.version);
it printed 

v14.21.3
/xxxx/node_modules/fast-uri/index.js:1
Error: Cannot find module 'node:url'

**Comment by Uzlopak** [comment]
No problem in my node 14.21.3:

![image](https://github.com/fastify/help/assets/5059100/3134c37a-2718-4dfc-a978-fea185c6e398)

**Comment by beastmst** [comment]
yes, I can require in that way too, but funny is when run in yarn start:dev 
it said module cannot be found

**Comment by kibertoad** [comment]
Then it means that yarn is running from a different, older, node version.

**Comment by beastmst** [comment]
but I put a console.log at the file before the require(node:ulr) line, it showed the same version ... v14.21.3 (i even use nvm changed to v18)... same problem

**Comment by Uzlopak** [comment]
Closing due to inactivit and because it is not reproducable.
