### ISSUE TITLE
I am getting double reply send issues with the following setup

### ISSUE THREAD

**Issue by tbhaxor** [fastify/help#979]
#### What are you trying to achieve, or the steps to reproduce?

I want to programatically redirect to the google consent page for the first time on `/google` route and on the `/google/callback` I want to 

Now the query parameters need to be validated before redirection, therefore **preValidation** can't be used and I want to use it in preHandler.

Afaik, it is problem in the google-passport.mjs hook

```
import fastifyPassport from "@fastify/passport";
import { GOOGLE_SCOPES } from "../utilities/constants.mjs";

/**
 *
 * @param {import("fastify").FastifyRequest} request
 * @param {import("fastify").FastifyReply} reply
 */
export default async function (request, reply) {
  fastifyPassport.authenticate("google", {
    session: false,
    accessType: "offline",
    consent: "prompt",
    scope: GOOGLE_SCOPES.getWith(request.query.for, "profile"),
    state: Buffer.from(JSON.stringify(request.query)).toString("base64"),
  })(request, reply);
}
```

And its two times usage in both `/google` and `/google/callback`

```
preHandler: [googlePassport],
```

> [!NOTE]
> I have removed the firebase and gcp related dependency for you. You can install it and run the server.

#### What was the result you received?

Error message

```
Reply was already sent
```

#### What did you expect?

There is no such error in the response redirect or message. It is just this error bugging me. It should not give this error. Rest everything is fine.

#### Context

* *node version*: v18
* *fastify version*: v4.25.2
* *fastify passport version*: v2.4.0
* *os*: Linux
* *any other relevant information*:  Check the repository https://github.com/tbhaxor/fastify-passport-error

**Comment by kibertoad** [comment]
Not sure if this is directly related to the error that you are seeing, but:
1) This method doesn't need to be async, you are not awaiting anything;
2) You are not returning promise that you get from `fastifyPassport.authenticate`

So my assumption is that you return an empty promise from your method which resolves immediately with `undefined`, and then the authenticate function fires up at some point in the future, but it's too late

**Comment by tbhaxor** [comment]
Thanks for your response. Yeah I kept it async because there are some firebase operations I need to carry out before calling the authenticate function. I have removed that code for you to run it locally without bothering firebase setup.

**Comment by kibertoad** [comment]
try returning the promise you get from authenticate

**Comment by tbhaxor** [comment]
There is some progress now. It is returning Unauthorized on /google/callback. Btw its not the solution. I am getting different error

**Comment by tbhaxor** [comment]
Update: It is working with session set to true. 

Is there any way I can make it work with session set to false?

**Comment by tbhaxor** [comment]
Nevermind, issue is resolved. I am using `session: true`
