### ISSUE TITLE
It is possible to use different routes for different domains?

### ISSUE THREAD

**Issue by egorovd** [fastify/help#98]
Hello.
I’m "studying" the fastify and want to understand whether it is possible to use different routes for different domains.
Thank.

**Comment by Eomm** [comment]
Could you elaborate?
I don't understand the question

For sure you can have a fastify server at 1.1.1.1 (for example)
and then configure your DNS:
www.my-site-one.com -> 1.1.1.1
www.my-site-two.com -> 1.1.1.1

**Comment by egorovd** [comment]
Yes.
```javascript
// www.my-site-one.com 
fastify.route({
  host: 'www.my-site-one.com'
  method: 'GET',
  url: '/a',
  handler: function (request, reply) {
    reply.send({ hello: 'world from A' })
  }
})
// www.my-site-two.com
fastify.route({
  host: 'www.my-site-two.com'
  method: 'GET',
  url: '/b',
  handler: function (request, reply) {
    reply.send({ hello: 'world from B' })
  }
})

```

**Comment by egorovd** [comment]
Or  (with arrays) :
```javascrip
// www.my-site-one.com 
fastify.route({
  host: ['my-site-one.com', 'www.my-site-one.com'],
  method: 'GET',
  url: '/a',
  handler: function (request, reply) {
    reply.send({ hello: 'world from A' })
  }
})
// www.my-site-two.com
fastify.route({
  host: ['my-site-two.com', 'www.my-site-two.com'],
  method: 'GET',
  url: '/b',
  handler: function (request, reply) {
    reply.send({ hello: 'world from B' })
  }
})
```

**Comment by Eomm** [comment]
What do you want to archive?
The http server doesn't know the domain where it is exposed.

For sure you can create two endpoint `/a` and `/b` and, writing code that checks the [`origin`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin) header and gives access to `/a` only if the origin is `my-site-one.com` etc..

**Comment by egorovd** [comment]
It is necessary to solve such a problem.
There is a top level domain: example.сom (1.1.1.1)
Later, lower-level domains are created:
111.example.com (1.1.1.1)
222.example.com (1.1.1.1)
333.example.com (1.1.1.1)
And each domain can have its own set of independent routes.
111.example.com/a/...

222.example.com/b/...

333.example.com/a/...
333.example.com/...

**Comment by evanshortiss** [comment]
@egorovd sounds like you need a reverse proxy? Usually people use NGINX or Apache reverse proxy to achieve what you are asking. 

Or, are you suggesting that you'd use single fastify server, inspect the hostname header ([x-forwarded-host](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host)) and decide which handler to use?

That would be a feature request I think.

**Comment by egorovd** [comment]
Yes, I understand when and why Apache and Nginx are needed, but I need something else.

> Or, are you suggesting that, even with a reverse proxy, you'd use single fastify server, inspect the hostname header (x-forwarded-host) and decide which handler to use?

Yes, I need this kind of behavior.
To get this:
```javascript
// www.my-site-one.com 
fastify.route({
  host: ['my-site-one.com', 'www.my-site-one.com'],
  method: 'GET',
  url: '/a',
  handler: handlerA
})
// www.my-site-two.com
fastify.route({
  host: ['my-site-two.com', 'www.my-site-two.com'],
  method: 'GET',
  url: '/b',
  handler: handlerB
  }
})
// www.my-site-three.com
fastify.route({
  host: ['my-site-three.com', 'www.my-site-three.com'],
  method: 'GET',
  url: '/a',
  handler: handlerC
  }
})

```

**Comment by nwoltman** [comment]
This could be achieved with an `onRequest` hook and the route [`config`](https://www.fastify.io/docs/latest/Routes/#config) option. Here's an example that should work:

```js
fastify.addHook('onRequest', (req, reply, next) => {
  const allowedHosts = reply.context.config.hosts
  if (allowedHosts === undefined || allowedHosts.includes(req.hostname)) {
    next()
  } else {
    reply.callNotFound()
  }
})

// www.my-site-one.com 
fastify.route({
  config: {
    host: ['my-site-one.com', 'www.my-site-one.com'],
  },
  method: 'GET',
  url: '/a',
  handler: handlerA
})
// www.my-site-two.com
fastify.route({
  config: {
    host: ['my-site-two.com', 'www.my-site-two.com'],
  },
  method: 'GET',
  url: '/b',
  handler: handlerB
  }
})
```

**Comment by egorovd** [comment]
Yes, that will work, but not in my case.
I will have thousands of hosts and changing _routes_ on runtime.

**Comment by nwoltman** [comment]
Why exactly will that not work in your case?

> changing *routes* on runtime

What does that mean?

**Comment by egorovd** [comment]
I need for each domain(for thousands) to have its own set of routes and the ability to change (or delete or add) routes without restart the nodejs.
if it is presented as a table:
![Image](https://user-images.githubusercontent.com/6965699/62784632-9c985d00-bac7-11e9-942e-ab0c4f789fea.png)

**Comment by jsumners** [comment]
Fastify probably isn't the framework for you. Fastify is built around a radix tree of the routes being compiled at startup so that route lookups are extremely quick. As a result, once Fastify is started the routing table is immutable.

**Comment by egorovd** [comment]
Yes, understand.
And I want to try to patch for my task.
If it succeeds, I will write a pull request.

**Comment by egorovd** [comment]
Hello.
I abandoned the idea of using multiple domains on the same instance of nodejs.
But another question arose...
How realistic and possible is it to make dynamic changes to routes and handlers?
Thank you.

**Comment by StarpTech** [comment]
@egorovd using a [custom](https://github.com/fastify/fastify/blob/0d2fdd701f9601bf0def9a018e06a371e821e8cc/docs/Server.md#versioning) version resolver could allow a use case where the route is enabled conditionally based on a header value:

```js
fastify.route({
  method: 'GET',
  url: '/',
  version: '1-tenantA',
  handler: function (request, reply) {
    reply.send({ hello: 'world' })
  }
})

fastify.route({
  method: 'GET',
  url: '/',
  version: '1-tenantB',
  handler: function (request, reply) {
    reply.send({ hello: 'world' })
  }
})
```

but in real-world those tasks are outsourced to a proxy (nginx, apache) in order to reduce the complexity on application side. In most cases you would just have different params or query if you work with different tenants.

```
GET - tenantA.mapi.com -> {PROXY rewrite} --> http://localhost:3000/transactions?tenant=A -> (fastify) GET - /transactions
```
or use a proxy like https://traefik.io/ where you can enable dynamic routing very easily. At the end I discourage to move that logic to a http framework.

**Comment by egorovd** [comment]
I am surprised. )))
How it turns out is hard to understand ...
But it was after the question I asked that such thoughts came to me.
Thank.

**Comment by StarpTech** [comment]
@egorovd I will close this issue. Feel free to open a new one and try to describe it based on a use-case.

**Comment by jsumners** [comment]
See https://github.com/fastify/fastify/blob/master/docs/Recommendations.md#use-a-reverse-proxy
