### ISSUE TITLE
Help - How to use fastify-cli and fastify-type-provider-typebox

### ISSUE THREAD

**Issue by tjapa** [fastify/help#981]
How to use fastify-cli and fastify-type-provider-typebox?

The setup of fastify-type-provider-typebox is described here:

[How to use fastify-cli and fastify-type-provider-typebox](https://github.com/fastify/fastify-type-provider-typebox?tab=readme-ov-file#usage)

Basically I need to do: 

```ts
import Fastify from 'fastify'
import { Type, TypeBoxTypeProvider } from '@fastify/type-provider-typebox'

const fastify = Fastify().withTypeProvider<TypeBoxTypeProvider>()
```

and it's writed that I can't do: 

```ts
import Fastify from 'fastify'
import { Type, TypeBoxTypeProvider } from '@fastify/type-provider-typebox'

const fastify = Fastify()

fastify.withTypeProvider<TypeBoxTypeProvider>()
```

**Comment by mcollina** [comment]
In that same readme:

https://github.com/fastify/fastify-type-provider-typebox?tab=readme-ov-file#plugin-definition
