### ISSUE TITLE
Help | `req.query.url` throws error `Property 'url' does not exist on type '{}'`

### ISSUE THREAD

**Issue by jainChetan81** [fastify/help#982]
## 💬  Using `req.query.url` is throwing an error so is `req.params["anything"]` as I understand I need to pass the type of params in the `req` using generics, but I can't find the document for that, would love any help

```js
const cityFromParams = req.params.filterstate
````

If possible add a link to sample codes for error reproduction (github or replit)

## Your Environment

- *node version*: 16
- *fastify version*: >=4.25.2
- *os*: Mac, Windows, Linux
- *any other relevant information*
<img width="983" alt="Screenshot 2024-01-18 at 4 04 21 PM" src="https://github.com/fastify/help/assets/38555207/40000a68-407e-4c5e-8a3a-fb58565fde98">

**Comment by RjManhas** [comment]
req.url

**Comment by RjManhas** [comment]
you using js or ts

**Comment by jainChetan81** [comment]
ts

**Comment by mcollina** [comment]
Use https://github.com/fastify/fastify-type-provider-typebox
