### ISSUE TITLE
fastify.inject() in the body or payload cannot send a function in the properties.

### ISSUE THREAD

**Issue by corteshvictor** [fastify/help#984]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.20.0

### Node.js version

20

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.2.1

### Description

I am unit testing my routes using `fastify.inject()`, the route receives a form-data with text fields and a file.

The '@fastify/multipart' plugin, enabling attachFieldsToBody to true, injects those fields into the body.

In my route I have a schema that validates some information from the body, but inject cannot send a mock function, it says that the property is required and I cannot invoke the route.

### Steps to Reproduce

I have a route similar to this, where I am validating the schema with the plugin `"@fastify/type-provider-typebox":"^3.3.0"`.

```js
fastify.route({
    url: '/create',
    method: 'POST',
    schema: {
    body: Type.Object({
       file: Type.Object({
         filename: Type.String(),
         mimetype: Type.String(),
         toBuffer: Type.Any(),
       })
    })
    },
    handler: async (req, reply) {}
  });
```

As you can see in the path, I am getting a file with other fields, to do this, I am using the plugin `"@fastify/multipart":"^8.1.0"`.
By using this plugin as follows 
```js
fastify.register(multipart, { attachFieldsToBody: true });
```
I am injecting all the form-data into the body so I can validate it in the schema, that file injects a toBuffer() function which I validate it type `any` in my schema.

When I want to use fastify.inject as follows, the body validates the text fields fine but the toBuffer function, even though it is type `any` in the schema says it is required because inject does not allow to send that mock function, but if I send a text `toBuffer: 'text'` if the path is executed.

```js
const response = await app.inject({
      method: 'POST',
      url: '/create',
      body: {
        file: {
          filename: 'test.pdf',
          mimetype: 'application/pdf',
          toBuffer: functionMock()
        },
      },
});
```

### Expected Behavior

The behavior I expect, is that `fastify.inject()` can allow to send a mock function in the properties and this replaces the one injected in the body when using the @fastify/multipart plugin.

**Comment by mcollina** [comment]
I’ve transferred this to help, because it’s mostly a question on how to do something

**Comment by victorhcortesp** [comment]
Thank you very much @climba03003, I will perform the tests tomorrow.

@mcollina I had tried with `new formData()` but it also failed me, the schema did not realize it and returned the error `body must be object`. But I did not think to try with `new Readable()`. 

I do the tests and I will tell you how it went, but thanks for the help.

**Comment by corteshvictor** [comment]
Thank you very much @climba03003, I will perform the tests tomorrow.

@mcollina I had tried with `new formData()` but it also failed me, the schema did not realize it and returned the error `body must be object`. But I did not think to try with `new Readable()`. 

I do the tests and I will tell you how it went, but thanks for the help.

**Comment by corteshvictor** [comment]
@mcollina @climba03003 thank you very much for the help, with the `new Readable()` it works without problem.

The `new fromData()` [native](https://developer.mozilla.org/en-US/docs/Web/API/FormData) using Node v20, if placed problems but using the `form-data` [library](https://www.npmjs.com/package/form-data) seems to work passing the headers with the `getHeaders()` function but this library has several years without being updated and may have security issue.

I decided to stick with `new Readable()` which worked very well.

Thanks again to both of you for your help.
