### ISSUE TITLE
Fastify Postgress external handler

### ISSUE THREAD

**Issue by cherimo** [fastify/help#985]
There have been several posts about this this problem and various solutions have been offered. Unfortunately I was unable to get this to work.

I have linked different routes to different handlers on my main(server.js) file.
I want to access my Postgres database from the handler, but this doesn't seem to go as smoothly as I had hoped.
The following error gets returned:

    {"statusCode":500,"error":"Internal Server Error","message":"Cannot read properties of undefined (reading 'pg')"}

This is the code:
server.js

    "use strict";
    // ESM
    import Fastify from 'fastify'
    import { Test } from './api/page/index.js'
    
    const fastify = Fastify({
     logger: true
    })
    
    fastify.register(import('@fastify/postgres'), {
      connectionString: 'postgresql://***',
      native: true
    })
    
    fastify.get('/', Test) //this doesnt work
    
    fastify.get('/user/:id', ( req, reply) => {  //this works
      fastify.pg.query(
        'SELECT * FROM logs_login WHERE log_type=$1', [1],
        function onResult (err, result) {
          reply.send(err || result)
        }
      )
    
    
    })
    
    fastify.listen({host: "0.0.0.0", port: 3333 })

index.js

    "use strict";
    
    import Test from './Test.js'
    
    export { 
        Test
     };

Test.js

    "use strict";
    
    export default (request, reply) => {
      console.log(request.pg) //request.pg does exist but returns null
      console.log(this.pg) //undefined
    
      this.pg.query( //this doesnt work nor request.pg.query
        'SELECT * FROM logs_login WHERE log_type=$1', [1],
        function onResult (err, result) {
          reply.send(err || result)
        }
      )
    
    }

What part do I miss? Should I pass fastify intance as parameter to the handler?

**Comment by mcollina** [comment]
This should fix it:

```

export default function (request, reply) {
  console.log(request.pg) //request.pg does exist but returns null
  console.log(this.pg) //undefined

  this.pg.query( //this doesnt work nor request.pg.query
    'SELECT * FROM logs_login WHERE log_type=$1', [1],
    function onResult (err, result) {
      reply.send(err || result)
    }
  )

}

```
