### ISSUE TITLE
Fastify vite (or esbuild) to run standalone server

### ISSUE THREAD

**Issue by kharann** [fastify/help#986]
## 💬  Question here 

Is there anything wrong with using vite as a standalone server rather than as a part of an SSR system? Vite has a lot of features such as HMR, fast bundling and a rich plugin system while leveraging the power of esbuild.

I couldn't find anything about it in the docs so I was curious of its use case. If not perhaps an esbuild/vite example would be cool. 

Edit:

I think that esbuild with esm is becoming more and more common especially with tools such as AWS cdk using it to deploy lambdas. 

For context I'm primarily using esbuild to build my fastify application and was simply curious about the vite plugin

Thanks for all the great work!

**Comment by mcollina** [comment]
cc @galvez

**Comment by galvez** [comment]
See [this section](https://fastify-vite.dev/guide/getting-started#a-quick-walkthrough) of the [`@fastify/vite`](https://fastify-vite.dev) documentation. It does exactly that, integrate Vite just for building your static SPA bundle.
