### ISSUE TITLE
Help: can't access fastify routes on vercel

### ISSUE THREAD

**Issue by imxade** [fastify/help#987]
## 💬  Question here 
locally it works fine with app.listen().
The route `/train` is supposed to execute scripts with node

But instead it throws `415` when hosted on vercel

problematic route: https://github.com/imxade/classifySketch/blob/f7592386c4b08d4e2daa88cf4ddb7ff99e391080/api/index.js#L40

## Your Environment
vercel: https://github.com/imxade/classifySketch/blob/master/vercel.json

## Runtime Log
https://vercel.com/imxades-projects/classifysketch/logs?responseStatusCodes=415
There aren't any details.

**Comment by metcoder95** [comment]
👋 
Can you provide an 
[Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

If this cannot be done outside of vercel, most likely its something on vercel that needs to be checked out

**Comment by imxade** [comment]
@metcoder95 
thanks for the response :)
fixed it by adding content type to fetch.
