### ISSUE TITLE
fastify + fastify-graceful-shutdown + fastify-socket.io not closing websocket connections

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [fastify/help#988]
## 💬  Question here 

I'm using `fastify` with `fastify-socket.io` in order to create a fastify server together with a `socket.io` server. I'm using also `fastify-graceful-shutdown` in order to gracefully shutdown the server on SIGINT and gracefully close all the connection with proper events for the clients.

I have an issue gracefully closing the server while some socket.io clients are connected to the instance. In that case, in fact, the `fastify-graceful-shutdown` always times out. Debugging the close flow I can be pretty sure that the `fastify.server.close(cb)` callback is never called. 

You can reproduce the issue here: https://codesandbox.io/p/devbox/socketio-close-stuck-jlcglp, by following these steps:

- Start the server on a terminal with `npm start`
- Start another server and run `node client.js`
- Try close with CTRL+C the first terminal: the shutdown process will time out.

A possible workaround is this:
```javascript
  fastify.addHook('preClose', () => {
    fastify.io.local.disconnectSockets();
  });
```

But then I can't use `onClose` hook in order to forward close events to my sockets (since they are already disconnected).
Since it is very crucial for my application to gracefully shutdown the server I didn't know if this issue can be opened on [socket.io](https://github.com/socketio/socket.io), [fastify-socket.io](https://github.com/ducktors/fastify-socket.io) or fastify itself.

## Your Environment

- *node version*: 20
- *fastify version*: >=4

**Comment by giovanni-bertoncelli** [comment]
Maybe in this case it is more useful to use `preClose` in order to handle socket.io leave and disconnection?

**Comment by kibertoad** [comment]
Why don't you add websocket closing to `fastify-graceful-shutdown` hook?

**Comment by mcollina** [comment]
Note that fastify-socket.io and fastify-graceful-shutdown are not core plugins, and they look like they have a bug.

**Comment by kibertoad** [comment]
@mcollina How is that a bug? graceful-shutdown waits for app to finish closing everything, and it doesn't seem like this closing logic is added anywhere.
See https://www.npmjs.com/package/fastify-graceful-shutdown documentation, it's possible to add whatever is needed inside graceful shutdown flow.

**Comment by mcollina** [comment]
fastify-socket.io is missing this logic https://github.com/fastify/fastify-websocket/blob/431cba461f0bdd133d607deee6cfc56b69ea379a/index.js#L155-L172.

**Comment by Uzlopak** [comment]
How about implementing a preClose hook into core?

**Comment by climba03003** [comment]
> How about implementing a preClose hook into core?

It's already there. It just forgotten to remove the comment.

**Comment by giovanni-bertoncelli** [comment]
> fastify-socket.io is missing this logic https://github.com/fastify/fastify-websocket/blob/431cba461f0bdd133d607deee6cfc56b69ea379a/index.js#L155-L172.

Ok then maybe it's the case to open an issue on fastify socket.io in order to close sockets on preclose?

**Comment by mcollina** [comment]
As I said, it's a bug in ecosystem modules ;). Yes, you should open a bug there.

**Comment by giovanni-bertoncelli** [comment]
Ok, done. To be clear, @mcollina is there any issue even with `fastify-graceful-shutdown` or is it fine?
If not, I'll close this.

**Comment by mcollina** [comment]
I don't know of any issues in fastify-graceful-shutdown. However I would recommend against it.
Use https://github.com/mcollina/close-with-grace

**Comment by kibertoad** [comment]
@mcollina Can we have a fastify wrapper for close-with-grace, or maybe just bake it into core fastify?

**Comment by giovanni-bertoncelli** [comment]
> @mcollina Can we have a fastify wrapper for close-with-grace, or maybe just bake it into core fastify?

Agree.. That would be great!

**Comment by mcollina** [comment]
> @mcollina Can we have a fastify wrapper for close-with-grace, or maybe just bake it into core fastify?

One of Fastify greatest attributes is that it does not modify globals or modify the runtime in any way.
Those tools cannot be instantiated multiple times, so they are better set up in the entry point of your application.

I think this is baked in fastify-cli and platformatic.
