### ISSUE TITLE
How to send data from fastify to nextjs

### ISSUE THREAD

**Issue by jibin2706** [fastify/help#99]
`
fastify.get('/a', (req, reply) => {
        return app.render(req.req, reply.res, '/a', req.query).then(() => {
          reply.sent = true
})
`

**Comment by RafaelGSS** [comment]
Sorry, I don't understand correctly what you want. Can you provide a description and the reproduction code?

**Comment by StarpTech** [comment]
This issue is not fastify related. You pass data to next.js with the 3rd argument of the render method. In your example you pass all query params to next.js. Please always try to be more specific in your issues otherwise nobody can or will invest in it.
