### ISSUE TITLE
Dynamic validation-and-Serialization inside handler

### ISSUE THREAD

**Issue by cherimo** [fastify/help#990]
At the moment I use Validation-and-Serialization method to validate my parameters and body input.
This works great.

Unfortunately I also have fields validation that are quite dynamic. These are field lines that are loaded from the database when the user submits the form.
Is it possible to perform this validation within the handler itself instead of from the router?

Or do I have to write a separate script for this?

**Comment by mcollina** [comment]
as long as you validate your data, do it when you want. It would be a little bit less efficient in that case.

**Comment by cherimo** [comment]
Normally you would have somthing like this:

```
    const schema = ...

    fastify.post('/submit', { schema } ,(req, reply) => {
        console.log("Submit passed")
        reply.send(req.body)
    });
```

What I was searching for was something like functionB example.

```
    fastify.post('/submit' ,(req, reply) => {

        const functionA =  ... //Connection to DB for form input/data and parse the DB input to a valid schema

        const functionB = ... //Run a validation-and-Serialization function here with the dynamic schema(from functionA) and the req.body

        if(functionB == passed){
          reply.send(...passed text)
        }else{
          reply.send(...error text)
        }

    });
```

Is this somthing that validation-and-Serialization supports(Called withing a handler) ?

**Comment by mcollina** [comment]
You can have a custom serializer, but not a custom validator.

**Comment by Eomm** [comment]
I think it is doable with: https://fastify.dev/docs/latest/Reference/Request/#validate
