### ISSUE TITLE
fastify-plugin: fastify-static - expected '3.x' fastify version, '4.26.0' is installed

### ISSUE THREAD

**Issue by samprasdsouza** [fastify/help#991]
## 💬  Question here 

FastifyError [Error]: fastify-plugin: fastify-static - expected '3.x' fastify version, '4.26.0' is installed

```js
// example codes if any
   "@fastify/cors": "^9.0.1",
    "@fastify/postgres": "^5.2.2",
    "dayjs": "^1.11.10",
    "fastify": "^4.26.0",
    "fastify-auth0-verify": "^2.0.0",
    "fastify-axios": "^1.2.8",
    "fastify-oas": "^3.0.8",


````

## Your Environment

- *node version*: 20
- *fastify version*: 4.26.0
- *os*: Mac
- *any other relevant information*

**Comment by mcollina** [comment]
fastify-static is deprecated, use `@fastify/static`.

**Comment by mcollina** [comment]
fastify-oas is not maintained anymore. Use `@fastify/swagger`.
