### ISSUE TITLE
Static Resource Streams Closing Prematurely

### ISSUE THREAD

**Issue by paul-norman** [fastify/help#993]
I'm using Fastify to serve a traditional website (server side rendering EJS templates) and have noticed that when loading static resources (JS, CSS, images etc) that the streams are (seemingly) randomly closed prematurely:

```sh
[11:29:22 UTC] INFO (16252): incoming request {"reqId":"req-8","req":{"method":"GET","url":"/favicons/android-icon-192x192.png","hostname":"localhost:4001","remoteAddress":"127.0.0.1","remotePort":63865}}
[11:29:22 UTC] INFO (16252): stream closed prematurely {"reqId":"req-8","res":{"statusCode":200}}
````

the same request only seconds later may succeed:

```sh
[11:29:24 UTC] INFO (16252): incoming request {"reqId":"req-a","req":{"method":"GET","url":"/favicons/android-icon-192x192.png","hostname":"localhost:4001","remoteAddress":"127.0.0.1","remotePort":63882}}
[11:29:24 UTC] INFO (16252): request completed {"reqId":"req-a","res":{"statusCode":304},"responseTime":1.5665999948978424}
````

This happens locally (rarely) and live (frequently). I have solved the live issue by using Nginx to serve all static files, but obviously this method should also work.

I believe that this is likely an error due to my mixing `@fastify/static` with `@fastify/compress`, but these are both added (autoloaded) pretty much by the book:

```js
'use strict';

import fp from 'fastify-plugin';
import fastifyCompress from '@fastify/compress';

export default fp(async function (fastify, opts) {
	fastify.register(fastifyCompress, {
		global: true
	});
});
```

```js
'use strict';

import fp from 'fastify-plugin';
import fastifyStatic from '@fastify/static';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __file__	= fileURLToPath(import.meta.url);
const __dir__	= dirname(dirname(__file__));

export default fp(async function (fastify, opts) {
	fastify.register(fastifyStatic, {
		root: join(__dir__, 'public')
	});
});
```

I looked at a [related issue](https://github.com/fastify/fastify-compress/issues/215#issuecomment-1210598312) which was solved by ensuring that the reply was returned correctly, but my understanding of Fastify is still too low to know exactly what I'm looking for in the plugin code to see if this is the issue here too.

If there's anything that I'm doing wrong so as to avoid this bug it would be great to know it. Apologies for not providing a minimal, reproducable example, but this error is random (99% of the time static resources load correctly) and testing it depends upon having some static files on the system.

## Environment

- *node version*: 21.5.0
- *fastify version*: 4.26.0
- *os*: Windows 11, Ubuntu 22.04
- *relevant plugins*: 
  - @fastify/static: 6.12.0
  - @fastify/compress: 6.5.0

**Comment by mcollina** [comment]
There might well be a problem somewhere, as both those modules do some tricky logic. Frankly, I've always put an nginx or cdn in front of Fastify, and I've never experienced this problem, and I usually don't turn on compression in Node.js, as it introduce too much load on the server. This being said, I'll be happy to look into it if you provide a reproduction.

**Comment by paul-norman** [comment]
Thanks for the quick reply! If it's best practice to pop something in front of Fastify then I'll just do that, it makes sense to use something specifically designed for that task anyway.
