### ISSUE TITLE
Setting `secure` Cookie Option Prevents My Cookies From Working

### ISSUE THREAD

**Issue by paul-norman** [fastify/help#994]
I am new to Fastify so this is likely user error, but I can't seem to be able to have cookies use the `secure` flag to enforce they're used only over SSL. I wish to use Redis sessions, so autoload in the config:

```js
'use strict';

import fp from 'fastify-plugin';
import session from '@fastify/session';
import RedisStore from 'connect-redis';

export default fp(async function (fastify, opts) {
	const { redis } = fastify;
	let redisStore = new RedisStore({
		client: redis,
		prefix: 'session:',
	});

	const options = {
		store: redisStore,
		resave: false,
		saveUninitialized: false,
		secret: fastify.config.SESSION_SECRET,
		cookie: {
			//path:		'/',
			//domain:	fastify.config.SITE_FQDN,
			secure:		false, //fastify.config.NODE_ENV === 'production',
			//httpOnly:	true,
			//sameSite:	true,
		},
	}

	fastify.register(session, options);
});
````
*(I also load in the cookie plugin prior to this)*

This all works, but I'd like to be able to conceptually uncomment everything there on the live server and have the session cookies locked down a little more than they are. However, if I do that I don't get any cookies / sessions at all.

At Nginx level, I'm doing the bare minimum really:

```sh
server {
	listen		443 ssl http2;
	listen		[::]:443 ssl http2;
	server_name	www.example.com;
	root		/var/www/www.example.com/public;
	
	include		server.d/expires.conf;	# Public file handling
	include		server.d/hidden.conf;	# Secure hidden files
	include		ssl.d/example.com.conf;	# SSL certs
	
	location / {
		proxy_pass		http://127.0.0.1:4001/;
		proxy_set_header	Host $host;
		proxy_set_header	X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}
```

Any help would be appreciated; I'd imagine that this is something obvious / remedial that I've messed up.

## Your Environment

- *node version*: 20.11.0
- *fastify version*: 4.26.0
- *os*: Ubuntu 22.04
- *webserver*: Nginx 1.18.0

**Comment by mcollina** [comment]
I think you'll
need the x-forwarded-proto header.

https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/

**Comment by paul-norman** [comment]
You are absolutely correct, that header fixed it completely:

```sh
location / {
	proxy_pass		http://127.0.0.1:4001/;
	proxy_set_header	Host $host;
	proxy_set_header	X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header	X-Forwarded-Proto https;
}
```

Thank you very much!
