### ISSUE TITLE
how to receive ndjson?

### ISSUE THREAD

**Issue by Calemy** [fastify/help#998]
#### What are you trying to achieve, or the steps to reproduce?
I'm trying to receive ndjson from meilisearch's new webhook feature which states the following in documentation
"he request body will be one or more task objects in [ndjson](https://github.com/ndjson/ndjson-spec) format"
everything i do is currently not working and resulting in me getting a 415. i've been searching for parsers but had no luck.

#### Context

* *node version*: 18.18
* *fastify version*: >= 4.26.1
* *os*: Linux Ubuntu 22.04

**Comment by mcollina** [comment]
What content-type is Mellisearch sending ndjson as?

**Comment by mcollina** [comment]
Something like this would work:

```
const split = require('split2')
fastify.addContentTypeParser('application/x-ndjson', function (request, payload, done) {
  const logs = []

  // handle errors in split
  request.pipe(split(JSON.parse))
    .on('data', (log) => logs.push(log))
    .on('end', done)
    .on('error', done)
})
```

**Comment by Calemy** [comment]
i get request.pipe is not a function, did i forget to add anything?

**Comment by Eomm** [comment]
Try `payload.pipe(split(JSON.parse))...` or `request.raw`

**Comment by Calemy** [comment]
well now it's just that the json parser can't parse it properly:
"Unexpected token \u001f in JSON at position 0"

**Comment by mcollina** [comment]
Well, that does not look like encoded in ndjson.

**Comment by Calemy** [comment]
seems that the encoding is in gzip that contains ndjson.
I've written another example in the Meilisearch repository (https://github.com/meilisearch/meilisearch/issues/4449).
Maybe i've made an error somewhere but i really do not know what could be the issue.

**Comment by mcollina** [comment]
Then you need to add https://www.npmjs.com/package/@fastify/compress if they set the correct content-type headers.

**Comment by Calemy** [comment]
i already did that exact thing like i did in the example written in the meilisearch repository.
it's still throwes me an undefined body. am i using it wrong?

**Comment by mcollina** [comment]
paste your code

**Comment by Calemy** [comment]
```js
import "dotenv/config"
import { fastify as f } from "fastify"
import compress from "@fastify/compress"
const fastify = f({ logger: true, trustProxy: true })

fastify.register(compress) //adds support for gzip

fastify.addContentTypeParser('application/x-ndjson', function (request, payload, done) {
    done()
})
fastify.addHook("onRequest", (req, reply, done) => {
    //* MeiliSearch please add a content-type :(
    if(req.headers["user-agent"].includes("ureq/")){
        req.headers["content-type"] = "application/x-ndjson"
    }
    done()
})

fastify.post("/api/update", (req, reply) => {
    console.log(req.body) // returns undefined
    return "ok"
})

fastify.listen({ host: "0.0.0.0", port: process.env.port }
```

**Comment by mcollina** [comment]
You still need the ndjson parsing logic. You've removed that.

**Comment by Calemy** [comment]
what exactly am i supposed to parse and how? the body is undefined and everything else mentioned here tells me that this is not the right format

**Comment by mcollina** [comment]
@irevoire if you can produce a curl command that reproduces the exact payload mellisearch is going to send, I can verify if this works:

```js
import "dotenv/config"
import { fastify as f } from "fastify"
import compress from "@fastify/compress"
const fastify = f({ logger: true, trustProxy: true })

fastify.register(compress) //adds support for gzip

// adds parsing of ndjson
fastify.addContentTypeParser('application/x-ndjson', function (request, payload, done) {
  const logs = []

  // TODO handle errors in split
  request.pipe(split(JSON.parse))
    .on('data', (log) => logs.push(log))
    .on('end', () => done(null, logs))
    .on('error', done)
})
fastify.addHook("onRequest", (req, reply, done) => {
    //* MeiliSearch please add a content-type :(
    if(req.headers["user-agent"].includes("ureq/")){
        req.headers["content-type"] = "application/x-ndjson"
    }
    done()
})

fastify.post("/api/update", (req, reply) => {
    console.log(req.body)
    return "ok"
})

fastify.listen({ host: "0.0.0.0", port: process.env.port }
```

**Comment by irevoire** [comment]
Hey, so two things:


### The exact kind of payload being sent by meilisearch

I ran `nc -l 9000` and then meilisearch just to get the exact content sent by meilisearch:
```
POST / HTTP/1.1
Host: localhost:9000
User-Agent: ureq/2.9.1
Accept: */*
Content-Encoding: gzip
accept-encoding: gzip
Transfer-Encoding: chunked

d8
}j1
^:Zj\D~}Mqcڨ<a~#q=w螖?E/;D
0
```

Note: The payload has been escaped to be displayed in the terminal, so don’t try to copy-paste it somewhere. It won’t work.

### A minimal request that works

Here’s the minimal curl request that gets accepted by my binary:
```bash
% echo '{ "hello": "world" }' | gzip > payload.gz 
% curl -X POST -H "Content-Encoding: gzip" -H "Accept-Encoding: gzip" http://localhost:9000/ --data-binary @payload.gz
```

Could the issue be related to the `Transfer-Encoding: chunked` thingy?

**Comment by jsumners** [comment]
> Hey, I don’t know what’s going on here; sorry, I’m terrible with JavaScript and don’t really understand anything.
> 
> But I hand-crafted the smallest repository possible with zero magic involved [here](https://github.com/meilisearch/meilisearch-webhook-usage-example)
> 
> Maybe that’ll help you understand the minimum requirements to receive our payload and help @Calemy accordingly.
> 
> Thanks for your support 🙏

In other words, that API does not stream ndjson. It streams gzip data:

```js
func handleStream(stream) {
	const gunzip = require('node:zlib').createGunzip()
	gunzip.pipe(/* split */).on('data', line => { /* do stuff with line */ })
	stream.pipe(gunzip)
}
```

**Comment by mcollina** [comment]
The following works:

```js
import { fastify as f } from "fastify"
import compress from "@fastify/compress"
import split from "split2"

const fastify = f({ logger: true, trustProxy: true })

await fastify.register(compress) // adds support for gzip

// adds parsing of ndjson
fastify.addContentTypeParser('application/x-ndjson', function (request, payload, done) {
  const logs = []

  payload.on('data', console.log)

  // TODO handle errors in split
  payload.pipe(split(JSON.parse))
    .on('data', (log) => logs.push(log))
    .on('end', () => done(null, logs))
    .on('error', done)
})

fastify.post("/api/update", {
  onRequest: (req, reply, done) => {
    // Force content-type to be application/x-ndjson
    req.headers["content-type"] = "application/x-ndjson"
    done()
  }
}, (req, reply) => {
    console.log(req.body)
    return "ok"
})

fastify.listen({ host: "0.0.0.0", port: process.env.port || 3000 })
```

Thanks for providing how to repropduce.

**Comment by mcollina** [comment]
Here is a more idiomatic version with the correct error handling:

```js
import { fastify as f } from "fastify"
import compress from "@fastify/compress"
import split from "split2"
import { pipeline } from "stream/promises"

const fastify = f({ logger: true, trustProxy: true })

await fastify.register(compress) // adds support for gzip

// adds parsing of ndjson
fastify.addContentTypeParser('application/x-ndjson', async function (request, payload) {
  const logs = []

  await pipeline(payload, split(JSON.parse), async function (stream) {
    for await (const log of stream) {
      logs.push(log)
    }
  })

  return logs
})

fastify.post("/api/update", {
  onRequest: (req, reply, done) => {
    // Force content-type to be application/x-ndjson
    req.headers["content-type"] = "application/x-ndjson"
    done()
  }
}, (req, reply) => {
    console.log(req.body)
    return "ok"
})

fastify.listen({ host: "0.0.0.0", port: process.env.port || 3000 })
```
