### ISSUE TITLE
Aborted requests for streams & deprecation notice

### ISSUE THREAD

**Issue by EDjur** [fastify/help#999]
## 💬  Aborted requests for streams & deprecation notice

Hi 👋 

I'm running into the exact same issue as described in https://github.com/fastify/help/issues/607. That seems to have been fixed but I'm afraid that it might not work with newer Node.js versions since `aborted` has been deprecated meaning it has stability 0:

`Stability: 0 - Deprecated. The feature may emit warnings. Backward compatibility is not guaranteed.`

So even with the fix in the above issue, Fastify will throw the error rather than just log it for me when I abort a request from the Browser. If I add a simple check for `destroyed` instead which is the recommended property to check for, Fastify will log the error and **not** throw it, which is the desired behaviour.

Thank you!

## Your Environment

- *node version*: 20.11.0
- *fastify version*: 4.26.0
- *os*: Mac, Linux

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by EDjur** [comment]
Makes sense. I'll see if I can make an MRE. But basically all I'm doing is aborting a request from the browser, which then throws an error instead of just logging it because it doesn't enter the conditional here: https://github.com/fastify/fastify/blob/main/lib/reply.js#L720

But I'll try to find some time to set something up.

**Comment by climba03003** [comment]
Note that `.destroyed` is not a replacement of `.aborted`.
Although it is mentioned in the document but when you test the two properly, they behave very different.

**Comment by EDjur** [comment]
Thanks @climba03003 for that insight!

Then Node needs to change their docs a bit 🙃 

Still havent found time to create an MRE but will try to find some...
